### ISSUE TITLE
Remove HTML rendering from CodeFileRenderer

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#1007]
CodeFileRenderer is supposed to be a plain-text renderer. I've missed this in review and we've added rendering HTML doc spans to it, they should move to `CodeFileHtmlRenderer` instead.

**Comment by pakrym** [comment]
This breaks diffs as well. Because doc spans are included in the plain-text representation diff goes a bit crazy:

![image](https://user-images.githubusercontent.com/1697911/93498063-1fdcd280-f8c6-11ea-8e45-d6c42eac6d8b.png)

**Comment by praveenkuttappan** [comment]
I will submit a PR now.


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
