### ISSUE TITLE
Include the Track 1 JS auxiliary packages in various tooling

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#1024]
Below are the repos for the TS code generator and the auxiliary packages that our team owns to support Track 1 auto generated JS packages (both data plane and management plane)
- https://github.com/Azure/autorest.typescript
- https://github.com/Azure/ms-rest-js
- https://github.com/Azure/ms-rest-azure-js
- https://github.com/Azure/ms-rest-nodeauth
- https://github.com/Azure/ms-rest-browserauth

We need to include these GitHub repos in the below automation we have around repo management
- bot to add the `customer-reported`, `needs-triage`, `needs-team-attention` and `needs-author-feedback` labels as needed
- daily emails on newly logged issues, PRs and issues that need team attention

@AlexGhiondea, Who would be the right person to help with this?

**Comment by ramya-rao-a** [comment]
@weshaggard, @praveenkuttappan, @kurtzeborn Any concerns with the above?

**Comment by weshaggard** [comment]
If we need to keep track of those issues I have no concerns with us on-boarding the issue management for those repos. @AlexGhiondea is usually the one that manages the issue tracking stuff so he can probably help on-board those repos or point you to correct documentation, part of it is at https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/316/FabricBot-config.  

One other option we could consider is to turn off issues for those repo's and redirect them to file issues in this repo with the appropriate labels.

**Comment by ramya-rao-a** [comment]
cc @mitchdenny

**Comment by AlexGhiondea** [comment]
I'm happy to onboard the repos in the bot infrastructure that we have.
I think @mitchdenny can help with the email reporting side.

**Comment by mitchdenny** [comment]
Yep ... e-mail reporting is easy. Do we have a mapping of aliases to repos (maybe ping me an e-mail privately on that one).

**Comment by ramya-rao-a** [comment]
@AlexGhiondea I recall that we talked to the Office Bot folks to enable the bot in the above repos. Am guessing we have to create the labels in these repos for the bot to start working?

**Comment by ramya-rao-a** [comment]
cc @joheredi

**Comment by kurtzeborn** [comment]
Hey, @AlexGhiondea, just double checking that you finished onboarding these.  If you have, please close.

**Comment by ramya-rao-a** [comment]
Yes, this has been done. Thanks!
