### ISSUE TITLE
Per repository config caching could be causing increased GitHub calls

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#1027]
This method:
https://github.com/Azure/azure-sdk-tools/blob/655003f0dd3f234a2f0f3d464aece57cd3bff629/tools/check-enforcer/Azure.Sdk.Tools.CheckEnforcer/Configuration/RepositoryConfigurationProvider.cs#L29

Caches repository configurations to GitHub. Consider the hypothetical scenario where we trigger an abuse limit on GitHub and we need to back off for 60 seconds. The cache duration for this method is 60 seconds also. Would this mean that as soon as we get an abuse limit reached everything backs off, the cache expires then every event needs to fetch this configuration again because the caching extension offers no stampede compensation.

Seems like this would mean we reach the abuse threadhold faster (at worst) and simply take longer to process requests (at best).

**Comment by kurtzeborn** [comment]
This can be closed because of another mitigation @mitchdenny put in.
