### ISSUE TITLE
Retire use of TargetVariable 

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#1035]
Remove `TargetVariable` from [eng/common/pipelines/templates/steps/get-pr-owners.yml](https://github.com/Azure/azure-sdk-tools/blob/8703aa98ba4ed3778aaf1dc5592515344bc1b97e/eng/common/pipelines/templates/steps/get-pr-owners.yml#L2) after updating all the call to it to use `TargetUserVariable`

**Comment by weshaggard** [comment]
@chidozieononiwu I assume this is still interesting once you get back to https://github.com/Azure/azure-sdk-tools/pull/981, assuming we still plan to do that.

**Comment by chidozieononiwu** [comment]
eng/common/pipelines/templates/steps/get-pr-owners.yml  no longer exists.
