### ISSUE TITLE
Consider auto-marking Sync PRs within language repos with appropriate label and assign to tools PR author.

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-tools#1038]
Use `Central-EngSys` label to help with filtering and auto-assign to the author who submitted the PR, to help with notifications and visibility.

cc @weshaggard, @chidozieononiwu

**Comment by weshaggard** [comment]
Thanks for the feedback @ahsonkhan we definitely plan to do both of those things.

We also are working on a plan that enables us to test things before we open the Sync PR's so the PRs don't sit open nearly as long as they have been today.

**Comment by ahsonkhan** [comment]
Great to hear!

**Comment by chidozieononiwu** [comment]
This has been taken care of by https://github.com/Azure/azure-sdk-tools/pull/1102
