### ISSUE TITLE
Warning about no files to sign in .NET pipelines

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#1042]
```
##[warning] No files found to sign. You must double check your configuration for input file names or minimatch pattern *.dll-31bf3856ad364e35 to ensure they are correct. -- Warning
```

Since we have moved to unified pipelines I think we might have a way to skip this task ahead of time by setting a variable in our partitioning script that we can use as a condition in our signing steps.

**Comment by chidozieononiwu** [comment]
Fixed
