### ISSUE TITLE
When tool generated PRs get a new iteration, the labels get reverted

### ISSUE THREAD

**Issue by damirault** [Azure/azure-sdk-tools#1046]
When a tool generated PR gets a new iteration pushed, any manually added labels get removed.

The `AddLabels` function is really a PUT labels function, overwriting existing labels.
https://github.com/Azure/azure-sdk-tools/blob/1ea2117fad56bb34cfe1cc5b090a0c58ef7b18c2/eng/common/scripts/Submit-PullRequest.ps1#L61

Example of this happening:
![image](https://user-images.githubusercontent.com/5903571/94324449-c5d7af00-ff4e-11ea-9225-1c0717dacb41.png)
https://github.com/Azure/azure-sdk-for-net/pull/15285

**Comment by weshaggard** [comment]
I added some investigation in https://github.com/Azure/azure-sdk-tools/pull/1047#discussion_r495345532.

**Comment by sima-zhu** [comment]
We have to read the labels out from the api first and add the parameter together with original labels. I can make a quick fix for this. Assign to me for now. Let me know if anyone has started the work already.

**Comment by sima-zhu** [comment]
Fixed by #1056 
Closed the issue
