### ISSUE TITLE
Update subscription configurations to only mark a subset of values as pipeline secrets

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#1050]
[Edited by @benbp]

Updating this issue to reflect a larger solution.

Currently our subscription configuration objects include secrets. As a result, [our script](https://github.com/Azure/azure-sdk-tools/blob/e4689bdefa9511950eaf77ebd7fc710d01d4e7b2/eng/common/TestResources/build-test-resource-config.yml) marks all the JSON values in the config as secrets for the azure pipelines logs. This means that it's hard to figure out which subscription/resource group/etc. a test is targeted at (it gets logged as `***`). Also, some of the values in our sovereign cloud configurations are things like `"textAnalyticsSku": "S"`, which means that every `S` character in the log gets starred out.

We should update the subscription object configuration to be able to mark which values are secret and which aren't (possibly by using nested objects, or adding some sort of annotation/comment that we know how to parse). Subsequently, we should update the subscription configuration build/parse script to handle more fine grained marking of secrets.

[Original]
Today I tried to debugging a resource provisioning issue and I couldn't figure out which subscription was being targeted based on the logs in Devops. We should add some logging that can help us figure out the correct subscription and also add some logging around out to retrieve the deployment logs if a deployment fails. 

I believe the subscription Id ends up being a secret based on how we are setting up the variables so we can either fix that or at least dump out the keyvault name for which subscription configuration we are using to help debug issues.

**Comment by benbp** [comment]
Another consideration, given that there are many subscription configurations now managed by partner teams outside of our direct control, any approach we take will be ideally backwards compatible.
