### ISSUE TITLE
Link checker support for wildcards

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-tools#1071]
Currently, link checker allows for exceptions in ignore-links.txt.

This has the problem that, for instance for preview SDKs trying to use their pypi link, they must replace the absolute link every release (typically pulling the old link out of ignore-links as an additional step for cleanliness after the package releases)

If there was basic wildcard support this would be mitigated.  Full regex support might be (probably is) riskier than it's worth, but I'd be remiss to not mention it as an option to let it be as flexible as possible.  (e.g. if my link was `https://pypi.org/project/azure-servicebus/7.0.0b1/` it'd be nice to specify e.g. `7.0.0b[1-9]`)

**Comment by weshaggard** [comment]
@KieranBrantnerMagee can you help me understand what scenario you are trying to accomplish? If it is about having a direct versioned reference to a package then I'd suggest us the landing page that is not versioned as the link. That is also our recommendation in our [link guidance](http://aka.ms/azsdk/guideline/links)

**Comment by sima-zhu** [comment]
Discussed through team, which we'd better not introduce the link might out of date as the time going. So it is better to use the history page for the issue. Closed this issue for now. Please feel free to reopen if you have extra use cases.
