### ISSUE TITLE
Use Microsoft Graph for sending GitHub Issues reports

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#1076]
We are getting SPAM knockbacks via the SendGrid mail API in GitHub Issues so we need to switch to using Microsoft Graph for sending e-mails.

**Comment by mitchdenny** [comment]
Looks like SendGrid has unblocked us and things are flowing again. Closing this down for now, if this reoccurs we'll know what the issue is and we can invest in working around it. But if it isn't a regular problem it probably isn't worth it.

**Comment by weshaggard** [comment]
@mitchdenny do we have anything in place to detect that we are getting blocked and email isn't getting out?

**Comment by mitchdenny** [comment]
Not at the moment. Folks just tell us which is spotty coverage. SendGrid might send a webhook notification.

**Comment by mitchdenny** [comment]
https://sendgrid.com/docs/for-developers/tracking-events/event/#delivery-events
