### ISSUE TITLE
Invoke template live test pipeline as part of common tool sync process 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#1080]
Some common pipelines and scripts are related to live tests

**Comment by weshaggard** [comment]
@pakrym while I'm OK with this I'm curious if there was a particular issue we hit that prompted you to request this?

**Comment by pakrym** [comment]
https://github.com/Azure/azure-sdk-tools/pull/1077 PR required invocation of the live tests to verify things are still working. I did it manually but it would be nice if this aspect of common infrastructure was tested along with the release pipeline.

**Comment by weshaggard** [comment]
Cool does the live test pipeline for the template project do anything useful in .NET?

**Comment by pakrym** [comment]
Yes, the template is a trimmed down keyvault client with an actual template and test.

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/template/test-resources.json
https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/template/Azure.Template/tests/MiniSecretClientLiveTest.cs

**Comment by kurtzeborn** [comment]
Pretty sure @chidozieononiwu already enabled this.

**Comment by pakrym** [comment]
I don't think so. https://github.com/Azure/azure-sdk-tools/pull/1233#issuecomment-737533097 doesn't list any test pipelines being invoked.

**Comment by pakrym** [comment]
Awesome! Thank you @chidozieononiwu !
