### ISSUE TITLE
Refine artifacts name in blob storage used by github io to avoid the ambiguity of track 1 and track 2 

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#1094]
Github IO only stores packages name (e.g. azure-storage-blob) to imply track 2 documentation in blob storage. 
However, if we want to support both track 1 and track 2 packages, the naming convention will not work. 
Need to redefine the artifact name which includes group id to distinguish the differences.

**Comment by weshaggard** [comment]
Note this is currently only an issue for java where we use the artifact id which can be in conflict between track 1 and track 2. We should assume everything is track 2 and uses "com.azure" as the group id for now. If and when we need to publish github.io docs for java track 1 libraries we should add the group id as part of the publishing convention for github.io docs.

**Comment by kurtzeborn** [comment]
@mitchdenny

**Comment by mitchdenny** [comment]
Did some analysis of this in the Java repository. My method was that I opened up all ```pom.xml``` files and extracted the artifactId and then grouped by the artifactId. The only packages with a > 1 count were storage and some of the old management plane libraries (which version via group id).

Based on this I think we can safely close this for now. I don't think it is an immediate issue, and actually less likely to occur moving forward.
