### ISSUE TITLE
Bot not applying the right label sometimes for PRs

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#1099]
PRs in the azure-sdk-for-js repo for Metrics Advisors and Communication packages are not getting the right label applied to them even if they are mapped as expected in the [CodeOwners file](https://github.com/Azure/azure-sdk-for-js/blob/master/.github/CODEOWNERS)

Examples:
- https://github.com/Azure/azure-sdk-for-js/pull/11790
- https://github.com/Azure/azure-sdk-for-js/pull/11713

**Comment by weshaggard** [comment]
I believe this is because we haven't refreshed the data from the codeowners files. I know @AlexGhiondea  was planning to manually run it again but we should also have an issue (perhaps this one) to track running this on some cadence. @mitchdenny do we have anything else that is watching codeowners files that we could add this to? Or should we just use some scheduling system (DevOps or function) that will run it on some schedule?

**Comment by mitchdenny** [comment]
I know that the live test notifications hang off the ```CODEOWNERS``` file as well. How does the bot pick up its configuration @AlexGhiondea?

**Comment by weshaggard** [comment]
>I know that the live test notifications hang off the CODEOWNERS file as well. 

That is done by a daily Devops Pipeline that runs https://dev.azure.com/azure-sdk/internal/_build?definitionId=679. We could do something similar here or maybe create a combined one.

**Comment by kurtzeborn** [comment]
This appears to have been caused because the bot doesn't "refresh" after a change is made to CODEOWNERS files.  Let's use this issue to track implementing that refresh.

**Comment by mitchdenny** [comment]
@weshaggard yep ... I think it would make sense to create a combined job here for refreshing anything that is tied to the ```CODEOWNERS``` file. @AlexGhiondea is there a tool that you already have that refreshes the bot settings?

**Comment by ramya-rao-a** [comment]
Can we have the bot "refreshed" manually for now and then continue to use this issue to track anything else we want to do? I have a lot of incoming PRs with no labels that I have to manually go and apply labels now

**Comment by mitchdenny** [comment]
I've done the manual refresh for now.

**Comment by AlexGhiondea** [comment]
@mitchdenny are you asking about [this](https://github.com/Azure/azure-sdk-tools/tree/master/tools/CreateRuleFabricBot)?

If so, then yes, you can point that tool to the code owners file in each of the repos and it will update the configuration for the bot. I ran this before the holidays as there were some other changes that need to be refreshed.

**Comment by mitchdenny** [comment]
Yeah ... its just something that needs to be done regularly. I see you reached out to the FabricBot team to ask about alternative authentication schemes (I did as well, and got the same response).

**Comment by ramya-rao-a** [comment]
The manual refresh didnt seem to stick. See https://github.com/Azure/azure-sdk-for-js/pull/13121 which should have gotten the Mgmt label, but didnt

**Comment by ramya-rao-a** [comment]
Alright, am re-opening this

The below PRs should have gotten the Mgmt label, they didnt:
- https://github.com/Azure/azure-sdk-for-js/pull/13317
- https://github.com/Azure/azure-sdk-for-js/pull/13316

**Comment by ramya-rao-a** [comment]
This is driving me nuts! Please help!
Another set of PRs that should have gotten the Mgmt label, and they didnt
- https://github.com/Azure/azure-sdk-for-js/pull/13871
- https://github.com/Azure/azure-sdk-for-js/pull/13870
- https://github.com/Azure/azure-sdk-for-js/pull/13869
- https://github.com/Azure/azure-sdk-for-js/pull/13868
And more!

**Comment by mitchdenny** [comment]
Looks like the various arm-* rules failed because fabric bot doesn't know how to interpret them:

![image](https://user-images.githubusercontent.com/513398/116029496-d7c43080-a69c-11eb-9ad2-f05c7018dce2.png)

So we've got two feature asks on the Fabric Bot team:

1. service principal based authentication (or repo-based configuration)
2. support for globbing syntax in filters.

Without #1, someone on the EngSys team has to go in every single time a rule is updated. And without #2 we have to have a separate rule (no globs) for each of the arm-* folders (which exacerbates the first issue).

**Comment by AlexGhiondea** [comment]
I believe they are working on a better auth story.

**Comment by mitchdenny** [comment]
That isn't the last I heard so that is good news. Did the person you spoke to give you any kind of ETA (better auth also implies they are acknowledging the need for a supported API?)

**Comment by ramya-rao-a** [comment]
@praveenkuttappan Can we have the manual refresh done in a regular frequency? We have more services joining our repos and the codeowners files are getting updated, and the bot is not able to keep up

**Comment by praveenkuttappan** [comment]
@AlexGhiondea Do you have any wiki or any info on how to trigger this labeling bot manually?

**Comment by weshaggard** [comment]
IIRC the main issue is that the fabric bot didn't provide a proper rest API we could call so Alex hacks around it by using a local cookie to try and automate this but that isn't a good way to do this automatically. It is probably worth reaching out the the fabric bot folks to see if they have made any headway on supporting an api for updating the rules.

**Comment by AlexGhiondea** [comment]
What @weshaggard said is right. I have a tool that can update the rules for the bot, but it requires that we extract an auth token from a cookie. @praveenkuttappan I can show you how to do it if you want to give it a try!

**Comment by ramya-rao-a** [comment]
Hello (again)

I have given up waiting for a solution here and have added an entry for each mgmt plane package in the JS repo directly. Please see https://github.com/Azure/azure-sdk-for-js/pull/17060

Can we get the "refresh" done so that the bot starts applying the right labels?

**Comment by praveenkuttappan** [comment]
@AlexGhiondea I would like to know more about this tool so I can try it. I can also reach out to fabric bot team once I understand more about what/how we do it now.

**Comment by ramya-rao-a** [comment]
How is that refresh going?

**Comment by ramya-rao-a** [comment]
Not sure what happened... now none of the PRs are getting any labels :(

**Comment by AlexGhiondea** [comment]
@ramya-rao-a the refresh went fine... but now there aren't any labels associated with any paths... I'm reaching out to the bot team to see what's going on 🙂.

**Comment by ramya-rao-a** [comment]
This is me, just posting here, like I do every 2 weeks, wondering what to expect next... None of the bot labelling is working now :(

**Comment by ramya-rao-a** [comment]
What is the plan for manual refresh?

**Comment by benbp** [comment]
@praveenkuttappan has anyone considered contributing SP auth to the fabric bot?

**Comment by kurtzeborn** [comment]
Pretty sure this no longer matters now that we've moved away from FabricBot.

CC: @JimSuplizio

**Comment by JimSuplizio** [comment]
@kurtzeborn, you're right, if the CODEOWNERS file is correct the labels should be being applied. The problem was that FabricBot didn't directly use the CODEOWNERS file. There was a script that generated the FabricBot.json from the CODEOWNERS which apparently broke and they stopped using it and started updating CODEOWNERS files directly. Moving to actions and the github-event-processor now uses the CODEOWNERS files.
