### ISSUE TITLE
Bot should not consider customer reported PRs to be in invalid state due to lack of Client/Mgmt/bug/question/feature request labels

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#1107]
In the weekly email for customer reported issues in an invalid state, PRs are now being included.
Examples: 
- https://github.com/Azure/azure-sdk-for-js/pull/11868
- https://github.com/Azure/azure-sdk-for-js/pull/11777

Am guessing this is because the rules dont differentiate between PRs and issues?

While we can update the CodeOwners file to add the `Client` labels to PRs made to the data plane libraries, the other rule that looks for one of bug/question/feature-request labels does not apply to PRs

**Comment by ramya-rao-a** [comment]
cc @mitchdenny, @AlexGhiondea, @weshaggard

**Comment by mitchdenny** [comment]
I believe that this was addressed in PR: https://github.com/Azure/azure-sdk-tools/pull/1271
