### ISSUE TITLE
Add "SDK tools" for the "Create GitHub issue" drop-down in APIView

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-tools#1125]
The "Create GitHub issue" option on APIView is great.

However, it is missing the ability to open issues or feature request related to the APIView tool itself to the `azure-sdk-tools` repo:

For example:
![image](https://user-images.githubusercontent.com/6527137/96639255-4aabb380-12d6-11eb-93eb-8cfd24c8df8d.png)

For such comments, I ended up creating the issue manually: https://github.com/Azure/azure-sdk-tools/issues/1124

cc @JoshLove-msft, @pakrym

**Comment by pakrym** [comment]
I don't think we need this. After we fix issues with any particular language implementation there is no constant need of adding APIView bug reports.

**Comment by ahsonkhan** [comment]
Fair, will leave it up to you and Josh to close the issue as you see fit.
