### ISSUE TITLE
Resource ref checking is breaking the .NET aggregate reporting pipeline

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#1139]
This line:

https://github.com/Azure/azure-sdk-for-net/blob/d364650358200117be8d520673dd553777e1b136/eng/common/scripts/Verify-Resource-Ref.ps1#L10

Has started failing the aggregate reports pipeline:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=587616&view=logs&j=10327055-d4d6-50a6-a312-3d2cd4bd9cb9&t=a33e152e-60e8-56d0-5175-9f5dffee2552

The reason it started failing is this recent change:

https://github.com/Azure/azure-sdk-for-net/commit/39534754d42b496e784f8ab0b771bc5c05cfcd93#

The underlying issue is that our pipeline templates whilst possessing a ```*.yml``` file suffix are not in fact wellformed YAML. We seem to have gotten away with this up until this change came in because likes 93 and 95 in the change listed above are effectively a duplicate value from the YAML parsers point of view (since it doesn't see the expanded templates).

There are probably a couple of things that we could do here:

1. Tweak the ```archetype-sdk-tests-jobs.yml``` file to avoid this parsing issue.
2. Exclude some files from the search criteria.
3. Switch to a RegEx parsing method because we aren't in fact parsing YAML.
4. Instead of processing the files on disk pre-processing by Azure Pipelines, make use of the Azure DevOps endpoint [described here
](https://docs.microsoft.com/en-us/azure/devops/release-notes/2020/sprint-165-update#preview-fully-parsed-yaml-document-without-committing-or-running-the-pipeline) to get Azure Pipelines to process the files into YAML and then we read that in.

**Comment by weshaggard** [comment]
@benbp fixed this issue with https://github.com/Azure/azure-sdk-for-net/pull/16225.

**Comment by benbp** [comment]
@mitchdenny for item 4 I don't think you pasted the right link. Assuming you're referring to what I think you are, I've been looking into that already to make local development a bit easier. I don't think it would be too hard to have a PR gate for pipeline yaml that uses that API for validation before merge.

For the Verify-Resource-Ref script in question (which I have little context on), the global yaml validation seems to be a side effect of the main purpose, which is validating git URIs. I like the idea to switch to regex. I think it makes sense the move the "validate all yaml" functionality out of that script/pipeline step and into a separate one that uses the devops API.

**Comment by mitchdenny** [comment]
Updated link for #4.

**Comment by mitchdenny** [comment]
Actually ... @weshaggard  do even still need that verify-resource-ref script anymore? Seems like it was a point in time thing when we were cutting over to eng/common?

**Comment by weshaggard** [comment]
It is still useful for .NET and Java which still pulls templates in from the internal tools for signing purposes. Also there are some other side repos (i.e. azure-sdk, autorest.csharp, etc) that are importing templates via a repository reference and for those repos we probably should add this verification step. 

We do have automation for updating our tagging (https://github.com/Azure/azure-sdk-tools/blob/master/eng/pipelines/templates/steps/ref-updater.yml) and perhaps we should just move that validation into that pipeline.
