### ISSUE TITLE
Move eng/common workflow docs out of eng/common directory.

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#1155]
We should create a doc folder, which matches the convention of all the other repos, and put a MD file for the eng/common workflow there and then have the eng/common/README.md simply link to that MD and update all our workflow links to point to it as well. This will allow us to more easily tweak these docs without needing to go through a heavy testing and syncing process that we have in place for our eng/common changes.

**Comment by chidozieononiwu** [comment]
Fixe with https://github.com/Azure/azure-sdk-tools/pull/1178
