### ISSUE TITLE
verify-path-length.yml should report all files exceeding allowed length

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#1156]
`verify-path-length.yml` should report all files exceeding the allowed length, to make it easier to detect and fix all such files in one pass.  I believe the current logic is to keep track of the longest path seen so far, and only report files longer than this.  This looks like a bug or design flaw in the script.

https://github.com/Azure/azure-sdk-tools/blob/3782889cb96c310098435e8ce37d621adf29a526/eng/common/pipelines/templates/steps/verify-path-length.yml#L32-L45

**Comment by chidozieononiwu** [comment]
Fixed with https://github.com/Azure/azure-sdk-tools/pull/1158
