### ISSUE TITLE
Assign version bump pull request to build requestor

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#1173]
Whenever there is a release build that submits a pull request to bump the versions we should assign the PR to the person that queued the release build.

**Comment by weshaggard** [comment]
As part of this work we should also add the "auto-merge" label to the PRs.

**Comment by kurtzeborn** [comment]
@chidozieononiwu, I'm not sure, but I suspect you may have already added this support.

**Comment by chidozieononiwu** [comment]
No This hs not been implemented. It was only implemented for eng/common sync

**Comment by chidozieononiwu** [comment]
Show we restore `get-pr-owners.yml` which was retired in https://github.com/Azure/azure-sdk-tools/commit/70537f04b4c28e372977e5a79c656c2dd5997b27#diff-1a79bcf256e0c4fe5218f94e133f5de9ab6ec913de30643b3b2836cee876c9cb

**Comment by weshaggard** [comment]
@chidozieononiwu I'm not sure we should even do this any longer. I actually think having the code owners be added as reviewers to the version increment PR is likely better than the one who did the release.

**Comment by chidozieononiwu** [comment]
Closing this since GitHub code owners are already assigned.
