### ISSUE TITLE
Classification rule for test resource deployment failure in smoke tests.

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#1191]
Found an "unknown" failure in Pipeline Witness for a smoke test deployment failure. Our classifier is missing this scenario:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=611754&view=logs&j=f3570516-c8fe-5ce9-92b2-b737df25d5ea&t=4cd9f8c0-ceef-5c16-ba8a-2d031dabe732

Task display name: Deploy Smoke Test resources and prepare samples

**Comment by kurtzeborn** [comment]
No longer interesting now that we've changed how we do smoke tests.  Further, we'd leverage our new telemetry system in kusto rather than adding more classifications in webhook router.
