### ISSUE TITLE
Classification rule for ctest failures

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#1192]
These should be classified as test failures in Pipeline Witness:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=613767&view=logs&s=c7e06700-234c-563b-1296-f8014eb87576&j=b28a1a35-334b-5681-3876-e5562b5e8062

**Comment by kurtzeborn** [comment]
@danieljurek, when you're back, please sync with @mitchdenny on how to do this correctly.
