### ISSUE TITLE
Hide APIs with EditorBrowsable(Never) attribute applied.

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#1206]

**Comment by kurtzeborn** [comment]
Leaving this assigned to you @praveenkuttappan since we believe it's a problem with tokenization, not with UI.

**Comment by tg-msft** [comment]
I don't like the idea of just removing them because I have no idea how we'd safely ensure the new overload was versioned correctly.  At most I'd want an interactive mode to hide anything with [EB(Never)].

**Comment by maririos** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-tools/issues/3900
