### ISSUE TITLE
Support Cadl in APIView

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#1208]

**Comment by praveenkuttappan** [comment]
We will revisit the priority of this feature when we have more info on CADL timeline and this will also needs to go to CADL team for resources.

**Comment by tjprescott** [comment]
https://github.com/Azure/azure-sdk-tools/pull/4160

This has been completed.

**Comment by praveenkuttappan** [comment]
Reopening this to track integration within APIView to support creating manual API review for CADL.

**Comment by maririos** [comment]
> Reopening this to track integration within APIView to support creating manual API review for CADL.

Could we create a separate specific issue for this work?

**Comment by praveenkuttappan** [comment]
I will reopen 3604.

**Comment by praveenkuttappan** [comment]
Actually filed a new issue: https://github.com/Azure/azure-sdk-tools/issues/4306
