### ISSUE TITLE
[APIView] Inconsistent button styling

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-tools#1212]
This is just a nit issue, but it would be nice to refine: our buttons in APIView are not consistently styled in terms of their colours:

<img width="1055" alt="Reviews_-_apiview_dev" src="https://user-images.githubusercontent.com/1427840/99196144-51ebb180-27ef-11eb-9adb-fc705e7593a7.png">

<img width="957" alt="microsoft-opentelemetry-exporter-azuremonitor-1_0_0-beta_2-sources_jar_-_apiview_dev" src="https://user-images.githubusercontent.com/1427840/99196154-6760db80-27ef-11eb-95b9-3a4983a5264c.png">

To me, the 'bright' blue is the action button. For this reason, I think the languages bar is the wrong way around: the "Java" button is the only button that cannot be actioned, so it should be the dark blue, and the other languages should be the light blue. That also helps because the light blue has a hover effect which is useful to users.

The same applies to 'open / close' buttons - they should be the two-tone blue, rather than grey.

In terms of the discussion areas:

<img width="872" alt="microsoft-opentelemetry-exporter-azuremonitor-1_0_0-beta_2-sources_jar_-_apiview_dev" src="https://user-images.githubusercontent.com/1427840/99196241-0980c380-27f0-11eb-928e-248a4c1280b2.png">

I would right-align the 'Resolve' button and make it blue as well.

**Comment by praveenkuttappan** [comment]
This issue will become void when we modify the UI to completely remove language and other  buttons.

**Comment by chidozieononiwu** [comment]
Resolved in  https://github.com/Azure/azure-sdk-tools/pull/2785
