### ISSUE TITLE
C++ APIView - model types from the `::Models` namespace defined in the protocol layer, in between `::Details` aren't showing up

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-tools#1225]
Steps to reproduce:
```text
clang++ .\sdk\storage\azure-storage-blobs\inc\azure\storage\blobs.hpp -I .\sdk\storage\azure-storage-blobs\inc -I .\sdk\core\azure-core\inc -I .\sdk\storage\azure-storage-common\inc -I .\sdk\identity\azure-identity\inc -Xclang -ast-dump > az_blobs.ast
Compress-Archive az_blobs.ast -DestinationPath az_blobs.zip
Rename-Item az_blobs.zip -NewName az_blobs.cppast
```

We need `::Model` types to show up from all header files that have that namespace (notice there are `::Details` namespace before the `::Model` one):
https://github.com/Azure/azure-sdk-for-cpp/blob/ac09ee6f448032b0e51469afe7bac3b4df3b118c/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L26-L34

But only the `::Model` types from the following header show up, presumably because this file defines the entire namespace up front:
https://github.com/Azure/azure-sdk-for-cpp/blob/ac09ee6f448032b0e51469afe7bac3b4df3b118c/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/blob_responses.hpp#L12

![image](https://user-images.githubusercontent.com/6527137/99749002-803ceb80-2a92-11eb-815e-c61e3193d139.png)

A workaround, that happens to work, is moving the model types into their own separate header with a single namespace chain defined at the top. This is not an ideal long term solution though and APIView should be able to find and filter the correct  namespaces wherever they are defined.

rev0 is what is currently in master: https://github.com/Azure/azure-sdk-for-cpp/tree/801e072e421935a1ec205987b4df02002f54402d

rev3 is from https://github.com/Azure/azure-sdk-for-cpp/pull/1007 where the `::Model` types were moved to a separate header, and that worked as expected.

Look at the APIView listing (and the difference between rev0 and rev3: https://apiview.dev/Assemblies/Review/0534fb3ede9f4d22b53672d3d5cba9e1?diffRevisionId=4c685be2d51146729a9bac5ffdd71b35&doc=False

cc @praveenkuttappan, @katmsft, @Jinming-Hu

**Comment by ahsonkhan** [comment]
FYI @RickWinter, @vhvb1989

**Comment by praveenkuttappan** [comment]
So issue is when members in same namespace is declared in multiple header files. I will check how this is represented in ast by clang and fix it.

**Comment by praveenkuttappan** [comment]
@ahsonkhan @RickWinter I don't see AST node itself for models objects in ast file for model declarations in blob_rest_client.hpp,

clang++ .\sdk\storage\azure-storage-blobs\inc\azure\storage\blobs.hpp -I .\sdk\storage\azure-storage-blobs\inc -I .\sdk\core\azure-core\inc -I .\sdk\storage\azure-storage-common\inc -I .\sdk\identity\azure-identity\inc -Xclang -ast-dump > az_blobs.ast

I have checked language processor and it does handle declarations from multiple header files as long as it is present in AST dump file. Can you please check if include is proper to clang command?

**Comment by katmsft** [comment]
@praveenkuttappan What you posted is the command we use.
>  I don't see AST node itself for models objects in ast file for model declarations in blob_rest_client.hpp

Are you saying the structs defined in Models namespace within blob_rest_client.hpp are missing? If so, that's the issue we were trying to resolve.

**Comment by vhvb1989** [comment]
@praveenkuttappan  The issue is that defining a Details namespace makes any other APIs after it to be not part of the APIView info
