### ISSUE TITLE
Handle empty diff during eng/common sync.

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#1236]
In the out of use case scenario that changes are pre-maturely merged to one of the language repo, `azure-sdk-tools - sync - eng-common` will fail to submit PR for that language because of empty diff.
We should make the pipeline more robust such that it skips pull request creation for the language with the issue but continue with the rest.

**Comment by kurtzeborn** [comment]
At this point, if we were going to fix this we would have by now (or already have and didn't close this).  Closing...
