### ISSUE TITLE
Create backup strategy for live test pipeline secrets

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#1238]
We have several hundred secrets used for live test provisioning across the language SDKs (subscription/SP configs, connection strings, etc.). Currently these are persisted in two places: keyvault, and the cache that azure pipelines keeps for secret variables. It would be ideal if we had a backup keyvault or some other method to ensure it's harder to accidentally remove them.

**Comment by kurtzeborn** [comment]
While we haven't put a backup strategy in place for this, we did put a delete lock on the KeyVault used for live test pipelines.  Further, all KeyVault deletes are "soft deletes" which means you have 30 days to recover it before the data is lost.  It's actually super hard to delete a KeyVault and make it be "gone" instantly.  Like, I can't even do it in the UI at all to my knowledge. :)
