### ISSUE TITLE
APIView - Error updating to new model

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-tools#1245]
When clicking the "update model" link in the following ApiView, the following error is displayed:

https://apiview.dev/Assemblies/Review/fdeebdac9acf4e8f932b64aede1b8d55

Error.
An error occurred while processing your request.
Development Mode
Swapping to the Development environment displays detailed information about the error that occurred.

The Development environment shouldn't be enabled for deployed applications. It can result in displaying sensitive information from exceptions to end users. For local debugging, enable the Development environment by setting the ASPNETCORE_ENVIRONMENT environment variable to Development and restarting the app.

**Comment by maririos** [comment]
Error handling will be done with issue https://github.com/Azure/azure-sdk-tools/issues/3495
