### ISSUE TITLE
Email for customer reported issues in invalid state should not include PRs

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#1255]
The current email notification for customer reported issues in invalid state includes PRs which should not be happening. My guess is that this started happening ever since PRs started getting labels. This makes the report very noisy.

cc @AlexGhiondea @mitchdenny @weshaggard

**Comment by ramya-rao-a** [comment]
Today's email on customer reported issues in invalid state contained PRs as well.
I see #1271 is merged. Should anything else need to happen to deploy the fix?

**Comment by mitchdenny** [comment]
Hrm ... it should be deployed. Let me check.

**Comment by mitchdenny** [comment]
My bad, I timed out the final approval but when I went back to it misread it and thought it deployed! Fixing now.

**Comment by mitchdenny** [comment]
Deployed.
