### ISSUE TITLE
[Pipeline Witness] Track individual test failures

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#1267]
It would be very helpful for flaky tests prioritization point of view to have a list of individual failed tests.

@mitchdenny do you think it's possible to do with the current Pipeline Witness model?

One day we might evolve it into something that files flaky test issues automatically.

cc @maririos

**Comment by mitchdenny** [comment]
It is possible we can pull this off. In the event of a build failure, if we detect it is a test failure we make subsequent calls to Azure DevOps to interrogate the test results and then append them to the Scope string fields. Then, we can look at a report which effectively groups by that scope string and filters by test failure and it'll give you a picture of the biggest contributors to test failures.

**Comment by kurtzeborn** [comment]
Obsolete.
