### ISSUE TITLE
A whole bunch of direct urls present at the top of azure.github.io landing page

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#1284]
In https://azure.github.io/azure-sdk-for-java/, you can see a whole set of links right under the header of the page

![image](https://user-images.githubusercontent.com/16890566/102302099-20105c80-3f0d-11eb-872e-bbe0a337c6a1.png)

The same can be seen in other azure.github.io pages for JS, Python and .Net repos

**Comment by sima-zhu** [comment]
![image](https://user-images.githubusercontent.com/48036328/102392465-f2b6c380-3f8b-11eb-803b-fbe728318957.png)

**Comment by sima-zhu** [comment]
![image](https://user-images.githubusercontent.com/48036328/102392505-fe09ef00-3f8b-11eb-925a-331610fc4012.png)

**Comment by sima-zhu** [comment]
![image](https://user-images.githubusercontent.com/48036328/102392533-095d1a80-3f8c-11eb-9d98-19533b168eab.png)

**Comment by sima-zhu** [comment]
![image](https://user-images.githubusercontent.com/48036328/102392782-5fca5900-3f8c-11eb-9ed5-d969c6ff32ef.png)

**Comment by sima-zhu** [comment]
![Uploading image.png…]()

**Comment by sima-zhu** [comment]
Currently, cpp reset the branch protection which blocks us to update the gh-pages. I have contacted @ahsonkhan to help unblock this.

**Comment by ahsonkhan** [comment]
cc @RickWinter who might know more about any recent changes to the branch protection.

**Comment by sima-zhu** [comment]
![image](https://user-images.githubusercontent.com/48036328/102395925-9c984f00-3f90-11eb-9479-1a8073fef4f6.png)

C++ has removed the branch protection. Thanks! @ahsonkhan @RickWinter 

Closed the issue as we addressed the issue for all lang repo.
