### ISSUE TITLE
Verify-Links Fails against Twitter AzureSDK Link

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#1291]
[This PR](https://github.com/Azure/azure-sdk/pull/2175) adds an ignore link for our official azure sdk twitter account.

The failure to GET `https://twitter.com/AzureSDK` repros locally, which is kinda funny considering it's just a standard link.

`Invoke-WebRequest -Method GET -URI "https://twitter.com/AzureSDK"`

```
This browser is no longer supported.

      Please switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center.
```

So it seems like a UserAgent issue to me. Need to investigate and remove from the ignore list in azure-sdk.

**Comment by sima-zhu** [comment]
Looking

**Comment by sima-zhu** [comment]
The default userAgent is not working for twitter.
Switch to chrome userAgent is able to return the right response.
```
Invoke-WebRequest -Method GET -URI "https://www.twitter.com/AzureSDK" -UserAgent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36" 
```

**Comment by sima-zhu** [comment]
Options:
1. Pass the latest popular used userAgent from pipeline variable. If not set, then use the default PSUserAgent.

**Comment by sima-zhu** [comment]
Changes have been merged and remove the twitter link out of ignore lists. Closed the issue. Please feel free to reopen this if anything unaddressed.
