### ISSUE TITLE
Unable to update model for FormRecognizer API View

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-tools#1297]
Tried clicking update model on the [FormRecognizer API View](https://apiview.dev/Assemblies/Review/cf2c57b3d4c44ef08c2e8284f7441a2d).  I consistently get this error page.

![image](https://user-images.githubusercontent.com/21269347/103565872-f300fb00-4e75-11eb-8e53-b05435e6742b.png)

**Comment by annelo-msft** [comment]
@maririos FYI

**Comment by praveenkuttappan** [comment]
We no longer need to update review manually. Review is updated automatically when parser has new changes.
