### ISSUE TITLE
Update all pipelines to ubuntu-18

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#1321]
There are still a few pipelines in the `tools` repo using ubuntu-16:

https://github.com/Azure/azure-sdk-tools/search?q=ubuntu-16

These should all be upgraded to ubuntu-18, which is our current default version for Linux pipelines.

**Comment by kurtzeborn** [comment]
We should consider leapfrogging ubuntu-18 and go straight to ubuntu-20 instead.  DevOps has already started moving their linux-latest to ubuntu-20 already.
