### ISSUE TITLE
Provide method to upload output from apiserializer.py to ApiView

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-tools#1328]
It would be very useful to be able to run Johan's [swagger to ApiView tool](https://github.com/johanste/swapiview) and upload the output to ApiView for more easily reading a REST API from a swagger as a set of object oriented methods.

**Comment by annelo-msft** [comment]
@johanste FYI

**Comment by annelo-msft** [comment]
It appears that this used to be enabled, e.g. for the following APIView to have been created:
https://apiview.dev/Assemblies/Review/eb9f25835aba4535b57f31ea46025601

**Comment by pakrym** [comment]
Nope, that was a manual JSON upload. @johanste

**Comment by annelo-msft** [comment]
The crash I was seeing was due to an invalid output file from the tool.

**Comment by pakrym** [comment]
We should still integrate the tool

**Comment by praveenkuttappan** [comment]
We have some work in progress to support swagger review support in APIView. We can probably revisit this issue again if swagger review support is not good enough?

**Comment by praveenkuttappan** [comment]
I think we don't need this anymore since we added support for Swagger API review.
