### ISSUE TITLE
Publish nuget packages to our Azure Devops Feed 

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#1329]
Lets move all our pipelines that build nuget packages in this repository and publish to our older blob storage feed to instead publish to our Azure DevOps feed https://dev.azure.com/azure-sdk/public/_packaging?_a=feed&feed=azure-sdk-for-net

We also have some pipelines that publish to the "azure-sdk" Devops feed we should also update those to publish to the azure-sdk-for-net as well. 

FYI @mitchdenny @chidozieononiwu

**Comment by mitchdenny** [comment]
Which ones publish to the azure-sdk team? I know that Pipeline Generator publishes there.

**Comment by weshaggard** [comment]
Not sure which all ones do but whoever is using https://github.com/Azure/azure-sdk-tools/blob/master/eng/pipelines/templates/stages/archetype-sdk-tool-dotnet.yml#L46 is doing that. In any case we should stop doing that and we should probably create a template that publishes as well as does signing to the azure-sdk-for-net Azure devops feeds.

**Comment by mitchdenny** [comment]
I wonder if publishing ```Azure.Sdkk.Tools.PipelineGenerator``` to the ```azure-sdk-for-net``` feed is a little misleading though since as a tool it is more cross cutting than that. Yes ... it's a NuGet package but it isn't something explicitly related to the .NET SDK.

**Comment by weshaggard** [comment]
That is a fair question. I will say that anything that the azure-sdk-for-net repo needs that isn't on nuget.org needs to be put on the azure-sdk-for-net Azure DevOps feed. As for other packages we use for other places we could consider as separate feed but I suspect most of these tools are used by the .NET repo so I don't have an issue with them being on that feed.

**Comment by ctaggart** [comment]
Hey @chidozieononiwu, any progress on this? The pinned version of `Microsoft.Azure.AutoRest.CSharp` is only [available in the older blob storage](https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/registration/microsoft.azure.autorest.csharp/3.0.0-beta.20210504.1.json), which we can't use from our Azure build. We were able to add the Azure DevOps feed `azure-feed://azure-sdk/public/azure-sdk-for-net@Local` as an upstream feed, but `Microsoft.Azure.AutoRest.CSharp` isn't there yet.

**Comment by chidozieononiwu** [comment]
Closing this as we now publish to the DevOps feed.

**Comment by mikeharder** [comment]
@chidozieononiwu, @weshaggard: Should these lines be removed from our `NuGet.Config` now that this issue has been fixed?

https://github.com/Azure/azure-sdk-for-net/blob/49c7c6694e05e3c9fdb0183b1e969969cbc30bac/NuGet.Config#L9-L12

**Comment by chidozieononiwu** [comment]
Yes, I think we can remove that. Although I need to make sure there is no mgmt workflow still relying on that.

**Comment by weshaggard** [comment]
@chidozieononiwu I'm reopening this to track the work to remove the feed from https://github.com/Azure/azure-sdk-for-net/blob/main/NuGet.Config#L12.

**Comment by weshaggard** [comment]
Config removed with https://github.com/Azure/azure-sdk-for-net/pull/37435
