### ISSUE TITLE
Automatic version increment step removed older prerelease change logs

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#1330]
Automatic version increment tool runs code to update change log and this step has removed older change logs for JS storage-blob package. These old logs doesn't follow current SDK versioning guidelines and has prerelease versions without a prerelease numbers. Update change log sorts the versions and it expects as prerelease number for prerelease versions. If version doesn't have a prerelease number then it appends '0' as prelease number and this causes a mismatch when new change log is created in sorted order.

**Comment by weshaggard** [comment]
@chidozieononiwu I suspect we only do this parsing to enable sorting. We should do some work in the changelog scripts to just ignore these entries and leave them as-is if the entry doesn't match the version or date format that we have.
