### ISSUE TITLE
Extend Package Properties to include Package Track

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#1333]
Extend the `eng\common\scripts\Package-Properties.ps1` tool to include package tracks. Data, Client or Management plane.
Update `eng\common\scripts\Prepare-Release.ps1` to use that property rather than directly passing `$BuildType`

**Comment by weshaggard** [comment]
I believe @praveenkuttappan has already added this based on his apiview work.
