### ISSUE TITLE
Set up approval for github alias resolution service

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1340]
See internal email

~- [ ] Eliminate potential PII logging~
~- [ ] Set up appropriate ServiceTree information~
~- [ ] Obtain appropriate manager approval~

There is a hosted API that may fulfill this purpose instead of the approval process. 

https://github.com/microsoft/opensource-portal/blob/develop/docs/api.md#headers-and-parameters 

https://github.com/microsoft/opensource-portal/blob/develop/docs/api.md#get-a-specific-linked-user

**Comment by kurtzeborn** [comment]
This is done and we have a tool(s) for this now.
