### ISSUE TITLE
Pipeline Naming Resiliency for failure notifications

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1350]
We are starting to see pipelines whose names, when combined with differentiators like "Notifications" and "Sync Notifications" will exceed the max team name length ([docs](https://docs.microsoft.com/en-us/azure/devops/organizations/settings/naming-restrictions?view=azure-devops#teams))

Possible strategies: 

* Insert random characters at the beginning (e.g. 1a2b3c-<pipeline-name-shortened>) and trim the end
* Trim the end back n characters and insert n random characters at the end (e.g. <pipeline-name-shortened>-1a2b3c) -- This may help with sorting and searching

In any case: 

* Put the target pipeline name in the description YAML 
* Ensure that the process updates the description YAML so this is automatically applied next time the tool runs

**Comment by kurtzeborn** [comment]
This is done.  Ben changed it to use group ids.
