### ISSUE TITLE
Clean-up old left-behind pipelines

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#1381]
Over the last year or so since we started running our pipeline generation tools we have left behind a number pipelines that are either not needed or invalid now. These might be because of bugs in the tools or because files were renamed or deleted in the repos.

We should do some analysis and clean-up these pipelines which should help with some of our load on the system.

For example: https://dev.azure.com/azure-sdk/public/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=600 is a leftover pipeline after a ci.yml was renamed. We should delete or fix these invalid pipelines.

For context this came up while working with the DevOps team about another issue we were having and they were talking about all the exceptions they are logging in their databases for pipelines that weren't able to determine if they should be triggered or not because the ci.yml file couldn't be found. The more we can eliminate these exceptions in our pipelines the less likely they will interfere with our processing and diagnosing of issues.

**Comment by benbp** [comment]
I looked around for pipelines not run in the past 6 months, legacy directories, ones based on outdated files and/or deprecated repos, ones run against test branches or for personal projects, etc. etc. I didn't see any more instances of pipelines like the one linked in the issue description.

I cleaned up the following (soft delete for 30 days):

### Internal

js - servicefabric
js - operationalinsights
js - graphrbac
js - cognitiveservices
js - client
js - batch
js - applicationinsights
amqp-common-js
azure-sdk-for-node - client
net - client
python - client
Python-EventHubs_livetest
joheredi.azure-sdk-for-js
js - autorest.typescript (v4)
js - test-external
link-verification
pre-release.azure-openapi-validator
test-timeouts
tools - PoliCheck
VeryEarly.azure-sdk-for-net
java - client
java - tracing
java - applicationinsights
ios-pr - client
cpp - client
azure-storage-python - client
android-pr - communication
js - client - amqp-common
azure-sdk-for-net-lab

### Public

OAV Validate Examples Regression (latestSpecifications only)
qwordy.azure-cli
java - applicationinsights - ci
