### ISSUE TITLE
Version increment tool moves around existing sections in CHANGELOG.md

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-tools#1394]
We are seeing this behavior in Azure.Search.Documents service area.
Please see this PR as an example of an undesirable update - https://github.com/Azure/azure-sdk-for-net/pull/18670/

**Comment by tg-msft** [comment]
We should sort changelog entries by date rather than version because we can pull shenanigans like changing a package name/version, but I can't break spacetime.

**Comment by heaths** [comment]
Duplicate of #1389
