### ISSUE TITLE
Pipeline generator needs to support generating pipelines for main and master

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#1402]
As part of the [rename of master to main epic](https://github.com/Azure/azure-sdk/issues/1447), we will need to handle the final (all master branches are renamed to main) and intermediate (some master branches have been renamed) states of the transition. The Pipeline Generator tool, and pipelines that use the tool need to be adapted to handle this scenario.

I believe that the pipeline generator tool already allows for the creation of pipelines that trigger of ```refs/heads/main```, its just an argument on the command, but it might be necessary to just survey the code to double check. We'll certainly need to adjust the pipeline generation pipelines (main pipeline, single pipeline, and prepare pipelines variants) to do the right thing.

We also need to make sure that when the change occurs that we can use pipeline generator to "conform" all the pipelines to the main branch.

**Comment by sima-zhu** [comment]
Done.
