### ISSUE TITLE
ApiView: Include the package's dependencies

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-tools#1409]
I always have to ask "what other packages are you depending on" during reviews and it would be nice if we could add that information automatically from the NuGet/Maven/etc. package.  We're very strict about 3rd party dependencies and don't want anything sneaking in accidentally.

**Comment by tg-msft** [comment]
This isn't just for .NET - I'd like every language to include dependencies.  I think this should be a P0.

**Comment by JoshLove-msft** [comment]
I've added support for C#, but as far as all of the other languages go it is still an open issue.

**Comment by JonathanGiles** [comment]
Java has been doing this for quite some time, and I agree it is very useful:

![image](https://user-images.githubusercontent.com/1427840/177217254-2839959a-5b22-4704-8bd4-3ef8101d39f6.png)

**Comment by JoshLove-msft** [comment]
Unassigning myself as this would require language specific implementations for each language. It is currently supported for C# and Java.

**Comment by praveenkuttappan** [comment]
This has already been done.
