### ISSUE TITLE
[ApiView] - Option to disable system-generated comments

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-tools#1413]
Some API views may have too many system-generated warning/error messages that can make reviewing the APIs hard. There's an option to disable comments but that disables the comments from other API reviewers too. This is a new feature request to provide an option to disable system-generated comments only (like the one with missing JavaDoc comment below).

![image](https://user-images.githubusercontent.com/51379715/108188934-07672300-70c5-11eb-817b-7e4cadc323c2.png)

**Comment by praveenkuttappan** [comment]
@chidozieononiwu This is probably an easy one to tackle if we have different class for auto generated comments.
