### ISSUE TITLE
Update docs repo root README.md files to point to source of docs

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1414]
Currently the README.md files do not describe the source of overview docs. Changes to handwritten docs can be overwritten during automated publishing. Updates to those docs should go in the primary SDK source repos and not the docs repos.

**Comment by kurtzeborn** [comment]
Haven't gotten to this in 2 years.  Not a priority.  People know what to do and are no longer surpised when their edits are overwritten in these repos.
