### ISSUE TITLE
Link verification target branch is incorrect

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#1424]
While helping with another issue I noticed we have some cases where "SYSTEM_PULLREQUEST_TARGETBRANCH" ends up being set to `refs\heads\master` instead of `master`, which cause some issues when doing a diff.

See: https://dev.azure.com/azure-sdk/public/_build/results?buildId=739457&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0

We need to trim `refs\heads\` off the front of the target branch at https://github.com/Azure/azure-sdk-tools/blob/master/eng/common/scripts/get-markdown-files-from-changed-files.ps1#L5, similar to what @chidozieononiwu is doing in PR https://github.com/Azure/azure-sdk-tools/pull/1415.

**Comment by sima-zhu** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=743185&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0

Ci is working as expected. 

PR validation works as expected: https://dev.azure.com/azure-sdk/public/_build/results?buildId=743226&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0

Closed the issue. Feel free to reopen if more issues found.
