### ISSUE TITLE
Keep Sync PRs from Closing unrelated Issues

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#1444]
We should have some guidance/system that prevents arbitrary issues in the language repos from getting closed by sync Prs.

For example, the following azure-sdk-tools PR closed an unrelated issue in C++ because the PR description said it resolved it, particularly in the commit message itself. That resolution was only relevant to issues in the sdk-tools repo:

https://github.com/Azure/azure-sdk-tools/pull/1408
https://github.com/azure/azure-sdk-for-cpp/issues/1388

**Comment by chidozieononiwu** [comment]
Guess we have to tidy up the git patches before using them.

**Comment by kurtzeborn** [comment]
We've only ever hit this once.  It's a corner case and it doesn't do any irreversible harm.  Not fixing this just means that an issue in a language repo which is tracking a tools changes may get closed a little too eagerly before the change makes it all the way back to the language repo (by way of commit and mirror through the azure-sdk-tools repo).
