### ISSUE TITLE
Check-Enforcer should ignore prepare-pipelines pipeline checks when approving a PR

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#1464]
There have been at least one case where auto-merge was enabled on a PR for a new service and after they rand prepare-pipelines it check-enforcer turned green and the PR was merged before someone could actually trigger the new pipeline. It would be nice if we could have check-enforcer ignore prepare-pipelines. It might also be nice if we could have prepare-pipelines trigger the ci pipeline, if one is created, for the PR that triggered it.

**Comment by kurtzeborn** [comment]
We've never really baked in checks like this into the prepare-pipeline process.  Longer term, we're going to be working on pipeline v3 improvements which will make the concern tracked in this issue moot anyway.
