### ISSUE TITLE
Add ignore check option to Check Enforcer

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#1466]
We had a situation this week when a new module was being added to the SDK and the developer issued a ```/azp run prepare-pipelines``` command like expected. At the same time they set auto-merge on the PR. Unfortunately Check Enforcer took the ```prepare-pipelines``` check as a check that it should consider for passing the PR so the code automatically merged.

To stop this happening again, we need to add an option to the CHECKENFORCER configuration file that allows us to list the pipelines that we ignore for the purposes of evaluating check enforcer passing.

**Comment by weshaggard** [comment]
https://github.com/Azure/azure-sdk-tools/issues/1464 I filed the same issue earlier :)

**Comment by sima-zhu** [comment]
Found issues that new service module only run prepare-pipeline without triggering the corresponding generated ci pipeline. It is better to have the link-checker scan the new module before check in. If we cannot trigger the exact ci pipeline, can we have some reminder in check-enforcer to remind people to manually trigger the generated pipeline?

Example:
The release [pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=767239&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=bdeefc16-b669-5ebd-ad94-a2c19ade53b0) caught the broken links which checked in by initial PR [here](https://github.com/Azure/azure-sdk-for-java/pull/19635).

**Comment by mitchdenny** [comment]
Snap :) I'll close this one out.
