### ISSUE TITLE
Enable create-pull-request.yml to receive a file location for a commit message

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1473]
Currently the logic in `git-branch-push.ps1` used by `create-pull-request.yml` requires a string which is passed into the command. If this string does not appropriately escape certain characters the commit message might be invalid. Git can also use text in a file as the commit message ([docs](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--Fltfilegt)). 

This reduces the risk by eliminating the need to write escape logic which could have a bug in it that surfaces at a later date and blocks the commit and push step.

**Comment by kurtzeborn** [comment]
At this point, we're probably not got to get to this.  We're also talking about moving away from these scripts.
