### ISSUE TITLE
Consider overwriting the PR title in subsequent calls to Submit-PullRequest.ps1

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1474]
Today Submit-PullRequest.ps1 exits if a PR already exists. In the case of C++ we want to update open PRs with additional commits and, for each of those commits, add language to the PR title. While we can extract and modify the PR title in a previous step, it might make sense that the pipeline updates the PR title.

**Comment by chidozieononiwu** [comment]
Closing this after talking with @danieljurek

**Comment by danieljurek** [comment]
Functions for fetching and updating PRs already exist and those can be combined properly to match the desired business logic in the C++ release process. Changes to `Submit-PullRequest.ps1` that would support the scenario I envision above would be putting too much business logic inside `Submit-PullRequest.ps1`
