### ISSUE TITLE
Non-.NET package links do not reference tag URLs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#1482]
Some time back in .NET @chidozieononiwu and others worked on making sure our packages' links (on package pages like on nuget.org, as well as links within packages) are full tagged references. For example:

https://www.nuget.org/packages/Azure.AI.TextAnalytics/5.1.0-beta.5 refers to several tagged reference:
* Release notes: https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.TextAnalytics_5.1.0-beta.5/sdk/textanalytics/Azure.AI.TextAnalytics/CHANGELOG.md
* Project site (README): https://github.com/Azure/azure-sdk-for-net/blob/Azure.AI.TextAnalytics_5.1.0-beta.5/sdk/textanalytics/Azure.AI.TextAnalytics/README.md

Even links in the .nuspec within the .nupkg used tagged links.

For JavaScript, npmjs.org just references master:

https://www.npmjs.com/package/@azure/cognitiveservices-textanalytics/v/5.0.0-dev.20200108.1:
* Homepage: https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/cognitiveservices/cognitiveservices-textanalytics

Unfortunately, the real issue is that non-NuGet sites actually display the README (I wish NuGet would) so links therein are not tagged references and it would be hard to keep up to date (though not impossible - maybe just not worth it).

The advantage of linking to tagged sources is giving devs the right link to the source snapshot that corresponds to the packages, and ideally a link to documentation for that version of the package. That said, I know there was quite a bit of effort to at least make documentation better versioned, so while changing links within READMEs would be ideal but significantly harder, at least documentation is versioned.

**Comment by kurtzeborn** [comment]
In general, we don't link to specific packages when generating these docs because there's a chicken and egg problem.  Often the packages are not yet released or are being released at the same time and we don't know where to link.  So we usually just link to main.
