### ISSUE TITLE
Template packages in docs repo

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1494]
Template packages do not need to be released to the docs site, but they're useful for validating our release pipelines. Future work should take this into account and probably: 

* In the case of docs.ms -- where we're heading these changes will be checked directly into the docs main branch. Is there something we can do here to ensure that template ref docs don't go out? It's helpful to see what the changes would look like in an e2e test. Perhaps there's a way to ignore these or put them in a non-publishing place? 
* In the case of githubio -- Is there a way to ignore these in the ToC?

**Comment by sima-zhu** [comment]
github IO read from release csv. If `Hide=true`, then we do not display it in toc.
I believe current github pages have the right setup

**Comment by sima-zhu** [comment]
For docs.ms, our new approach is trying to sync with release csv, which filter out the package hide=true. It helps with this issue too.

**Comment by sima-zhu** [comment]
Template currently set 'Hide' to 'true'. Issue has been resolved. Closed the issue.
