### ISSUE TITLE
[check-enforcer] Require running smoke tests in PRs which modify samples

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#1497]
If a PR adds or modifies samples, the smoke-test pipeline should be included in PR verification, since the samples are used as smoke test sources.  It's easy for developers to miss this, so it would be good if `check-enforcer` or a similar tool could remind developers to run the smoke tests and/or block merging until they are green.

**Comment by kurtzeborn** [comment]
This doesn't really apply any more.  Most of the samples have been moved into unit tests which run nightly already.  Most of the smoke tests have been moved into the release process and what we do in smoke tests has changed a bunch since this was opened.
