### ISSUE TITLE
Docs repos should be re-generated by deterministic process

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1499]
Automation should be able to generate all necessary elements for a given docs repo from sources in the Azure SDK repo, package repositories, and data sources like the Azure [SDK CSV files](https://github.com/Azure/azure-sdk/tree/master/_data/releases/latest) 

This includes some work: 

* Move hand-written documents out of the docs repos, especially for legacy packages

**Comment by JimSuplizio** [comment]
@danieljurek, I'm closing this issue out as this isn't going to happen. As a matter of fact, [changes were made in June of 2023 to make the Json files the source of truth](https://github.com/Azure/azure-sdk-tools/pull/6273).
