### ISSUE TITLE
Enabling GitHub.io publishing for android repro

### ISSUE THREAD

**Issue by anuchandy** [Azure/azure-sdk-tools#1523]
Currently the GitHub.io publish for android ref doc is manually done, by locally running the script https://github.com/Azure/azure-sdk-for-android/blob/master/build_api_docs.sh and pushing to gh-pages branch. Can we can this as a pipeline run like for other languages.

**Comment by weshaggard** [comment]
related to https://github.com/Azure/azure-sdk-for-android/issues/487. We definition should try and get android onboarded to the standard publishing process.

**Comment by kurtzeborn** [comment]
Assigning this back to the client team for follow up.  The infrastructure is all in place for how and where to publish these.  We've done a lot of work to make the toolset and look and feel of our github.io docs across repos.  Once you have docs generating using the appropriate refdoc generation tools for our mobile languages, please work with @danieljurek to plug it into our systems and get them published.

**Comment by kurtzeborn** [comment]
Closing this duplicate issue.
