### ISSUE TITLE
[APIView Python] rendering of optional kwarg is creating duplicate kwarg entries

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-tools#1529]
hey @praveenkuttappan 

this code
<img width="861" alt="Screen Shot 2021-03-30 at 3 58 11 PM" src="https://user-images.githubusercontent.com/43154838/113048623-bdb43280-9170-11eb-91f8-47e36cf641fd.png">

is causing this apiview (search `build_classificationrules_list_all_request` [here](https://apiview.dev/Assemblies/Review/6abafb3120fb4063b09df0f2303a4ef9)). The `Union[str, NoneType]` is weird, it should be `Optional[str]`, and there's duplicate entries. My understanding is we don't do `optional[str]` in sphinx docs, is this correct?

Note: is not exclusive to string, also seeing for int

**Comment by scbedd** [comment]
Eliminate duplication, see if we can keep around `Optional[str]`.

**Comment by praveenkuttappan** [comment]
@tjprescott Will this be resolved with your changes to remove duplicate kwarg?

**Comment by tjprescott** [comment]
The duplication will be fixed, yes.
