### ISSUE TITLE
Running the Prepare-Release.ps1 in the hotfix branch would replace the latest entry instead of adding a new one

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#1542]
cc @chidozieononiwu @weshaggard

**Comment by weshaggard** [comment]
@pakrym I assume you are talking about the change log? That is an interest scenario where there is no entry in the change log already but you want to add one. I think we can probably use the Unreleased vs Date as an indication of whether or not to replace (i.e. if the latest is marked unreleased) or add a new one if the latest is marked with a date. Although that might make running the script multiple times inconsistent so we will have to think through the scenarios somewhat.
