### ISSUE TITLE
ApiView pipeline checks need to work around branches

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#1547]
Consider the scenario where someone is working on the next beta in master and then they need to hotfix an older version so they create a release or hotfix branch from an older approved version and then they try and do a release from that older branch but there has been new apis already added to apiview from master. Currently the ApiView checks fails because there is a diff between the latest from master and the hotfix version in another branch. We need some way to allow these hotfixes to be approved, especially when they are not actually change any APIs.  In order to do that I suspect we will use the versions of the library in order to align to the correct apiview to compare against.

For reference here is example build for keyvault in java that hit this exact problem https://dev.azure.com/azure-sdk/internal/_build/results?buildId=834175&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=9d510ff3-53a8-5192-bd2d-466ce830bc13.

**Comment by kurtzeborn** [comment]
This is higher priority than any new features in ApiView currently in the backlog.  This is getting in the way of some release situations on the team and with partners.

**Comment by kurtzeborn** [comment]
https://github.com/Azure/azure-sdk-for-java/issues/21408 is likely caused by this or is a duplicate issue tracking the same thing.
