### ISSUE TITLE
Improvement on aggregate-report CredScan tool

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#1569]
Two things to do for improving the pipeline:
1. We have to switch the step of post-analysis and publish security analysis log in each lang repo aggregate-report yaml. This will help to publish the baseline/suppression file if we want to regenerate those.
2. Add a step which convert CredScan sarif (json like file extension) to csv.

It is currently implemented in Java itself. However, we want to extract the common parts out into a script file. So we can simplify the aggregate report for all language repo and run the script locally.

PR in Java: https://github.com/Azure/azure-sdk-for-java/pull/20575

Proposal scripts:
```
parameters:
  RepoOwner: ""
  RepoName: ""
  SourceRepository: ""

$results = (Get-Content "${{ parameters.SourceRepository }}\.gdn\.r\CredScan\001\CredScan-matches.sarif" | ConvertFrom-Json).runs.results
$csvRows = @()
$results | ForEach-Object {
  $csvRows += [pscustomobject]@{
    ruleId = $_.ruleId
    ruleIndex = $_.ruleIndex
    fingerprints = $_.fingerprints
    message = $_.message
    properties = $_.properties
    rank = $_.rank
    fileName = $_.analysisTarget.uri -replace "${{ parameters.SourceRepository }}(.*)" "https://github.com/${{ parameters.RepoOwner }}/${{ parameters.RepoName }}/blob/master/`$1"
    startLine = $_.locations.physicalLocation.region.startLine
    startColumn = $_.locations.physicalLocation.region.startColumn
    endLine = $_.locations.physicalLocation.region.endLine
    endColumn = $_.locations.physicalLocation.region.endColumn
    level = $_.level
  }
} 
$csvRows | Export-Csv -Path $(Pipeline.Workspace)\.gdn\.r\CredScan\001\CredScan-matches.csv -NoTypeInformation
```

**Comment by weshaggard** [comment]
@sima-zhu I suggest we use this issue to just remove that conversion as we are mostly clean now I don't think it is worth having this in the pipelines.
