### ISSUE TITLE
LLCView Phase1 : Get serializers for LLCAPIView

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#1605]
The concept is to have a declarative Python code that can describe the LLC view, and the ability to get it as JSON file

Brainstorm example:
```python
main_view = LLCClientView(name="DocumentTranslationClient")

main_view.add_operation(LLCOperationView(
    name="CancelOperation",
    parameter=ParameterView(
        type="string(guid)",
        namea="id"
    )
))

def to_json(): # LLCClientView
    for operation in self.operations:
        operation.to_json()

main_view.operations[0].to_json()

# Approach 1
main_view.serialize()
# Approach 2
main_view.to_json() # produces the API view JSON
# Approach 3
import json
json.dumps(main_view, encoder=APIViewEncoder())
```

Those object should be into a "llc_view_models.py", that the future scripts can do `from llc_view_models import *`

In practical term:
`python my_llc_declarative.py` outputs on stdout the JSON that we will put in APIView input

Important concepts:
- Operations name
- Operation group
- Client constructor (endpoint, credential)
- Optional parameters (with/without default values)
- parameters
- title/description
- NO MODELS

Expected APIView:
![image](https://user-images.githubusercontent.com/1050156/118048473-304c2c80-b331-11eb-9376-de2c0af20cba.png)

Expected deliverable date:
- June 4th

Reference:
- [The Python APIView](https://github.com/Azure/azure-sdk-tools/tree/master/packages/python-packages/api-stub-generator) could be used as inspiration. Copy/paste is fine.
- [The APIView JSON format](https://gist.github.com/pakrym/09558b6a339449ab1c26a7f95e6df37c).

**Comment by kristapratico** [comment]
@LibbaLawrence
