### ISSUE TITLE
LLCView Phase 2 : From autorest to LLC APIView

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#1607]
The idea is to have full story from an autorest call to APIView.

Interesting points:
- To get m4 from any autorest call, add `--output-artifact=code-model-v4-no-tags --use:@autorest/modelerfour@latest`
- This is a YAML model with references (method points to parameters, etc.)

Assuming we have a `LLCViewModel` from https://github.com/azure/azure-sdk-tools/issues/1605, we want a parser from the YAML to that model:

```python
import yaml
m4_yaml = yaml.safe_load(m4_file)
llc_view = parse_m4_into_view(m4_yaml)
```

```shell
autorest https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/TextAnalytics/readme.md --output-artifact=code-model-v4-no-tags --use:@autorest/modelerfour@latest
```

**Comment by kristapratico** [comment]
@LibbaLawrence
