### ISSUE TITLE
APIView conversation view is broken

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#1612]
https://apiview.dev/Assemblies/Conversation/f50c27920f774c4ab6ca1f9b279683d0

shows `There are no comments in the review.` but there are many

cc @praveenkuttappan

**Comment by praveenkuttappan** [comment]
I have checked this issue. Comments in Conversation tab is grouped under each revision where as review page shows all comments.   If a revision is deleted then conversation tab is not showing comments added in that revision. This is definitely confusing and I would like to change. But I would like to know more on the reasoning behind grouping these comments under revisions before I can think of a better solution. My expectation is in line with issue comments. If a comment is visible in review page then it should be visible in Conversations tab as well. @JoshLove-msft

**Comment by pakrym** [comment]
The reason was to see unresolved comments from previous revisions that we hidden by API changes.

**Comment by JoshLove-msft** [comment]
Maybe group under Deleted Revisions section?

**Comment by JoshLove-msft** [comment]
Or is the issue that the comment appears in other revisions as well? In that case, we should just put it under the first non-deleted revision.

**Comment by pakrym** [comment]
@praveenkuttappan can we prioritize this one? https://apiview.dev/Assemblies/Review/f50c27920f774c4ab6ca1f9b279683d0 has a bunch of archboard comments I can't see anymore.

**Comment by pakrym** [comment]
I think we should keep reversions that have comments on them.

**Comment by pakrym** [comment]
@weshaggard @praveenkuttappan @kurtzeborn can we look at this issue?

Today @KrzysztofCwalina asked me for 
![image](https://user-images.githubusercontent.com/1697911/135356580-62adb675-ce58-4d85-a638-83c5747def66.png)

But because we delete all intermediate revisions there is none that represents archboard review.

**Comment by pakrym** [comment]
Maybe it's worth keeping all revisions just fix the UI to collapse non-Approved ones in the list

**Comment by praveenkuttappan** [comment]
Sorry for the delay. I will have this prioritized.
