### ISSUE TITLE
[Python APIView] generates bogus "kwargs" required warnings on methods that shouldn't require them.

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk-tools#1620]
ApiView's linter generates a "kwargs required" warning on the following code:

```
    def serialize(self):
        #type:() -> str
        """ Returns a string serializing the JSON Web Token
        
        :rtype: str
        """
        return self._token
```

There is no reason to add a kwargs parameter to this method, as far as I can tell.

**Comment by kurtzeborn** [comment]
@seankane-msft may be more appropriate to work on this one.

**Comment by tjprescott** [comment]
Closing this issue as the APIView-specific kwargs check is being removed and our custom pylint checks have more tailored kwargs checks (which can be suppressed if they are not applicable).
