### ISSUE TITLE
Release pipeline should allow NuGet packages with .winmd files

### ISSUE THREAD

**Issue by LoadLibrary** [Azure/azure-sdk-tools#1626]
The current release pipeline doesn't know how to sign .winmd files and also tries to verify if .winmds are strong name signed.
It would be good to have the release pipeline fixing these issues to allow publishing packages using .Net Native.

**Comment by weshaggard** [comment]
This has been fixed with https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-build-tools/commit/380af6f0d526bdf597cf71f73ec93c97881613ea. The signing/publishing now support winmd files.
