### ISSUE TITLE
Sparse checkout yml should accommodate commitish which does not yet exist

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1642]
Found this while adapting `docs-metadata-release.yml` to support daily builds. 

In the case of daily builds a sparse checkout currently fails when checking out a branch which doesn't exist: 

```
...
Repository MicrosoftDocs/azure-docs-sdk-node is being initialized.
Cloning into '.'...
remote: Enumerating objects: 3391, done.
remote: Counting objects: 100% (112/112), done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 3391 (delta 36), reused 65 (delta 0), pack-reused 3279
Receiving objects: 100% (3391/3391), 1.03 MiB | 3.27 MiB/s, done.
Resolving deltas: 100% (383/383), done.
git sparse-checkout add eng doc-ref-services/preview doc-ref-services/latest
Set sparse checkout paths to:
eng
eng
doc-ref-services/preview
doc-ref-services/latest
git checkout new-branch-doesnt-exist-yet
error: pathspec 'new-branch-doesnt-exist-yet' did not match any file(s) known to git
```

In this case we'd want to check out a "base" branch. In most cases today the base branch would be the default branch. However, it may become necessary to specify another base branch... though I'm not aware of a concrete example of that scenario yet.

Failure conditions could get complex. For example, if the base branch isn't the default branch and also doesn't exist yet do you fall back to the default branch or throw an error? ... I'd recommend throwing an error instead of trying to guess the user's intent. 

@benbp

**Comment by benbp** [comment]
Do you have an example of the changes you were making that caused this failure? Even with the old checkout method, you can't specify a branch that doesn't exist, so similarly sparse checkout needs to be initialized against a base branch rather than a new branch (which would be added in subsequent scripts). Or is this an issue with the variables that are passed through to specify `Commitish`?

**Comment by benbp** [comment]
@danieljurek do you still think this is a needed feature request, or is the approach you took adequate?

**Comment by benbp** [comment]
Closing and we can re-open if the need arises.
