### ISSUE TITLE
APIView automation doesn't auto-upload track 2 package with Microsoft.* name for .NET

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#1673]

**Comment by pakrym** [comment]
Or System.Memory.Data for that matter.

**Comment by weshaggard** [comment]
We will need to come up with some way to detect track 2 beyond https://github.com/Azure/azure-sdk-for-net/blob/master/eng/scripts/Language-Settings.ps1#L43. Currently we only parse the local csproj file but if we want to gather something like IsClientLibrary property we will need to run an msbuild target to determine if it is set for a project.

**Comment by praveenkuttappan** [comment]
@weshaggard : This is the issue we have discussed about last week. Some of the track2 C# packages are incorrectly treated as  track 1.

**Comment by weshaggard** [comment]
I have a started looking at a solution that I'm testing locally. I hope to have a PR out within a few days.
