### ISSUE TITLE
[EngSys] False positive in API changes detection in CI

### ISSUE THREAD

**Issue by deyaaeldeen** [Azure/azure-sdk-tools#1675]
Here is a specific failure for detected API changes in core-amqp: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=935768&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=e2744c02-d5ab-5ec4-b597-2a76a072b500

However there are no changes in core-amqp's public APIs. Perhaps it is a problem in the check itself confused by differences in line breaks between Windows and UNIX?

cc @jeremymeng @chradek

**Comment by praveenkuttappan** [comment]
This is fixed in PR https://github.com/Azure/azure-sdk-tools/pull/1678.
We had an issue in comparison when latest revision is not approved and if it has some temporary changes.
