### ISSUE TITLE
Show release date in API view for automatic review

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#1696]
Architects prefer to approve automatic reviews proactively and currently it is difficult when there are so many reviews in pending state. They would like to see a release date for packages that are ready to be released so they can prioritize reviewing them. Proposed suggestion is to show release date from changelog here.

**Comment by chidozieononiwu** [comment]
Related to https://github.com/Azure/azure-sdk-tools/issues/2278

**Comment by WhitShake** [comment]
Completed
