### ISSUE TITLE
Update revision name for automatic packages to show published status when a package is released

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#1698]
Only few revisions (manually feeded) show as published in revision dropdown and rest all revisions show SHA. This is confusing and architects  would like to get it updated as published and version number when a package is released.

**Comment by praveenkuttappan** [comment]
@lmazuel This issue is in line with one of the requirement you have filed to avoid confusion about review revisions.

**Comment by WhitShake** [comment]
Revision is marked as Released.
