### ISSUE TITLE
Allow live test pre- and post- steps to use other scripts besides PS

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#1713]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/48/Create-a-new-Live-Test-pipeline?anchor=optional-pre--and-post-steps

In the iOS team (and coming from the CLI team), our toolchain is largely Linux-based. As a result, Powershell knowledge is not widespread, which adds friction when trying to write `test-resources-pre.ps1` and `test-resources-post.ps1` scripts. Right now, we have a very wonky script that simply calls into a Python script in our `eng/scripts` folder (https://github.com/Azure/azure-sdk-for-ios/blob/feature/AzureTest/sdk/communication/test-resources-post.ps1), but I would much prefer to simply have a `test-resources-post.py` script in the service directory.

It would be great if `test-resources-pre/post` could support other formats like `.sh` or, my personal fave, `.py`.

In this specific case, Python is a **necessary** mechanism because while the Python SDK supports the operations we need to set up the test, neither Azure CLI nor Azure Powershell have the necessary commands.

**Comment by tjprescott** [comment]
cc/ @benbp

**Comment by kurtzeborn** [comment]
We don't see a general need here across the broader set of languages that we support. It looks like you've got something working using this PowerShell+Python solution. If this works and unblocks you in mobile, let's go with what you've got already.

**Comment by tjprescott** [comment]
I certainly agree that there isn't a _need_, but I think it misses the point. The purpose of our engineering system is to reduce developer friction for the various SDK and service teams. Right now, the only mechanism we have to deploy test resources for mobile is the `New-TestResources.ps1` script combined with the post-deployement script. Using the New-TestResources script requires Powershell, but no knowledge of Powershell scripting, so it's a minimal hassle. ARM templates are a hassle, but we have significantly improved that by developing the bicep format.

However, it's the SDK and service teams which have to write the pre/post-deployment scripts. Forcing them to write their scripts in Powershell does add a lot of friction for teams which don't have that expertise. It seems like a simple way to empower these teams would be to let them use the scripting language of their choice.

**Comment by weshaggard** [comment]
The pre and post scripts are for edge cases where the arm templates don't yet have support for some new feature yet and so the hope is that most people don't ever need to write them at all. I don't think it is a huge hurdle to write a couple links of powershell to do what ever it is you need to do even if that is to call into another tool or language. I think the price of that is much lower then adding more complexity into our common deployment scripts to support various other languages. If folks need assistance in writing these we are more then willing to assist but the hope is that most folks will never need to. 

Just consider your simple example how would our common script know what dependencies to pip install to enable your python script to execute? We would have to add another layer of complexity to be able to find and install the necessary dependencies before we could even call a post python script. To me I don't see the value of that complexity.
