### ISSUE TITLE
APIView Support for Swift

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#1714]
We plan to add support for creating APIView token files from Swift source code over this summer (https://github.com/Azure/autorest.swift/issues/141).

Once we have that working, we will need the necessary UI tab on the APIView site to publish the reviews.

**Comment by kurtzeborn** [comment]
My understanding is that some one on the mobile clients team is going to add this support.  Please reach out to @praveenkuttappan for guidance when you're ready to do this.

**Comment by tjprescott** [comment]
@kurtzeborn this issue is to track the UI/client work that will need to be done on APIView itself to utilize what our mobile intern develops.
