### ISSUE TITLE
[Test-Proxy] Question for Resolution - Randomly Generated Resources Matching During Playback?

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#1733]
@HarshaNalluru had a question that I don't have an excellent answer for yet. Context:

Let's say we are testing write to a table storage resource.  The components are essentially:

- The name of the resource (created at outset of test)
- The name of the table being created. (looks like `<prefix>-<randomnumber>`)

When running in record mode, the request/response entries for the actions taken by this test will have both the URI to the storage account AND the relevant tablename in random places within the recording. This isn't an issue for recording, but during `playback`, we run into an issue w/ that randomly generated tablename. Given that it's generated _as part of the test_ PRIOR to invoking the requests, the `tablename` between two different runs will never be the same! This will cause us to _fail_ to match the appropriate recording entry during playback because our bodies (or wherever that tablename lives) will not align.

Currently, the JS team gets around this by checking the recording for what the `tablename` was _before_ the test actually starts. This means that while yes, the table name was random during `recording`, during `playback` everything will align just fine.

Given that the recorder is touching local resources, this isn't really an option anymore. 

Thoughts so far:

- A general name sanitizer that takes whatever format is necessary, and replaces it with a fake test resource prior to matching
- A looser matcher that ignores certain constraints intentionally

**Comment by pakrym** [comment]
Or you can have the recorder generate random names and store them along with the record.
