### ISSUE TITLE
[APIView Python] client method return type getting cutting off

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-tools#1738]
Example here: https://apiview.dev/Assemblies/Review/f74ef8c4777b408f85dab76b8034cb41#dcda8732257d46a7abb8f332b40c741c

**Comment by tjprescott** [comment]
![image](https://user-images.githubusercontent.com/5723682/139511544-57d4acf9-a75a-4851-8660-1d6b13f26e46.png)

**Comment by tjprescott** [comment]
Looks like this is the same (or similar) as #826.
