### ISSUE TITLE
[Python APIView] Cutting off Tuples

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-tools#1741]
[link](https://apiview.dev/Assemblies/Review/5210fb6aa28542e4ad65c13a44c2b9d6) `add_policy_management_certificate` method has a type of `Tuple[AttestationPolicyCertifacteResult, AttestationToken]` but the types of the tuple are cut-off

**Comment by tjprescott** [comment]
This is almost certainly fixed by #2255.

**Comment by tjprescott** [comment]
@seankane-msft are you still experiencing this with APIVIew 0.2.5?

**Comment by tjprescott** [comment]
I believe this is fixed in 0.2.6. Please reopen if that is not the case.
