### ISSUE TITLE
Parallelize Pipeline Generation

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#1745]
We are hitting timeouts. Filed a PR elsewhere to allow us to override that.

I'm not saying we should _entirely_ parallelize it. But at least the the current serial `for-each` [here](https://github.com/Azure/azure-sdk-tools/blob/07c8cf02afcf36a14986001b766ceeb27ce13b11/tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Program.cs#L183) into a `Parallel.Invoke` or the like.

**Comment by kurtzeborn** [comment]
Been a while since we saw timeouts on this.  Closing.  Sima did add caching logic which sped up a lot of the interactions with DevOps.  That may be why we're not seeing timeouts anymore.
