### ISSUE TITLE
[Python APIView] Import type aliases

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-tools#1747]
Some projects use type aliases to simplify type hints in their code, but these are not models so not read by the apistubgen tool. Having these at the top of the api view file would be great for architects to understand the tool

**Comment by tjprescott** [comment]
@seankane-msft do you have a short section of example code to illustrate this?

**Comment by seankane-msft** [comment]
@tjprescott iirc this was an issue for Tables, but I can't find an example in the source code. I think it is safe to close this issue.
