### ISSUE TITLE
Striped table is messed up when filtering

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#1756]
The striped tables get messed up when using the search filter:
![image](https://user-images.githubusercontent.com/54595583/123854206-46a74b00-d8d3-11eb-8a35-97c2d4faa940.png)

_Originally posted by @JoshLove-msft in https://github.com/Azure/azure-sdk-tools/pull/1750#r660894712_

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/2785
