### ISSUE TITLE
[Python APIView] `ivar` not detecting vartype when param has the same name

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-tools#1765]
Variable types for ivars listed under[ `AmqpMessageProperties` here](https://apiview.dev/Assemblies/Review/3e49ce1ca870470289360023dcb51edf#azure.eventhub.amqp.AmqpMessageProperties) do not reflect the variable types listed for ivars [here in the code](https://github.com/Azure/azure-sdk-for-python/blob/538a5055b4330c6b324fa54a00e96d73d882fa63/sdk/eventhub/azure-eventhub/azure/eventhub/amqp/_amqp_message.py#L491). This seems to be because the `ivar`s have the same names as the `param`s.

**Comment by tjprescott** [comment]
@swathipil do you still observe this problem in APIView 0.2.5?

**Comment by swathipil** [comment]
@tjprescott Would I need to manually upload a whl to see if those changes took place? Or should they happen automatically?

**Comment by tjprescott** [comment]
Not sure if it would be automatic, but the first line would say
`# Package is parsed using api-stub-generator(version:0.2.5)`

**Comment by swathipil** [comment]
ah gotcha - so it looks like a new one was regenerated with version:0.2.5, but still has the same issue: https://apiview.dev/Assemblies/Review/3e49ce1ca870470289360023dcb51edf#

**Comment by tjprescott** [comment]
Okay, thanks, I think that should be a pretty easy fix. Thanks for confirming!
