### ISSUE TITLE
Reduce dotnet weekly pipeline schedules

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#1766]
Two primary issues:

- The dotnet tests-weekly pipelines are running on both Saturday and Sunday. These pipelines should only be running one day per week.
- We run weeklies for all dotnet service SDKs, covering public and canary regions. This is probably unnecessary, and we only need to run the weeklies for SDKs that support sovereign cloud testing.

![image](https://user-images.githubusercontent.com/1020379/124018331-bb52b600-d9b5-11eb-9dd1-57cd41aedbe8.png)

**Comment by kurtzeborn** [comment]
@heaths, it's just a guess that you're the best person to follow up on this.  Please reassign as appropriate.  @benbp is ready and available to answer questions and support making this change.

**Comment by heaths** [comment]
If it's all SDKs, wouldn't it be easier to write a quick script to change all pipelines' schedules? I'm happy to update my own, but changing all pipelines - especially across all languages - seems like a bulk operation would be better. And is the new pipeline creator going to stop scheduling both days going forward?

**Comment by benbp** [comment]
Chatting with @heaths, we're not sure why it's both days, and will change it to run on Sunday only.

**Comment by weshaggard** [comment]
I have a script we can use to update schedules if needed but we should still update our pipeline generation tool to bucket the pipelines across the entire 2 days.
