### ISSUE TITLE
Protcol APIView: stylistic improvements

### ISSUE THREAD

**Issue by LibbaLawrence** [Azure/azure-sdk-tools#1774]
-> narrow down the exception type of try/catch
https://github.com/Azure/azure-sdk-tools/blob/main/packages/python-packages/protocol-stub-generator/protocol/protocol_models.py#L1383

-> Instances like the [below ](https://github.com/Azure/azure-sdk-tools/blob/main/packages/python-packages/protocol-stub-generator/protocol/protocol_models.py#L413) can be refactored to leverage `enumerate`:
```
for op_groups in range(0, len(yaml_data["operationGroups"])):
```

**Comment by mikekistler** [comment]
Closing as LLC View will be replaced with Swagger view.
