### ISSUE TITLE
Branch cleanup for daily docs builds

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#1778]
Clean up the daily docs branches after X number of days so we don't have a long list of obsolete branches.

**Comment by weshaggard** [comment]
FYI we have https://github.com/Azure/azure-sdk-tools/blob/main/eng/pipelines/templates/jobs/tools-cleanup.yml which runs for cleaning other branches you could potentially piggy-back on that or at least use the common helper scripts.

**Comment by sima-zhu** [comment]
Link above is broken. Guess it has been moved out to somewhere else. 

I am currently running github actions to test the job.
https://github.com/sima-zhu/azure-docs-sdk-java/actions/runs/1590076109

**Comment by benbp** [comment]
@sima-zhu perhaps @weshaggard meant https://github.com/Azure/azure-sdk-tools/blob/main/eng/pipelines/branch-cleanup.yml ?

**Comment by weshaggard** [comment]
It used to be that file until I moved it when I fixed the organization with https://github.com/Azure/azure-sdk-tools/commit/589224add781b7b11f6cf2741b6639068c29a168

**Comment by sima-zhu** [comment]
Taking the one as my next work of docs automation.

**Comment by sima-zhu** [comment]
As the script exists, we only need a new pipeline for docs daily branch.

**Comment by sima-zhu** [comment]
Also, do a mass delete on all four repos.
