### ISSUE TITLE
Remove "Preview" and "Canary" from default weekly live testing clouds

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#1781]
The default `SupportedClouds` value in `archetype-sdk-tests.yml` should be `Public,UsGov,China`. This will remove config duplication in `tests.yml` files.

For `Preview` especially, and also `Canary`, there is no added value in testing it in the weekly pipeline for services that don't require it.

**Comment by weshaggard** [comment]
Lets just try and see if we can make these additive so that people that do need them they don't need to duplicate the default list. Perhaps an AdditionalClouds parameter (assuming we don't already have that).

**Comment by benbp** [comment]
@weshaggard I'll try out a prototype for that, though we may find that the complexity of merging two lists in pipelines yaml templates isn't worth it (as only a few config files would use this parameter).
