### ISSUE TITLE
Swift APIView: coverage gaps

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#1818]
The following declaration types are implemented in Swift APIView and will cause a fatal error:
- [x] Deinitializers (PR: #1820)
- [x] Operators (PR: #1820)
- [x] Precedence Groups (PR: #1820)
- [x] Subscripts (PR: #1820)

**Comment by jairmyree** [comment]
- Suggestion: a new line between variables, functions, and constants
- Suggestion: group navigation items by type (enums, classes, structs, etc.)
- Parameters, variable identifiers, and constant identifiers don't allow you to click them to add comments
- Inconsistent newlines among encapsulating definitions (definitions with members)
- Inconsistent white space for opening brackets when there's no inheritance.
- Suggestion: Put parameters on their own lines

**Comment by tjprescott** [comment]
Example APIView: https://apiviewstaging.azurewebsites.net/Assemblies/Review/29dc0e0aec33421ea7a6728eb05178e5?doc=False

**Comment by tjprescott** [comment]
> Parameters, variable identifiers, and constant identifiers don't allow you to click them to add comments

Only types are intended to be clickable. Clicking should let you jump to that type's definition. So identifiers should not be clickable. To leave a comment, you click the blue + in the left margin. Are there lines missing that comment marker?

**Comment by tjprescott** [comment]
Example of added operators and precedence groups:
https://apiviewstaging.azurewebsites.net/Assemblies/Review/29dc0e0aec33421ea7a6728eb05178e5

**Comment by tjprescott** [comment]
Closing since #1820 is merged. Other style suggestions moved to #1832
