### ISSUE TITLE
API View for .NET should not show AsyncIteratorStateMachine attributes

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#1821]
Today, APIView shows AsyncIteratorStateMachine attributes on methods returning async enumerables. These attributes are irrelevant plumbing. We should not show them.

**Comment by praveenkuttappan** [comment]
@KrzysztofCwalina : Can you please share more info on expected result here? Are you asking to hide methods with attribute `AsyncIteratorStateMachine` which in this case is `GetAsyncEnumerator`

**Comment by KrzysztofCwalina** [comment]
No, just hide the attribute.
