### ISSUE TITLE
Swift APIView: Support ObjC with Bridgecraft

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#1823]
https://github.com/lvsti/Bridgecraft

We need to be able to generate the swift interface from Objective-C code to make it parsable by Swift APIView. This was why we had support for `*.swiftinterface` but apparently some ObjC projects can't generate that file.

**Comment by kurtzeborn** [comment]
@tjprescott, this work will need to be funded by the mobile libraries team.  @praveenkuttappan will be ready and willing to explain/assist/support that work and ensure that integration goes smoothly when you are ready.

**Comment by tjprescott** [comment]
@kurtzeborn that's the intent for the mobile team to provide this, but since the code lives here, I created the issue here. Is there somewhere else I should put this issue?
