### ISSUE TITLE
APIView internal error on uploading Go

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-tools#1828]
I am attempting to upload a go archive to apiview.dev and am getting internal errors. 

I am able to reproduce it with an existing library:

azure-sdk-for-go

 on e6396ce08
> Compress-Archive .\sdk\compute\ -DestinationPath compute.zip
> Rename-Item .\compute.zip -NewName .\compute.gosource

GH issues don't accept *.gosource so I zipped them:

[testcases.zip](https://github.com/Azure/azure-sdk-tools/files/6851207/testcases.zip)

![image](https://user-images.githubusercontent.com/6392201/126395017-3c23da59-a9a4-42eb-af14-c1358da4fb51.png)

![image](https://user-images.githubusercontent.com/6392201/126395030-76464830-ff34-4673-9a12-36f283643661.png)

**Comment by praveenkuttappan** [comment]
Incorrect source zip files has caused the issue here. It seems current help text is misleading to compress at service level instead of package level. I will submit a PR to update this text.

**Comment by praveenkuttappan** [comment]
I have modified helptext to clarify that developer needs to archive the folder in which has go.mod file is present. This issue can be closed now.
