### ISSUE TITLE
Add perf/stress job(s) to nightly tests.

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-tools#1838]
In Storage (Java) we have bodged "stress test suite" that runs after normal live test run. See example here https://github.com/Azure/azure-sdk-for-java/blob/8e6f50208c518bf7940066caca14a5e413900f69/sdk/storage/tests.yml#L65-L75 .

However this is becoming a problem as we add scenarios. The stress tests run after live tests contribute to overall pipeline run and that contribution isn't trivial (20m as of now).
Therefore, we'd like to request to find a way to parallelize this better. I.e. not wait for usual tests to complete to start stress testing.

Some thoughts:
- we'd rather not create separate pipeline for that, we already have ci, weekly and nightly pipelines to look at when we release.
- this could be extra job or stage in nightly pipeline (like we do coverage measurement)
- we shouldn't run normal tests and stress tests in parallel on the same VM - stress tests are quite memory greedy and will be noisy neighbor.

**Comment by benbp** [comment]
Discussing with @kasobol-msft I was thinking it might make sense to have a general job template for perf tests that we can include as a separate stage in the `archetype-sdk-tests.yml` templates more generally.

**Comment by kurtzeborn** [comment]
We do this already.  Done. Done.
