### ISSUE TITLE
Polymorphic Data Issue - ApiView Protocol

### ISSUE THREAD

**Issue by LibbaLawrence** [Azure/azure-sdk-tools#1844]
SystemData in Json Response output is "{}" and contains no additional properties and therefore is empty when represented in ADL formatting. 

Properties are found under "parents" and that is something not currently parsed. 

https://github.com/Azure/azure-rest-api-specs/blob/cb405da5485f0d0f78ee27339722d5faca39f637/specification/purview/data-plane/Azure.Analytics.Purview.Account/preview/2019-11-01-preview/account.json#L842

**Comment by maririos** [comment]
@LibbaLawrence what is the work that needs to happen here? is this specific to Python? or generic APIView

**Comment by kristapratico** [comment]
@l0lawrence

**Comment by l0lawrence** [comment]
@maririos This was from when I was an intern, so I don't remember the exact details behind this issue, but I was working on protocol apiview which was language agnostic.

**Comment by maririos** [comment]
@l0lawrence how do you want to handle this issue? who needs this? and with what priority? or should we close this issue?

**Comment by l0lawrence** [comment]
I would say close it
