### ISSUE TITLE
CI Tests

### ISSUE THREAD

**Issue by LibbaLawrence** [Azure/azure-sdk-tools#1845]
Add on CI tests to the current manual run tests: 

- Check against correct ADL format
- Check against an expected request and response versus what it is outputting

**Comment by maririos** [comment]
@LibbaLawrence is this something you are still planning on doing? And is this Python specific?

**Comment by kristapratico** [comment]
@l0lawrence

**Comment by l0lawrence** [comment]
@maririos not something I still plan on doing! This was from my internship -- this was also Protocol apiview related

**Comment by maririos** [comment]
@kristapratico @l0lawrence so should we close this issue then?
