### ISSUE TITLE
README has some auto-generated snippet replacer text

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#1867]
The text `C:/repo/sdk-tools/packages/java-packages/snippet-replacer-maven-plugin` is at the bottom of the tools readme. I assume this was just added by accident once, but it would be good to know why so it doesn't get re-added.

https://github.com/Azure/azure-sdk-tools/blob/main/README.md?plain=1#L32

CC @mikeharder @scbedd as you're both on the git blame around this line.

**Comment by scbedd** [comment]
@benbp I seriously doubt this was automation. I'll remove it and close. If it pops up again I'll re-open this issue.

**Comment by scbedd** [comment]
Hasn't come back. Closing.
