### ISSUE TITLE
[Test-Proxy] Error Reporting Improvements

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-tools#1877]
The error reporting for the test proxy should be improved so tests fail quickly and with proper error codes. These can be a combination of logging information and 
- [x] When the recording cannot be found the recording id should be printed to stdout and returned in the response of the 400 error code
- [x] If a request is improperly formatted (ie, missing headers) we should return a 400 with information about what headers are missing.
- [x] If the recordings do not match, no 400 is returned instead an unhandled exception occurs and the request hangs until the timeout is reached.
- [x] Handle regex compilation failures when hitting `/Admin/AddSanitizer/`

**Comment by scbedd** [comment]
Adding to the above set of known failures:

We need to handle an invalid regex. Here's an example from @HarshaNalluru 

```
Target = "UriRegexSanitizer"
BODY
{"value":"st=2021-08-03T08:52:15Z&spr=https&sig=fakesig","regex":["sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2023-08-03T16:52:15Z&st=2021-08-03T08:52:15Z&spr=https&sig=randomsigM%3D"]}
```
