### ISSUE TITLE
Set default AZURE_CLIENT_* variables in subscription configuration

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#1888]
There are many places across our `tests.yml` live test configs where AZURE_CLIENT_* env variables are hardcoded (see for example https://github.com/Azure/azure-sdk-for-python/search?l=YAML&q=azure_client_id). The live test automation currently pre-populates the service principal variables (client id, client secret, etc.) with a service directory prefix. This is handled in some tests already, but it's not universal, while the default auth libraries handle AZURE_* prefixed variables consistently.

We should update either our [subscription configurations](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/389/Configuring-Tests?anchor=subscriptionconfiguration-schema) (public, canary, usgov, china, preview) and/or the New-TestResources.ps1 script to populate the following environment variables, and also update all tests.yml files across the repos to remove references to them:

- AZURE_CLIENT_ID
- AZURE_CLIENT_SECRET
- AZURE_TENANT_ID
- AZURE_SUBSCRIPTION_ID

These variables being hardcoded also make the work to support cross-cloud testing harder, so this task will be helpful for that.

**Comment by kurtzeborn** [comment]
As we discussed this in triage, we wanted to make sure that we didn't cause conflicts between tests with this change.  In the event that we run more than one set of tests, the scripts my overwrite or duplicate the settings.
