### ISSUE TITLE
[LLCView] Models should be part of default view, not documentation

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#1905]
When we did the first archboard using this view, people wanted to comment on the models, and this is not possible if they are part of the "documentation"

This issue is about moving the "models" out of "documentation" into the default view.

**Comment by praveenkuttappan** [comment]
Can you please give an example or screenshot of an example? A link to any existing review and expected section will be helpful to check this further.

**Comment by praveenkuttappan** [comment]
Closing this issue since we are not moving ahead with LLC.
