### ISSUE TITLE
[LLCView] Improve the credential type shown

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#1906]
Right now, the credential shown is hard coded to AzureCredential. We want to take advantage of the information in m4 to be more precise:
- TokenCredentials (needs a AAD token)
- KeyCredentials (needs a key in header)
- Both

@timotheeguerin can help to provide guidance on what to read from m4 yaml to make a distinction in the supported type.

**Comment by mikekistler** [comment]
Closing as LLC View will be replaced with Swagger view.
