### ISSUE TITLE
[LLCView] Make comment link to two places

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#1907]
The LLC view is split into two sections that are redondant:
- The overview view, with inline method declaration
- The detail view, with detailled multi-line declaration

We want to make sure a comment in one place is reflected to the other place. According to Ted, it's possible to do that in APIView, since it happened by error in the C++ view. We want to make it a feature and link the comments in both part of the views.

**Comment by mikekistler** [comment]
Closing as LLC View will be replaced with Swagger view.
