### ISSUE TITLE
Add package property to decide whether a package requires API status check

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#1914]
Currently API status check is enabled only for new data plane packages. Java team needs to enable API check for spring package also. We should add a property in package properties object that's default to true for new data plane package and use this property to decide whether to enable API status check or not. This property can be overridden if any language requires specific conditions or  if extra package requires API status check.

**Comment by mikekistler** [comment]
@praveenkuttappan to check if this is already done.

**Comment by praveenkuttappan** [comment]
Automatic API review support is already added for Java Spring SDK.
