### ISSUE TITLE
DeleteAfterHours=48 is too aggressive for local development

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#1917]
It usually takes more than 2 days to develop a feature, should we at least increase it to a week now that the cleanup script is running?

**Comment by pakrym** [comment]
cc @benbp @heaths

**Comment by JoshLove-msft** [comment]
Is there a way that it can look at time since used rather than a hardcoded value?

**Comment by heaths** [comment]
You can pass `-DeleteAfterHours <hours>`. The parameter was always there, but we defaulted it a while back. Is this not suitable? The goal was to minimize expensive resource uptime. CosmosDb, Managed HSM, and more resources are expensive.

**Comment by pakrym** [comment]
>You can pass -DeleteAfterHours <hours>.

I know, but the goal is to have the default dev experience be usable. If we make people pass `DeleteAfterHours ` they would pass 99999999 just so they don't have to bother again.

**Comment by heaths** [comment]
No one else has provided feedback yet. When I use it for Key Vault, I have all my tests written, deploy test-resources.json, record, verify sus recordings, and tear down. I'm not saying everyone has to work this way (I know the other KV v-team devs have been), but seems most people do. If you need longer, you can pass in a different value.

Again, the point of defaulting to some amount of time - at one point, even 24hrs was discussed - was to tear down expensive resources ASAP.

We can certainly change the default, but I leave it to @kurtzeborn and @weshaggard who are largely managing the budget.

The scripts, BTW, only delete RGs that have expired - which -`DeleteAfterHours` sets - and VKs, and MHSMs that have already been deleted but not yet purged. If an RG and its resources are still active, they don't get cleaned up so specifying a longer default will still keep them up.

**Comment by pakrym** [comment]
>No one else has provided feedback yet

@JoshLove-msft did.

**Comment by JoshLove-msft** [comment]
Yeah, I have run into this a few times lately. Part of the problem is that I am running into issues running the NewTestResources script where it either hangs, or just takes a really long time.

**Comment by heaths** [comment]
I'll rephrase: this is the first issue opened, nor have I heard anyone say anything elsewhere.

The script sets up service principals as needed, but otherwise just deploys ARM templates. If either of those is taking long - I can say when deploying a Managed HSM it takes quite a long time - we need to know. Unfortunately, the deployment process doesn't provide any feedback (and I doubt there would be any progress to be provided). Some resources take longer than others. Managed HSMs are, in fact, hardware that has to be provisioned.

**Comment by JoshLove-msft** [comment]
Could the deletion be restricted to the expensive resources?

**Comment by pakrym** [comment]
>I'll rephrase: this is the first issue opened, nor have I heard anyone say anything elsewhere.

Didn't we just enable the cleanup script?

**Comment by heaths** [comment]
All costs add up. And are we to delete only those resources that are expensive and leave the rest of a RG around? That seems worse. We could find the RG and delete all of that, sure, but it seems a larger engineering effort than just overriding the default.

You can also default the parameter value so you don't have to remember. See https://docs.microsoft.com/powershell/module/microsoft.powershell.core/about/about_parameters_default_values. Example:

```powershell
# You can add this to your $profile. Be sure to add .ps1 at the end of the cmdlet name.
$PSDefaultParameterValues["New-TestResources.ps1:DeleteAfterHours"] = 72
```

**Comment by JoshLove-msft** [comment]
Costs are not solely measured in Azure resources - there is also the cost of dev time spent waiting to re-create resources.

**Comment by heaths** [comment]
> Didn't we just enable the cleanup script?

As stated [above](https://github.com/Azure/azure-sdk-tools/issues/1917#issuecomment-900603633),

> The scripts, BTW, only delete RGs that have expired - which `-DeleteAfterHours` sets - and VKs, and MHSMs that have already been deleted but not yet purged. If an RG and its resources are still active, they don't get cleaned up so specifying a longer default will still keep them up.

Using a longer default lifetime means we don't tear down resources as soon. We don't tear down resources that are still being used.

**Comment by heaths** [comment]
> Costs are not solely measured in Azure resources - there is also the cost of dev time spent waiting to re-create resources.

Of course not, which is why I've provided several different ways to override the time for the cases where it's needed. Why keep resources alive longer in the default cases when only in a few cases you need to override - which was always supported.

**Comment by pakrym** [comment]
>As stated above,

I'm sorry, I don't follow.

**Comment by JoshLove-msft** [comment]
> > Costs are not solely measured in Azure resources - there is also the cost of dev time spent waiting to re-create resources.
> 
> Of course not, which is why I've provided several different ways to override the time for the cases where it's needed. Why keep resources alive longer in the default cases when only in a few cases you need to override - which was always supported.

From my experience at least, the default case is wanting them to stay around indefinitely. I run live tests locally while debugging, looking at perf, etc, so I would want to keep the resources around. I understand that some resources are expensive, independent of usage, but I think most resources created from test-resources files are not expensive.

**Comment by heaths** [comment]
I've been working on it, yes. But we only delete RGs that have expired. Right now they expire in 48 hours *by default* with supported ways to override that when needed. If we default it to, say, 120 hours then that's 72 more hours those resources are alive and costing us. We chose 48 hours as a reasonable time to run live tests or even re-record. If you are using resources for active development, you can pass a different value to `-DeleteAfterHours`.

The clean-up scripts are being improved (and enabled for Playground; were only running on Test Resources prior) to better control costs. That we weren't cleaning up resources before is irrelevant. We're trying to bring costs down now.

**Comment by pakrym** [comment]
What I'm trying to say is that the fact that you didn't hear any feedback before is based on the cleanup script being disabled.

**Comment by pakrym** [comment]
Pretty sure we can build a thing into the test framework that would extend the value every time tests run live.

**Comment by heaths** [comment]
>  but I think most resources created from test-resources files are not expensive.

See any _test-resources.json_ that provisions Managed HSMs (sdk/keyvault in all languages' repois) or Cosmos DBs.

I'm not arguing that people shouldn't use a longer lifetime when needed, just that when we picked 48 hours we didn't think more was needed by default.

**Comment by kurtzeborn** [comment]
@pakrym What would be a better default for this?  I'd rather not have people setting it to 99999 as you suggest above.  If extending the default another day or two would make you more comfortable we could do that.  I don't think it having the default be longer than a week is desirable though.

**Comment by weshaggard** [comment]
I sort of like @pakrym comment about having the test framework extend the time by setting the tag on the resources when we use them. Even in that case I'd suggest only 48 hours though and not pushing it out to a week or something.

**Comment by heaths** [comment]
I opened #1921 to track and, like @weshaggard, suggested that if/when we do that we maybe bump the default days back down to 48. If you're actively using a resource group it should get bumped regularly.

**Comment by pakrym** [comment]
I think a week or 5 days is good.

**Comment by heaths** [comment]
I will resolve this with PR #1912 since I have to update eng/common anyway.

**Comment by heaths** [comment]
I just don't want to push it yet since that will cancel pipelines we have running that are slowly working on the backlog of deleted KVs and MHSMs.
