### ISSUE TITLE
Have testing and recording framework automatically extend testing resource group when in use

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#1921]
The TestResources scripts automatically provision test resources in an ARM template with some default value to be cleaned up (currently 48 hours but may change). For people using these resources long-term, we could automatically extend it when in use, maybe adding 24 or 48 hours at a time.

If we do that, I would like to bump the default TTL back down to 48 hours or so. Some resources are expensive and the shorter they are provisioned the better.

Originally:

Pretty sure we can build a thing into the test framework that would extend the value every time tests run live.

_Originally posted by @pakrym in https://github.com/Azure/azure-sdk-tools/issues/1917#issuecomment-900619830_

**Comment by benbp** [comment]
Closing this for now unless the language teams want to pick it up for their respective test frameworks.
