### ISSUE TITLE
[Python APIView] crashes for python whl or stub file generated by API Stub Generator

### ISSUE THREAD

**Issue by D-W-** [Azure/azure-sdk-tools#1922]
Hi, I'm trying to upload a python package for review but it crashes with the following error:
![image](https://user-images.githubusercontent.com/7776147/129828707-8c4776ce-146f-4455-8b78-e8f2f48cbf75.png)

![image](https://user-images.githubusercontent.com/7776147/129829764-f70f1426-d47a-4a3d-8fab-c163bd9460b5.png)

I also tried to upload the stub file generated by API Stub Generator but it also failed.

![image](https://user-images.githubusercontent.com/7776147/129829864-8567813a-fdc6-4509-a210-fff00a2d3f2e.png)

Here's the files:
[package.zip](https://github.com/Azure/azure-sdk-tools/files/7004217/package.zip)

**Comment by tjprescott** [comment]
@praveenkuttappan with the move away from parsing WHLs, is this issue still relevant?

**Comment by kurtzeborn** [comment]
Pretty sure this issue is obsolete at this point.
