### ISSUE TITLE
[APIView Python] incorrectly marking async paging as `async def`

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-tools#1931]
When we pass in autorest generated async paging to apiview, api view shows it as being `async def`, while it should just be `def`.

For example, [this](https://github.com/Azure/azure-sdk-for-python/blob/22e3480c70b14119fb908198da3778fe180d9221/sdk/purview/azure-purview-account/azure/purview/account/aio/operations/_resource_set_rules_operations.py#L577
Leads to this apiview
<img width="485" alt="Screen Shot 2021-08-23 at 7 02 22 PM" src="https://user-images.githubusercontent.com/43154838/130530193-5ee6a3ce-0911-4031-8809-31f60d4b1cd0.png">
) generated code

**Comment by tjprescott** [comment]
This is occurring because the substring "async def" exists in the method body due to an internal function definition that starts with "async def".
