### ISSUE TITLE
Auto-merge does not wait for approval when used on a PR to a feature branch

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#1933]
https://github.com/Azure/azure-sdk-for-js/pull/17061 is a PR targeting a feature branch and has the label auto-merge.
The expectation was that the PR gets automatically merged after approval.

Turns out the bot does not wait for the approval when the PR is for a feature branch :(

cc @praveenkuttappan, @weshaggard

**Comment by weshaggard** [comment]
cc @kurtzeborn 

This is because the there are new required checks configured for the target feature/v4 branch. I believe @kurtzeborn has enabled branch protection for `release/*` and `hotfix/*` branch patterns did we want to add `feature/*` pattern to the list of protected branches as well?

**Comment by kurtzeborn** [comment]
I've added `feature/*` branch protection to all of the public language repos.
