### ISSUE TITLE
C# analyzer tests are not correctly validating single expected descriptors

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#1960]
While writing a new analyzer, I found that when you use `VerifyAnalyzerAsync(string source, string expectedDescriptor, ...)` the `expectedDescriptor` is not actually asserted. You can remove that optional argument or even change it to an invalid descriptor and the test still passes. Even if it did work, a string for which descriptors to assert may not be enough. As with some other tests, any descriptor with a location (most of them?) need to call `Verifier.Descriptor(...).WithMessage(...).WithSpan(...)` to be properly asserted since the equivalency is struct-style - or at least inclusive of the message and snap (not arguments, oddly).

**Comment by pakrym** [comment]
cc @AlexanderSher

**Comment by heaths** [comment]
For context,

1. In one existing test I delected the `expectedDescriptor` argument from `VerifyAnalyzerAsync` and the test still **passed**.
2. I changed the `expectedDescriptor` to a different descriptor ID and it still **passed**.
3. I deleted a descriptor created with `Verifier.Diagnostic` (I believe it returns a `DiagnosticResult` off hand) from *that* overload of `VerifyAnalyzerAsync` and then it **failed** because a warning was emitted and wasn't expected. So that overload works.

Looking at that, I think the problem is that the underlying asserts don't care about the string descriptor for expected results. Even if we changed that overload of `VerifyAnalyzerAsync` to create one from the string, the underlying equivalency assert at least checks the fully formatted message and the span, so giving just a string won't work even if there are no arguments. Perhaps there's some way to change the underlying assert, but it seems that's buried in an assembly we don't own and we'd have to work with the maintainers to update.

It may not be ideal, but we modify these so infrequently that it could work: I just ran the test, got the assertion error with the formatted message and span expects, visually verified they made sense, and used those values to better construct a descriptor that would pass the assert. See PR #1961 for an example.

**Comment by AlexanderSher** [comment]
@heaths , what test have you tried to change?

**Comment by heaths** [comment]
The tests I mentioned above were for AZC0001 but I also tried ACZ0008 and, IIRC, ACZ0009.

**Comment by AlexanderSher** [comment]
Ok, so looks like you've removed the descriptor but haven't removed the region, so test has applied the default descriptor, which was the same in this case. Not a false positive, but misleading. Also, when descriptor name is incorrect, that is indeed a false positive.

Luckily, right now you can specify descriptor id right in the source code.
