### ISSUE TITLE
Python APIView: public members of Python classes do not show

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#1964]
I have a Python class that creates a bunch of public properties in its initializer, but APIView does not display any of them.

```Python
class MyClass:

  def __init__(self, **kwargs):
    self.foo = kwargs.get('foo', None)
```

It would seem like this would severely limit the value of APIView for Python. I tried to use it to verify that regenerating Swagger only added a single new property, but instead it showed no diff.

**Comment by tjprescott** [comment]
If I change the docstrings from `:param` to `:ivar` then they appear in APIView. However, autorest generates everything as `:param`, so the question is what behavior is appropriate?

**Comment by tjprescott** [comment]
I found this: https://github.com/Azure/autorest.python/blob/4f33cb88a9480a9a743f4318c3c911b4a7725056/autorest/codegen/serializers/model_base_serializer.py#L54

```python
   def prop_documentation_string(prop: Property) -> str:
        # building the param line of the property doc
        if prop.constant or prop.readonly:
            param_doc_string = f":ivar {prop.name}:"
        else:
            param_doc_string = f":param {prop.name}:"
```

I don't know the rationale for why constants are ivar and everything else is param, but assuming it is sound, should APIView also expose params?  Or should we somehow examine the __init__ to determine what are actually properties, since it's entirely possible an init param could be consumed and not set on the object with `self.foo`.

**Comment by iscai-msft** [comment]
@tjprescott `param` basically means we accept this as an input parameter. `ivar` means it's a variable. Sometimes, the inputted param will also end up being a variable. Hope this clears it up!

**Comment by tjprescott** [comment]
Azure/autorest.python#1026 fixes this issue. Closing.
