### ISSUE TITLE
[eslint-plugin-azure-sdk] Anamolous behavior w.r.t the placement of `Copyright headers`  

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/azure-sdk-tools#199]
### Context

Added .eslintrc.json config and imported the `eslint-plugin-azure-sdk` to cosmos sdk in azure-sdk-for-js repo.
One of the things the plugin does is -
 adding license headers like below to all the relevant files when we run `lint:fix`.

`"lint:fix": "eslint package.json tsconfig.json src test samples --ext .ts --fix"`

![image](https://user-images.githubusercontent.com/10452642/65290940-22b3b480-db06-11e9-95a2-739bb5d2f6a9.png)

### Issue
Below is a screenshot of the changes in one specific file from the PR https://github.com/Azure/azure-sdk-for-js/pull/5151  that represents abnormal behaviour.
![image](https://user-images.githubusercontent.com/10452642/65290460-3eb65680-db04-11e9-990a-c03a59df1a88.png)
I would expect the Copyright headers to be at the first two lines.
The placement of these headers when a file starts with the JSDoc comments(`/** * * */`) is a little off. 

It would be great if this border-case can be fixed to make the plugin add the headers at the beginning of the file.

### Reference
https://github.com/Azure/azure-sdk-for-js/pull/5151/files 

cc - @ramya-rao-a @southpolesteve @KarishmaGhiya

**Comment by willmtemple** [comment]
This was fixed a while ago. The older copyright header fixer was trying to do some very complicated stuff. The new one just inserts the correct header at the very top of the file if it doesn't find an exact match, see : #247 . Once we get the plugin moved to the js repo, this should be gone. Issue to track merging the new plugin into our repo is here: Azure/azure-sdk-for-js#6226 . Closing this in favor of tracking the work in our repo.
