### ISSUE TITLE
[Python APIView] raise error if users pass in param docstring for class-level documentation

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-tools#1992]
Right now, apistubgen silently ignores param docstrings for class-level docstrings. apistubgen should at least let users know that this will be dropped by raising a linter error. Not quite sure if you want to support it, but should let users know that it will be ignored (at least for now).

**Comment by tjprescott** [comment]
@iscai-msft is this still an issue? Do you have an example so I can repro?
