### ISSUE TITLE
Docs metadata release should update preview package overviews to describe released packages

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#2005]
In cases where preview and GA versions for a package both exist the package overview for the preview version should state that there is a GA release and link to the moniker/page of the latest released version. 

* What should the copy be? 
* Will need to update preview pages on GA release via some kind of parsing (preview package overviews aren't published when GA releases for a given package today; those pages are only updated upon release of preview packages)

**Comment by mario-guerra** [comment]
My stab at what a callout should say:

"The Azure <insert library/package name> for <insert language> is now generally available (GA) and fully supported for production use. More details on the GA release can be found here <link to GA announcement post>.

**Comment by danieljurek** [comment]
After chatting with @mario-guerra, it is probably better for the customer experience (and certainly more straightforward to automate) linking to the GA package overview. Possible text: 

> The Azure Tables client library for .NET is now generally available (GA) and fully supported for production use. More details on the GA release can be found in the [GA documentation]\(link-to-documentation\)

**Comment by danieljurek** [comment]
Updated copy: 

```markdown
> [!IMPORTANT]
> The Azure Tables client library for .NET is now generally available (GA) and fully supported for production use. **The GA library should be used instead of this preview version to ensure you are using the most secure and performant version of the library.** More details on the GA release can be found in the [GA documentation](data.tables-readme.md)
```

**Comment by danieljurek** [comment]
Updated onboarding will eliminate these files which will result in automatic redirects to the `latest` or `legacy` moniker as needed. We won't need to edit markdown files in place.
