### ISSUE TITLE
[doc-warden] `sdk/*/<directory>` is matching too generically

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#2020]
`sdk/*/READMe.md` is matching readmes like `sdk/schemaregistry/azure-schemaregistry/README.md`.

This _should_ require the `**` glob pattern. Need to dig in an understand why.

This bug is the cause of confusion over in Azure/azure-sdk-for-js#16869

**Comment by weshaggard** [comment]
Unless it is critical and you are already investigating @scbedd lets let @chidozieononiwu look at this as pat of some similar issues he has.

**Comment by scbedd** [comment]
It's not critical (as they are running day to day with this bug), but we probably should fix sooner rather than later. 

@chidozieononiwu , [this is the problem](https://github.com/Azure/azure-sdk-tools/blob/a680f28d0f03c536c7a127c415bb9b0ca98b1dec/packages/python-packages/doc-warden/warden/warden_common.py#L30)

I've been waffling back and forth thinking about how to resolve this. I think the solution _may_ be to convert the simple globbing patterns to regex, then do a `re.match()` on the path. Let's chat offline when you have a few moments?

**Comment by ramya-rao-a** [comment]
Hello!
Any updates here?

**Comment by kurtzeborn** [comment]
At this point we're not going to fix this.  More likely, we're going to transition away from DocWarden entirely.
