### ISSUE TITLE
Common pattern for DevOps Template YAML convertToJson

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#2030]
We should have common patterns for use when calling `convertToJson` as it is possible that runtime substitutions will result in invalid JSON. 

In some cases providing runtime values to a yaml object which was converted to JSON using `convertToJson` may result in unescaped backslahes. For example: 

https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/pipelines/templates/steps/update-docsms-metadata.yml#L78

```
    $packageInfoJson = '${{ convertToJson(parameters.PackageInfoLocations) }}'.Trim('"')
```

If the value of `PackageInfoLocations` contains a runtime-evaluated macro-syntax variable (e.g. `$(Pipeline.Workspace)`) on a Windows machine this may, at runtime, expand into a string which has unescaped backslashes (e.g. `D:\a\_work\1...`). This is not an error in the `convertToJson` function because that function is executing before the macro-syntax variable is expanded. 

One possible fix is to use `-replace` to escape or overwrite backslashes at runtime after the macro-syntax variable has been expanded: https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/pipelines/templates/steps/sparse-checkout.yml#L75

```
        $repositories = '${{ convertToJson(parameters.Repositories) }}' -replace '\\', '/' | ConvertFrom-Json -AsHashtable
```

**Comment by aressler38** [comment]
This function doesn't produce valid JSON. The quotation marks are missing.

**Comment by kurtzeborn** [comment]
We've used this tool in more places since this was opened.  At this point there's not really a need to consolidate.
