### ISSUE TITLE
Make consistent the criteria for daily pipeline jobs

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#2037]
For example the criteria for JS' `PublishPackages` job which publishes dev packages is: 

```
or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['SetDevVersion'], ''), eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
```

While the .NET criteria for the similar `PublishPackages` job is: 

```
or(eq(variables['SetDevVersion'], 'true'), and(eq(variables['Build.Reason'],'Schedule'), eq(variables['System.TeamProject'], 'internal')))
```

It's unclear whether these criteria are different. They should be made as consistent as possible to smooth the process of editing these pipelines.

**Comment by weshaggard** [comment]
I don't believe `eq(variables['SetDevVersion'], '')` is interesting in the second part of this condition. It probably doesn't hurt the execution in our scenarios because we don't set that variable as a global variable for our scheduled builds, but it would be nice to remove it here as it just makes the conditions more complex then it needs to be.

**Comment by danieljurek** [comment]
* Indeed it is no longer relevant -- https://github.com/Azure/azure-sdk-for-js/pull/11476#issuecomment-699395920 
* The expression in .NET, Java, and Python are all the same, only JS is different

**Comment by kurtzeborn** [comment]
Triaging this... we're pretty sure that you (@danieljurek) have already fixed the place(s) where this happens.  If there is broader tools work to do here, please reassign to @chidozieononiwu.

**Comment by danieljurek** [comment]
Oh yes, this is merged here and it only impacts JS -- https://github.com/Azure/azure-sdk-for-net/pull/24199 

Closing.
