### ISSUE TITLE
Use rp-package instead of package for pipeline name in pipeline-generator tool

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-tools#2063]
When use 'prepare pipelines' to create pipeline for new RP, prefix parameter + directory path's last segment (always package name) is used for pipeline name according to https://github.com/Azure/azure-sdk-tools/blob/4b13cb8063e2d9e872f77684e0debdfc218fe1eb/tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/SdkComponentScanner.cs#L52. But some RPs may have the same last segment of the path (e.g. resources/armsubscriptions vs subscriptions/armsubscriptions) or we may change the module path which result in pipeline creation failure with duplicated name. Is it possible to use rp-package instead of package for pipeline name in pipeline-generator tool to solve such problem?

**Comment by benbp** [comment]
Resolved by https://github.com/Azure/azure-sdk-tools/issues/2474#issuecomment-1004213313 with a recommended approach to name files like `ci.resources.yml`.
