### ISSUE TITLE
Automatic onboarding of Track 1 documentation

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#2066]
We already are onboarding Track 2 documentation. Should we implement logic to update Track 1 package documentation onboarding (as in Java management packages like [`azure-mgmt-media`](https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/java-packages.csv))?

**Comment by weshaggard** [comment]
I don't even believe those track 1 mgmt packages even exist in the main branch any longer so we shouldn't do any work for them at this point.
