### ISSUE TITLE
API review comment should show larger diff using details tag

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#2081]
Currently comment on PR shows diff only if number of lines of change is less than 10. This creates a confusion why it shows diff sometimes and sometimes not. We should show the diff using  tag to add it in a collapsed panel.
https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2

<details><summary>Diff</summary>Diff details</details>

**Comment by kurtzeborn** [comment]
Doesn't apply any more.  We've addressed this with different feature implementations.
