### ISSUE TITLE
[Test-Proxy] Current default dev certificate will not work on `mac`

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#2090]
Shown in [this commit](https://github.com/scbedd/azure-sdk-for-python/blob/873624df6ea5a3fdff691330de45f969f456c1a7/eng/pipelines/test-with-proxy.yml#L70).

We exported our `pfx` using `pkcs12` format, while the mac keychain explicitly requires `x509`. We need to either re-roll a cross-compatible one, or simply split it out and use it.

**Comment by yeongseon** [comment]
@scbedd The following command failed on Mac. Is it same error you mentioned above?

dotnet dev-certs https --clean --import eng/common/testproxy/dotnet-devcert.pfx --password="password"

Cleaning HTTPS development certificates from the machine. This operation might require elevated privileges. If that is the case, a prompt for credentials will be displayed.
HTTPS development certificates successfully removed from the machine.
The provided certificate file 'eng/common/testproxy/dotnet-devcert.pfx' is not a valid PFX file or the password is incorrect.

**Comment by scbedd** [comment]
@yeongseon I believe so, yeah. Apologies for the lack of traction on the issue! I'll try to push a bit harder on getting access to a mac machine to debug this locally. I saw that @jeesang7 submitted a PR around this and I need a machine to actually validate it. 👍
