### ISSUE TITLE
Update index of tools in Azure-SDK-Tools

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#2105]
Add a md file that lists and describes the tools present in the Azure-SDK-Tools repo.

**Comment by kurtzeborn** [comment]
Assigning to @sima-zhu as a good one to get her started on in the tools space.

**Comment by chidozieononiwu** [comment]
Here is a [markdown table generator](https://www.tablesgenerator.com/markdown_tables) that @scbedd shared with me. hoefully this helps with creatiing/updating the large table.

**Comment by sima-zhu** [comment]
The contributing.md is done.
https://github.com/Azure/azure-sdk-tools/blob/main/CONTRIBUTING.md

Need to update the index of the tool readme.
