### ISSUE TITLE
[Eng] Publish mock-service-host as part of the infrastructure for auto testing

### ISSUE THREAD

**Issue by changlong-liu** [Azure/azure-sdk-tools#2110]
The mock-service-host is maintained in ADO repo: https://devdiv.visualstudio.com/DevDiv/_git/avs, and no NPM release.
Expect: move to azure-sdk-tools repo and setup NPM release pipeline.

**Comment by weshaggard** [comment]
@changlong-liu I assume this issue is completed now?

**Comment by changlong-liu** [comment]
Hi @weshaggard , I'm still working on publish to npm as @azure-tools/mock-service-host.  I think can complete this after npm released :)
