### ISSUE TITLE
[Eng] Publish mgmt test generator for auto test generation

### ISSUE THREAD

**Issue by changlong-liu** [Azure/azure-sdk-tools#2111]
The mgmt test generator is maintained in ADO repo: https://devdiv.visualstudio.com/DevDiv/_git/autorest.tests.

Expect: 
1. split the autorest.tests to two autorest extension:  1) testModeler as test middle layer, 2) gotest as GoLang test generator
2. move them to azure-sdk-tools repo and setup NPM release pipelines.

**Comment by weshaggard** [comment]
@tadelesh @changlong-liu we should close down the internal repo now so that we don't keep getting pinged about any issues that might show up there.
