### ISSUE TITLE
APIView - Show language filter as dropdown

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#2113]
Currently language filter is shown as button in APIView to filter reviews created for a specific language. 

![image](https://user-images.githubusercontent.com/55455725/137789381-b4e1aca7-eb6a-4d0e-9327-aeaca7203a90.png)

This was earlier helpful when we supported only 4 languages. But we have added more language support in APIView and this button list is growing. We should convert this to a dropdown instead of button list.

 Language : <dropdown>

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/2785
