### ISSUE TITLE
APIView - Add new UI option to group reviews

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#2114]
API reviews are listed as flat list. We should add option to group reviews based on their service and/or package name as tree level to easily find reviews. Currently all reviews doesn't have this metadata or package name service level so we may have to migrate some of these reviews to add any newly required metadata in cosmos DB.

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/2785
