### ISSUE TITLE
Class definition missing if part of Paging

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#2118]
See DeviceUpdate and Paging[DeviceClass]:
https://apiview.dev/Assemblies/Review/b140fe258e3049f8bbe831e65ad8ade2?doc=True&diffOnly=False#Azure.DeviceUpdateClientUpdatesListOperationsoverview

**Comment by mikekistler** [comment]
Closing as LLC View will be replaced with Swagger view.
