### ISSUE TITLE
Path parameters should go first

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#2119]
https://apiview.dev/Assemblies/Review/b140fe258e3049f8bbe831e65ad8ade2?doc=True&diffOnly=False#Azure.DeviceUpdateClientUpdatesListOperationsoverview

![image](https://user-images.githubusercontent.com/1050156/137816070-fdaad0cf-09ad-46f2-9cd4-330ead3c27f5.png)

**Comment by praveenkuttappan** [comment]
Investigate how parameters are ordered. Group should be the last one.

**Comment by mikekistler** [comment]
Closing as LLC View will be replaced with Swagger view.
