### ISSUE TITLE
APIView should have an option to choose persistent language preference 

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#2155]
APIView shows reviews created for all languages by default and user has to select appropriate filter if they want to view reviews for a specific language only. It will be a good option to store user preference and create default view based on user preference. User should still be able to select other languages or unselect to see reviews created for other langauges.

**Comment by praveenkuttappan** [comment]
Let's put this in backlog. Language param in URL is good enough to achieve this and any one who wants to see reviews for a specific language can use a bookmarked link to APIView with language param.

**Comment by mikekistler** [comment]
SImilar to "sticky filters" that are currently being implemented but this would be persistent.

**Comment by chidozieononiwu** [comment]
This has been resolved with the persistence of user preferences
