### ISSUE TITLE
Shared cspell dictionaries

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#2160]
Old name: Spell check REST API specs in the specs repo 

This should take the form of a central dictionary placed in eng/common and included by the .vscode/cspell.json files in each repo.

**Comment by kurtzeborn** [comment]
@danieljurek, this work that should probably be owned by the Shanghai team. I know you're already working with them on shared dictionaries, so maybe they're already tracking it.

**Comment by danieljurek** [comment]
Once we sync eng/common in azure-rest-api-specs this should be a pretty straightforward process. Closing for now as this work has not been a significant priority up to this point.
