### ISSUE TITLE
Auto merge bot not auto merging when there are no pipelines to run

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#2194]
See PR https://github.com/Azure/azure-sdk-for-js/pull/18446 which has the auto-merge label

There are no pipelines to run, so I ran the `/check-enforcer override` as recommended

But now the bot does not like that there were no pipelines to run

Anything we can do about this?

(I am merging the PR manually for now)

**Comment by weshaggard** [comment]
![image](https://user-images.githubusercontent.com/9010698/140975769-77dc7ecf-9829-4ff7-be29-fd40af19761f.png)
Based on the fabric bot setting I would have expected it to work after did the check-enforcer override. 

However based on the comment https://github.com/Azure/azure-sdk-for-js/pull/18446#issuecomment-955057577 the bot seems to be looking for some sort of pipeline status check which we don't have in these cases. I suppose we can report this scenario to the fabric bot team but honestly this feels like a pretty edge case and if you are already overrriding check-enforcer you can also go ahead and hit the merge button.

**Comment by weshaggard** [comment]
We are moving away from the fabric bot for automerge and now folks need to use the github built-in automerge feature.
