### ISSUE TITLE
[Test-Proxy] Only reserialize body if it was changed

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2213]
When using JSON Path sanitizers, there is [logic](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/RecordedTestSanitizer.cs#L95) in the .NET repo version of RecordedTestSanitizer to prevent reserializing if nothing changed - this allows the body to be completely unchanged with respect to whitespace and is also better for perf in the case that there are no matches for any JSON paths.

In [BodyKeySanitizer](https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs#L64), we don't have this logic so we always end up reserializing with NewtonSoft. Would it be possible to add the logic so that the original JSON is preserved when there are no matches?

Also, can we add a try/catch around the JSON body parsing like we have in the .NET Test Framework? The catch would just return the body as-is. This is needed since not all bodies are expected to be JSON and we add path sanitizers unconditionally in the base RecordedTestSanitizer in the .NET Test Framework.

**Comment by JoshLove-msft** [comment]
FYI I'd be happy to contribute this 😄

**Comment by scbedd** [comment]
1) I'd be happy to review if you submit that
2) This seems like a super straightforward change, so if you don't get to it by today, I should have a PR submitted.

**Comment by JoshLove-msft** [comment]
Sorry, I snuck in a second part to this issue that you probably didn't notice:
Also, can we add a try/catch around the JSON body parsing like we have in the .NET Test Framework? The catch would just return the body as-is. This is needed since not all bodies are expected to be JSON and we add path sanitizers unconditionally in the base RecordedTestSanitizer in the .NET Test Framework.

**Comment by scbedd** [comment]
Thanks for the clarity! On it.
