### ISSUE TITLE
Restore search live tests to use main testing subscription

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2216]
Due to an incident with the search RP, we were unable to provision search resources for live tests. In order to mitigate the issue, we had to switch the target region and/or subscription for deployments. The issue fix should be fully rolled out within a couple weeks, after which the following PRs can be reverted:

https://github.com/Azure/azure-sdk-for-js/pull/18512
https://github.com/Azure/azure-sdk-for-python/pull/21568
https://github.com/Azure/azure-sdk-for-net/pull/25113
https://github.com/Azure/azure-sdk-for-java/pull/25175

CC @alzimmermsft

**Comment by kurtzeborn** [comment]
We're not going to get to this anytime soon.  All the tests work.  No one is blocked by this.
