### ISSUE TITLE
Have common script/template for install dotnet tool

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#2225]
https://github.com/Azure/azure-sdk-tools/pull/2181#issuecomment-954218667

**Comment by kurtzeborn** [comment]
You may have already fixed this with the work you did to move us forward to .NET 6.

**Comment by konrad-jamrozik** [comment]
> You may have already fixed this with the work you did to move us forward to .NET 6.

Yeah, fixed by:
- #5045
