### ISSUE TITLE
[Test-Proxy] Default parameters in sanitizers are not used

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2231]
Not sure if this is by design, but the default parameter values for the various sanitizers are not being respected because we explicitly add null if the argument is not supplied:
https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Admin.cs#L150-L152

Initially, I thought it would be as simple as updating from:
```cs
  if (param.IsOptional)
  {
      arg_list.Add(null);
  }
```
to:
```cs
  if (param.IsOptional)
  {
      arg_list.Add(param.DefaultValue);
  }
```

But this causes some strange behavior due to the regex param being defaulted to ".*" in the BodyKeySanitizer. In my case, I am just trying to replace a json path token with "Sanitized", but when I made this change locally, it replaced the token with "SanitizedSanitized". So for now, I will just supply "Sanitized" in my request, but we may want to look into making the defaults work, and considering whether the various defaults make sense or not.

**Comment by scbedd** [comment]
Defaulting is actually working as expected. 

We got [bitten by this, essentially.](https://stackoverflow.com/questions/52351217/why-do-some-regex-engines-match-twice-in-a-single-input-string)

Fixed in #2295
