### ISSUE TITLE
[Test-Proxy] docker-start-proxy.ps1 uses wrong directory to find repo root

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-tools#2250]
The `docker-start-proxy.ps1` script will store recordings differently depending on where it's executed from. For example, tests for `azure-data-tables` end up in
```
azure-sdk-for-python/sdk/tables/azure-data-tables/sdk/tables/azure-data-tables/tests/recordings
```
instead of
```
azure-sdk-for-python/sdk/tables/tests/recordings
```
if `docker-start-proxy.ps1` is executed from the `azure-sdk-for-python/sdk/tables/azure-data-tables` directory instead of the `azure-sdk-for-python` directory.

**Comment by scbedd** [comment]
@mccoyp It accepts the target folder as a second argument. I will change the default behavior from `current_folder` if unset to `root of repo` if unset.
