### ISSUE TITLE
[Swift APIView] Comments appear multiple times and not in the location clicked

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2254]
https://apiviewstaging.azurewebsites.net/Assemblies/Review/2ff7a94a8fa549ee857632931072fed0

The comment about `isRecordingActive` appears (correctly) once in the Conversation tab, but multiple times in the normal or diff views. The comment should appear on line 274 (only) but also appears on lines: 250, 305, 367, 389, 400.

It appears anywhere that `unowned(unsafe) open var delegate` appears, regardless of the type, implying something is wrong with how Swift APIView is setting line ids.

**Comment by kurtzeborn** [comment]
My understanding is that the mobile team added swift support and is supporting it, so adding "Client" label.  if this needs/requires @praveenkuttappan's attention for some reason, go ahead and switch "Client" to "Central-EngSys".

**Comment by praveenkuttappan** [comment]
This issue occurs when line ID created is not unique. This should be fixed in the parser to ensure each line ID where we support creating a comment is unique.
