### ISSUE TITLE
[Python APIView] CI test stage does not fail on actual test failure

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2256]
![image](https://user-images.githubusercontent.com/5723682/141361326-c0d69682-0951-4c47-8112-cf154f7bd20f.png)

However, the test stage and the PR overall are marked green by the CI.
https://github.com/Azure/azure-sdk-tools/pull/2255

**Comment by praveenkuttappan** [comment]
@scbedd has fixed this issue. Thanks a lot for the fix.
