### ISSUE TITLE
[APIView] Should not create automatic diff if the only difference is tooling number

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#2275]
Example:
https://apiview.dev/Assemblies/Review/18826b88a9ba482fab51d53572e740a6

![image](https://user-images.githubusercontent.com/1050156/141863633-d09a7d88-e941-4482-adf6-23eaa5615f07.png)

**Comment by praveenkuttappan** [comment]
I can wrap this line around no diff tags which will ignore the line when diffing by auto revision. But this issue must have happened when it's not able to refresh previous revision automatically using latest parser.
