### ISSUE TITLE
[APIView] Get clarity on the version showed in APIView

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#2277]
https://apiview.dev/Assemblies/Review/69ab82637bf547faab80cf1ad639dc01

You could see the only version we see is 1.1.26 for azure-common
![image](https://user-images.githubusercontent.com/1050156/141864141-8fd33a33-8fee-4f7f-afae-6b4dc660cee9.png)

The last regeneration is from "2 hours ago", which means 11/15/2021 morning.

However, the last release was 1.1.27 in march 2021. The diff showed in the view is actually the diff from 1.1.26 to 1.1.27. It's unclear why the automatic view is pinging this now, and do not reflect that there is a 1.1.27 released 6 months ago.

**Comment by praveenkuttappan** [comment]
Latest revision is getting refreshed every day if that revision is not approved. I think that's causing confusion here Solution is to avoid refreshing latest revision if it matches irrespective of it's approval status. Second change is to include the version instead of SHA in revision.

**Comment by WhitShake** [comment]
Complete
