### ISSUE TITLE
[APIView] Add release metadata to API

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#2278]
To make easier the discovery of the work to do, each API should be corralated with planned releases.

- Each API should have a deadline (to help prioritize) that should be visible on the APIView table, and possible to order using it
- Each API should have a tag GA/preview, to tell what the next release will be for this view

This could be connected with the release script for instance, or other mechanism

**Comment by praveenkuttappan** [comment]
API review revisions are correctly tagged as per package version and release metadata.
