### ISSUE TITLE
[APIView] Assign view to architects

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#2281]
Similarly to PR on Github, it should be possible to asign a view to someone. This would allow:
- To know if there is "view that needs architect now" (in combination with #2278)
- To know if Anna/Johan has took ownership of a review

In particular, in the automatic view, the "uploader" column brings no value since it's always azure-sdk. Having an assignee information that we can order would be helpful.

**Comment by maririos** [comment]
@chidozieononiwu what is the work that needs to be done from our side for this issue to be addressed?

**Comment by JonathanGiles** [comment]
We need a UI that allows for assignees to be selected and assigned to a review. This may be similar to the existing GitHub UI:

![image](https://user-images.githubusercontent.com/1427840/180689125-67f94a8c-b977-4f26-82e0-89c025fc9d65.png)

The suggestions should be based on the language of the review (no point proposing Java architects for Python reviews!). 

Once a review is assigned to an architect (or multiple architects), APIView should send an email to those people to request a review, detailing who requested the review and providing a link for the architect to follow to access the review. Additionally, the review should show some text stating who has been requested to review.

**Comment by JonathanGiles** [comment]
Here is a quick summary of how I would consider implementing this (in case the Massey 2022 students I'm working with want to take this on):

* All reviews would have a "request review" button.
* APIView would need to know which architects own which languages.
* There will be a "pending reviews" page, like the main reviews page, that will show all pending reviews for the currently logged in user, which is all pending reviews for their language, minus the ones they have already reviewed.
* When a review is requested, all people for that language will get an email notification.

There would be some technicalities about when a pending review stops being pending (is it when one approval happens?). Also, how can someone re-request review, etc.

**Comment by Baas-hub** [comment]
@JonathanGiles I'll take on this issue
