### ISSUE TITLE
Need "fix" documentation for Avocado

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2291]
The "How to Fix" link for Avocado in the azure-rest-api-specs repo currently just links to the Avocado repo.

![image](https://user-images.githubusercontent.com/85643503/142071716-6f4838fe-1181-405d-bb66-41dc1ca0972b.png)

We should have a page that describes how to fix problems reported by Avocado and link to that page here, as we do with the other CI tools.

**Comment by weshaggard** [comment]
I actually suggest we stop output this generic help text and just start adding better error messages with links to the correct contextual docs when there are failures in the CI.

**Comment by akning-ms** [comment]
Yes. Thanks Mike for good catch.  @ruowan to fix the link. 
Hi Wes, we still not finalize , basic idea is: we may route support request to our team channel when service team need to reach us  for help even read how to fix doc.

**Comment by ruowan** [comment]
Will be fixed in this PR: https://github.com/Azure/azure-rest-api-specs/pull/16770
