### ISSUE TITLE
[BUG] Remove-TestResources.ps1 script fails to run

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-tools#2299]
**Describe the bug**
Remove-TestResources.ps1 script fails to run and cleanup test resources.

**Expected behavior**
The script runs successfully

**Actual behavior (include Exception or Stack Trace)**
The script fails to run because it calls the function `Get-PurgeableGroupResources` which calls the missing function `Get-AzKeyVaultManagedHsm`

**To Reproduce**
> .\eng\common\TestResources\Remove-TestResources.ps1 <service-name>

Get-PurgeableGroupResources: C:\azure-sdk-for-net\eng\common\TestResources\Remove-TestResources.ps1:220
Line |
 220 |  $purgeableResources = Get-PurgeableGroupResources $ResourceGroupName
     |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The term 'Get-AzKeyVaultManagedHsm' is not recognized as a name of a cmdlet, function, script file, or executable program. Check the spelling of the name,
     | or if a path was included, verify that the path is correct and try again.

**Comment by weshaggard** [comment]
The version requirement will at least give folks an idea of what needs to happen.

**Comment by heaths** [comment]
The more I think about this, I believe there was a reason why I might not have. @mikeharder didn't we have some conversation about this a while back before you made changes to try to load newer Az modules from outside the `$env:PSModulePath`? I could be crossing wires on something unrelated, though. Just want to double check.

Whatever the case, I wonder if we actually just want to take a dependency on an `Az` module that has dependencies on at least the versions of `Az.*` modules we want. While users can install individual `Az.*` modules directly - which is what the error might infer - it's best just to update them all.

**Comment by weshaggard** [comment]
For DevOps we have some helpers for using the cached Az modules or installing as needed, see https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Import-AzModules.ps1. If we need a newer version we should update the version in that script.

**Comment by heaths** [comment]
This runs as a separate task earlier in the pipeline, right? As long as modules can still be resolved via `$env:PSModulePath` then a `#Requires ...` statement should still work.

But updating only that script isn't enough. Humans don't run that script. So the `#Requires` still needs to be in the `New-TestResources.ps1` script.

**Comment by heaths** [comment]
Currently we load Az 5.7.0, which depends on Az.KeyVault 3.4.1 which includes `Get-AzKeyVaultManagedHsm`. So I think we could safely add that as a dependency (min version). @Mohit-Chakraborty could you confirm that you had an older version. The below command will show all versions in case you already upgraded (alas, PSGet does not prune older versions because there's no ref-counting of older deps):

```powershell
get-module -list Az.KeyVault
```

**Comment by kurtzeborn** [comment]
Pretty sure this was addressed with this PR: https://github.com/Azure/azure-sdk-tools/pull/2306

Please reactivate if the issue continues.
