### ISSUE TITLE
[Test-Proxy] Create custom matcher, ignore all headers during matching

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#2303]
@HarshaNalluru 

This is what the JS team does for their existing recording framework. Is there anything blocking from making this the default experience from everyone using the test-proxy?

@seankane-msft 
@JoshLove-msft 
@mccoyp 
@YalinLi0312

**Comment by HarshaNalluru** [comment]
This works if the recorder follows a stack approach by removing the requests(and responses) that are were answered for the requests during playback. And since the requests follow the same order.

Removing the requests won't work for perf test framework, but should be good for recorder framework.

Providing a matcher might be enough for differentiating as needed.

**Comment by JoshLove-msft** [comment]
I'm not sure I understand the full context here. How does one specify a custom matcher?

**Comment by scbedd** [comment]
@JoshLove-msft `/Admin/SetMatcher`. Works on both session/individual recording.

Right now the only custom one supported is `BodilessMatcher`, no arguments.

**Comment by JoshLove-msft** [comment]
Ah so you're asking whether specifying a matcher should mean that headers are ignored? Personally, I'd rather not do this as depending on the matcher there might be different implications for headers, e.g. for BodilessMatcher, we ignore the value of content-length, but still care that all the other headers match.

**Comment by scbedd** [comment]
Context: Harsha wants to ignore headers entirely when matching.

This issue exists to provide a specific matcher to do so, but it won't be the **default** matcher. I personally am a bit concerned about making it the default, as I'm certain that there ARE cases where the headers will have to be used stack-approach or no stack-approach.

I am just adding some tests, but will have a PR ready that will give further context.

**Comment by JoshLove-msft** [comment]
I don't see why we would ever want to ignore headers entirely - what is the scenario where this is required?

**Comment by scbedd** [comment]
@JoshLove-msft it's how the JS team has recorded their tests so far 🤷. Harsha has been fighting a bunch of these small issues, and would prefer to return to how they did it before.

I don't mind providing, I don't think I'll make it the default.

**Comment by JoshLove-msft** [comment]
Ah I see - in that case, we should probably make it clear that you should not use this. I wouldn't want other languages to see it and start using it. Maybe we can prefix the matcher name with "Dangerous" 😆

**Comment by HarshaNalluru** [comment]
Hmmm.
How about an API instead to pick the headers that are supposed to be excluded while matching during playback?
There are some that are excluded already, we'll add more headers as needed if we ever end up with some dynamic header.

**Comment by JoshLove-msft** [comment]
Yes, this would be useful - being able to add headers to the list of excluded ones.

**Comment by JoshLove-msft** [comment]
I ran into an issue where I will need this ability for the Connection header. This is only sent in Net Framework for the first request in a connection.

This is different than just ignoring the header value, I need to actually ignore the presence of the header.

**Comment by scbedd** [comment]
And specifically, we want to _keep_ the header present right? It's like

> ignore during matching, but don't necessitate that it's sanitized away to get that behavior

I'll just add to the current PR.

**Comment by HarshaNalluru** [comment]
> And specifically, we want to keep the header present right?

Could be irrespective of its presence.
- Record has a header, we don't want to match that header during playback with the API
- Record has that header removed with a sanitizer, we still don't want to match it during playback. [Currently, proxy-tool throws if a new header is added in playback that is not present in the record]

So, basically, doesn't matter if the header is present or not in the recording, if we say it should not be matched during playback with the new API, it should be respected.
