### ISSUE TITLE
[Test-Proxy] Add explicit response header for mismatch in Playback

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2309]
Currently, a 404 is returned along with the actual exception message as part of the response body. It would be great to include a response header that can be used to help identify that this is a 404 coming from the proxy, as opposed to a 404 from a service.

**Comment by scbedd** [comment]
Ack. Frustrated I dropped this on the floor. Thanks for the issue.

**Comment by JoshLove-msft** [comment]
No worries!

**Comment by JoshLove-msft** [comment]
This has been fixed.
