### ISSUE TITLE
Create hooks for smoke test v2 language automation

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2314]
Design/document/implement scripts and/or configuration to support the smoke test v2 work happening in the language repos. Our smoke test pipeline should support a common model that all the language implementations can leverage (e.g. common script entrypoint, pipeline entrypoint for dependencies, etc.) in order for us to create and run smoke tests.

**Comment by kurtzeborn** [comment]
This is old and we've done what we intended to do here.  Closing.
