### ISSUE TITLE
[Python APIView] CI should have an end-to-end token generation test

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2315]
The CI pipeline for apistubgen does not have any end-to-end test, only a small assortment of very narrow unit tests. However, the azure-sdk-for-python repo does run apistubgen on every build. As a result, regressions that could have been caught at the PR level in this repo are not caught until a PR is merged and Python SDK builds start failing.

We should have a stage in the CI pipeline that runs apistubgen on some "representative" service(s) so that regressions can avoid being introduced. Manual testing is not a reliable solution.

**Comment by kurtzeborn** [comment]
Bugs in language tokenization should be followed up on by that language team.  @praveenkuttappan is available to consult if needed.

**Comment by tjprescott** [comment]
This is not an issue about specific bugs in language tokenization. The purpose of this issue is to add a stage to the CI such that regressions are not introduced. Right now, the APIView CI lets regressions get through which are not caught until PRs on the Python SDK repo start failing. If a change to APIView is going to break all of the SDK builds, it should be caught here by the CI.

**Comment by weshaggard** [comment]
That is fair @tjprescott. I will add however we are planning to move the tokenization outside of ApiView itself and it will be part of the language repos so that would be the best place to add those tests once that work gets completed.

**Comment by tjprescott** [comment]
This issue has struck again today.

**Comment by praveenkuttappan** [comment]
We can add a pipeline that run apistubgen against all packages.

**Comment by tjprescott** [comment]
This is done.
