### ISSUE TITLE
[Swift APIView] Add tests to Swift APIView and CI

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2325]
Work item for MQ:
- [ ] Add unit tests to Swift APIView
<del>- [ ] Add pipeline stage to APIView pipelines</del>
<del>  - [ ] build</del>
<del>  - [ ] run tests</del>

**Comment by tjprescott** [comment]
CI-related items will be tracked under https://github.com/Azure/azure-sdk-tools/issues/2532

**Comment by tjprescott** [comment]
CI-related items will be tracked under https://github.com/Azure/azure-sdk-tools/issues/2532

**Comment by kyle-patterson** [comment]
Closing as duplicate of #2532
