### ISSUE TITLE
[Test-Proxy] Add error handling

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2328]
There are a few places where an unhandled exception can be thrown and the output we get back contains only:
```
Status: 500 (Internal Server Error)

Headers:
Date: Sun, 21 Nov 2021 02:47:04 GMT
Server: Kestrel
Content-Length: 0
```

It would be helpful to catch these exceptions and add the error information into the response that gets returned.
One such case can happen in record mode if the upstream host does not exist:
https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs#L143

Another example is when starting playback the file does not exist:
https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs#L272

In this second example, we should probably be throwing a TestRecordingMismatchException if the file doesn't exist.

**Comment by JoshLove-msft** [comment]
I don't think this is completely fixed. I just ran into another error that isn't propagated at all when an exception is thrown due to having a null `originalValue` here - https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Sanitizers/BodyKeySanitizer.cs#L67

In this case, the test finishes but nothing gets recorded.

**Comment by JoshLove-msft** [comment]
Patched specific issue here https://github.com/Azure/azure-sdk-tools/pull/2374, but ideally we would have every possible exception throwing line of code in a try/catch.

**Comment by pakrym** [comment]
https://docs.microsoft.com/en-us/aspnet/core/web-api/handle-errors?view=aspnetcore-6.0
