### ISSUE TITLE
Add Rest API review support into APIView

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#2342]
We need to you add support for review swagger files inside of APIView. A basic starter prototype is at https://github.com/Azure/azure-sdk-tools/pull/1949. 

Basic requirements:
- Should be able to display the swagger 
- Should be able to show a diff against existing or older api versions of a swagger
- Need to enable comments and discussions
- Need to enable review approval for the API.

**Comment by tg-msft** [comment]
I have a draft PR at https://github.com/Azure/azure-sdk-tools/pull/1949 with a very basic swagger view handling showing what I see as the P0:

![image](https://user-images.githubusercontent.com/1179329/144340353-61afcacf-a66e-4bfb-8ce5-70eaa3acc47a.png)

**Comment by zhenglaizhang** [comment]
@tg-msft yes, thanks! I am now starting to some more enhancement based on your draft PR

**Comment by maririos** [comment]
Adding intial requirements:

- **[Done]** Should be able to display the swagger
- Should be able to show a diff against existing or older api versions of a swagger. Issue https://github.com/Azure/azure-sdk-tools/issues/4210
- **[Done]** Need to enable comments and discussions

@praveenkuttappan for status on:
- Need to enable review approval for the API.
