### ISSUE TITLE
Document generation reports succeeded, but docs are not found

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#2358]
In PR [#16705](https://github.com/Azure/azure-rest-api-specs/pull/16705) the pipleline reports that it succeeds, however the docs do not appear to be generated and/or in the right place. 

![image](https://user-images.githubusercontent.com/522116/144258474-c1aec93e-d41d-4be7-ac42-90d8c228f831.png)

![image](https://user-images.githubusercontent.com/522116/144258570-b1a208fd-00a1-414c-96d3-59bec4391f67.png)

![image](https://user-images.githubusercontent.com/522116/144258661-8d0244e8-690f-464d-806f-83a2ab7864f3.png)

**Comment by weshaggard** [comment]
@akning-ms @zhenglaizhang who on your side is the right person to investigate this?

**Comment by zhenglaizhang** [comment]
> @akning-ms @zhenglaizhang who on your side is the right person to investigate this?

@weshaggard I will take a look at this

**Comment by zhenglaizhang** [comment]
Hi @markweitzel I talked with docs team, it's due to the side effect of docs side config branch manual cleanup, I didn't realize that the removal of config branch will leads to page deletion. Now your preview is recovered https://github.com/Azure/azure-rest-api-specs/pull/16705#issuecomment-963483678
I will use a safer way to do the cleanup automatically.

**Comment by markweitzel** [comment]
Great! Thank you for looking at this so quickly. 

One quick question... What is required of a team to regenerate their docs if the link does not work? I'd like to be able to instruct a team and/or do it for them. 

Also, if this is fixed going forward, please feel free to close the issue.

Thanks

**Comment by zhenglaizhang** [comment]
> Great! Thank you for looking at this so quickly.
> 
> One quick question... What is required of a team to regenerate their docs if the link does not work? I'd like to be able to instruct a team and/or do it for them.
> 
> Also, if this is fixed going forward, please feel free to close the issue.
> 
> Thanks

You just need to comment PR with `/azp run` to rerun the generation, e.g. https://github.com/Azure/azure-rest-api-specs/pull/16705#issuecomment-984839875
Yes going forward I wont remove such branches, so there wont be such problem, closing the issue.
