### ISSUE TITLE
APIView: dashboard to latest approved version of packages per language

### ISSUE THREAD

**Issue by xirzec** [Azure/azure-sdk-tools#2361]
I would like a simple table (filtered by language and perhaps searchable) that simply lists the latest approved API version of each known package. 

The motivation here is to quickly know if a package has been approved for a particular major release or not (vs only having beta surface approved)

**Comment by maririos** [comment]
@xirzec with the new filters in place, do you find you can achieve this?
i.e. https://apiview.dev/?languages=JavaScript&state=Open&status=Approved&type=Automatic&pageNo=1&pageSize=50

**Comment by xirzec** [comment]
> @xirzec with the new filters in place, do you find you can achieve this? i.e. https://apiview.dev/?languages=JavaScript&state=Open&status=Approved&type=Automatic&pageNo=1&pageSize=50

Ooo! This is very nice. Is there any way we can control the result ordering? The default sort of using the "Last Updated" column makes a lot of sense when looking for things to approve, but when looking at old approvals, "Name" might be nicer

**Comment by maririos** [comment]
Not currently but we do have issue https://github.com/Azure/azure-sdk-tools/issues/2282 to trak sorting of columns

**Comment by maririos** [comment]
@xirzec I am closing this issue. If there is work to be done different from sorting columns, feel free to re-open
