### ISSUE TITLE
[Test-Proxy] Need a way to conditionally sanitize the body based on the URI

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2369]
For Identity tests, the entire request body is sanitized if the URI ends with /token. As far as I can tell, this isn't supported with any of the existing sanitizers.

See - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/tests/IdentityRecordedTestSanitizer.cs#L18

**Comment by scbedd** [comment]
I started working through through both #2338 and this one at the same time. Early preview for how I'm going to extend `sanitizers` and `transforms` both. Not so applicable to `matcher` the way I'm thinking about this unfortunately.

Starting with UriRegex only before branching out to header and body vlaues.

```
POST Admin/AddSanitizer
{
 "value": "replacement",
 "regex": "<regex>",
 "apply-conditions": {
  "uriRegex": "<some regex">
 }
}
```
