### ISSUE TITLE
[APIView] have new APIView versions regenerate old automatic revisions

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-tools#2371]
Right now, when looking and signing off on automatic apiviews, there are both apiview version differences and actual sdk changes. It would be great everytime a new apiview version came out, all past autoatmic apiviews that have been created can be regenerated with the new apiview version, this way automatic apiview diffs will always only show the actual sdk changes

**Comment by tjprescott** [comment]
Alternatively, if an APIView was started with an older version, keep that version for revisions.

**Comment by praveenkuttappan** [comment]
This is already built in as part of APIView. But auto upgrade of existing review was clashing with new revision request from CI builds. We have successfully rebuilt all existing reviews for Python when parser was upgraded to 0.2.9
