### ISSUE TITLE
Update variable group on existing or new pipelines

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#2373]
Docs.Ms is trying to use variable group for docker id + secrets.

It is currently putting under **Release Github IO secrets** group. Close but not accurate.

**TODO:**
Need to update to pipeline-generator.yml and prepare-pipeline.yml, so we can add new variable group to all existing pipeline.

**Comment by weshaggard** [comment]
I think this was accidentally closed as part of the other PR, so reopening to track using the correct variable group.
