### ISSUE TITLE
[Test-Proxy] Custom Default Matcher needs to have Ignored Headers in addition to excluded headers

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2379]
Right now it only has excluded headers which doesn't take the presence or absence of the specified headers into account when matching. Ignored Headers _does_ consider the presence but ignores the values.

It also needs ignored query parameters.

**Comment by scbedd** [comment]
Just a heads up @JoshLove-msft `ExcludedHeaders` is [being used like](https://github.com/Azure/azure-sdk-tools/blob/5d02fb9f16efed1e3c2a9e24076004884c1aee0b/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs#L123) `IgnoredHeaders` in the [current `RecordMatcher`.](https://github.com/Azure/azure-sdk-for-net/blob/a9925c97e0ff9de2f11e15492afb5c37b79fd528/sdk/core/Azure.Core.TestFramework/src/RecordMatcher.cs).

**Comment by JoshLove-msft** [comment]
No, ExcludedHeaders is different because it doesn't even check for the presence of the header.

**Comment by scbedd** [comment]
Understood. I'm not saying we shouldn't do that, just that it's not implemented like that currently.

**Comment by JoshLove-msft** [comment]
Do you mean it's not doing that in the .NET test framework, or in the Test Proxy?

**Comment by JoshLove-msft** [comment]
Ah I misunderstood - yes, I think we need to update Test-Proxy to have the different behavior for these two.
