### ISSUE TITLE
[stress] Single dashboard with a breakdown of the test job status

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#2386]
As part of finalizing the first phase we want to have a simple dashboard that leads can look at to see all of the active tests in the cluster. Right now the tests are run at least once a week, which means we can just scrape the cluster stats (maybe for a couple of weeks) and display:

| Test name | Started On | Time running | LastStatus |
|------------|------------|------------|------------|
| go-sb-infinitesend | 2021-12-01 | 1d | Active |
| go-sb-infinitesend | 2021-11-28 | 3d | Failed |

This should give enough starting information for leads to get an idea of how far along things are, which tests are running, etc...

**Comment by benbp** [comment]
@ckairen this will be a good task for learning KQL and more about all the different telemetry sources from the stress tests and cluster services.

**Comment by richardpark-msft** [comment]
Just a note, a new set of tests is going to deploy _each_ week. There'll need to be some simple way of tracking a set of tests, and not just showing them all at once.

**Comment by benbp** [comment]
Tests have a `deployId` label which is set to the deployment date (`YYYYMMDD.REVISION`), so we could parse that. Also we could add another label and/or grab the actual kubernetes deployment date and bin that.
