### ISSUE TITLE
[Test-Proxy] Cross-compile the proxy to .NET 5.0, revert `docker` to take advantage of .NET 5.0

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#2394]
Be aware that after we do this,  in `ItemGroups` that define output files, we will need to be aware of the targetframework. This may affect testing and the like.

This will reduce image sizes back to pre `core-3.1` downgrade.

**Comment by pakrym** [comment]
At this point is it worth using the .NET 6?

**Comment by scbedd** [comment]
Yep. And we actually successfully upgraded to .NET 6. However, it's not natively on our build machines, so without the custom .NET `Use .NET Version` that actually downloads it, we can't just use it without installing a .NET version.

A PR is attached that will cross-compile to .NET 5, which will unblock standard tool usage in CI, but still leave you folks able to consume as part of your test project.
