### ISSUE TITLE
[Test-Proxy] Builds of test-proxy should automatically update it's version in language repos

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#2400]
Allows everyone to be up-to-date and avoid regressions.

For example, this is what we do with Autorest https://github.com/Azure/azure-sdk-for-net/pull/25630

@scbedd

**Comment by pakrym** [comment]
Implementation for autorest is in https://github.com/Azure/autorest.csharp/blob/feature/v3/eng/pipelines/build.yml#L121-L145

cc @josh-love

**Comment by benbp** [comment]
Potential dup with the larger issue https://github.com/Azure/azure-sdk-tools/issues/2347. @weshaggard do you want to merge or track this under that?

**Comment by weshaggard** [comment]
Yes this is just one instance of that larger issues. Lets keep this issue open to track this specific tool updating process.

**Comment by scbedd** [comment]
We follow the `eng/common` workflow for this.
