### ISSUE TITLE
[TestProxy] Receive a 404 for batch requests in Tables

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-tools#2403]
Requests targeting the batch group of operations return a 404 without logging a `Played Back` request (shown in `docker logs`)

Steps to reproduce:
* Check out branch `seankane-msft/tables-cov`
* `AZURE_RECORD_MODE=playback`
* Run `go test -v -run BatchAdd`

Note: There might be other failures in this test (batching was previously live only, trying to migrate to recorded test), but it should not return a 404.

**Comment by scbedd** [comment]
1) previous unexpected errors have been resolved.
2) we're now failing matching in an explicit and expected way.

I have provided an update commit [here](https://github.com/seankane-msft/azure-sdk-for-go/commit/3547b93641c6966aebedf051b08745754f9e71fd) that gets us to errors that make sense, and we need to determine our strategy when handling the batch body.
