### ISSUE TITLE
Bot posting duplicate comment thanking external contributors

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#2429]
See https://github.com/Azure/azure-sdk-for-js/pull/19129

You will see 2 comments from the bot thanking external contributors

This might be related to the Impact++ label

cc @jsquire

**Comment by jsquire** [comment]
Yeah, this was a result of the `Impact++` rule.   I've updated it to assign the tag but no longer emit a message.  We shouldn't see duplication going forward.

**Comment by jsquire** [comment]
ot

**Comment by ramya-rao-a** [comment]
Thank you!
