### ISSUE TITLE
[Test-Proxy] Consider adding ability to skip recording request body/entire request

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2434]
In .NET Test Framework, there is a [feature ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/TestRecording.cs#L445) where you can skip recording either an entire request, or a request body. This is useful for large request bodies where the content is not meaningful, e.g. form recognizer has a [test ](https://github.com/Azure/azure-sdk-for-net/blob/823e5e76060452a50df1172be067dde5cce55ab4/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/RecognizeReceiptsLiveTests.cs#L348) where the request body is just an empty pdf. For now, I'm using the Test Framework implementation when using the Test Proxy for now, but we should consider moving this into Test Proxy so all languages can use the feature.

**Comment by kurtzeborn** [comment]
@JoshLove-msft, looks like you already have a PR for this, so assigning to you.

**Comment by catalinaperalta** [comment]
@scbedd Python Form Recognizer also needs this, should I open a separate issue?

**Comment by scbedd** [comment]
Nope! It's the same problem.

**Comment by JoshLove-msft** [comment]
To be clear, the PR that I had linked was implementing this in the .NET Test Framework in its integration with Test Proxy. I can submit a separate PR that adds this feature to the Test Proxy.

**Comment by scbedd** [comment]
I would really appreciate this Josh, as it's definitely something that the test-proxy needs.

**Comment by JoshLove-msft** [comment]
Sure, my thought was to just have another custom header that we include in the request headers to signify that the body should not be recorded.

**Comment by scbedd** [comment]
Something like `x-recording-skip` or the like. Yeah, sounds good.

**Comment by JoshLove-msft** [comment]
We should also add the option to avoid recording the entire test - this is useful for teardown scenarios.
/cc @heaths

**Comment by JoshLove-msft** [comment]
maybe x-recording-mode:
- skip-body
- skip

**Comment by heaths** [comment]
In the case of Key Vault, we call `using (Recording.DisableRecording()) { }` in a few places like with LROs or clean-up to avoid putting a lot of unnecessary entries in JSON recordings. This *significantly* reduces the size of recordings.

For now, I only need to update a few tests and have commented out our old way, but switching everything over to use a non-instrumented client would take quite a while and, so close to release, I'm not keen on risking test coverage. It might be just fine using a non-instrumented client, but will take time to know for sure and we don't have a lot of time.

Seems like the ability to stop recording some request/responses would be generally useful as well.
