### ISSUE TITLE
Enhance snippet generator to include using directives

### ISSUE THREAD

**Issue by scottaddie** [Azure/azure-sdk-tools#2438]
We can improve customers' Track 2 SDK getting started experience by displaying the required `using` directives in each of our README code samples. See [this related issue](https://github.com/Azure/azure-sdk-for-net/issues/25763). To get there, the snippet generator tool should include the necessary C# `using` directives. This should be the default behavior.

There may be some cases in which `using` directives aren't as useful to display. To support those cases, a new command-line option should also be provided to opt out of including the `using` directives.

With the proposed enhancement, the following code sample:

```csharp
var client = new LogsQueryClient(new DefaultAzureCredential());
```

Would look like this:

```csharp
using Azure.Identity;
using Azure.Monitor.Query;

// code omitted for brevity

var client = new LogsQueryClient(new DefaultAzureCredential());
```

The standard `System.*` namespaces should be filtered out.

**Comment by jsquire** [comment]
That would not be compilable in the requested form, and would defeat the mandate for snippets that they be copy/paste to compile.   The work-around for this would be to create a separate snippet for using statements and a section in the README / Sample explicitly for usings.  I like the clarify that you're going for and would recommend bringing this up for discussion with the architects to be codified in the guidelines for docs.

As this is not a suggestion that we'll move forward with, and this repository doesn't define guidelines for samples, I'm going to close this out.
