### ISSUE TITLE
[Test-Proxy] Unable to find a record for the request because of quote encoding

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-tools#2441]
Proxy is not finding a request most likely because of the a URL encoding of the request.

Message: 
```
{"Message":"Unable to find a record for the request PUT https://fakeaccountname.blob.core.windows.net/gocblobstartcopydestempty?restype=container\nUri doesn\u0027t match:\n    request \u003Chttps://fakeaccountname.blob.core.windows.net/gocblobstartcopydestempty?restype=container\u003E\n    record  \u003Chttps://fakeaccount.blob.core.windows.net/gocblobstartcopydestempty?restype=container\u003E\nHeader differences:\nBody differences:\n","Status":"NotFound"}
```

Proxy Version: `1209124`

Steps to reproduce
1. Check out the branch `seankane-msft/azblob-recording`
2. Run `go test -v -run TestBlobStartCopyDestEmpty` with `AZURE_RECORD_MODE="playback"`

Note: This only shows up for tests in `azblob`, tested against `aztables` and this did not show up

**Comment by JoshLove-msft** [comment]
Looks like the host names are different:
"fakeaccountname" vs "fakeaccount"

**Comment by seankane-msft** [comment]
Good catch @JoshLove-msft , that solved it.
