### ISSUE TITLE
Support failing of releases for critical diagnostics failures

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-tools#2449]
Sometimes I discover that a library is doing something nefarious such as configuring its build to suppress certain kinds of build failures. This means that the library is not in its expected state, but we have no means of discovering this without manual inspection of the appropriate files. Even if we did enforce certain requirements on the build files, it is possible that teams could override these enforcements too.

What I'm proposing is the introduction of a new `DiagnosticKind` of type `FATAL`, that would fail the release of any library that has one or more of these diagnostics. The build failure could then report back the diagnostic text to the build system so that it may be reported to the user.

In my most recent example, I discovered a team was manually modifying their build config to suppress breaking API change warnings. I would in a heartbeat write a diagnostic that looks for these suppressions in the build config, and mark that as a fatal diagnostic to prevent releasing.
```[tasklist]
### Tasks
- [x] Add Fatal Level Diagnostics Kind at https://github.com/Azure/azure-sdk-tools/blob/8ac3c6b9afed1d303f71fb0c8fc51150803c64ef/src/dotnet/APIView/APIView/Model/CodeDiagnosticLevel.cs#L10
- [x] Update Build and Release APIView step to block release if APIRevison has FATAL diagnostic.
```

**Comment by maririos** [comment]
@praveenkuttappan this seems language specific, is this correct? what would be the work here for our team?

**Comment by JonathanGiles** [comment]
I suspect other languages might not bother to introduce FATAL diagnostics, so I'm happy to move that part of the work onto my shoulders, and leave this issue to cover the introduction of FATAL (a one-line enum addition I believe) and / or the build pipeline failing checking.
