### ISSUE TITLE
Python & JS OPS

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#2459]
Update OPS for Python and JS to point to new repository or use existing "Transfer ownership" functionality if it works. 

* [ ] Python
* [ ] JS

**Comment by benbp** [comment]
@danieljurek this is a rather barren issue :)

**Comment by danieljurek** [comment]
If, whatever this is, comes up again I'll open a real issue.

**Comment by danieljurek** [comment]
Turns out this is part of an epic and the work item makes sense... Added more detail.

**Comment by kurtzeborn** [comment]
We're not going to get to this anytime soon.  I don't think this is blocking anything either.
