### ISSUE TITLE
New-TestResource: support different output formats

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2463]
Currently, running, `New-TestResources` will yield one of three outputs:

- Copy-pasta for Powershell environment variables if you run the *.ps1 script plain
- Copy-pasta for CMD  environment variables if you run the *.CMD script plain
- An encrypted `test-resources.json.env` file if you run the script with `-OutFile`

This is limiting. For Python, the `test-proxy` supports loading environment variables via a `.env` file, which is just `key=value` pairs, but there is no simple way to transform the output of the script into this. It would be great to simply output directly to file or be able to pipe to file.

I have typically just used the copy-pasta to set the environment variables in my VSCode terminal, but the VSCode debugger doesn't see these unless they are in the `.env` file. Manually copy and pasting values into that file adds an unnecessary level of inefficiency, but is currently the only viable end-to-end solution.

Even if I could just copy-paste the output of the script into the .env file, it would be a productivity win. 

cc/ @lmazuel @mccoyp

**Comment by kurtzeborn** [comment]
Not sure if this should be assigned to @scbedd or @tjprescott.  Assigning to Scott to start things off. Please reassign as appropriate.

**Comment by kurtzeborn** [comment]
At this point, we're probably not going to fix this as suggested.  The strategy we intend to follow instead is a more dynamic strategy which retrieves secrets from the tests based on the users credentials.
