### ISSUE TITLE
[Python APIView] does not show methods/models correctly due to namespace check

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-tools#2465]
API view does not show aio methods and models for https://pypi.org/project/azure-search-documents/11.1.0b4/#files

**Comment by lmazuel** [comment]
@xiangyan99 please confirm if this is still the case

**Comment by tjprescott** [comment]
This seems to be addressed:
![image](https://user-images.githubusercontent.com/5723682/148431312-c8416426-c664-49a9-9c1d-03e0c883d2e7.png)

@xiangyan99 do you agree?

**Comment by tjprescott** [comment]
I think this has been addressed. Please re-open if you feel it is still an issue.
