### ISSUE TITLE
Pipeline name collision for two RPs with same package name

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-tools#2474]
When we use `prepare pipeline` to create new package's pipeline, we come into a collision problem that two RPs(solutions and resources) all have same package named `armmanagedapplications`. So the pipeline for solutions can not be created automatically as there is an existed pipeline named `go - armmanagedapplications - ci`. I've traced to [here](https://github.com/Azure/azure-sdk-tools/blob/e4689bdefa9511950eaf77ebd7fc710d01d4e7b2/tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PullRequestValidationPipelineConvention.cs#L17-L20). I wonder whether the component name set [here](https://github.com/Azure/azure-sdk-tools/blob/e4689bdefa9511950eaf77ebd7fc710d01d4e7b2/tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/SdkComponentScanner.cs#L52-L54) can include more directory part or give an param for downstream to pass the component name.

**Comment by weshaggard** [comment]
Thanks for tracing this @tadelesh this is an issue that @benbp and I are aware of. I believe @benbp already has an issue tracking this although I cannot find it currently.

**Comment by benbp** [comment]
@tadelesh @weshaggard the approach we've been recommending here is to add a name segment to the ci file like `ci.solutions.yml`. For example, [ci.keyvault.yml](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/keyvault/internal/ci.keyvault.yml) becomes [go - internal - keyvault](https://dev.azure.com/azure-sdk/internal/_build?definitionId=3296). In your case it would become `go - armmanagedapplications - solutions`.

**Comment by benbp** [comment]
@weshaggard I wonder if it's worth adding a log comment in the prepare pipelines code on name collisions that suggests this approach (or links to a troubleshooting FAQ that outlines this approach). If you agree I'll keep this issue open and make that the work for it, otherwise I'll close this.

**Comment by weshaggard** [comment]
Yes it is probably worth adding some logging and perhaps even making it a failure for both prepare-pipelines and the nightly run so that we know we are in this bad state.

**Comment by tadelesh** [comment]
@benbp @weshaggard Thanks for help. I'll change ci file name first.
