### ISSUE TITLE
[TestProxy] Centralize service-specific sanitizers

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2477]
The TestProxy has a robust set of default sanitizers, but inevitably there seem to be some service-specific sanitizers that are needed. Currently, each of those has to be configured in a language-specific way for each language and each service. But the kinds of things that need sanitizing (endpoints, special headers) aren't language-specific. We run the risk of a language missing some key sanitization or incorrectly specifying it (example: cut-paste from another language and the regex syntax is slightly different).

It seems like these sanitizers could be specified in some configuration file that could be loaded by the individual languages or bundled with the test-proxy such that it automatically applies them based on the request URL. This would mean all languages would sanitize the same way for a service and that new sanitizers and bug fixes to sanitizers would benefit all languages immediately.

**Comment by kurtzeborn** [comment]
Not sure if this should be assigned to @scbedd or @tjprescott.  Assigning to Scott to start things off. Please reassign as appropriate.

**Comment by scbedd** [comment]
Completed in #8038
