### ISSUE TITLE
[Test-Proxy] Response header transform needed

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2482]
For Identity tests, we need a way to mutate specific response headers, something like a HeaderTransform that derives from ResponseTransform. It would need to take the header key, a regex to match the header value, and a replacement value. It may be possible to use ApplyCondition for the matching the header value part, but not sure as it would need to be specifically for the header key that is specified.

**Comment by kurtzeborn** [comment]
Not sure if this should be assigned to @scbedd or @JoshLove-msft.  Assigning to Scott to start things off. Please reassign as appropriate.

**Comment by JoshLove-msft** [comment]
I can take a stab at this since it may just be a .NET specific requirement.

**Comment by scbedd** [comment]
Assigned Josh as I didn't do any work for this 👍 .
