### ISSUE TITLE
Add common template to get the list of files changed in a pull request

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#2531]
We have various implementations to figure out the list of files that have changed in a pull request and each of them are slightly different. It is about time for us to have a common shared version that we can optimize and keep updated for all the places.

Here is a list of the known implementations:
- https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/get-markdown-files-from-changed-files.ps1#L7
- https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml#L14
- https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/check-spelling-in-changed-files.ps1#L289
- https://github.com/Azure/azure-sdk-tools/pull/2686 [In pr, not merged yet]
One issue I know we have hit with the eng-common-workflow, that I suspect exists in the others as well is when we do a diff we are using the local commit which is the PR merge command and the head branch. Unfortunately the PR merge branch might not only contain the files in the PR it could contain other files pulled in from the merge. We should figure out the correct refs to diff only the commits in the PR, excluding the merge. We might want to consider using `system.pullRequest.sourceCommitId` and `system.pullRequest.targetBranch`, assuming those always provide the correct values we need.

**Comment by sima-zhu** [comment]
Testing criteria
1. Testing on PR, CI, Scheduled 
2. Testing with sparse checkout cases
3. Testing on A(dd), U(pdate), D(elete), R(ename)

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-tools/pull/2833

**Comment by sima-zhu** [comment]
The issue has addressed. Closed the issue.
