### ISSUE TITLE
[Swift APIView] Improve extension handling

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2536]
Currently, extension blocks from the source code appear in the APIView. The "extension Foo" line is not commentable, and how to represent this is tricky. There's not a good way to create a deterministic ID for the block itself.

For example:
```Swift

class MyClass { }

// A bunch of other code here...

extension myClass {
  public myNewMethod()
}
```

Clicking "MyClass" will take you to the class definition, but there's no way to link to the extension block.

One idea would be to essentially "collect" all of the extensions and stuff them in as though they were in the class block. That could be difficult and not work for all cases.

**Comment by tjprescott** [comment]
cc/ @jimchou-dev

**Comment by jimchou-dev** [comment]
Error for duplicate definition id
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/77021369/159807048-b8e75cce-7cf9-4e6e-8279-b2697f924999.png">
Repo: https://github.com/Azure/communication-ui-library-ios (reproduced in commit 6afcfcfac25acdc1776f7dee877e152f9373422f)

Scenario
2 subclass both implementing from `DrawerContainerViewController` with different type, each have an extension on `UITableViewDataSource, UITableViewDelegate`
- AudioDevicesListViewController: DrawerContainerViewController<T>
- ParticipantsListViewController: DrawerContainerViewController<T>

**Comment by tjprescott** [comment]
Original
```Swift
class SomeClass {
}

extension SomeClass {
  func doSomething() -> String {
    return "Something"
  }
}
```

**Option 1**
We would simply collect the extensions within `SomeClass` and render them as such, even if the syntax isn't technically valid.

```Swift
class SomeClass {
  extension SomeClass {
    func doSomething() -> String
  }
}
```

**Option 2**
Collect the methods/properties defined in the extension and display them as though they were properties of the original class definition. This does lose the context that the method actual came from an extension.

```Swift
class SomeClass {
  func doSomething() -> String
}
```

**Comment by tjprescott** [comment]
After discussion, the way forward will be to render extensions as follows:
- extensions of an "owned" type (defined by the package) will appear right after the type they extend
- extensions of foundation types (not defined in the package) will appear at the end of the APIView.
- if there are multiple extensions that resolve to the same definitionId, they will be logically merged together so that APIView will render them as a single extension block.
