### ISSUE TITLE
[TestProxy] Failure to start in Windows CI

### ISSUE THREAD

**Issue by seankane-msft** [Azure/azure-sdk-tools#2539]
The testproxy docker container is failing to start on Windows CI builds, blocking builds from succeeding

CI Run: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1291148&view=logs&j=15c99fa5-9535-554c-39e6-3d09570900f2&t=51208589-b323-5f77-91a1-91e63014cfa6&s=6884a131-87da-5381-61f3-d7acc3b91d76

**Comment by scbedd** [comment]
We mitigated this by swapping to the tool version, but the problem still stands.

**Comment by scbedd** [comment]
[Updated Failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1325468&view=logs&j=8befe419-3c43-5b79-8252-252cf2582e85&t=28290eab-65c5-5660-854e-094a9a6ebd66)

**Comment by scbedd** [comment]
Something in recent commits has resolved this. I'm betting that it was a real issue on windows-2019 agents.

[Here's an example build with docker re-enabled](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1394669&view=logs&j=15c99fa5-9535-554c-39e6-3d09570900f2&t=ad808b56-6715-5be2-f0f7-f6067485973f)
