### ISSUE TITLE
[Python APIView] Support @dataclass annotation in Python 3.7+

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2567]
Currently APIView blows up if a class uses the @dataclass annotation that was introduced in Python 3.7. We should support this annotation.

**Comment by tjprescott** [comment]
@annatisch @johanste what would you like these to look like?  A straightforward representation from:
https://docs.python.org/3/library/dataclasses.html

If we don't do things like try and display the generated methods, this should be fairly straightforward.

**Comment by johanste** [comment]
If the metadata from the fields is included, then I don't think I need to see the generated methods. If we are not including the metadata, then one would have to see things like what the options are (e.g. read-only, default etc.)
