### ISSUE TITLE
[Test-Proxy] Why do we need to send x-recording-mode after starting to record/playback?

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-tools#2574]
While reading the docs, I learned that I need to POST /record/start and that would generate a `x-recording-id`.  So, after that, why do I still need to set `x-recording-mode=record` for each request that I sent?  If I just told the server `/record/start`, why do I need to keep telling which request to record?

Same way, after POST `/playback/start` , why do I need to send `x-recording-mode=playback` for all requests?

If the reason is to enable skipping some requests from being recorded/playback, shouldn't it be an option for skip a request?  ( something like `x-ignore-request=true` so if server is recording, the request is not recorded, or if server is playback, it ignores and act just as a Proxy

**Comment by scbedd** [comment]
This method is used to route the traffic to the appropriate controller. We simply haven't invested in searching for an alternate routing method first checks `recordingId` and then routes it to the appropriate controller.

**Comment by scbedd** [comment]
I am going to close this. Currently the way we do this is quite straightforward, and I don't see a real benefit to making changes under the hood here.
