### ISSUE TITLE
[Test-Proxy] Mismatch for head request causes errors

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2594]
When there is a TestRecordingMismatchException, we include the exception message in the [response body](https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/HttpExceptionMiddleware.cs#L56). In the case where the initial request was a HEAD request, the body will not be transmitted over the wire, leading to the client (Test Framework) either choking when trying to read the response body, or just acknowledging that there won't be a response body making the initial mismatch more difficult to debug. In this case, we should consider including more information in a header, or just always having the message in a response header rather than in the response body (assuming there are no non-ascii characters).

**Comment by scbedd** [comment]
While we can't be certain that a stack trace will be valuable if we constrain it to X first few characters (constrained by header limit), I do think that we can at the very least add the one-liner describing the exception to a header.
