### ISSUE TITLE
API View: missing readonly keyword on the structs 

### ISSUE THREAD

**Issue by tarekgh** [Azure/azure-sdk-tools#260]
if defining the following struct with readonly keyword, 

```C#
    public readonly struct ReadonlyStruct
    {

    }
```

When showing it in api view, the readonly keyword will be missing

```C#
    public struct ReadonlyStruct
    {

    }
```

**Comment by pakrym** [comment]
Fixed in https://github.com/Azure/azure-sdk-tools/pull/292
