### ISSUE TITLE
Add TimeoutSec option to Verify-Links check

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#2600]
For some reason some websites appear to hang indefinitely when verifying if the link request will succeed. To help avoid indefinite hangs we should start using TimeoutSec option when we call Invoke-WebRequest in order to not fail all the other checks.

For example this particular request seems to hang indefinitely:
```
Invoke-WebRequest https://www.java.com
```
I've not been able to figure out why that never returns but in order to avoid such sites from throwing off all other link validation we should set a default timeout of 15 seconds.
```
> Invoke-WebRequest https://www.java.com -TimeoutSec 15
Invoke-WebRequest: The request was canceled due to the configured HttpClient.Timeout of 15 seconds elapsing.
```

For reference this has been causing an issue with our Java aggregate-reports pipeline for a few months, while checking https://github.com/Azure/azure-sdk-for-java/blob/main/common/smoke-tests/README.md. That link used to correctly validate but it seems sometime in the last month or so it started failing. @alzimmermsft is going to update the link to something else so this isn't a high priority issue, but we should fix this to avoid these types of issues in the future.

**Comment by sima-zhu** [comment]
Done. Checked in.
