### ISSUE TITLE
Live test subscription cleanup is failing for several subs on keyvault purge operation

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2610]
We are seeing `InvalidOperation: Operation 'DeletedVaultPurge' is not allowed.` errors on cleanup for several live test subscriptions. From what I can see the role assignments are the same, so perhaps these are older keyvaults, or we have some weird feature flag enabled in those subscriptions.

Affected subs:
- gov test resources
- playground
- ACS partner team public cloud subscription

[Pipeline failure example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1322439&view=logs&j=a460d732-23aa-5493-a411-cc406067acf8&t=23a627d1-f23b-57c9-66b4-c274364b8453&l=387)

**Comment by kurtzeborn** [comment]
@heaths, would you take a first look at this since you created it originally. Please reassign to @benbp if that doesn't work.

**Comment by heaths** [comment]
It's failing on some sub I don't seem to have access to, so I've sent @benbp the commands via Teams I need to see output. I'm guessing the vaults are just in some odd state, but we might want to change the scripts to output the whole service message. Could hide it behind `Write-Verbose` so the default user experience isn't too verbose. I hope the service would tell us more why it can't be deleted (it was clearly discovered).

**Comment by heaths** [comment]
Oddly enough, a query for vaults in a deleted state today is different than the list from the linked pipeline. I'm working with the Key Vault team to try to figure out what's going on.

```bash
az keyvault list-deleted --subscription <sub> --query 'sort([].name)'
```

**Comment by heaths** [comment]
The clean-up script isn't waiting for resources to be fully deleted, so KVs would not yet be in a purgeable state:

https://github.com/Azure/azure-sdk-tools/blob/59f8cb1df260dbf367271b87582e55bb77dff8c5/eng/scripts/live-test-resource-cleanup.ps1#L85
