### ISSUE TITLE
[Test-Proxy] Flaky test - BodyKeySanitizer

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/azure-sdk-tools#2612]
Reporting here - the same problem that was posted on the teams channel to track the work better.

Problem - sanitizer isn't being applied sometimes.

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1320783&view=logs&j=f9023f38-2626-5b42-3dd0-094a498a85bb&t=b1330a6f-3a70-570a-938b-a728ee27c0b0&l=3060
![0f77869e-29db-4bba-8200-bad8c6c854bc](https://user-images.githubusercontent.com/10452642/151064827-d7f962c6-657e-419d-a509-936361cc5e9e.jpg)

BodyKeySanitizer seems to be failing, and only on "Ubuntu". 🥲
Originally reported by @jeremymeng. 

Did a re-run(link above), which also failed on Ubuntu with the same error again.

It also succeeds sometimes - that's why calling it flaky.
![3164fa38-bea8-4d3e-9d61-7c367feed675](https://user-images.githubusercontent.com/10452642/151065137-61b33410-1daa-4979-b2fd-69c8eb450f18.jpg)

One general observation: Ubuntu is usually faster than mac and windows as you see above in the screenshot.

cc @jeremymeng @scbedd @timovv

**Comment by timovv** [comment]
[Also encountered on Windows](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1330424&view=logs&jobId=889ff074-62b8-55e4-5d7f-907488e92b21&j=889ff074-62b8-55e4-5d7f-907488e92b21&t=0da6ba07-cc57-557e-3355-438c1b2e5790): 
![image](https://user-images.githubusercontent.com/1787642/151442110-b8bf9f27-d138-44ce-8400-a51ad21c8b98.png)

**Comment by scbedd** [comment]
@timovv @HarshaNalluru I haven't seen this ever since the merge of the test-proxy from the 10th. Can you folks point me to any new occurrences?

**Comment by timovv** [comment]
Can't say I've seen it recently, whereas before I was running into it all the time. Good chance it's been fixed I reckon (unless you've been seeing it still, Harsha).

**Comment by scbedd** [comment]
I am looking at a failure in public on the [16th](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1370310&view=results) that looks like this. So I'm not closing this.

**Comment by scbedd** [comment]
I haven't seen any instances of this in a couple months. Closing.
