### ISSUE TITLE
Add CredScan in PR validation + Ci build

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#2618]
**Summary**

The cleanup work for 4 tier-1 language repos are near the end. To release the burden of the dedicated eng, we decided to move CredScan step to PR validation, so people who introduce the error are responsible to clean them up.

**Current Status**
1. [Lang side] The cleanup status of each language

| Repo| Active Errors | Use baseline|
| :--- | :---: | :--- |
| .NET | 25 | Yes |
| Java| 2 | No |
| Python | 55 | Yes |
| JS |  1 | No |

2. [Eng side] Open `enable credscan` [PR](https://github.com/Azure/azure-sdk-for-net/pull/26527) towards .NET. We run `Compliance` job in parallel with `Build`, `Analysis`, `Test`
* PR scan against changed files. 
  - **Testing data**
  - Changed files: `eng/ignore-links.txt`, `eng/pipelines/templates/jobs/ci.yml`
  - Total running time: 7 mins
  - Pipeline: [Link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1327681&view=logs&jobId=bc67675d-56bf-581f-e0a2-208848ba68ca&j=bc67675d-56bf-581f-e0a2-208848ba68ca&t=b28ad947-3a96-5456-bab5-14395d503466)

* CI build scan against the service directory.
  - **Testing data**
  - Changed folder: sdk/storage
  - Total running time: 15 mins
  - Pipeline: [Link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1327596&view=logs&j=bc67675d-56bf-581f-e0a2-208848ba68ca)

**Next Step**:
1. (Lang)Keep cleaning the errors reported in aggregate-reports.
2. (Lang + Eng)Have a guidance on how to clear the errors for different cases.
  - Real secret
  - False positive placeholder
  - False positive, but secret refresh for every generation.  
3. (Eng)Have `enable credscan` PR ready for 4 repos.

**Comment by alzimmermsft** [comment]
Un-assigning myself as Java has been completed and the only remaining tasks appears to be C++ related.

**Comment by kurtzeborn** [comment]
We've done this in all the places we care to do it now.
