### ISSUE TITLE
Cleanup .NET repo

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#2623]
Pre-requisite:
Have the credscan PR ready

**Comment by kurtzeborn** [comment]
Assuming since you put it in the CredScan epic (in ZenHub) that this is about cleaning up CredScan errors in the repo.  If you intend to have someone on the language team do this cleanup, please reassign/retag as appropriate.

**Comment by sima-zhu** [comment]
Will update the baseline file to address the issue.

**Comment by sima-zhu** [comment]
The repo has been cleaned up.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1358153&view=results
Closed this issue.
