### ISSUE TITLE
Stress Test Release pipeline should deploy examples to playground environment

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2635]
The only reason to do this is we are now deleting service principals that aren't actively used, and the one registered to this pipeline for manual deploys to playground wasn't used in 45+ days. We should keep the connection active so it doesn't get flagged.

**Comment by kurtzeborn** [comment]
When we discussed this, we agreed that we should lump all of the places where our DevOps accesses our subscriptions to use the same service principal so that we don't accidentally delete it when we don't recognize it in some future cleanup sweep.

**Comment by richardpark-msft** [comment]
Update: deleting service principals is not the only reason. We'd also like to support https://github.com/Azure/azure-sdk-tools/issues/2764.

**Comment by benbp** [comment]
Related https://github.com/Azure/azure-sdk-tools/issues/2764
