### ISSUE TITLE
Create Github issue should have a link to the APIView comment

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#2642]
![image](https://user-images.githubusercontent.com/1050156/151638318-ad6aecb6-025a-4aaf-b553-4faa31b485c1.png)

Creates this:
![image](https://user-images.githubusercontent.com/1050156/151638336-f8077b9b-66fb-4929-9e67-f9264bb527e6.png)

I'd like to see a link to APIView back, in this case:
https://apiview.dev/Assemblies/Review/c7f8f0ec039a46a8b763dd7f33a2a3de#d8add0a7280f49758215adfc2c5c4f5c

**Comment by JoshLove-msft** [comment]
Agreed - when this was initially added I think the concern was around having the link to ApiView in public issue that customers may not be able to click.

**Comment by chidozieononiwu** [comment]
Fixed by https://github.com/Azure/azure-sdk-tools/pull/7779
