### ISSUE TITLE
gitignore file is too broad

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2648]
Something in the gitignore for this repo is causing new *.py files to not be detected by git. The workaround is to manually `git add <file> --force` but this should not be necessary.

**Comment by benbp** [comment]
@tjprescott I am able to add one to the root of the repo. All the gitignore files in the repo only seem to contains exclusions for .pyc files and other build/cache artifacts. Was there a specific directory you were unable to add files in?

**Comment by heaths** [comment]
Keep in mind that you can add .gitignore files at any level in the directory that can override parent configuration.

**Comment by tjprescott** [comment]
Anything in `packages\python-packages\api-stub-generator\`. The only gitignore file is at the root of the repo. If I add test or code `*.py` files (not `*.pyc`) I have to do a `git add --force` to add them, usually after the CI fails because some file is missing.

**Comment by tjprescott** [comment]
Git sees it if it is in the repo root, but not once I move it under `\packages`

**Comment by tjprescott** [comment]
Actually, it looks like this is probably the culprit:
https://github.com/Azure/azure-sdk-tools/blob/main/.gitignore#L292

**Comment by tjprescott** [comment]
The comments says
`# The packages folder can be ignored because of Package Restore`
But this is not the case because we store python and java packages under this folder which has nothing to do with Nuget.

**Comment by heaths** [comment]
I mean, you can add a .gitignore file to a subdirectory and override the exclusion if there's normally reaso to ignore .pyc but you want to include them in this case:

* .gitignore
  ```gitignore
  *.pyc
  ```
  * some/subdirectory/.gitignore
    ```gitignore
    !*.pyc
    ```

**Comment by tjprescott** [comment]
I added an exclusion for the Python packages folder like we have for Java in the linked PR.

**Comment by weshaggard** [comment]
FYI @sima-zhu at some point we should move things out of the root packages folder and under tools folder which would also fix this issue.
