### ISSUE TITLE
[APIView] Support for URL token type

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#2650]
Looking forward in the evolution of APIView, we would like to see a token type added for external links. Currently tokens can have a "navigateToId" property which controls jumping between things within the APIView, but we would like a token that displays URLs that will open links in a separate browser.

Some applications of this:
- Displaying the link to the source PR for generated APIViews as part of the APIView preamble (along with version etc.) The ultimate goal would actually be to link this to the source _Swagger_ PR, but an interim step would be linking to the language PR.
- Building off the previous, adding a (link) tag to certain lines that would provide a direct link to the source code line in the relevant PR.
- Building off that, potentially adding a (doc) tag to certain lines that would provide a direct link to the generated docs for a relevant PR.

Note that there's a whole lot more that would need to happen to fully implement these scenarios, but they underpinning all of them is the need for an external link mechanism.

**Comment by tjprescott** [comment]
cc/ @johanste @praveenkuttappan

**Comment by johanste** [comment]
cc/ @annatisch

**Comment by Vailorium** [comment]
@JonathanGiles
