### ISSUE TITLE
Toolbar growing too long for practical browser size

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#2655]
As we add more languages, modes, etc., to APIView, the toolbar / tab bar is growing long enough to cause odd rendering like this:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/1532486/152073216-f3958c3e-f535-4a02-a018-c9def3fd36f5.png">

Perhaps we should switch to a drop-down or something that takes less room. My browser window is typically at a pretty good width for most sites, but I have to maximize or otherwise make it longer than usual for APIView.

**Comment by weshaggard** [comment]
cc @chidozieononiwu @praveenkuttappan This is something already fixed in our upcoming UI updates.
