### ISSUE TITLE
APIView is showing analyzer errors that are incorrect and that I don't see locally

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#2656]
Not sure if this is an APIView bug or an analyzer bug, but I don't see this when building locally. I happened to notice today this for Azure.Security.KeyVault.Certificates, which is incorrect because there is such a constructor:

<img width="761" alt="image" src="https://user-images.githubusercontent.com/1532486/152073616-41b3228d-827e-494f-9c82-89f324e6e9d5.png">

See https://apiview.dev/Assemblies/Review/da210106190946c0874b30d5f84f41b1#Azure.Security.KeyVault.Certificates.CertificateClient

**Comment by jsquire** [comment]
Given that this is 2+ years old at this point and a number of APIView releases have come out, I'm going to close this out.   We can reactivate if the behavior persists and we need to look at it from a language-specific perspective.
