### ISSUE TITLE
'Apply Documentation Updates' step fails occasionally causing tests to be reported as failed

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-tools#2669]
[Example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1343611&view=logs&j=f8e040b3-c0ff-5789-0eda-99daaaa3fc1b&t=4ddc76a6-85f2-526e-fa3e-b1020f31ed12) of a failed job.

From the log -

Generating aad token...
Fetching aad identity for github user: Mohit-Chakraborty
Write-Error: /mnt/vss/_work/1/s/eng/common/scripts/Update-DocsMsMetadata.ps1:117
Line |
 117 |  … $msauthor = GetMsAliasFromGithub -TenantId $TenantId -ClientId $Clien …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     |  404 Not Found  404 Not Found nginx   

##[error]PowerShell exited with code '1'.
Finishing: Apply Documentation Updates

**Comment by sima-zhu** [comment]
Hi We have a fix to make it as warning instead of error.

Could you please share your Microsoft alias? Seems like you do not have a right link between github identity <-> ms alias. That's why it failed.

**Comment by Mohit-Chakraborty** [comment]
Thanks for checking Sima. I'll ping you separately.

**Comment by sima-zhu** [comment]
The opensource API call seems have failure rates on first try.
Will add retry on the API call.

**Comment by sima-zhu** [comment]
https://github.com/Azure/azure-sdk-tools/pull/2685
https://github.com/Azure/azure-sdk-tools/pull/2673

These two PRs will fix the issue.

**Comment by sima-zhu** [comment]
Resolved. Closed the issue. Feel free to reopen if you have any other open issues
