### ISSUE TITLE
[Test-Proxy] Consider Special-casing two browser-specific headers

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#2674]
This detailed write-up is pulled from teams. Don't want @HarshaNalluru 's effort to go to waste.

I have a **browser** only test that is failing with the following error. This test interacts with the app-config resource.

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/45376673/152411672-7a6fbd47-13fe-4f4b-b347-faed4ae8d66e.png)

I think, browser adds these headers to the requests.

```
Header differences:\n    \u003C
 
If-Modified-Since\u003E is absent in record, value \u003CWed, 01 Dec 2021 02:23:41 GMT\u003E\n    \u003C
If-None-Match\u003E is absent in record, value \u003C\u0022jHnSsNSkboEWJFD7nnfzHgnZjRA
```

### If-Modified-Since 
	
"The If-Modified-Since request HTTP header makes the request conditional: the server sends back the requested resource, with a [200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) status, only if it has been last modified after the given date. " 
	
When used in combination with [If-None-Match](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match), it is ignored, unless the server doesn't support If-None-Match.
	
[If-Modified-Since - HTTP | MDN (mozilla.org)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since)

### If-None-Match

The If-None-Match HTTP request header makes the request conditional. For [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET) and [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) methods, the server will return the requested resource, with a [200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) status, only if it doesn't have an [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) matching the given ones. For other methods, the request will be processed only if the eventually existing resource's [ETag](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/ETag) doesn't match any of the values listed.

[If-None-Match - HTTP | MDN (mozilla.org)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-None-Match)

In this case, we have both If-Modified-Since and If-None-Match in playback, so If-None-Match should take precedence. And the proxy tool should return the resource without checking the If-None-Match header.

What I want here from the proxy tool is..

- If this header is not present in the recording, ignore the header and give me the response back
- That would solve the current issue that we're seeing, but I'm not sure if I can convince that it's the right thing to do
-  And if we are specifically testing for Etags, these header checks might make more sense. I'm unsure if we are adding any value by checking them in playback with the headers in the recording.

**Comment by scbedd** [comment]
I have advised @HarshaNalluru that using a `CustomDefault` with `ExcludedHeaders` adding these two headers will also work for them.

I am legitimately not certain whether or not we want to implement this behavior.

**Comment by scbedd** [comment]
After a discussion w/ @mikeharder , really the best way to handle these is to special case these two specific headers. By that, we mean that we're going to actively remove `If-None-Match` and `If-Modified-Since` from the request _entirely_ while we handle the request. This applies to both recording/playback.

This is due to the fact that these two headers cause different behavior if the content _has_ changed, you're going to get a [302](https://stackoverflow.com/a/973130) response. That's definitely not valuable in recordings. By stripping from the request before we ever send it to the upstream, we eliminate any possibilities of mismatch during recording or playback.

@HarshaNalluru do your browser tests intentionally exercise these headers? If they _do_, then this method is a non-starter, and we should just continue with the ExcludeHeaders and close this issue.

**Comment by HarshaNalluru** [comment]
I don't see any problems in actively removing the If-None-Match and If-Modified-Since headers. Let's go ahead with that approach.

Ideally, this is just a browser caching mechanism which we aren't really interested in our tests primarily because if two requests are the same, they must be coming from different tests - and we don't intentionally want inter-dependencies in tests.

There might be other ways to stop browser caching by adding more headers to ask the browser not to cache the requests, but the "actively remove If-None-Match and If-Modified-Since from the request entirely" sounds fine to me.
Let's go ahead with that. 😎

**Comment by scbedd** [comment]
I had a chat with @mikeharder when we first proposed this, but I didn't follow up on this issue.

@HarshaNalluru if you're not currently blocked by this, I don't think we're going to take it. The proxy currently does **0** manipulation of request/response that is auto-magical, and I'd rather keep it that way.
