### ISSUE TITLE
[Test Proxy] JS test from template package - recording is not always generated 

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/azure-sdk-tools#2683]
Test for which we want to generate the recording - https://github.com/Azure/azure-sdk-for-js/blob/1535c63eabbb54dc04406ddd18a408712401f4d5/sdk/template/template/test/public/configurationClient.spec.ts#L90

When testing with browsers, 
- if all the tests are run, the recording is not generated for the "supports tracing" test
- if only the "supports tracing" test is run, the recording is generated

Seen this behavior when tested in codespaces. Unsure about other environments.

## Steps to repro
1. Clone the repo https://github.com/azure/azure-sdk-for-js - main branch should be good to repro
2. Go to the template package - `cd sdk/template/template`
3. Make sure to have the env variables in `.env` file as described in `sample.env`
4. `rush update && rush build -t .` (updates deps and builds azure deps from the repo)
5. `rushx test:browser` - should generate recordings, but the "supports tracing" test generates an empty recording
6. Set `.only` for the "supports tracing" test 
7. Then run the `rushx test:browser` command, this time the recording will be generated as expected

**Comment by scbedd** [comment]
Related to docker maybe? Trying that now
![save_works_locally_from_tool](https://user-images.githubusercontent.com/45376673/152894317-c813a78f-1e34-424e-a78a-157bd1f78908.gif)
.

**Comment by scbedd** [comment]
I initialized locally with `eng/common/testproxy/docker-start-proxy.ps1 START`.

After initialization, I ran tests in record mode.

Results:
![save_works_locally_from_docker](https://user-images.githubusercontent.com/45376673/152895299-afc4a0e9-d71c-4a95-a085-115fd3da6999.gif)

**Comment by scbedd** [comment]
@HarshaNalluru I cannot repro this on `main` for _any_ environment I have access to.

![image](https://user-images.githubusercontent.com/45376673/153057763-d4a13ce6-b46b-41f9-a50b-5e2a218cfe37.png)

It's definitely always updating recordings. I think you have a local configuration issue.

**Comment by scbedd** [comment]
I am going to close this until there is a repro @HarshaNalluru .
