### ISSUE TITLE
[Test-Proxy] Support dynamic port binding

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#2702]
Right now. It's bound to `5000` for http or `5001` for https.

Allow command line settings for this instead of hardcoding.

**Comment by JoshLove-msft** [comment]
It can also be set via env var. In .NET, we [set the env var](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.TestFramework/src/TestProxy.cs#L73) to 127.0.0.1:0 which tells the server to give us the next available port.

**Comment by scbedd** [comment]
@vhvb1989 jumped on this and #2664  a solution that just builds on top of the default config handlers.  Now we can set `--urls` to get the same experience as the env var now. (and any other ASP.NET config option in fact!)
