### ISSUE TITLE
Changelog verification should happen in PRs if possible

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2705]
Right now verifying that there are no missing change log entries happens as part of the release pipeline. It would be great if we could verify that there are no empty sections if a release date is set, during the CI pipeline as this would save a lot of unnecessary steps when this step is ultimately going to fail.

**Comment by weshaggard** [comment]
Thanks for the feedback and we do have issue https://github.com/Azure/azure-sdk/issues/3690 tracking this work.
