### ISSUE TITLE
APIVIew - Group reviews by dll or package name instead of service name

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#2706]
Show reviews grouped based on actual review name or artifact name for e.g. artifact name for .Net review is .dll file for the package. 

New UI groups reviews based on service name and package name. We should support a grouping based on review name( which is actually underlying artifact file name) as an optional view. 

Additional change: We need to add capability to store user preferred view and generate it accordingly based on logged in user.

**Comment by maririos** [comment]
This was the view people didn't like? or is this another approach? do you know if peole still want it?

**Comment by praveenkuttappan** [comment]
This is no longer required. We have reverted the view reviews by service.
