### ISSUE TITLE
APIView - Reviews dropdown should show more metadata to differentiate reviews

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#2707]
New dropdown in review page shows all reviews for a given package name (this is based on the package name of current review). Dropdown lists many reviews with same name for a package and it makes is difficult to identity what needs to be verified. We need to update dropdown to show more differentiating properties to show which one is pull request, manual and automatic in addition to any label available in review metadata.

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/2785
