### ISSUE TITLE
[Test proxy] cannot create recordings for AI Text Analytics

### ISSUE THREAD

**Issue by timovv** [Azure/azure-sdk-tools#2719]
Raising issue as requested during the sync today. In the process of trying to record tests for AI text analytics, I run into this:

![image](https://user-images.githubusercontent.com/1787642/153091740-7f6fd7e4-3256-41df-98f7-1e9fd21f83a3.png)

To reproduce:
* Checkout [my branch]
* Go to `sdk/textanalytics/ai-text-analytics`
* Set up `.env` based on the `sample.env` file using your Language Service thingy (happy to share my .env offline if that helps)
* Do a `rush update` and `rush build -t .`
* Run `TEST_MODE=record rushx unit-test:node`

Some info that may or may not be useful:
* This is on WSL 2 with Docker
* Tests run without issue in live mode
* It hangs for a long time before returning the 500 error
* Error message seems to indicate that it's a DNS issue

Cc: @scbedd @HarshaNalluru

[my branch]: https://github.com/timovv/azure-sdk-for-js/tree/ai-text-analytics/19859-recorder-migration

**Comment by scbedd** [comment]
@timovv When running this, I see error

> [node-tests]      RestError: {"Message":"The URI being passed has two leading \u0027/\u0027 in the Target, which will break URI combine with the hostname. Visible URI target: //text/analytics/v3.2-preview.2/sentiment?stringIndexType=Utf16CodeUnit.","Status":"BadRequest"}

**Comment by timovv** [comment]
Ah, I ran into this too, should have mentioned. Try removing the trailing `/` from the endpoint URL in your `.env` file.

**Comment by scbedd** [comment]
Aha! Thanks for quick response let me unblock on that :)

**Comment by scbedd** [comment]
So far, I'm not seeing the same errors.

```
[node-tests] [APIKey] TextAnalyticsClient
[node-tests] fast tests
[node-tests] #analyzeSentiment
[node-tests] √ client accepts string[] and language (1051ms)
[node-tests]
[node-tests] [AAD] TextAnalyticsClient
[node-tests] fast tests
[node-tests] #analyzeSentiment
[node-tests] 1) client accepts string[] and language
[node-tests]
[node-tests]
[node-tests] 1 passing (2s)
[node-tests] 1 failing
[node-tests]
[node-tests] 1) [AAD] TextAnalyticsClient
[node-tests] fast tests
[node-tests] #analyzeSentiment
[node-tests] client accepts string[] and language:
[node-tests] RestError: Principal does not have access to API/Operation.
[node-tests] at handleErrorResponse (C:\repo\sdk-for-js\sdk\core\core-client\src\deserializationPolicy.ts:251:17)
[node-tests] at deserializeResponseBody (C:\repo\sdk-for-js\sdk\core\core-client\src\deserializationPolicy.ts:159:43)
[node-tests] at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Failing on second test. Something in AAD is going wrong.

**Comment by scbedd** [comment]
Timo attempted repro on a new codespaces instance, and cannot repro this issue.

I am closing until we see the 500ing behavior again.
