### ISSUE TITLE
[stress testing][s] Invert -Login and -PushImages parameters

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2730]
For the most common use case of the stress test deployment script (which is to log in and push images), we should make this the default behavior when invoked with no parameters.

For example, `-SkipLogin` and `-SkipPushImages` instead.

**Comment by kurtzeborn** [comment]
Closing.  At this point if we haven't done this, we're not going to.  Small request, but we're pretty sure people have gotten used to how this script works and changing it's behavior might cause problems.
