### ISSUE TITLE
AzurePS 0.8.4 - Missing commands to manage Azure Automation Accounts

### ISSUE THREAD

**Issue by pcgeek86** [Azure/azure-sdk-tools#2740]
The Azure PowerShell module, version 0.8.4, is missing commands to manage Azure Automation accounts. There is only one command with the noun `AzureAutomationAccount`, which allows enumeration of Azure Automation accounts within the "selected" Azure subscription.

```
PS C:\> Get-Command -Noun AzureAutomationAccount;

CommandType     Name                                               ModuleName
-----------     ----                                               ----------
Cmdlet          Get-AzureAutomationAccount                         Azure
```

To keep consistency with other features of the Azure PowerShell module, in a future version of the module, I would like to see (at a minimum) the following commands:

1. Remove-AzureAutomationAccount
2. New-AzureAutomationAccount

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by matt-gibbs** [comment]
Closing this issue. Work to add more automation functionality is underway.

**Comment by jamiekt** [comment]
Fantastic. Can you share the list of cmdlets?

**Comment by pcgeek86** [comment]
I'd suggest holding off on closing issues until they're resolved. Will the 0.8.14 release include the new commands? What commands are being added or changed?

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by jodoglevy** [comment]
New:
New-AzureAutomationAccount
Remove-AzureAutomationAccount
Get-AzureAutomationScheduledRunbook
New-AzureAutomationVariable
Set-AzureAutomationVariable
Remove-AzureAutomationVariable
Get-AzureAutomationVariable
Get-AzureAutomationCredential
New-AzureAutomationCredential
Remove-AzureAutomationCredential
Set-AzureAutomationCredential
Get-AzureAutomationCertificate
New-AzureAutomationCertificate
Set-AzureAutomationCertificate
Remove-AzureAutomationCertificate
Get-AzureAutomationConnection
New-AzureAutomationConnection
Remove-AzureAutomationConnection
Set-AzureAutomationConnectionFieldValue
Get-AzureAutomationModule
New-AzureAutomationModule
Set-AzureAutomationModule
Remove-AzureAutomationModule

Updated:
Get-AzureAutomationJob - supports server side filter on Job Status

Coming soon...

**Comment by pcgeek86** [comment]
Nice! Thanks for the list. Good to know these are coming soon.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell
