### ISSUE TITLE
Add service label to PRs opened in azure-rest-api-specs(-pr)

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2743]
The azure-rest-api-specs repo has labels for most if not all Azure services. We should have an automation to add the correct service label when a PR is opened in this repo.  The automation should determine the service label to apply from the files changed.
For example, a PR that has files changed in the "specification/purview" directory should get the "Purview" label.

**Comment by ruowan** [comment]
Sure. In azure-rest-api-specs repo., we have enabled synapse and compute RP auto add label based on file changes. These rules is requested by service team. Do we need to apply this rule to all the resource providers?

**Comment by mikekistler** [comment]
This request is not specific to resource providers and my primary interest is actually for data plane.  And yes, I would like this to be done for every service.

**Comment by weshaggard** [comment]
@ruowan Yes we should try to do this for everything. I'm also curious how the current auto label solution works to compare it to what we do with our language repos.

**Comment by jsquire** [comment]
Our language repos use the [Fabric Bot](https://portal.fabricbot.ms/bot/?repo=Azure/azure-rest-api-specs) to manage this.  It looks like someone set up a limited set of bot rules for labeling for the specs repo:

![image](https://user-images.githubusercontent.com/913445/154308842-a5f2adac-5e2d-40c2-a82e-f1c425db1f3d.png)

In order to enable this for all paths, they would need to be added to the existing rule.   For our language repositories, we can auto-generate this ruleset based on the [CODEOWNERS](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS) extensions that we use  _(note the comments following the pattern:  `# PRLabel: %Azure.Identity`)_  There currently is no CODEOWNERS file in the spec repo.  As an alternative to implementing the bot rule directly, if someone wanted to create the CODEOWNERS file, we could generate the needed auto-label rule based on it.

With respect to the private (-pr) language repositories, no automation is registered for them.  The same is true of the specs-pr.  I'm not sure if the bot supports integration with private repositories, but I can follow-up if someone is looking to replicate rules.

**Comment by ruowan** [comment]
I have no permission to edit for azure-rest-api-specs. We are also using fabric bot to add labels for changed files. @jsquire Azure-rest-api-specs also has some codeowner file how to enable auto generate rule set in spec folder?

**Comment by jsquire** [comment]
> Add the "DataPlane" label to any PR that updates a file with a path matching "specification/*/data-plane".

Unfortunately, this is beyond the ability of Fabric Bot's path matching.   It cannot handle globs or regex patterns.   It does a simple `StartsWith` check against the path.

**Comment by jsquire** [comment]
> Azure-rest-api-specs also has some codeowner file how to enable auto generate rule set in spec folder?

The CODEOWNERS file has none of the annotations that I mentioned above.   Parsing it would result in no rules.    The tool that does rule generation can be found [here](https://github.com/Azure/azure-sdk-tools/tree/main/tools/CreateRuleFabricBot).

**Comment by ruowan** [comment]
Hi, @jsquire Thanks your tools for rule generation. This sprint we are working on this work item. But I found I doesn't have permission for configuring Azure/azure-rest-api-specs repo. Do you know how to gain permission.

**Comment by jsquire** [comment]
@lilyjma:  Are you able to assist with suggesting a path for @ruowan to request access?

**Comment by mikekistler** [comment]
cc: @heaths

**Comment by lilyjma** [comment]
@ruowan -- I've added you as an administrator, and you should have access to configuring the azure-rest-api-specs repo in the [bot](https://portal.fabricbot.ms/bot/). That said, I think the Fabric Bot team last said that long-term, the idea is to do config-as-code.

**Comment by mikekistler** [comment]
I personally find “Data Plane” more description than “Client”, but I could be persuaded.

Regarding service labels (the original subject of this issue), I’m open to any solution that accomplishes this.

**Comment by heaths** [comment]
We already use Client across all our other repos. Maybe "DataPlane" (spaces are best to avoid - makes queries more difficult in general) is more descriptive, but we already have a lot of automation built around Client vs. Service vs. Mgmt vs. EngSys; basically, all the yellow labels - the label colors are a critical piece of our automation store.

**Comment by weshaggard** [comment]
Yes I'd like to use consistent labels and we should sync the labels we have in the other repos. I know @jsquire maintains a master list of labels and has a tool to sync them, perhaps he could consider using the gh cli going forward.

**Comment by mikekistler** [comment]
So who needs to do what here? How do we make progress?

**Comment by tomkerkhove** [comment]
We can use fabric bot or a simple GitHub Action.

If I get it correctly, the goal is to:
- Have a label per service (which I was looking for as well)
- Have a label for ARM vs Data Plane

Good summary? GitHub Actions should be simple enough IMO. Happy to take as tab at it if need be.

**Comment by mikekistler** [comment]
That is a good summary and the labels for services are for the most part already in place -- we just need some automation to apply them to incoming PRs based on which folder(s) the changed files live in.

I would welcome a proposal for a GitHub action to do this.

**Comment by tomkerkhove** [comment]
> labels for services are for the most part already in place

Would you mind elaborating on this please? Are you referring to Fabric Bot above? Because then we can't use GH Actions.

**Comment by mikekistler** [comment]
Just have a look at 

https://github.com/Azure/azure-rest-api-specs/labels

There are already tons of labels created, many for specific services like "Purview".

**Comment by tomkerkhove** [comment]
Oh you mean the labels themselves, ok thanks.

**Comment by tomkerkhove** [comment]
@kurtzeborn Feel free to assign to me

**Comment by weshaggard** [comment]
@tomkerkhove today we use fabric bot to configure these labeling rules and I believe @ruowan is working on that and it requires permissions to setup. 

We are considering moving to using github actions (see https://github.com/Azure/azure-sdk-tools/issues/3195) but we aren't ready to make that move yet.

**Comment by ruowan** [comment]
For azure-rest-api-specs repo, we are working on that and trying use rules generation tool to generate config.

**Comment by tomkerkhove** [comment]
I was more asking for the REST API specs but it looks like @ruowan is already working on it so will wait for that.

**Comment by heaths** [comment]
FWIW, I did add label cloning to the [GitHub CLI](https://github.com/cli/cli/releases/latest) you could use if you want. For example:

```bash
cd azure-sdk-tools
gh label clone Azure/azure-sdk-for-net
```

It'll create or update as needed. If you want to selectively clone, I have an extension for that as well but let me know.

**Comment by ruowan** [comment]
Hi, @tomkerkhove we have a PR to update codeowner files. https://github.com/Azure/azure-rest-api-specs/pull/19123/files We have generate fabric bot config locally. seems the codeowner file in spec repo doesn't cover all the RPs, https://github.com/Azure/azure-rest-api-specs/pull/19123/files.  Do you have ideas about manage Resource Provider to label mappings?

**Comment by tomkerkhove** [comment]
Unfortunately I do not, sorry! But that PR already looks very helpful.

**Comment by weshaggard** [comment]
@ruowan thus far we don't have anything setup to try to keep those things in-sync but as we are updating our on-boarding processes I would really like that information to be stored in our PowerApps dataverse and then we use it to generate the necessary codeowner files. Until then we will have to manually maintain them.

**Comment by ruowan** [comment]
Got it. We have already enabled fabric bot to add labels. Looks good now. If no other issues, we could close this issue.
