### ISSUE TITLE
[Test-Proxy] Proxy exceptions should set a response header

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2746]
If the proxy hits an exception, the error gets returned in the response body. Some libraries expect a specific shape for errors and will end up hitting an exception caused by the error parsing if the error response doesn't match this shape. It would be helpful to set a known response header similar to what we do for mismatch errors, so that the test framework can intercept these responses and throw an appropriate exception before returning control to the calling libraries.

**Comment by scbedd** [comment]
@JoshLove-msft I will do the following.

When handling a mismatch exception, we add two headers

- `x-request-mismatch: true` 
- `x-request-mismatch-error: <base64 encoded string>`

I will do the same for "generic" exceptions that are unhandled.

- `x-request-exception: true`
- `x-request-exception-error: <base64 encoded string>`

**Comment by JoshLove-msft** [comment]
That sounds great!
