### ISSUE TITLE
[stress testing][m] Create CI pipeline for stress-cluster related changes

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2764]
It should check at least these three things:

- `az bicep build -f main.bicep` - Is the cluster deployment config valid
- `helm upgrade --dry-run` for the stress infrastructure
- `helm upgrade --dry-run` for the stress test examples

It might be a good idea to also add a `DryRun` parameter to the `deploy-stress-tests.ps1` script, then instead of copying over the helm upgrade commands for the examples we could just run the script in dry run mode.

**Comment by richardpark-msft** [comment]
After talking with @benbp , we'll also want to have a "live" run where it actually does the deploy to check for things like being able to deploy to multiple regions, etc...
