### ISSUE TITLE
Add support for wildcard handling of file matching in codeowners library

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#2770]
See comment https://github.com/Azure/azure-sdk-for-js/pull/20354#discussion_r806177441.

It would be helpful to support some basic wildcard matching in our code owners file library. Maybe we cannot easily support all wildcard patterns but we could probably support `**` for something like `/sdk/**/ci.mgmt.yml`.

**Comment by konrad-jamrozik** [comment]
@weshaggard I analyzed the relevant code and here is my plan of action. Sharing with you in case you have any concerns or suggestions.

## What code needs to change

Principally, there are two places that need to be modified:

1. [CodeOwnersFile.FindOwnersForClosestMatch](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs#LL79-L90C14):

``` csharp
// We want to find the match closest to the bottom of the codeowners file.
// CODEOWNERS sorts the paths in order of 'RepoPath', 'ServicePath' and then 'PackagePath'.
for (int i = codeOwnerEntries.Count - 1; i >= 0; i--)
{
    string codeOwnerPath = codeOwnerEntries[i].PathExpression.Trim('/');
    // Note that this only matches on paths without glob patterns which is good enough
    // for our current scenarios but in the future might need to support globs
    if (targetPath.StartsWith(codeOwnerPath, StringComparison.OrdinalIgnoreCase))
    {
        return codeOwnerEntries[i];
    }
}
```

2. [PullRequestLabelFolderCapability.ReadConfigurationFromFile](https://github.com/Azure/azure-sdk-tools/blob/23703d23e922257be2723625c8af8b16dc66a116/tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/PullRequestLabelFolderCapability.cs#LL64-L75C18):

``` csharp
// Entries with wildcards are not yet supported
if (entries[i].ContainsWildcard)
{
    // log a warning there

    if (entries[i].PRLabels.Any())
    {
        Colorizer.WriteLine("[Yellow!Warning]: The path '[Cyan!{0}]' contains a wildcard and a label '[Magenta!{1}]' which is not supported!", entries[i].PathExpression, string.Join(',', entries[i].PRLabels));
    }

    continue; //TODO: regex expressions are not yet supported
}
```

## Proposed modifications

In the two places that require modification listed above, I will make a check for [CodeOwnerEntry.ContainsWildcard](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/CodeOwnersParser/CodeOwnerEntry.cs#L24). If it is true, I will call a newly introduced method, like `CodeOwnerEntry.ExpandWildcard` that will return a `List` of `CodeOwnerEntry`, after expanding the wildcards. 

Such expanded non-wildcard entries will be matched reverse-alphabetically, to retain the property of entries being matched bottom-to-top [1], as defined in CODEOWNERS. Here I am making an implicit assumption that wildcard means all the entries represented by wildcard would have been listed alphabetically in the CODEOWNERS file. If the author wants different order of matching, they need to list the entries explicitly.

Expanding the wildcards will require for the logic to be able to access the contents of the repository in which the CODEOWNERS file is located, to pattern-match the file paths against the wildcards. Having a handle to that file only will no longer be enough.

The [GitHub doc on CODEOWNERS syntax](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) states:

> A CODEOWNERS file uses a pattern that follows most of the same rules used in [gitignore](https://git-scm.com/docs/gitignore#_pattern_format) files.

Per this issue description, only this pattern has to be supported, as explained in the [gitignore doc](https://git-scm.com/docs/gitignore#_pattern_format):

> A slash followed by two consecutive asterisks then a slash matches zero or more directories. For example, "a/**/b" matches "a/b", "a/x/b", "a/x/y/b" and so on.

However, if it will turn out that ROI on supporting other patterns too will be good, I will do so too.

#### Footnotes

[1] per [this comment](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs#L79):

> // We want to find the match closest to the bottom of the codeowners file.

and [our CODEOWNERS documentation](https://github.com/Azure/azure-sdk/blob/main/docs/policies/opensource.md#codeowners):

> Place more general rules higher in the file and more specific rules lower in the file as GitHub uses the last matching expression

## Why do I think these are the places to modify, and no other?

The parsing logic lives in [CodeOwnersFile.ParseContent](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs#LL18C52-L18C52). It returns a value of type `List<CodeOwnerEntry>`. Each CODEOWNERS entry is parsed into an aptly named class [CodeOwnerEntry](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/CodeOwnersParser/CodeOwnerEntry.cs#L127-L129). 

`CodeOwnerEntry` CODEOWNERS file line parsing logic already supports reading paths with wildcards into `CodeOwnerEntry.PathExpression`, as seen in [CodeOwnerEntry.ParsePath](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/CodeOwnersParser/CodeOwnerEntry.cs#L127-L129).

This means that any limitations of supporting wildcards need to be present downstream of a call to `CodeOwnersFile.ParseContent` and hence I analyzed where the value output of this method flows to.

I made the analysis by loading in VS Code the entire repository and doing `Find all references` on [CodeOwnersFile.ParseContent](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs#LL18C52-L18C52), and also by using GitHub web code browser navigation.

In addition, I also looked at references to [CodeOwnerEntry.PathExpression and CodeOwnerEntry.ContainsWildcard](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/CodeOwnersParser/CodeOwnerEntry.cs#LL22-L24C70).

Here are all the use cases I have identified:

### Use case 1: The `code-owners-parser`

`CodeOwnersFile.ParseContent` is called by 
`CodeOwnersFile.ParseFile` which is called by 
`CodeOwnersFile.ParseAndFindOwnersForClosestMatch` which is called by
`Azure.Sdk.Tools.RetrieveCodeOwners.Program.Main`
which, in turn, ends up taking **one** `CodeOwnerEntry` (not a list, just one), serializing it to JSON, and outputting it to STDOUT, as seen in the [Program.cs, here](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/Azure.Sdk.Tools.RetrieveCodeOwners/Program.cs#LL33-L34C50): 

``` csharp
var codeOwnerJson = JsonSerializer.Serialize<CodeOwnerEntry>(codeOwnerEntry, new JsonSerializerOptions { WriteIndented = true });
Console.WriteLine(codeOwnerJson);
```

This tool is also run via the pipeline [azure-sdk / internal / tools / tools - code-owners-parser](https://dev.azure.com/azure-sdk/internal/_build?definitionId=3188).

This pipeline can be used to publish a NuGet package, e.g.:

```
Pushing Azure.Sdk.Tools.RetrieveCodeOwners.1.0.0-dev.20221205.3.nupkg to 'https://pkgs.dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_packaging/f9f4dcc6-8e73-7147-a0d8-8c14278093ff/nuget/v2/'...
  PUT https://pkgs.dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_packaging/f9f4dcc6-8e73-7147-a0d8-8c14278093ff/nuget/v2/
```

The call to [ParseAndFindOwnersForClosestMatch](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs#LL18C52-L18C52) does the following:

```
public static CodeOwnerEntry ParseAndFindOwnersForClosestMatch(string codeOwnersFilePathOrUrl, string targetPath)
{
    var codeOwnerEntries = ParseFile(codeOwnersFilePathOrUrl);
    return FindOwnersForClosestMatch(codeOwnerEntries, targetPath);
}
```

where `FindOwnersForClosestMatch` has the first of two places that require modification, as mentioned in the beginning of this post. This method is also `public`, so it may be depended upon by the consumers of the NuGet package.

### Use case 2: `notification-configuration`

`CodeOwnersFile.ParseContent` is called by 
`CodeOwnersFile.ParseFile` which is called by 
`GitHubService.GetCodeownersFileImpl` which is called by
`GitHubService.GetCodeownersFile` which is called by
`NotificationConfigurator.SyncTeamWithCodeOwnerFile`

This method then ends up calling [later in the same method](https://github.com/Azure/azure-sdk-tools/blob/main/tools/notification-configuration/notification-creator/NotificationConfigurator.cs#L212) the `CodeOwnersFile.FindOwnersForClosestMatch`, for each processed input build definition pipeline. The execution of this tool is triggered by the pipeline [internal / automation /
automation - build-failure-notification-subscriptions](https://dev.azure.com/azure-sdk/internal/_build?definitionId=679&_a=summary). It processes the pipeline to hook-up ADO email configurations on build failure. I elaborated on that in https://github.com/Azure/azure-sdk-tools/issues/4859#issue-1472442836

### Use case 3: `pipeline-owners-extraction`

`CodeOwnersFile.ParseContent` is called by 
`CodeOwnersFile.ParseFile` which is called by 
`GitHubService.GetCodeownersFileImpl` which is called by
`GitHubService.GetCodeownersFile` which is called by
`PipelineOwnersExtractor.Processor.GetCodeOwnerEntriesAsync` which is called by
`PipelineOwnersExtractor.Processor.ExecuteAsync`.

The data returned to `ExecuteAsync` then flows to `AssociateOwnersToPipelinesAsync` which invokes `CodeOwnersFile.FindOwnersForClosestMatch` from [this line](https://github.com/Azure/azure-sdk-tools/blob/main/tools/pipeline-owners-extractor/Azure.Sdk.Tools.PipelineOwnersExtractor/Processor.cs#L103).

Cursory analysis tells me the situation is similar to use case 2, i.e. each pipeline is being used as input to return relevant `CodeOwnersEntry`. The relevant pipeline triggering it is [internal / automation / automation - pipeline-owners-extraction](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5112&_a=summary).

### Use case 4: `FabricBot` - PR labels

`CodeOwnersFile.ParseContent` is called by 
`CodeOwnersFile.ParseFile` which is called by 
`CreateRuleFabricBot.Rules.PullRequestLabel.PullRequestLabelFolderCapability.ReadConfigurationFromFile`

which is the second code location that needs to be modified.

### Use case 5: `FabricBot` - service routing labels

`CodeOwnersFile.ParseContent` is called by 
`CodeOwnersFile.ParseFile` which is called by 
`CreateRuleFabricBot.Rules.IssueRouting.IssueRoutingCapability.ReadConfigurationFromFile` which then [doesn't do anything related to wildcard matching](https://github.com/Azure/azure-sdk-tools/blob/main/tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/IssueRouting/IssueRoutingCapability.cs#L62-L75).

**Comment by weshaggard** [comment]
>Expanding the wildcards will require for the logic to be able to access the contents of the repository in which the CODEOWNERS file is located, to pattern-match the file paths against the wildcards. Having a handle to that file only will no longer be enough.

What do you mean by expand here? Do you plan to use some sort of regex patterns to replace the gitignore patterns so you can do a match? That is sort of what I had in mind for implementing this.

Other than the one clarification the other logic and searching seems correct. Thanks for the detailed investigation.

**Comment by konrad-jamrozik** [comment]
> What do you mean by expand here? Do you plan to use some sort of regex patterns to replace the gitignore patterns so you can do a match? That is sort of what I had in mind for implementing this.
> 
> Other than the one clarification the other logic and searching seems correct. Thanks for the detailed investigation.

@weshaggard let me summarize our in-person follow-up discussion here. I also discovered another limitation, and I would appreciate your input.

We observed that the usage in [CodeOwnersFile.FindOwnersForClosestMatch](https://github.com/Azure/azure-sdk-tools/blob/main/tools/code-owners-parser/CodeOwnersParser/CodeOwnersFile.cs#LL79-L90C14) is matching specific file names against the CODEOWNERS entry, so indeed changing the logic from "does this `fileName` start with this `codeownersEntry` path" to "does this `fileName` match the `codeowners` path-with-wildcards regex" [should cover all the cases we care about](https://git-scm.com/docs/gitignore#_pattern_format), which are all the cases that involve `*` or `**` but not `!` or `?`.

However!

The second use case is FabricBot, and there is a problem with it, as it **does not** support wildcards. The CODEOWNERS path entry gets converted to FabricBot's `pathFilter`. For example, [azure-sdk-net-for-net/CODEOWNERS has this entry:](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS#L20-L21)

```
# PRLabel: %Azure.Core
/sdk/core/                                      @JoshLove-msft @christothes @annelo-msft @KrzysztofCwalina
```

which ends up being converted to [this pathFilter in fabricbot.json](https://github.com/Azure/azure-sdk-for-net/blob/main/.github/fabricbot.json#L798-L801):

```
"label": "Azure.Core",
"pathFilter": [
  "sdk/core/"
],
```

Our relevant code doing this is in [CreateRuleFabricBot/Rules/PullRequestLabel/PathConfig.cs](https://github.com/Azure/azure-sdk-tools/blob/23703d23e922257be2723625c8af8b16dc66a116/tools/CreateRuleFabricBot/CreateRuleFabricBot/Rules/PullRequestLabel/PathConfig.cs#L34) and around it, in `PullRequestLabelFolderCapability` class.

I believe the FabricBot logic matching paths against `pathFilter` is [this (Microsoft-internal)](https://dev.azure.com/mseng/1ES/_git/fabricbot.bot?path=/CapabilityUtils/src/pullRequests.ts&version=GBmaster&_a=contents):

```
/**
 * Checks whether the given file name matches any of the given set of path filters.
 * @param fileName File name to check.
 * @param pathFilters Optional set of path filters.
 */
export function doesFileNameMatchPathFilters(fileName: string, pathFilters?: string[]): boolean {
  if (!pathFilters) {
    return false;
  }

  for (const pathFilter of pathFilters) {
    if (fileName.startsWith(pathFilter)) {
      return true;
    }
  }

  return false;
}
```

as it appears to be called from [here (Microsoft-internal)](https://dev.azure.com/mseng/1ES/_git/fabricbot.bot?path=/PrAutoLabel/src/engine.ts&version=GBmaster&line=153&lineEnd=153&lineStartColumn=15&lineEndColumn=43&lineStyle=plain&_a=contents).

As you can see, this logic is doing plain `fileName.startsWith(pathFilter)`.

I see two options going forward:

1. Clarify that paths in CODEOWNERS that have wildcards on them cannot have `# PRLabel:` comments. This could be enforced by the upcoming validation: https://github.com/Azure/azure-sdk-tools/issues/4859
2. Reach out to FabricBot maintainers and ask them if it would be feasible for us to implement support of wildcards into this method. I know who to reach out to.

Given that we plan to move away from FabricBot anyway, per https://github.com/Azure/azure-sdk-tools/issues/4478, I am leaning towards option no 1.

@weshaggard let me know what you think. Also CC @JimSuplizio as possibly relevant to his work.

**Comment by weshaggard** [comment]
I agree that for now we can ignore fabricbot and any wildcard paths will just not work there. Once @JimSuplizio does his work to move to github actions for this work he will be using our library here so any file path match should work.

**Comment by JimSuplizio** [comment]
@konrad-jamrozik , Ignore the FabricBot work, right now they have what they have hard coded inside of the repository specific FabricBot.json files. I need similar things but what I'd ended up doing was including the code-owners-parser to my project and writing some utils. We should, however, have a chat about how I'm using it.

**Comment by konrad-jamrozik** [comment]
This functionality has been enabled as of:
- https://github.com/Azure/azure-sdk-tools/pull/5488
