### ISSUE TITLE
[stress testing][s] Add log count/usage widget to stress insights dashboard

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2776]
This will help us track any tests that have runaway log volume which may add significantly to our cost.

aka.ms/azsdk/stress/dashboard

**Comment by richardpark-msft** [comment]
Do you (or @ckairen) have some special handling for "the cluster has ingested too much data at once" alert? Or is it just the general email that goes to everyone?

**Comment by kurtzeborn** [comment]
Already fixed by @benbp last week.
