### ISSUE TITLE
[Test-Proxy] GeneralStringSanitizer sanitizes binary body, GeneralRegexSanitizer does not

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#2777]
There were good reasons that Josh commited [this pr](https://github.com/Azure/azure-sdk-tools/pull/2638), but we're seeing an issue with JS tests where gzipped responses are also not sanitized. Given that we store those uncompressed, I feel like that's not expected behavior.

We need to be consistent, but also do what folks expect. 

[Here is a build that shows this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1372660&view=logs&j=7e17f77e-2815-52ab-caf2-e231a45542b7&t=b6406ae8-4e49-58df-d534-c6973b1787ce&l=1836)

The gzipped body is not sanitized, so the request fails to match it.

**Comment by JoshLove-msft** [comment]
Is this on the response or request body? Agreed that both sanitizers should be consistent, but I'd expect the content type to reflect that it is text even if it is zipped.

**Comment by scbedd** [comment]
@JoshLove-msft My fix for the test was to _add_ `Content-Length`, which means the code flows through the auto-text-decode and sanitizes properly.

The failed matching is on the request body.
