### ISSUE TITLE
[Test-Proxy] Multipart/mixed sanitization

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2784]
For content-type "multipart/mixed", the request body may contain bodies of different content types. If any of the sub-bodies are textual, we should apply the body sanitizers. Additionally, each sub-part of the body may contain headers which should also probably have the default header sanitization applied, and allow users to further customize what headers are sanitized.

A simpler approach that may be good enough would be to just let multipart/mixed be considered as "textual" and attempt to apply the BodySanitizer to it.

[Traffic Example](https://raw.githubusercontent.com/Azure/azure-sdk-for-net/main/sdk/storage/Azure.Storage.Blobs.Batch/tests/SessionRecords/BlobBatchClientTests/Batch_Limit.json)

**Comment by scbedd** [comment]
The latter "simpler" approach may actually work. Right now we try to parse the content based on Encoding/Content-Type. Is there any guarantee that `multipart/mixed` can be treated as UTF8?

**Comment by JoshLove-msft** [comment]
> > The bodies may or may not be textual
> 
> Wait. By this you mean "could be json" right? It's not going to be
> 
> ```
> HEADERS
> 
> <binary content>
> ```
> 
> Right? How would that even work encoding wise.

Correct, it could be a mix of different content types:

https://www.w3.org/Protocols/rfc1341/7_2_Multipart.html

**Comment by scbedd** [comment]
Went hunting for examples of more complex multipart requests and found [Appendix C referenced in the article above.](https://www.freesoft.org/CIE/RFC/1521/45.htm)

The thing I was most concerned about was binary content types within the the body. In their example, I discovered that binary is just base64 encoded. Every other example I've dug up reflects that as well. 

My hunch is we can safely treat `multipart/mixed` as text. I'll submit a PR for that.

**Comment by JoshLove-msft** [comment]
Yes, the binary is base64 encoded, but the issue is that you don't know whether or not it can be decoded to UTF-8 without looking at the nested content types.

**Comment by scbedd** [comment]
100%, but we can't understand those nested content types on each labelled boundary unless we decode at least once. 

You see where I'm coming from here right? [Example multipart](https://github.com/Azure/azure-sdk-for-python/blob/8479758cd6b1daf4360cf3de19bea70bcb6895dd/sdk/tables/azure-data-tables/tests/recordings/test_table_aad.pyTestTableAADtest_aad_batch_all_operations_together.json#L480) request body:

So when it's a non-text type, we just write the byte array of content using ToBase64. If we wanted to treat this stuff as text, we need to decode it somehow first, otherwise there is no way to _understand_ the `ContentType` after each boundary mark.

Am I way off base? Is this as simple as reading each individual character until I hit a content type, then swapping encoding on the fly? 

```
--batch_00000000-0000-0000-0000-000000000000
Content-Type: multipart/mixed; boundary=changeset_2deb0284-577b-4bc5-9cd8-594df317b3d7

--changeset_2deb0284-577b-4bc5-9cd8-594df317b3d7
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 0

POST https://fakeendpoint.table.core.windows.net/uttable913d2aeb HTTP/1.1
x-ms-version: 2019-02-02
DataServiceVersion: 3.0
Prefer: return-no-content
Content-Type: application/json;odata=nometadata
Accept: application/json;odata=minimalmetadata
Content-Length: 317
x-ms-date: Thu, 09 Dec 2021 00:21:32 GMT
Date: Thu, 09 Dec 2021 00:21:32 GMT

{"PartitionKey": "003", "PartitionKey@odata.type": "Edm.String", "RowKey": "batch_all_operations_together", "RowKey@odata.type": "Edm.String", "test": true, "test2": "value", "test2@odata.type": "Edm.String", "test3": 3, "test4": 1234567890, "test5": "2021-12-09T08:21:32.040478Z", "test5@odata.type": "Edm.DateTime"}
--changeset_2deb0284-577b-4bc5-9cd8-594df317b3d7
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 1

DELETE https://fakeendpoint.table.core.windows.net/uttable913d2aeb(PartitionKey='003',RowKey='batch_all_operations_together-1') HTTP/1.1
x-ms-version: 2019-02-02
DataServiceVersion: 3.0
If-Match: *
Accept: application/json;odata=minimalmetadata
x-ms-date: Thu, 09 Dec 2021 00:21:32 GMT
Date: Thu, 09 Dec 2021 00:21:32 GMT


--changeset_2deb0284-577b-4bc5-9cd8-594df317b3d7
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 2

PATCH https://fakeendpoint.table.core.windows.net/uttable913d2aeb(PartitionKey='003',RowKey='batch_all_operations_together-2') HTTP/1.1
x-ms-version: 2019-02-02
DataServiceVersion: 3.0
If-Match: *
Content-Type: application/json
Accept: application/json
Content-Length: 320
x-ms-date: Thu, 09 Dec 2021 00:21:32 GMT
Date: Thu, 09 Dec 2021 00:21:32 GMT

{"PartitionKey": "003", "PartitionKey@odata.type": "Edm.String", "RowKey": "batch_all_operations_together-2", "RowKey@odata.type": "Edm.String", "test": true, "test2": "value", "test2@odata.type": "Edm.String", "test3": 10, "test4": 1234567890, "test5": "2021-12-09T08:21:32.040478Z", "test5@odata.type": "Edm.DateTime"}
--changeset_2deb0284-577b-4bc5-9cd8-594df317b3d7
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 3

PUT https://fakeendpoint.table.core.windows.net/uttable913d2aeb(PartitionKey='003',RowKey='batch_all_operations_together-3') HTTP/1.1
x-ms-version: 2019-02-02
DataServiceVersion: 3.0
If-Match: *
Content-Type: application/json
Accept: application/json
Content-Length: 321
x-ms-date: Thu, 09 Dec 2021 00:21:32 GMT
Date: Thu, 09 Dec 2021 00:21:32 GMT

{"PartitionKey": "003", "PartitionKey@odata.type": "Edm.String", "RowKey": "batch_all_operations_together-3", "RowKey@odata.type": "Edm.String", "test": true, "test2": "value", "test2@odata.type": "Edm.String", "test3": 100, "test4": 1234567890, "test5": "2021-12-09T08:21:32.040478Z", "test5@odata.type": "Edm.DateTime"}
--changeset_2deb0284-577b-4bc5-9cd8-594df317b3d7
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 4

PATCH https://fakeendpoint.table.core.windows.net/uttable913d2aeb(PartitionKey='003',RowKey='batch_all_operations_together-4') HTTP/1.1
x-ms-version: 2019-02-02
DataServiceVersion: 3.0
Content-Type: application/json
Accept: application/json
Content-Length: 320
x-ms-date: Thu, 09 Dec 2021 00:21:32 GMT
Date: Thu, 09 Dec 2021 00:21:32 GMT

{"PartitionKey": "003", "PartitionKey@odata.type": "Edm.String", "RowKey": "batch_all_operations_together-4", "RowKey@odata.type": "Edm.String", "test": true, "test2": "value", "test2@odata.type": "Edm.String", "test3": 10, "test4": 1234567890, "test5": "2021-12-09T08:21:32.040478Z", "test5@odata.type": "Edm.DateTime"}
--changeset_2deb0284-577b-4bc5-9cd8-594df317b3d7
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 5

PUT https://fakeendpoint.table.core.windows.net/uttable913d2aeb(PartitionKey='003',RowKey='batch_all_operations_together-5') HTTP/1.1
x-ms-version: 2019-02-02
DataServiceVersion: 3.0
Content-Type: application/json
Accept: application/json
Content-Length: 320
x-ms-date: Thu, 09 Dec 2021 00:21:32 GMT
Date: Thu, 09 Dec 2021 00:21:32 GMT

{"PartitionKey": "003", "PartitionKey@odata.type": "Edm.String", "RowKey": "batch_all_operations_together-5", "RowKey@odata.type": "Edm.String", "test": true, "test2": "value", "test2@odata.type": "Edm.String", "test3": 10, "test4": 1234567890, "test5": "2021-12-09T08:21:32.040478Z", "test5@odata.type": "Edm.DateTime"}
--changeset_2deb0284-577b-4bc5-9cd8-594df317b3d7--

--batch_00000000-0000-0000-0000-000000000000--

```

**Comment by JoshLove-msft** [comment]
No, you are correct. I thought you were saying that the whole content can be just treated as text and passed to the sanitizer. You can safely decode the entire body from base64 to UTF-8. At that point, you'd need to inspect each nested content-type to determine what to do.

**Comment by scbedd** [comment]
Ok. We're on the same page. I'm figuring out where to put the additional decoding steps.
