### ISSUE TITLE
[stress testing] Reduce log analytics data volume cap

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2791]
Currently the data volume cap is 100gb per day, which is much higher than we need and means that stress tests which have runaway logging will end up incurring more cost than they need to before we get alerted. We should look at usage and lower the cap to something more appropriate (e.g. 7-10 GB/day as normal usage is around 3 GB/day).

We might also considering configuring extra alerts around log volume rate of change, though that could end up being noisy with bursty stress tests.

Updating quota:
https://azure.microsoft.com/en-us/updates/controlling-data-volume-and-retention-in-log-analytics-2/

@ckairen this is a quick task but I think you should do it to spread the knowledge around.

```
Usage
| where TimeGenerated > startofday(ago(31d))
| where StartTime > startofday(ago(31d))
| where IsBillable == true
| summarize TotalVolumeGB = sum(Quantity) / 1000 by bin(StartTime, 1d), Solution
| render columnchart
```

**Comment by richardpark-msft** [comment]
This is a mostly theoretical issue that we've never run into in actual testing.

**Comment by benbp** [comment]
@richardpark-msft hey no stress testing the github PR sarcasm detector.

**Comment by ckairen** [comment]
Set both prod and test, cap @ 10G, warning @ 7G
