### ISSUE TITLE
Failing PR automation: SDK azure-sdk-for-net-track2

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2807]
The SDK azure-sdk-for-net-track2 PR check is failing on [this PR](https://github.com/Azure/azure-rest-api-specs/pull/17718).

The failure looks like this:
![image](https://user-images.githubusercontent.com/85643503/155550284-29f0b5d3-bc60-4902-8fb2-2f415dbf5692.png)

[link](https://github.com/Azure/azure-rest-api-specs/pull/17718/checks?check_run_id=5283127811)

This looks like the automation is failing since the error message gives no clear indication of what is wrong with the PR.

**Comment by fengzhou-msft** [comment]
The PR added a tag but did not update the default tag, therefore the generated SDK is not changed. We need to confirm from the pipeline side whether the error is related to that.

**Comment by akning-ms** [comment]
@dw511214992 to take a look

**Comment by dw511214992** [comment]
This issue is fixed two weeks ago, and you shouldn't encounter it again.
