### ISSUE TITLE
Mouse wheel in APIView does not scroll consistently

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#2812]
With a [review open](https://apiview.dev/Assemblies/Review/d2d05cf175c7478184662d580a300e68?diffRevisionId=e229c861eb9940de96b6adc1d5a8e5b1&doc=False&diffOnly=False&revisionId=3efcb9e9cb314dbe982852d85df4bf24) in MSEdge Dev, there are places - like over source in the right pane - where the mouse wheel to scroll the page only nudges the page a couple pixels, but does not scroll. If I mouse over the ToC or in whitespace and use the wheel, the page does scroll.

I hadn't dug into why, but I imagine some mouse events are not bubbling up depending on the current element being hovered.

I'm not sure a repro video would do the problem justice as the problem is something that's not happening, but I'd be happy to do a screencast offline if that would help.

**Comment by JonathanGiles** [comment]
I've seen this also (and mentioned it in Teams). Would love to get to the bottom of this as it can be difficult to review sometimes!

**Comment by chidozieononiwu** [comment]
This has been resolved. I will close this feel free to open it if you think it's still an issue.
