### ISSUE TITLE
APIView bot should comment all PRs

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#2819]
If the PR has API changes, keep doing the same thing as today.
If the PR has no API changes, write "This PR doesn’t change the API surface of this SDK. Reference APIView is <link to automatic APIView from main>".

This will avoid some confusion where people are unclear if no message from the APIView bot means this is not enabled or not working, or if this means there was no changes.

**Comment by dw511214992** [comment]
@lmazuel
_If the PR has API changes, keep doing the same thing as today._
Does it mean there is a comment about the link of new created APIView in SDK PR?

**Comment by praveenkuttappan** [comment]
This has already been completed.
