### ISSUE TITLE
[Test-Proxy] Add flag when stopping stopping recording to control whether or not to save

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#2825]
Currently calling Record/Stop will always result in the session being saved to disk. This behavior is not ideal because it means for failed tests you will need to not call Record/Stop if you don't want to save the record. Discussed with @scbedd, and he suggested we should introduce a parameter that lets the callers tell the proxy whether or not to save.

**Comment by JoshLove-msft** [comment]
This is actually how it already works so long as the Test Framework calls record/Stop. Discussed with @scbedd, and we agreed that we probably need a way to specify whether or not to save the recording when calling record/stop

**Comment by JoshLove-msft** [comment]
@scbedd @mikeharder  should this flag also apply to InMemorySessions for perf framework?

**Comment by scbedd** [comment]
@JoshLove-msft It wouldn't hurt. It's a single line change location, so I'm not too concerned. PR incoming.

**Comment by JoshLove-msft** [comment]
Just wanted to check in on this one.
