### ISSUE TITLE
False positive PR checks in azure-rest-api-specs repo

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2837]
PR #17921 in azure-rest-api-specs has several failing PR checks

https://github.com/Azure/azure-rest-api-specs/pull/17921/checks

![image](https://user-images.githubusercontent.com/85643503/156305471-0e053f00-37a6-48b6-a0ca-acedc84a40aa.png)

But this PR only changed "examples" files, so it seems very unlikely that these changes could cause breaking changes.

**Comment by akning-ms** [comment]
As the PR include too many RP change which trigger different package SDK automation, maybe one of RP has default tag change in another PR which introduced SDK generation failure.  @msyyc to take a python and @fengzhou-msft to take a .Net

**Comment by akning-ms** [comment]
Also @dw511214992 to take a look

**Comment by dw511214992** [comment]
I cannot find any information from the PR comments/checks.
By the way, the SDK breaking changes comes from comparing new generated codes to released package/main branch.(It depends on the implementation in sdk repository). So, although it only contains the change of example, there may be other breaking change in previous commit to this service.

**Comment by dw511214992** [comment]
please check my previous answer, and I will close this issue. if you encounter this kind of issue again, please create a new issue. thanks
