### ISSUE TITLE
Don't run labeling / assignments automation on Data Plane PRs to feature branches in rest-api-specs

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2856]
It looks like the current automation assigned me and Shawn Gaul to PR #18201:

https://github.com/Azure/azure-rest-api-specs/pull/18021

![image](https://user-images.githubusercontent.com/85643503/156608618-c3263520-6334-4ab6-a501-081e47959464.png)

But this PR isn’t requesting a merge into the main branch – it is targeting a feature (development) branch:

![image](https://user-images.githubusercontent.com/85643503/156608691-1fef4816-b193-4e02-8485-738ff1221ad3.png)

I think we should disable the auto-assignment of reviewers (and assignees) for PRs that are not targeting the main branch.

The automation also seems to assign labels like "BreakingChangeReviewRequired" on PRs to feature branches and this is not helpful.  That too should only run on PRs to the main branch.

Does that sound reasonable?  If so, how hard would it be to get that change implemented?

**Comment by weidongxu-microsoft** [comment]
@akning-ms Would you take a look? Maybe we do need to have a DataPlane label (added if PR touches file in **/data-plane/**), and bot would behave somewhat differently on DataPlane.

**Comment by akning-ms** [comment]
currently, if no special reason, all feature branch will also need a review to avoid huge PR when move feature branch to main,
Hi Mike, are you sure remove all review for feature branch for dataplane?

**Comment by mikekistler** [comment]
I don't think we want to be reviewing "work in progress" by the service teams, and I doubt they would want that either.

The service team can / should review merges into their feature branch, and when it is ready bring that for a formal review with a PR to main.

As for huge PR reviews, we've had plenty of whoppers and managed to get through them.

And if the service team really does want early feedback on changes, then they can open a draft PR to main with the changes they want reviewed.

@tg-msft , @johanste , @markweitzel , please weigh in to think if we should be in the game of reviewing PRs to feature branches in azure-rest-api-specs.

**Comment by tg-msft** [comment]
I don't think we should be reviewing feature branches by default.  It's a little jarring for folks on partner teams who are making iterative PRs when we drop in and start commenting on things that aren't done yet.

What if the bot only ran in main by default, but partners ready to engage us had a command to trigger the bot in a feature branch?

**Comment by heaths** [comment]
> I don't think we should be reviewing feature branches by default. It's a little jarring for folks on partner teams who are making iterative PRs when we drop in and start commenting on things that aren't done yet.

@tg-msft I strongly disagree. Not only are some beta SDKs shipping off feature branches with teams working on multiple api-versions in general, as a codeowner/reviewer for swaggers it's better and more efficient for me to review smaller changes than gigantic ones when merging to main, especially when the /specification folder contains all-new files for even small changes to a previous api-version (in a new api-version). I want to be reviewing these PRs.

That said, @akning-ms can we prioritize this? Almost daily - and then multiple times a day - I have to ping someone like @lmazuel  to use his admin powers to merge PRs with validation errors only because they have a breaking change validation error. Me nor most people who can be assigned PRs have those permissions, and it's a waste of breaking change approvers' time to have to review these going into feature branches. Run the validation errors so the teams can discover and fix real issues, but don't add the labels requiring exemptions.

/cc @JeffreyRichter

**Comment by mikekistler** [comment]
Yes, I'm specifically talking about the REST API board. Service teams can request a review from anyone on a PR to a feature branch.

I don't like the practice of releasing betas from feature branches but that's a separate topic.

It seems that we are in agreement that PR checks should only block merges to main -- let's at least move forward on that part.

**Comment by weidongxu-microsoft** [comment]
A trick of "Approved-BreakingChange" label can skip the validation. However it seems indeed some very useful for breaking change check when targeting feature branch.

PS: I am spamming "Approved-Avocado" in main because of "MISSING_APIS_IN_DEFAULT_TAG".

**Comment by akning-ms** [comment]
Few things we are working to improve this is:
1. Removing protect branch policy setting in OpenAPIHub, (will be released in 1 or 2 weeks)
2. Assignment bot will only assign PR target to main / Dev-* /Release-* which is set as protect branch. (support in next sprint- May) 

So service team can bypass PR review for their feature branch if use other branch name which is not protect. 
it means service team can merge their PR into the branch by themself.
If they want PR review for feature branch. they can use branch name as Dev-* / Release-* ( For the case in management plane PR (NRP, CRP, SQL etc )
Is this make sense? @heaths

**Comment by mikekistler** [comment]
> I am spamming "Approved-Avocado" in main because of "MISSING_APIS_IN_DEFAULT_TAG".

Did you open an issue to get that fixed?

**Comment by heaths** [comment]
We hit `MISSING_APIS_IN_DEFAULT_TAG` in COGS Language frequently because the "Language" pseudo-RP doesn't always include every swagger from past api-versions. I've talked with @johanste about this problem but we have no plans of changing it for now.

**Comment by weidongxu-microsoft** [comment]
> > I am spamming "Approved-Avocado" in main because of "MISSING_APIS_IN_DEFAULT_TAG".
> 
> Did you open an issue to get that fixed?

Talked last week with Arthur and Josephine internally on group chat. The recommendation of readme structure is still in progress, so this might take a few more weeks.

**Comment by weshaggard** [comment]
>The error of MISSING_APIS_IN_DEFAULT_TAG is supposed to be correct. Just the way to fix it in data-plane is not decided... (and that "fix" might involve more readme.md)

If we don't know how to fix this we should try and disable the check until we have guidance for how to handle this.

**Comment by mikekistler** [comment]
For Data plane, assignees will only be added by the automation when the PR is to the main branch.

A service team can request review by adding assignees/reviewers manually.

**Comment by raych1** [comment]
Work item created in ADO https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1548145.

**Comment by raych1** [comment]
@mikekistler , change was deployed to production pipeline that only the PR targeting `main` branch will be assigned for review.
