### ISSUE TITLE
 [TestProxy] ReadMe misspelled word

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-tools#2858]
Link to the misspelled word in the README.md[https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/README.md#:~:text=if%20we%20take-,approporiate,-care%20in%20the](url)

**Comment by benbp** [comment]
@l0lawrence pull requests are also welcome from anybody if you'd like to fix the typo yourself :)
