### ISSUE TITLE
Investigate exporting subscription activity logs to log analytics

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#2859]
Sometimes we need to do historical queries against the testing subscriptions to see what changed, if roles were updated, resources deployed, etc. This can get especially cumbersome when querying across a lot of data many weeks old. If the cost is not too high, I think it's worth exporting the subscription activity logs to a log analytics resource so we can create easy/fast queries via KQL instead.

**Comment by kurtzeborn** [comment]
We talked about this in triage and agreed we should try using the activity log data that already exists on the internal ARM production logs and see if we can make/share some queries that work well with that.

**Comment by benbp** [comment]
Closing for now.
