### ISSUE TITLE
Fix accessibility issues in Azure SDK Guidelines

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2873]
Microsoft Accessibility Insights (FastPass) reports a number of accessibility issues with the Azure SDK Guidelines pages:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/85643503/156903227-8c4dd68f-d31a-4ae9-8fea-44a54ff63705.png">

These should be corrected wherever possible.

**Comment by kurtzeborn** [comment]
@mikekistler, can you put a link to the FastPass report in here or instructions on how to generate it when this makes it to the top of our backlog?

**Comment by mikekistler** [comment]
How to generate the Fastpass Report:
1. Install the Microsoft Accessibility Insights browser extension
   - Go to https://accessibilityinsights.io/, click on "Get Accessibility Insights" and then "Add to Chrome/Edge"
2. Navigate to the SDK Guidelines page and activate the extension
3. Select "Fast Pass"
