### ISSUE TITLE
openapi-workflow-bot generates bad link to API Specs Comparison Report Generator 

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2906]
For PRs opened in the azure-rest-api-specs repo, the openapi-workflow-bot posts a comment shortly after the PR is opened with various bits of information, among them a link to the "API Specs Comparison Report Generator".  I believe that the intent of this link is to directly load the API Diff for the specific PR.  Here' an example from [PR 18169](https://github.com/Azure/azure-rest-api-specs/pull/18169#issuecomment-1064094391):
```
[API Specs Comparison Report Generator](https://portal.azure-devex-tools.com/tools/diff?pr=Azure/azure-rest-api-specs/18169)
```
Unfortunately, navigating to that link opens the page on OpenAPI Hub with an error message "* Mandatory fields for generating the compare report":

![image](https://user-images.githubusercontent.com/85643503/157774230-609ba90a-558b-42dd-8fa3-6ba704eb8615.png)

**Comment by akning-ms** [comment]
It is by design to save your time to input all parameters for api diff, but you have to choose the readme tags/version to be compared  @mikekistler , yes, it may still need to improve like preset some tag, maybe we can do it in integration with API view. @honghr to awareness

**Comment by mikekistler** [comment]
Agreed that we need to preset the tag. The pipeline already decides which tags to use for the breaking changes checks, and we should just use the same tags there.

**Comment by mikekistler** [comment]
Then I recommend simply removing the bad link.

**Comment by mikekistler** [comment]
We'll leave the link as it is not "broken" just hard to use for novices.
