### ISSUE TITLE
Add option to collapse sections in API review

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#2921]
We need UI changes to show child level entries in collapsed panel and reviewer can expand the section to see underlying section if required.

I am working with [@Ruoxuan Wang](mailto:Ruoxuan.Wang@microsoft.com) on supporting swagger review in APIView. Swagger reviews are massive in terns of size and a lot of information in these swagger files are not required to be displayed by default. We want to support collapsible panels in APIView review page so that reviewer can expand to see underlying information if they want. I need some help from you to make UI side scripting and css changes that supports this feature. I will generate class name and child group names in a way it will look like below.
For e.g. We want to show below review.

NameSpace Azure.PackageNameRoot  
Class NameClass1 >
     Method Class1Method1()
     Method Class1Method2()
Class NameClass2 >
     Method Class1Method1()
     Method Class1Method2()
NameSpace Azure.PackageNameRoot.sub 
Class NameClass1 >
     Method Class1Method1()
     Method Class1Method2()
Class NameClass2 >
     Method Class1Method1()
     Method Class1Method2()

This will by default look like in collapsible mode like below

  NameSpace Azure.PackageNameRoot 
Class NameClass1 
Class NameClass2
NameSpace Azure.PackageNameRoot.sub 
Class NameClass1 
Class NameClass2

Parent class will have class name like “classname>-header” and it’s child content will have class name like “classname-content”. We can change these class name or id as well.

**Comment by chidozieononiwu** [comment]
resolved byhttps://github.com/Azure/azure-sdk-tools/pull/4091
