### ISSUE TITLE
Multiple failures in azure-rest-api-specs-pr pipelines

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#2937]
In email from @pvrk regarding https://github.com/Azure/azure-rest-api-specs-pr/pull/5524

```
We have made the changes that were discussed in last review meeting, But facing below errors in the PR.
 
1. Go SDK generation is failing in autorest· [https://github.com/Azure/azure-rest-api-specs-pr/pull/5524/checks?check_run_id=56231090622](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs-pr%2Fpull%2F5524%2Fchecks%3Fcheck_run_id%3D56231090622&data=04%7C01%7Cmikekistler%40microsoft.com%7C76beec2a3a0b404b971a08da0b328455%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637834608905187474%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Fn2UcKrkj7yVEzhx7GF4mx%2FLYl0Tf2%2FuHkA%2BXrDiQvU%3D&reserved=0).
2. Swagger SDK Breaking Change Tracking is failing, although, this is first ever PR. Its incorrectly comparing with our management set of APIs. [https://github.com/Azure/azure-rest-api-specs-pr/pull/5524/checks?check_run_id=56230935833](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs-pr%2Fpull%2F5524%2Fchecks%3Fcheck_run_id%3D56230935833&data=04%7C01%7Cmikekistler%40microsoft.com%7C76beec2a3a0b404b971a08da0b328455%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637834608905187474%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Vg9X3%2FgqxAxWMs4yl4QbAMhYtv09kU83VqWJiSoftmE%3D&reserved=0).
3. Pretty print checks are passing on the local run for same set of files. How can we check exact errors locally to fix?
```

**Comment by akning-ms** [comment]
@ruowan  to take a #2 #3,  
@weshaggard for #1, do you know who own GO SDK generation for dataplane?

**Comment by mikekistler** [comment]
@RickWinter owns Go SDK generation for dataplane.

**Comment by Petermarcu** [comment]
@jhendrixMSFT  as FYI

**Comment by jhendrixMSFT** [comment]
I reran the failed the job for whatever reason the logs aren't accessible.  At any rate, as this is executing the track 1 code generator, and we no longer generate data-plane for track 1, can we remove this step?

**Comment by akning-ms** [comment]
for 1, go sdk track1 code gen should already removed, @dw511214992 to confirm and check above 2,

**Comment by dw511214992** [comment]
The PR is a dataplane PR, and it shouldn't include `azure-sdk-for-go` in readme.md because azure-sdk-for-go doesn't support generating dataplane sdk in sdk automation pipeline.  

About the sdk breaking change tracking ci, I think the PR change the swaggers in mgmt folder, and go sdk pipeline generates breaking change in mgmt sdk side. Although the PR changes to store the swaggers in data-plane folder, the original generated breaking change cannot be moved because the sdk breaking change tracking ci's architecture restriction.

Moreoever, `azure-sdk-for-net` should be changed to `azure-sdk-for-net-track2`

I have added comment to the PR.

**Comment by raych1** [comment]
I assume @dw511214992 resolved this issue with his comment in the associated PR. Feel free to re-open this issue if necessary.
