### ISSUE TITLE
Stress test resources are deleted earlier than they should be

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#2954]
I had a test running in southeastasia for about 94h when the resources for the test were deleted. Since stress test apps are intended to test longer timelines (7 days or so) we need them to run for longer.

Talking with @ckairen  and @benbp  it looks like we're creating resource groups but assuming that a given test is only deployed once, which is no longer true now that we support deploying the same test to multiple namespaces. This means that the previous system (where a resource group was basically just the test name + the deployment ID) isn't guaranteed to be globally unique amongst all deployments in the Kubernetes cluster.

The simplest solution is just to use the same random naming that we use for resources and not worry about having a plain text association between the resources and the test. Developers that need to do some sort of collation can just look at the .env file for their test and figure out which resources they're looking at.

In the future it'd be nice to do some metadata tagging on the resource group so you can do some searches, but given the resources are temporary in nature it's probably not a huge deal to do that.

**Comment by benbp** [comment]
Linked a PR that should act as a short term workaround, but we should keep this open to think about the tagging, etc. that you mention.

**Comment by richardpark-msft** [comment]
(reopening: probably closed on accident since your previous comment indicates you want to keep it open)

**Comment by benbp** [comment]
The core issue was basically a bug that is fixed now. Some of the ideas around metadata are still valid, but not super high priority and just "nice to have." Closing unless those asks become higher priority.
