### ISSUE TITLE
PS Module Helper should be able to clobber 

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#2960]
The ps module helper fails when attempting to install `Az.Storage` on windows agents. I think we should add some kind of `-AllowClobber` feature

Example failure: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1454990&view=logs&j=34680a5f-6ae3-5138-ac88-c2c786351f1e&t=2a1986a3-0bcc-56b5-60f7-9b7c19a7a9f7&l=72

```
Installing module Az.Storage with min version 4.3.0 from https://www.powershellgallery.com/api/v2
PackageManagement\Install-Package : The following commands are already available on this system:'Start-CopyAzureStorageBlob,Stop-CopyAzureStorageBlob'. This module 'Az.Storage' may override the existing commands. If you still want to install this module 'Az.Storage', use -AllowClobber parameter.
At C:\program files\powershell\7\Modules\PowerShellGet\PSModule.psm1:9711 char:34
+ … talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Microsoft.PowerShel…lets.InstallPackage:InstallPackage) [Install-Package], Exception
+ FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
##[debug]Exit code: 1
##[debug]Leaving Invoke-VstsTool.
##[error]PowerShell exited with code '1'.
```

_Originally posted by @danieljurek in https://github.com/Azure/azure-sdk-for-cpp/pull/3329#discussion_r833562603_

**Comment by weshaggard** [comment]
In general we shouldn't need to allowclobber because the helper is supposed to check to see if the package already exists and if so not install. We should investigate to understand of those cmd-lets are coming from somewhere else or if there is some other conflict that we should try handling.

**Comment by kurtzeborn** [comment]
It's been a while since this was opened and we're not hitting this now.  If we hit this again in the future we should revist.
