### ISSUE TITLE
Add git diff checking for sparse checkout

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#2965]
**Summary**
Sparse checkout has a static setting. We do have cases which diff changes in PR are outside of sparse checkout paths.

**Problem**
Here is the core pipeline complains about the template changes. 
If we have changes in both core and template. sparse-checkout only checkout core package and git diff returns changed in files in template and core. So the template file is not in local caused the following issue.
![image](https://user-images.githubusercontent.com/48036328/159814909-15d09535-4817-4a1b-9c29-a99bb79cb4fa.png)

**Proposal**
Add git diff changes together with sparse checkout.

**Comment by kurtzeborn** [comment]
We've already handled this in get-changed-files.ps1, so we probably don't need this any more.
