### ISSUE TITLE
API viewer need support GO generic

### ISSUE THREAD

**Issue by tadelesh** [Azure/azure-sdk-tools#2969]
As GO SDK will use the latest GO 1.18 with generic support, it is necessary that the API viewer should do a upgrade to support the generic.

**Comment by lirenhe** [comment]
@weshaggard, this issue blocks us to generate API Views for GO track2 mgmt. plane that leveraging the GO 1.18 features.
Could you help to handle it with priority? Thanks

**Comment by weshaggard** [comment]
@mikekistler @RickWinter who is the owner of the APIView go parser?

**Comment by RickWinter** [comment]
Charles is working on fixes.  A PR will be coming once fixes are available.

cc: @chlowell
