### ISSUE TITLE
C++ APIView does not appear to have a mechanism to show comments.

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk-tools#2975]
https://apiview.dev/Assemblies/Review/5b2efd771af642728e4796813564404b

C++ APIViews don't seem to have the ability to show comments. The comments appear to be in the cppast file, but they are not shown in the APIView:
|       |-CXXRecordDecl 0xa47c708 <line:32:3, line:62:3> line:32:9 referenced class AttestationType definition
|       | |-DefinitionData standard_layout has_user_declared_ctor can_const_default_init
|       | | |-DefaultConstructor
|       | | |-CopyConstructor simple non_trivial has_const_param needs_overload_resolution implicit_has_const_param
|       | | |-MoveConstructor exists simple non_trivial needs_overload_resolution
|       | | |-CopyAssignment simple non_trivial has_const_param needs_implicit implicit_has_const_param
|       | | |-MoveAssignment exists simple non_trivial needs_overload_resolution
|       | | `-Destructor simple non_trivial needs_overload_resolution
|       | |-public 'Azure::Core::_internal::ExtendableEnumeration<AttestationType>':'Azure::Core::_internal::ExtendableEnumeration<Azure::Security::Attestation::Models::AttestationType>'
|       | |-FinalAttr 0xa47d378 <col:25> final
|       | |-FullComment 0xb305e58 <line:28:5, line:31:3>
|       | | |-ParagraphComment 0xb305d88 <line:28:5>
|       | | | `-TextComment 0xb305d68 <col:5> Text=" "
|       | | |-BlockCommandComment 0xb305da0 <col:6, line:29:29> Name="brief"
|       | | | `-ParagraphComment 0xb305df8 <line:28:12, line:29:29>
|       | | |   |-TextComment 0xb305dc0 <line:28:12, col:91> Text=" The AttestationType type represent a Trusted Execution Environment supported by"
|       | | |   `-TextComment 0xb305dd8 <line:29:5, col:29> Text=" the attestation service."
|       | | `-ParagraphComment 0xb305e30 <line:31:1, col:3>
|       | |   `-TextComment 0xb305e10 <col:1, col:3> Text="   "

**Comment by maririos** [comment]
@LarryOsterman is this still an issue?

**Comment by LarryOsterman** [comment]
No, closing.
