### ISSUE TITLE
Add "Help" link to ApiView

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-tools#2989]
We have a lot of partners outside the SDK team using ApiView today and that number is going to explode when we start using it for REST API reviews.  @heaths made a great suggestion to link [our README](https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/APIView/APIViewWeb/README.md#types-of-api-reviews) from inside ApiView itself.  This will both help partners figure out how to use the tool and show them where to file issues if they encounter unexpected behavior.

**Comment by heaths** [comment]
I have a change ready, but was waiting for help from the Edge community on another issue I was actually trying to solve. If it goes much longer without resolution, I'll just submit a PR for this change.
