### ISSUE TITLE
Swagger validation is returning erroneous comparisons between dissimilar models

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#2995]
If you look at https://github.com/Azure/azure-rest-api-specs/pull/18173/checks?check_run_id=5503209529, it shows a bunch of RemovedProperty errors. But when I look at the lines, they are comparing two completely different models. I helped create these branches and they did start as a copy of previous versions and have been kept up to date, so I don't think these validation errors are correct.

**Comment by akning-ms** [comment]
@heaths cross-api version breaking change is mainly to protected stable version. 
If the last version of key vault is 7.2, then the result should be correct, if no. @jianyexi can help look into this issue

**Comment by jianyexi** [comment]
@heaths 

take the first error as an example, 
![image](https://user-images.githubusercontent.com/59603451/160524774-15003a03-2843-4a23-a683-61577e166daf.png)

actually, it's comparing the below properties, but they point to different models in the swagger before and after the PR 
https://github.com/Azure/azure-rest-api-specs/blob/d8ec90b901ab4d3418157b754804f4a1d3065441/specification/keyvault/data-plane/Microsoft.KeyVault/preview/7.4-preview.1/securitydomain.json#L233-L237

before:
        "certificates": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SecurityDomainJsonWebKey"
          },

after:
"certificates":` {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SecurityDomainCertificateItem"
          },

**Comment by heaths** [comment]
Thank you for clarifying. I do see what you're saying, but it wasn't obvious from the links in the error. Could you maybe emit the JSONPath (or similar syntax) of the whole property chain, like `$.CertificateInfoObject.certificates[0].kid` vs. `$.CertificateInfoObject.certificates[0].value`?

**Comment by jianyexi** [comment]
yes, but it's designed to deep into the reference to compare and the '$.CertificateInfoObject.certificates[0].kid' is invalid jsonpath for your cases
