### ISSUE TITLE
[Python] ACR APIView is unexpected

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#3012]
See this code:
https://github.com/Azure/azure-sdk-for-python/blob/e3e8135c83d0ca4cde1aae683b7304cfde39b276/sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_container_registry_client.py#L573-L586

With 2 overloads and one async method.

This is what APIView gives:
https://apiview.dev/Assemblies/Review/e77720207ba7448e84cb77859392731d#azure.containerregistry.aio.ContainerRegistryClient

![image](https://user-images.githubusercontent.com/1050156/160883688-397316f5-413d-4990-b6c4-0cce228441ca.png)

![image](https://user-images.githubusercontent.com/1050156/160883724-eb7ba8e0-1237-47db-84a1-149a33864928.png)

Why two functions? Why one async, and one not? Something feels not right :)

**Comment by tjprescott** [comment]
This is the same underlying issue as #3011.

**Comment by tjprescott** [comment]
#3044 will fix this, but there's an underlying problem in the ACR SDK. Their overload signatures are not compatible with the implementation because they do not include the `async` keyword.
