### ISSUE TITLE
C, C++, and Go do not show up in Service grouping

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-tools#3014]
Service grouping currently doesn't work for C, C++ and Go because package name and Service name is not available for these reviews to  map. We don't have a mechanism to find this mapping for these reviews. Can you please file an issue? I will check what can be done to identify this info. all C++ reviews are listed under "Other -> Other" group.

**Comment by heaths** [comment]
I also found that Go (golang) shows up as "Other" with a C# icon and assembly name e.g., https://apiview.dev/Assemblies/Review/81f68e700dcd4243a0ced7223e4d71fa. Perhaps related, but I'm happy to open another bug if needed.

/cc @JeffreyRichter

**Comment by praveenkuttappan** [comment]
Closing this issue since we removed service name-based grouping
