### ISSUE TITLE
M1 Mac problems with the docker image -- test proxy --

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/azure-sdk-tools#3020]
@LuChen-Microsoft  reported the below while testing the communication SDK in JS.  

```
docker run -v /Users/luc/repos/azure-sdk-for-js/sdk/communication/communication-chat:/srv/testproxy -p 5001:5001 -p 5000:5000 azsdkengsys.azurecr.io/engsys/testproxy-lin:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
docker: Error response from daemon: Ports are not available: listen tcp 0.0.0.0:5000: bind: address already in use.
ERRO[0000] error waiting for container: context canceled   
```
I've suggested she run the tool with "dotnet tool" command manually for now until we figure out a solution for this.

EDITED BY @scbedd:

Going to tackle this in a two-stage fashion.

1. [Add ARM docker image](https://github.com/Azure/azure-sdk-tools/issues/3070)
2. Add additional publishing capability to merge multiple tagged images into a single manifest under a simplified tag.

**Comment by benbp** [comment]
Looks like we need to publish arm builds of the test proxy (testproxy-arm or testproxy-m1, etc.).

**Comment by scbedd** [comment]
@HarshaNalluru I have published a `manifest-list` that is supposed to contain an image of each platform, but I believe that I need to make some adjustments.

The image tag is `azsdkengsys.azurecr.io/engsys/testproxy:1.0.0-dev.20220407.1`

(Note there is no more `lin` vs `win` 👍 )

I don't believe this first attempt is going to work, but I don't have an M1 to try. Can you have them give this tag a shot? If it pulls down and runs properly I think we're in business.

**Comment by scbedd** [comment]
I have published our first fully multi-platform test-proxy image!

@HarshaNalluru you don't even need to _care_ what platform you're on now. Pull from this repository `azsdkengsys.azurecr.io/engsys/test-proxy` and you will get an image appropriate for your current docker platform! 

Can you have the person running into issues try the image `azsdkengsys.azurecr.io/engsys/test-proxy:1.0.0-dev.20220411.7`? I have every confidence it should be good to go based on both my local experimentation as well as manifest output:

![image](https://user-images.githubusercontent.com/45376673/162823253-1778d2f4-f3c5-4d5b-993f-7c0c46ca6e2d.png)

**Comment by HarshaNalluru** [comment]
Lovely, thank you @scbedd.
Will get this tested and let you know soon. 🙂
