### ISSUE TITLE
git-branch-push.ps1 and git-push-changes.yml should support skipping remediation steps

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#3024]
Since the remediation process could change the SHA this can break instances where a commit SHA is referenced in commits that were intended to be pushed. 

In short: Try to push what's in the repo and do not try to remediate if the push fails.

**Comment by kurtzeborn** [comment]
We have a workaround for the problem that came up originally.  This was a follow up item.  Now that 7 months have passed, I'd say we're probably not going to get to this.  If it comes up again, we'll deal with the problem at hand at that time.
