### ISSUE TITLE
[Python APIView] Parameterized decorators do not show in APIView.

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-sdk-tools#3028]
https://apiview.dev/Assemblies/Review/ee993c29a21746d5b3d98d496b538f93/5d0c16d86dc94dd5a85a8d8fe320014d?diffRevisionId=ab94b712f31a4736a71f6590bb236903&doc=False&diffOnly=False#azure.identity.aio.VisualStudioCodeCredential

We show @log_get_token_async for aio.VisualStudioCodeCredential.get_token(). But it does not show for sync one.

**Comment by tjprescott** [comment]
I think the issue is not sync/async but the fact that the sync decorator takes arguments and the async one does not.
