### ISSUE TITLE
[APIView] Edge keeps asking me to translate from Portugese

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#3029]
Whenever I'm using APIVIew, Edge keeps asking me to translate the page from Portugese. Is there a language code that can be set to silence this?

**Comment by mikekistler** [comment]
@tjprescott pls check to see if this is still happening.

**Comment by tjprescott** [comment]
A quick check this morning on my office desktop is looking good. My guess is this was fixed and the issue not closed, so I'll close this and reopen it if it recurs.
