### ISSUE TITLE
[check enforcer] Add filtering for main CI check run events and queries

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#3030]
Check enforcer gets check run events from main CI runs (e.g. main merge triggered builds, scheduled builds). In some cases, the event payload contains linked pull requests (e.g. primarily against fork repositories that have commits from main synced via PR bots). These linked pull requests trigger check enforcer to query the check run data many times. This can result in request storms against the github API causing throttling via [secondary rate limits](https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits).

We should:

- Understand when check enforcer makes these check run queries (e.g. every time, or only if the pull requests array is > 0)?
- Not query the check run API when the pull requests array is empty (this may already be the case)
- Not query the check run API when the pull requests array does not contain owned repositories
    - This is probably best achieved by checking/knowing if the repository has the check enforcer app as a github app installation. There may be efficient ways to check this data or load it out of the event payload.
- It's possible there are other improvements around when/how we do check run reports for main. Do we need to report check enforcer check runs at all for main commits, assuming the devops check runs are already registered, we will still get the "green checkbox" next to the commits in the github UI. If check enforcer only exists as a unified PR gate, then we don't need to create and query check run status for main commits.

**Comment by kurtzeborn** [comment]
We can close this.  It's been replaced by a GitHub Action based solution.
