### ISSUE TITLE
Swagger SemanticValidation PR check fails with INTERNAL_ERROR

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3057]
The [Swagger SemanticValidation check in PR #18279](https://github.com/Azure/azure-rest-api-specs/pull/18279/checks?check_run_id=5778335694) failed with an "Unexpected internal error":

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/85643503/161608458-19d78ddd-b645-4d9c-95f2-61ef59330de2.png">

**Comment by raych1** [comment]
@mikekistler , this is the [bug](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1515412) created internally and fixes are in review. Comment were added in the swagger PR for the real issue.

**Comment by raych1** [comment]
Closed as fixed.
https://github.com/Azure/oav/pull/776
