### ISSUE TITLE
Remove projects which are no longer affected in PR api-view

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#3068]
If you create a PR which affects 4 projects when you go to the automatically created pr reviews you will see 4 api views created for that PR.  If you then make an update so that only 3 projects are affected the 4th one will still show up as if it still has a change which can be confusing for the api reviewer.

It might be better if we can remove these automatically so its clear what is still in scope for the review.

**Comment by praveenkuttappan** [comment]
Each commit to a PR triggers a pipeline run for all required services. If a new commit does not effect a specific service/package then it won't get triggered and as a result APIView won't get the request to update the review.

We can identify all reviews created from previous commit and mark them as closed. Review will get recreated if the new commit impacts any API level change for any of those packages.

**Comment by maririos** [comment]
With the new desing, this might be way easier. @praveenkuttappan  will take a look again
