### ISSUE TITLE
Select-AzureSubscription does not return the subscription in v 0.8.11

### ISSUE THREAD

**Issue by fredericaltorres** [Azure/azure-sdk-tools#3073]
Select-AzureSubscription does not return the subscription anymore in v 0.8.11.
Select-AzureSubscription was returning the subscription in v 0.8.10.
The help in v 0.8.11, says the output should be the subscription.

**Comment by pcgeek86** [comment]
In most cases, the output isn't necessarily. By convention, PowerShell commands offer a `-PassThru` parameter to enable output from PowerShell cmdlets. For example, see the core PowerShell commands `Start-Process` and `Add-Member`. These are both great examples.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by ogail** [comment]
@pcgeek86 thanks for your answer!
