### ISSUE TITLE
[APIView Web] Clicking links jumps to a place hidden under the menu bar.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#3082]
I am observing this behavior on Chrome on a Mac.

When I click a link in APIView with a linkToID, the page jumps to that place, but it seems that it is hidden behind the menu bar.

Click Size:
<img width="883" alt="image" src="https://user-images.githubusercontent.com/5723682/162039250-dd17d0bd-2ef4-4201-8f6f-77d42e6cb834.png">

Jumps to hide the line behind the menu
![image](https://user-images.githubusercontent.com/5723682/162039444-4331cb57-6176-4666-af3d-7b635018c547.png)

Have to scroll back down to see.
![image](https://user-images.githubusercontent.com/5723682/162039637-89623f4a-26d3-4804-80c7-85bc25c341ac.png)

The worst part is that it also does this for the navigation, and that forces you to scroll all the way up to.

**Comment by kurtzeborn** [comment]
@chidozieononiwu looks like you may need Chrome on a MAC in order to reproduce this.

**Comment by tjprescott** [comment]
@kurtzeborn I observe this on Windows 11 on Edge as well.

**Comment by tjprescott** [comment]
This is still happening with the live APIView site. cc/ @mikekistler

**Comment by chidozieononiwu** [comment]
> This is still happening with the live APIView site. cc/ @mikekistler

You are right, this is still an issue in safari. I will work to fix it.

**Comment by mikekistler** [comment]
@chidozieononiwu FYI it was happening for me in Chrome (on MacOS).

**Comment by tjprescott** [comment]
And frankly, this is happening for me on any platform and any browser.

**Comment by chidozieononiwu** [comment]
This is now resolved. Will be deployed soon
