### ISSUE TITLE
Unified deployment pipeline for APIView

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#3098]
APIView uses Azure devops release pipeline to deploy changes to APIView. We should change this to unified pipeline to support deployment to staging and then swapping to production without logging in to Azure portal. Currently hot swap from staging to production is done using Azure portal.

**Comment by maririos** [comment]
@praveenkuttappan how is this issue related to https://github.com/Azure/azure-sdk-tools/issues/4443
