### ISSUE TITLE
[stress testing] Investigate chaos studio and chaos mesh integration progress

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#3106]
This is more of a long-running background task, but we should keep abreast of changes in azure chaos studio made to support chaos mesh.

[Background](https://docs.microsoft.com/en-us/azure/chaos-studio/chaos-studio-tutorial-aks-portal)

**Comment by kurtzeborn** [comment]
We looked at this last week and it's not where we hoped it would be.  Still keeping an eye on it, but there's no clear task/work right now beyond paying attention to these tools progress.
