### ISSUE TITLE
Block PRs with case-insensitive file collisions

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#3109]
A case-insensitive file collision was recently introduced into the .NET repo in https://github.com/Azure/azure-sdk-for-net/pull/27961.  When you clone the repo on Windows or Mac with default settings (case-insensitive file system), you get this warning:
 
```
Updating files: 100% (68668/68668), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:
  'sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Generated/Models/OCIManifest.cs'
  'sdk/containerregistry/Azure.Containers.ContainerRegistry/src/Generated/Models/OciManifest.cs'
```

This has happened a few times now, and it's usually easy to fix once detected, but it can go days until someone reports it.

We should investigate if it's possible to detect this during PR validation and block on failures.  Ideally we could block this at the Git or GitHub level, but I didn't see any settings for this in GitHub, and a Git-level solution might be client-dependent.

**Comment by sima-zhu** [comment]
@mikeharder I think git is able to set to case sensitive by enabling 
```
git config core.ignorecase false
```

Do we allow to have both file `OCIManifest.cs` and `OciManifest.cs`? Or we'd better to just keep one.

**Comment by mikeharder** [comment]
@sima-zhu: I'm not sure what you are asking.  But the goal of this issue is to block PRs which contain files that only differ in case.  So if you submit a PR containing files `foo.txt` and `Foo.txt`, the PR should fail validation.

**Comment by sima-zhu** [comment]
Several things to explore:
1. Can linux turn off case-sensitive feature, like in checkout step?
2. Can git prevent this checkin to remote?
3. Can we use checkout step to validation?
4. Can we add a step to check dups? (Feasible)
