### ISSUE TITLE
OpenAPI Hub diffing tools take too long

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#3110]
When using https://portal.azure-devex-tools.com/tools/diff that I have to nearly every day for diffing changes across different release branches in Azure/azure-rest-api-specs, the diffing takes too long and I have to shift focus away for significant time. Even for a small swagger of ~6 models and no endpoints, it can take 20 minutes or more. Across numerous PRs and multiple files in each, this takes up a significant portion of my day.

I'm using 2 URLs to raw swagger JSON files because I need to diff two separate files (different api-versions) across branches, one of which isn't always main. Using the readme.md from those branches doesn't seem to offer any benefit since I know exactly what files I want to review, and want to see the changes between them separate since, in this case, specification/cognitiveservices/data-plane/Language isn't a true RP and different api-versions may ship different swaggers.

Could the diffing be sped up somehow? I wouldn't expect that building a graph of nodes for endpoints, models, parameters, etc. and diffing them would take 20+ minutes.

**Comment by akning-ms** [comment]
Thanks, @heaths, We know the diff tool has some performance issue sometime due to github api threshold , but 20+min is too long, can you share us the 2 URL you are testing for us triage?

**Comment by heaths** [comment]
Here's a few, but this has been consistent on any swagger-to-swagger diff:

* https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvbWFpbi9zcGVjaWZpY2F0aW9uL2NvZ25pdGl2ZXNlcnZpY2VzL2RhdGEtcGxhbmUvTGFuZ3VhZ2UvcHJldmlldy8yMDIyLTAzLTAxLXByZXZpZXcvYW5hbHl6ZWNvbnZlcnNhdGlvbnMuanNvbiIsInRhcmdldFVybCI6Imh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9BenVyZS9henVyZS1yZXN0LWFwaS1zcGVjcy85OTIwOTlkZmJkNTJmZjVlYzcwMGFjZjg5ZDlmNzhkNzliNjE5OGNlL3NwZWNpZmljYXRpb24vY29nbml0aXZlc2VydmljZXMvZGF0YS1wbGFuZS9MYW5ndWFnZS9wcmV2aWV3LzIwMjItMDUtMDEtcHJldmlldy9hbmFseXplY29udmVyc2F0aW9ucy5qc29uIn0=
* https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvbWFpbi9zcGVjaWZpY2F0aW9uL2NvZ25pdGl2ZXNlcnZpY2VzL2RhdGEtcGxhbmUvTGFuZ3VhZ2UvcHJldmlldy8yMDIyLTAzLTAxLXByZXZpZXcvY29tbW9uLmpzb24iLCJ0YXJnZXRVcmwiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvOTkyMDk5ZGZiZDUyZmY1ZWM3MDBhY2Y4OWQ5Zjc4ZDc5YjYxOThjZS9zcGVjaWZpY2F0aW9uL2NvZ25pdGl2ZXNlcnZpY2VzL2RhdGEtcGxhbmUvTGFuZ3VhZ2UvcHJldmlldy8yMDIyLTA1LTAxLXByZXZpZXcvY29tbW9uLmpzb24ifQ==
* https://portal.azure-devex-tools.com/tools/diff/eyJzb3VyY2VVcmwiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vQXp1cmUvYXp1cmUtcmVzdC1hcGktc3BlY3MvbWFpbi9zcGVjaWZpY2F0aW9uL2NvZ25pdGl2ZXNlcnZpY2VzL2RhdGEtcGxhbmUvTGFuZ3VhZ2UvcHJldmlldy8yMDIyLTAzLTAxLXByZXZpZXcvdGV4dGFuYWx5dGljcy5qc29uIiwidGFyZ2V0VXJsIjoiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL0F6dXJlL2F6dXJlLXJlc3QtYXBpLXNwZWNzLzk5MjA5OWRmYmQ1MmZmNWVjNzAwYWNmODlkOWY3OGQ3OWI2MTk4Y2Uvc3BlY2lmaWNhdGlvbi9jb2duaXRpdmVzZXJ2aWNlcy9kYXRhLXBsYW5lL0xhbmd1YWdlL3ByZXZpZXcvMjAyMi0wNS0wMS1wcmV2aWV3L3RleHRhbmFseXRpY3MuanNvbiJ9

**Comment by honghr** [comment]
It work fine. Please try again. Thanks

**Comment by heaths** [comment]
Even that seems too long. Devs can diff 3GB+ repos in under a second. I get more processing is necessary, but how is this taking minutes as opposed to seconds? I've heard from a few people that they often hit refresh several times before giving up using the tool.

**Comment by akning-ms** [comment]
@jianyexi to try whether there is other space to improve performance in tooling service

**Comment by jianyexi** [comment]
Since it's perf issue about the oad, create an issue https://github.com/Azure/openapi-diff/issues/227 to track
