### ISSUE TITLE
Docwarden has hard coded dependency on file locations in Java repo.

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#312]
A recent change to Docwarden:

https://github.com/Azure/azure-sdk-tools/commit/90793333756e3cc91a44aba4414232ba44655279

Introduced a hard-coded dependency on the location of the client SDK parent POM. As part of some restructuring work we want to move the parent into ```sdk/parents/azure-client-sdk-parent/pom.xml```. We could potentially just fix up this path, but I wonder whether it is a good thing to have hard coded paths specified in code in the ```azure-sdk-tools``` repo which makes assumptions about the structure of another repo.

Additionally, post parent POM restructuring the parent POM won't contain a module listing, which means the logic being used here wouldn't work anyway.

/cc @chidozieononiwu this was a fairly recent change ... is it easy to back out, and if so what are the consequences?

**Comment by chidozieononiwu** [comment]
Am not aware of any other way of determining what packages are client libraries in Java. I can update the path to the parent pom.xml. If there is a better way to determine which libraries are client that will be great.

**Comment by mitchdenny** [comment]
If you scan for all ```pom.xml``` files, any POM file that has a parent of ```azure-client-sdk-parent``` is a track 2 library.

**Comment by chidozieononiwu** [comment]
Fixed in DocWarden 0.4.2
