### ISSUE TITLE
Allow creating new api-versions from existing feature branches

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#3129]
In relation to #2929 and due to the [Azure Breaking Changes Policy](https://aka.ms/AzBreakingChangesPolicy), we recommend that customers use a feature branch (aka release branch) to stage their changes. It is not uncommon, however, to start a new api-version to work on subsequent versions concurrently, but OpenAPI Hub does not let you select a source branch other than "main" despite having a drop-down for it:

![image](https://user-images.githubusercontent.com/1532486/163019741-1a96ff19-31bf-4908-bdf1-9e7293216c46.png)

It would be great if users could select - or at least type in - a different source branch so they can create a subsequent api-version from an existing feature branch.

In the meantime, I've written [a script](https://gist.github.com/heaths/350485ab034f9da2bd10468dfcf2c794) customers can use should they find this issue.

**Comment by akning-ms** [comment]
FYI, @heaths ,  OpenAPI Hub already supported this feature,
You can input specific base branch & "copy from API version "  when you choose  "Customize" base branch option.
Pls have a test and Let us know if any further feedback on this.

**Comment by heaths** [comment]
I see that. Thanks for letting me know. However, even on a large resolution monitor, it's not obvious what the Default and Customize radio buttons do to the page. Could you add a brief description to each e.g.,

* Default - create a copy of the specified version from the main branch
* Customize - create a copy from the specified version from any branch, as well as ...<whatever else Customize allows>

**Comment by akning-ms** [comment]
good suggestion. @raych1 to help

**Comment by raych1** [comment]
Suggestion was taken and was implemented in code. It is in testing phase.

**Comment by raych1** [comment]
@heaths , the change was deployed to production, check it out.
