### ISSUE TITLE
[Python APIView] Type aliases are not rendered in APIView

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#3138]
Example from Service Bus:

```Python
MessageTypes = Union[
    Mapping[str, Any],
    ServiceBusMessage,
    AmqpAnnotatedMessage,
    List[Union[Mapping[str, Any], ServiceBusMessage, AmqpAnnotatedMessage]],
]

def schedule_messages(
    self,
    messages: "MessageTypes",
    schedule_time_utc: datetime.datetime,
    *,
    timeout: Optional[float] = None,
    **kwargs: Any
) -> List[int]
```

APIView will render `MessageTypes`, but there's no type definition to show what that means and it is not linkable. This should probably appear in the APIView like Swift's `typealias`.

**Comment by catalinaperalta** [comment]
Example from Form Recognizer: 

```
from typing import Dict, NewType
TargetAuthorization = NewType('TargetAuthorization', Dict[str, str])
```

**Comment by tjprescott** [comment]
The first syntax cannot be supported. Python sees the type as the RHS of the equals and I cannot access the LHS name. However, with PR #4036, type aliases are supported by using this syntax:
`TargetAuthorization = NewType('TargetAuthorization', Dict[str, str])`
