### ISSUE TITLE
[APIView] Check-boxes to enable deleting multiple API reviews?

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#3159]
Currently, when I want to clean up manual reviews, I have to do the following:

1. Options > Manual
2. Search in the search bar (which can be very slow btw) for the package I'm working on
3. Click the delete button for ONE of the items I want to delete.
4. The entire UI resets and I have to repeat steps 1-3 for every item I want to delete. 

It takes about 30 sec per item (if the search bar is nice to me), which gets frustrating. Instead, could we have checkboxes on the search results so that multiple things could be deleted at once?
![image](https://user-images.githubusercontent.com/5723682/163845144-148e5387-1bd7-4a4c-b9d5-64bdc8069cc2.png)

**Comment by chidozieononiwu** [comment]
This issue should perhaps be tackled after or together with [Enabling Soft Delete](https://github.com/Azure/azure-sdk-tools/issues/6167), since adding multiple check will also increase likelihood of reviews deleted in error.

**Comment by chidozieononiwu** [comment]
Addressed in new Beta UI. Will be added in coming releases
