### ISSUE TITLE
[Test-Proxy] Custom matcher for body keys only

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-tools#3171]
Key Vault tests currently use a custom [json_attribute_matcher](https://github.com/Azure/azure-sdk-for-python/blob/c8291ac6cb0dbd865da03a88dd2bcb9279e2c4a6/sdk/keyvault/azure-keyvault-certificates/tests/_shared/json_attribute_matcher.py) with `vcrpy` as a custom request matcher. This checks that the keys in request bodies match, without enforcing an ordering and without comparing body values.

It would be great if we could support this kind of matching with the test proxy, as it probably would have uses outside of KV for tests that have consistently-structured bodies with possibly (expectedly) inconsistent values.

@scbedd

**Comment by scbedd** [comment]
@pshao25 has just requested this in general for `application/json`.

Frankly I think it's probably a reasonable request. I don't think that it would have negative impact to the existing tests. If anything this lowers the restriction on matching.
