### ISSUE TITLE
[ci] Occasional issues using RBAC creds with Service Bus

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#3172]
On occasion I will get an error in the azservicebus pipeline where it appears that permissions haven't been setup on the resource:

[azdev link](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/1516821/logs/169)

```log
022-04-20T01:11:48.9699161Z         	Error Trace:	client_test.go:61
2022-04-20T01:11:48.9700708Z         	Error:      	Received unexpected error:
2022-04-20T01:11:48.9704226Z         	            	*Error{Condition: amqp:unauthorized-access, Description: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://***/queue-16e77580ad4b5631'. TrackingId:<ignore tracking id>, SystemTracker:gateway7, Timestamp:2022-04-20T01:09:45, Info: map[]}
```

Re-running that failed leg works every time so it does appear to be timing dependent. It's also not _every_ time I run the pipeline, and it usually only fails one of the platforms, not every one. So if it's an issue with the test-resources then it's something that's not obvious at all.

I'm not entirely blocked by this, but wanted to raise a warning flag in case this represents something systemic that needs to be addressed.

**Comment by benbp** [comment]
I've seen this for event hub before with @mikeharder. One way to fix it is having a subscription level RBAC for our test principal (though not ideal). I'm wondering if RBAC propagation delays are sometimes happening when they are provisioned at the resource group level.

**Comment by richardpark-msft** [comment]
Some positives/negatives @benbp and I discussed offline:

- Globally set RBAC might solve this issue, which we think might just be timing/propagation delays. But it would also cover up for potential issues in our bicep/arm templates if they were incorrectly configuring permissions. This isn't a huge deal, but just something to be aware of.
- Having more globally configured stuff can make recreating the subscription more involved and would need to be considered.

For the particular tests that were failing, since all the identity info is just injected via environment, it would be fine. There might be other use cases, but we can solve this particular one for me (and probably others that are attempting to do the same type of tests).

**Comment by jsquire** [comment]
I'm wondering if RBAC propagation delays are sometimes happening when they are provisioned at the resource group level.

I believe so, in the .NET messaging libraries, we worked around this by introducing an artificial delay to allow for propagation via the "post" test resources script.   [Example](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/test-resources-post.ps1)

**Comment by benbp** [comment]
I could also see doing some trivial operations in a before loop and retrying to check RBAC, that way you don't have to wait 60 seconds in the happy path cases.

**Comment by richardpark-msft** [comment]
Another option is to shift the deployment of resources earlier then let the normal build steps cover for the propagation interval.

Maybe that already happens though.

**Comment by kurtzeborn** [comment]
Pretty sure we've got this sorted out now.  If anyone sees this still happening, please re-open and provide a pointer/details to what you're seeing.

**Comment by benbp** [comment]
I'm not seeing any recent hits of this:

[query](https://dataexplorer.azure.com/clusters/azsdkengsys.westus2/databases/Pipelines?query=H4sIAAAAAAAAA3WPwQqCQBCG7z3FtCcFQ8NTgR2ki2C3XmB0Jx1wZ83dJYoePiWwU9f5v4//nzLwoGvb1Sy0ecOjp4ngyoacRzPCCbCzUZ7peA3LxTjTjYU9W6k0FAWoPDtkamUu5Bx2BK0VjywOFJr7eAyCwfd24hfpHbbtTClA0Su//QmpWJnIT4zNQOlffa50wRhcjnNdEB/F0DyhYYnWNxLY6zj5Lq/0B+eqLXTzAAAA)

```
BuildLogLine
| where Timestamp > ago(30d)
| where BuildDefinitionId == "3090"
| where Message contains "amqp:unauthorized-access" and Message !contains "/nonretriable/amqp:unauthorized-access"
| summarize count() by bin(Timestamp, 1d), BuildId
```
