### ISSUE TITLE
Sparse checkout should handle private repos

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#3222]

**Comment by benbp** [comment]
I couldn't get the PAT formatting syntax right at the time based on what devops gave the task, but I believe there are some promising examples here: https://github.com/MicrosoftDocs/azure-devops-docs/issues/2455

**Comment by weshaggard** [comment]
There is also persistCredentials option for an explicit checkout https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines that we might be able to use to get the correct credentials setup.

**Comment by JimSuplizio** [comment]
@danieljurek, @benbp and I chatted and we're closing this one out. It's been almost 2 1/2 years, and this clearly isn't going to get fixed.

**Comment by weshaggard** [comment]
I'm fine closing this but we may need to solve this for other reasons in the future.
