### ISSUE TITLE
Docker Image Static Analysis

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#3244]
Talking with @benbp and we know we will have some effort coming here.

- [ ] Identify out of date `FROM` statements
- [ ] How do we ensure that non-tag related dependencies are updated?
- [ ] How can we ensure that CVEs filed against docker images are automatically routed to the appropriate owner?

**Comment by danieljurek** [comment]
Was this intended to apply to our internal ACR instance? Dockerfiles in our repos? Usage of containers in our EngSys? Or some other scope?

**Comment by scbedd** [comment]
Closing as 1ES does this for us.
