### ISSUE TITLE
[check enforcer] Investigate using status api instead of check_run api

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#3245]
Right now check enforcer has to handle every check_run event for a PR and check if all other check_run events are finished. It would be much easier to listen for a [check_suite](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#check_suite) completed event before posting back a final status. Right now this can't work because check enforcer is a check_run, meaning the check_suite only completes when check enforcer completes.

You can also configure a [commit status](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#status) via the status API, and set a branch protection policy on that status being `success`. If check enforcer used the status API, then we could stop handling check_run events in favor of a singular check_suite event, and use the status API as the final gate for the PR. You can post a `pending` status to keep the PR from being mergeable at the start.

**Comment by kurtzeborn** [comment]
Closing because you did this @benbp!
