### ISSUE TITLE
[stress] The current resource naming scheme uses too many characters

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#3263]
Currently the resource names get a combination of the Kubernetes namespace I choose, the scenario name and the Chart name. This eats up a lot of character space, which means I was getting failed deployments for service bus since our generated name is too long.

I'd suggest not combining all of that information and instead coming up with a fixed length ID (timestamp in seconds - hexed, etc..) and using that instead.

I've shortened one of my deployments so it'd fit, but here's an example of the namespace name today. Normally I'd rather use a much longer namespace name (that's descriptive and that contains my actual username). 

```
rpus-constantdetach-gosb-1.servicebus.windows.net
# Kubernetes ns: rpus
# Scenario name: constantdetach
# Helm chart name: gosb
```

**Comment by benbp** [comment]
@richardpark-msft what about something like a short name hash function in the template? That way you could still use readable names for the cluster resources, but the resource group name could be shortened/generated (similar to [uniqueString](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-string#uniquestring) in bicep). This would probably just be internal and from the template perspective it would still be `{{ .Stress.ResourceGroupName }}`.

**Comment by richardpark-msft** [comment]
That sounds perfect to me.

**Comment by richardpark-msft** [comment]
@swathipil just ran into this as well. I think we should just go purely with the hash function name, and not include the chart or anything else.
