### ISSUE TITLE
Automation on service level readme

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#3278]
Docs.Ms is ready to move to service level readme automation.

Problem:
Docs.Ms has ability to automate package level readme, but we currently require people to manually update the service level readme.
The service level readme they initially push to docs repo has package version information on it. So whenever we update the package version, the service readme info is out of date.

Proposals:
We generate the service level readme nightly in docindex as the service level readme currently linked from automation toc. 
Inside of the readme, we will have the metadata infomation, client packages table and mgmt packages table.

To avoid introduce too many logic, we decided to have general information on table instead of versioned docs.

**Comment by sima-zhu** [comment]
New proposals according to @weshaggard  suggestion.

1. Check whether the {service-name}.md exist.

>  If yes, go to the file and update `author`, `ms.author` and `ms.service`

> If no, go to step 2

2. Create two markdowns `{service-name}.md` and `{service-name}-index.md`.
> For `{service-name}-index.md`, generate the client package table and mgmt package table.

> For `{service-name}.md`, generate the metadata and table includes the content of `{service-name}-index.md`

**Comment by sima-zhu** [comment]
Will have a report on:
1. Existing service readmes which will not update through the scripts. Have a follow up issue to address them as to most recent format.

**Comment by weshaggard** [comment]
As a slight update to the proposal which is we should always generate `{service-name}-index.md` for existing or non-existing services. Those should always be generated for everyone. For new ones we will automatically include those but for the existing ones we will need to work with the service teams to add the include in those.

**Comment by sima-zhu** [comment]
On how to generate markdown table.

1. Filtered out package by "New" to true
For attribute of reference, if no readme
1. We can level the attribute blank.
2. Generate a package level readme which lists the children items.
