### ISSUE TITLE
Disable Avocado MISSING_APIS_IN_DEFAULT_TAG check on data plane APIs

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3285]
There is no clear explanation of this requirement nor recommendations for how to fix for data plane, so until these are in place we need to disable this rule for data plane APIs.

Example: https://github.com/Azure/azure-rest-api-specs/pull/18372/checks?check_run_id=6315603156

ref: https://github.com/Azure/azure-sdk-tools/issues/2856#issuecomment-1113546950

**Comment by ruowan** [comment]
We have made this change on prod pipeline. Close this issues.
