### ISSUE TITLE
Policheck PR check in azure-rest-api-specs is failing on custom-words.txt "whitelist"

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3300]
The Policheck PR check in azure-rest-api-specs is failing because there are words containing "whitelist" in the custom-words.txt file.

The words being flagged are already merged to main:

https://github.com/Azure/azure-rest-api-specs/blob/main/custom-words.txt#L2390

but Polichek flags them in the [PR checks for PR #18372](https://github.com/Azure/azure-rest-api-specs/pull/18372/checks).

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/85643503/167435183-8844be30-a851-4ea5-b204-1264531b029b.png">

**Comment by raych1** [comment]
Suppression mechanism is added and this work will be added to the suppression list. The change is pending to be released.
//CC: @tianxchen-ms

**Comment by raych1** [comment]
@mikekistler, new version of policheck tool was released to PROD pipeline and some terms were added to suppression list.
