### ISSUE TITLE
【Mock-Service-Host】  Unable to authenticate due to incorrect tenant ID format.

### ISSUE THREAD

**Issue by yuichiromukaiyama** [Azure/azure-sdk-tools#3313]
I would like to use "@azure-tools/mock-service-host" to develop an application locally using Azure SDK for Go.
Perform the following steps and MockServer is up and running. The command line shows the following at the end.
[https://github.com/Azure/azure-sdk-tools/tree/main/tools/mock-service-host](https://github.com/Azure/azure-sdk-tools/tree/main/tools/mock-service-host)

```
~~~ omission ~~~
{
  level: '\x1B[33mwarn\x1B[39m',
  message: 'Unable to find provider for path : "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/validateMoveResources". Bucketizing into provider: "microsoft.unknown"'
}
2022-05-11T09:44:16.953Z [info]: validator initialized
```

Once I decided to check the connection with Azure Cli for verification, I proceeded with the following steps.
[https://github.com/Azure/azure-sdk-tools/blob/main/tools/mock-service-host/doc/consume_with_cli.md](https://github.com/Azure/azure-sdk-tools/blob/main/tools/mock-service-host/doc/consume_with_cli.md)

However, you will be asked to authenticate after performing the following steps

```
az login // open browser and login. --> success auth
az cloud register -n virtualCloud
                    --endpoint-resource-manager "https://localhost:8443"               
                    --endpoint-active-directory https://login.microsoftonline.com
                    --endpoint-active-directory-graph-resource-id https://graph.windows.net/
                    --endpoint-active-directory-resource-id https://management.core.windows.net/
az cloud set -n virtualCloud // Successfully switch
az group create -n sample -l westus // It will show that you need to log in.
```

Error Message
```
PS C:\Users\**** > az group create -n sample -l westus
?[91mPlease run 'az login' to setup account.?[0m
```

If I try to authenticate in this state, I get the following error

```
PS C:\Users\*** > az login
?[93mA web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.?[0m
D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\urllib3/connection.py:460: SubjectAltNameWarning: Certificate for localhost has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/urllib3/urllib3/issues/497 for details.)
?[91mThe command failed with an unexpected error. Here is the traceback:?[0m
?[91mUnable to get authority configuration for https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.
Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 100, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 169, in tenant_discovery
ValueError: OIDC Discovery endpoint rejects our request. Error: {"error":"invalid_tenant","error_description":"AADSTS900021: Requested tenant identifier '00000000-0000-0000-0000-000000000000' is not valid. Tenant identifiers may not be an empty GUID.\r\nTrace ID: 160e8633-661e-45f5-9381-b2fe91f18100\r\nCorrelation ID: f4e461a2-ad6b-4983-83c1-a8baaafc8d5c\r\nTimestamp: 2022-05-11 10:16:48Z","error_codes":[900021],"timestamp":"2022-05-11 10:16:48Z","trace_id":"160e8633-661e-45f5-9381-b2fe91f18100","correlation_id":"f4e461a2-ad6b-4983-83c1-a8baaafc8d5c"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 231, in invoke
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 658, in execute
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 721, in _run_jobs_serially
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 692, in _run_job
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 328, in __call__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/profile/custom.py", line 139, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 177, in login
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/_profile.py", line 746, in find_using_common_tenant
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/identity.py", line 203, in get_user_credential
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/auth/msal_authentication.py", line
39, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 1485, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/application.py", line 455, in __init__
  File "D:\a\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\msal/authority.py", line 104, in __init__
ValueError: Unable to get authority configuration for https://login.microsoftonline.com/00000000-0000-0000-0000-000000000000. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant Also please double check your tenant name or GUID is correct.?[0m
To open an issue, please run: 'az feedback'
```

Is there any way to bypass authentication? 
Thank you.

**Comment by changlong-liu** [comment]
Hi @yuichiromukaiyama , thanks for the finding.
Would you mind to set your real tenantId in two lines here in your local machine and restart the mock-service-host, then the 'az login' should use your real tenant to login: https://github.com/Azure/azure-sdk-tools/blob/main/tools/mock-service-host/src/mid/specials.ts#L1128-L1129

I may open PR to make it configurable.

**Comment by raych1** [comment]
@yuichiromukaiyama , does the solution changlong provided resolve your issue? 

@changlong-liu , would you like to create an issue or work item in your backlog?

**Comment by yuichiromukaiyama** [comment]
@changlong-liu Sorry for the late reply.
I have checked the part you wrote.

`node_modules/@azure-tools/mock-service-host/dist/src/mid/specials.js`

The location already contained the value as you specified.
↓

```
exports.get_tenants = {
    value: [
        {
            id: '/tenants/00000000-0000-0000-0000-000000000000',
            tenantId: '00000000-0000-0000-0000-000000000000',
            countryCode: 'US',
            displayName: 'Microsoft',
```

Therefore, the following flow was performed again

1. `npm init -y`
2. `npm i @azure-tools/mock-service-host`
3. `node node_modules/@azure-tools/mock-service-host/dist/src/main.js`
→ Confirm that `[info]: validator initialized` is displayed 
4. `az login`
→ I logged in on the browser side and authenticated
5. `az cloud register -n virtualCloud --endpoint-resource-manager "https://localhost:8443" --endpoint-active-directory https://login.microsoftonline.com/ --endpoint-active-directory-graph-resource-id https://graph.windows.net/ --endpoint-active-directory-resource-id https://management.core.windows.net/`
6. `az cloud set -n virtualCloud`
→ switch success

---
In this state, I ran the following

```
az group create -n sample -l westus
```

You will then be asked to log in and an error will occur

```
Please run 'az login' to setup account.
```

Am I doing something wrong with the procedure?

**Comment by changlong-liu** [comment]
Hi @yuichiromukaiyama , do you have a real azure account?

Currently it's required to login with your real azure account. 
And need to set you real tenant at https://github.com/Azure/azure-sdk-tools/blob/main/tools/mock-service-host/src/mid/specials.ts#L1128-L1129 (don't use 00000000-0000-0000-0000-000000000000, replace it with your real azure tenant)

**Comment by yuichiromukaiyama** [comment]
Sorry. I was mistaken.
I was using 00000000-0000-0000-0000-0000-0000000000000000 as it is. I added my subscription here and it worked.

**Comment by changlong-liu** [comment]
> @yuichiromukaiyama , does the solution changlong provided resolve your issue?
> 
> @changlong-liu , would you like to create an issue or work item in your backlog?

Hi @raych1 , working issue created here https://github.com/Azure/azure-sdk-tools/issues/3520 , and closing this one.
