### ISSUE TITLE
Set up proxies to be used by tests to ensure client libraries can connect through...proxies...

### ISSUE THREAD

**Issue by johanste** [Azure/azure-sdk-tools#3326]
Azure/azure-sdk#175 tracks the requirement for client libraries to be able to connect through proxies. Just as it is a common requirement to support it, it is also a common requirement to verify said support. Having proxies that are set up to use auth (digest and basic) would presumably be needed for this.

**Comment by scbedd** [comment]
Closing, this is client side.
