### ISSUE TITLE
Autorest SDK generation is failing

### ISSUE THREAD

**Issue by shrja-ms** [Azure/azure-sdk-tools#3350]
Need assistance in https://github.com/Azure/azure-rest-api-specs-pr/pull/7113 Azure SDK generation issues for C# and GOLang.
- Still an issue.

Also, Prettier is not working on local, Need reference of any online tool if available to fix issues. - This was fixed.

**Comment by shrja-ms** [comment]
Can someone from SDK Tool side please look into this?

**Comment by shrja-ms** [comment]
Hi @weshaggard Can you please assign this issue to someone to look into. TIA.

**Comment by weshaggard** [comment]
@akning-ms can you please rout this issue?

**Comment by akning-ms** [comment]
Looks GO is not ready as Dapeng commented in PR.
.Net code generation is going to deprecate in PR pipeline. @dw511214992  to confirm

**Comment by akning-ms** [comment]
For Prettier check, can you try to add parameter  "--print-width 1" to try again? if still not working, may need you provide more like cmdline and error message for your local run @shrja-ms

**Comment by dw511214992** [comment]
I have change `azure-sdk-for-net` to `azure-sdk-for-net-track2` because `azure-sdk-for-net` is deprecated.

**Comment by shrja-ms** [comment]
@akning-ms Prettier check has passed now.

**Comment by dw511214992** [comment]
I have fixed the sdk automation pipeline failure.
