### ISSUE TITLE
[stress testing] Create bash and pwsh exportable env files

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#3352]
Currently we only generate a dotenv format env file with all the relevant stress secrets. In some cases, it would be useful for higher level scripts to have access to these variables (e.g. loading the app insights java agent). For example, a `/mnt/outputs/.bashenv` file that has `export` statements.

**Comment by kurtzeborn** [comment]
Closing.  @benbp says it's not worth the complexity. :)
