### ISSUE TITLE
[stress testing] Design more fine grained chaos resource targeting

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#3353]
Currently there are two ways to define chaos resources, either via hardcoded/static targets, or by defining a single resource through our addons templates, which will be looped over via `.Values.Scenarios`. In cases where multiple scenario tests are being run, but only a subset of those tests should have chaos applied to them, we need a better way to define and link these resources together.

**Comment by kurtzeborn** [comment]
Already have other issues tracking this (example #3281)
