### ISSUE TITLE
Check and cleanup codeowner files in spec repo.

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-sdk-tools#3374]
Github codeowener file has report many existing issue, we should scan codeowner file and clean up legacy codeowners.

**Comment by raych1** [comment]
Assigned to liurunliang.

**Comment by raych1** [comment]
Added the PR link.
https://github.com/Azure/azure-rest-api-specs/pull/19329

**Comment by raych1** [comment]
This work is done.
