### ISSUE TITLE
Power Automation flow for SDK generation pipeline(get pipeline result from dataverse)

### ISSUE THREAD

**Issue by zzvswxy** [Azure/azure-sdk-tools#3393]
get pipeline result from codegen table and result table

**Comment by weshaggard** [comment]
@zzvswxy Can you help me understand this a little more? Can we not get the pipeline result from the pipeline itself?

**Comment by zzvswxy** [comment]
for SDK generation pipeline, we have to status: 1 task result(codegen task failed or succeed) 2 pipeline status(queued, in_progress, completed). But for service team (the codegen power apps user), what are they cared is if the task is in progress or completed(both succeed or failed). I will combine task result and pipeline status in pipeline final event. And the power apps will consume the event and display in the result table.

**Comment by weshaggard** [comment]
I think my question is where are you planning to write that status? We should just query the DevOPs pipeline to get that status?

**Comment by zzvswxy** [comment]
Currently I put it in eventhubs.  Because there are a lot of things need to send to power apps, so I put  it all in the event.

**Comment by weshaggard** [comment]
OK so the only thing we publish to the eventhub is the success status whenever the pipeline is finished? If that is the case how does someone know the pipeline is in progress? Eventhub is generally for eventing and not useful for querying status. The status can be queried directly from the pipeline whenever it is needed.

**Comment by zzvswxy** [comment]
at the begin of the pipeline, when finished 'Setup Pipeline Runtime Environment', it send queued event. For example:
 {"status":"queued","trigger":{"name":"release-workflow"},"pipelineBuildId":"16xxx"}.
before run task engine docker to generate sdk, it send in progress event. For example:
{"status":"in_progress","trigger":{"name":"release-workflow"},"pipelineBuildId":"16xxx"}.
when pipeline artifact has published, it send completed event. For example:
{"status":"completed","trigger":{"name":"release-workflow"},"pipelineBuildId":"16xxx","logPath":"xxxxx.com","result":{"name":"total","pipelineBuildId":"16xxx","result":"succeeded","errorCount":0,"messages":[]}}.
All event will be consumed by power automation and saved in dataverse.
Power apps will load pipeline result from dataverse.

**Comment by weshaggard** [comment]
Do we expect to have active listeners? If not then I'm still not sure this is needed. @chunyu3 do you know who will be pulling those events from the hub? Could they instead pull the status from the pipeline?

**Comment by chunyu3** [comment]
Hi @weshaggard Our sdk pipeline will be used in power app release workflow and the unified pipeline(swagger PR CI). We use the event to inform the pipeline trigger (the unified pipeline or app release workflow) the result and status in asynchronous way. The trigger does not need to query from pipeline every time.

The unified pipeline will consume those events from eventhub to update the status/result in the github PR. And it will not convenient for them to query out the data from pipeline and render and update the data to github check. Also they don't know exactly which pipeline build is the last one for this PR and also they don't know if the github check store the result of the latest pipeline, so even they can record down the latest pipeline build id, it always need to retrieve the data from pipeline every time and update the github check. So eventhub is the suitable way for them to handle this.

**Comment by weshaggard** [comment]
Today the unified pipeline (swagger PR CI) is using an eventhub but I don't think it is the best way to accomplish this. If you remember I was hoping to move away from that eventually and let github and DevOps talk to each other natively as that is how we do pipelines for every other github repo. We hook-up the pipeline to the repo and the pipeline will trigger automatically when a PR is created without the need for a lot of extra stuff in the middle like the Eventhub and bot. I realize until we can get that work cleaned up the Eventhub might be helpful for that scenario but we should not take a dependency on that for the PowerApps workflow given we plan to eliminate it. 

For PowerApp I think we should directly query DevOps for now. I will also add that eventually I think the PowerApp will not directly trigger the devops pipeline but instead will trigger a specs PR which will then trigger the pipeline and so we might need to work through the specs PR to get the information we want to display in the powerApp.

**Comment by chunyu3** [comment]
Hi @weshaggard I remember that you are planning to remove away all the external resource such as eventhub from unified pipeline (swagger PR CI). and I afraid eventhub may not be able to remove for the reasons I mentioned before.  So our sdk generation pipeline still need to send event.
For PowerApp, it has limitation now to retrieve the data from DevOps. If we store all the result as an artifact file in DevOps, and DevOps only provide an rest api to download the file, but PowerApp has no way to store the file and read the file data. As a result, powerApp cannot support this scenario. 

At last, I know you want to combine release with swagger PR CI into one pipeline. It works and can save resources. Only one thing may not be good is that we couple the release with PR.

**Comment by weshaggard** [comment]
>For PowerApp, it has limitation now to retrieve the data from DevOps. If we store all the result as an artifact file in DevOps, and DevOps only provide an rest api to download the file, but PowerApp has no way to store the file and read the file data. As a result, powerApp cannot support this scenario.

No matter which solution we take the PowerApp is likely going to need to store/cache some data (not necessarily files but data from the files) somewhere into the DataVerse behind the PowerApp. I don't think pulling that from the DevOps pipeline artifact or from the EventHub changes that. In which case I would like to just pull that directly from the DevOps pipeline artifacts. 

cc @raych1

**Comment by raych1** [comment]
Discussed with @chunyu3 , we might leverage openapi hub backend service to download artifacts from pipeline result then the run result can be extracted for PowerApp to use.

**Comment by weshaggard** [comment]
Why would we need do that? The PowerApp can have some integration code that will be able to process the result from the pipeline. At worst it should be simple script that we run in the PowerApp to process the pipeline. We shouldn't have another service to keep up and running to process this.

**Comment by zzvswxy** [comment]
Use Azure pipeline rest api to get status and task result in artifact, instead of eventhub. Wes thanks for your help, I really appreciate it.
