### ISSUE TITLE
[FEATURE] Can we get two independent scroll bars?

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#3410]
If you are viewing a large library like [network ](https://apiview.dev/Assemblies/Review/0a05fdc440214556bf53f021aa31e0cd#Azure.ResourceManager.Network.FlowLogResource)having a single scroll bar control both the class list pane and the details pane makes it difficult to keep track of where you are.

As you can see in the link I pasted above you are barely 20% through the details pane but it forces you to scroll all the way to the bottom of the class pane.  If I wanted to click on the [FlowLogCollection](https://apiview.dev/Assemblies/Review/0a05fdc440214556bf53f021aa31e0cd#Azure.ResourceManager.Network.FlowLogCollection) class from the class pane which is 2 items above the original link of [FlowLogResource](https://apiview.dev/Assemblies/Review/0a05fdc440214556bf53f021aa31e0cd#Azure.ResourceManager.Network.FlowLogResource) I have to scroll all the way back to the top of the page losing my place in the details pane just so I can see the options in the class pane that are higher up the list.

**Comment by chidozieononiwu** [comment]
Resolved
