### ISSUE TITLE
[FEATURE] Can we get a tooltip over the Approved button?

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#3416]
When we mouse over the Approved button it would be nice to see a tooltip of who approved the API.

**Comment by chidozieononiwu** [comment]
There already exists a popover. You do need to click on it to see it though.
![Screenshot (1)](https://user-images.githubusercontent.com/31145988/178057329-98cc9418-c191-4eff-9b19-8d66ff2c8866.png)
