### ISSUE TITLE
Integrate Java DPG in sdk automation pipeline

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-tools#3421]
doc: https://github.com/Azure/azure-rest-api-specs/tree/dpg-doc/documentation/onboard-dpg-in-sdkautomation

**Comment by weidongxu-microsoft** [comment]
existing package https://github.com/openapi-env-test/azure-rest-api-specs/pull/3144
new package https://github.com/openapi-env-test/azure-rest-api-specs/pull/3152

merge is TBD (when someone really needs it)
