### ISSUE TITLE
Docs.Ms automation

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#3429]
- [x] Toc automation
- [x] Service level readme
- [x] main to live merge
- [ ] metadata on APIs

**Comment by sima-zhu** [comment]
- [ ] Toc automation
https://github.com/Azure/azure-sdk-tools/pull/3428

**Comment by sima-zhu** [comment]
- [ ] Service level readme
https://github.com/Azure/azure-sdk-tools/pull/3267

**Comment by kurtzeborn** [comment]
@danieljurek, I'm pretty sure all that's left here is "metadata on Apis"

**Comment by danieljurek** [comment]
"metadata on APIs" is part of https://github.com/Azure/azure-sdk-tools/issues/1442 

This should be closed as relevant work is finished and automating metadata production should be tracked in a separate task.
