### ISSUE TITLE
Policheck errors are not shown in PR pipeline

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3431]
Errors issued by Policheck are not correctly reported in the PR pipeline.  The check is marked as "failed" but the PR pipeline status says "PoliCheck: 0 Errors, 0 Warnings".  The errors are visible in the "Swagger Pipeline".

Example from PR 19316

![image](https://user-images.githubusercontent.com/85643503/173366409-cf22e97d-321d-4bef-8c7e-3a99f2df070e.png)

![image](https://user-images.githubusercontent.com/85643503/173366631-1e8e3153-bfdb-4990-84af-0e6b5b135a35.png)

**Comment by raych1** [comment]
@mikekistler , this was improved by displaying a message to prompt to look into details in the pipeline result. A few changes are pending to be released.

**Comment by raych1** [comment]
@mikekistler , the new version was released to prod pipeline, please have a try.
