### ISSUE TITLE
Create automation to replace "chooser" template with correct PR template in azure-rest-api-specs

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3440]
We'd like to introduce a "chooser" PR template to prompt the user to pick either a data plane or control plane PR template.  But in the first attempt we found many users simply accepted the template without following the directions.

So we want automation that looks for PRs whose description is the "chooser" template and replaces that with the appropriate PR template based on the files included in the PR.  When that is in place we can go back to using the "chooser" template.

**Comment by raych1** [comment]
Created [work item](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1555382) to track this request.\
//CC: @ruowan

**Comment by raych1** [comment]
@mikekistler , you can proceed to check in template change. @ruowan already deployed the bot change to support first comment update if user doesn't choose template.

**Comment by mikekistler** [comment]
Automation has been deployed so this issue is resolved.
