### ISSUE TITLE
Code pane needs horizontal scrollbar

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#3452]
During an archboard review, I was often not able to (easily - my mouse does have a way to get a cursor but may not be intuitive to everyone) scroll horizontally on some of our longer method names. E.g.:

<img width="779" alt="image" src="https://user-images.githubusercontent.com/1532486/173964070-964dd238-8f98-443a-89d6-200914c668d6.png">

This makes reviews difficult. It would be great if a horizontal scrollbar was added as needed.

**Comment by JonathanGiles** [comment]
@heaths With a mouse that has a scroll wheel (which, I'm guessing, is almost all of them these days??) if you press and hold the scroll wheel down, and then move your mouse to the left or right of where your original click occurred, you should see horizontal scrolling occur. Does this work for you (it does for me)?

**Comment by heaths** [comment]
It does. I mentioned I did that, but not sure everyone would know about that. If we want everyone using this, having an intuitive and familiar UI may be a better user experience overall.

**Comment by cmcd22** [comment]
@JonathanGiles I'll take this one

**Comment by JonathanGiles** [comment]
@heaths If you have a moment, can you try installing a browser extension such as "[Super Styles](https://microsoftedge.microsoft.com/addons/detail/super-styles/lgcjpmgldoadgddlhigdadahfdecchcp)", so that you may make local modifications to websites. If you do, please go to the APIView website and apply the following CSS in the extension:

```css
#review-right {
  overflow-x: visible !important; 
}
```

The end result is an always-visible horizontal scrollbar, but I would argue that the usability is less than what we have today (so long as you know about the mouse wheel click trick to enable horizontal scrolling). Keen to hear your thoughts.

**Comment by JonathanGiles** [comment]
I saw a mockup of this by @cmcd22 yesterday that looked like this:

![image](https://user-images.githubusercontent.com/1427840/189765169-2a22acde-8735-4dbc-a8f6-54ee23b962d8.png)

The problem with this image is that the API viewport becomes exceedingly small.

I still tend to prefer the suggestion that people horizontal scroll with their 'only up/down' mouse wheel by pressing the mousewheel down and moving the mouse horizontally. I wonder which mouse wheels do not support horizontal scroll (I would have assumed it was an operating system feature, rather than a hardware-specific feature)

**Comment by heaths** [comment]
The padding in that image definitely makes it works. I wouldn't add the padding and then it doesn't look so bad.

Not all mice support a middle click, though maybe in time that is solving itself.

**Comment by cmcd22** [comment]
@praveenkuttappan @chidozieononiwu are you please able to give your expert opinions on the approach taken in the screenshot above and if you believe this will aid usability? Cheers

**Comment by heaths** [comment]
FWIW, I'd get rid of the effective padding, though. Keep everything like it is, but make the divs scrollable. I came close to a mock-up using F12 dev tools but you have to use a fixed (or calculated, which is where my CSS 1.1 skills fail me) height/width for whichever axis you're trying to scroll.

**Comment by chidozieononiwu** [comment]
Am not clear what is the ask here. It seems that this is already present either using the mouse wheel or the scroll bar itself.

**Comment by heaths** [comment]
> Am not clear what is the ask here. It seems that this is already present either using the mouse wheel or the scroll bar itself.

Not all mouse wheels move horizontally, and there's no horizontal scrollbar.

What I'd like to see is vertical and horizontal scrollbars - as needed - for both the TOC and content.

**Comment by chidozieononiwu** [comment]
Perhaps it's a browser compatibility issue. What web browser are you using. I ask because I see horizontal scroll bar in the main content in (Edge, Chrome and Mozilla). As for the table of Content a scroll is also present although not deployed yet. But it is fixed in staging right now.

**Comment by heaths** [comment]
I'm using Edge Dev and see no horizontal scrollbar:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/1532486/192370258-c5f819ea-cc5b-45bb-8385-0de07a2372e4.png">

**Comment by maririos** [comment]
@chidozieononiwu I know we went back and forth with this feature. What was the conclusion? and what is the state today?

**Comment by chidozieononiwu** [comment]
The horizontal scroll is present even in Edge Dev. 
![Scroll](https://user-images.githubusercontent.com/31145988/196320117-89e8e438-d065-4285-828f-4f285dbd8b5d.png)

**Comment by heaths** [comment]
Only if you scroll the main content down, though. It seems someone did already change the content regions: TOC has no scroll on overflow, but probably fine since it's typically long enough to see enough of a type; and th emain content *does* have a horizontal scrollbar but not properly taking into account the height above it seems. Here's me before scrolling the main content region (and doesn't matter if I maximize on a 2K resolution:

![image](https://user-images.githubusercontent.com/1532486/196502000-6ee446a1-a060-4e93-9c19-f462071eb481.png)

But now if I scroll the main content down, but losing all the useful toolbar features at the top:

![image](https://user-images.githubusercontent.com/1532486/196502208-7909f26a-f2f0-40d2-8ca3-d0b75111b3f7.png)

It seems the height of the page about the main content area wasn't taken into account. Perhaps the height should be a CSS calculation.

Using Edge Dev version 107.0.1418.8 (Official build) dev (64-bit).

**Comment by maririos** [comment]
@chidozieononiwu the ask here is to make sure the horizatonal scroll bar is always available, not only if the user scrolls down

**Comment by chidozieononiwu** [comment]
Do you want the toolbars and scrollbars to be always visible? that will require calculating the space to allocate for the content based on user screen size. That is possible but I suspect as someone else will complain about the space that will be eaten up by the toolbars and footer. I think the best thing here is to scroll with the mouse wheel which I think is the best experience.

**Comment by maririos** [comment]
Ohh right. I was one of those users complaining about all the space losted because of the scroll bars :|

**Comment by heaths** [comment]
The scrollbars themselves don't take much. In email discussions when the UI that we sort of have now, there's a lot of whitespace on the sides and bottom we don't need. Get rid of that, and the loss of space is none to negligible (none if the scrollbars aren't necessary). If the scrollbars aren't visible, there's no point in having them and it's probably just better off as it was.

If you know the height of the top and nix the bottom whitespace (like it was before), you can use `height: calc(100% - {header height})`.

**Comment by chidozieononiwu** [comment]
Resolve in https://github.com/Azure/azure-sdk-tools/pull/5385
