### ISSUE TITLE
Support more Java-specific APIView 'TypeKinds'

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-tools#3463]
It would be nice to have support for additional TypeKinds in APIView that relate to Java. I would like the following: 

* ANNOTATION
* JAVA_MODULE
* MAVEN
* GRADLE

This requires changes to the Java APIView tooling to include these as appropriate, as well as the APIViewWeb tooling to make appropriate use of these type kinds (most notably, to have more unique icons in the left navigation bar).

**Comment by JonathanGiles** [comment]
My estimation for the changes required here is:

* Add new TypeKind enum values into the Java [TypeKind](https://github.com/Azure/azure-sdk-tools/blob/main/src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/TypeKind.java) enum.
* Because the navigation simply appends the [type kind as a CSS style class](https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/APIView/APIViewWeb/Pages/Shared/Navigation.cshtml#L11), we need to update the [site.scss file](https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/APIView/APIViewWeb/Client/css/site.scss#L463) to include additional `.icon-*` selectors.
* We need to select appropriate images for these, and include them in the /wwwroot/icons directory.

This work may align with issue #3464, as these will be Java-specific, it makes sense for this CSS to be part of a java-specific CSS file perhaps.

**Comment by Baas-hub** [comment]
I'll pick up this issue now @JonathanGiles. Do you have icon files you'd like to be used, or should I source some?

**Comment by JonathanGiles** [comment]
I'll get you the icons
