### ISSUE TITLE
Support language-specific CSS files

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-tools#3464]
I wonder if it would be nice to enable language-specific CSS customisations for APIView. Personally I override the styling of Java APIViews with different icons, font sizes, etc, but it would be potentially interesting to enable this for all reviewers of Java APIs, as it may then feel more idiomatic (the current icons do not).

I am happy to supply some Java-specific icons and CSS, if accepted.

**Comment by JonathanGiles** [comment]
I would approach this quite simply - add empty scss files for each language we support, and add conditional switches (like we already have in [_ReviewsPartial.cshtml](https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewsPartial.cshtml#L28) to include the appropriate css file. 

We can then move Java-specific CSS into our file (e.g. from #3463 and #3465)

**Comment by JackJamesNZ** [comment]
@JonathanGiles I was looking to work on this

**Comment by cmcd22** [comment]
@JonathanGiles might be best to assign this issue to me now
