### ISSUE TITLE
Support for Java variants

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-tools#3465]
I would like to be able to support more language sub-variants. Currently we have support for the language to be 'Java', but it would be nice to also support 'Java-Spring' and 'Java-Android', so that the icons can be made appropriate for Spring and Android, including in the main reviews table, as well on each individual review page.

**Comment by JonathanGiles** [comment]
In my mind, this can be approached by doing the following:

* Introducing a new property to the [APIListing](https://github.com/Azure/azure-sdk-tools/blob/main/src/java/apiview-java-processor/src/main/java/com/azure/tools/apiview/processor/model/APIListing.java) type named `variant` or similar.
* Introduce code into the Java APIView processor code to determine the variant (based on package name containing 'spring' or 'android', for example), and set the variant value into the APIListing.
* In the ApiViewWeb, introduce checks for variant, e.g. in [_ReviewsPartial.cshtml](https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/APIView/APIViewWeb/Pages/Shared/_ReviewsPartial.cshtml#L49) you might check variant to change the icon.

The end result should be additional icons being used in all places that icons are displayed. 

This work may align with issue https://github.com/Azure/azure-sdk-tools/issues/3464, as these will be Java-specific, it makes sense for this CSS to be part of a java-specific CSS file perhaps.

**Comment by Vailorium** [comment]
@JonathanGiles
