### ISSUE TITLE
Review scope of doc-warden tool

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#347]
In pull request #320 we discussed removing some of the package indexing logic from the ```doc-warden``` tool since not all of it is required anymore. It turns out that we need to index packages in order to accurate check capitalization of README.md file headers, and for presence information for CHANGELOG.md (and variants) files.

This issue is to do a bit of an overall review of the scope of the ```doc-warden``` tool and whether we can remove some functionality and reduce the complexity of the tool (i.e. not having to have deep knowledge of package types/formats to do its work).

**Comment by chidozieononiwu** [comment]
With the conversion of `.rst` files to `.md ` in the python repo some of the DocWarden logic might need to be updated also. 
There is also the issue of moving all changelog logic into the `eng/common directory`

**Comment by chidozieononiwu** [comment]
Closing this since most of those changes were eventually made in eng/common rather than doc warden.
