### ISSUE TITLE
Next/previous buttons should only navigate to unresolved issues

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#3470]
The addition of the next/previous buttons on comments is great, but seems it should only navigate - by default, anyway - through unresolved comments. Resolved comments are collapsed by default and not opened on navigation - and it would be confusing to open them when navigated to (harder to tell what's resolved and not) - so there's no easy way to get to the next/previous comment.

**Comment by cmcd22** [comment]
@JonathanGiles I'll take this one
