### ISSUE TITLE
Create EngSys scripting guidelines

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#3473]
This came up in the branch deletion post-mortem. Examples of things that would be listed in the guidelines:

- Plumb in default `-WhatIf` support to all scripts
- Improve logging more generally across our current scripts of actions taken

**Comment by kurtzeborn** [comment]
We already have some EngSys scripting guidelines [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/2/Azure-DevOps-Pipeline-Guidance?anchor=powershell-tips).  Maybe these should be broken out into a separate document and updated to include these new suggestions.
