### ISSUE TITLE
Swagger APIView diff experience improvement

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-sdk-tools#3485]
Currently, in Github swagger reivew experience. When service create a new api-version swagger, it's hard to review what's the difference between this new api-version and previous version.  

I expected swagger APIView could display cross api-version difference. Not just text diff, but also include  which operation added in new api-version, which swagger definition model changed.  In this way, reviewer can easily identify what has beed changed in this PR.

**Comment by praveenkuttappan** [comment]
This is about offline diff gen and create run time diff only if pre-generated diff is missing
