### ISSUE TITLE
.NET branding is wrong in APIView

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#3487]
Nit: in APIView, ".NET" should be cased that way everywhere. I see from the "Creak issue" hamburger menu item it's ".Net".

<img width="143" alt="image" src="https://user-images.githubusercontent.com/1532486/175126991-c59d0ab5-8a63-4484-9def-536e855e8ef1.png">

See https://github.com/dotnet/brand

**Comment by chidozieononiwu** [comment]
Resolved by https://github.com/Azure/azure-sdk-tools/pull/4206
