### ISSUE TITLE
Improvements to API View Search

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#3492]
The following improvements need to be made to APIView Search
- Add search by pull request number.
- Improve search precision.

We also have a problem with the precision of the search. This is because there is some inconsistency between review names stored in cosmos and the review name as displayed on the UI side. Also even the different name fields in the reviews document (in cosmos) seem to be doing different things. We have review.Name, review.Revisions[ i ].Name, and review.Revision[ i ].Files[ i ].Name . It's not clear which is the real source of truth for the review name.

**Comment by praveenkuttappan** [comment]
@chidozieononiwu This is done. right? Is there any more enhancements required in search?

**Comment by chidozieononiwu** [comment]
Merged but not deployed.

**Comment by chidozieononiwu** [comment]
This has been deployed
