### ISSUE TITLE
APIView BreakUp Swagger Token Files

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#3493]
- Large token files (e.g. swagger) need to be post processed into smaller files.
- This will help improve performance on UI side as the files can be loaded in sections.

**Comment by praveenkuttappan** [comment]
@chidozieononiwu Do we still need this? I thought we decided to go with partial page load.

**Comment by chidozieononiwu** [comment]
This can still be used to track that work.
