### ISSUE TITLE
Update Pixel-Server Readme to reflect issues real users encountered while leveraging pixel-server

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#35]
I've had multiple people ask the below questions, so the documentation should be updated..

1. querying appinsights data (like the base query that has been shared in the existing appinsights)
2. More examples!
    * A tiny bit more detail on what happens when a request hits the pixel-server
    * Given a pixel in a markdown, what data comes out of that?

**Comment by kurtzeborn** [comment]
Pretty sure this is dead since we discovered that GitHub caches images on the server, so we don't get accurate data.
