### ISSUE TITLE
Generating an AST, a thriller, an emotional roller-coaster of untold amplitude .  

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-tools#3503]
I have a branch, C++ , i make some updates i commit / submit. build ,generate ast, zip, rename,upload  .... hmmm ... my changes are not reflected .. . maybe i missed something...  build ... generate upload .. same ... hmmm doing the same thing multiple times expecting different results is the definition of insanity , yet we shall persevere ... .clean all rebuild all generate ast upload .... aha ... nope ... hmmm... same thing ... i am sinking lower and lower in the pit of sorrow and despair ... we are past the depressive state, we are going into full blown insanity... what am i doing with my life.. why am i here ... one more time.  
delete the local files , ALL of them , reclone the project , go to branch ... rinse and repeat, HUZZAAH we did it , the changes are there. Why we don't know and we don't dare ask, as it might anger the spirits that haunt the ast generating code. 

Proposal : 
1. good: clarify what folders is an AST generated from, definatelly not the source code. some rando build locations? 
2. better: can we have a warning at least when the sources and whatever files are consumed are out of sync ? a simple time stamp or MD5 hash comparison would do
3. best : when the files are out fo sync actually trigger a build in the root or ask for build params to run a full build and satisfy whatever mystical requirements are needed to get the proper content. 

If i wasn't paranoid enough and OCD enough i would not have double chaked the results thus the reviewers would have been even more confused that they already are by my changes.

**Comment by benbp** [comment]
@gearama you might be interested in https://github.com/Azure/azure-sdk-for-cpp/pull/3763

**Comment by praveenkuttappan** [comment]
@benbp  I see automatic API review only for Azure::Core. Is this enabled for all pipelines?

**Comment by benbp** [comment]
@praveenkuttappan it is. Seems like it could be a bug? See for example the "identity" api review uploaded here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1745387&view=logs&j=a5b8631f-d2a8-5bf4-c5b7-ed5dd46e146c&t=e1b0a0cf-6330-5d90-93da-5076ba54d894 but clicking through the links doesn't show anything like an identity api review.

**Comment by praveenkuttappan** [comment]
This is no longer required since we generate API review for C++ using new parser.
