### ISSUE TITLE
Add support for pop-up on the calendar component 

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3514]
Certain meeting times are reserved for certain time zones. Add support for a pop-up when those times are picked up.

This is true for:
- Informational meetings: User should be notified that the Mon(Asia Pacific preferred), Tuesday (European preferred) is preferred by certain time locations and so should be chosen with discretion.

**Comment by JonathanCrd** [comment]
This is a duplicate for: 

- https://github.com/Azure/azure-sdk-tools/issues/3589

Closing this issue but copying its description in the other one.
