### ISSUE TITLE
Client side telemetry experience

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3515]
PowerApps has the ability to connect to AppInsights. Is this what we want to enable? What is the best way to do this in a way that is compliant with existing Eng Sys tooling?

**Comment by benbp** [comment]
I'm happy to help brainstorm on this and share what we're doing today if people would find it helpful.

**Comment by maririos** [comment]
Not only UI but also flows executed

**Comment by maririos** [comment]
it doesn't work for flows :(

**Comment by JonathanCrd** [comment]
I created a new Application Insights resource and connected the apps and the Prod environment analytics to it.

For now, we can leave it like that for the next release cycle and see what data we get, the next step would be to define how to use the data to get the most value from it.

I'm going to create a new issue for monitoring that and define the strategy we want to use with this data. @benbp we can discuss later what you already do today and see how we can integrate our app with the current team's processes 😄
