### ISSUE TITLE
Limit Calendar to go n days to the future for scheduling events

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3541]
Meeting settings should control how much time in advance can a meeting be created.
The calendar is currently open to go as much as people want into the future.
The events list shows only the events for the next 90 days

**Comment by ladonnaq** [comment]
We should be able to set the min and max lead time for the scheduling of meetings.  We should also be able to add additional timeslots or remove timeslots.

**Comment by maririos** [comment]
This has been fixed with the move to Outlook calendar. Issue https://github.com/Azure/azure-sdk-tools/issues/5015
