### ISSUE TITLE
For SDK meetings, Github issues can be created in azure-sdk and azure-sdk-pr repositories

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3543]
Currently only `azure-sdk` is allowed. We need to make sure that a service can create a review in a private repository

**Comment by maririos** [comment]
@maririos  make sure to communicate with Kyle

**Comment by JonathanCrd** [comment]
I have added this feature in Dev.
I'm not closing this issue yet until we deploy to PPE just to be sure that the two options are being displayed correctly.
I also updated PROD with the private repo info on the Admin app.
