### ISSUE TITLE
Consider using "None" instead of "Default" in Subservice area

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3556]
Current requirement was asked for REST API meetings. We need to figure out if this applies for the other 2 types of meetings

**Comment by JonathanCrd** [comment]
> We need to figure out if this applies for the other 2 types of meetings

For Informational meetings, there's no option to specify a subservice

For SDK Review, there's is. It shows "Default" too as the default option. Changing this to "None" as well.

**Comment by JonathanCrd** [comment]
Fixed 🚀

Another small change I did: The `+ Add new` option now always appears at the end of the list, not as the second option anymore
