### ISSUE TITLE
Consolidate REST API meeting information content with the wiki information

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3557]
Current REST API meeting add process information to their meeting invites. For now, we are including it in the message of the meeting invite that comes from the scheduler tool. (See specifics [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1565893)).

This information is similar to the one in the wiki https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/665/Azure-REST-API-Stewardship-Review .

We need to consolidate this information and make sure that we don't have dups or inconsistencies between them.

**Comment by maririos** [comment]
The majority of the information should be in the Wiki and the content of the email should point to it. That way we don't have multiple sources of information.

With that present, the proposed content of the email is:
```
Hi All, 

This review is designed to help service owners create developer-friendly and consistent REST (data plane)
APIs for your service. For information about the meeting format, the prerequisites, and more, see <link to wiki>.

Here if the information provided:
- Service name: <Service name>
- Key contact for this review: <name person that created the meeting> <email person that created the meeting>

- Review material:
  - Issue tracking the meeting
  - Swagger PR link
  - Link to any docs uploaded
```

Need approval from meeting admin before implementing the changes

**Comment by maririos** [comment]
@markweitzel you ok if we add this content to the meeting invite content?
Note that us modifying the content is temporary until the Admin app supports modifications to templates

**Comment by markweitzel** [comment]
@maririos -- the issue that I have with the proposed format is that it requires the reader to take another action--click to the wiki--and then read. The success rate of this will be very low. I would keep the information in the email--and make sure to put the CTAs at the top. We should still provide links to the wiki as well. 

I want to make sure that we optimize around the experience of the recipient of the information. Agree it would be easier for us to manage a single source of information, but significantly harder for the recipient to consume this.

**Comment by maririos** [comment]
I have identified the problem with our email template. I added a correct one for API meetings and have the following content:
i.e. 

![Image](https://user-images.githubusercontent.com/9868623/185042917-94111a8d-843f-432b-b4fa-b9233b35d2a2.png)

I still need to add the information requested about the process

**Comment by maririos** [comment]
Process added.
Looks like I am still missing including the PR link if provided

**Comment by maririos** [comment]
I opened issue https://github.com/Azure/azure-sdk-tools/issues/3986 for the PR link
