### ISSUE TITLE
PoliCheck failing due to existing code.

### ISSUE THREAD

**Issue by pansharm-ms** [Azure/azure-sdk-tools#3576]
Hello,
I have created a pull request in repository: [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs)
Here is the PR link: https://github.com/Azure/azure-rest-api-specs/pull/19316
The pull request is failing the PoliCheck due to some words in the [custom-words.txt](https://github.com/Azure/azure-rest-api-specs/pull/19316/files#diff-d09ef4ff2b106e85f7cf9ddb903b2d00534fc3bf9063d4e63b226a19eaa1cd16) file.
Although I have not added any invalid words in the PR but the file already contains some words.
I am not sure how to fix this check as removing existing words may cause breaking changes.
Can you please look into the issue?
If removing existing words will not cause any breaking change then can I remove the words and commit in my PR.

**Comment by weshaggard** [comment]
@ruowan didn't we fix this?

**Comment by ruowan** [comment]
I think @tianxchen-ms have already fixed. Maybe you could resolve conflict and rerun the pipeline.

**Comment by raych1** [comment]
> Hello, I have created a pull request in repository: [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) Here is the PR link: [Azure/azure-rest-api-specs#19316](https://github.com/Azure/azure-rest-api-specs/pull/19316) The pull request is failing the PoliCheck due to some words in the [custom-words.txt](https://github.com/Azure/azure-rest-api-specs/pull/19316/files#diff-d09ef4ff2b106e85f7cf9ddb903b2d00534fc3bf9063d4e63b226a19eaa1cd16) file. Although I have not added any invalid words in the PR but the file already contains some words. I am not sure how to fix this check as removing existing words may cause breaking changes. Can you please look into the issue? If removing existing words will not cause any breaking change then can I remove the words and commit in my PR.

@pansharm-ms , can you resolve branch conflicts in PR then re-run the CI checks?

**Comment by pansharm-ms** [comment]
Verified that the issue is no longer occurring when created a new PR with the latest code.
Closing the issue now.
