### ISSUE TITLE
Move TestResources scripts to eng/common

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#358]
>After this goes through and the pipeline runs, should I move the TestResource scripts and replace them with stubs as we discussed?

Yes once this is goes in and starts running then you can move your test resource scripts into the eng\common directory and watch the updates flow :)

_Originally posted by @weshaggard in https://github.com/Azure/azure-sdk-tools/pull/353#issuecomment-578242067_

**Comment by heaths** [comment]
Be sure to update all repos' pipelines to use the direct script, but create stubs for end users. Or, rather, since we haven't documented how to use them, maybe it's not worth stubs directly under eng. @weshaggard and @danieljurek, what do you think?

**Comment by weshaggard** [comment]
I'd only add stubs if it actually helps in some way if it doesn't help I'd remove that layer of indirection and simply call the scripts directly from the eng\common directory.

**Comment by danieljurek** [comment]
This should include a parameterized template such that the archetype-sdk-tests.yml files do not invoke the scripts directly but import the template to do so.

**Comment by heaths** [comment]
The azure-sdk-for-net repo isn't using this yet. Not sure about the other languages.

Additionally, this repo needs to be updated from the .NET repo first.

**Comment by danieljurek** [comment]
* [ ] Update templates to include a subscription ID
  * [ ] Merge subscription ID change PRs into language repos (see: https://github.com/Azure/azure-sdk-for-net/blob/master/eng/pipelines/templates/jobs/archetype-sdk-tests.yml#L106 and https://github.com/Azure/azure-sdk-for-net/commit/48a7a6eb3fe846c2307fa705ae311eb56f79eb47) 

* [ ] Update `tests.yml` files
  * [ ] .NET
  * [ ] Java
  * [ ] JS
  * [ ] Python

**Comment by heaths** [comment]
Is this one done? I went ahead and checked .NET since I know that's completed.
