### ISSUE TITLE
Support multiple ARM template selection in test pipelines

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#3580]
We need a way to support selecting different ARM templates within a single test pipeline. Currently the storage team needs this as a way of testing one-off resource types. A couple ways I can think of to do this:

- Support custom arm template paths via matrix variables (e.g. similar to how we support the special field `armTemplateParameters`) or via the `MatrixConfigs` yaml configuration.
- Give guidance on using bicep modules with a top level bicep file that uses if conditionals to select a module, based on `armTemplateParameters` set in the matrix config. It may be complicated to figure out hwo to standardize deployment outputs and skip/run test-resources-post scripts.

CC @seanmcc-msft

**Comment by seanmcc-msft** [comment]
After talking with Scott, it sounds like we are going to create a new pipeline for the virtualized storage account tests, so we will no longer need to support multiple ARM templates on the same pipeline.
