### ISSUE TITLE
Add a label to azure-rest-api-specs PRs for definitions generated from Cadl

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3594]
Some service teams are starting to use Cadl to author their API definition and then generate OpenAPI v2 from the Cadl.  The Cadl compiler adds a marker in the generated OpenAPI to indicate that it came from Cadl. PRs that have OpenAPI generated from Cadl should have a special label added so that reviewers are alerted that the OpenAPI was generated.

**Comment by raych1** [comment]
@jianyexi will work on this task in this sprint.
https://devdiv.visualstudio.com/DevDiv/_sprints/taskboard/Azure%20Swagger%20Tools/DevDiv/Copper/CY22%20Q3/2022-07?workitem=1563421

**Comment by raych1** [comment]
This feature was released in spec PR pipeline.
