### ISSUE TITLE
azure-rest-api-specs PR pipeline should verify that Cadl is checked in for generated OpenAPI

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3595]
When a PR is opened in azure-rest-api-specs containing an OpenAPI file that was generated from Cadl, the PR pipeline should verify that the corresponding Cadl file(s) are also included in the PR.

**Comment by raych1** [comment]
Being tracked in this task.
https://devdiv.visualstudio.com/DevDiv/_sprints/taskboard/Azure%20Swagger%20Tools/DevDiv/Copper/CY22%20Q3/2022-07?workitem=1563422

**Comment by raych1** [comment]
This feature was released in spec PR pipeline.
