### ISSUE TITLE
Create SDK API reviews when swagger is modified

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#3602]
SDK automation will generate language specific SDK packages when a swagger is modified. This swagger PR pipeline step will create an API review for these generated SDK packages so we can identify changes at language SDK level when a swagger is modified.

**Comment by praveenkuttappan** [comment]
@dw511214992 Can you please close this issue since SDK automation went live already?

**Comment by dw511214992** [comment]
closed it as it's ready in production
