### ISSUE TITLE
Cross language view of API review

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#3603]
We have got some requests from reviewers to add an ability to view how a specific class or API is defined in other languages without actually opening that review. For e.g. When someone reviews swagger file and want to see how a specific REST API looks in Python SDK. 

We will need to add an option in review page to ask users if they want to see this API in other supported languages and show the API details as a projected sub window and allow user to open that review page in a window so they can comment on it. 

Currently we do not have any metadata to identify APIs across language SDK reviews. This project requires some additional metadata added by code generators so we can identify similar APIs across languages.

This issue also depends on #3600

**Comment by tjprescott** [comment]
Python has implemented CrossLanguageDefinitionId. I presume that's the necessary prerequisite.

**Comment by maririos** [comment]
Closing as dup of https://github.com/Azure/azure-sdk-tools/issues/4033
