### ISSUE TITLE
If available, reuse existing GitHub issue when scheduling a meeting - REST API

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3619]
Currently the scheduling app creates a new issue every time a meeting is scheduled. In the case of REST API meetings, if a service is coming back for a follow up, they use the original GitHub issue instead of opening a new one. This helps to keep track of the history, comments, etc.

Is this true for the other type of meetings? What will be the flow in the scheduler app for this?

**Comment by JonathanCrd** [comment]
Regarding the follow-up meetings, currently there's an implementation for this. If the meeting was not cancelled, and the scheduled date has passed, the app will show a button to **schedule a follow-up**. What this is actually doing is editing the meeting, and it will keep the following information:
- Service 
- Subservice
- GitHub issue

So, no new issue is being created if this is scheduled by clicking the button I mentioned before.
Should I add a new option when creating a **new meeting**, asking if this is a follow-up for a previous meeting? And then let the user provide the GitHub Issue? I wonder what repercussions this could cause in our current flow.

**Comment by JonathanCrd** [comment]
Also, I should mention that there are labels and messages we have to change so it is clear that the updated meeting is a follow up, and not an update.

Currently, the email and the app display the same messages (titles, emails, etc) as when editing a meeting. This could create confusion.

**Comment by JonathanCrd** [comment]
> Is this true for the other type of meetings? What will be the flow in the scheduler app for this?

For SDK Review, there's an option to specify if the meeting type is either `Introduction` or `Follow Up`. It will create a new issue on GitHub every time, no matter if `Follow Up` is selected or not. In this case, I'm deciding how to prevent this and reuse the already existing issue. One option is to ask the user for it (in a textbox), another option is to let the user select a previous introductory meeting and get the GitHub link from our records.

**Comment by maririos** [comment]
We need to clarify what the behavior for this is for `Informational` and for `SDK Review`.  At this point in the development, I am hesitant to change any of those views until we hear explicit feedback from them. I do see how in a more advance stage we would like all meetings to behave similarly.

As for the API Review meeting, I would advise to go with because the `follow-up flow you` mentioned might not be easily discovered and it won't work for users that today have issues opened against Github:
> Should I add a new option when creating a new meeting, asking if this is a follow-up for a previous meeting? And then let the user provide the GitHub Issue?

As for the `schedule follow-up` flow that is already in place, what do you think about disabling it until we have a clearer understanding of how and frequency it is going to be used? I want to avoid having too much logic or different behaviors to maintain

**Comment by maririos** [comment]
I opened issue https://github.com/Azure/azure-sdk-tools/issues/3803 to track the work on the other meetin types

**Comment by maririos** [comment]
@JonathanCrd  looks like the required information is done and we are ready to implement this.
Let me know if that is not the case

**Comment by JonathanCrd** [comment]
Done for API Review.

When scheduling a meeting, there's a new text field at the bottom that allows the user to provide a GitHub Issue. If this text field is not blank, first it is going to validate that the issue exists, and then it will not create a new tracking issue and use that one instead.



![Image](https://user-images.githubusercontent.com/17486462/183722261-08fdc44d-9846-4e9d-a6f4-64a45bdc8140.png)
