### ISSUE TITLE
Populate swagger repository information in Prod

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3620]
In REST API meetings, Prod instance doesn't have information about the available repos to associate a PR with. See
![image](https://user-images.githubusercontent.com/9868623/178561494-e617594a-e0d7-4345-bc2f-c5ebad64929c.png)

For Private preview we agreed on including https://github.com/Azure/azure-rest-api-specs

**Comment by maririos** [comment]
This issue has been fixed

**Comment by markweitzel** [comment]
![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 09-54-42](https://user-images.githubusercontent.com/522116/179527211-144d4b4b-f2ae-46ae-8a88-a8fcddb352d8.png)

**Comment by JonathanCrd** [comment]
Thanks for reporting this @markweitzel .

It's fixed, now it shows both repositories.
![image](https://user-images.githubusercontent.com/17486462/179577205-41cdcf7d-fd69-4491-8613-85f19dd3921a.png)
