### ISSUE TITLE
Make user options "sticky"

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#3638]
i.e. store the language selection in a cookie such that the language stays selected between sessions.

**Comment by chidozieononiwu** [comment]
I will use this issue to track persistence of all user options.

**Comment by chidozieononiwu** [comment]
This has been resolved

**Comment by billwert** [comment]
@chidozieononiwu hey! Has there been a regression here? It seems like my options are not stored.

**Comment by maririos** [comment]
@chidozieononiwu  could you please take a look?

**Comment by chidozieononiwu** [comment]
I don't see any issue here the user preferences are still sticky.

**Comment by billwert** [comment]
Ah weird. It's indeed working this morning but I've definitely seen it forget that I'd previously checked java in the past, particularly if I have to log in.
