### ISSUE TITLE
Python CI shows warning about overwriting a read only task variable 'OSName'

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#364]
Verify agent OS step in pipeline (~~~verify-agent-os.yml@azure-sdk-tools~~~) overwrites OSName variable and this is causing a warning as shown below.

~~~
##[warning]Overwriting readonly task variable 'OSName'. This behavior will be disabled in the future. See https://github.com/microsoft/azure-pipelines-yaml/blob/master/design/readonly-variables.md for details.
~~~

**Comment by weshaggard** [comment]
This warning is showing up in all our language pipelines and it is a likely going to cause use bigger issues soon. @chidozieononiwu can you please work on addressing this and updating our verify OS yml template to use the newer eng/common in the process?

**Comment by weshaggard** [comment]
There is more then just making the tweak in the yml template. We need to update the pipelines in the language repos as well. We should probably remove OSName completely as we were discussing in https://github.com/Azure/azure-sdk-for-java/pull/8685

**Comment by chidozieononiwu** [comment]
This has been resolved by removing `$(OSVmImage)` from the pipeline matrix and only setting it after `verify-agent-os.yml ` has run. Example PR https://github.com/Azure/azure-sdk-for-net/pull/12029
