### ISSUE TITLE
Show Only Diff option should show "context"

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#3640]
Show Only Diff is a great option that is unfortunately totally unusable today. If shows very small slices of the full listing (just the changed members) which makes it impossible to tell what type the members are in and what other members are in the same type. 

I propose that this option simply filters out all types that don't have changes, but otherwise shows full types with changes and their namespaces.

Update 6/14:
- Active development and testing will keep happening until June 20th
- By June 20th Dozie will share the link of an APIView environment which will be stable for you to test.
  - If critical changes need to be made, they will be communicated over Teams
- Documentation will be improved and shared by the same date
- Unless there is critical feedback that needs to be addressed right away, we will deploy to Production on June 27th
- Rethink migration strategy for the other parsers

**Comment by JonathanGiles** [comment]
@praveenkuttappan @chidozieononiwu I suspect for this to work we would need to improve the language parsers to discern in the JSON output between lines that should never be filtered out in diff view (i.e. class declarations), and the rest of lines that can be removed if they are not diffed. Would you agree? If so, did you want to make a proposal that we could implement in the parser for each language?

**Comment by praveenkuttappan** [comment]
That's true. APIView doesn't have full context of parent components which makes it hard to find parent context lines to show. Adding a context like Level 0, Level 1, Level2 etc to show tree structure will help us find the context and show entire context with it's siblings.

**Comment by JonathanGiles** [comment]
@praveenkuttappan What would be more useful for APIView? It seems we have two different approaches:

1. Annotate the lines that are non-hidable
2. Annotate all lines with their level (I wonder if at that point we can remove all code in our parsers related to adding indentation whitespace).

**Comment by praveenkuttappan** [comment]
1. Currently tokens are created as a flat list of tokens with line separator. So there is no hierarchy context.
2.  Annotating lines with their level number is better option.

**Comment by maririos** [comment]
Feedback from @KrzysztofCwalina : "The way I would address the problem is by changing "show diff only" to "show types with diffs only", i.e. if any members had diffs, the whole type with these members is shown."

**Comment by tjprescott** [comment]
Related: https://github.com/Azure/azure-sdk-tools/issues/7375

**Comment by maririos** [comment]
This has been completed as part of the work on #5897 and #8174 .
Once those epics are stable, other languages can onboard the Tree Token parser and use the Diff with context feature
