### ISSUE TITLE
SDK Automation should report error when the config output path is incorrect.

### ISSUE THREAD

**Issue by qiaozha** [Azure/azure-sdk-tools#3650]
Sometimes, we will get service readme.typescirpt.md configed like this https://github.com/Azure/azure-rest-api-specs/pull/19729/files  And in fact this RP's SDK can not be generated correctly if we don't add the title configuration. Such kind of SDK generation failure can not be detected if we don't set the SDK output path correctly. we should report errors in the SDK automation pipeline when this output path is incorrect.

**Comment by dw511214992** [comment]
close it as finished.
