### ISSUE TITLE
[Test Proxy] Expand oauth sanitizer matches for request filtering

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-tools#3658]
This issue is a feature proposal that can be closed if we decide that we don't actually need/want this functionality.

Context: the Storage team gave feedback about the presence of some token fetching-related requests that remain in recordings, even when an [oath response sanitizer is used](https://github.com/Azure/azure-sdk-for-python/blob/7ee992704e2e6152b22bcca072addbb2e1bd43c6/sdk/storage/azure-storage-blob/tests/conftest.py#L17). (These requests only seem to get sent in synchronous tests, for Storage and other libraries.)

[Here](https://github.com/Azure/azure-sdk-for-python/blob/7ee992704e2e6152b22bcca072addbb2e1bd43c6/sdk/storage/azure-storage-blob/tests/recordings/test_append_blob.pyTestStorageAppendBlobtest_append_block_from_url_with_oauth.json#L148) is an example of one of these requests in a Storage recording. The contents aren't necessarily sensitive, but tenant IDs are included in a few locations. The Storage team is reasonably wondering whether these auth-related requests/responses should also be filtered out from recordings when the oauth response sanitizer is used, despite not having `/oauth2` in the URL.

**Comment by scbedd** [comment]
For clarity, you'd want the sanitizer to apply to this entire object:

```
    {
      "RequestUri": "https://login.microsoftonline.com/72f988bf-86f1-41af-91ab-2d7cd011db47/v2.0/.well-known/openid-configuration",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Accept": "*/*",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "keep-alive",
        "User-Agent": "azsdk-python-identity/1.11.0b2 Python/3.10.5 (Windows-10-10.0.22000-SP0)"
      },
      "RequestBody": null,
      "StatusCode": 200,
      "ResponseHeaders": {
        "Access-Control-Allow-Methods": "GET, OPTIONS",
        "Access-Control-Allow-Origin": "*",
        "Cache-Control": "max-age=86400, private",
        "Content-Length": "1753",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Fri, 08 Jul 2022 23:45:29 GMT",
        "P3P": "CP=\u0022DSP CUR OTPi IND OTRi ONL FIN\u0022",
        "Set-Cookie": [
          "fpc=ApiZaXZ0gstOkPPtSbHZmN8; expires=Sun, 07-Aug-2022 23:45:30 GMT; path=/; secure; HttpOnly; SameSite=None",
          "esctx=AQABAAAAAAD--DLA3VO7QrddgJg7WevrHqDSxbEJdXguyyaBREtRWckCMP70zRgra-rOoZMXnt01xID3cnePxVs__mbpuJlcbG_Gh25ABkSuqm0clgU1GiCHBr8h2n3yIrc2hGTiBiCPglijE7DukQWBTUZlysqhIqNl8lTLn2TPUeWjWluyh2bKRNP4OUdycCQ0Glgn-YYgAA; domain=.login.microsoftonline.com; path=/; secure; HttpOnly; SameSite=None",
          "x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly",
          "stsservicecookie=estsfd; path=/; secure; samesite=none; httponly"
        ],
        "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "x-ms-ests-server": "2.1.13156.10 - SCUS ProdSlices",
        "X-XSS-Protection": "0"
      },
```

and omit both the request and the response yes?

**Comment by scbedd** [comment]
Ok. I've been looking around. I am going to leave the `oauthsanitizer` as is for now. Will provide a new sanitizer as requested in #3659 called `RegexMatchEntrySanitizer`. It will follow the same "rules" as our other text sanitizers. EG, if you give me a body that isn't string like, we aren't going to match against it.

URI/Header values though? Easy.

You will be able to register multiple of this sanitizer for different URLS etc.

**Comment by scbedd** [comment]
Closing as no-op until someone else requests the default add to OAuthSanitizer. The new addition sanitizer should cover pretty much everything.
