### ISSUE TITLE
[Test Proxy] Add sanitizer for filtering entire request/response

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-tools#3659]
The Python Storage team made a request for a sanitizer that would allow them to filter out an entire request/response interaction instead of individual parts. They didn't specify a method for determining the requests to filter, but this was raised in the context of https://github.com/Azure/azure-sdk-tools/issues/3658. It would probably be most convenient to specify something like a URI regex to choose requests to filter.

**Comment by scbedd** [comment]
ok. I'll call these implementations `Omit` sanitizers. WE already have something _like_ this with the oauth sanitizer, but that isn't going far enough.
