### ISSUE TITLE
[Scheduler App] [Bug] PR Not found Error shown when creating a new Rest Review

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#3664]
When creating a new Rest Review, if no PR is specified, an error will show up as a notification. However, a PR number is not required until 48 hours before the meeting, so this shouldn't be displayed if it is not required.

Add a validation to skip linking the GitHub PR if the user did not specify it when creating the issue.

**Comment by maririos** [comment]
check if this is still happening

**Comment by JonathanCrd** [comment]
With the new toggle, this is not an issue anymore



![Image](https://user-images.githubusercontent.com/17486462/184946341-396544b8-5a8f-472f-843f-23c0ab42e8fa.png)



![Image](https://user-images.githubusercontent.com/17486462/184946323-ad8439ed-1411-4b9a-9a46-5387e4481c46.png)
