### ISSUE TITLE
create button below the fold...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3668]
The `Create` button is below the fols. It would be good to have this above the fold so that it's obvious to the user
![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 10-20-38](https://user-images.githubusercontent.com/522116/179532604-ae81ccb6-2ab1-48dc-b6d6-322093da9b42.png)
.

**Comment by JonathanCrd** [comment]
This is no longer an issue, the Create Button is now under the calendar
