### ISSUE TITLE
Make it possible to schedule review w/out Open API document...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3669]
It's possible that a team may not have an Open API document when they are asking for a review. This is rare, but ideally, as we move earlier in the design stage, and adopt Cadl, could become more frequent. Perhaps there should be an overrride that indicates, "I don't have an Open API document" and this would kick off an email to the api stewardship board indicating an exception came in.

![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 10-23-31](https://user-images.githubusercontent.com/522116/179532860-f7057b3e-b4f4-4ad8-9fd1-5c20b8f8236c.png)

**Comment by maririos** [comment]
It is currently not required but the re `*` suggest it is. We should delete it from the UI

**Comment by JonathanCrd** [comment]
Now that message will only appears when the user select to add the PR Link later:


![Image](https://user-images.githubusercontent.com/17486462/188239324-64ce90ad-b151-4bab-bdc1-b59caa62ff85.png)

and



![Image](https://user-images.githubusercontent.com/17486462/188239619-d5b1b4f9-6b00-433e-a1e7-fb92a86886ab.png)
