### ISSUE TITLE
Please spell "your" properly

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3670]
![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 10-27-37](https://user-images.githubusercontent.com/522116/179533735-5dbebcea-ded3-46b4-a121-f1cad16db512.png)

**Comment by benbp** [comment]
Also `isnt't`

**Comment by mrjeanjoseph** [comment]
Simply rephrasing this should suffice.
Based on the service tree, contact us if your service is not listed.

**Comment by maririos** [comment]
You could also look into https://github.com/Azure/azure-sdk-tools/issues/3734 as you are already in that section

This text happens in the 3 meetings, so it will need to be updated in all of them
