### ISSUE TITLE
"Sub Service" entry field magically appearing is jarring...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3671]
We always ask for a "sub service" and when the entry field magically appears, it's jarring and shifts everything down. Rather, we should make this always visible but not enter anything until the user selects the service.

![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 10-29-06](https://user-images.githubusercontent.com/522116/179534134-fe498075-7353-490f-a40c-e79e6df9f323.png)

**Comment by maririos** [comment]
This was fixed a while back for API Review meeting.
Fixed for SDK meeting implemented too.
