### ISSUE TITLE
Text box alignment

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3673]
Very minor issues, but the text boxes should be left aligned.

![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 10-33-46](https://user-images.githubusercontent.com/522116/179535204-937e5315-372a-4845-a8ca-ad7d0db00511.png)

**Comment by JonathanCrd** [comment]
Fixed, also took the time to fix any other alignment issues in the other meeting types.
