### ISSUE TITLE
Show previous meetings on the Rest Reivew main page

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3674]
![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 10-35-24](https://user-images.githubusercontent.com/522116/179535469-00cba3c7-015c-4677-b24b-888b9b3ad387.png)

**Comment by JonathanCrd** [comment]
Hi @markweitzel, thanks for the suggestion.

Actually, right now there's an implementation for this. By default, previous meetings will be shown in the list. Here's how it looks like:
![image](https://user-images.githubusercontent.com/17486462/182470827-4a4e4539-d0f1-4469-b6f2-32d18d28b0ac.png)

Would it be helpful to add the filter like in the other meeting types, and only show them when the user turns on the option?

**Comment by markweitzel** [comment]
Perfect. I've not seen that yet in the dev environment--but could have missed it.
