### ISSUE TITLE
Change "Rest Reivew" to "API Review"

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3675]
Change "Rest Reivew" to "API Review"
![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 10-36-30](https://user-images.githubusercontent.com/522116/179535637-d2da0891-0439-408e-bdc2-ebb4b00f4896.png)

![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 10-42-51](https://user-images.githubusercontent.com/522116/179536964-a7677f1a-e996-4c48-b2a7-70e63e3a80cf.png)

**Comment by maririos** [comment]
Name consistency across documents

**Comment by maririos** [comment]
REST API is used in:
- Email
- Github repo
- Guidelines

REST API Stewardship
- Email
- Wiki

API Stewardship:
- Teams Channel

**Comment by maririos** [comment]
@markweitzel according to the list of names used in various places, does it make sense to change the name in the Scheduler app?

**Comment by markweitzel** [comment]
Yes. We *should* change the name everywhere. A few more specifics...

* What teams channels are you referring to? The one I am most familiar with is the [Azure API Stewardship Board](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47), although I am sure there are others.
* GitHub Repo: I *assume* you are referring to https://github.com/Azure/azure-rest-api-specs If so, that is OK. What mainly lives here IS the swagger documentation for the API definitions. So this makes sense. Technically, it could get muddled a bit when we get a lot more Cadl docs in, but, the way we use the repo now is so <less than desirable> that we should change the process before worrying about the name.
* Guidelines: These are the REST guidelines, so that is OK. There are folks working on guidelines for other protocols, e.g. gRPC, Graph, etc. Ultimately, the API Stewardship Board may end up reviewing some of these, e.g. gRPC/Events.

**Comment by maririos** [comment]
> What teams channels are you referring to? The one I am most familiar with is the [Azure API Stewardship Board](https://teams.microsoft.com/l/channel/19%3a3ebb18fded0e47938f998e196a52952f%40thread.tacv2/General?groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47), although I am sure there are others.

Yes. That one. The name is API Stewardship which is different to API Review. I know the difference is small, but the more we can do to avoid confusion, the better

**Comment by maririos** [comment]
Name is updated to `API Review`

**Comment by JonathanCrd** [comment]
> Name is updated to API Review

Should we also take the time to change our internal naming? I mean, variables, settings, types, etc?
