### ISSUE TITLE
Add clarifying text to "Meeting Attendees"

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3677]
It should be clear in the "Meeting Attendees" section that the PM and Eng Lead should attend the review session.
![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 10-39-01](https://user-images.githubusercontent.com/522116/179536151-62d10c92-900f-431f-8c43-5a784b9dc059.png)

**Comment by JonathanCrd** [comment]
Fixed


![Image](https://user-images.githubusercontent.com/17486462/188243621-8edd9168-f61e-49e5-8811-b34816e9b2a0.png)
