### ISSUE TITLE
Fix capitalization

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3678]
Fix the capitalization of the word "if" as it begins a new sentence.
![Azure SDK Team Scheduler Rest Review - Power Apps 2022-07-18 10-40-37](https://user-images.githubusercontent.com/522116/179536516-f406c9aa-95de-4b2c-9429-1be46bcbb4dd.png)

**Comment by maririos** [comment]
Updated in all 3 meeting types
