### ISSUE TITLE
Incorrect versions shown in Swagger Breaking Change report

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3680]
The [Swagger Breaking Change PR check in PR #19791](https://github.com/Azure/azure-rest-api-specs/pull/19791/checks?check_run_id=7364414414) shows "2022-04-01" as the new and base version should show "2022-04-01-preview".

![image](https://user-images.githubusercontent.com/85643503/179570745-34d57e6d-45b5-421a-a5ca-aeb6ae20f930.png)

**Comment by raych1** [comment]
The fix was released to production pipeline.
