### ISSUE TITLE
[REST API REVIEW] [BUG] Follow up GitHub link does not work

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#3696]
If you schedule a Follow-up meeting for a REST API Review, there is the GitHub link to the issue that was created. However, clicking this link does not open it in a new tab, it actually does nothing.

**Comment by praveenkuttappan** [comment]
@JonathanCrd I have fixed this issue in Dev. Sorry to jump on this. I thought of picking this issue to improve my understanding of power apps by doing this change. Can you please give it a try on dev env and see if it's working as expected?

@maririos just fyi.

**Comment by JonathanCrd** [comment]
@praveenkuttappan no worries! Thanks for fixing this 💯 

The link works as expected 👍🏼
