### ISSUE TITLE
sdk release pipeline need to provide a way to sign approval for publish artifact outside of pipeline

### ISSUE THREAD

**Issue by chunyu3** [Azure/azure-sdk-tools#3706]
in powerapp release workflow, the last step is to trigger release pipeline to publish sdk package, such as publish to nuget, npmjs and so on.

In the release pipeline, there is an artifact publish approval step which need sdk owner to sign off.  Current SDK owner need to enter the pipeline and click "Resume" button to approve which artifacts are approved to publish.

Now in order to support release SDK in powerapp workflow, we need to sign approval outside of release pipeline.
There are two approaches:

- auto-approval: Pipeline auto approve the publish. In that way, we need to provide an artifact parameter when trigger the pipeline build, and pipeline will auto-approve to publish this artifact. 
- provide a way to approve outside of release pipeline.
1.  provide an devops pipeline rest api  to approve which artifact is approved to publish.
2. send email to ask sdk owner to sign off

**Comment by weshaggard** [comment]
@maririos @benbp any thoughts on this? For releases triggered from our new PowerApps workflow we want to enable the full release to happen in the PowerApp. Should we provide some way to override and disable the approval or provide someway for the PowerApp to submit an approval on the behalf of the user that started the release. I'm not sure if the DevOps approval API supports approval via a rest API outside of their web UI.

**Comment by weshaggard** [comment]
From a quick search I did find https://stackoverflow.com/questions/64370254/how-do-you-get-approvals-and-checks-for-a-given-service-connection-via-the-azure which shows how to potentially do the approval via rest api. So it looks like that might be an option.

**Comment by benbp** [comment]
@weshaggard we could also investigate using callbacks for agentless jobs, e.g. https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/http-rest-api?view=azure-devops

**Comment by weshaggard** [comment]
How would you imagine a callback helping in this scenario? Would we make a call to PowerApps and block until an approval is ready or something along those lines?

**Comment by benbp** [comment]
Yeah the devops pipeline would run the release, then the "approval" step consists of an http call or more likely an az function to the powerapps data to see if the release has already been authorized. If so, we could send a callback right away. If not, then it would block until powerapps gets the authorization and sends the callback. Trying to support both and/or an override would take some thinking though.

**Comment by kurtzeborn** [comment]
For now we're just going to use the approve button in the DevOps pipeline UI.  In the future we will consider the full end-to-end release process as part of our larger partner on-boarding and support processes and likely find a better way to integrate release approvals into that experience.
