### ISSUE TITLE
Avocado should not validate api-version folders for the dev/ folder

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#3711]
Per our new git-friendly instructions we are prototyping with Cognitive Services, teams would put pre-published swaggers they are working on in the /dev folder: structured the same as the /specification folder, but without the "stable", "preview", or api-version folders. The idea is that we copy files *after* modifications, since diff'ing separate files is not something git or GitHub was designed to do effectively. It's not a git-friendly process at all and causes reviewers to go through much more work and tools that don't always work to try to thoroughly diff swagger changes, especially for new api-versions that might have minimal changes.

As such, we need Avocado to not err saying that the swagger is not in the right directory structure, I assume referring to a directory like "preview/2022-07-01-preview". See https://github.com/Azure/azure-rest-api-specs/pull/19825 for context.

**Comment by raych1** [comment]
@heaths , can you use label of `Approved-Avocado` in the PR to bypass this error for short term solution? For long term, we need to evaluate the effort to invest on the validation tools support for `dev` folder. 

Btw, this error for each swagger file wouldn't report again if it's approved once.

**Comment by heaths** [comment]
Cadl will be using a similar concept, though probably will still be under /specifications. It won't force teams to copy swagger before diffing, though, which is honestly the biggest problem with our current system: git and GitHub weren't designed to diff arbitrary files. This is why my proposal has swaggers copied only when publishing after all other changes are made. Branches can be still be used and Cognitive Services will create a stabilization branch while they continue to work on another.

Whether it's worth it to handle this for now, perhaps not.

**Comment by raych1** [comment]
Close this as another issue #3950 is created to track all the validation tools support for dev folder.
