### ISSUE TITLE
[Test-Proxy] Cloned asset repo should auto-ignore some assets

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#3722]
Suggested by @benbp 

I don't know what the complete list of these would look like, but off the top of my head, we'd definitely want to ignore

- `.pyc` (temporarily created python files)
- others

**Comment by benbp** [comment]
Would something like `!**/*.json` work?

**Comment by scbedd** [comment]
Given that this is coming from the test-proxy, which _does_ infer that everything coming through it is recordings? Yeah probably.

**Comment by JimSuplizio** [comment]
> Would something like `!**/*.json` work?

@benbp, the assets repository can store anything deemed to be a test asset. .json files just happen to be the thing that's common across any of the languages that utilize record/playback but we could ultimately end up with other types of assets. Like @scbedd mentioned in the description, the temporary python files would probably be something to ignore as would any potential temporary files for other languages but I don't believe only allowing .json is what we'd want to do here.

**Comment by scbedd** [comment]
Going to close this, I think the gitignore is fine for now.
