### ISSUE TITLE
Select a service drop and product down menu requirements

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#3762]
Near-term: 

1. The drop-down menu for selecting a service is too long.  There needs to be a way to filter or prompt type that filters based on the input. Similar to Azure Devops would be okay.  
2. Add another drop-down menu so that service teams can specify the product (offering, feature, sku) that relates to the meeting.  This information is stored in service tree so we should be able to have a pre-populated list for the service team member to select the product based on the service name. 

Long-term: 

1. The scheduling tool should be invoked as part of the workflow.  The SDK workflow should map to the service and the product. For APEX driven SDK workflows - each product maps to one Cloud Lifecycle record.  A product is an offering, sku, or feature.  When the scheduling tool is invoked from an SDK workflow, the default service and product should be set in the dropdown menus.  To understand how APEX launch candidates are identified and product mapping review the information on the [Azure wiki](https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/57218/Identifying-Product-Launch-Candidates). 
2. For non-APEX workflows the scheduler should still be invoked as part of the workflow. The scheduling tool should still set the default service and product.  There could potentially be another field we would want as a drop-down menu to better identify what is in scope for the API Review and SDK Review.  For example, API Version.  We should work with the API Stewardship Board and Azure DevEx Arch Board to determine additional requirements for North Star and MVP.

**Comment by maririos** [comment]
> The drop-down menu for selecting a service is too long. There needs to be a way to filter or prompt type that filters based on the input. Similar to Azure Devops would be okay.

Created issue: https://github.com/Azure/azure-sdk-tools/issues/3866

> Add another drop-down menu so that service teams can specify the product (offering, feature, sku) that relates to the meeting. This information is stored in service tree so we should be able to have a pre-populated list for the service team member to select the product based on the service name.

Created issue https://github.com/Azure/azure-sdk-tools/issues/3867

**Comment by maririos** [comment]
The long term goals have been covered with the integration of the Release Planner app and the Scheduler app
