### ISSUE TITLE
Updates to the UI text for Informational Meeting 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#3763]
There are multiple updates required for the UI text for the Informational Meeting.  I can create a GitHub issue for each bolded topic if that is what is desired.  I just wanted to capture everything I have found that needs to be addressed for the UI for the Data Plane Informational Meeting blade. 

**The tile of the meeting is not correct.** 

- As I have explained previously, the meeting scope is for data plane only.  It does not apply to management plane. The tile needs to be changed to Data Plane Informational. 
- The name also needs to be changed on the left side navigation menu to Data Plane Informational.  

**Invalid URL error does not provide descriptive information so that the user understands why the URL is invalid** 

- When the URL that is entered in a field is too long an error appears stating invalid link. This error message needs to be more specific. I tested this yesterday with a valid link and the error message stated invalid link which is not helpful to user in understanding why the link is invalid.  The error message should state "Value to field <name of field> is too long. The max URL character length is <specify the max>. Please shorten URL and resubmit scheduling request."  What are the other reasons why a user would see the invalid error message. We need to have detailed information for each potential error. 

**Descriptive text needs to be associated with the field not at the top of the blade** 

- Remove this text which is not grammatically correct - _NOTE: This meeting documents to be submitted before the meeting starts. Please review the list of requirements [here ](https://aka.ms/azsdk/onboarding/informational)before picking a date. Failure to provide this documentation before the meeting will result in automatic cancellation of this meeting. _
- Instead add hover text or ? by each field that briefly explains the document and provides link to an example. 
- For core concepts indicate that the field are optional - core concepts doc link (optional). Hover text should state "Completion of core concepts is optional for this meeting.  <link to examples>. "
- For hero scenario link indicate that the field is optional - hero scenario link (optional). Hover text should state "Completion of initial hero scenarios is optional for this meeting.  <link to examples>. " 

**Add new field above architecture diagram link for validating that the service has completed Azure SDK onboarding survey.**  

- This is a required pre-requisite for this meeting. 

- Checkbox titled "Completion of Azure SDK Onboarding survey with a <link> (required 48 hours prior to start of the meeting)".  

- Hover or ? link should state "Prior to the data plane informational meeting service teams must complete the Azure SDK Onboarding survey. The survey gathers baseline information so that we can better understand the data plane requirements for the service and/or product". 
- Future:  We need to 
**Change description filed to agenda field because there is a pre-defined agenda for the data plane informational meeting** 

- Change Description Field to Proposed Agenda add pre-populated information that provides agenda and link to the Data Plane Informational wiki page for more details. 

**Add new field so that the user can specify additional topics or questions that they wish to be addressed during the meeting.** 

- Add new field that "Additional Topics" that the service team member can use to add any additional topics or questions they wish to be addressed in the data plane informational meeting.  Hover text or ? text should state "Use this field to indicate additional topics or questions you wish to be addressed in the data plane informational meeting."

**Comment by ladonnaq** [comment]
Opened issues for each topic and will close this issue.

**Comment by ladonnaq** [comment]
Opened issues for each topic mentioned in this issue.  Closing this issue.

**Comment by maririos** [comment]
Thank you :)
