### ISSUE TITLE
The tile of the current Information meeting is not correct 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#3766]
- As I have explained previously, the meeting scope is for data plane only. It does not apply to management plane. The tile needs to be changed to Data Plane Informational.

- The name also needs to be changed on the left side navigation menu to Data Plane Informational.

**Comment by maririos** [comment]
Need to reconsider according to how this will connect with the general reelase process flow and the number of meetings needed

**Comment by maririos** [comment]
This won't be needed anymore. More changes will come once the Intake app gives us more informaiton and it is connected to this specific meeting type
