### ISSUE TITLE
Permission issue in creating apiview

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-tools#3773]
I want to discuss the permission issue in creating apiview in spec PR pipeline.

As the apiview service checks whether PR creator is in Azure/Microsoft organzation, apiview service needs to get PR creator's org information. However, most PR creator's org information is private, and apiview service doesn't allow their spec PR to create apiview by default because apiview service cannot get their org information.

It's not an issue when user create apiview in apiview service UI because the apiview service will induce user to make github account's org information public. However, it's an issue in spec PR pipeline. We want to create apiview automatically in spec PR pipeline, and it will fail if the PR creator doesn't make github account public.

I proposed some solutions here:
1. Add more information in PR comment and let user know where they can make github account's org information public. (We will use this solution now because it's most easy, but I don't think it's friendly for user)
2. If apiview service has a PAT which is in Azure/Microsot organzation, then it can use the PAT to get PR creator's org information. (The PAT should belong to bot account. Is there a way to let bot account join Azure/Microsoft org?)
3. Disable the authorization verification in apiview service when we create apiview in spec pipeline. I don't know what security issue it will have because the apiview is created from spec pipeline, and so I think we can make sure the behaviors is safe. 

@praveenkuttappan @weshaggard @lirenhe Hope you can put your ideas here. Also, please @ more people who can give us some suggestions. Thanks

**Comment by weshaggard** [comment]
@dw511214992 all the folks submitting a spec change should be in the Azure org and if so their account should be public. If that isn't the case then we shouldn't try and create an APIView for them. In which case we can instead just output a message as to why.

**Comment by dw511214992** [comment]
@weshaggard Actually, we already support displaying a  message about it. However, most service teams' github account are set to private by default. So, we cannot create apiview for most PRs by default, which is not friendly, and I'm just thinking whether there is a better way to check their permissions, or whether we can skip permission check when the request is from our pipeline.
thanks

**Comment by lirenhe** [comment]
cc @praveenkuttappan

**Comment by weshaggard** [comment]
What does the message say? Does it tell folks (or link to docs) that tells them they need to make their Azure org public for their account? If not I suspect we might want to have them do that.

>whether we can skip permission check when the request is from our pipeline

I don't think we want to skip this permission check because it potentially opens up a security hole for public PRs.

@praveenkuttappan any thoughts on this?

**Comment by praveenkuttappan** [comment]
> What does the message say? Does it tell folks (or link to docs) that tells them they need to make their Azure org public for their account? If not I suspect we might want to have them do that.
> 
> > whether we can skip permission check when the request is from our pipeline
> 
> I don't think we want to skip this permission check because it potentially opens up a security hole for public PRs.
> 
> @praveenkuttappan any thoughts on this?

We definitely cannot skip permission check which is the only way to ensure this REST API is protected from unauthorized access. Users can login to APIView only if their org info is publicly available. So even if we support an alternate approach for this REST AP, user will still not be able to access the review that get's generated. So that's not a cleaner solution either. 

Can we add a step in pipeline to create a warning and notify them if org info is not available publicly? Currently it is just added as a message if it fails to create API review. right?

**Comment by dw511214992** [comment]
Now, the message will help user know they need to make their org information public. The message is: Create ApiView failed. Please ensure your github account in <a href="https://github.com/orgs/Azure/people">Azure</a>/<a href="https://github.com/orgs/Microsoft/people">Microsoft</a> is public and add a comment "/azp run" to re-trigger the CI.

**Comment by weshaggard** [comment]
Eventually we want to have the pipeline inside of the Azure/azure-rest-api-specs repo to standardize how we do our pipelines but even with that that approach we have some strategies for handling this. Please work with @praveenkuttappan to use a similar approach as we do for our public PRs in the language repos. For now however given that the pipeline is protected we can use the apikey as a secret to call the api.

**Comment by praveenkuttappan** [comment]
This was already fixed as part of the change we did in one of the last releases in January to switch PR owner authentication to Microsoft OSS api instead of verifying GitHub authentication.
