### ISSUE TITLE
Consider pulling full credscan out of service directory pipelines

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#3779]
Since credscan requires a full clone, it can take a long time. I'm not sure if there is any compelling reason to run credscan for each service pipeline, rather than having one repository global pipeline that runs on commit batches to main (e.g. run on each merge, and group together multiple merges that happen before the next run) or on every commit to main.

For PRs, we would still need credscan runs, but it could be done against the directories of changed files with a sparse checkout, which would be faster.

One potential downside would be replacing credscan checks that run for feature branch merges.

**Comment by benbp** [comment]
Nvm. Closing because I realized we still need PR checks.

**Comment by benbp** [comment]
CC @scbedd

**Comment by kurtzeborn** [comment]
Since this was opened, we've since optimized credscan in PR validation to only scan edited files.  The nightly runs still scan the full service folder, but that doesn't add much time to the nightly runs anyway.
