### ISSUE TITLE
[API View] For a GA'd library, all new API views of that library should include a revision that points to the last released version

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-tools#3781]
For a library that has a GA version released, all new API views created for that library (manual/PR/auto) should include a revision that points to the latest released version. This helps to see the diff between the current API with the last released version.

**Comment by mikekistler** [comment]
This should already be the case for automatic reviews -- these have all the revisions that have GAed.  So this would only apply to manual and PR reviews.

**Comment by WhitShake** [comment]
Completed as part of new UI redesign
