### ISSUE TITLE
Data Plane follow-up informational meeting type option added to the Informational Meeting

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#3785]
Use case:  Service partners who need a follow-up informational meeting for data plane can schedule the meeting via the scheduling tool as a meeting type for the informational meeting.  

Requirement: 

1.  Add drop-down box with 2 meeting types for Informational.   Informational meeting, follow-up data plane.  See suggested UI changes in the last comment I made on the issue. 
2. Trigger, check the Azure Devops work item to see if the service team has completed an informational meeting.  If they have then show the meeting type drop-down box. See screenshot below.  

![Image](https://user-images.githubusercontent.com/67656762/204918661-aa5a1d4f-121b-4ed5-81da-7367a3d1cbfc.png)

4. If the meeting type is follow-up data plane, then this is the wiki page with the information for the meeting.  https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/663/Azure-SDK-Informational-Meeting-Data-Plane-Follow-Up

**Comment by maririos** [comment]
@ladonnaq could you include this asks in the mock interface you are working on?

**Comment by josefree** [comment]
I wonder this requirement is fulfilled.  Currently, the information meeting is promoted after the Onboard survey.

**Comment by ladonnaq** [comment]
@maririos This would be follow-up from the first informational meeting that is for data plane only.  What I would like to see is a drop-down box similar to what is in the SDK Review.  I will edit the first entry on the GitHub issue so that the requirement is clearer. 



![Image](https://user-images.githubusercontent.com/67656762/204917205-80a72015-3d33-4fd0-873c-b4abe7efa98d.png)

I suggested that we put box right after the product drop-down box.  



![Image](https://user-images.githubusercontent.com/67656762/204917660-3f9b2c62-a45e-47bc-9672-3736fe4339db.png)

**Comment by maririos** [comment]
Ohh interesting. So you want to have a type of meeting too!
What will be the values? `Introduction` and `Data Plane Follow up`? What else should change accordingly?

**Comment by josefree** [comment]
I recategorize the issue to 'Design'

**Comment by ladonnaq** [comment]
@mario-guerra What other information do you need to enable this feature? I would like for teams that have already met for an onboarding Azure SDK informational and are in scope for data plane to select this option.  The agenda is different for this meeting type - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/663/Azure-SDK-Informational-Meeting-Data-Plane-Follow-Up.  Any ideas on how best to identify the trigger for this meeting?  Would data plane scope = yes and Info meeting state = complete be good indicators?

**Comment by maririos** [comment]
@ladonnaq To clarify:
- The prerequisites between an informational meeting and a Data plane follow up are the same right? So no need to change the UI there.
- The major change is when a calendar invite is sent, to include the correct information about what to expect of the meeting (agenda), right?

If so, I believe it will be better not to ask the user to select the meeting type, but instead the tool to calculate it according to the information in the ADO item like you suggested (data scope = yes and Info meeting state = completed).

The tool does have a link to the wiki which currently points to informational so we could either update the wiki and say hey if you already met with us and you are in scope see here for your meeting information (better worded).

**Comment by maririos** [comment]
Email template changes (from issue)
- Meeting title: Azure SDK information meeting: data plane follow-up
- Content: Use https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/663/Azure-SDK-Informational-Meeting-Data-Plane-Follow-Up

**Comment by maririos** [comment]
We need 2 ways to identify this:
- Directly from our app.
  - When a product is selected, we need to look at the ADO item and according to `(data scope = yes and Info meeting state = completed)` provide the Data plane information
- From the Release Planner App.

In both cases the prerequisites are:
- Arch diagram (required)
- Specs PR link
- Core concepts
- Hero scenario

Note that the wiki link is also different.

**Comment by maririos** [comment]
As part of this work, see how to add the ADO workitem link

**Comment by maririos** [comment]
Tables affected:
- Reference Documents
  - New column: Informational Meeting - DP Wiki Link

**Comment by maririos** [comment]
Flows that we are reusing from the Release Planner Solution:
- `Get Work Item Details`
- `Get Work Item Details Child`

We need to make sure that the connection reference works too

**Comment by maririos** [comment]
Change implemented
