### ISSUE TITLE
Updates to the Body of Data Plane Information Meeting 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#3788]
**This is the current body of the Data plane informational meeting:**  

Hello (name of who scheduled meeting) 

Thanks for Scheduling this informational session.

Please remember that you'll need to provide the meeting requirements documents as explained in this link:
 
Please submit within 48 hours of the meeting start date\time.

Kindly note that this meeting will be cancelled if you don't provide it by that time.

If you have any questions. Contact [azsdkinfoboard@microsoft.com](mailto:azsdkinfoboard@microsoft.com)
 
This meeting can be updated only through the scheduling app [here](https://web.powerapps.com/apps/946a86a6-c21b-4f52-a931-f74a51c6a332?view=edit&event=53746be6-270d-ed11-82e5-000d3a5936cd).
 
A [GitHub Issue](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk-pr%2Fissues%2F810&data=05%7C01%7Cladonnaquinn%40microsoft.com%7C435a90582a684e81536d08da6f4c6e4d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637944671298417165%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5iMn477f0tPLuJrgcszs7K4DgIjCQuy0PIYkqmK%2FtFQ%3D&reserved=0) has been created to track actions items and comments for this meeting.

**Requirement: Here is what should be in the body of the calendar invite.** 

Thanks for Scheduling this data plane informational meeting.  Please complete the pre-requisites below 48 hours prior to the day/time of the scheduled meeting. 

### **Pre-Requisites**
1.	  If you have not submitted an [Azure SDK onboarding survey](https://aka.ms/sdk-apex) for your service and/or product, please do so 48 hours before the meeting.
2. The information collected in the Azure SDK onboarding survey will help: 

- Document scope of work

- Determine next steps in engaging and partnering with our team 

- Identify planning requirements and APEX (PLR) timelines

3.	 If you did not include a link to a service high level architecture in the Azure SDK Onboarding survey, please send a link to [azuresdkintake@microsoft.com](mailto:azuresdkintake@microsoft.com) 48 hours before the meeting. 

### What to expect during the data plane informational meeting 

**Note: Topics are adjusted based on relevance.** 

| Topic | Description| 
| ------------- |:-------------:| 
|Process walkthrough | Discuss and determine the appropriate SDK workflow. The team will be introduced to the [data plane and [SDK creation workflow](https://aka.ms/azsdk/dpcodegen). and review [Onboarding scenarios](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/539/Onboarding-Scenarios). |
|Launch Readiness | Review [Azure SDK launch criteria](https://aka.ms/azsdk/apex/launch-criteria), discuss timelines and expectations.|
|Rest API Stewardship review preparation | Help the service team prepare for the [Rest API stewardship review](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/665/Azure-Rest-API-Stewardship-Review).|

Additional topics requested by (name of person who scheduled the meeting): 
(list any additional topics that were requested when the meeting was scheduled) 

 Contact us by posting a question to our [teams channel](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db4) or sending an email to [azuresdkintake@microsoft.com](mailto:azuresdkintake@microsoft.com).

**Requirement: An email should also be sent that contains the following information:** 

Today I am using bookings.  There is an email sent as well as the calendar invite.  The body of the email contains the following data: 

- Data plane informational meeting has been scheduled for (name of service)
- Date and Time and who the meeting is scheduled with (in this case Azure SDK Onboarding team)
- Reminder to complete pre-requisites 48 hours prior to start of the scheduled meeting or the meeting will be cancelled. 
- Link to the team's meeting
- The table in the What to expect during the data plane informational meeting calendar invite (above)
- Contact information (same as above in the calendar invite) 

This email should be sent at the same time that the calendar invite is sent. 

**Requirement: Reminder email sent 7 days and 2 days before the scheduled meeting** 

- This is a reminder that a data plane informational meeting has been scheduled for (name of service).
- Date and Time and who the meeting is scheduled with (in this case Azure SDK Onboarding team)
- Reminder to complete pre-requisites 48 hours prior to start of the scheduled meeting or the meeting will be cancelled.

**Comment by maririos** [comment]
> Requirement: An email should also be sent that contains the following information:

Created issue Requirement: Reminder email sent 7 days and 2 days before the scheduled meeting

> Requirement: Reminder email sent 7 days and 2 days before the scheduled meeting

Created issue https://github.com/Azure/azure-sdk-tools/issues/3865

**Comment by maririos** [comment]
I opened specific issues for the Reminders and email features. That way we are leaving this issue to only be for updating the content of the current meeting body

**Comment by maririos** [comment]
@ladonnaq is going to provide the email template.
We will no longer have Github issues created for the Informational meetings

**Comment by ladonnaq** [comment]
### _**Requirement: Meeting title = Azure SDK information meeting: data plane follow-up + product name**_
### _**Requirement: Azure SDK Informational Meeting: data plane follow-up - body of the calendar invite**_

Thanks for scheduling an Azure SDK informational meeting: data plane follow-up. 

This meeting can be updated only through the scheduling app [here](https://aka.ms/azsdk/scheduleinformational).

Please complete the pre-requisites below 48 hours prior to the day/time of the scheduled meeting.  

### **Pre-Requisites**
1. If you have not submitted an Azure SDK Onboarding Questionnaire (link to the Azure SDK Release Planner Beta 1), please complete for your service and/or product, please do so 48 hours before the meeting.
2. If the product is a new offering or sku and you did not include a link to the high-level architecture (showing management and data plane) when scheduling this meeting, please update the scheduled meeting with the link (link to the scheduled meeting). 

### What to expect during the data plane informational meeting.
The information collected in the Azure SDK onboarding survey will help: 
- Document the API/SDK scope

- Determine next steps in engaging and partnering with our team 

- Identify planning requirements and APEX launch readiness timelines


**Note: Topics are adjusted based on relevance.** 

| Topic | Description| 
| ------------- |:-------------:| 
|Process walkthrough | Discuss and determine the appropriate SDK workflow. The team will be introduced to the [data plane and [SDK creation workflow](https://aka.ms/azsdk/dpcodegen). and review [Onboarding scenarios](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/539/Onboarding-Scenarios). |
|Launch Readiness | Review [Azure SDK launch criteria](https://aka.ms/azsdk/apex/launch-criteria), discuss timelines and expectations.|
|Rest API Stewardship review preparation | Help the service team prepare for the [Rest API stewardship review](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/665/Azure-Rest-API-Stewardship-Review).|

Additional topics requested by (name of person who scheduled the meeting): 
(list any additional topics that were requested when the meeting was scheduled) 

 Contact us by posting a question to our [teams channel](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db4) or sending email to azsdkapex@microsoft.com.


**Requirement: Reminder email sent 7 days and 2 days before the scheduled meeting** 

- This is a reminder that a data plane informational meeting has been scheduled for (name of service).
- Date and Time and who the meeting is scheduled with (in this case Azure SDK Onboarding team)
- Reminder to complete pre-requisites have not been completed and links to request they are completed prior to the meeting. 
- Contact information (same as the info in the body of the meeting invite).

**Comment by ladonnaq** [comment]
@maririos - I will create another issue for the default information meeting.  This is for the alternative flow (data plane follow-up).

**Comment by maririos** [comment]
> Requirement: Meeting title = Azure SDK information meeting: data plane follow-up + product name

We have been using the format `[Service name - subservice/product name] - Azure SDK Information meeting: data plane follow - up` for the REST and SDK meetings, will you liek this format too?

Also, I added `<Service name - Product name` do you prefer only the product name?

**Comment by ladonnaq** [comment]
I prefer product name because that maps to the release plan and that is what the teams will be looking to get signed off - the APEX launch criteria for the product.   

I think we can an option so that a team can choose data plane follow as an information meeting type.  The template in this GitHub issue is the data plane follow-up.  I will review it and create 2 more GitHub issues for the other templates (management plane follow-up and data + management plane follow-up).  



![Image](https://user-images.githubusercontent.com/67656762/202577102-a6d3f147-8f97-42d0-a815-81609c23c3ca.png)

**Comment by maririos** [comment]
I worry that by asking the service team to select the type of meeting, we are confusing them more instead of us doing it according to the information they provided.
Also, do the templates need to change that much? Do we really need to divide things that much? or can we try to unify them even more so the service has a more unified experience?

**Comment by maririos** [comment]
Changes will be covered in issue https://github.com/Azure/azure-sdk-tools/issues/3785
