### ISSUE TITLE
APIView reference docs have too much padding on first line

### ISSUE THREAD

**Issue by cmcd22** [Azure/azure-sdk-tools#3804]
When showing documentation/reference text in APIView, regardless of the language, there is too much padding on the first line of every text section, resulting in the appearance of a new line/buffer zone between the first and second lines
<img width="770" alt="Screen Shot 2022-08-02 at 11 07 15 AM" src="https://user-images.githubusercontent.com/87786853/182260304-29abea36-3e7c-4d80-9483-6dffaf8df822.png">
![unknown](https://user-images.githubusercontent.com/87786853/182260321-22c0c08a-ebd3-4b7a-97fd-53ce470e0918.png)
.

**Comment by JonathanGiles** [comment]
If you inspect the first line and compare it to subsequent lines, the generated HTML is slightly different:
![image](https://user-images.githubusercontent.com/1427840/182491051-75f2956a-f238-4468-9e49-353cdfe8ab1b.png)

If you edit the code-inner of the first line to change the white-space setting, it renders correctly:
![image](https://user-images.githubusercontent.com/1427840/182492089-fb4a3094-ebf1-4fb2-9322-8810363daec6.png)

**Comment by chidozieononiwu** [comment]
It looks like this issue has been resolved from what I can see.
![DocumentationPadding](https://user-images.githubusercontent.com/31145988/191379997-5aca612f-bb5e-42cc-b947-b4e5676a466c.png)

**Comment by JonathanGiles** [comment]
I agree - I can not seeing it in staging (but I can see it in production). The Massey students will look into this further to ensure that it remains fixed.

**Comment by mikekistler** [comment]
@JonathanGiles Can you please check production again. We believe this is fixed and can be closed,
