### ISSUE TITLE
Create Python ApiView Failed (Service returns 524)

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-tools#3812]
Details of Request and Response: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1747576&view=logs&j=45089dbe-f1df-5d30-406b-2e88e9255691&t=063ef311-1ede-507d-1131-e2857163b226&l=55

After discussed with @praveenkuttappan , it's caused by costing much time to create python apiview. We need to figure out why it takes so much time.

**Comment by dw511214992** [comment]
find a new one which has the same issue: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1754201&view=logs&j=45089dbe-f1df-5d30-406b-2e88e9255691&t=063ef311-1ede-507d-1131-e2857163b226

**Comment by mikekistler** [comment]
This will be fixed when Sandboxing is implemented for manual reviews.

**Comment by praveenkuttappan** [comment]
This is no longer an issue since Python API reviews are generated on pipeline side instead of parsing within APIView.
