### ISSUE TITLE
Create AAD group for Admin app

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3815]
Because of the sensitivity of the Admin app, we need to make sure that only selected people have access to the Admin app.
We should follow the pattern that has been used so far.
See https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/728/Scheduler-Experience-App?anchor=permissions for more information.

**Comment by JonathanCrd** [comment]
A new ADD group has been created, next step is to add that group to the appropriate security roles in PowerApps. Internal wiki got updated as well.

Not closing this issue until the right security roles are assign to that AAD group.
