### ISSUE TITLE
[Test-Proxy] TLS validation cert setup not working in Python with Docker

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-tools#3819]
When using the test proxy's recording options API, requests coming from Python aren't able to set a TLS validation certificate when using the test proxy via Docker. This issue was raised by Confidential Ledger, which has a test that tries to set a certificate that's fetched from the service: [test code](https://github.com/lynshi/azure-sdk-for-python/blob/1f05d6803812c49a67b02f630bb7003a4776f720/sdk/confidentialledger/azure-confidentialledger/tests/test_confidential_ledger_client.py#L34).

The same error is raised when using a [PEM certificate](https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/Test.Certificates/test_public-key-only_pem) that's used for test proxy tests, though this certificate is known to be problematic on Linux.

An example of error response (which is raised when certificate newlines are removed or not):
```
'Unable to instantiate a valid cert from the value provided in Transport settings key "TLSValidationCert".
Value: "-----BEGIN CERTIFICATE-----MIIBe[redacted]MZFq+9-----END CERTIFICATE-----".
Message: "ASN1 corrupted data.".'
```

When the "-----BEGIN/END CERTIFICATE-----" delimiters are removed, the error's `Message` is "No PEM encoded data found." instead.

This has been observed when using the Docker test proxy tool on WSL Ubuntu and Windows 11.

**Comment by scbedd** [comment]
Thank you for filing the issue! You're the first folks to try these features against docker. I'm certain that if JS had been the first they would have also encountered this.

When debugging locally on a windows machine, the recording option sets just fine. Anecdotally, these operations also succeed in CI for azure-sdk-for net, which _absolutely_ runs on a linux machine.

This makes me think the failure is specific to the docker image, but I will be digging into this today.
