### ISSUE TITLE
Add text to meeting invite area recommending people to attend...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3820]
There should be additional guidance regarding who should attend an API review meeting.
"It is recommended that the PM, Eng Lead, and service Architect attend the API review session"
![Azure SDK Team Scheduler Rest Review - Power Apps 2022-08-02 17-25-21](https://user-images.githubusercontent.com/522116/182476635-3301e86d-e466-456e-bda0-f1f960fb4dc9.png)

**Comment by maririos** [comment]
PM and Eng Lead added in issue https://github.com/Azure/azure-sdk-tools/issues/3677.

We need to add Service Architect

**Comment by JonathanCrd** [comment]
Fixed
