### ISSUE TITLE
[Stress test]  Link broken

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-tools#3824]
https://github.com/Azure/azure-sdk-tools/blob/main/tools/stress-cluster/chaos/README.md#chaos-manifest

Chaos experiments here is broken 

I think it should be directed here now: https://chaos-mesh.org/docs/simulate-pod-chaos-on-kubernetes/

**Comment by benbp** [comment]
Thanks for filing this! @l0lawrence the correct link is actually https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/ not the link to pod chaos, in case you need to refer to it. I'll have a PR up shortly.

**Comment by l0lawrence** [comment]
> Thanks for filing this! @l0lawrence the correct link is actually https://chaos-mesh.org/docs/simulate-network-chaos-on-kubernetes/ not the link to pod chaos, in case you need to refer to it. I'll have a PR up shortly.

Thanks Ben!
