### ISSUE TITLE
Enable the admin to cancel the meeting with a reason, e.g. no PR supplied

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3834]
Requested from REST meetings. Do we want this everywhere else?

**Comment by JonathanCrd** [comment]
This seems to be related to:
- https://github.com/Azure/azure-sdk-tools/issues/4237
and
- https://github.com/Azure/azure-sdk-tools/issues/3857

Adding those issues for context. 
We could add a special textboxt to modify the default message `Cancelled by <person>` that we use right now.
