### ISSUE TITLE
[Bug-Java] Nested interface is not shown.

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-tools#384]
The nested interface is not shown here, but it should be shown because it is an interface defined in an interface. Anything in an interface is public by default.

For example, https://apiview.dev/Assemblies/Review/bc9e446581a4475ca4df0a011c152da7
The Azure search API view doesn't show the inner nested interface [BuilderDefinition](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/cosmos/microsoft-azure-cosmos/src/main/java/com/azure/data/cosmos/ChangeFeedProcessor.java#L79) within the public interface ChangeFeedProcessor.

**Comment by JonathanGiles** [comment]
@mssfang You need to provide more context in this bug report so that you and others know what you're referring to.

**Comment by JonathanGiles** [comment]
I have fixed this issue in #388
