### ISSUE TITLE
[Python APIView] Inherited methods filtered out depending on platform used to generate APIView

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#3849]
There is logic in APIView when deciding whether to display inherited methods as part of a class. This logic omits inherited methods that are not part of the target namespace (for example, something inherited from `azure.core`). 

However the namespace that inspect sees for these methods differs depending on whether the APIView is generated on Windows or Linux. For example:
https://apiview.dev/Assemblies/Review/453e3478565f4bdfb4df7e8ca9b53ba9?diffRevisionId=a0ca9d65fc02403da0162ba27a7dd08a&doc=False&diffOnly=True&revisionId=53ff99d839df4d81bccc62f9d870adca

Here, Windows sees that `add_done_callback` is part of `azure.core.polling` and thus omits it. Linux sees this as part of the root namespace and thus includes it. 

cc/ @kristapratico

**Comment by mikekistler** [comment]
Will be fixed when sandboxing restricts platform to be Ubuntu.

**Comment by praveenkuttappan** [comment]
This should no longer be an issue. Python API review gets generated only on Devops pipeline.
