### ISSUE TITLE
Can not subscribe to apiview.dev reviews in Chrome

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-tools#385]
Both @srnagar and I cannot subscribe to reviews in Chrome. He is on Windows and I am on MacOS. We were both able to subscribe when we loaded the same review in Edge (Chromium).

On my machine, the 'subscribe' button is visible but not clickable. The mouse cursor does not change and clicking on the button has no effect.

**Comment by JonathanGiles** [comment]
It looks like it might be because my chrome OAuth doesn't have any scopes, whereas the Edge OAuth has the user:email scope.

**Comment by pakrym** [comment]
Does logout-login help?

**Comment by srnagar** [comment]
My system rebooted and I tried on Chrome and I was able to `subscribe`. Seems like a new browser session will fix this issue. If @JonathanGiles can also confirm, we can close this issue.

**Comment by JonathanGiles** [comment]
Agreed - new browser session and logout / login helped to resolve the issue.
