### ISSUE TITLE
Add ability to see all meetings that have been scheduled

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3857]
It doesn't have to be separated by meeting type.
Is this something we want only for Admin people? or open to everyone? I can see benefits on both so we will need to check.

How to show this? as a calendar view? or as a list?

**Comment by JonathanCrd** [comment]
For this, as a first step, I'm going to create a new view in the Admin app, and for this current release (beta.7) just display them and maybe have a button to go to the corresponding app with the app ID.

**Comment by JonathanCrd** [comment]
I implemented a new screen in the Admin App to monitor all upcoming meetings. To achieve this, I created a new View in the `Events` table that filters out meetings that are `In Progress` and whose dates are in the next 365 days. Then I use that view into a component with a gallery to display the information. From this new screen, admins can open the GitHub issues for the reviews or the full details in the corresponding scheduler app.
