### ISSUE TITLE
Sub area or sub service should be fed from Dataverse

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3867]
Cotnext comes from https://github.com/Azure/azure-sdk-tools/issues/3762 where it is explained how subservice can be obtained from CLC or Service Tree.
Should there be a dropbdown for subarea that is independent from sub product? In which specific cases is sub area needed?

**Comment by maririos** [comment]
Is this something that has been considered in the other PowerApps?

**Comment by maririos** [comment]
Note: 
From a service perspective, they are responsible for each particular release. But there could be some features or offerings that are grouped in the same SDK.

**Comment by maririos** [comment]
@praveenkuttappan  FYI

**Comment by ladonnaq** [comment]
We need to figure out how we map the APEX products to the service and subarea.  The release plans will be mapped to a product, not a service.  So we need to make sure that we have service and subarea data fields for the product data tables and Azure Devops work item (there is a field for service already, I can add subarea.  Sometimes subarea will map to the APEX product but other times it will not.

**Comment by maririos** [comment]
This is how I see it. If we follow Service Tree,:

- Service name: Key Vault
- Product: Key Vault
- Subservice: Secrets (this is not in Service Tree but it is how the SDKs are partitioned)

With this it looks like:

- Informational meetings should have Service name and Product name
- API meetings: Service name and Product name
- SDK meetings: Service name, product name, and subservice

**Comment by maririos** [comment]
So subservice shouldn't come from service tree, and it is only for SDK meetings when needed.

Across all of our Release process, the way to identify a relationship with partner team is with Service name & Product name (maybe something with release date or version or something else I am missing)

**Comment by josefree** [comment]
I put on target milestone to be '2023-1', and add a label 'needs-triage'

**Comment by maririos** [comment]
@josefree I am thinking if maybe we should try this first in the Scheduler tool, get feedback and according to that make changes to the Release Planner app... what do you think?

**Comment by maririos** [comment]
Action items from this issue:
- Add product field to Informational meeting: https://github.com/Azure/azure-sdk-tools/issues/4682
- Add Product field and remove sub-service to API meeting: https://github.com/Azure/azure-sdk-tools/issues/4926
- Add Product field to SDK meeting: https://github.com/Azure/azure-sdk-tools/issues/4927

For now all work is in scheduler tool and has been individually tagged so we can close this issue
