### ISSUE TITLE
When editing a API Review meeting, what is the expected behavior for changing the API PR?

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#3869]
For the particular scenario in which a user is editing a meeting that already has a PR specified:

- Are we going to allow users to change the PR number on the same repo?
- Are we going to allow users to change the PR completely, even change the repo in which the PR number is?
  - If so, what should happen to the tracking issue? (The tracking issue was created on the repo that the PR was when the meeting got created)
- Should we allow the users to delete the PR link?

When scheduling a meeting for the first time, if the user does not specify a PR repo nor number:

- Should we ask the users to specify if the API is public or private?
- Is there a default repo we should use for these scenarios?

When editing a meeting that has no PR repo and number specified yet:
- Will the user be limited to specify the PR number only for the repo in which the tracking issue is? I mean, not allow the user to specify the repo, just the PR number.

**Comment by maririos** [comment]
>When scheduling a meeting for the first time, if the user does not specify a PR repo nor number:
  Should we ask the users to specify if the API is public or private?
  Is there a default repo we should use for these scenarios?

We already ask the user which repo, and we show as first option the public repo.

> When editing a meeting that has no PR repo and number specified yet:
  Will the user be limited to specify the PR number only for the repo in which the tracking issue is? I mean, not allow the user to specify the repo, just the PR number.

Yes.

**Comment by maririos** [comment]
> For the particular scenario in which a user is editing a meeting that already has a PR specified:

If a user wants to update the PR, we will let them. In our record we won't delete it or override it. We will add a new entry for it and update the GH issue with this new link. We will also link it to the Pull Request field

**Comment by maririos** [comment]
@JonathanCrd let me know if there are still questions for the design here that I didn't cover

**Comment by maririos** [comment]
@JonathanCrd I confirmed that this is what we want: 
>If a user wants to update the PR, we will let them. In our record we won't delete it or override it. We will add a new entry for it and update the GH issue with this new link. We will also link it to the Pull Request field

**Comment by JonathanCrd** [comment]
Are we expected to show the old PRs somewhere in the app?

**Comment by maririos** [comment]
> Are we expected to show the old PRs somewhere in the app?

Maybe? how will this change the design?

**Comment by JonathanCrd** [comment]
> > Are we expected to show the old PRs somewhere in the app?
> 
> Maybe? how will this change the design?

It won't change the design at all, I wanted to know if I needed to add a new gallery to display the old ones as part of this issue.

**Comment by maririos** [comment]
> I wanted to know if I had to add a new gallery to display the old ones as part of this issue.

Got it. No new gallery needed to show history
