### ISSUE TITLE
PPE links for scheduler app not published correctly as they are redirecting to Dev env

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3871]
Following the wiki, when clicking on Scheduler app for PPE, it takes me to the informational meeting.
Once there, if I click in any of the links of the left menu, i.e. Home, it takes me to the DEV instance app.
This is true for any link.

@live1206 looks like there is something wrong with the deployment from Dev -> PPE.

Note that this is not true for PPE -> PROD

FYI @praveenkuttappan

**Comment by live1206** [comment]
@maririos Yes, there is something wrong about the environment variable settings during the deployment: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1582977
I am close to a fix now.

**Comment by live1206** [comment]
Works now

**Comment by maririos** [comment]
Thank you!
