### ISSUE TITLE
SDK azure-sdk-for-net-track2 check failing due to existing code.

### ISSUE THREAD

**Issue by pansharm-ms** [Azure/azure-sdk-tools#3877]
I have created a PR in the azure api specs repository: [20142](https://github.com/Azure/azure-rest-api-specs/pull/20142)
One check is failing in this PR: [SDK azure-sdk-for-net-track2](https://github.com/Azure/azure-rest-api-specs/pull/20142/checks?check_run_id=7716340268)
This check is not related to the code changed in PR but is failing due to existing code in repository.
Can you please resolve this issue.

**Comment by raych1** [comment]
@pansharm-ms , please resolve the branch conflicts then re-run the check with /azp run.

**Comment by raych1** [comment]
I close this issue as there's no response.  Feel free to re-open it.
