### ISSUE TITLE
[API Review] Disable Follow Up button from past meetings

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#3879]
We need to define what is the user path for scheduling a follow up with all of the possible scenarios.

For now, we should disable (or hide) the `Schedule a Follow Up` button from past meetings in the **API Review** view.

**Comment by praveenkuttappan** [comment]
This has been completed. We have made schedule follow up button as hidden always

**Comment by ladonnaq** [comment]
I opened a GitHub issue to identify if the service partner + product have already completed an initial API review.  Once that is enabled you can set the default to Schedule an API Review follow-up. https://github.com/Azure/azure-sdk-tools/issues/4694

**Comment by maririos** [comment]
I am hesitant to enable the `Follow-up` UI again. I will prefer to edit current one and avoid having the user to select more things.
If #4694 turns out to be insuficient, then we can consider opening this issue again
