### ISSUE TITLE
Links in Breaking Change PR report don't resolve to line

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3886]
The links shown for a problem in the Breaking Change report don't resolve to the affected line because they include a column.

For example, in [PR #19558](https://github.com/Azure/azure-rest-api-specs/pull/19558/checks?check_run_id=7737524252), the Breaking Change report includes this entry:

<img width="736" alt="image" src="https://user-images.githubusercontent.com/85643503/183560912-ebadd43c-b00e-4031-a9e1-403cd6438741.png">

When clicking on either the old or new link, the user is taken to the top of the file. To get to the specific line, the user must edit the url to remove the column position (the ":" and the number after it).

This occurs for me in the Chrome browser -- I have not tested in other browsers.

**Comment by jianyexi** [comment]
It works in my edge browser
