### ISSUE TITLE
Breaking Changes PR check not flagging type change as breaking

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3893]
The Breaking Changes PR check in the azure-rest-api-specs repo is failing to flag a type change as breaking and requiring a Breaking Change review.

REST API PR: https://github.com/Azure/azure-rest-api-specs/pull/19468

The [Breaking Changes-Cross Version PR check](https://github.com/Azure/azure-rest-api-specs/pull/19468/checks?check_run_id=6997934677) issued these two warnings for change of type:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/85643503/183765829-0f5256f7-fd5d-4e5f-b3c7-4928a5c7bdfe.png">

Here is one of the changes:

https://github.com/Azure/azure-rest-api-specs/commit/ed2c211f02777ea940b14465c43acd45e6ea8de1

<img width="899" alt="image" src="https://user-images.githubusercontent.com/85643503/183765919-64082ddc-1b0c-46bf-89c2-75b96452d63a.png">

According to the Azure Versioning and Breaking Change Policy, Table 3 (Changes requiring a review with Azure’s breaking Change Review Board), this should be reported as an error and require review/approval by the Azure Breaking Changes review board before the PR can be merged.

<img width="456" alt="image" src="https://user-images.githubusercontent.com/85643503/183765977-fc24368f-773f-415d-a3b1-3a435806af4d.png">

cc: @JeffreyRichter @srmantha

**Comment by mikekistler** [comment]
@akning-ms Please give this top priority as it is allowing breaking changes to evade review and impact customers.

**Comment by akning-ms** [comment]
@jianyexi to triage the issue

**Comment by jianyexi** [comment]
I think it's because currently there are a lot of object schema which doesn't contain the 'type:object' , autorest team want to differentiate the schema with or without 'type:object' and we have a lint rule to force them the add it.  But fixing it will cause a breaking change false alarm, so we flag this rule as waring temporary, as SDK breaking change can detect as well

**Comment by mikekistler** [comment]
Can we special-case adding `type: object` -- make that a warning -- but return to reporting a _change_ of type to be an error?

**Comment by jianyexi** [comment]
> Can we special-case adding `type: object` -- make that a warning -- but return to reporting a _change_ of type to be an error?
 But if we honor the autorest/OAS2 semantic, then adding 'type: object' is an 'error', so we don't need to do any change on the current implementation ,we just need to change it back to 'error' in the configuration without any code change

**Comment by mikekistler** [comment]
Are you suggesting that autorest does something different when a schema has `type: object` vs when it does not?  I know that _technically_ these are different, as discussed in [this issue](https://github.com/Azure/openapi-diff/issues/208). Maybe even more specifically -- if a schema has "properties", does autorest behavior change if `type: object` is added? If not then I think a warning is sufficient for this special case.

**Comment by jianyexi** [comment]
> if a schema has "properties", does autorest behavior change if type: object is added?

yes, actually it's motivation that autorest want to add the linting rule , after adding 'type:object' , the model would be a object, but if without 'type:object' it would be an any type

**Comment by mikekistler** [comment]
@jianyexi But I really don't think the code generated by autorest changes when `type: object` is added.

I just tested this with the appconfiguration service in the dotnet mgmt SDK ([link to test branch](https://github.com/mikekistler/azure-sdk-for-net/tree/mdk-test)). In my test, I removed `type: object` from many of the schemas that also have `properties` (commit [b1f253d](https://github.com/mikekistler/azure-rest-api-specs/commit/b1f253d70547f975650612226919c73da808b015)). Then I updated the autorest.md to point to this version and regenerated the client library.  The regeneration threw a bunch of warning messages like:
```
      - https://github.com/mikekistler/azure-rest-api-specs/blob/b1f253d70547f975650612226919c73da808b015/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration/preview/2021-10-01-preview/appconfiguration.json:1203:5
  warning | PreCheck/SchemaMissingType | The schema 'ConfigurationStoreProperties' with an undefined type and declared properties is a bit ambiguous. This has been auto-corrected to 'type:object'
      - https://github.com/mikekistler/azure-rest-api-specs/blob/b1f253d70547f975650612226919c73da808b015/specification/appconfiguration/resource-manager/Microsoft.AppConfiguration/preview/2021-10-01-preview/appconfiguration.json:1251:5
  warning | PreCheck/SchemaMissingType | The schema 'ConfigurationStoreUpdateParameters' with an undefined type and declared properties is a bit ambiguous. This has been auto-corrected to 'type:object'
```

but there was _no change_ to the actual generated code (see the branch I pushed [here](https://github.com/mikekistler/azure-sdk-for-net/tree/mdk-test)).

Is there some other language or perhaps dotnet dataplane that _does_ generate different code based on whether `type: object` is present or absent in a schema that has defined `properties`?

**Comment by jianyexi** [comment]
I think it has no change today is because of below flag in the M4 ,https://github.com/Azure/autorest/tree/main/packages/extensions/modelerfour
![image](https://user-images.githubusercontent.com/59603451/184567427-298f5aa3-a0da-4433-8102-c992562a55f4.png)

**Comment by mikekistler** [comment]
Perfect. So please treat this as a special case -- adding `type: object` next to `properties` is only a warning -- and all other additions or changes of `type` are error. We need this fix ASAP.
