### ISSUE TITLE
azureapirbcore@microsoft.com not added to API Reviews

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3896]
hi folks! ok... i've had a couple of teams use the scheduling app and think i've discovered a problem.

Jorge mentioned that he scheduled a meeting and no one from the review board showed up. He sent me the calendar invite.

Phani also just scheduled a meeting.

I noticed with both of these that the azureapirbcore@microsoft.com is NOT on either of these invites.

In the admin console for the scheduling app--the [azureapirbcore@microsoft.com](mailto:azureapirbcore@microsoft.com) IS a REQUIRED reviewer. So not sure why this isn't showing up.

Here are the screen shots....

![MicrosoftTeams-image](https://user-images.githubusercontent.com/522116/183993714-502aba77-df30-487a-a4b0-e2792cde81dc.png)
![Azure SDKs Admin App - Power Apps 2022-08-10 14-37-34](https://user-images.githubusercontent.com/522116/183993716-1d3a9bca-5955-4ec3-ba81-ecf17d24a2c1.png)
![API Review -Microsoft Purview • Calendar • markweitzel@microsoft com 2022-08-10 14-37-58](https://user-images.githubusercontent.com/522116/183993719-c4eed706-9126-4452-8116-34891369aa43.png)

**Comment by JonathanCrd** [comment]
Fixed, read permission was lacking for the Event Reviewers table
