### ISSUE TITLE
C# API View specific: Add the ability to hide EditorBrowsable(Never) APIs

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#3900]
It would be good if we had an option (probably enabled by default) to hide APIs with EditorBrowsable(Never) attribute.

**Comment by maririos** [comment]
FYI @JoshLove-msft that @KrzysztofCwalina  has asked for this issue 3 times. I modified the priority and added in the `Requested by` field that it was an architect.

This should mostly be in the parser. If there is extra support needed from EngSys team, let us know

**Comment by JoshLove-msft** [comment]
It looks like there is already support for marking tokens as deprecated that was added for Java in https://github.com/Azure/azure-sdk-tools/pull/958/files. I'd suggest we reuse this pattern to mark members with EditorBrowsable as deprecated. The effect is that the APIs are struck through. We can then expand the feature to include a toggle that to hide the deprecated elements entirely.

**Comment by KrzysztofCwalina** [comment]
>  @KrzysztofCwalina has asked for this issue 3 times.

Really? If yes, I apologize. I have totally forgotten that I asked for this.

**Comment by maririos** [comment]
> Really? If yes, I apologize. I have totally forgotten that I asked for this.

No worries. It means it is important and you really want it done :)

**Comment by JoshLove-msft** [comment]
I agree this will be a good feature to add - I'm looking into it.
