### ISSUE TITLE
[Asset-Sync] Add Post-Checkout Git Hook Script to Restore all assets.json within repo

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#3902]
Problems:
- test-proxy (our "restore" tool) may or may not be present on the machine
- is there a post-checkout hook specifically that we can add to each repo?
- The script should properly no-op (or inform user) if tooling is not present

Does this cooperate well?

**Comment by kurtzeborn** [comment]
@scbedd, not sure if you or @JimSuplizio will be doing this.  Assigning it to you first.

**Comment by scbedd** [comment]
This task is supplanted by the shims of each repo passing the appropriate assets.json along to the proxy if detected.
