### ISSUE TITLE
[Asset-Sync] Write a transition document that describes how to take advantage of the external assets repo

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#3905]
This document should be used to cover at least the following topics:

- Simple description of the storage algo, where data is stored and how it's retrieved.
- Description of changes in their shim to take advantage of `restore` and `push` functionality
- Details on how to restore and push manually on both tool and docker platforms
- Description of livetest additions

**Comment by scbedd** [comment]
Adding additional topics.

- Common errors and how to resolve them

Create a stripped down "one-pager" version of above doc that covers.

- Where to go with questions
- How to create a new assets.json from nothing
- Cheatsheet for swapping an existing service to leverage asset-sync.

**Comment by benbp** [comment]
Happy to be a beta tester.

**Comment by scbedd** [comment]
Going to keep this item open for a longer `introduction to asset-sync` that walks through the whole process in detail, then leads into the transition script that that Jim wrote.

**Comment by scbedd** [comment]
This is present [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/785/Externalizing-Recordings-(Asset-Sync)) now.
