### ISSUE TITLE
[Asset-Sync] Create `tools - test-proxy - tests`

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#3906]
- This pipeline should be the `tools - test-proxy - tests` equivalent
- It should run a couple selected unit tests from each of our main languages.
  - JS (appconfiguration)
  - Python (tables, formrecognizer, confidentialledger)
  - Go (aztables)
  - NET (core) 
- It should go through the _complete_ set of integration changes targeting `azure-sdk-assets-integration` repo. This should _actually_ be pushing new SHAs and the like to the repo. 
- It should run the `tool` push/reset/restore scenarios on Windows/Linux/Mac
- It should run the `docker`  push/reset/restore scenarios on Windows/Linux only. 

[An example of an integration test is visible here.](https://github.com/Azure/azure-sdk-tools/blob/2325eca955be184d052a5fc85c3a4188392359a1/tools/asset-sync/assets.Tests.ps1#L248)

**Comment by JimSuplizio** [comment]
The last of the initial integration tests were added with the following [PR](https://github.com/Azure/azure-sdk-tools/pull/4074)
