### ISSUE TITLE
Automatically add/update review date to project

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3917]
We use a [github project](https://github.com/orgs/Azure/projects/196/views/8) to track all upcoming reviews. 
When a review is scheduled/updated the date should be automatically added to the `Review Date` field in the project. 

Note: This is in addition to #3915 , which is intended to track the historical list of meetings/review sessions.

**Comment by JonathanCrd** [comment]
Done, there's a follow up issue for configurability: #4890
