### ISSUE TITLE
Link the `informational meeting` info to the API Review Meeting

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3918]
When an API Review is scheduled, the information from the onboarding/ informational meeting should be linked. Ideally, this information is, itself, captured and documented in a Github issue that can be easily linked and referenced. This is what we've been referring to as the `engagement record`. See: https://github.com/Azure/azure-rest-api-specs-pr/issues/6011 as an example.

**Comment by ladonnaq** [comment]
@maririos When the product field is added to the API Meeting, we can find the ADO work item and link it to the API Review GitHub issues that is created for the API Review meeting.  Moving issue to backlog and assigning requirements category to the issue.

**Comment by maririos** [comment]
See design comments on https://github.com/Azure/azure-sdk-tools/issues/3919

**Comment by maririos** [comment]
This has been added into the calendar invite and the GH issue. Example:

![Image](https://user-images.githubusercontent.com/9868623/231290323-e42d73d7-d36b-4120-a46f-4d0f4bb3ef37.png)

The remaining questions is, what to do when the workItem is not found?
- How do we communicate with the users?
- Who should be paying attention to it?
- Should we make it a requirement for the API Review meeting?

I'm going to start an email thread on that

**Comment by maririos** [comment]
After looking more into this, updates:
- Change `Engagement Record` to `Onboarding Record`
- When there is no onboarding record, we should sent a separate email to the creator of the meeting asking them to Schedule an Informational meeting. 
- For now, it won't be a requirement for API Review. We don't want to stop people from scheduling a meeting

**Comment by maririos** [comment]
> Change `Engagement Record` to `Onboarding Record`

Done.

![Image](https://user-images.githubusercontent.com/9868623/232563671-bbeceb73-0df0-4700-9624-650cd0cffa5f.png)
