### ISSUE TITLE
When an SDK review is scheduled, include a link to all previous API reviews

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3919]
When an SDK meeting is scheduled, a link to all previous API reviews for that team should be included. 

cc: @kyle-patterson

**Comment by ladonnaq** [comment]
@maririos When the API Review GitHub issues are mapped to products, then you can locate the ADO work item and the API review GitHub issues and link to the GitHub issues that is created for the SDK Review or Introduction meeting.  Moving to backlog and assigning requirements category.

**Comment by maririos** [comment]
@ladonnaq initially we are going to include the ADO work item in the calendar invite and in the GH issue.
Is this what you are thinking too?

**Comment by ladonnaq** [comment]
> @ladonnaq initially we are going to include the ADO work item in the calendar invite and in the GH issue. Is this what you are thinking too?
> 
> `Engagement Record: <link>`

Yes that is what I am thinking.  If the ADO work item is in the calendar invite and GH issue, then it has the relevant history and data that has been provided through the service partner using the scheduler, release planner, and updates made directly to the ADO work item (i.e. email exchanges, info meeting notes, etc).

**Comment by JonathanCrd** [comment]
Currently both GH Issue and Email do not have a link to the ADO Work Item. Do we want to add it as part of this too?

**Comment by JonathanCrd** [comment]
Data is retrieved from the ADO Work Item, and it is now included in the email.
