### ISSUE TITLE
The text for `SDK review` reads `API Review` in side nav

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3920]
![Azure SDK Team Scheduler SDK Review - Power Apps 2022-08-11 09-39-36](https://user-images.githubusercontent.com/522116/184146903-a4bb0ea8-b9c9-4818-a6e1-a1682a49f036.png)

**Comment by maririos** [comment]
Dup of https://github.com/Azure/azure-sdk-tools/issues/3821 

This was fixed in release `1.0.0-beta.2`
