### ISSUE TITLE
[Test-Proxy] Apply string sanitizers from longest to shortest target string

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-tools#3939]
### Context

In Python, the Storage team ran into an instance where some URL domains aren't being sanitized as expected. Storage tests use a primary account name as well as a secondary account name, and the former is often a substring of the latter (e.g. `accountname` and `accountnamesecondary`).

Storage [specified](https://github.com/Azure/azure-sdk-for-python/blob/d7223acdc520cd66786295b6ec7f48a03c25504d/sdk/storage/azure-storage-blob/tests/settings/testcase.py#L53-L55) that primary account names should be "storagename" in recordings, and secondary account names should be "pyrmtstoragestorname". This worked with `vcrpy`, but with the test proxy, secondary account names are instead being recorded as "storagename" followed by the rest of the real secondary account name. For example, "storagenamegrs" in a real scenario.

This happens because the sanitizer for the primary account name runs over recordings first. The test proxy's recording handler [seems to iterate over the sanitizers in a deterministic order](https://github.com/Azure/azure-sdk-tools/blob/2279cc0fa00f1e5e4035236f4d6a6aee5dfe3902/tools/test-proxy/Azure.Sdk.Tools.TestProxy/RecordingHandler.cs#L117), and I assume that order goes from least-recently to most-recently registered. If that's an accurate order that we can expect to remain constant, then I can recommend that sanitizers for substrings of another value get registered last (e.g. add a sanitizer for `x_secondary` before the one for `x`).

### Feature request

If the sanitizer order isn't guaranteed to be dependent on when sanitizers were registered, then another solution would be to order our string sanitizers based on the target string's length. This substring sanitizing issue is guaranteed to not be a concern if the sanitizer for the shorter string runs last. Theoretically, something similar could be done for regex sanitizers, but that would require a lot of logic that probably isn't worth the hassle.

**Comment by scbedd** [comment]
> If the sanitizer order isn't guaranteed to be dependent on when sanitizers were registered,

Ordering is definitely guaranteed. I can add additional ordering of target string length.

**Comment by scbedd** [comment]
I think I am going to close this. I will open a discussion on the test-proxy teams channel to discuss the sanitizer updates.

For me, I feel that clients know what order they register the sanitizers in. Knowing that they apply one after an other _in the order that is registered_ is the least confusing solution, IMO.

Sorting your sanitizers by length will introduce some craziness, and I'd rather not do it.
