### ISSUE TITLE
Network Error in Patch function when creating a new Rest API meeting

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#3943]
This is caused due to long descriptions or URLS. We should increase the max character for the columns in the database and add length checks before making the calls to the DB.

**Comment by JonathanCrd** [comment]
This has to be done too for all the other meetings:

- [ ] SDK Review
- [ ] Informational

**Comment by JonathanCrd** [comment]
I have reviewed and adjust the necessary `maxLenght` properties in the `Events` and `Artifacts` table.

This is a summary of the max character length now:
| Description           | 2000 |
|-----------------------|------|
| GitHub Tracking Issue | 2000 |

And for artifacts the URL length is 4000, but I limit it in the app to 2000 characters.

**Comment by praveenkuttappan** [comment]
We have completed this change for all 3 apps.
