### ISSUE TITLE
Add ability to tell which meetings have been scheduled every day

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3944]

**Comment by maririos** [comment]
I added a View that will help with this. If the Admins can see the view then we are good. 
I am waiting on deployment to see if the view gets to Production

**Comment by JonathanCrd** [comment]
I wonder if we can integrate that view into the admin app or another new app too. Just for visualization.

**Comment by maririos** [comment]
Yes. that is the main goal and there is already an issue for the Admin app to include that. https://github.com/Azure/azure-sdk-tools/issues/3857

This is a workaround while we have that.

**Comment by maririos** [comment]
The view is available in PROD. Need to verify permissions with stakeholders

**Comment by maririos** [comment]
Admn don't have permissions for this view. We have added a view into the Admin app
