### ISSUE TITLE
Meeting title is incorrect...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3948]
This was a meeting that was scheduled using the new tool. The service and the sub-service were properly selected and an existing github issue put in. The title of the meeting should be:

[Communication Services - Calling Server] API Review #19308.
Note: We drop the leading `Azure` in the name b/c it's redundant. 

![API Review -Azure Communication Services • Calendar • markweitzel@microsoft com 2022-08-15 18-06-08](https://user-images.githubusercontent.com/522116/184726585-c26d5d91-da79-4c24-af44-86d1bf1c9eed.png)

**Comment by markweitzel** [comment]
Also... the text is technically incorrect. An issue was not created, it was already provided.

**Comment by maririos** [comment]
>  Also... the text is technically incorrect. An issue was not created, it was already provided.

Issue https://github.com/Azure/azure-sdk-tools/issues/3830

**Comment by maririos** [comment]
Title of the meeting has been updated to  `[<service> - <sub service>] API Review `.
@markweitzel what is the number making refenrece to? The Github issue that tracks the meeting?

**Comment by maririos** [comment]
From issue #3928: `[<service family> - <service area>] - API Review: <issue #>  `

**Comment by maririos** [comment]
GH issue number added.
