### ISSUE TITLE
Relative Link Replacement Should Also Update Master Links

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#395]
1. Continue relative link replacement as is now.
2. Add another replacement regex that looks for links directly to **master** branch. 

There is some gotchas here, as there are a couple different ways you can refer directly to master.

**Comment by sima-zhu** [comment]
We have disabled the relative link and replaced with master link. Also, we switched the master link to release tag link at release. The issue has been resolved. Close it for now. Feel free to reopen if anything left.
