### ISSUE TITLE
Swagger validation should run on /dev folder

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#3950]
Until more teams move to CADL or we have a new system in place, we are starting more teams with the /dev folder I [documented](https://microsoft-my.sharepoint.com/:w:/p/heaths/EXprgNBWfgRErZaf45Hv89sBLfxRRB0PI82Z_nTpcyXgxQ?e=TH2wol) (internal link). This is a git- and GitHub-friendly process that not only makes it easier to move changes across API versions for teams working on multiple releases simultaneously - common for larger data plane APIs - but also makes it much easier to review because, as was intended for Git (and any version control system, really), you're viewing modifications to files and not modifies to copies of files (which then appear as completely new files).

There's not much difference. The folder structure is the same but without the "(stable|preview)/{api-version}" folders since all changes are made in place *and then* files are copied to /specification. All validation should work exactly the same, I would think, except for Avocado, for which I filed a separate bug: #3711.

**Comment by raych1** [comment]
@heaths , this is supported.
