### ISSUE TITLE
Requiring that Arch Board reviews only use automatic ApiView listings.  

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3951]
Consider start with an automatic API View listing by default and manually grant exceptions after discussing with the team.
If so, the Scheduling tool should support this.

**Comment by MrJustinB** [comment]
Is this a process or tooling improvement?  Update Issue to reflect correct Area please

**Comment by maririos** [comment]
Great question. The way I see it is to modify tooling and drive process change with it. For now I will put it in Tooling

**Comment by josefree** [comment]
I wonder if this is a requirement for the scheduling tool? @maririos I added 'Scheduling tool' label per my understanding. If it is not only for the scheduling tool, feel free to remove it.

**Comment by maririos** [comment]
Thank you @josefree  I agree tha thte scheduling tool can help with this

**Comment by maririos** [comment]
@ronniegeraghty form your experience with the arch boards, do you know how many reviews happen from people manually uploading their APIViews vs automatic APIViews?

**Comment by maririos** [comment]
Thank you @ronniegeraghty . Great point.
The easiest way to see this will be to look directly in APIView in the `Revisions` tab. If the revision says `Created for PR` or `Auto Review` then it is automatic.

Ted has been one of the architects asking for this. Maybe a topic that could be brought up for the discussions with the arch board?

**Comment by maririos** [comment]
FYI @praveenkuttappan

**Comment by maririos** [comment]
Closing issue for now as this is not a real scenario or restriction we want to have
