### ISSUE TITLE
[Asset-Sync] Remove "climbing" for assets.json

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#3960]
We "ascend" until `repo root` or `disk root` given an input path. We should error if the target directory doesn't have an assets.json. 

We still need to ascend to ascertain location of repo root, etc.

**Comment by JimSuplizio** [comment]
@scbedd this shouldn't be terrible, there's [one function to change](https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitStore.cs#L506) and it only affects the assets.json, and has nothing to do with anything else like ascertaining the location of the repo root. I've assigned this to me.
