### ISSUE TITLE
Add templates for GH Body message for API and SDK meetings

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3965]
Only Informational meeting has this template: GH tracking Body Message

We need to implement the templates for the other meeting types and update the logic to use this ones

**Comment by praveenkuttappan** [comment]
@maririos Can we use same template as Informational for REST And SDK review apps or is there any different content we should put in template for REST And SDK review apps?

I have discussed this issue with Jonathan and I think I have an idea where to start on this issue. But needs to have some confirmation about the content within this template.

**Comment by maririos** [comment]
API Review:
Title of the GH issue: `[<service name> - <Subservice name>] API Review`

Content:
Service name: <service name> - <Subservice name>
Review created by: <username> - <user email>
PR: <PR link> -- _This should only appear if provided_
Description: <description> -- _Only it provided_

Detailed meeting information and documents provided can be accessed here<link to powerapps meeting> -- _same as we currently do in the template_

**Comment by maririos** [comment]
Something that just occured to me is that this works when we create the issue, but what should we do when the user provides the issue to us? should we add a comment in the issue with this information? -- I need to follow up with @markweitzel for this specific case

**Comment by maririos** [comment]
Also, see https://github.com/Azure/azure-sdk-tools/issues/3947
Maybe Github issue doesn't need the template to be with html format?
