### ISSUE TITLE
Breaking Changes PR check not flagging removed property as breaking

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#3982]
The Breaking Changes PR check in the azure-rest-api-specs repo is failing to flag a removed property as breaking and requiring a Breaking Change review.

REST API PR: https://github.com/Azure/azure-rest-api-specs/pull/20009

The [Breaking Changes-Cross Version PR check](https://github.com/Azure/azure-rest-api-specs/pull/20009/checks?check_run_id=7570117397) issued a warning for the removed property:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/85643503/185497759-3b4d20f3-62f7-44ad-84fc-5398c22ebdbd.png">

Here is the actual change:

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/85643503/185497916-c952aa91-0c36-4df4-a9d4-ac52c61c24e1.png">

Any property being removed should be flagged as a breaking change even in a new API version.

cc: @JeffreyRichter @srmantha

**Comment by jianyexi** [comment]
@mikekistler this is because all the api-versions of the RP are preview and no stable version, so the breaking change are allowed per breaking change policy , then we flag it as warning

**Comment by mikekistler** [comment]
Thanks @jianyexi, that's good to know. Could you please update the [breaking changes doc in your PR](https://github.com/Azure/azure-rest-api-specs/pull/20021) to explain this subtle point? Thx.

**Comment by jianyexi** [comment]
@mikekistler it's already described in https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/ci-fix.md#breaking-change-check

**Comment by mikekistler** [comment]
Fair enough.

**Comment by mikekistler** [comment]
It seems that the situation is not quite as simple as this. The breaking changes check _do_ flag some breaking changes as errors even when there is no prior stable version. [PR #8244](https://github.com/Azure/azure-rest-api-specs-pr/pull/8244/checks?check_run_id=8192489224) is an example:

<img width="868" alt="image" src="https://user-images.githubusercontent.com/85643503/188490495-1a33267d-4b43-4ae9-9175-5acced217c6a.png">

What is the explanation for why these breaking changes are reported as errors even though there is no prior GA version?

**Comment by jianyexi** [comment]
if we can know the last preview is over 1 year (consider the api-version as date ), we will consider it as stable version, it's already described in the documentation

**Comment by jianyexi** [comment]
One exception is that some data-plane Api-version follow the pattern like 'preview/v1', so we always treat them as preview version. let me know if you want to have different strategy
