### ISSUE TITLE
APIView integration from Cadl PR

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#3991]
When a user creates a PR in the specs repo and is using Cadl, make sure there is an APIView created for it (as we currently do for SDK changes)

**Comment by lirenhe** [comment]
@maririos, is this APIView for CADL file or the apiview for the generated SDKs from CADL?

**Comment by maririos** [comment]
@lirenhe 

>  is this APIView for CADL file

^ this

**Comment by maririos** [comment]
This work has been done: https://apiview.dev/?languages=Cadl&state=Open&type=PullRequest&pageNo=1&pageSize=50
