### ISSUE TITLE
Scheduling tool requires start of free trial

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#3997]
The scheduling tool is requiring the start of a free trial due to some of the features it's using. 
The app is unusable. 

![Power Apps 2022-08-23 09-13-11](https://user-images.githubusercontent.com/522116/186167023-74ecd216-2f6e-486e-a0eb-45920275fa13.png)
![Power Apps 2022-08-23 09-13-24](https://user-images.githubusercontent.com/522116/186167077-6a2ffb65-b177-4f0f-9a2f-743d9634c5b1.png)
![Monosnap 2022-08-23 09-13-39](https://user-images.githubusercontent.com/522116/186167382-41d7fd51-f310-49c1-8be3-0098146f0279.png)

**Comment by maririos** [comment]
I'm unable to repro this, which makes me think there is something with permissions and this might be a new feature that was added by other team.
@praveenkuttappan  could you look into it?

**Comment by praveenkuttappan** [comment]
@markweitzel While I am investigating this issue of Premium usage within app, I would like to know if your account has Powerapps subscription. I believe our Microsoft account by default should have Power apps for Office 365 subscription plan. Could you please check and confirm whether you see Power apps in subscription list here for your account? 
https://portal.office.com/account/?ref=MeControl

**Comment by praveenkuttappan** [comment]
I have resolved this issue by changing license to "Pay as you go"
