### ISSUE TITLE
folder does not exist for iOS apiview

### ISSUE THREAD

**Issue by jpeng-ms** [Azure/azure-sdk-tools#4000]
upon building the project, I got the following errors and app crashed:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/109105353/186286110-bcee97a1-f969-4444-8727-4cecd5050e56.png">

there's no "travisprescott" folder on my laptop

**Comment by benbp** [comment]
FYI @tjprescott

**Comment by tjprescott** [comment]
@jpeng-ms what are you attempting to do?

**Comment by tjprescott** [comment]
You will need to update the arguments passed on launched to point to whatever source you are trying to generate for.
<img width="873" alt="image" src="https://user-images.githubusercontent.com/5723682/186532882-9d15cea7-8192-4e31-8f14-b0b19addfebd.png">
