### ISSUE TITLE
User unable to schedule meeting...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#4015]
[8/25 8:58 AM] Natalija OstojicAzure API Scheduling tool is not working
    Hello all,
I am trying to schedule the Azure API review via this tool: https://apps.powerapps.com/play/e41c69de-ef96-44ba-b287-0e012e7c13ae
but after filling in all the required data, selecting the slot from the calendar and clicking on "Create" I see this error

![General (Azure API Stewardship Board) | Microsoft Teams 2022-08-29 08-59-35](https://user-images.githubusercontent.com/522116/187206780-8c8180be-82ca-4f90-85e8-73d5039a4ede.png)

Can you please help here? Thank you

<https://teams.microsoft.com/l/message/19:3ebb18fded0e47938f998e196a52952f@thread.tacv2/1661432336635?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;groupId=1a10b50c-e870-4fe0-8483-bf5542a8d2d8&amp;parentMessageId=1661432336635&amp;teamName=Azure API Stewardship Board&amp;channelName=General&amp;createdTime=1661432336635&amp;allowXTenantAccess=false>

**Comment by maririos** [comment]
Following up with Natalija. I see entries in our DB but not concrete errors about her interaction with the tool

**Comment by maririos** [comment]
User is unblocked and meeting has been created.
We will create issues for the bugs encountered.

Thanks @JonathanCrd :)
