### ISSUE TITLE
API Review main view shows meetings twice

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#4022]
The same meeting that was scheduled by one of our users was being displayed twice in the main view. This is a bug.

**Comment by maririos** [comment]
<img width="738" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/9868623/187321558-5aceb283-60ca-4bfe-9512-4422be39f335.png">

**Comment by maririos** [comment]
I got another repro of this in Dev environment. I was testing adding special characters in the description box and I got 3 fail attemps adn the 4th one worked (once I removed special characters). When the meeting was created, this vide shows the meting 4 times!
Wehn I cancel 1 of the 4 instances, all dissapear, so at least they are all connected

**Comment by JonathanCrd** [comment]
Interesting, I'm going to try this on my side to see what happens when I replicate the bug in PPE.

**Comment by maririos** [comment]
I created issue https://github.com/Azure/azure-sdk-tools/issues/4029 for that.
Ahh good to know. I def prefer going with 
> we might want to consider changing all " to \" before storing the values in the JSON, and then see if this work.

**Comment by JonathanCrd** [comment]
Fixed, this was caused because the event invitees were being added twice to the event if something failed the first time trying to schedule the meeting.
