### ISSUE TITLE
Edit button is not showing in the API Review main view

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#4023]
The `Edit` button was not displayed for a user who just had scheduled an API Review meeting. This happened in the main view, the meeting was in the list, but the `Edit` button was not there.

**Comment by maririos** [comment]
<img width="738" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/9868623/187321616-27bb089f-ada7-4515-ae14-e1142f540dee.png">

**Comment by JonathanCrd** [comment]
I was able to replicate this issue. If for some reason in the `Event` table the date is null, even that the event is `In Progress`, the edit and cancel buttons won't show up. This is kind of expected because you cannot edit/cancel a meeting from a past date, or that is in Draft. However, should I include a check in case the date is null? if so, what should I do in this case?

By the way, a date being null is a bug, in theory this will never happen, and we should have other mechanisms to prevent and fix this bug.

**Comment by maririos** [comment]
Because of our conversation, I would consider closing this issue
