### ISSUE TITLE
Subservice is not being displayed in Edit mode for API Review

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#4025]
When editing an existing meeting, the subservice is being displayed as `None` even though there was one specified.
The subservice was correctly stored in the Event table row for that meeting.

Does this happen to the other meeting types too?

**Comment by maririos** [comment]
Filtering some data:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/9868623/187323199-83244a76-63eb-4e34-bfd0-5d9729060d9e.png">

**Comment by JonathanCrd** [comment]
Fixed
