### ISSUE TITLE
Special characters in Description field are not allowed

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4029]
for a text like: `hello "world"`

The creation of the meeting fails with:  `Could not create GH issue. Please try again later.`

**Comment by JonathanCrd** [comment]
Should we fix this issue in the current release?

**Comment by maririos** [comment]
First step: Make sure people know in the UI that this is not supported until we proparly fix it

**Comment by maririos** [comment]
Is there any option here to select "no special characters" ? FRom @praveenkuttappan

**Comment by JonathanCrd** [comment]
I have fixed this by creating a component that modifies the output of the TextBox, changing all `"` to `'`.
Next thing to do is adding that component in the apps to replace the current textbox.

If we need to do more changes in the future, or input checks, we can now just update that component.

**Comment by JonathanCrd** [comment]
I added more capabilities to this component because I forgot the Update usecases, so now it's good.

Adding this new component in the different apps:

- [ ] Informational
- [ ] API Reviews
- [ ] SDK Reviews

**Comment by JonathanCrd** [comment]
The old TextBox is gone, now this component will output any `"` to `'`, for example:
```
This is is "test"
```

The output Text from `Description.Text` Will be 
```
This is a 'test'
```

It looks exactly the same as the old TextBox:
![image](https://user-images.githubusercontent.com/17486462/198171582-99e44e03-0f2b-4a25-9842-85251b4b4c4f.png)

But now, it will display a warning wheneve rthe user inputs the max amount of characters as well:
![image](https://user-images.githubusercontent.com/17486462/198171626-ac71ebdf-fe93-4a99-8f23-113d35d69dc0.png)
