### ISSUE TITLE
ApiView support for paragraphs in comments

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4030]
You can't have paragraphs in comments. I think this boils down to stripping out newlines in comments. If we preserve the new lines, it allows commenters to break thoughts into paragraphs which would help with certain types of comments. (just to clarify - multiple newlines get squashed)

**Comment by mikekistler** [comment]
Link to recent discussion on this in the APIView teams channel: [link](https://teams.microsoft.com/l/message/19:3adeba4aa1164f1c889e148b1b3e3ddd@thread.skype/1661813440448?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1661813440448&teamName=Azure%20SDK&channelName=APIView&createdTime=1661813440448&allowXTenantAccess=false)

**Comment by Baas-hub** [comment]
I'll take on this issue @JonathanGiles
