### ISSUE TITLE
Title of created issue and meeting should match...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#4040]
The title of the meeting and the issue should match. This makes understanding, aligning the two easier. 

![Searching  Meeting Invites   Responses  2022-08-31 15-48-31](https://user-images.githubusercontent.com/522116/187769219-2532aca5-bbf6-469b-8d1e-e4c7b1f313ce.png)

![azure-rest-api-specs 2022-08-31 15-49-45](https://user-images.githubusercontent.com/522116/187769340-d36722bc-45cd-4fe0-8ca5-7f25d6e49511.png)

**Comment by maririos** [comment]
Thanks @markweitzel 
This will be covered in https://github.com/Azure/azure-sdk-tools/issues/3965

FYI @praveenkuttappan

**Comment by markweitzel** [comment]
The "formula" for creating the meeting name and issue

[<Service Family> +  <service area>] API Review: <version>

We don't need to add "Azure" -- That is implied and just noise.
Ideally the PR also follows this convention. Most have not at this point, and that is an indication that teams are not following our process.


![azure-rest-api-specs 2022-08-31 15-52-03](https://user-images.githubusercontent.com/522116/187770216-8c68b4b8-c6a3-489e-ba1e-33735d8eeb0b.png)
