### ISSUE TITLE
Review artifacts information must be in the API review issue and calendar invite...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#4043]
When a meeting is scheduled, the issue used to track the work in github is incomplete. Specifically, the way the API Review Board works is via github issues. The issue IS the record of the meeting, e.g. it will be where we assign ownership, take notes etc. It should contain everything necessary to prepare for a review. 

![azure-rest-api-specs 2022-08-31 17-28-12](https://user-images.githubusercontent.com/522116/187788385-8e9a05e9-1709-4239-8a7f-ac518ca1ae8d.png)

Further, the meeting invite text should also contain the information. Right now, if I open up the meeting invite to find out what I will be looking at, e.g. to review the hero scenarios...
Meeting Invite --> GitHub Issue --> Calendar tool. 

![Azure SDK Team Scheduler Rest Review - Power Apps 2022-08-31 17-32-46](https://user-images.githubusercontent.com/522116/187789254-38224c33-1af5-44d4-b53c-2b7ed1ddf380.png)

**Comment by maririos** [comment]
FYI @praveenkuttappan

**Comment by maririos** [comment]
Email information has been updated in issue https://github.com/Azure/azure-sdk-tools/issues/3986

**Comment by maririos** [comment]
Github issue has been updated too
