### ISSUE TITLE
[OpenAPI Hub] Consistent naming convention across our tools for GitHub issues or PRs that automatically generated

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#4048]
When the open api hub generates a pull request, the naming pattern it uses is not consistent with that of the rest of our tool chain, notably, the Scheduling tool.

We should update the Open API Hub to match our naming convention. 
* We should use a label to indicate the pr was hub generated.
  * Note: we should also investigate if we can use a github `tag` on the commit to tag this as hub generated. This could be very effective.  

![2022-09-01-preview by specialforest · Pull Request #20245 · Az… 2022-09-01 10-52-48](https://user-images.githubusercontent.com/522116/187945227-002b8351-a09c-42af-b78b-24fdc710f85d.png)

Note: This isn't a scheduling tool issue, per se, but adding it to the project b/c of alignment.

**Comment by josefree** [comment]
Add it to API tooling project for triage

**Comment by josefree** [comment]
@maririos could you help to clarify what's scheduling app naming convension?

**Comment by maririos** [comment]
@josefree  witht he Release Planner App I won't expect users to keep using OpenAPI Hub right? so we won't be creating a PR for them. Is this correct? or in which cases we will still ask users to user OpenAPI Hub?

BTW the format that was requested by @markweitzel and that is used in the Scheduling tool is: `[<service name> - <product name>] API Review`

**Comment by maririos** [comment]
OpenAPI Hub (or any other tooling) is no longer creating the PRs for the users. Closing this issue
