### ISSUE TITLE
Define role, responsibilities, and more for Service buddy

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4051]
The purpose of this Epic is to focus on defining the roles and responsibilities, tools for people to do their job, and mechanisms to build in accountability for the service buddy for Cadl

**Comment by josefree** [comment]
I place the milestone to be '2023-01'. This could be closed when Release Planner can cover both Data Plane and Management Plane SDK release.

**Comment by ladonnaq** [comment]
@maririos I am moving this to backlog.  If the TypeSpec team does assign a TypeSpec service buddy to help new services adopt TypeSpec, then we can revisit. At this time, Catalina and Travis are acting in this role for data plane but I think that this is an interim sort of role, they would not be doing this long term.

**Comment by ladonnaq** [comment]
I am closing this issue as this requirement is in the TypeSpec onboarding requirement - https://github.com/Azure/azure-sdk-tools/issues/4050.
