### ISSUE TITLE
[API view] Formatting issue in Java API view 

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-tools#4052]
https://apiviewstaging.azurewebsites.net/Assemblies/Review/9f0252f1f1264c61be1fe517a0d8d667

- The class annotation has additional space. 
- The class ending parenthesis indentation does not align with class declaration indentation
![image](https://user-images.githubusercontent.com/51379715/188016733-d5fac227-a416-4f4b-ab79-c856cc81c1c1.png)

**Comment by JonathanGiles** [comment]
Looks to be a regression introduced by #3941

**Comment by Vailorium** [comment]
@JonathanGiles

**Comment by Vailorium** [comment]
This appears to be working fine on the main branch - it was probably resolved with #4091

**Comment by Vailorium** [comment]
Issue is in the Java code, which I hadn't rebuilt since some changes were made. Reopened and looking into this again.
