### ISSUE TITLE
Gaps and changes in the API Stewardship Board activities due to TypeSpec

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4053]
The purpose of this Epic is to define the gaps on the API Review (management and data plane) process inside the Azure SDK Release process affected by Cadl.
Some general parts on the step that need to be accounted for:
- APIView should support Cadl in some sort. Issue looking into that is https://github.com/Azure/azure-sdk-tools/issues/1208
- Information communicated to API Stewardship around Cadl state and breaking changes
- How will the approval take place? With a label on the PR like today? With a button on APIView? 
- Follow up with teams?
- Other items: https://github.com/Azure/azure-sdk-tools/issues/5760

**Comment by maririos** [comment]
wiki will have to be updated to include information about Cadl https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/665/Azure-REST-API-Stewardship-Review

**Comment by josefree** [comment]
I place the milestone to be '2023-01'. This could be closed when Release Planner can cover both Data Plane and Management Plane SDK release. Notification and dashboard requirements can be tracked with separate epics.

**Comment by ladonnaq** [comment]
@mikekistler I assigned you to this issue.  This is related to some of the process gaps I wanted to discuss yesterday but we did not have enough time.  I will setup a meeting so we can walk through the open issues related to Release Planner and Cadl and API Reviews.

**Comment by mikekistler** [comment]
@ladonnaq Is there still work do to on this or can we close?

**Comment by ladonnaq** [comment]
Closing this issue.  Outstanding APIView todo being tracked in this GitHub issue - https://github.com/Azure/azure-sdk-tools/issues/5760
