### ISSUE TITLE
Wrong review date time for SDK and API Review Github Issue

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4059]
User scheduled a SDK Review meeting for 9/21/2022 2PM . The calendar meeting was sent correctly, but the GH issue displayed 4PM.
The meeting in the Data Verse is correctly stored.

i.e email:
<img width="469" alt="image" src="https://user-images.githubusercontent.com/9868623/188203430-545eea6d-b914-434a-8089-b7f2a9660164.png">

Github issue:
<img width="767" alt="image" src="https://user-images.githubusercontent.com/9868623/188203586-3c2ffc82-fe02-410e-bc2b-28f0375b2c43.png">

Same happens for API meetings. The error is also 2h

**Comment by maririos** [comment]
PS: I went and manually updated the issues so it has the correct information

**Comment by maririos** [comment]
We decided to remove the field `Review date` completely and follow up with our admin users how they want us to display the date

**Comment by JonathanCrd** [comment]
I've removed `Review date` from the GH tracking issue
