### ISSUE TITLE
Process and tools to support communication with service partner regarding follow-up across the release plan activities

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4060]
### Communication with service partner regarding follow-up across the release plan activities 

- Currently there is no clear/easy way to guarantee that during the release process we are following up with the service team. Although this can be slightly improved with the outcome of the work on [#4045](https://github.com/Azure/azure-sdk-tools/issues/4045) we need to make sure that tooling is supporting the follow up too.
- For example, when a user requests feedback on a OpenAPI PR, who follows up? what is the time frame?
- We also have a bot that is looking at the state of the PRs and issues in our repo, how is this contributing? 
- There are several teams channels for management plane that service partner's use to engage our team and ARM.  Service team's tend to use these channels to get help with PRs and Shift Left/API Spec pipeline enablement. Should links to these teams channels be available via the release plan at the appropriate step? 
1.[Service API Toolset](https://teams.microsoft.com/l/channel/19%3a9efda948665d481086766c0b7572abc3%40thread.skype/Service%2520API%2520Toolset?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
2.[API Spec Review](https://teams.microsoft.com/l/channel/19%3a0351f5f9404446e4b4fd4eaf2c27448d%40thread.skype/API%2520Spec%2520Review%2520(previously%2520Swagger%2520Review)?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)
- Does the API Stewardship Board use their teams channel as a way for service teams to follow-up or ask questions during or after API Reviews? 
- Is APIView the tool that the arch board uses for follow-up after the SDK Reviews? 
- What are the SLAs associated with follow-ups for the following activities? 

1. API Reviews.
2. API Spec/TypeSpec pull requests (PRs).
3. SDK reviews.
4. Naming approvals for new initial Beta SDKs for management plane and data plane.
5. Arch Board approval for initial stable SDK release. 
6. SDK breaking change review for new SDK versions for management plane and data plane. 
7. APEX launch criteria attestations/signoffs.
8. Release planner bugs reported by service partners. 

- Notifications.  Which activities should have notifications?  How and where should these notifications be?  Who should recieve the notifications?

**Comment by josefree** [comment]
We can do a lot here, for example, notification, dashboard.  However, currently, this issue is a requirement, yet being translated into features.  This is not ready to hand over to engineer.

**Comment by josefree** [comment]
I place the milestone to be '2023-01'. This could be closed when Release Planner can cover both Data Plane and Management Plane SDK release.  Notification and dashboard requirements can be tracked with separate epics.

**Comment by maririos** [comment]
These are all great ideas and most of it has been covered by independent efforts. Where we can, the [docs](https://eng.ms/docs/products/azure-developer-experience) have been updated to reflect the point of contact for each step.
As there are no concrete action items for the Eng Experience team, I am closing this issue
