### ISSUE TITLE
When adding a new API View Link on an existing SDK review meeting, it is not clear that those links have been saved

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#4061]
When editing an SDK review meeting, adding or removing an API View Link will not enable the Save button.

However, those changes are being saved at the moment the API View Link artifact is updated or deleted, so in theory this is working fine, but it is very confusing for the user.

We should add an alert or pop out to let the user know that their changes have been saved even if the Save button is disabled.

**Comment by maririos** [comment]
I was able to enable the `Update` button so it is clear to the user that the apiview link was correctly saved.
I'm closing this issue becuase of the work done in https://github.com/Azure/azure-sdk-tools/issues/4416.

Something that could happen though is that a user is editing a meeting, adds/updates an apiview link but doesn't hit `Update` button. This will save the information in dataverse but not in email/GH. If this is an issue, we can rethink our approach
