### ISSUE TITLE
What timezone format we should use when communicating on Github

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4068]

**Comment by maririos** [comment]
I will take this and ask the PMs

**Comment by maririos** [comment]
- SDK Review: Use fo PDT time. An example: `9/13 2p-4p PDT` This was manually entered and I am not suggesting this exact format, just an example.
- API Review: Only date, no time. Date is set according to USA

**Comment by maririos** [comment]
Ready for development

**Comment by benbp** [comment]
@maririos this is just me sticking my head in other people's business, but PDT may get annoying as a reference when we switch to PST for the other half of the year (e.g. if people keep using PDT out of habit). Personally I use PT or pacific or pacific time, that way it's consistent year round for typing.

**Comment by JonathanCrd** [comment]
> @maririos 
API Review: Only date, no time. Date is set according to USA

How are we planning to display this? `Date: 9/15/2022 USA`? 

> @benbp 
Personally I use PT or pacific or pacific time, that way it's consistent year round for typing.

Good point, we could use _PT_ or _US Pacific Time_ and don't add that extra complexity of changing between _PDT_ and _PST_

**Comment by maririos** [comment]
> > @benbp
> > Personally I use PT or pacific or pacific time, that way it's consistent year round for typing.
> 
> Good point, we could use _PT_ or _US Pacific Time_ and don't add that extra complexity of changing between _PDT_ and _PST_

PT sounds good

**Comment by maririos** [comment]
As for format we could use `LongDateTime` for everything (including API Review meeting). See https://docs.microsoft.com/en-us/power-apps/maker/canvas-apps/show-text-dates-times

**Comment by maririos** [comment]
@JonathanCrd could you open an issue to improve this
