### ISSUE TITLE
Cross-version breaking change when adding x-ms-enum wasn't flagged in CI

### ISSUE THREAD

**Issue by jhendrixMSFT** [Azure/azure-sdk-tools#4073]
The following PR introduced a new API version for storage (control-plane).

https://github.com/Azure/azure-rest-api-specs/pull/19357

In `common.json`, `CorsRule.allowedMethods` had the `x-ms-enum` extension added to control the name and not rely on an auto-generated one.  This resulted in a different name from the previous API version which didn't have the `x-ms-enum` extension.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/storage/resource-manager/Microsoft.Storage/stable/2021-09-01/common.json#L32

This was not flagged as a cross-API version breaking change when it should have been.

CC @mikekistler

**Comment by raych1** [comment]
@jianyexi , can you provide update?

**Comment by jianyexi** [comment]
already fixed
