### ISSUE TITLE
Erroneous messages from [Staging] Swagger LintDiff

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4075]
[Staging] Swagger LintDiff is issuing erroneous messages for "GetCollectionResponseSchema". A specific example is [PR #8338](https://github.com/Azure/azure-rest-api-specs-pr/pull/8338):

<img width="973" alt="image" src="https://user-images.githubusercontent.com/85643503/188759251-ff6bb90d-b59c-47fe-a07f-14b68a43be35.png">

Note that all four of these messages point to the same line in the API definition but reference four different "individual GET operation"s. None of the referenced operations are actually the individual GET that should be referenced.

**Comment by jianyexi** [comment]
fixed
