### ISSUE TITLE
Button (or something) to navigate to first comment

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#4085]
The next/previous buttons to go from comment to comment in APIView are *very* helpful; however, often finding that first comment can be difficult, especially for many pages of API. Could you add a button to go to the first comment? No realy preference on where it'd be, but maybe a button (or link) in the drop-down that shows how many active comments there are, which may be an intuitive place to put it.

**Comment by chidozieononiwu** [comment]
Resolved by https://github.com/Azure/azure-sdk-tools/pull/4206
