### ISSUE TITLE
First preview must require APIView approval for release

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#4099]
Right now, we have a system in place that any APIView changes in a GA library requires an explicit approval by architect on APIView. Previews are not subject to this, and can be released at will.

The ask here, is that if the preview is the first one ever (no baseline release ever happened), then the library must requires an APIView approval as well.

This is to avoid a service team to be able to release a preview library for the first time without even been discussed in archboard about the package name, which happened recently with Purview Share.

cc @pallavit @weshaggard

**Comment by tg-msft** [comment]
Today ApiView signoff means your API is ready to GA and it’ll muddy our workflows to mix “API signoff” and “package name signoff.”  Ideally it’ll eventually be in ApiView so there are fewer moving pieces for architects and partner teams, but “packages.(net|java|js|py).txt” files with one package name per line in the azure-sdk repo works fine for now too.

**Comment by JonathanGiles** [comment]
An alternative solution for consideration: could we instead use the approach I outline in #2449 to have diagnostics that are critical blockers, and then write diagnostics per language that validate against ecosystem artifacts in nuget, maven central, etc?

**Comment by praveenkuttappan** [comment]
We are adding a new feature in APIView to approve package name and we will enforce package name approval for preview release.
