### ISSUE TITLE
Add ability to set specific labels into a specific Github issue

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4107]
Related to https://github.com/Azure/azure-sdk-tools/issues/3858
This should work independently of the meeting type and if the issue was created by the Scheduling tool or provided by the user

**Comment by JonathanCrd** [comment]
Now the GitHub Create flow has an optional parameter to specify any labels to add into the issue. We can now proceed to ask stakeholders how they want to specify the issue, or design what would be the best way to implement this feature (if required).
