### ISSUE TITLE
[Asset Sync] test-proxy livetest pushes failing with git config errors

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#4110]
[Started Friday](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1841059&view=results)

Not quite certain why some succeed and others do not.

I believe the issue with the push is that pushing from a run machine not having a user.name or a user.email in the commit line.

**Comment by JimSuplizio** [comment]
Passing as of this [morning's scheduled run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1852743&view=results). It runs at 5am, the change wasn't checked in until after yesterday's scheduled run.
