### ISSUE TITLE
Update-Change-Logs.ps1 seems to run too late

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#412]
When Update-Change-Logs.ps1 runs as part of the pipeline to, for example, replace "(Unreleased)" with the release date, it creates a PR. But that build is what is getting released, so it runs too late. Conversely, modifying the repo directly often leads to merge conflicts so that might not be ideal either, since even then the repo would have to be rebuilt at that commit, which might've been specified by the package owner as something other than HEAD.

**Comment by weshaggard** [comment]
This is now part of prepare-release so isn't an issue any longer.
