### ISSUE TITLE
azure-sdk-for-net validation fails with multiple security definitions

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#4121]
See https://github.com/Azure/azure-rest-api-specs/runs/8311459849

If a service supports multiple security definitions - which is valid swagger - such as AAD and shared key, the validation fails with something like:

```text
warn	Skip initScript due to not configured
command	sudo apt-get install -y dotnet-sdk-6.0
command	autorest --version=2.0.4421 --csharp --reflect-api-versions --license-header=MICROSOFT_MIT_NO_VERSION --use=@microsoft.azure/autorest.csharp@2.3.82 --csharp-sdks-folder=/mnt/vss/_work/1/s/azure-sdk-for-net/sdk ../azure-rest-api-specs/dev/cognitiveservices/data-plane/Language/readme.md
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] FATAL: swagger-document/compose - FAILED
cmderr	[Autorest] FATAL: Error: '$.security' has incompatible values (---
cmderr	[Autorest] - apim_key: []
cmderr	[Autorest] , ---
cmderr	[Autorest] - AADToken:
cmderr	[Autorest]     - 'https://cognitiveservices.azure.com/.default'
cmderr	[Autorest] - apim_key: []
cmderr	[Autorest] ).
cmderr	[Autorest]   Error: '$.security' has incompatible values (---
cmderr	[Autorest] - apim_key: []
cmderr	[Autorest] , ---
cmderr	[Autorest] - AADToken:
cmderr	[Autorest]     - 'https://cognitiveservices.azure.com/.default'
cmderr	[Autorest] - apim_key: []
cmderr	[Autorest] ).
error	Script return with result [failed] code [1] signal [null] cwd [azure-sdk-for-net]: autorest
warn	Skip package processing as generation is failed
```

This requires forced squash-merges, and could cause real issues to be [missed](https://github.com/Azure/azure-rest-api-specs/pull/20679#discussion_r968629865).

**Comment by fengzhou-msft** [comment]
As the track 1 generator (autorest.csharp V2) is no longer maintained, we're not likely to update the generator to fix the issue. Since this is caused in generating dataplane SDKs (original swagger PR [here](https://github.com/Azure/azure-rest-api-specs/pull/20679)), @archerzz @pshao25 to check if there is workaround to bypass this issue.

**Comment by archerzz** [comment]
I'm not sure if we should fix this in track1 generator because for track1 SDK I believe we only supports one security scheme.

On the other hand, is there are way to tag a spec to be track2 only so that the pipeline can skip track1 validation? For new swagger definitions (e.g. with multiple security schemes) you won't expect a Track1 SDK.

**Comment by archerzz** [comment]
@heaths I think you need to update the https://github.com/Azure/azure-rest-api-specs/blob/main/dev/cognitiveservices/data-plane/Language/readme.md#swagger-to-sdk

change the `- repo: azure-sdk-for-net` to `- repo: azure-sdk-for-net-track2`, like what [Metrics Advisor does](https://github.com/Azure/azure-rest-api-specs/blob/cde7f150e8d3bf3af2418cc347cae0fb2baed6a7/specification/cognitiveservices/data-plane/MetricsAdvisor/readme.md#swagger-to-sdk).

**Comment by heaths** [comment]
I thought the track 1 was removed and the track 2 was renamed to what track 1 was. Is that not the case?

**Comment by fengzhou-msft** [comment]
> I thought the track 1 was removed and the track 2 was renamed to what track 1 was. Is that not the case?

@dw511214992 cleared track 1 `swagger-to-sdk` settings for data plane under `specification` directory(https://github.com/Azure/azure-rest-api-specs/pull/19000). I noticed the path for the swaggers in the issue-related PR https://github.com/Azure/azure-rest-api-specs/pull/20679 is under `dev`.  

I don't know the story behind having the new `dev` directory (is it a mistake?).  @dw511214992 please evaluate whether you need to clean up `swagger-to-sdk` settings for `dev` directory as well or move it to `specification` if it's a mistake.

**Comment by dw511214992** [comment]
`dev` is a new folder and we also need to clean up the `azure-sdk-for-net`.

**Comment by raych1** [comment]
@dw511214992 , can you close this issue if the PR made the fix?

**Comment by dw511214992** [comment]
sure @raych1
