### ISSUE TITLE
[Cadl APIView] surface suppressed linting rules & emitters...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#4129]
When working with Cadl definitions, it will be important for the API reviewers, to know what linting rules have been suppressed and what emitters were used to produced the outputted artifacts.

**Comment by maririos** [comment]
FYI @tjprescott

**Comment by tjprescott** [comment]
I'm not sure what is meant be which emitters are used. The `cadl-apiview` emitter is the emitter used to generate the APIView file, and its version is annotated in the APIView preamble.

As far as identifying which linter rules are suppressed, I agree, though I've yet to find any way to access comments (which is how suppressions are managed) through the Cadl program, which is how the APIView is generated.

**Comment by tjprescott** [comment]
The latest TypeSpec APIView now displays directives, which includes suppressions (and deprecations).
