### ISSUE TITLE
Track all the entry points from Service Teams to the Azure SDK team

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4136]
The goal of this issue is to figure out how to track how teams are finding the link to the application. The following places are likely:  Our wiki pages, once updated the Arch Board GitHub page, APEX wiki, Cloud Lifecycle launch criteria description, and word of mouth

**Comment by josefree** [comment]
the proposed solution is to add different parameters to link in different entries

**Comment by maririos** [comment]
We should start catalloging the specific places to make sure they are updated correctly

**Comment by josefree** [comment]
Agree.  I change the category to be 'Design', and Area to be ‘Documentation’.

**Comment by maririos** [comment]
We have added a question for this in the Release Planner survey: https://github.com/Azure/azure-sdk-tools/issues/5463
