### ISSUE TITLE
Login page to apiview.dev should include steps to make Github account public

### ISSUE THREAD

**Issue by nakulkar-msft** [Azure/azure-sdk-tools#4137]
By default new users have their account private, and would not know if account can be made public/private.

**Comment by kurtzeborn** [comment]
We're suspicious that this may no longer be needed.  The Open Source Portal APIs we're planning to switch to don't depend on this being public or not.  @praveenkuttappan, can you confirm, and close if that's the case since we won't need these instructions after all?

**Comment by praveenkuttappan** [comment]
Correct. I will close this issue once we switch auth API to open-source portal API to verify internal users.

**Comment by praveenkuttappan** [comment]
This is still required since we switched to OSS authentication only to verify PR owners and login to APIView still uses GitHub authentication.

**Comment by praveenkuttappan** [comment]
We should change authentication steps to verify if GitHub user ID is present in MSFT OSS if GitHub org information is not available for a user to support users who has org membership set as private.

**Comment by maririos** [comment]
I bumped the priority to medium because with the new flow of Swagger and Cadl APIViews we are getting new people using the tool that are not use to having their organization as public
