### ISSUE TITLE
azure-sdk-for-net validation fails for dataplane PR

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#4144]
A few dataplane PRs fails with same error. See [PR#20540](https://github.com/Azure/azure-rest-api-specs/pull/20540/checks), [PR#20545](https://github.com/Azure/azure-rest-api-specs/pull/20545/checks)
```
warn	Skip initScript due to not configured
command	sudo apt-get install -y dotnet-sdk-6.0
command	autorest --version=2.0.4421 --csharp --reflect-api-versions --license-header=MICROSOFT_MIT_NO_VERSION --use=@microsoft.azure/autorest.csharp@2.3.82 --csharp-sdks-folder=/mnt/vss/_work/1/s/azure-sdk-for-net/sdk ../azure-rest-api-specs/specification/synapse/resource-manager/readme.md
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] realpath(): Permission denied
cmderr	[Autorest] No usable version of the libssl was found
cmderr	[Autorest] FATAL: csharp/simplifier - FAILED
cmderr	[Autorest] FATAL: Error: [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
cmderr	[Autorest] Process() cancelled due to exception : [Exception] AutoRest extension '@microsoft.azure/autorest.csharp' terminated.
cmderr	[Autorest] Failure during batch task - {"tag":"$(tag)"} -- false.
error	Script return with result [failed] code [1] signal [null] cwd [azure-sdk-for-net]: autorest
warn	Skip package processing as generation is failed
```

**Comment by archerzz** [comment]
The issues seem related to build environment. Both contains the error message `cmderr	[Autorest] No usable version of the libssl was found`. I did some search, and it looks like lack of OpenSSL: https://dev.to/n3wt0n/no-usable-version-of-the-libssl-was-found-solved-2ffa

By the way, those two PRs are for management plane SDKs.

**Comment by JeffreyRichter** [comment]
Of course, issues/problems in the pipeline need to be fixed.
But, I'm also looking for something more here: When someone looks at the PR Checks and sees issues like this how can we know what to do? Is it a problem in the swagger and so that swagger author needs to fix it or is it a bug in the tool and the tool author needs to fix it or something else? Or, should we just always assume it's a tool problem and file an issue in this repo?

**Comment by benbp** [comment]
@archerzz the libssl error is probably misleading. I am seeing instances of it going back at least as far as June before my pipeline log query times out:

![image](https://user-images.githubusercontent.com/1020379/190828058-61d0c1c0-8d60-4d17-ad6e-b19a9a81951e.png)

```
BuildLogLine
| where Timestamp > ago(90d)
| where BuildDefinitionId == "1736"
| where Message contains "No usable version of the libssl was found"
| project Timestamp, Message
| summarize count() by bin(Timestamp, 1d)
| render columnchart
```

**Comment by raych1** [comment]
> Of course, issues/problems in the pipeline need to be fixed. But, I'm also looking for something more here: When someone looks at the PR Checks and sees issues like this how can we know what to do? Is it a problem in the swagger and so that swagger author needs to fix it or is it a bug in the tool and the tool author needs to fix it or something else? Or, should we just always assume it's a tool problem and file an issue in this repo?

@JeffreyRichter , the goal of tool's team is to provide readable and actionable message to PR author/reviewer. In general, the error details and rule details are displayed in the comment of pipeline result in PR. You're supposed to assume it's tool issue and create an issue here if the error isn't clear to user and user has no idea of what to do. Then tooling team will make investigation and improvement.

**Comment by archerzz** [comment]
> 

@fengzhou-msft could you please share your findings here? I remember you mentioned the similar issue happened before. Thanks.

**Comment by fengzhou-msft** [comment]
.NET Track 1 generator (`autorest.csharp` V2) [uses .NET Core 2.0](https://github.com/Azure/autorest.csharp/blob/577856ec9b735fa264a17cafd937ff9d678c97c9/src/autorest.csharp.csproj#L29) (link provided by @archerzz ) which uses OpenSSL 1.0 and is not supported by the current CI agents in swagger pipeline with Ubuntu 20.04.

@raych1 is it possible for the SDKAutomation script to specify a CI agent with lower Ubuntu versions to run the .NET tack 1 SDK generation?

**Comment by raych1** [comment]
@fengzhou-msft , please provide an update if downgrading agent os to ubuntu 1804 works.

**Comment by fengzhou-msft** [comment]
> @fengzhou-msft , please provide an update if downgrading agent os to ubuntu 1804 works.

It works.

**Comment by fengzhou-msft** [comment]
Issue resolved by a short term solution to downgrade the CI system to Ubuntu 18. A long term solution is tracked by https://github.com/Azure/azure-sdk-for-net/issues/31839.
