### ISSUE TITLE
[Asset-Sync] optional `no-cone` support, adjust minimum version of git lower

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#4146]
Right now, we enforce the version `2.37.0`. As I was working through ensuring `git` is present on our docker images, I realized that `2.37.0` is literally the latest version of git.

EDIT after Ben's coment: our minimum version needs to be `git 2.25.0`.

I am not comfortable with mandating that folks need to be on the very latest of ANY tool to run our tool. We should make the inclusion of `--no-cone` optional and based off a quick `git --version` check at Startup. This way we can require a version of git that has `sparse-checkout`, but relax on the `no-cone` side.

**Comment by benbp** [comment]
@scbedd versions < 2.37 still support both `--cone` and `--no-cone` flags, so our sparse checkout logic works in either case. The only change in 2.37.x is that cone mode is the default when no mode is specified (it used to be no cone). So the git commands will work exactly the same whether git 2.36 or 2.37 is installed as long as you manually specify `--no-cone`.

**Comment by scbedd** [comment]
@benbp excellent! So we're future proofed by always specifying!  (cause that's what we do rn)

That means that we just need to relax the version check to one that supports sparse checkout.

**Comment by benbp** [comment]
@scbedd it may be worth investigating the perf of some of the 2.2 versions vs. 2.3. Sparse checkout has been around for a while, but they've been adding a lot more sparse index improvements and command support to git since then, so the differences may be big enough that it's worth setting a higher minimum bar.
