### ISSUE TITLE
[APIView] Introduce lightweight user profile system

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-tools#4164]
There are increasing numbers of opportunities in APIView to do things, if only we knew more about the users in our system. Most notably, we now have two use cases in development where direct email notifications would be beneficial:

1. Tagging users in comments using the `@` tagging notation that we are all familiar with.
2. Requesting reviews from specific architects.

What we lack is a sure fire way of knowing a users email address. What I'm proposing in this issue is that we introduce a very lightweight profile system into APIView - just enough to associate the github user profiles that form the foundation of our auth strategy with details such as email address, theme preferences, etc.

When a user first logs in, if a profile does not exist for them, we should encourage them to set their email address and any other preferences. We can pre-populate the email address with their public GitHub one, if it exists (although I'm guessing many users will have personal email addresses in GitHub that they will want to change in APIView).

We can then write API in APIView to email a certain GitHub username, and look that up in our profile system.

**Comment by Baas-hub** [comment]
@JonathanGiles can you please assign me, @cmcd22 and @Vailorium to this issue?

**Comment by Vailorium** [comment]
@JonathanGiles

**Comment by cmcd22** [comment]
@JonathanGiles
