### ISSUE TITLE
SDK review reminder emails don't link to the right version of the scheduling tool

### ISSUE THREAD

**Issue by kyle-patterson** [Azure/azure-sdk-tools#4177]
In the following screenshot, the link below redirects to the wrong instance of the scheduling tool - it points to the DEV instance, which can't find the meeting ID.

![image](https://user-images.githubusercontent.com/57923303/191318378-a73988a0-62a9-4e27-aced-83854fb29abc.png)

Link in question:
https://web.powerapps.com/apps/db1cda0f-e441-482f-9790-56d053d32ccb?view=editinformational&event=394a7bfb-022e-ed11-9db1-0022480ab176

**Comment by maririos** [comment]
This should be covered by https://github.com/Azure/azure-sdk-tools/issues/7676
