### ISSUE TITLE
SDK review meeting titles are unclear in reminder emails

### ISSUE THREAD

**Issue by kyle-patterson** [Azure/azure-sdk-tools#4178]
Per the screenshot below, I'm not sure what the "None" refers to in the reminder emails. Could you break down the fields into a "key: value" list?

![image](https://user-images.githubusercontent.com/57923303/191318711-997e327e-f9c9-4d78-9946-abf40b7b65c1.png)

**Comment by maririos** [comment]
This has been fixed thanks to issue https://github.com/Azure/azure-sdk-tools/issues/3964
