### ISSUE TITLE
Improve Informational Email templates to include missing information

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#4183]
The templates we are using for the Informational meetings are obsolete now.

There's also information missing, like:
> Please remember that you'll need to provide the meeting requirements documents as explained in this link:

And then no link was provided in the email.

**Comment by maririos** [comment]
We decided GH issue is no longer needed for Informational meeting

**Comment by maririos** [comment]
This will be included with issue https://github.com/Azure/azure-sdk-tools/issues/3788
