### ISSUE TITLE
When an Admin edits a meeting, the outlook event gets updated to a duration of 0 minutes.

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#4189]
If a user schedules a review, and then an Admin goes and updates any information from that review in the Tool, the updated outlook event will have the new information but the duration will change to 0 minutes.

This can't be replicated when the same user who schedule the meeting is the one who updates it.

**Comment by JonathanCrd** [comment]
It turns out this not only happens with admin, the issue can be replicated by updating a meeting but not changing the original datetime. 

The reason why this is happening is because the duration of the event is provided by the Calendar component when an available date is clicked. Since the user didn't perform any action on the Calendar itsefl, the duration is `blank`. Then, on the PowerApp itself, the end datetime is calculated by adding the duration to the `start` datetime, however, since the duration is `blank`, the end datetime ends up being the same as the start datetime.

Some approached to fix this in the Calendar Event Update cloud flow are:

1. Send Null or blank `start` and `end` properties if the date was not modified, and then reuse the existing properties from the retrieved Outlook Calendar event. This would required changes on the App side too, and new variables and conditions in the flow.
2. Just send the `start` datetime,  and calculate the `end` datetime on the cloud flow. We would use the duration from the outlook event and this would require some extra steps in the Update flow, but no redundancy or new conditions. Another advantage is that we can remove the DateTime addition logic from the Apps side.

On the PowerApp side, we don't know the duration of the current event that the user is editting, this information can be calculated using the Outlook event `start` and `end` properties. So I figured out it would be better if the end datetime is calculated on the Cloud Floud.  That's why I ended up taking the 2nd approach.

Now, the Update flow will ignore the `end` property (we might want to delete this from the parse schema once we update all 3 apps). The end date will always be calculated using the current duration of the Outlook Event. 

However, there's an scenario in which I'm not sure if we should do something different: 
What if, when the user reschedule a meeting, the new meeting duration has changed? (Let's say, now API Reviews are 45 minutes long instead of an hour). 
Is this a possible scenario?
Is it expected that the new meeting duration in the new date should change too?

One possible solution for this is to always send a new property `duration` to the cloud flow whenever a new date is selected, and use that in case it is not null. And then if it is not null, it means that the date was not modified so we could simply reuse the existing outlook properties. This approach would introduce more variables and conditions to the flow tho. Do you consider that this would be a better implementation for this bug fix?

Said that, the bug is almost fix for now, I just have to edit the Apps to remove the `end` datetime.
Regarding my question, I'm curious what do you think about the implementation and if that scenario I described earlier is something we should consider.

**Comment by maririos** [comment]
> What if, when the user reschedule a meeting, the new meeting duration has changed? (Let's say, now API Reviews are 45 minutes long instead of an hour).
Is this a possible scenario?
Is it expected that the new meeting duration in the new date should change too?

Not something that happens. So no need to worry about it.

> Now, the Update flow will ignore the end property (we might want to delete this from the parse schema once we update all 3 apps). The end date will always be calculated using the current duration of the Outlook Event.

+1

SAme as you, I prefer option 2 more.

**Comment by JonathanCrd** [comment]
Fixed
