### ISSUE TITLE
Add Test Results to Kusto

### ISSUE THREAD

**Issue by hallipr** [Azure/azure-sdk-tools#4194]
If we ingested details at the test level, we could see the history of a single test as well as a more complete breakdown of the time spent in a test run.

On build completion, we ingest TestRuns into blob storage and Kusto at the TestRun level. This included overall test run duration as well as aggregate counts per test result:

```
"StartedDate": 2022-09-20T22:00:38.233Z,
"CompletedDate": 2022-09-20T22:01:03.76Z,
"ResultDurationSeconds": 0,
"RunDurationSeconds": 250,
...
"ResultCount": 177,
"ResultErrorCount": 0,
"ResultFailCount": 4,
"ResultInconclusiveCount": 0,
"ResultNoneCount": 0,
"ResultNotApplicableCount": 0,
"ResultNotExecutedCount": 0,
"ResultNotImpactedCount": 0,
"ResultPassCount": 173,
```

We don't know which tests failed, and we don't know why this run took 250 seconds.

Preferably, we could query for tests within a run to see which tests took the longest and start forming metrics like time per passing test or visualizing test duration or success rate over time.

**Comment by benbp** [comment]
This would be amazing to have and would unlock a lot of new possibilities (flaky test monitoring, etc.)

**Comment by kurtzeborn** [comment]
Are there concerns here around the cost of including this data in kusto?  It seems like it would be an enormous amount of data.  Maybe we could filter it to only test failures (and assume success if it's not there)?  What about putting into AppInstights (which theoretically would be cheaper) instead of kusto?

**Comment by benbp** [comment]
This will be a good potential item to get some data going before MQ starts, so if we get to do test time/pipeline time improvement work with the dev teams, we'll have a good idea what the highest impact areas are. CC @alzimmermsft

**Comment by scbedd** [comment]
Taking this in honor of the pipelinev3 effort. Definitely useful data to have.

**Comment by scbedd** [comment]
## For the .NET buildId 3271643:

### Existing Files:


- `132264545 bytes` (`132.264545 Mb`) of build log lines across 1419 files.
- `20599 bytes` (`.02 Mb`) of testruns across 23 files.
- `1540020 bytes` (`1.54002 Mb`) of timeline records across 1 files.
- `7819 bytes` (`0.008 Mb`) of build blob records across 1 files.

### Newly Added Files:

internal\2023\11\17\44405910\results.jsonl 447382
internal\2023\11\17\44405912\results.jsonl 444524
internal\2023\11\17\44405937\results.jsonl 234394
internal\2023\11\17\44405940\results.jsonl 468633
internal\2023\11\17\44405954\results.jsonl 443850
internal\2023\11\17\44405957\results.jsonl 442428
internal\2023\11\17\44405959\results.jsonl 442931
internal\2023\11\17\44405961\results.jsonl 467995
internal\2023\11\17\44405962\results.jsonl 566810
internal\2023\11\17\44405968\results.jsonl 444279
internal\2023\11\17\44405972\results.jsonl 470557
internal\2023\11\17\44405983\results.jsonl 482881
internal\2023\11\17\44405986\results.jsonl 483400
internal\2023\11\17\44405987\results.jsonl 444478
internal\2023\11\17\44405993\results.jsonl 482782
internal\2023\11\17\44405995\results.jsonl 453086
internal\2023\11\17\44405998\results.jsonl 470782
internal\2023\11\17\44406001\results.jsonl 477338
internal\2023\11\17\44406002\results.jsonl 441467
internal\2023\11\17\44406116\results.jsonl 500474
internal\2023\11\17\44406142\results.jsonl 473928
internal\2023\11\17\44406235\results.jsonl 441443
internal\2023\11\17\44406237\results.jsonl 461155

For a total of `10486997` bytes or `10.486997` Megabytes of additional storage required per build.

**Comment by scbedd** [comment]
Need to address batching issue in #7617

**Comment by scbedd** [comment]
Shipped and working.
