### ISSUE TITLE
No BreakingChangeReviewRequired label for breaking change

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4199]
I'm still struggling to understand the rules for when the PR pipeline checks will add the `BreakingChangeReviewRequired` label to a PR.

[PR 20762](https://github.com/Azure/azure-rest-api-specs/pull/20762) failed the "Breaking Changes - Cross Version" PR check:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/85643503/191395739-a3c8d15e-ee4c-42e9-ab50-55319fc2cafa.png">

The API has a GA version and a new preview is breaking from that.

The openapi-pipeline-app added labels but not `BreakingChangesReviewRequired`.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/85643503/191396331-924db399-5aec-44c4-81ac-e7e9370f1b02.png">

Why?

**Comment by raych1** [comment]
@jianyexi , can you confirmed if this is fixed?

**Comment by jianyexi** [comment]
fixed
