### ISSUE TITLE
Automation in azure-rest-api-specs repo is adding incorrect labels to PRs

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4220]
The AzureRestAPISpecReview bot incorrectly added the `ARMReview` and `WaitForARMFeedback` labels to [PR 20672](https://github.com/Azure/azure-rest-api-specs/pull/20762) in the azure-rest-api-specs repo. These labels are incorrect because this PR makes no changes to files within a "resource-manager" directory.

<img width="764" alt="image" src="https://user-images.githubusercontent.com/85643503/192278331-98a577ba-cd95-4e3c-8c0d-4afb819961bd.png">

**Comment by mikekistler** [comment]
Another example is [PR 20342](https://github.com/Azure/azure-rest-api-specs/pull/20342)

<img width="750" alt="image" src="https://user-images.githubusercontent.com/85643503/192420813-2d9dc41d-6cb4-4852-83f2-2a22732874aa.png">

**Comment by mikekistler** [comment]
@ruowan Could you please investigate?

**Comment by ruowan** [comment]
Thanks for feedback. We have filter data-plane PR and won't add ARMReview and WaitForARMFeedback for data-plane PR.
