### ISSUE TITLE
Admin should be able to cancel a meeting

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4237]
We need to make sure that admins can schendule meetings. Currently, the only view that allows this is the central "list" view. Only people that created the meeting or were explicitly invited can see the "cancel" button.

We should re-think if that is the right view and/or if there should be a view on the Admin panel that will list the meetings and provide the option to edit/cancel them.

Open to other options as well

**Comment by JonathanCrd** [comment]
This has been resolved in https://github.com/Azure/azure-sdk-tools/issues/3857 by adding a `Cancel` button on the Meetings list in the Admin App.

However, I have 2 questions:

1.  The current message shown in the email and the GitHub tracking issue is: "Cancelled by System Admin". Is this ok? Or would it be helpful to show exactly who cancelled the meeting?
2. Do we want this cancel button to also appear in the Meetings Detail on each app too? Or will the admin app screen be enough?

Please feel free to reopen this issue if we want to implement one of those things I mentioned above.
