### ISSUE TITLE
[test-proxy] Test proxy adds `Content-Length: 0` header to GET and DELETE requests

### ISSUE THREAD

**Issue by timovv** [Azure/azure-sdk-tools#4239]
## Background

One of our service partners is trying to migrate the Azure Batch JavaScript SDK to the test proxy-based recorder. The Batch service uses a [shared-key authentication mechanism](https://learn.microsoft.com/en-us/rest/api/batchservice/authenticate-requests-to-the-azure-batch-service#construct-the-signature-string) which requires calculation of a HMAC signature. This signature is calculated using a number of properties of the request, including the value of the `Content-Length` header. The JavaScript SDK does not add a Content-Length header to GET and DELETE requests. But the test proxy seems to be adding a `Content-Length: 0` header to all GET and DELETE requests. The addition of this header causes the HMAC calculated by the SDK client to not match what the service calculates.

## Issue

This is what I found in my investigation. Feel free to skip to the repro below.

In `record` and `live` mode, the service returns an error with the following detail: 

```
The MAC signature found in the HTTP request '[redacted]' is not the same as any computed signature. Server used following string to sign: 'DELETE\n\n\n0\n\n\n\n\n\n\n\n\nocp-date:Tue, 27 Sep 2022 20:38:38 GMT\n/timovbatch/jobs/JSSDKTestJob/tasks/JSSDKTestJob-task2/files/stderr.txt\napi-version:2022-01-01.15.0'.
```

This string to sign is different from the string the client used to sign, which was

```
DELETE\n\n\n\n\n\n\n\n\n\n\n\nocp-date:Tue, 27 Sep 2022 20:38:38 GMT\n/timovbatch/jobs/JSSDKTestJob/tasks/JSSDKTestJob-task2/files/stderr.txt\napi-version:2022-01-01.15.0
```

Note the additional '0' after the third newline character in the string the client used to sign. This corresponds to the position of where the `Content-Length` header value should be in the string to sign ([see detail](https://learn.microsoft.com/en-us/rest/api/batchservice/authenticate-requests-to-the-azure-batch-service#construct-the-signature-string)).

I intercepted the requests being made to the service. When making a request in _live_ mode, bypassing the proxy entirely, the request is as follows:

```http
DELETE /jobs/JSSDKTestJob/tasks/JSSDKTestJob-task2/files/stderr.txt?api-version=2022-01-01.15.0 HTTP/1.1
Accept: application/json
Accept-Encoding: gzip,deflate
User-Agent: azsdk-js-batch/11.0.0-beta.1 core-rest-pipeline/1.9.3 Node/v16.15.1 OS/(x64-Linux-5.10.102.1-microsoft-standard-WSL2)
x-ms-client-request-id: 302a6aab-fa98-4eaa-a479-1f1c3be8d912
ocp-date: Tue, 27 Sep 2022 21:03:10 GMT
authorization: SharedKey [redacted]
Host: localhost:8080
Connection: keep-alive


```

The upstream request from the test proxy to the service when in record mode, however, looks like this:

```http
DELETE /jobs/JSSDKTestJob/tasks/JSSDKTestJob-task2/files/stderr.txt?api-version=2022-01-01.15.0 HTTP/1.1
Host: localhost:8080
Accept: application/json
Connection: keep-alive
User-Agent: azsdk-js-batch/11.0.0-beta.1 core-rest-pipeline/1.9.3 Node/v16.15.1 OS/(x64-Linux-5.10.102.1-microsoft-standard-WSL2)
Accept-Encoding: gzip,deflate
Authorization: SharedKey [redacted]
x-ms-client-request-id: 38988824-df05-4446-8f47-ddac1d684d6b
ocp-date: Tue, 27 Sep 2022 21:04:06 GMT
traceparent: 00-db07a1fdae4e9e56715537c3f037a9f1-45a978c1ca45f6c8-00
Content-Length: 0

```

Note the addition of the `Content-Length: 0` header. The header is being added by the test proxy!

## Steps to reproduce

This test case I added reproduces the issue: https://github.com/Azure/azure-sdk-for-js/pull/23332.

Note how currently, the tests fail in both record and playback modes, but pass in live mode. You can run the tests against the dotnet test proxy (not in a container) by setting the environment variable `PROXY_MANUAL_START=true`.

Cc: @NickKouds

**Comment by mikeharder** [comment]
This issue is a little complex because `test-proxy` needs to properly mirror two similar client requests:

1. No body, no `Content-Length` header
2. No body, with `Content-Length: 0` header

`test-proxy` cannot disambiguate these requests by only inspecting the body, it also needs to check whether the `Content-Length` header was present on the incoming request.

**Comment by scbedd** [comment]
@timovv I have merged a piece of code that I believe addresses this problem. Once I have a docker image and nuget version published, I'll cut an eng/common PR to make the bugfix available to all the repos (including _your_ repo 👍)
