### ISSUE TITLE
Organize the requirements fields for API Review meeting

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4244]
Currently we are asking the user to provide Core concepts, API Documentation, and Hero scenarios. 
We should:

1. Remove API Documentation field as it is the same as asking for the Swagger PR.
2. Add add a new field alled `Architecture diagram link` (we have this field already in the informational meetings)
3. Reorder the fields to Hero scenarios, Architecture diagram, Core concepts

Note: The current documentation doesn't talk about architecture diagram, so it needs to be updated https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/665/Azure-REST-API-Stewardship-Review

**Comment by maririos** [comment]
@markweitzel could you please update the documentation of the wiki https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/665/Azure-REST-API-Stewardship-Review to reflect the need for the architure diagram?

**Comment by maririos** [comment]
@ladonnaq to follow up with Mark on documentation

**Comment by maririos** [comment]
We will first swap documentation wiki pages by Wed 11/16. Then we will update the fields in the wiki

**Comment by maririos** [comment]
> Remove API Documentation field as it is the same as asking for the Swagger PR.

It has been removed as part of version `1.0.0-beta.11`

**Comment by maririos** [comment]
> Reorder the fields to Hero scenarios, Architecture diagram, Core concepts

Done as part of `1.0.0-beta.11`

**Comment by maririos** [comment]
![Image](https://user-images.githubusercontent.com/9868623/206589727-f7c3ef28-3e06-494b-9096-2840570371a2.png)

**Comment by maririos** [comment]
Remaining work here:
- Add add a new field called Architecture diagram link (we have this field already in the informational meetings)
  - Add field into calendar invite template
  - Add field into GH issue template
- Update wiki documentation to make sure this is reflected too
- Review calendar invite template content and make sure informatio is up to date

**Comment by mikekistler** [comment]
It's find as a request but not a requirement (IMHO).
