### ISSUE TITLE
Update aka.ms/azsdk/onboarding/informational with new Onboarding wiki

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4248]
We will have a new more generic wiki for the Informational meetings. Once it is ready, we need to update this aka.ms link and make sure that it is the one we consume on our scheduling tool and email templates

**Comment by ladonnaq** [comment]
@maririos - I have 2 Azure SDK Informational Meeting wiki pages. 

### Azure SDK Information Meeting 

#### AKA links 

- [ ] Create new AKA for https://aka.ms/azsdk/onboarding/informational, link to wiki page - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/773/Azure-SDK-Informational-Meeting
- [ ] AKA link to the scheduling tool information meeting power app - https://aka.ms/azsdk/scheduleinformational
- [ ] AKA link to the agenda wiki page for Azure SDK Information Meeting - data plane follow-up - https://aka.ms/azsdk/onboarding/dpinfomeeting

#### Conditional triggers for informational meeting agenda for data plane 
IF product ADO work item field or dataverse table field "information mtg data followup" state equals incomplete, THEN use the https://aka.ms/azsdk/scheduleinformational ELSE use https://aka.ms/azsdk/onboarding/informational. 

TODO:  I will open a GitHub issue for Azure SDK Release Planner Beta V1 for the "information mtg data followup" field.

**Comment by maririos** [comment]
It turns out I am not an owner of `https://aka.ms/azsdk/onboarding/informational,` I have requested access to it so I can modify it with the new wiki you created

**Comment by ladonnaq** [comment]
> It turns out I am not an owner of `https://aka.ms/azsdk/onboarding/informational,` I have requested access to it so I can modify it with the new wiki you created

Great, I could not find the link aka tool so did not know who owned it.  :-)

**Comment by maririos** [comment]
Link has been updated :)

**Comment by maririos** [comment]
> Conditional triggers for informational meeting agenda for data plane
IF product ADO work item field or dataverse table field "information mtg data followup" state equals incomplete, THEN use the https://aka.ms/azsdk/scheduleinformational ELSE use https://aka.ms/azsdk/onboarding/informational.
TODO: I will open a GitHub issue for Azure SDK Release Planner Beta V1 for the "information mtg data followup" field.

Sounds good!
So looks like this issue is all done, right?

**Comment by ladonnaq** [comment]
Correct this is done. This issue will have a dependency on the issue I need to open for the "informational mtg data followup".  I will open that tomorrow.

**Comment by ladonnaq** [comment]
I think that we can trigger to use the appropriate template by using a drop-down box for service partners to identify what type of follow-up meeting.   See this GitHub issue - https://github.com/Azure/azure-sdk-tools/issues/3788.
