### ISSUE TITLE
Integrate asset-sync w/ azure-sdk-for-go

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#4257]
Right now, the `start` on record/playback POSTS to the `playback/start` or `record/start` with a json body that looks like:

```
{
  "x-recording-file": "<relative path from repo root to test file>"
}
```

The adjustment to the framework is the following.

1. Starting from the test path, begin traversing upwards along the directories. Checking each level for a `assets.json` file.
2. If an `assets.json` file is found. Save that path.
3. During creation of the POST to `start`, add the found assets.json path as an argument, either relative or absolute.
4. If the repo root is reached without finding an assets.json, abandon trying to find one. Don't send the `x-recording-assets-file` key in the POST body.

Example modified post
```jsonc
// relative
{
  "x-recording-file": "<relative path from repo root to test file>"
  "x-recording-assets-file": "sdk/aztables/assets.json"
}
// absolute
{
  "x-recording-file": "<relative path from repo root to test file>"
  "x-recording-assets-file": "C:/repo/sdk-for-go/sdk/aztables/assets.json"
}
```

**Comment by benbp** [comment]
@scbedd I think we may need to be more flexible regarding relative vs. absolute paths. Relative paths work for a containerized proxy, but absolute paths work for a local process proxy. From the perspective of the test framework, we don't really know which mode the proxy may be running in. I'm musing over a few options:

1. Add a new proxy route that returns some information about the proxy host (e.g. container vs. not)
2. Add a new proxy route that returns information about which kind of path is desired (absolute vs. relative)
3. Support posting both absolute and relative paths and letting the proxy try both
4. Try posting an absolute path from the test framework, if there's a not found failure, try posting a relative path.
