### ISSUE TITLE
Hide the APEX and non-APEX question in the Onboarding Questionnaire blade in Beta V1

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4259]
The APEX or non-APEX question should be hidden in Beta V1.  It is disabled but it is confusing to keep it visible.  

![image](https://user-images.githubusercontent.com/67656762/193139672-109cbfee-73a7-44b0-baf8-432a439adefe.png)

**Comment by live1206** [comment]
Updated in PPE
