### ISSUE TITLE
404 error for "I don't see my SDK package release here" 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4260]
Updates to the UI text label and broken link 

- [ ] Error: In current prototype, 404 error when link was clicked.  

- [ ] Change UI label text: Let's change the sentence to "If you cannot find the SDK package release, click here"

![image](https://user-images.githubusercontent.com/67656762/193142626-d410a30f-6784-4c26-b5ca-683f22476588.png)

**Comment by live1206** [comment]
Fixed in the App
