### ISSUE TITLE
When onboarding questionnaire is submitted, change the ADO field that maps to the launch criteria to complete

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4261]
Updates to the ADO creation power automate flow 

- [ ] When the ADO onboarding work item is created, also change the ADO field that corresponds to the "Onboard with the Azure SDK Team" APEX launch readiness criteria to "Complete"> 

![image](https://user-images.githubusercontent.com/67656762/193145946-470ab466-c491-4f89-8ca0-0a75ca479dbe.png)

**Comment by ladonnaq** [comment]
@live1206 You can assign someone else, but I want to make sure that this task is completed.  This way we don't manually have to update the field to complete.

**Comment by live1206** [comment]
@honghr Could you help update this field? Thanks

**Comment by honghr** [comment]
HI @ladonnaq, Just for management-plane or both?

**Comment by live1206** [comment]
@honghr Management-plane and data-plane tabs are sharing the same field: `Onboard with Azure SDK Team Launch Criteria State`
