### ISSUE TITLE
Option to show all products associated with a service

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4264]
It is weird that the only prodcut available for Cognitive Services is this one. @ladonnaq is there a mapping we are missing?
Or are all not APEX products? 

This is problematic and @live1206 discussed this morning because I have had a couple service team's blocked because the filtering is only retrieving products that are in scope or APEX (showing up in Cloud LIfecycle).  

Scenarios we need to support: 

- New service, product metatdata indicates that the product is out of scope for APEX.  This could be an error by service team when entering information in service tree but we need to let them onboard to validate. 
- Service partner could be creating a release plan to complete work for an extension. In this scenario, the product is GA and may not show as in scope for APEX anymore.  However, the product has an extension for releasing Beta or Stable SDKs.  They need to use the application to create release plan to complete the work for the extension. 

<img width="461" alt="image" src="https://user-images.githubusercontent.com/9868623/193322374-794e15a0-a91e-4cd2-8dd8-8cdebe28e88e.png">

**Comment by ladonnaq** [comment]
@maririos  I am waiting to test after the re-design that I requested.  Currently, the dataverse is only retrieving the data for the product's "target lifecycle".  As I explained in several comments in the Beta V2 requirements document, this is not what we want to do.  As you can see in your example, you can't find the other products for Cognitive Services.

**Comment by maririos** [comment]
Do you have the issue with the re-design? 
When I looked at the code, it does retrieve accoding to target lifecycle values: Private Preview, Public Preview, and GA

**Comment by ladonnaq** [comment]
I noticed that I am still not seeing all of the products that I know have outstanding work.  We need to relook at the logic.  For example, existing extensions.  We have service partners that have existing extensions. If the product is showing as in GA, I don't think that the product is going to show up in the drop down box.  We could potentially have a check box that states "I can't find the product".  Then we either show a drop down box with all products associated with that service or we let the user enter the product service tree identifier.

**Comment by maririos** [comment]
I see. Currently the mapping is: Service has ARM data, Product target lifecylce is Private Preview, Public Preview or GA. If there are additional things that we should look into, let us know the specifics and we can adjust.
FYI @live1206

**Comment by josefree** [comment]
reassign to @live1206 to take a quick look if this is fixed

**Comment by live1206** [comment]
The behavior is not changed.
We have not changed the logic of how we fetch the mapping products for the selected service.

**Comment by ladonnaq** [comment]
Scenario: New service, product metatdata indicates that the product is out of scope for APEX.  This could be an error by service team when entering information in service tree.  Or the service partner could be creating a release plan to complete work for an extension.  

Suggested resolution:

- Change the current implementation to not just include products that are currently in scope for APEX (i.e. not completed ring onboarding, already GA but have extensions for SDKs, working on new functionality that may not be in scope for APEX but requires new APIs/SDKs, ...)
- 
-  If we think the list of products will be too long, then we could default to APEX. Have a checkbox that can be selected if the product is not found. Show the products associated with the service that are not currently in scope for APEX.
- 
-  When user submits the onboard form, pop-up the schedule information meeting (we would want to talk to them and understand their scenario so we can make sure we have a release plan type for the work they are doing.)
- 
-  Create ADO work item and tag "validate out of scope of APEX".

**Comment by ladonnaq** [comment]
This GitHub issue is related (covering slightly different scenario) - https://github.com/Azure/azure-sdk-tools/issues/4918

**Comment by live1206** [comment]
> Scenario: New service, product metatdata indicates that the product is out of scope for APEX. This could be an error by service team when entering information in service tree. Or the service partner could be creating a release plan to complete work for an extension.
> 
> Suggested resolution:
> 
> * Change the current implementation to not just include products that are currently in scope for APEX (i.e. not completed ring onboarding, already GA but have extensions for SDKs, working on new functionality that may not be in scope for APEX but requires new APIs/SDKs, ...).  We should show all products, not just offerings.  We need to show skus and features too.
> * If we think the list of products will be too long, then we could default to APEX. Have a checkbox that can be selected if the product is not found. Show the products associated with the service that are not currently in scope for APEX.  This may be very long list - we could have user select offering then show skus and features that map to the offering.
> * When user submits the onboard form, pop-up the schedule information meeting (we would want to talk to them and understand their scenario so we can make sure we have a release plan type for the work they are doing.)
> * Create ADO work item and tag "validate out of scope of APEX".

@ladonnaq I want to further clarify this scenario.
Right now, we do not filter products based on `the scope for APEX` or `ARM namespace`. 
**As long as the product exists in CLC and service tree, and there is a mapping between the product and user service in service tree**, the user should be able to select the product. 
Given this, are we still missing the products for this scenario?

**Comment by ladonnaq** [comment]
@live1206 @maririos - This issue is blocking Cadl + DPG teams that have already met GA but have an extension (which is not tracked well in Cloud Lifecycle so we are manually tracking via our Azure Devops work items).  Let's talk next week so we can figure out how to resolve this issue.

**Comment by live1206** [comment]
@ladonnaq 
Could you provide the latest missing product and corresponding service? 
Do you mean the product is missing in Release Planner is due to product missing in CLC?

**Comment by ladonnaq** [comment]
> @ladonnaq Could you provide the latest missing product and corresponding service? Do you mean the product is missing in Release Planner is due to product missing in CLC?

Most of the cognitive products have met GA so they are not showing up in the drop-down list in "create a release plan".  I will add a list of the products with the CLC and Service Tree links so you can figure out how to best ensure they are in the drop-down list.

**Comment by live1206** [comment]
@ladonnaq Thanks for the clarification!
There is a filtering that products in CLC should target `Private Preview`, `Public Preview` or `GA`. I will remove this restriction, so that all the existing products will show up in the drop down list.

**Comment by live1206** [comment]
@ladonnaq Removed the filtering, deployed to Prod, all the existing products in CLC should be available in the drop-down list now.

**Comment by ladonnaq** [comment]
@live1206 This seems to be working. I can find the products for Cognitive.  We just need to make sure that service partners know to look in service tree to choose the correct services. For example, Multivariate Anomaly Detection is mapped to it's own service, which is Anomaly Detector. So if they choose Cognitive Services they would not find their product.  I will close issue for now and if we get reports of user's not finding their product we can re-open or create a new GitHub issue.
