### ISSUE TITLE
Communicate next steps when a service is not present

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4265]
What should a user do if their service is not listed here? Should we add a hint/message/label/etcx with instructions?

<img width="625" alt="image" src="https://user-images.githubusercontent.com/9868623/193323829-9da0e35d-0667-44c3-9368-8fbb5cd659ac.png">

**Comment by ladonnaq** [comment]
We have another related GitHub issues for this problem.  I think we agreed that a checkbox that states "I cannot find service".  Then the user is presented with a field that they can use to enter the service tree identifier for the service.

**Comment by josefree** [comment]
@honghr and @live1206 I wonder if this is solved in November release?

**Comment by josefree** [comment]
I wonder this is a duplicate issue of https://github.com/Azure/azure-sdk-tools/issues/4295

**Comment by live1206** [comment]
There should not be any missing service for the user anymore, we can close this as resolved.
And this is not the same as #4295
