### ISSUE TITLE
Improve documentation about APEX Launch-Readiness

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4266]
Current app says:
<img width="682" alt="image" src="https://user-images.githubusercontent.com/9868623/193325022-5e8faf21-62da-4d3b-bda5-c6ed6a9a4afd.png">

Looking at the page: https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37799/APEX-Launch-Readiness-(PLR) I am lost at what should I do when looking at this page. It will be good to improve the documentation to explain what APEX Launch-Readiness is and steps or other information

**Comment by ladonnaq** [comment]
This UI is not in Beta V1 or Beta V2.  It may surface again when we support non-APEX products.  The page you found is the table for all of our APEX launch criteria (not APEX program).  We can add information at the top of the page that directs to the APEX wiki.

**Comment by maririos** [comment]
We can close this issue for now. If needed in the future, we can re-open
