### ISSUE TITLE
Network error when looking for an existing SDK package

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4267]
AS I was typing Text Analytics in the SDK search field, this error appeared:
<img width="1490" alt="image" src="https://user-images.githubusercontent.com/9868623/193325389-a8b022d7-f629-4b20-82b8-3b161dfdf9d5.png">

**Comment by honghr** [comment]
@maririos I cannot replicate this issue. But According to your screenshot, I suppose that your network is unstable and the page fails when loading data.

**Comment by maririos** [comment]
Hmmm I couldn't repro it again. Closing issue
