### ISSUE TITLE
Error when submitting questionnaire

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4268]
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/9868623/193326506-95484123-32c2-4367-9f10-b7ad042ed19b.png">

**Comment by maririos** [comment]
Seems like a flow is turned off in PPE. I am taking a look

**Comment by maririos** [comment]
Both parent and child flows are on in PPE

**Comment by maririos** [comment]
@JonathanCrd could you take a look and see if something pops for you on why this is happening?

**Comment by maririos** [comment]
It actually might be a bug. If I select yes for any option, then it works.

**Comment by JonathanCrd** [comment]
@maririos I was not able to replicate the problem, I also see that both flows are turned on in PPE and then have been running succesfully in the past days.

**Comment by honghr** [comment]
@maririos I also cannot replicate the issue. Can you try again? If you can get this error, please ping me

**Comment by maririos** [comment]
Thank you all. Couldn't repro. Closing isue
