### ISSUE TITLE
Consolidate Contact Us/report a bug pages between Release Planner and Scheduler apps

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4269]
It will be good to have both apps feel the same, so expose information similarly.
See different approaches:
![image](https://user-images.githubusercontent.com/9868623/193327346-e689a023-42a9-4d62-b00c-c2726020a314.png)

As for the Release Planner app reporting a bug on Github, we should tell them the repo and to add the `Engagement Experience` label.

FYI @ladonnaq @josefree

**Comment by josefree** [comment]
Agree. Let me bring this to engineer for triage

**Comment by josefree** [comment]
team channel: https://teams.microsoft.com/l/channel/19%3a59dbfadafb5e41c4890e2cd3d74cc7ba%40thread.skype/Engineering%2520System%2520%25F0%259F%259B%25A0%25EF%25B8%258F?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47
GitHub Issue: https://github.com/Azure/azure-sdk-tools/issues/new

**Comment by josefree** [comment]
For GitHub Issue, I wonder if we would create an Github issue template, so that the feedback can directly flow into Engagement Service project with some context infor.  Some questions in the template maybe

-	Category: Bug report, Feature requirement
-	Which app: General, Release planner, API spec readiness, SDK release
-	Description
-	Screenshot

**Comment by maririos** [comment]
This issue is realted to https://github.com/Azure/azure-sdk-tools/issues/4642 

- For teams channel the conclusion was to use the Onboarding channel. The Scheduler Tool has already been updated to reflect that. I am unsure about the status of the Release Planner App.
- Love the idea about the Github issue template :)

**Comment by honghr** [comment]
Hi @maririos , The screenshot you posted in Scheduler app is not contact us page. It's bug reporting page. I looked at the contact us page in Schedular app.
![image](https://user-images.githubusercontent.com/88764852/204450352-a71bda1b-8a13-4e08-83a0-13c481964b95.png)
So, Did you want to us follow the page to update contact us or add a new page for bug reporting?

**Comment by honghr** [comment]
Updated to 'Report a bug' page in Release planner app, API readiness app and SDK release app.

**Comment by maririos** [comment]
thanks @honghr . @ccbarragan is adding this screen into her UI design so we can have the best experience for our users
