### ISSUE TITLE
Improve text for pop up to schedule an informational meeting

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4270]
Wording and ending in `?` could be improved. What about changing `?` to `.` and add `We recommend for you to schedule an Informational meeting with our team to better understand your needs`. @ladonnaq is this ok? Feel free to correct in any case

<img width="704" alt="image" src="https://user-images.githubusercontent.com/9868623/193332350-3e9d601a-0e4c-4b2c-be6a-9f0d535ecbd8.png">

**Comment by josefree** [comment]
Let me bring this to triage

**Comment by josefree** [comment]
@ladonnaq would you propose a new text here. Then @honghr could pick up for revise.

**Comment by honghr** [comment]
@ladonnaq Any update?

**Comment by ladonnaq** [comment]
@honghr   How about this?  

![image](https://user-images.githubusercontent.com/67656762/207092639-9871ce54-01e3-4b2f-a5cc-4cfece244917.png)

**Comment by honghr** [comment]
@ladonnaq I think that's good. Will be changed to it.

**Comment by honghr** [comment]
![image](https://user-images.githubusercontent.com/88764852/207293212-82ce51d2-a0a3-41b7-bb0f-c9b893da9b06.png)
 Done for this issue.

**Comment by ladonnaq** [comment]
Thanks @honghr!
