### ISSUE TITLE
Incorrect Scheduler app loaded from Release Planner app

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4271]
When a user says `Unsure` on the Release Planner app, they have the suggestion to schedule an Informational meeting. When clicking on the button, the general scheduler app is loaded. https://apps.powerapps.com/play/e/a49cfcc0-87c2-469b-9516-da85bf6474e6/a/b406d8d6-06b2-4738-be7b-1edf716799cb

The one loaded should be the Informational Meeting: https://apps.powerapps.com/play/e/a49cfcc0-87c2-469b-9516-da85bf6474e6/a/15dbe239-cb18-4171-902e-23a77f3f3ff0

Also, if we already know the service name, we should populate that in the Informational meeting so the user doesn't have to do that again

**Comment by live1206** [comment]
@maririos Updated to schedule an informational meeting.
How can we pass along the selected service to the informational meeting page?
As I can see, the scheduler tool only accept `eventID` in the URL query: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/728/Scheduler-Experience-App?anchor=additional-information

cc @JonathanCrd

**Comment by maririos** [comment]
You will need to add an entry on Data verse with the information you have. See more information here: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/728/Scheduler-Experience-App?anchor=integrate-the-scheduler-app-with-another-powerapp

**Comment by live1206** [comment]
The service is pre-selected in the informational meeting page now, change deployed to PPE.

**Comment by maririos** [comment]
Yes!!! woohooo
The only thing to note is that youa re targetting PPE scheduler app whcih is good for now and I like that both apps are targeting same environment. IS the idea that when Release planner moves to Prod that the link will be for Scheduler prod too?

**Comment by live1206** [comment]
Yes. Release Planner in Prod will link to Scheduler Prod.
