### ISSUE TITLE
Update change log is adding existing version

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#428]
Update change log script is triggered automatically after release and this has caused an issue for java package if someone manually edits change log without updating the version to prepare for the release. Scenario is as follows:

- Change log for package pkg1 is updated with new version manually and didn't update the version in centralized version file.
- package pkg2 is released and this triggers auto version bump and change log update
- Version bump tool calls update change edit script for all packages and it triggers this for pkg1 also with old version in centralized version file.

Update change log script currently compares against only latest version and adds version passed as arg to change log if it doesn't match.

Fix: We should search and make sure version is not present in change log before adding instead of just comparing against latest version in log.

**Comment by weshaggard** [comment]
@praveenkuttappan could you please link the PR to this issue?

**Comment by praveenkuttappan** [comment]
@weshaggard  linked PR now.
