### ISSUE TITLE
Multi sources support for iOS APIView tool

### ISSUE THREAD

**Issue by vhuseinova-msft** [Azure/azure-sdk-tools#4281]
Currently, APIView tool for iOS can support only 1 of the following: file, folder, framework. As a git repo can contain more than 1 product, some products can share some common code that will be located outside of the project folder.

<img width="493" alt="Screen Shot 2022-10-03 at 3 01 39 PM" src="https://user-images.githubusercontent.com/98852890/193693906-474d1fd1-7a17-4333-9fb1-e096d606a092.png">

Because of this, iOS APIView can be generated:
- only for part of the public code - a couple of APIView will need to be used in this case and it won't be easy to see the full picture of public API.
- including other products - where it will take some time to remove the other products or it would be mix of everything
- from a framework file - some of the annotations don't match between a framework APIView and a folder one, and his can lead to some misunderstanding in APIView

Please provide an option to support a couple of sources paths for iOS APIView tool.

**Comment by tjprescott** [comment]
For cases where projects share common code, you should use the framework option.

**Comment by tjprescott** [comment]
Closing this issue, as this is supported using the framework option.
