### ISSUE TITLE
Link to create GitHub Issue from APIView comment is not working

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4288]
APIView allows to create an issue in GitHub from APIView comment, It opens GitHub new issue page with prefilled information when you  click on a language. This link is broken when you click on language button in comment panel from review page but works fine from conversations page.

**Comment by chidozieononiwu** [comment]
As far as I can see there is no issue here. Can you check to see if this is still an issue.

**Comment by chidozieononiwu** [comment]
I will go ahead and close this. Feel free to reopen it if you think it's still an issue.
