### ISSUE TITLE
Current design will block users with products that do not map to a service in service tree. 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4295]
Current design will block users with products that do not map to a service in service tree. 

Not all products in service tree map to a "service".   Some services map to SGs (Service Groups).   We need have an option to select a Service Group if a user can't find the services.  This is not the standard scenario but we have had several products we are working with that will be blocked from accessing the application, so we need to resolve for Beta V1. 

1. Suggestion a (if accessing the SG data is not too difficult): 
Have an option on the panel for a user to check "The product does not map to a service in service tree".  Then ask the user to pick a Service Group from a drop-down menu. 

1. Suggestion b (if accessing the SG data is too difficult): 

Have an option on the panel for a user to check "The product does not map to a service in service tree".  Show and ask user to select the offering associated with the product drop-down profile for offerings only and the Azure SDK Release Planner will be bound to the offering not the service. 

This is the current UI design. 
![image](https://user-images.githubusercontent.com/67656762/193927666-54e24065-df9d-43d3-809d-1584ae908a20.png)

![image](https://user-images.githubusercontent.com/67656762/193927816-fad7165d-a35f-43e6-badb-cb81f4c72b7b.png)

Example of a product that does not map to a service in service tree.  

![image](https://user-images.githubusercontent.com/67656762/193928474-4c8ca4d3-9dd7-48df-9a03-b76ad0e7cd81.png)
![image](https://user-images.githubusercontent.com/67656762/193928598-89d64357-20f9-4382-ba46-5dd30ad51314.png)
![image](https://user-images.githubusercontent.com/67656762/193931256-3219e6e0-cdb0-47f2-b811-273491ae2096.png)

**Comment by josefree** [comment]
let me bring this to triage

**Comment by live1206** [comment]
This is a corner case. We postponed the design until we figure out more details of requirements. Re-assign to PM

**Comment by ladonnaq** [comment]
I am closing this GitHub issue.  Services that do not have product entries in service tree are no longer blocked from onboarding.
