### ISSUE TITLE
doc-warden looks for readmes above the packages on .NET

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-tools#43]
Storage has four packages they like to work on in one meta *.sln file.  doc-warden thinks there should be a readme next to the meta *.sln.  This caused a failure at https://dev.azure.com/azure-sdk/public/_build/results?buildId=30620

Should we be looking for *.csproj files instead of *.slns via `get_net_packages` instead of `get_net_package_roots` at https://github.com/Azure/azure-sdk-tools/blob/master/packages/python-packages/doc-warden/warden/enforce_readme_presence.py#L56?

I'm adding an exclusion for now and not blocked by this.  Thanks!

**Comment by annelo-msft** [comment]
We are looking for .csproj files per: https://github.com/Azure/azure-sdk-tools/blob/3ba3c0aa471b7fbd4d60c792685350fac85a97fc/packages/python-packages/doc-warden/warden/warden_common.py#L19

I believe this resolves this issue, @tg-msft please re-open if it does not.  Thanks!
