### ISSUE TITLE
Consider updating the TagPrefix in assets.json to match the sparse checkout path

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-tools#4300]
Here's an example of an initial assets.json created in the azure-sdk-for-java\sdk\attestation directory, the way things are today
{
  "AssetsRepo": "Azure/azure-sdk-assets-integration",
  "AssetsRepoPrefixPath": "java",
  "TagPrefix": "java/attestation",
  "Tag": ""
}
The TagPrefix definition `"<Language>/<ServiceDirectory>" or "<Language>/<ServiceDirectory>/<library>" or deeper if things are nested in such a manner.` 

TestProxy, CLI call will use the language and the relative path from the root repository to the assets.json file for the sparse checkout path. In this case it'll use `sparse-checkout set --no-cone java/sdk/attestation`

The recommendation is to update the TagPrefix to be the same as the sparse-checkout directory. It'll make discoverability easier and keep things consistent between the two.

**Comment by kurtzeborn** [comment]
Not sure if this goes to you Jim or Scott.  Please reassign if I got it wrong.

**Comment by benbp** [comment]
@scbedd @JimSuplizio is the actual command `sparse-checkout set --no-cone java/sdk/attestation`? If so, we can just use cone mode as we only need non-cone if globs are being used (which will be unnecessary after we migrate to asset sync).

**Comment by JimSuplizio** [comment]
> @scbedd @JimSuplizio is the actual command `sparse-checkout set --no-cone java/sdk/attestation`? If so, we can just use cone mode as we only need non-cone if globs are being used (which will be unnecessary after we migrate to asset sync).

Yes, the sparse-checkout path is java/sdk/attestation but the TagPrefix is java/attestation. The suggestion here is to make them the same.

**Comment by scbedd** [comment]
Closing the issue. While I don't think there will be any fallout to this change, I also don't feel that there is any real benefit to taking it.

If someone insists later on or submits a PR, I won't push back tho. 👍
