### ISSUE TITLE
Can't upload an ApiView file more than 50MB.

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-tools#4304]
When I upload an ApiView file to create a review, and the file is >50 MB, I get HTTP 413 "Request entity too large".
Maybe it has something to do with some server settings, where the app is deployed on.

**Comment by antkmsft** [comment]
Maybe this will help: https://techcommunity.microsoft.com/t5/iis-support-blog/solution-for-request-entity-too-large-error/ba-p/501134

**Comment by mikekistler** [comment]
Changes in the parsers have reduced file size such that this should be a rare problem, so reduced priority to low.

**Comment by praveenkuttappan** [comment]
We no longer need to upload C++ ast file. Marking this issue as closed.
