### ISSUE TITLE
[stress testing] Pass docker build args/env vars from scenario matrix

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#4305]
Since a lot of the test parameters end up just being baked into the customized dockerfile for the test scenario (as opposed to via command line params or environment variables), we will get more utility out of the scenario matrix generator if we also passed in the matrix parameters to the docker build step.

CC @ckairen @richardpark-msft

**Comment by richardpark-msft** [comment]
One example we discussed as swapping out the base image to use different runtimes (ie, multiple versions of Python, different .NET framework runtimes, different versions of Go for the build image, etc..)
