### ISSUE TITLE
Support creating manual API review for CADL

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4306]
Add CADL manual API review gen in APIView

**Comment by tjprescott** [comment]
Is this the file where you need the commit hash? Would this also enable PR and automatic APIViews?

**Comment by maririos** [comment]
@praveenkuttappan please correct me if I'm wrong but the work for enabling CADL APIView generation from PR is issue https://github.com/Azure/azure-sdk-tools/issues/3991

**Comment by praveenkuttappan** [comment]
> Is this the file where you need the commit hash? Would this also enable PR and automatic APIViews?

This one is to take URL to CADL file as input and generate api review. This is not to enable auto review gen from PR.
