### ISSUE TITLE
Add a tooltip or similar for Contact us when service needs a special time request

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4324]
The way it is right now, if the service can't accomodate to our dates, they need to go to the left panel and click in `Contact Us` or email/text a PM they know about to request for a differnt time slot.
We could add something in our UI with that message:
<img width="623" alt="image" src="https://user-images.githubusercontent.com/9868623/194393348-3d797df7-d059-4157-ac72-35233582c254.png">

**Comment by ladonnaq** [comment]
This was feedback from early releases of the Scheduling Tool.  Re-evaluate for future releases if and how this feature would be implemented.

**Comment by JonathanCrd** [comment]
I have added a label with a hyperlink to the 'Contact Us' section below the calendar.
