### ISSUE TITLE
Service names not appearing in list

### ISSUE THREAD

**Issue by kyle-patterson** [Azure/azure-sdk-tools#4331]
Several service names seem to be missing from the service list, such as Azure Communication Services, Azure Storage, and Azure Web PubSub...

**Comment by kyle-patterson** [comment]
Azure SDK appears to be missing as well

**Comment by maririos** [comment]
Interesting. The service names are comming from Service Tree. @ladonnaq how do we handle this? Do these services have another "Service Name"?
Is Azure SDK another Service Name? or you mean our team?

**Comment by maririos** [comment]
This is a limitation that we have with the data we are getting. @ladonnaq is looking into this to see how we can get unblock

**Comment by maririos** [comment]
FYI this is also needed for the other scheduler apps and fro the Release Planner App

**Comment by maririos** [comment]
While we figure this out, we can add an input field for it

**Comment by maririos** [comment]
@kyle-patterson and @ronniegeraghty 
With the dev team we have been looking and all services are listed in our app. For example:
- Azure Communication Services is called `IC3 ACS Resource Provider` https://servicetree.msftcloudes.com/?pathSet=true#/ServiceModel/Home/5b23174b-8c6d-467d-862d-a3f24958fb74 . You can see how they succesfully schedule a meeting using the scheduler app for 10/19
- Azure Storage looks to be named `Azure Storage Mover` https://microsoftservicetree.com/services/c88bf702-9a3e-4962-a15d-dbc3c3a8f42f
- Azure Web PubSub : this is the product name. The service name is `Azure SignalR Service` https://microsoftservicetree.com/services/624c481d-e51c-4016-a522-fbe180d125fc/products

**Comment by kyle-patterson** [comment]
- Azure Storage Mover is not the same as Blobs, Files Shares, etc; it's just a migration tool for Storage resources
- For Azure SDK, we need a means of blocking days for things such as Azure Core. We do have a service tree instance that isn't showing up, I can provide that offline
- For Web PubSub and ACS, this seems confusing and disjointed from the experience we already have; friendly names are preferred to service tree names, which cannot be changed :( I think it falls outside the scope of our tool, which is just depending on service tree, but it's not intuitive...

With this in mind, there should be a way for service teams to onboard their service if it's not listed, or maybe rename existing services (in our tool) - perhaps through a provided service tree ID?

**Comment by maririos** [comment]
- Storage: My bad. According to the description I thought that was it.

Ok so I created issue  https://github.com/Azure/azure-sdk-tools/issues/4469 and will discuss design to see if/how we can enable user to input Service Tree Id if needed.

I aggree that farther along the way we can consider leveraging the information we have been coleted and cleaning and instead of asking for Service/Product name, we can ask for the specific SDK they want to talk about.

**Comment by maririos** [comment]
> For Azure SDK, we need a means of blocking days for things such as Azure Core. We do have a service tree instance that isn't showing up, I can provide that offline

Great! We need to make sure information in Service Tree is correct so we can go ahead and consume it.
cc @ladonnaq as she is the expert with Service Tree :)

**Comment by maririos** [comment]
Closing this issue as there is no action to take for us here.
