### ISSUE TITLE
Azure SDK information meeting email template 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4333]
Requirement: Meeting title = Azure SDK information meeting + product name 

Requirement: body of the email invite 

Thank you for scheduling an Azure SDK information meeting.  

This meeting is designed to help service teams who are engaging the Azure SDK team to complete APIs/SDKs for new APEX products, which may require new APIs or new API version and new or new SDK versions. 

This meeting can be updated only through the scheduling app [here](https://aka.ms/azsdk/scheduleinformational).

Please complete the pre-requisites below 48 hours prior to the day/time of the scheduled meeting.  

## Prerequisites

|Title | Importance | Brief Description | Example |
|:-----:|:-------------:| :-------------:|  :-------------:| 
|Onboard with the Azure SDK Team | Must Have- Required 48 hours prior to the start of the meeting |Completed [Azure SDK Onboarding survey](https://aka.ms/sdk-apex). | N/A
Architecture Diagram (new offerings) | Must Have - Required 48 hours prior to the start of the meeting for new offerings| Provide the architecture diagram of your service | [Example](https://github.com/Azure/azure-sdk-pr/blob/main/onboarding/architecture_diagram.png)|
Link pull request (PR) or to the existing Cadl or Open API doc (Swagger)| Nice to have | Specification of the Rest API service | [Example](https://github.com/Azure/azure-sdk-pr/blob/main/onboarding/Core_Concepts.pdf)

## What to expect during the informational

 <span style="color:red;font-size:12px">Note: These are some of the main things that get covered during the review but every review has it's own circumstances and more areas can be discussed.<span>

|Title| Description|
|:-----:|:-------------:|
Discuss API/SDK scenarios | Determine the information needed the actions needed for the product team to complee the Azure SDK launch criteria.  
Process walkthrough | The team will be introduced to appropriate documentation and checklist they need to complete the work needed to APEX launch criteria. 
Launch Readiness | Review Azure SDK launch criteria https://aka.ms/azsdk/apex/launch-criteria, discuss timelines and expectations.

## Contact Us

<span style="color:purple">Admins Email Alias:</span> azsdkapex@microsoft.com
<span style="color:purple">Teams Channel (Online 4:00am-3pm PST, Monday - Friday)</span>: [Teams Channel Link](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Engage%2520with%2520us%2520-%2520AzureSDK%2520Team?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)

**Comment by ladonnaq** [comment]
@maririos I will finish this up later this evening.  I need to add email templates.

**Comment by maririos** [comment]
Two questions:
- We cuerrently don't have product name in the scheduling tool (issue chuchuchu ) so what about service name?
- The format for the other meetings is `[Service name - sub service/ product name] - <name of meeting>` would you like to follow this format too?

**Comment by ladonnaq** [comment]
I will open a requirement to change the scheduling tool blade and logic. We should have the drop-down box for product. I sent you an email Wei sent to Ronnie and Sandeep regarding using dataverse for the dashboard they built. Wei is also getting data from Cloud Lifecycle Kustos tables.  Until we implement the product box you can use service. We can update later.

**Comment by ladonnaq** [comment]
Format is fine for now but I do want product when it is implemented.

**Comment by maririos** [comment]
Ohh so preference is to have product over service. Got it. 
Yes we can do service for now, and once we have product then move with that.

Thank you!

**Comment by ladonnaq** [comment]
> Ohh so preference is to have product over service. Got it. Yes we can do service for now, and once we have product then move with that.
> 
> Thank you!

Yes that is correct! Thank you! I will add the email reminder info in the morning.

**Comment by maririos** [comment]
Tables updated:
- Reference Documents:
  - Core Concepts document guidance link
  - Architecture document guidance link
  - Informational Meeting - Wiki Link
- SDK Email:
  - Informational Meeting Confirmation Email
- Event Settings: add Teams channel link -> this should be done from the Admin app

**Comment by maririos** [comment]
Template has been updated and published in the DEV app. @ladonnaq I sent you the email so you could take a look and give me feedback :)

**Comment by maririos** [comment]
It will go as is until hearing different

**Comment by maririos** [comment]
Tables were updated in PPE end of last week
