### ISSUE TITLE
Language repositories are going to need .assets added to their respective .gitignore files

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-tools#4338]
When a user executes test-proxy restore -a <pathToAssets.json>\assets.json, by default it'll create an **.assets** directory in the root of the repository. Git status shows this as untracked and it shouldn't be showing up at all.
```
> git status
On branch main
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .assets/
```

**Comment by JimSuplizio** [comment]
@benbp is going to be adding the .gitignore to Go since he's already working on an assets PR.

**Comment by benbp** [comment]
Go PR that includes the gitignore change: https://github.com/Azure/azure-sdk-for-go/pull/19322

**Comment by scbedd** [comment]
@JimSuplizio completed this. When we closed the issue during scrum it didn't close it automagically. Doing that here.
