### ISSUE TITLE
ACS Calling needs to be migrated to use unified pipelines

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#4340]
Currently, the only language for the AzureCommunicationCalling library that goes through our unified pipeline is iOS. All tier1 languages use the partner pipeline for release. This results in Calling releases bypassing a crucial SDK quality check--the APIView gating mechanism for GA versions.

Calling releases as binaries because they essentially wrap C++ libraries, but we should still route them through the unified pipeline for release to ensure that GA releases have been approved by the ArchBoard. 

cc/ @praveenkuttappan

**Comment by weshaggard** [comment]
@tjprescott do you know how they release today? Are they using the partner release pipelines?

**Comment by gaobob-msft** [comment]
@weshaggard yes we use the partner release pipeline. @tjprescott are there instructions/wiki anywhere on how to migrate to the unified pipeline?

**Comment by weshaggard** [comment]
In order to move the unified pipeline you would need to move the code into our public mono repos and build and release from there. If you cannot do that for some reason I'd like to better understand but then your only option is to use the partner release pipeline which currently doesn't support the APIView check.

**Comment by weshaggard** [comment]
Ok So the question would be do we want to start blocking partner release pipeline on APIView check. I think that may cause a lot of issues. There are a number of teams using that for releasing that for track 1 libraries aren't working with our team for API reviews and we would end up blocking them and/or cause more work on our team to review those.

So what is the suggestion here?

**Comment by tjprescott** [comment]
My suggestion would be:
1) yes add APIView gate release check to partner pipelines
but
2) we specifically opt services into that check. Right now it would just be the ACS Calling and UI libraries, I think. That way all those services for which it doesn't make sense aren't unnecessarily blocked.

**Comment by kurtzeborn** [comment]
We can't do this for all packages.  This is a case where communication is happening outside of the system and then trying to enforce those special cases with ApiView.  In this case, the package is not released through our normal system and process.  It is released using our partner release pipelines and we don't do this level of enforcement in those release systems.
