### ISSUE TITLE
Consider adding the ADO workitem in warning message

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4345]
When this warning message is displayed, it will be good to include the ADO workitem link so the user can look at the information adn then decide what to do:

<img width="545" alt="image" src="https://user-images.githubusercontent.com/9868623/194886251-d06bbf13-9fa7-41be-9e0f-50b5181436e6.png">

**Comment by maririos** [comment]
Another question: Will I get the warning if the issue was closed?

**Comment by honghr** [comment]
resolved
