### ISSUE TITLE
Test Proxy asset transition script should enforce minimum test proxy version

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#4352]
I just tried running the asset transition script, and since I've been using/testing proxy via docker, my actual test proxy binary version is many months old. This resulted in the `restore` command "hanging" because the sub-command was ignored and it started just running the test server instead (but the logs were swallowed so it just appeared to hang).

We should check a minimum version via `test-proxy --version` and log a link and/or command to update to the latest version (or install it automatically).

CC @scbedd @JimSuplizio

**Comment by scbedd** [comment]
Minimum test-proxy version should be `1.0.0-dev.20221007.3` IMO.

This is the latest version that has the fixed `buffer` problems AND Jim's `--tags` fix.

**Comment by JimSuplizio** [comment]
> Minimum test-proxy version should be `1.0.0-dev.20221007.3` IMO.
> 
> This is the latest version that has the fixed `buffer` problems AND Jim's `--tags` fix.

@scbedd We're going to need the test-proxy that uses the CLP version changes that were [checked in today](https://github.com/Azure/azure-sdk-tools/pull/4366) in order to do the version check. Pre-CLP version, the --version will spit out the version but also start the proxy which we don't want here.
