### ISSUE TITLE
AzureRestAPISpecReview bot incorrectly removes NewApiVersionRequired label

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4353]
In [PR 20745](https://github.com/Azure/azure-rest-api-specs/pull/20745), the openapi-pipeline-bot correctly added the "NewApiVersionRequired" label

<img width="566" alt="image" src="https://user-images.githubusercontent.com/85643503/194945429-c29718c9-83f2-42d0-b497-469c8b927723.png">

But then 12 days later the AzureRestAPISpecReview bot removed it:

<img width="579" alt="image" src="https://user-images.githubusercontent.com/85643503/194945600-5826240d-dfb8-4dd0-a97c-311e3f82c301.png">

**Comment by raych1** [comment]
This issue was fixed as the label was added again for the latest pipeline run.
