### ISSUE TITLE
Support for use case involving products that do not map to a service 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4354]
### Use case 2:  
A new product in scope for APEX does is not mapped to a service in service tree.  The engineering lead access the Azure SDK Release planner for the first time to complete the SDK onboarding Questionnaire. 

### Issue with current design:  
Azure SDK Release Planner request a user to enter the service that the product is mapped to at login.  The context for the Azure SDK Release Planner app is set to the service context.  Products that are not mapped to a service will not be able to access the Azure SDK Release Planner to complete the onboarding questionnaire.  

### Proposed UI and Requirements to address this design gap 

<img width="627" alt="image" src="https://user-images.githubusercontent.com/67656762/194938690-f6ef0fa2-4e1b-4ff3-8489-943369729437.png">

![image](https://user-images.githubusercontent.com/67656762/194927035-3f2dab5b-54cc-4513-9ee9-0a041d2aec41.png)

![image](https://user-images.githubusercontent.com/67656762/194927982-c4534ca6-5be2-4cd2-b93a-cc2566f33a2f.png)

#### UI & Data Requirements  (still working on formatting table) 
Revisions to the [Azure SDK Release Planner Beta V1 document }(https://microsoft.sharepoint.com/:w:/t/AzureDeveloperExperience/EacBCeA8OeRFgCnzSFYhl-YBhOYwhxqfwiGjpX2BRUC6zw?e=1HYdkx)

| Requirement Section + req letter | UI Element | Action  | Trigger | Frequency |
|:-------------------------------------:|:------------:|:--------:|:--------:|:----------:|
|   5.1.3 a   |SelectService text label|  Provide help text seen on panel. |  Always show  |  Always  |
|   5.1.3 b  | SelectServicerdopdown1 | Display all services as retrieved today 1. Display all services or service groups that have accessed Azure SDK release planner context.  |  Always show | Always  |
|   5.1.3 c  | ServiceNotFoundcheckbox and ServiceNotFoundtextlabel| Show the text label. If this box is checked, show Organization dropdown | Always show| Always show|
|  5.1.3 d  | Division dropdown | Show all divisions listed in Service Tree, user selects the division | Only show if 5.1.3 c is checked. ServiceNotFoundcheckbox=TRUE | when triggered|
|  5.1.3 e  | Organization dropdown | Show all organizations mapped to selected Division listed in Service Tree, user selects organization | Shown if division dropdown is triggered.  | when triggered |
|  5.1.3 f  | Service group dropdown| Show all service groups mapped to selected organization listed in Service Tree, user selects service group | Shown if division dropdown is triggered |  when triggered |
|  5.1.3 g   | SelectServicedropdown2| Show all services mapped to the selected service group, user selects service. If user selects a service, then set the Azure SDK Planner context for the product to the service selected.  |   Shown if division dropdown is triggered | when triggered |
|  5.1.3 h  | NoSpecificServiceCheckbox and text label | If user selects box, then set the Azure SDK Release Planner context for the product to the service group. |Shown if division dropdown is triggered | when triggered |
|  5.1.3 g   |SelectServiceContinuebutton| If ServiceNotFoundcheckbox=TRUE, the SelectServiceContinuebutton  will display the Contextpopup|always show SelectServiceContinuebutton. |If ServiceNotFoundcheckbox=FALSE, continue to the Azure SDK Onboarding Questionnaire Blade|
|  5.1.3 h   |Contextpopup|Display the service or service group context set in SelectService blade. | If ServiceNotFoundcheckbox=TRUE, when Continue button show Contextpopup. |when triggered|
|  5.1.3    |Contextpopupbutton |Display the service or service group context| When user chooses continue button display the Azure SDK Onboarding Questionnaire Blade |when triggered |

### Use case 2:  
A user accesses the Azure SDK Release planner, and the onboarding survey has been completed.  The use case for the product during initial access to complete the onboarding survey was use case 1.  

### Proposed UI and Requirements

![Image](https://user-images.githubusercontent.com/67656762/194963646-0834e859-075d-41aa-8126-21270c63e57b.png)

#### UI & Data Requirements 
Revisions to the [Azure SDK Release Planner Beta V1 document }(https://microsoft.sharepoint.com/:w:/t/AzureDeveloperExperience/EacBCeA8OeRFgCnzSFYhl-YBhOYwhxqfwiGjpX2BRUC6zw?e=1HYdkx)

 | Requirement Section + req letter | UI Element | Action                                                                      | Trigger | Frequency |                                      
|:-------------------------------------:|:------------:|:-------------------------------------------------------:|:------:|:----------:|
|   5.1.3 a   |SelectService text label|  Provide help text seen on panel 1.  | Always show |  Always  |
|   5.1.3 b  | SelectServicerdopdown1 | Display all services, including services found in user case #1. During initial access to the Power App, the user went through the alternative flow so if a service was identified, then it should show up in the dropdown box.  This service should have been added to our data and should be mapped to the product.  So it should show up in the dropdown box. |  Always show | Always  |
|   5.1.3 c  | ServiceNotFoundcheckbox and ServiceNotFoundtextlabel| Show the text label. If this box is checked, show the Service Group dropdown box.  |Always show| Always show|
|  5.1.3 f  | Service group dropdown| Show all service groups that we have Azure SDK Release planner context set to for a product that completed use case #1 | Shown if ServiceNotFoundcheckboTRUE| when triggered |
|  5.1.3 g   |SelectServiceContinuebutton| Display the main blade for the Azure SDK release planner app |always show|always|

**Comment by live1206** [comment]
@ladonnaq  As we offline discussed, most of the products have a mapping service. The only exception we encountered now is `Azure Playfab`. We could talk to the Product team to figure out why they are not mapping to any service.
We do not need to implement a way for this case for now.

cc @maririos
