### ISSUE TITLE
[stress testing] Stress watcher deletes test resource groups on container restart

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#4356]
Some events in the cluster, such as a node reboot, will cause the pod to reach a terminating state, and a new pod to be re-scheduled on a new node. The first pod event triggers the watcher to delete the underlying resources, despite the test still running on a new node. We need to figure out a way to skip completion hooks in the watcher when they are actually pods getting re-scheduled.

CC @ckairen @LibbaLawrence @richardpark-msft

**Comment by benbp** [comment]
Perhaps we can change the watch to job events, or at least check the job status on a pod event to exclude `Running`.

**Comment by richardpark-msft** [comment]
@l0lawrence, this is probably what happened to your test.

**Comment by benbp** [comment]
For posterity, some investigative tools for rooting out node reboots:

You can see these changes with these two queries against [stress-pg - Microsoft Azure](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/faa080af-c1d8-40ad-9cce-e1a450ca5b57/resourceGroups/rg-stress-cluster-pg/providers/Microsoft.ContainerService/managedClusters/stress-pg/logs)

```
KubePodInventory
| where Namespace == "llawrence"
| where TimeGenerated between (datetime(10/8/2022, 6:10:00 AM)..datetime(10/8/2022, 6:45:00 AM))
| where ControllerName startswith "sendconsumesync-pyamqp-feature-branch-warning"
| where ContainerName endswith "python-eh-stress"
| sort by TimeGenerated asc
```

This shows you your test containers/pods and what their state was. At the beginning of those results there are TWO pods for the same test, with different ID suffixes, one in state terminating and the other in state running. The one in terminating state is on node aks-default-37641077-vmss000001 and the running one on node aks-default-37641077-vmss000002. Then:

```
KubeNodeInventory
| where TimeGenerated between (datetime(10/8/2022, 6:10:00 AM)..datetime(10/8/2022, 6:45:00 AM))
| where Computer in ('aks-default-37641077-vmss000001', 'aks-default-37641077-vmss000002')
| sort by TimeGenerated asc
```

This shows the node states for the same time period. node *001 has a Status of "RebootScheduled,Ready" and then "RebootScheduled" which was the node the original pod was on
