### ISSUE TITLE
Validation should not err on missing `type: object` in model

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#4357]
Since OpenAPI models are considered `type: object` by default (rather, per JSON schema), why do we need the `MissingTypeObject` error validation? It's not hard to add it, but just seems like unnecessary friction since it's the default anyway.

**Comment by raych1** [comment]
Here's the abstract of the rule definition, with type: object or without it have different types in generated SDK. For details, please see [rule#4037](https://github.com/Azure/azure-rest-api-specs/blob/master/documentation/openapi-authoring-automated-guidelines.md#r4037-missingtypeobject)

```
Why this rule is important: The semantics of with and without "type:object" are different. With “type:object” means “it has to be an object”. Without “type: object” means “it could be any type”. Azure SDK Track 2 generator will honor the difference, and generate different SDK codes. A free-form object would like:
```

**Comment by heaths** [comment]
@lmazuel can you follow up on this? I seriously doubt any track 2 code generators make this distinction. .NET is the only runtime (/C# language) that even has a distinction between structures vs. classes and we certainly don't use the presence of `type: object` to make that distinction. In fact, the only time we generate structs currently is for extensible enums (`modelAsString: true`).

I would argue this rule is outdated and unnecessary.

**Comment by lmazuel** [comment]
Per Swagger spec, it's not the same semantic with and without `type: object` as without it means "it _may_ be an object, and if it does those are the properties that it must have", with it means "it _has to_ be an object, and if it does those are the properties that it must have".

**Comment by heaths** [comment]
I get the swagger spec may say that, but do any of our generators even make that distinction? If not, this validator is just unnecessary friction. Now we're in a case where it's treated like an object already across our language SDKs, but we get validation errors because we didn't unnecessarily define it, and when we do define it we get breaking change validation errors. At the end of the day, there will be no difference to generated code - just lots of hassle to get past validation.

**Comment by lmazuel** [comment]
M4 does the difference and will return AnyObject or Any type to codegen depending on what was found, I believe some codegen are generating sligtly different things.

It was supposed to be the way to define SDK like Data Factory and their "string or Expression" (cc @JoshLove-msft ) but I don't think it was ever implemented all the way to be honest.

@timotheeguerin did a PR at some point to batch update all Swagger spec to add them, but the amount of work to verify them didn't see worth it.

I do get your pragmatic point @heaths , ideally everybody should write it: no warning, better spec, no debate, everybody is happy :)

**Comment by heaths** [comment]
Thank you for the explanation. Seems if teams have to add it, they will need a break-change exception. Any generators that do care will require language devs to account for the change then.
