### ISSUE TITLE
TopLevelResourcesListBySubscription should not fire for extension resources

### ISSUE THREAD

**Issue by raosuhas** [Azure/azure-sdk-tools#4362]
Example failed run : https://github.com/Azure/azure-rest-api-specs-pr/pull/9070/checks?check_run_id=8809421296

The   path "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.OperationalInsights/workspaces/{workspaceName}/providers/Microsoft.SecurityInsights/multiXConfigurations": 

is an extension resource and does not need a top level resource list by subscription

**Comment by mikekistler** [comment]
I just discovered that this issue has already been reported, [#398](https://github.com/azure/azure-openapi-validator/issues/398), and the fix is already in PR,  [#399](https://github.com/azure/azure-openapi-validator/pull/399).

**Comment by raych1** [comment]
Feel free to re-open if necessary.
