### ISSUE TITLE
Consider using the absolute path to the assets.json as the local cache key instead of the relative path

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-tools#4365]
With the changes to [optimize the restore path to minimize disk reads/writes](https://github.com/Azure/azure-sdk-tools/pull/4105) a cache was added where we're using the AssetsJsonRelativeLocation as the key. I'm not 100% if the relative path is unique enough. As I found out while trying to write a [testcase](https://github.com/Azure/azure-sdk-tools/blob/main/tools/test-proxy/Azure.Sdk.Tools.TestProxy.Tests/IntegrationTests/GitStoreIntegrationPushTests.cs#L386) for a [scenario](https://github.com/Azure/azure-sdk-tools/pull/4339) I'd fixed. As it turns out, the relative path doesn't have to be unique in spite of the assets.json files living in completely different directories. This shouldn't be something that'll happen with the test-proxy running and the CLI commands won't persist the cache past a single command but it's still something we should consider as the absolute path will guarantee uniqueness.

**Comment by scbedd** [comment]
I don't think I'm going to take this one. Here's my thinking:

We find the assets store by the following algo.

- `PROXY_ASSETS_FOLDER` if set. 
- `<reporoot> + .assets` if override not set.

`<reporoot>` is calculated by ascending from the assets.json location to the first git root. My belief is that if we're aiming the test-proxy at an assets.json without explicitly overriding the assets store folder, they intended to re-use the same assets clone.

Now, given that, the test-proxy runs in both `local` as well as `docker` mode. When running in local mode, the absolute path to the assets json will be:

```
C:/repo/sdk-for-python/sdk/tables/assets.json
```

But when running in **docker** mode, the absolute path to that SAME ASSETS.JSON will be:

```
/srv/test-proxy/sdk/tables/assets.json
```

This has the effects of using a different assets repo clone depending on whether you're running tests through docker or the local tool. This goes against my expectations of the tool.
