### ISSUE TITLE
How should we save and surface the ADO workitem that was created from the Release Planner App into the Scheduler app?

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4371]

**Comment by maririos** [comment]
@live1206 you were talking about keeping a relationship between the Service Name + Product + ADO wokfitem id? 
If we do that, we could get that information and surface it in the scheduler when the user is requesting a meeting

**Comment by maririos** [comment]
We need to have the product information in order to have the ADO linked to the meeting

**Comment by maririos** [comment]
Let's start by adding the link into the email templates.
Confirm with @ladonnaq if we need this in the app too

**Comment by JonathanCrd** [comment]
ADO Item link added to the email!
I'm closing this issue now. If we need that link in the app too, we can reopen it.
