### ISSUE TITLE
[PowerApps] Decide what information would be displayed after the SDK is released

### ISSUE THREAD

**Issue by lirenhe** [Azure/azure-sdk-tools#4381]
This is to follow up with the discussion the EngSys sync up meeting.

There are a couple of thinkings.
1.  Release pipeline would provide the link of the released SDK but for some language, it takes time to get the link of the released SDK.
2. Use a template to combine the information for the link of the released SDK.
3. Shall we provide other information like installation guide, etc

No conclusion yet, need PM's input about the scenarios.

**Comment by josefree** [comment]
let's work on this after collecting feedback from service parnter.

**Comment by maririos** [comment]
We have removed this view from the current SDK release apps so issue is no longer needed
