### ISSUE TITLE
[Python APIView] hide generated overloads from API view

### ISSUE THREAD

**Issue by rakshith91** [Azure/azure-sdk-tools#4387]
https://apiview.dev/Assemblies/Review/5fbe8b98bd4a4c62be152df0f4abc3d1

I have a couple of auto generated overloads showing on the API view which I don't need. 
Is there a workarounf to remove them?

**Comment by tjprescott** [comment]
When you say "I have a couple of auto generated overloads showing on the API view which I don't need." what do you mean? If you don't need the overloads at all, that sounds like Autorest (or DPG). If you mean you don't need them to show up on APIView... that's.. trickier.

**Comment by kristapratico** [comment]
I think this would ideally be solved in the generator. Even if we hide the generated overloads in APIview somehow, the overridden overloads will still not play nice with type checkers

**Comment by tjprescott** [comment]
Since the solution is to not generate these in the first place, I will close this issue for now.
