### ISSUE TITLE
CDAL+DPG: Package quickstart document based on docker container

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-tools#4395]

**Comment by dw511214992** [comment]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/800/CADL-DPG-Local-Use-Docker-Image-to-Generate-Codes-and-Grow-Up-in-Local
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/797/CADL-DPG-PowerApps-Use-Docker-Image-to-Do-Grow-Up-Development

**Comment by maririos** [comment]
Just curious, where is this documentation used? in the SDK Release App?
