### ISSUE TITLE
Validation does not support different host templates across separate specs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#4419]
If separate swaggers are together in a data plane RP and use different host templates like `{Endpoint}/language` and `{Endpoint}/language/authoring` to simplify authoring, validations tools are erring that,
```
"location":"specification/cognitiveservices/data-plane/Language/readme.md",
"tag":"[release_2022_10_01_preview](https://github.com/Azure/azure-rest-api-specs/blob/9b5852c414e04fe51c97c3a40820df937d1d937e/specification/cognitiveservices/data-plane/Language/readme.md#tag-release_2022_10_01_preview)",
"details":"Error: '$["x-ms-parameterized-host"].hostTemplate' has incompatible values (---'Endpoint/language',
---'Endpoint/language/authoring')."
```
See https://github.com/Azure/azure-rest-api-specs/pull/21068#issuecomment-1278304921 for more information.

This may also be a problem related to #3309. @tjprescott this should also be solved for Cadl, right? That each client within an SDK (1 or more) should have a separate directory for Cadl?

**Comment by raych1** [comment]
@jianyexi , can you have a look at the lint tool error?

**Comment by jianyexi** [comment]
it should be fixed when the 'staging lintDiff' comes stable
