### ISSUE TITLE
Current meeting Date and Time overlaps with other UI elements when editting a meeting

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#4424]
When editting any meeting, the green label overlaps other UI elements.

![Image](https://user-images.githubusercontent.com/17486462/195949158-777a7b41-5f16-4bf7-a7b8-53319134291d.png)

**Comment by maririos** [comment]
`Show time` is removed from UI so won't overlap. There are other UI elements that still need work

**Comment by JonathanCrd** [comment]
Apps in which we need to update this:

- [ ] Informational
- [ ] API Review
- [ ] SDK Review

**Comment by JonathanCrd** [comment]
Since I'm doing UI changes for this issue, I'm also modifying the "Back" button in the screens, currently, it seems that this button is disabled, but it is not.

I'm changing its colors to make clear that this is a secondary button and avoid confusions.

Old style:


![Image](https://user-images.githubusercontent.com/17486462/198155948-d750cbba-0ced-49b7-b0eb-e0a99b78a7a1.png)


New style:




![Image](https://user-images.githubusercontent.com/17486462/198156052-a4c364d0-a471-4382-a337-1762038a521c.png)

**Comment by maririos** [comment]
Interesting. talking about UI. According to the app, the buttons are in different places and this drives me crazy sometimes lol.
It is not urgent, but if you could make sure they are all in the same place, that will be great. 
For example:

![image](https://user-images.githubusercontent.com/9868623/198159164-24b18280-f8c8-42c7-bd73-2d47fc281a8c.png)

**Comment by JonathanCrd** [comment]
Changing that as well, primary button _(Create)_ will be on the right, and secondary button _(Back)_ on the left.

**Comment by JonathanCrd** [comment]
This has been fixed in all three apps
