### ISSUE TITLE
[Release Planner Requirement] Support Linter Error Suppression Recording and Review

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#4437]
Currently Swagger Linter Error suppression follows the [Swagger Suppression Process] (https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process). The suppression settings distribute in the readme.md configuration file of each resource provider.  It is expected
-  To set up a centralized suppression for new resource provider.  
-  Entry of the suppression request should be placed in the Release Planner. 
-  There should be a review before the suppression is applied

=================================================

From: Wes Haggard 

Jianye Xi we should look to try to include these power automate flow into the new PowerApp solutions we are currently working on so things can be consistent and contained together. 

We should definitely work on some method of getting the list of people from some data store (like github) and not have them be hardcoded in the tool. That simply will not work out longer term. At a minimum we should define a SG or DL that we can use to manage the list of folks but ideally we would have this list in a similar place like we have in the specs github repo today for assignments and reviewers. Can you please file some tracking items for this so we don’t lose track? 

Thanks,
Wes

**Comment by josefree** [comment]
bring this to triage

**Comment by josefree** [comment]
this is not specific for Release Planner. This is a requirement for Linter validation.

**Comment by maririos** [comment]
What we need to track as part of the Engagement Experience is that SG or DL that will contain the approvers. We want to have a centralized place with that information and be able to re-use it in different places

**Comment by konrad-jamrozik** [comment]
The new guidance for suppressions is given here:

https://aka.ms/pr-suppressions

It is unclear to me to which tool exactly this issue refers to, but I suspect `Swagger LintDiff`, as the description appears to match the suppression model. LintDiff suppressions work by adding relevant section to README, which is interpreted by AutoRest. LintDiff is an extension of AutoRest.

I do have a work item to add such suppression mechanism to breaking change check:

- https://github.com/Azure/azure-sdk-tools/issues/7259

I am not sure if this work item should also apply to breaking change suppressions (and all other checks), or only LintDiff.

@mikekistler filed another issue about restricting who can suppress:

- https://github.com/Azure/azure-sdk-tools/issues/6035

> I think the PR check must only be squashed (neutralized) if the label was added by a member of the breaking change review board or otherwise trained and responsible user

Plus there are few more items related to suppressions:

- https://github.com/Azure/azure-sdk-tools/issues/6509
- https://github.com/Azure/azure-sdk-tools/issues/6622
- Ray's proposal here for SDK suppressions: https://github.com/Azure/azure-sdk-tools/issues/7259#issuecomment-1819875813

Overall, I think we need to discuss one unified vision for suppressions including permissions and audit, as mentioned in this issue.

**Comment by konrad-jamrozik** [comment]
@maririos per my chat with @weshaggard, given everything that has transpired since this was filed, we are going to close this work item. The idea is to make the suppression approval process way more light-weight and based on GitOps: PRs and `git blame` over added suppressions files (see [proposal here](https://github.com/Azure/azure-sdk-tools/issues/7259#issuecomment-1874681669)) for auditing and review. No need to have all of this in release planner. If release planner needs this information it could derive it from the Git repo history of the suppressions files.
