### ISSUE TITLE
APIView - SDK review gen from swagger PR fails with auth error

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4440]
APIView fails SDK review request if Azure Org membership is private for PR author, and this has been done to run review gen steps for authorized users only. We are seeing a too many failures due to this reason and causing swagger to SDK automation not getting much benefit unless users change their membership type. Alternate option is to verify Azure org membership using Microsoft opensource URL to avoid these 401 errors.

**Comment by benbp** [comment]
just meddling

**Comment by praveenkuttappan** [comment]
We will change authentication to use MSFT opensource API to check if PR author is internal employee or not.
