### ISSUE TITLE
APIView - Auto generate swagger API review from Spec PR

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4441]
We have added manual swagger API review gen support in APIView. This issue is to track the feature to support autogenerating API review from Swagger spec PR.

**Comment by ruowan** [comment]
Hi, @praveenkuttappan .  Our swagger pipeline need to download the swagger-api-parser tool. Could you share how to access the private nuget register?

**Comment by ruowan** [comment]
We already deploy it to prod. We could close it.

**Comment by maririos** [comment]
Thanks for the heads up!!
Question, I see these 2 comments in the PR you have linked. Waht is the behavior?

<img width="705" alt="image" src="https://user-images.githubusercontent.com/9868623/201215269-0588592a-2f6e-4af2-a417-23b88b9febd8.png">

Couple comments lower:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/9868623/201215312-133ae64c-d5a3-4ce9-97da-b371bedb055c.png">

**Comment by maririos** [comment]
Also, should we see it in every PR? i.e.  https://github.com/Azure/azure-rest-api-specs/pull/21510

**Comment by ruowan** [comment]
For PR target branch is main, RPSaaSMaster, release-* . The apiView should be generated. I saw there are still some PR which generation succeed but apiView service return 401. @praveenkuttappan have a issue to fix them.
