### ISSUE TITLE
APIView - Enable CD of APIView when changes are merged to main

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4443]
Auto deploy changes to staging instance from main branch to support CI - CD. Staging instance should not be used for any manual deployment from PR.

@maririos just fyi..

**Comment by praveenkuttappan** [comment]
correct. continuous deployment

**Comment by chidozieononiwu** [comment]
I setup continuous deployment of latest changes from main to staging.
Changing the term staging to redeployment will require recreating the resources in the resource group.
