### ISSUE TITLE
Create Release pipelines from Dev to PPE and PPE to PROD

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4445]

**Comment by maririos** [comment]
Depends on https://github.com/Azure/azure-sdk-tools/issues/4742

**Comment by JonathanCrd** [comment]
The existing release pipelines for PPE and PROD worked as expected in the previous release.

Could you clarify what this issue is abou? Is it about creating new ones or a copy of those?

**Comment by maririos** [comment]
@JonathanCrd the pipelines were not working before so we were looking into it.
Now that Admin app is clean and Wei has been cleaning the pipelines it seems to be working.
We can close the issue
