### ISSUE TITLE
Communication with Stakeholder

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4446]

**Comment by maririos** [comment]
We decided:
- To add a new Field to our project to be able to indentify who requested the issue/change. Options are `User, Admin`.
- We will meet with our admins once every month, days before our Scheduler Planning meeting on Mondays with Eng team.
- Agenda will be share previous to the meeting so admin users can take a look. Agenda will be based on our Project

**Comment by maririos** [comment]
- Field added
- All issues in our project (open and closed) have been updated to include this value
- A new view called `Requested by` has been added to the project
- A new chart was added to have a view of `Requested by and Release` relationship

**Comment by maririos** [comment]
Meeting scheduled and agenda will be managed by @ladonnaq

**Comment by ladonnaq** [comment]
![Image](https://user-images.githubusercontent.com/67656762/202581242-0501c386-6201-4510-a21c-e73f83eb8014.png)

**Comment by ladonnaq** [comment]
We should change our requested by to match what I put in the engagement experience project.  I think it make sense to list the main stakeholders by area they represent.  



![Image](https://user-images.githubusercontent.com/67656762/202581374-9698b7d6-1f53-40a4-89cd-734883568795.png)

**Comment by maririos** [comment]
> We should change our requested by to match what I put in the engagement experience project. I think it make sense to list the main stakeholders by area they represent.

I like this for the Engagement experience project because of how many different areas it involves. But for the Scheduler meeting, our stakeholders are the admins of the meetings. The nature of the issue tells us what type of meeting or meetings the issue is for (note that one issue could apply to all meetings).

How will this information be used?

**Comment by maririos** [comment]
Field updated:


![Image](https://user-images.githubusercontent.com/9868623/203449664-11bac66c-8022-44a4-bc6b-488281955769.png)

Also views and graphs like:
https://github.com/orgs/Azure/projects/231/insights/9
