### ISSUE TITLE
APIView - Requested review page is not listing reviews

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4448]
Existing reviews doesn't have new column which was causing issue when processing reviews to find required reviews to be listed in pending reviews page. This was also fetching all reviews from cosmos DB and filtering on APP side to find required pending reviews.

We should change this to fetch only required reviews from Cosmos DB.

**Comment by JonathanGiles** [comment]
I think this can be marked as closed / resolved?
