### ISSUE TITLE
Support test-resources.json at library level

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#4450]
Currently, test-resources.json (and the bicep equivalent) is expected to live in service directory. For services where we have split live test pipelines by library, we may want to have separate files per library directory. It should be as simple as updating New-TestResources.ps1 to accept an optional library directory parameter.

**Comment by benbp** [comment]
Related work from #2609, moving to this issue:

Add/extend parameters to support:

Custom test-resources.json and/or test-resources.bicep paths
Absolute paths for -ServiceDirectory to enable running the script outside of a repo (for example, when testing changes in the tools directory, or running the script for deployments in the stress infrastructure).
