### ISSUE TITLE
Onboarding documentation should be out of private Github repos

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4451]
We use this repository for some of the Onboarding pre-requisites documentation: https://github.com/Azure/azure-sdk-pr/blob/main/onboarding 

The problems are:
- It is in a private repo
- It is on Gihtub while the user is already in DevOps
- Some users don't have a Github account, so trying to access this file gives them `404`

We should make sure all documentation is available for etiher public consumption or internal consumption

**Comment by josefree** [comment]
and also consider to be out of Azure SDK internal wiki

**Comment by josefree** [comment]
for example, Cadl central document site is http://aka.ms/Cadl/azuredoc

**Comment by maririos** [comment]
This has been accomplished with the new documentation site: https://eng.ms/docs/products/azure-developer-experience
