### ISSUE TITLE
Daylight savings end date is different per country

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4457]
This is creating start time mislaps if the person that created/updated the meeting is in a country which end date for daylight savings is different than the one for the USA.

**Comment by JonathanCrd** [comment]
### Workaround to fix meetings affected by this problem:
We can use the existing CalendarEvent - Update flow to fix those events manually.

**If the error was caused when updating a meeting:**

1. Locate the previous run in the Update parent flow
2. Expand the first step and look at the Output Properties
3. Open a new tab to do a new run of the Update flow
4. Copy the Weblink as it is and paste it in the run window
5. Copy and paste the Calendar Name
6. Copy the meeting details, then change the `start` and `end` properties to the correct datetime, and finally paste it.
7. Copy the email parameters and change the `Review Date` to the correct one (remember that this is in shown in PT)
8. Copy and paste the Email Template Name
9. Copy and paste the GitHub Comment Template Name
10. Hit Run Flow at the bottom of the screen

**If the error was caused when creating a meeting:**

1. Open the CalendarEvent - Create flow and the GitHub - Create flow too.
2. Locate the previous runs on both flows for the meeting you want to change.
3. Open in a new tab the CalendarEvent - Update flow, and click Run, it will ask you for some params.
4. On the CalendarEvent - Create , go to the Microsoft Teams step and copy the weblink located in the Output properties, then paste it in the Update flow.
5. Calendar Name is always "Calendar" (without ").
6. On the CalendarEvent - Create flow, copy the Meeting Payload property of the flow (on the initial step).
   a. On UpdatedBy, add "System Admin".
   b. Delete the contents of the Subject property.
   c. Modify the End and Start properties to the correct times.
   d. Paste the modified Payload into Meeting Details on the Update Flow.
11. Go back to the Event Create flow and copy the Emails Parameters property value.
  a. Paste it in somewhere temporarily, we are going to need this later.
  b. Change the UpdatedBy property to "System Admin"
14. Then, go to the GitHub - Create and in the Body parameters locate the "Review Date' property.
  a. Copy that line and paste it into the Emails parameters from the other flow.
  b. Change the "ReviewDate" property to the correct time
17. Paste the Emai Parameters into the Update flow param with the same name
18. For the Email Template Name, and GitHub Comment Template Name, you will need to look at the SDK Email table and locate the proper one depending on the type of meeting you are fixing
19. Click Run Flow at the very bottom of the screen.

**Comment by maririos** [comment]
Dev (published):
- [x] Informational
- [ ] SDK
- [ ] API
