### ISSUE TITLE
[Swagger APIView] Fix missing first property for definition model 

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-sdk-tools#4461]
For contentModerator, the first property of model in definition are missing.

Feedback from @mikekistler 

Some of the schemas in "definitions" are missing properties. For example, "ErrorCode" only shows "code" but also contains "message" in the REST API definition. "TextDetectDiagnosis" is also missing the "start" property. Maybe it is always the first one that is missed?

**Comment by ruowan** [comment]
I checked the swagger-api-parser part. The swagger-api-parser part actually generate the property. @chidozieononiwu Could you check from UI side?

**Comment by mikekistler** [comment]
Is this done?
