### ISSUE TITLE
Consider the option to let user input the Service Tree ID when service doesn't show up

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4469]
There have been 2 scenarios where the Service Name is not showing up in our apps. We have received feedback that it will be good for the  user to be able to provide the Service Tree ID. Then we can fetch the service name and use that.

**Comment by josefree** [comment]
I realize this is specific to Scheduling App

**Comment by maririos** [comment]
This applies to both apps as we have the same data. We have decided on trying a different approach as stated on issue https://github.com/Azure/azure-sdk-tools/issues/4597.
We can close this and if we still need it re-open and revisit
