### ISSUE TITLE
Output Some Metadata in SDK Release Pipeline

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-tools#4483]
PowerApps needs to get the released packages from sdk release pipeline, such as the link to the release package. So it asks sdk release pipeline to store this kind of information to a metadata file in pipeline artifact.

cc: @josefree @lirenhe @zzvswxy @chunyu3

**Comment by weshaggard** [comment]
@josefree @dw511214992 what is the link information that we want here? Do we want to the link to the public package manager? Or the link to the package in the devops pipeline? Also I'm still interested in knowing what we plan to do with this link? What do we expect the user of the PowerApp to do with this link?

**Comment by weshaggard** [comment]
My suggestion for this first release is to provide a download link for the package from the DevOps artifacts. In a future release after we get some feedback about what is more interesting to the consumer of the app we can try to update that to be a download link from the public package manager or perhaps a set of instructions on how to consume that package for each language. It really depends on what the goal is for those using the app. 

If we do want the public package manager pipeline we will need to do unique work in each language release pipeline to upload those and as mentioned offline some of those links like to maven will not be live until the package manager finishes indexing the package.

**Comment by dw511214992** [comment]
I think we need the link to public package manager, because ther is a page in powerapps which tells customer where the released sdk is. You don't need to worry about the delayed access to maven, because we will check whether the link is valid before we show it to customer.

**Comment by josefree** [comment]
Not sure how long the "download link for the package from the DevOps artifacts" can be available. Before they are available, we can present message "generating...[details](lnk-to-ci-job)"

**Comment by weshaggard** [comment]
>"download link for the package from the DevOps artifacts" can be available. 

For our release builds we retain them for 2 yrs.

**Comment by weshaggard** [comment]
We are currently not providing links to the packages in the release planner. If and when we decide to do that, we can figure out how to expose the necessary metadata.
