### ISSUE TITLE
Automate checking for spell check upgrades

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#4493]
Changes to cspell can affect what is consider and not considered by cspell to be a word or a spelling error detection independent of our configuration of cspell and the state of our repos. That is, you could get new spelling error detections across repos when you upgrade cspell and its dictionaries.

The original reason for pinning the cspell version was to prevent unpredicted errors from coming into our builds as the result of changes to cspell occurring independently of changes to our code. These changes would block PRs who are onboarded to spell checking according to this list: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/367/Capabilities-and-State (all 4 of the cardinal languages are onboarded)

Known potential problems: 
* Changes to cspell business logic affects word boundaries which affects detected words which could result in new spelling error detections
* Changes to cspell dictionaries (add words, remove words, merge dictionaries, split dictionaries) could result in new spelling error detections

To test for these we need to run spell checks against spell checked repos to gain an understanding of what errors are detected that could block PRs. 

Against each onboarded repo run: 
1. Spell check the repo (cspell runs take a long time, use strategies to parallelize checks) 
2. If all passes, merge... If there are failures consider correcting the failures before merging.

Possible fixes or mitigations to failures: 
* Update acceptable terms in the `cspell.json` file 
* Ensure dictionaries used match expected dictionaries
* Change other configurations in `cspell.json` file according to new features in cspell

**Comment by kurtzeborn** [comment]
With the last update to cspell (last Friday, 10/21), let's see if there is any fallout from that update that an investment like this would've caught.  Good to track this in an issue so that we remember we might want/need this level of validation.

**Comment by danieljurek** [comment]
We've taken several updates to cspell and have not had any major problems. If there were problems this work would be of a higher priority. 

This PR refactored testing to use Pester and onboarded those tests to the tools pipeline: https://github.com/Azure/azure-sdk-tools/pull/9013. 

Closing.
