### ISSUE TITLE
Network error Azure SDK Release Planner App Beta 1 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4494]
Network error after selecting service.  The error was resolved but now seeing it again today (10/24/2022).  Accessed via this link - https://aka.ms/sdk-release-planner

![image](https://user-images.githubusercontent.com/67656762/197588783-ec18bc0e-e475-4fbc-bbac-27d7dcf5d870.png)

**Comment by live1206** [comment]
Should be fixed now.
