### ISSUE TITLE
Define what an API Spec "approved" means

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4498]
Currently, when a PR is reviewed by the ARM Review board, there are labels that are use to signal:
- When a review is needed
- When there are comments that the service team needs to addresss in order for the review to be approved
- When the changes are approved and, from and ARM API perspective, ready to merge

So when a reviewer approves an APIView file, what does that mean? how is that translated back into the PR? Can we remove/add labels to the PR accordingly?

**Comment by maririos** [comment]
This is applicable for any API Spec (Typespec, Swagger)

**Comment by maririos** [comment]
The current approach mentioned is working and no need to have the approval on APIView. Removing this form main epic and leaving it in the backlog

**Comment by ladonnaq** [comment]
Adding to my backlog to review and ensure no changes needed based on current API Spec review process for data plane and management plane.

**Comment by ladonnaq** [comment]
@maririos Do you think this is still relevant?

**Comment by maririos** [comment]
> @maririos Do you think this is still relevant?

Thanks for bringing to attention. Not really. This has all been covered in the REST repo thansk to the work @konrad-jamrozik  has done. 
I am going to close the issue

**Comment by ladonnaq** [comment]
> > @maririos Do you think this is still relevant?
> 
> Thanks for bringing to attention. Not really. This has all been covered in the REST repo thansk to the work @konrad-jamrozik has done. I am going to close the issue

No I don't think it is still relevant.
