### ISSUE TITLE
Breaking Change 'required' status changed message has old and new values reversed

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4500]
In [PR 21233](https://github.com/Azure/azure-rest-api-specs/pull/21233), the [Breaking Change PR check](https://github.com/Azure/azure-rest-api-specs/pull/21233/checks?check_run_id=9039474053) reports a "'required' status change" but the "old" and "new" values are reversed.

<img width="885" alt="image" src="https://user-images.githubusercontent.com/85643503/197650715-2683850f-fa62-4536-9b32-3c0c341fcc2a.png">

Old: [Microsoft.ApiManagement/stable/2021-08-01/definitions.json#L5073:7](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2021-08-01/definitions.json#L5073:7)

"document" is NOT required.

New: [Microsoft.ApiManagement/preview/2022-09-01-preview/definitions.json#L5738:7](https://github.com/Azure/azure-rest-api-specs/blob/d4a78de3c1658b76cebfb8c9f5e06e9d933a3d1a/specification/apimanagement/resource-manager/Microsoft.ApiManagement/preview/2022-09-01-preview/definitions.json#L5738:7)

"document" is required.

The message should also include the name of the property whose status changed.

**Comment by raych1** [comment]
@jianyexi , please have a look.
