### ISSUE TITLE
Avocado check fails for changes that don't update swagger files

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#4505]
In a case of a PR like https://github.com/Azure/azure-rest-api-specs/pull/20893 which only changes MD documentation Avocado fails the pipeline. 

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1942898&view=logs&j=22cb5f76-5058-5a9d-2377-d04e5451a5f2&t=75f8d99b-764d-5b43-90d5-e9f774389f08

```
./node_modules/.bin/avocado -f pipe.log --excludePaths "/common-types/" ".github" ".azure-pipelines" "documentation/" "arm-compute/" "profile/" "profiles/" "/scenarios/" "/package.json" "/package-lock.json" "/cadl/examples/"
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /mnt/vss/_work/_temp/98c4c88b-7035-4351-8300-34ddd9025622.sh
{"level":"Error","code":"MISSING_README","message":"Can not find readme.md in the folder. If no readme.md file, it will block SDK generation.","path":"/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/documentation","folderUrl":"/mnt/vss/_work/1/c93b354fd9c14905bb574a8834c4d69b/documentation"}
errors: 1
##[error]Bash exited with code '1'.
```

**Comment by weshaggard** [comment]
@tianxchen-ms @ruowan do you expect this is fixed by https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/431575

**Comment by raych1** [comment]
@weshaggard , this will be fixed in sprint of Nov.

**Comment by raych1** [comment]
> @tianxchen-ms @ruowan do you expect this is fixed by https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/431575

@weshaggard , this issue wasn't fixed in above PR and we will consider making the list of exclusion files as config in next change.
