### ISSUE TITLE
Error: Intake Questionnaire for App Compliance Automation Tool for Microsoft 365 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4506]
The engineering lead for App Compliance Automation Tool for Microsoft 365 tried to use the Azure SDK Release Planner app to complete the Intake Questionnaire.  She could not find the service; I found the service but got an error when trying to select a product from the drop-down menu.  

![image](https://user-images.githubusercontent.com/67656762/197819286-95e37929-6ecb-4c04-9a93-32621f987c20.png)

**Comment by ladonnaq** [comment]
> I was able to repro the error too. Looking to see what it could be.

Thanks @maririos!  Appreciate it!

**Comment by maririos** [comment]
I found the issue and fixed it in the Dev environment. The fix needs to be deployed to Production environment.

FYI @honghr

**Comment by honghr** [comment]
Thanks @maririos!

**Comment by live1206** [comment]
Fix deployed to Prod.

**Comment by ladonnaq** [comment]
@honghr @live1206 @maririos - Can we document process for closing issues that are reported in PROD by users?   This issue is not fixed.  Neither myself or the user have been able to successfully complete the onboarding questionnaire without errors.  We will quickly lose the trust of our users, if we don't validate and test that fixes are truly resolved.

**Comment by ladonnaq** [comment]
Here is the most recent error -  

![Image](https://user-images.githubusercontent.com/67656762/198138946-c374f4fa-d4df-465c-acc0-aad7a40138da.png)

**Comment by live1206** [comment]
The error was caused by the corresponding flow was turned off, got it turned on. 
And I manually created a work item successfully and closed it.

**Comment by ladonnaq** [comment]
I was able to successfully create the work item.  


![Image](https://user-images.githubusercontent.com/67656762/198366931-56760a81-931f-423c-9e9a-c4860bf75d0d.png)
