### ISSUE TITLE
Github secondary limit rate error

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4508]
We are seeing this in the scheduler app. We have checked our flows where we use the Azure SDK Bot and we don't have it on loops or situations where we do extra calls that are not needed.

Should we create a new Bot?

More information:
- Flow failing `Github - Create - Child` https://make.preview.powerapps.com/environments/ca95f761-477a-4e98-b34e-dfd5dd03a770/solutions/ebb9ee5e-104b-ed11-bba1-000d3a3419dc/objects/cloudflows/e44dbac6-3fe4-4c24-b57e-4f92abcab36e/view?utm_source=office&utm_medium=app_launcher&utm_campaign=office_referrals
-  https://docs.github.com/en/rest/overview/resources-in-the-rest-api#secondary-rate-limits

**Comment by JonathanCrd** [comment]
Created a post on the EngSys teams channel to get the conversation started

**Comment by praveenkuttappan** [comment]
We no longer see this issue. right? Can we close this and reopen if we see it again? @maririos
