### ISSUE TITLE
APEX PM team needs to be copied on all of the automated emails related to onboarding questionnaire 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4530]
Hello, I noticed that Siva and I are not copied on the emails that are sent to the user and APEX PM after the onboarding questionnaire is complete.  You can use the azuresdkapex@microsoft.com group email (which includes Justin, Siva, and I).

**Comment by honghr** [comment]
I have add azuresdkapex@microsoft.com to all email templates

**Comment by ladonnaq** [comment]
Thanks!  This can be closed when it is released in PROD.

**Comment by josefree** [comment]
please close the issue if it is deployed
