### ISSUE TITLE
[Stress Testing] Deployment of stress tests -- file sizes too large

### ISSUE THREAD

**Issue by l0lawrence** [Azure/azure-sdk-tools#4541]
`Error: create: failed to create: Secret "sh.helm.release.v1.stress-py-eh.v1" is invalid: data: Too long: must have at most 1048576 bytes`

Without a .helmignore file, deploying stress tests will drag in all files that are on the same level as chart.yaml (i.e log files etc.).

**Comment by benbp** [comment]
@LibbaLawrence Aside from following the layout recommendations (https://github.com/Azure/azure-sdk-tools/blob/main/tools/stress-cluster/chaos/README.md#layout) I'm not if there's a super great generic solution for this. Some options:

1. We could try to create some sort of reverse helm ignore allowlist
2. We could do some pre-calculation in the deploy stress script that looks if extra files are being included that shouldn't be and warns you or gives you a prompt option to add them to the .helmignore file.

I think I like option 2 the most. Thoughts @richardpark-msft @ckairen?
