### ISSUE TITLE
For API Reviews, Service Profile given from the Planner app is not showing on the scheduler app.

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#4546]
Reported by Haoran, when scheduling a new meeting from the Planner app, the given Service Profile on the database is not showing as the profile selected in the app.

You can take a look at the event record `5a6f0792-9355-ed11-bba2-002248041e0a` in the table to see the data that has been provided

**Comment by maririos** [comment]
Changes applied. It now looks like this:


![Image](https://user-images.githubusercontent.com/9868623/200068704-f00ae6d3-8dc5-4f95-ab81-17fcba452716.png)

@honghr could you give it a try and let me know if it works as expected?

**Comment by maririos** [comment]
Changed also addressed in Informational and SDK meeting types
