### ISSUE TITLE
Scheduler admin app shows incorrect meeting time

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4553]
Admin app shows 12:00 as meeting time for all meetings listed in upcoming meeting page. 

![image](https://user-images.githubusercontent.com/55455725/198713382-c5155424-8231-4cc6-8c6c-897ab5492d52.png)

**Comment by maririos** [comment]
Fixed and deployed to DEV.
See: 


![Image](https://user-images.githubusercontent.com/9868623/199356872-9b283510-f3e7-44f3-b405-3b0eb4ebafc0.png)
