### ISSUE TITLE
Scheduler admin app is showing schedule configuration incorrectly

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4554]
Admin app allows creating configuration at any hour: minute combination and this gets saved correctly in dataverse and used by schedule generator by all scheduler apps. But admin app shows schedule minute as `00` when editing an existing schedule even if meeting schedule has non-zero value for minute.

For e.g. 9:05 schedule config shows as 9:00 in edit screen

**Comment by maririos** [comment]
The time is not showing up either. For example, this meeting is at 11L00AM but see image:


![Image](https://user-images.githubusercontent.com/9868623/199357277-bb06a61f-28ba-406a-b2d4-8b301ce291f6.png)

**Comment by maririos** [comment]
Fixed: 


![Image](https://user-images.githubusercontent.com/9868623/203445604-d73e3d07-cdc3-43a7-bad4-500803c79611.png)
