### ISSUE TITLE
Survey/Experience after using the scheduler app

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4567]
@MrJustinB @maririos @ccbarragan Here is a [Draft of survey for the scheduling tool]( https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=v4j5cvGGr0GRqy180BHbR-SRHOv9H51LkqMFimFYWbJUMFdXRUQwUlU3MUpNWkswTkpEMVRBUkRUVi4u).  Please review and provide feedback. Mariana is planning to send next week to service partners who have used the tool to schedule meetings.

**Comment by maririos** [comment]
Open design questions:

- - When to send the survey?
  After the meeting happened we can do it
- How do we know a meeting happened?
  - Informational: The ADO item should be manually updated by the admin of the meeting.
  - API Review ?
  - SDK Review?
- We can have automation around the trigger so we send the survey.

- Should there be a survey per meeting?

**Comment by maririos** [comment]
Issue related for API Review: https://github.com/Azure/azure-sdk-tools/issues/3681

**Comment by JonathanCrd** [comment]
I created a new cloud flow, called: "Survey Test" inside the "Playgroung" solution.

That flow will send an email to all the people that scheduled at least one meeting in the last month from the moment that cloud flow gets triggered.

**Comment by maririos** [comment]
Phase 1 completed
