### ISSUE TITLE
Revisit logic for finding package name when not available in release tracker sheet

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4571]
Otherwise this happens:
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/9868623/199113650-d6dc74d8-fc6d-4ea9-b12c-6dd71596c9f9.png)

**Comment by praveenkuttappan** [comment]
This is no longer required. I have removed Service name with actual package name returned by parser as part of package name approval change.
