### ISSUE TITLE
The meeting scheduling tool should support rescheduling meetings to a custom timeslot

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4573]
Currently the meeting tool will allow rescheduling a meeting but only to one of the predefined timeslots.  We need a way to allow an admin to reschedule to a custom timeslot. This will allow the service team to create the meeting ... providing all the appropriate information ... and then the admin can modify only the date and time of the meeting.

Currently the admin must cancel the existing meeting and schedule a brand new meeting outside the tool, which opens up opportunities to miss or incorrectly transfer information from the original meeting to the new one.

**Comment by maririos** [comment]
This issue is potentially blocked by https://github.com/Azure/azure-sdk-tools/issues/5498

**Comment by maririos** [comment]
This was fixed. Documentation: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/728/Meeting-Scheduler-Apps?anchor=**how-to-add-a-new-random-meeting-slot**

**Comment by mikekistler** [comment]
[like]  Mike Kistler reacted to your message:
________________________________
