### ISSUE TITLE
Add Product ServiceTreeID  and Associated Service ServiceTreeID to management plane existing ADO work items 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4580]
The release planner will need to migrate existing ADO work items into dataverse so that the work items can be synched to update ADO fields based on current data in Cloud Lifecycle, S360, Service Tree Kusto's tables.

**Comment by live1206** [comment]
@ladonnaq Is this duplicated with https://github.com/Azure/azure-sdk-tools/issues/4600?

**Comment by ladonnaq** [comment]
Siva is working on making sure this information is complete for products we are tracking for APEX.  Here is a query - https://dev.azure.com/azure-sdk/Release/_queries?tempQueryId=09dfa364-f2a2-4b7a-a906-cf8f631f8ffa

**Comment by ladonnaq** [comment]
@maririos I do need all of the current ADO work items for management plane migrated to Release Planner dataverse so that I can begin onboarding teams who did not use the release planner to onboard.  Remember some teams onboarded for private preview before the release planner was available.  So we have existing work items with details/history that we don't want to have to try and manually synchronize.

**Comment by maririos** [comment]
@ladonnaq I pinged @live1206 offline to understand how to do this as this was not covered in the transition meeting

**Comment by maririos** [comment]
Work is blocked by https://github.com/Azure/azure-sdk-tools/issues/5796
Everytime I make an update fields change in the ADO item.

I am going to update the logic in the Migrate flow so it stops updating the ADO items with the information Dataverse has

**Comment by maririos** [comment]
Work is blocked by https://github.com/Azure/azure-sdk-tools/issues/5796
Everytime I make an update fields change in the ADO item.

I am going to update the logic in the Migrate flow so it stops updating the ADO items with the information Dataverse has

**Comment by maririos** [comment]
> I am going to update the logic in the Migrate flow so it stops updating the ADO items with the information Dataverse has

Done.

I have updated run the flow and most of the information was updated.
In cases where this was not true, I have communicated over email with La Donna
