### ISSUE TITLE
Hovering over API view comment bubble should show the comment

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#4584]
Repro:
1. Add a comment to an API View
2. Select Options and hide comments.
3. Hover the mouse pointer over the comment "bubble"

Feature Request: it would be very nice if the text of the comment showed when hovering over a hidden comment bubble.

**Comment by chidozieononiwu** [comment]
We already have this functionality [on-click](https://github.com/Azure/azure-sdk-tools/blob/ffe81dfa74a95d5d5df3bf97217b154e15957047/src/dotnet/APIView/APIViewWeb/Client/src/shared/comments.ts#LL68C6-L68C6), will need to also enable it on hover.
