### ISSUE TITLE
Allow hiding [EditorBrowsable(EditorBrowsableState.Never)] APIs in .NET API View

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#4585]
Some .NET APIs are marked with [EditorBrowsable(EditorBrowsableState.Never)] attribute.
It would be great if API View for .NET hid these APIs by default and allowed an option to show them

**Comment by maririos** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-tools/issues/3900
