### ISSUE TITLE
Clarify quality criteria for Data Plane SDK Library release

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#4595]
For Data Plane SDK release, service partner is expected to provide test cases and samples of SDK library of each language.  However, the satisfaction criteria are not clear that 
- test cases: #>0 ? Covers operations in hero scenarios (where is the definition of hero scenario)? or 100% defined operation coverage
- samples: #>0? Covers operations in hero scenarios (where is the definition of hero scenario)? or 100% defined operation coverage
- SDK testing: running against submitted test cases? require all pass before SDK PR merge?
- etc.

**Comment by josefree** [comment]
per discussion with engineer, currently most services are targeting to public preview.  For public preview, the critiers are test case > 0, samples >0.

**Comment by josefree** [comment]
this could hand over to engineer team for implementation

**Comment by dw511214992** [comment]
We cannot get the sample information. @josefree Do you think it's required now?

**Comment by maririos** [comment]
> We cannot get the sample information. @josefree Do you think it's required now?

Curious on the reason. @dw511214992 could you expand on the why?

**Comment by dw511214992** [comment]
@josefree We had a discussion with @weshaggard and Wes thinks it's not required to check the samples, and it shouldn't be a blocker for samples.

**Comment by weshaggard** [comment]
Correct there isn't any standard way of providing samples in our repos today so we shouldn't require them. In the future if we have a documented guideline and standard for how to provide them we can revisit that requirement.

**Comment by dw511214992** [comment]
After discussing with @lirenhe , it's required to contain samples in DPG. We will add a check to only check whether there is  samples in the sdk package. thanks

**Comment by maririos** [comment]
> After discussing with @lirenhe , it's required to contain samples in DPG. We will add some logics to check whether there is samples in the sdk package. thanks

Could you add in this issue what the logic to determine that will be?

**Comment by weshaggard** [comment]
@lirenhe @dw511214992 can you give more details on this sample's requirement? Do we have a document anywhere that tells folks how to write these samples? I think that is a prerequisite before we can make it a requirement.

**Comment by lirenhe** [comment]
Please check https://aka.ms/azsdk/dpcodegen.   

ACTION: Implement tests, samples and Readme
Usability is a critical part of the success SDKs to customers. There are requirements on all SDKs released, depending of their final status:

Public preview: at least one test per language and one sample for the most common scenario of usage
GA: at one test per shipped method and 4 samples for the most common scenarios of usage

**Comment by weshaggard** [comment]
@lirenhe While in principle I agree with you, the thing that is missing however is a guide to write such samples and even more then that how we write them in each language such that someone could detect there are samples. @lmazuel I'm curious about your take on this requirement.

**Comment by lirenhe** [comment]
@weshaggard, we have the guides https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-samples.   There are also some existing samples that people could follow.    i will double check for all SDKs.
By checking with @dw511214992, we already had some solutions to detect samples so technically, we could do that.

**Comment by weshaggard** [comment]
@lirenhe that is more of a higher-level guideline but we still need a more detailed set of docs on how to do this in each language so that folks know how to create them. Then based on that we might be able to figure out a consistent way across languages to detect and enforce. Right now, I don't think this is our biggest issue and we should probably try to focus on the overall usability of the release planner to get service teams using it.

**Comment by dw511214992** [comment]
> > After discussing with @lirenhe , it's required to contain samples in DPG. We will add some logics to check whether there is samples in the sdk package. thanks
> 
> Could you add in this issue what the logic to determine that will be?

@maririos For now, the logic is very simple. We only check whether the package contains a `samples` folder.
cc: @weshaggard @lirenhe

**Comment by zzvswxy** [comment]
deployed to Prod

**Comment by weshaggard** [comment]
>For now, the logic is very simple. We only check whether the package contains a samples

Even if we think that check is easy if that check fails we need to have a pointer to clear documentation on how to add samples for the particular language. Do we have that? If we don't yet then I still don't think this check should be required. We need to enable folks to be able to work through this process on their own and if we put up blockers we need to ensure we have clear documentation on how to get past those blockers.
