### ISSUE TITLE
Migration of data plane ADO work items to dataverse 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4600]
Here is an ADO query for APEX products in scope for data plane - https://dev.azure.com/azure-sdk/Release/_queries?tempQueryId=ed574226-7220-4b66-8145-8a4b513dce0d. 

We can identify from this list, which products will be using Cadl + DPG, then we make sure to migrate those first.  Once migrated, we should have a power automate flow in place that schedule a synch to the ADO work items.  We can start by scheduling the synch to run weekly.  If we are finding inconsistencies, we can adjust the schedule of when the synch runs.

**Comment by live1206** [comment]
@ladonnaq Thanks, I have exported the data I need for migration from the query.
Regarding the data sync from Service Tree and CLC, it will be automatically triggered if anything updated in Service Tree or CLC.
Is that OK? What do you mean by inconsistencies, if data inconsistent between ADO work item and Service Tree & CLC, shall we just take it from Service Tree & CLC?

**Comment by live1206** [comment]
@ladonnaq 
There are a few ADO work items missing Product Service Tree Id or corresponding Service Id.
https://dev.azure.com/azure-sdk/Release/_workitems/edit/12320
https://dev.azure.com/azure-sdk/Release/_workitems/edit/12604
https://dev.azure.com/azure-sdk/Release/_workitems/edit/13206
https://dev.azure.com/azure-sdk/Release/_workitems/edit/13280
https://dev.azure.com/azure-sdk/Release/_workitems/edit/10744

**Comment by live1206** [comment]
Apart from the above 5, the rest have been migrated to Dataverse

**Comment by ladonnaq** [comment]
Thanks!  I will check on these 5 and also on management plane.  I think that Siva has management plane done as well. I would like to start synching the data so that I can work on the new APEX product dashboard (for us not the service partners, service partner dashboard is in release planner app).

**Comment by josefree** [comment]
reassign back to Ladonna for the rest five work items handling

**Comment by live1206** [comment]
@ladonnaq Any update on above ADO work items? And any plan with management plane related work items?

**Comment by ladonnaq** [comment]
There are a few ADO work items missing Product Service Tree Id or corresponding Service Id.
https://dev.azure.com/azure-sdk/Release/_workitems/edit/12320 - Closed, not in scope for APEX launch readiness anymore, not an Azure product. 
https://dev.azure.com/azure-sdk/Release/_workitems/edit/12604 - Updated with information.  In scope for data plane and management plane. 
https://dev.azure.com/azure-sdk/Release/_workitems/edit/13206 - Updated 
https://dev.azure.com/azure-sdk/Release/_workitems/edit/13280 -  Updated (the product has not been officially named)
https://dev.azure.com/azure-sdk/Release/_workitems/edit/10744 - This is Vision SDK (Carbon) service and there is no product. So this is atypical scenario (service only, no product).

**Comment by ladonnaq** [comment]
This query contains all active APEX onboard work items.  https://dev.azure.com/azure-sdk/Release/_queries?tempQueryId=dba6666a-c9fc-471d-9f43-b90e7a89c4c5

There are the work items that have missing data in service tree.  How should we handle these?  

- https://dev.azure.com/azure-sdk/Release/_queries/edit/10474/?triage=true  (no service mapping) 
- https://dev.azure.com/azure-sdk/Release/_queries/edit/10744/?triage=true (no product, only service) 
- https://dev.azure.com/azure-sdk/Release/_queries/edit/12389/?triage=true (sku not mapped to a service, offering mapped to multiple services) 
- https://dev.azure.com/azure-sdk/Release/_queries/edit/9348/?triage=true (sku not mapped to a service, offering mapped to multiple services)
- https://dev.azure.com/azure-sdk/Release/_queries/edit/9522/?triage=true (offering not mapped to a service)

**Comment by live1206** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/huwe/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/huwe/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">



Product ID | Service   ID | ID
-- | -- | --
6daef9b6-b3e3-4dab-8263-6153281ba96b | 39e42a5e-0ccf-492c-a470-4d3128212711 | 9298
8202aa38-b077-eb11-9889-501ac51f903e | b31f90f9-53d3-445e-8546-5654f84ce606 | 10538
dc5a46d4-f21f-4053-945a-f8abd21b2d2b | 44a2b1b8-0556-4403-8261-fe6a9172ea32 | 10743
e84759d5-5946-4252-911f-83ab338e4945 | 58aa8ff2-5d53-444a-8026-1610fb23c30f | 10973
2a4116b2-1930-4236-b303-6639c765bd03 | 773fcab3-54b3-47df-b0be-c08250826c37 | 11476
ee5716b5-e6fd-480a-9396-0343b023dfa5 | 33819a99-e22d-4f43-a861-3045b207011f | 12278
b1292068-f087-4b80-9025-62662e245028 | 403a1a7e-9f26-44b7-be51-4c15b0d02c21 | 12396
a3a1bc16-da28-465c-92cb-5771c8270a65 | f9caafe4-e867-44b2-bd68-69a8efe5df3f | 13167



</body>

</html>
For these ADO work items, the corresponding products do not contain action items in CLC, we do not sync them in Release Planners. So, they do not exist in the App.

**Comment by maririos** [comment]
@live1206 what is the work remaining in this issue?

**Comment by live1206** [comment]
I think we can close this and deal with https://github.com/Azure/azure-sdk-tools/issues/5200 instead.
