### ISSUE TITLE
[Scheduling Tool] Admin ability to block a day

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-tools#4605]
It would be extremely useful for the Arch Board Help Desk team to have the ability to block days on the schedule. This way when a team schedules a review session by submittting a GitHub Issue themselves, or by going through the Arch Board Help Desk, we can block that day so another team doesn't schedule a session with the Arch Board on the same day. 

Whether this is impleted through the Scheduling tool Admin site through an interface to choose a day and then block it. Or if there could be a way to add the scheduling tool's email account to the meeting we manually create and then the scheduling tool automatically blocks it off. 

@kyle-patterson @ladonnaq

**Comment by maririos** [comment]
I agree that we need a way to block days in case there are other activities, holidays, etc.

> This way when a team schedules a review session by submittting a GitHub Issue themselves, or by going through the Arch Board Help Desk, we can block that day so another team doesn't schedule a session with the Arch Board on the same day.

Wouldn't the documentation/process be updated so the only entry point for users to schedule a meeting is through the Scheduling Tool?

**Comment by kyle-patterson** [comment]
Teams needing nonstandard times will still need to book through the helpdesk until the scheduling tool supports non-PST meetings (a conflict arising from this scenario is what prompted this issue)

**Comment by maririos** [comment]
Thanks for the explanation @kyle-patterson 
What are the nonstandard times for meetings? Is it only when it is needed? or do architects are blocked specific times some days to work on those hours.

Also XOR, do you mean that there can only be one arch board per day?

**Comment by ronniegeraghty** [comment]
> Thanks for the explanation @kyle-patterson What are the nonstandard times for meetings? Is it only when it is needed? or do architects are blocked specific times some days to work on those hours.
> 
> Also XOR, do you mean that there can only be one arch board per day?

Yes. We only schedule one arch board meeting per day to not overload the architect's whole schedule.

**Comment by ronniegeraghty** [comment]
@maririos 
Standard Times: 2:05PM - 4PM PST or 4:05PM - 6PM PST (for Shanghai teams). 
Non-Standard Times: 10:05AM - 12PM PST and 9:05AM - 11AM PST (the 9-11 time is only used when absolutely necessary, usually for India located teams) 
Non-Standard Times are only used when needed and the Architects need to accept the non-standard time. Normally when a team is asking for a non-standard time Kyle and I will post in the Architects team chat asking if anyone has an issue with the non-standard time on the next open day. If no one has an issue the meeting is created, if someone does, we look to the next open day and ask the architects again.

**Comment by maririos** [comment]
This has been accomplished by issue https://github.com/Azure/azure-sdk-tools/issues/5015
