### ISSUE TITLE
Release Planner Contact Us page links don't work

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#4617]
If I select the Report a Bug, Contact Us, or Provide Feedback links, nothing happens.  if you select the "this link" link it does work, but the others do not.

https://apps.powerapps.com/play/e/ca95f761-477a-4e98-b34e-dfd5dd03a770/a/0d436325-4499-48b2-b03b-8156c75712d2?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&source=portal

![Image](https://user-images.githubusercontent.com/105250266/199861864-b28db092-60f2-4870-8614-1a4324c5174b.png)

**Comment by MrJustinB** [comment]
I have the same problem w/ the question mark icons



![Image](https://user-images.githubusercontent.com/105250266/199862288-0bab8175-bb8d-4c60-8a71-a054c2eba59e.png)

**Comment by maririos** [comment]
We had a conversation with Eng teams and we want feedback from @ccbarragan on what is the best way to present this information.
Justin is sharing the page in the Release Planner App. Here is what we have in the scheduler app:

![image](https://user-images.githubusercontent.com/9868623/200035482-642f6a8d-9142-413a-b8b2-44d8d102f226.png)


<img width="610" alt="image" src="https://user-images.githubusercontent.com/9868623/200035446-abec2f15-f893-4525-883b-9c5a81743f9e.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/9868623/200035554-706a3b96-f72c-44b5-9af9-fb1dfdce72f4.png">

@ccbarragan  what do you think?

**Comment by maririos** [comment]
As for links:
- Report a bug: tools repo
- Contacs us email: azsdkexp@microsoft.com
- Contact us Teams Channel: @ladonnaq do you think we can use the Onbaording channel? or should we create a new channel for engagement? I am wondering what is the best way for our users to find us

**Comment by maririos** [comment]
FYI @josefree

**Comment by ladonnaq** [comment]
@maririos We can use the onboarding team channel.

**Comment by josefree** [comment]
Thanks. bring this to engineering triage.

**Comment by josefree** [comment]
duplicate with this https://github.com/Azure/azure-sdk-tools/issues/4269
