### ISSUE TITLE
Service now found checkbox redirects to GitHub bugs repo 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4626]
There is a requirement that was missed in the revisions of the requirement docs.   

### Helptext 
Helptext: 
If you do not know what service that your product maps to, please use the new service tree to look up the product service mapping. [Service Tree | Home (microsoftservicetree.com)](https://microsoftservicetree.com/home).

### Added checkbox if service is not found 
The checkbox is under the drop down menu with text label.  Text should be "I cannot find the service associated with the product.".  When checked they should be directed to a bugs repo so they can open a GitHub issue.

**Comment by josefree** [comment]
bring to engineering triage

**Comment by josefree** [comment]
Helptext can be done.  But add a checkbox to allow manual input is not feasible, for manual input cannot trigger the linkage.

**Comment by live1206** [comment]
There should not be any missing service for the user anymore.

**Comment by honghr** [comment]
Added helptext in login popup and account settings page.
