### ISSUE TITLE
[Prioritized] Add CLI verb `config`

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#4652]
In short, we want an "official" way to interact with the assets.json only involving the test-proxy and now pshell to do things like create it.

- [ ] test-proxy config initialize (pending, I don't have a good way to discover `language` in an automated way
- [ ] test-proxy config show (shows details about config, relevant paths, etc)
- [ ] test-proxy config locate (shows location of assets repo for config file)
- [ ] test-proxy config diff (generates a git link that diffs current and previous tags)

**Comment by benbp** [comment]
@scbedd For example, does this mean that `test-proxy cd sdk/appconfiguration` would take the user to `<repo>/.assets/<path boilerplate>/appconfiguration`?

The `cd` action/verb feels a little odd to me, especially as a top level command amongst `start|push|etc.`. Perhaps having a verb class for `config` would give you some breathing room for additional actions?

```
test-proxy config path # infer from current directory
cd $(test-proxy config path)
test-proxy config path sdk/appconfiguration
test-proxy config path /home/ben/sdk/azure-sdk-for-python/sdk/appconfiguration
test-proxy config edit # open in code, vim, etc. feels very extra though
test-proxy config show
test-proxy config github # open/print github link to assets tag/files
```

**Comment by scbedd** [comment]
I like this a lot. A lot a lot. Going to take a pause on the current PR to change to something like this.

**Comment by benbp** [comment]
We should also add `test-proxy config initialize` as a command based on discussion.
