### ISSUE TITLE
Scheduling tool creates issue in wrong repo

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#4654]
It looks like when a meeting is created, and a PR is provided, the issue is opened in the wrong repo. By default, the issue and the PR should be in the same repository.

![azure-rest-api-specs 2022-11-08 14-55-56](https://user-images.githubusercontent.com/522116/200662598-9e1b8a40-c781-4bc6-98f3-d63ca704ce17.png)

**Comment by maririos** [comment]
Not sure I follow. Looking at the screenshot, the issue was created in the `Azure/azure-rest-api-specs` repo, same as the PR

Issue: https://github.com/Azure/azure-rest-api-specs/issues/21279
PR: https://github.com/Azure/azure-rest-api-specs/pull/9407

**Comment by markweitzel** [comment]
yeah. i think i grabbed the wrong screen shot

**Comment by weshaggard** [comment]
@maririos the problem appears to be that the github issue is in the public repo but the associated PR should have come from the private repo https://github.com/Azure/azure-rest-api-specs-pr/pull/9407

**Comment by maririos** [comment]
Opened issue https://github.com/Azure/azure-sdk-tools/issues/4656 to see how we could improve the UI design and avoid this problem in the future
