### ISSUE TITLE
Establish a strategy for the management of Codeowners and its usage

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4663]
- Codeowners information across repositories should be consistent
- Tooling dependent on this information should use one source of truth instead of hardcoded values. i.e. PowerApps, APIView, etc

**Comment by josefree** [comment]
agree. should be one of the steps when a brand-new service onboarding

**Comment by maririos** [comment]
This should be covered by https://github.com/Azure/azure-sdk-tools/issues/7366
