### ISSUE TITLE
Set up connection between tables while syncing data from CLC

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#4664]
Set up connection of 'Product Profile' in 'Service Product Mapping'

**Comment by live1206** [comment]
Added 2 additional columns: `Service Profile` (lookup of `Service Profile` table), `Product Profile` (lookup of `Product Profile` column)
![Image](https://user-images.githubusercontent.com/5196139/207260536-acc15f6a-3a88-4c23-9c51-e8223fbaf5ec.png)
cc @JonathanCrd

**Comment by JonathanCrd** [comment]
Thank you
