### ISSUE TITLE
Enable email sender service

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4670]
Instead of continuing the use of SendGrid, this [doc](https://dev.azure.com/devdiv/Engineering/_wiki/wikis/CNEKB/24555/How-to-send-email-from-Azure) about how to use MS service to send email.

**Comment by richardpark-msft** [comment]
Just FYI, I just realized I've been filtering all of these emails because it met two of my criteria - [EXTERNAL] and it has an unsubscribe link, which is typical for spam.
