### ISSUE TITLE
[PR Workflow] Swagger unified pipeline avoid adding ARM review label for those PR target branch to dev-*

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-sdk-tools#4675]
Feature request from Roopesh

> Can we have the bot remove the ARM review tags as well for PRs against dev branches?

**Comment by konrad-jamrozik** [comment]
@raych1 can you link me to the changes that have been made to move it into `Done` state?

**Comment by ruowan** [comment]
I cannot remember the exact work item. But the logic is handled in this [code](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps?path=/public/rest-api-specs-scripts/src/prSummary.ts&version=GBmain&line=725&lineEnd=726&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents)

**Comment by konrad-jamrozik** [comment]
@ruowan thank you! I understand it is not clear at this time if this work item was actually completed.

I am assigning myself: I need to evaluate if this work item was done or not and if not, work on it.

**Comment by konrad-jamrozik** [comment]
@rkmanda do you recall if this issue is still relevant? If so, maybe I could solve it by making adjustment to:
- https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/477900

**Comment by rkmanda** [comment]
We no longer see the review labels against dev branches. So looks like this is already addressed
