### ISSUE TITLE
Create a new view in APIView to show all API reviews from same PR in one page.

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4677]
We need to generate a new API review link that shows a dropdown with list of all API reviews created from a specific PR. This will help us correlate API reviews created from a swagger/CADL PR under a common link. All API reviews correlated by PR number will be listed under a dropdown to easily go to reviews created from a single PR.

@weshaggard I have filed this issue to track the change we discussed to make a correlated view in APIView based on PR number.

**Comment by mikekistler** [comment]
We need to clearly understand who is going to look at the language tabs and when they will look at it.

Are we asking language architects to look at BOTH this intermediate generated SDKs AND the PRs that are made to the actual client libary repos?
