### ISSUE TITLE
Make relevant information in SDK Reviews emails more visible

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#4680]
I got this feedback from one of the reviewers.

In the SDK Review confirmation email, the GitHub tracking issue link is not easy to find within all the text. A suggestion I got is to add the usefull links at the top of the email, or have a different email template for reviewers.

To be clear, the feedback I got was not against the content of the email, in fact, that person told me that the information in the email is great for the people who requested it.

**Comment by maririos** [comment]
It will be good to redesign the email template and put the most relevant information on top, similar to what we do with the other types of meetings.

**Comment by maririos** [comment]
Template has been updated and approved by PMs.
It is still missing the APIView links (which are present in the GH issue). I have created issue https://github.com/Azure/azure-sdk-tools/issues/5021 to follow up on that
