### ISSUE TITLE
Update ADO work item Info Meeting Field when Info Meeting is scheduled 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4681]
Update ADO work item Info Meeting Field when Info Meeting is scheduled. The field is Info Meeting State and the state should be "Scheduled".  I can create an ADO query for you that has the product servicetree ID, the service servicetree ID, and the Info Meeting State column. 
![image](https://user-images.githubusercontent.com/67656762/201227182-026abbd0-d22f-4460-ab58-fa370b3ee70a.png)

**Comment by maririos** [comment]
FYI @ladonnaq

**Comment by maririos** [comment]
@JonathanCrd you could start working on this to update the field when a meeting is created. When we have confirmation on the cancellation behavior, we will add that

**Comment by JonathanCrd** [comment]
@maririos do you know if the bot account has access to the org? If so, then I will need to create a connection first to AzDevOps using the bot account instead of mine.

**Comment by maririos** [comment]
Yes. the Release Planner App has access to it as they are using the bot to create the WorkItems

**Comment by JonathanCrd** [comment]
I have added this funct

> @JonathanCrd Jonathan Cardenas FTE you could start working on this to update the field when a meeting is created. When we have confirmation on the cancellation behavior, we will add that

I have finished adding this feature. Now, when an informal meeting with a product is created, it will update add "Scheduled" to the ADO Work Item.

However, if the meeting is re-scheduled or cancelled it won't update anything.

**Comment by JonathanCrd** [comment]
@maririos since the Product Name for informational meetings can be updated by the users at any time:

- What's the expected behaviour when a user deletes a product from the meeting?
- What should happens with the ADO work item if the user changes the product to another?

**Comment by ladonnaq** [comment]
I don't think that the user should be able to change the product name once the meeting is scheduled.  Especially in this scenario where the info meeting is triggered during using the release planner to onboard a new product in scope for APEX.

**Comment by maririos** [comment]
> I don't think that the user should be able to change the product name once the meeting is scheduled. Especially in this scenario where the info meeting is triggered during using the release planner to onboard a new product in scope for APEX.

@ladonnaq  Ohh interesting. We allowed a product to be changed because of the conversation on https://github.com/Azure/azure-sdk-tools/issues/4682
Do you want us to block that and not enable a product to be changed once a meeting is scheduled?

**Comment by maririos** [comment]
@JonathanCrd going back to 
>However, if the meeting is re-scheduled or cancelled it won't update anything.

- Re-scheduled: nothing should change, right? we are only saying the meeting is still happening and we are not saving the date
- Cancelled: could you expand on why we are not updating the field to `Cancelled` ?

**Comment by JonathanCrd** [comment]
@maririos 
> Re-scheduled: nothing should change, right? we are only saying the meeting is still happening and we are not saving the date

You are right, this should not do anything regarding the ADO work item. It's just the scenario for adding, removing or changing the product when updating/re-scheduling a meeting the one that is still ambiguous.


> Cancelled: could you expand on why we are not updating the field to Cancelled ?

There is not "Cancelled" option in the ADO field, so passing the keyword results in a fail request.

**Comment by ladonnaq** [comment]
I added it so it should show up in all existing onboard work items and any newly created.

**Comment by JonathanCrd** [comment]
@ladonnaq thank you. I added that feature into the app, now, when meetings gets cancelled, the associated ADO Work Item will show "Cancelled" under the `Info meeting state` field.

So far, the status of the features added into the app is:

- [X] Creating a meeting updates the ADO Work Item field to "Scheduled"
- [X] Cancelling a meeting updates the ADO Work Item field to "Cancelled"

The update scenarios are still ambiguous:
- [ ] Adding a Product when updating a meeting updates the ADO Work Item field to "Scheduled"?
- [ ] Changing a product to another when updating a meeting... ???
- [ ] Removing a product when updating a meeting... ???

Going back to:
> I don't think that the user should be able to change the product name once the meeting is scheduled. Especially in this scenario where the info meeting is triggered during using the release planner to onboard a new product in scope for APEX.

Then, should we not allow the users to update the product selection once they specified one? Or should we not allow them to edit the product at any time, even if they didn't specify one when creating the meeting?
