### ISSUE TITLE
Standardize PowerShell SemVer Parsing Logic

### ISSUE THREAD

**Issue by damirault** [Azure/azure-sdk-tools#469]
We have PowerShell SemVer parsing logic duplicated in a couple locations and should consolidate and standardize them.

- https://github.com/Azure/azure-sdk/blob/master/eng/scripts/Update-Release-Versions.ps1#L26-L58
- https://github.com/Azure/azure-sdk-for-net/blob/master/eng/Update-PkgVersion.ps1#L48
- https://github.com/Azure/azure-sdk-for-cpp/blob/master/eng/Update-PkgVersion.ps1#L48

_Originally posted by @weshaggard in https://github.com/Azure/azure-sdk-for-cpp/pull/52_

**Comment by weshaggard** [comment]
Thanks for tackling this @damirault
