### ISSUE TITLE
Adding APIView Status Check as one of SDK ArchBoard Review Exit criteria 

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#4692]
Relevant app: SDK Release App
Relevant blade: step 2.4 
Details:  Require APIView status check.  This requires clarifying exit criteria of SDK ArchBoard review - Signoff with approval in APIView of each language?

**Comment by dw511214992** [comment]
depends on https://github.com/Azure/azure-sdk-tools/issues/4815

**Comment by dw511214992** [comment]
As https://github.com/Azure/azure-sdk-tools/issues/4695 is finished and  there is no blocker, we will support it.

**Comment by dw511214992** [comment]
Create a power automate flow `Get ApiView Status`.
@zzvswxy  Please integrate it with powerapps.

**Comment by live1206** [comment]
Done for data-plane, need confirmation for management-plane

**Comment by josefree** [comment]
for management plane, .NET requires ArchBoard review and approval on each releases.  For other languages (Python, Java, JS, Go), only brand new SDK package requires ArchBoard review.  To create a new SDK version of an already onboarded service does not require ArchBoard review.

**Comment by zzvswxy** [comment]
> only brand new SDK package requires ArchBoard review.

Need to investigate how to detect the SDK is brand new SDK.

> for management plane, .NET requires ArchBoard review and approval on each releases.

Done

**Comment by zzvswxy** [comment]
Elendil give a web contains each language package csv file
https://github.com/Azure/azure-sdk/tree/main/_data/releases/latest
Will see if we can use it.

**Comment by live1206** [comment]
> Elendil give a web contains each language package csv file https://github.com/Azure/azure-sdk/tree/main/_data/releases/latest Will see if we can use it.

@zzvswxy We have stored the package list in Dataverse table `SDK Release Package`

**Comment by zzvswxy** [comment]
Checked with Elendil and Wei both `https://github.com/Azure/azure-sdk/tree/main/_data/releases/latest` and `SDK Release Package` are maintained manually. So we can't accurate detection SDK is brand new SDK. If we check SDK use these info, it may block user by mistake and we have to modify the data in DB. 

For current version, I add a icon with tool tip in Sign off page.
![image](https://user-images.githubusercontent.com/20081898/216539437-88189e79-d357-4455-9ed2-a765a8da68e6.png)

And create a issue to track if we can find a way to detect the SDK is brand new SDK.
https://github.com/Azure/azure-sdk-tools/issues/5333
If we find another way, I will update it in app.

Close this issue as .Net SDK apiview is checked in current version.

**Comment by maririos** [comment]
@MaryGao @live1206 could you explain the reasoning for reopening this issue? What is missing?

**Comment by live1206** [comment]
@maririos The ApiView check is only needed for first beta and every GA, sorry that we should have comment for this.

**Comment by zzvswxy** [comment]
Close as it has been deployed to Prod
