### ISSUE TITLE
Finding existing GitHub issues for API Reviews

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4694]
**User experience for stakeholder (API Stewardship Board member leading scheduling of API Reviews:** When a service partner schedule an API Review, look if there is an existing GitHub issue that is tracking the API review and update it vs creating a new GitHub issue. 

Example:  https://github.com/Azure/azure-rest-api-specs/issues/21166

**Options for resolving:** 

- When API Review meeting is scheduled update dataverse field API Review Private Preview scheduled to yes and keep info needed to find the GitHub issue. 
- Update the Azure Devops work item Private REST API Review with link to GitHub issue 
- Update the Azure Devops work item Private Preview API PR with link to PR 
- Adding API Review follow-up as default for meeting if a GitHub issue is found for the service and product.  

<img width="420" alt="image" src="https://user-images.githubusercontent.com/67656762/201718348-14c4edcd-35e3-48ac-a488-55977e73ea78.png">

**Comment by maririos** [comment]
Looking into this a little more here are my thoughts:
- We need to track:
  - The GitHub issue with the meeting information
  - The Github PRs the team has used for a specific release version
- The `REST API Reviews` field could be renamed to `API review tracking` where we link the GH issue for the meetings and there is a new Field for `API Review PRs`.
- When scheduling an `API Review` meeting, the scheduler tool will look at the respective ADO item and look into the `API review tracking` field to see if there is an existing issue. 
  - If there is a value, populate it in the tool.
  - If there isn't one: ask the user to provide one or the tool will create one. Etiher case, the tool will update the ADO item with the respective link.

@ladonnaq  and @markweitzel  what do you think?

**Comment by maririos** [comment]
Lowering the priority and waiting for the work to happen in Release Planner App. 
Once that is set, the Scheduler Tool can consume that information

**Comment by maririos** [comment]
The moment has come to look into this again.
@ladonnaq  what do you think about my proposal here https://github.com/Azure/azure-sdk-tools/issues/4694#issuecomment-1320461976 ?

Is the existing field currently used by something that if we modify it we will break something?

**Comment by ladonnaq** [comment]
> The moment has come to look into this again. @ladonnaq what do you think about my proposal here [#4694 (comment)](https://github.com/Azure/azure-sdk-tools/issues/4694#issuecomment-1320461976) ?
> 
> Is the existing field currently used by something that if we modify it we will break something?

The REST API Review field is a multi-text field.  Right now we are manually putting the links to the REST API Reviews and relevant pull request in this field.  We could add a different field(s) if it would be easier. 

- If the REST API Review GitHub issue that is created when an API Review is scheduled, always has the relevant PRs associated with it, then we can create a new ADO Field that is single line and the scheduler tool can update that field for "REST API Review Issue link".  
- When a service team provides a pull request link for the API Review, that link is stored in dataverse - correct?  If a service team is using API readiness app, this link should be the same one that they used for API readiness (TypeSpec validation).  Do you know if the label that indicates that the API Stewardship Board has signed off is on the PR or the GitHub issue?  This is what we really need to make sure we track so that we know that the service partner is ready to move forward (arch board, etc). 
- We can keep the existing multi-line field for history (before we automated adding the REST API Review GitHub link).

**Comment by maririos** [comment]
This is related to the work we are doing in https://github.com/Azure/azure-sdk-tools/issues/5932

**Comment by maririos** [comment]
The field we will use for this work is described here: https://github.com/Azure/azure-sdk-tools/issues/6060

Note that when looking at this data, there might be multiple values so we need to show them to the user and the user needs to decide which one to use (at least for now)

**Comment by maririos** [comment]
We need to look into this again and email the admins. It looks like we might not needed

**Comment by maririos** [comment]
Emails was sent to Mike, Mark, La Donna today

**Comment by maririos** [comment]
Dashboard information can help remove this request. We are going to wait until the dashboard is more stbale before making a call on this issue

**Comment by ladonnaq** [comment]
> Dashboard information can help remove this request. We are going to wait until the dashboard is more stbale before making a call on this issue

@maririos - I think that we can close this issue.  As long as the most recent API Review PR link (the one that is being used in the API readiness app), then that is what is needed in this field.  Since user's should be using the latest (most current) PR for the API Review and the PR should have the label indicating that the Stewardship Board signed off or ARM signed off, then the latest PR should be the most relevant.

**Comment by maririos** [comment]
Agree. Let's close it.

> > Dashboard information can help remove this request. We are going to wait until the dashboard is more stbale before making a call on this issue
> 
> @maririos Mariana Rios Flores FTE - I think that we can close this issue. As long as the most recent API Review PR link (the one that is being used in the API readiness app), then that is what is needed in this field. Since user's should be using the latest (most current) PR for the API Review and the PR should have the label indicating that the Stewardship Board signed off or ARM signed off, then the latest PR should be the most relevant.

Side note: the Stewardship board will have the neccesary information if the user booked the meeting from the Release Planner app. If not, this will be fixed with https://github.com/Azure/azure-sdk-tools/issues/6819
