### ISSUE TITLE
APIView - Get status REST API to take reviewId as optional parameter

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4695]
GetStatus API in APIView returns status of automatic API review only and this doesn't work if caller is trying to get status of a review created from PR.  We need to change this API to add an optional review ID param which will return status of review with given review ID.

REST API entry point for GetStatus. https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/APIView/APIViewWeb/Controllers/AutoReviewController.cs#L52

**Comment by maririos** [comment]
FYI @chidozieononiwu  once this change is deployed into APIView, we need to communicate it to Wei Dong so he can start consuming it in the SDK automation flow

**Comment by dw511214992** [comment]
@praveenkuttappan could you please send me the details of the rest api? I have tried it by rest api `https://apiview.dev:443/AutoReview/GetReviewStatus?reviewId=922523946df54b758ce808d3afca8353`, but get 401 Unauthorized. How can I pass the authorization? thanks
