### ISSUE TITLE
[ApiView] Swagger paths should NOT have a trailing colon

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-tools#4708]
When creating an ApiView listing for a swagger file with an [action](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#performing-an-action), the trailing colon on the path makes it look like we're sandwiching the action name in colons.  

![image](https://user-images.githubusercontent.com/1179329/202019576-e9d2d9ee-352d-4e88-a1ab-edbb01c47f3d.png)

We should remove the trailing colon on paths just like we do for verbs already.  It should instead look like:

![image](https://user-images.githubusercontent.com/1179329/202020046-ff5da481-70d0-4dd4-ada4-ae8b2503e44e.png)

**Comment by ruowan** [comment]
PR created https://github.com/Azure/azure-sdk-tools/pull/4740

**Comment by ruowan** [comment]
@tg-msft done

**Comment by maririos** [comment]
@tg-msft FYI that you won't see this fix until next APIView deployment which is scheduled for 11/28
