### ISSUE TITLE
Update AZC0002 to look for RequestOptions as well

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#4715]
Since cancellation token can be passed through the RequestContext for protocol methods we need to update this check to account for that.

https://github.com/Azure/azure-sdk-for-net/pull/32466/files#diff-4af651fe17380560084e5cb68456401c225c9a3c3f511049bbe8144e8c4eae08R6

**Comment by archerzz** [comment]
@m-nash I think the comment in the original suppression could be wrong. It should be `RequestContext`, not `RequestOptions`. @ShivangiReja Could you please confirm? Thanks.

We've already [added `RequestContext` in AZC0002](https://github.com/Azure/azure-sdk-tools/commit/17876d209b476d853f17b093a8012bea552f8354).

**Comment by m-nash** [comment]
@archerzz  yes edited the original comment.
