### ISSUE TITLE
Gate release of client libraries on REST API merge to main

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4718]
I recently discovered that we released a "stable" version of the FormRecognizer client libraries (in September) that we built using a REST API definition that was not in the "main" branch of azure-rest-api-specs.  In fact, the PR for this version  was only merged last week, after I discovered this situation and asked Joel to merge it.

https://github.com/Azure/azure-rest-api-specs/pull/20404

There was no real damage done in this particular case -- the PR was in good shape and could be merged as is.  But in general this seems like an anti-pattern.  Our SDK Guidelines say

[✅](https://azure.github.io/azure-sdk/general_design.html#general-service-apiversion-1) DO only target generally available service API versions when releasing a stable version of the client library.

And I don't think an api-version sitting in a PR should qualify as "generally available".

I know we want to allow development of a stable client library to begin before the GA REST API has been merged. But I think we need a gate before _release_ of a stable client library that ensures it only depends on REST APIs that have been fully merged to main in azure-rest-api-specs.

I did a quick scan of the azure-sdk-for-net repo and found a few more cases like this, but only a handful. So again ... not a serious issue, but something I think we should catch and prevent going forward.

**Comment by mikekistler** [comment]
Here's a script I wrote to check the `autorest.md` files in azure-sdk-for-net for references to commits in azure-rest-api-specs that are not merged to main:
```
#!/bin/bash

repo=~/Projects/Azure/azure-rest-api-specs

find sdk -name 'autorest.md' | while read f; do
    hash=$(grep -i -e '\(raw.githubusercontent\|github\).com/azure/azure-rest-api-specs/' $f \
                  | sed 's|.*azure-rest-api-specs\(/blob\)\{0,1\}/\([^/]*\).*|\2|' | sort | uniq)
    for h in $(echo $hash); do
        echo "$h $f"
    done
done | grep -v -e '^\(master\|main\|tree\|issues\)' | \
while read h f; do
    if [ -z "$(git -C $repo cat-file -t $h 2>/dev/null)" ]; then
        echo "$h $f";
    elif [ -z "$(git -C $repo branch main --contains $h)" ]; then
        echo "$h $f";
    fi
done
```

and here's what it found:
```
2fd7dcd89afa70ff5ba7be88bee987da62099a28 sdk/formrecognizer/Azure.AI.FormRecognizer/src/autorest.md
f6fab392bec9dbb3ceeb01c4604eba6d929e0074 sdk/storage/Azure.Storage.Files.DataLake/src/autorest.md
f8c3f91da6a9ed64b687711af64e8d70cb500e1d sdk/storage/Azure.Storage.Blobs.Batch/src/autorest.md
4a93ab078fba7f087116283c8ed169f9b8e30397 sdk/storage/Azure.Storage.Queues/src/autorest.md
da15318e582f0cd1ea01e7a2556190c98aa1578f sdk/appcomplianceautomation/Azure.ResourceManager.AppComplianceAutomation/src/autorest.md
75a8d8dcc9f6d0ec626bdeb32f5154f20c8c61cd sdk/devcenter/Azure.Developer.DevCenter/src/autorest.md
e30976f6ccb058a36cd2f9d5160e1fd51f6c5d95 sdk/communication/Azure.Communication.Rooms/src/autorest.md
140b5b64350c17e0900034d66cee2d6623af3ea8 sdk/communication/Azure.Communication.MediaComposition/src/autorest.md
d0d60267975bf5823a9173ce0c926659bc9775bb sdk/communication/Azure.Communication.Chat/src/autorest.md
e5bc61526e11f9b51e1e098d71a730f1494bc2f8 sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/autorest.md
50adac0106ba23718cb6b736d69cf834ae37f505 sdk/quantum/Azure.Quantum.Jobs/src/autorest.md
```

**Comment by josefree** [comment]
@dw511214992 let's take this as a requirement to SDK release app

**Comment by dw511214992** [comment]
In sdk release app, we can block sdk release when the spec PR is not merged.

**Comment by dw511214992** [comment]
@josefree do you think it's necessary to check whether the spec PR is merged before release sdks?

**Comment by maririos** [comment]
> @josefree do you think it's necessary to check whether the spec PR is merged before release sdks?

Yes. this comes from feedback about the flow and how it is important that no SDK ships from a spec PR that is not merged in main.

**Comment by zzvswxy** [comment]
will  check spec pr status in step3

**Comment by m-nash** [comment]
This will also be an issue for the new [cadl-location.yaml](https://github.com/Azure/azure-sdk-for-net/blob/1849a21f5a4305a2b08ae2d749a6d406cb55a7f6/sdk/openai/Azure.AI.OpenAI/src/cadl-location.yaml) file that is used to pin a language sdk to a specific commit of a spec for cadl.

There are one thing here that we probably want to block the release pipeline on if they exist.
1. If the sha is not in the main branch
   a.  We will need a way to override this in the rare event we ship from a hotfix branch.

There is another thing we probably want to block commit preferably or PR merge if we can't do commit.
2. If the spec repo doesn't match the language repo.  I.e. if the language repo is azure-sdk-for-net and the spec repo is azure-rest-api-specs-pr or vice versa.

**Comment by dw511214992** [comment]
move @m-nash 's comment to a new issue: https://github.com/Azure/azure-sdk-tools/issues/5387

**Comment by zzvswxy** [comment]
> will check spec pr status in step3

As the spec pr status checked in step3, and deploy on product. Other questions will track in new issues.
