### ISSUE TITLE
SDK generation result is not showing

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#4736]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/5196139/202394093-23eb0f20-614d-4a0d-a0c0-062626968ed9.png">
Corresponding PR:   https://github.com/Azure/azure-rest-api-specs/pull/21393

**Comment by dw511214992** [comment]
it's caused by unexpected response of openapi-hub
![image](https://user-images.githubusercontent.com/40835867/202394748-d5dfe5e1-dfba-4e38-aa3c-a4c01ef6c4fb.png)

**Comment by live1206** [comment]
Change to connect to OpenAPI hub in Prod, it is showing now
<img width="866" alt="image" src="https://user-images.githubusercontent.com/5196139/202599527-021c4f16-2bbf-416e-8a3a-ba7d8b49fbab.png">
