### ISSUE TITLE
Add ability to force live test resources to be created in a given subscription

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#474]
It looks like live test resources have been getting created in the Playground subscription. We need to force these to be created in the Test Resources subscription.

**Comment by heaths** [comment]
I would call it `-SubscriptionId` for consistency. The variable group also needs to be passed the right secret value (it's using a similar - but non-existent - variable name).

**Comment by heaths** [comment]
Note this should also be an optional parameter, so I recommend relying on splatting to conditionally add it to `Connect-AzAccount` and other cmdlets as needed.

**Comment by heaths** [comment]
Please update this repo from my changes in https://github.com/Azure/azure-sdk-for-net/pull/10983. Probably would be a good time to remove the files directly in eng/ and update the YAMLs to use the ones in eng/common.
