### ISSUE TITLE
[ApiView] Swagger view should remember what's been expanded

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-tools#4749]
If you expand some of the nodes in the swagger view and refresh the browser, it will collapse everything again.  I often need to refresh to check if my comment was correctly applied or if other comments were added and it's very jarring to have my context disappear.  It'd be great to remember the state of whether things were collapsed in a local cookie.

**Comment by chidozieononiwu** [comment]
@tg-msft do we want this to be persisted across different browsing sessions (tabs), or should it only be before reload of the same (session) tab then cleared on session end?
