### ISSUE TITLE
DocWarden exclusions are case-sensitive

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#4751]
The `omitted_paths` in _.docsettings.yml_ are treated case-sensitive, which can be a problem in some cases. It would be great if any file paths are matched case-insensitively to avoid needing otherwise redundant paths/globs.

**Comment by kurtzeborn** [comment]
Yes, this is a less than desirable behavior in doc warden.  Longer term though we're rather invest in moving away from doc warden to another, standard md linting tool.  So we're probably not going to fix this.  
@heaths, if this is causing you immediate pain, feel free to open a PR to doc warden and @scbedd or @weshaggard can review.

**Comment by heaths** [comment]
Would those standard linting tools happen to be ones that power the extensions for VSCode? That would be ideal, as 1) I know the Microsoft Docs team uses those in their pipeline, and 2) they encourage - and therefore I have - the extensions to be used, so now we have one set of rules/exemptions/etc.

**Comment by weshaggard** [comment]
Yet to be determined but we have issue https://github.com/Azure/azure-sdk-tools/issues/1896 that is tracking to a more mainstream MD linter tool.
