### ISSUE TITLE
[ApiView] Fix swagger apiParser CI pipeline run empty unit test

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-sdk-tools#4753]
The unit test in swagger apiParser CI is empty. Actually we have swaggerApiParserTest project. We should run unittest on this project.

**Comment by praveenkuttappan** [comment]
@ruowan  Is this still pending?

**Comment by ruowan** [comment]
The pipeline is not pending. But the seems the unit tests under swaggerApiParserTest project actually doesn't run.

**Comment by maririos** [comment]
@chidozieononiwu could you take a look at this as part of your work on testing?

**Comment by chidozieononiwu** [comment]
We don't build or test the swager parser as part of the apiview pipeline. Do we want to add that?

**Comment by maririos** [comment]
Ideally if there are test for each parser, we should make sure they run on CI so when new changes are added they are not breaking. 
What do you think will be best?
