### ISSUE TITLE
Resolved threads make the current APIs hard to read

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#4755]
When a discussion thread is resolved in API View, we show something along the lines of "This thread is marked resolved by KrzysztofCwalina [(show)]" between API listing lines. When there is a lot of resolved threads, it's difficult to see the overall shape of the APIs. 

Feature Requests: show resolved threads as a gyph at the beginning of the line as opposed to a new line. When the user hovers the mouse pointer over the glyph, a summary (or summaries) of the resolved discussion will be shown in a pop up bubble.

**Comment by KrzysztofCwalina** [comment]
> Does this satisfy your requirement?

It's close, but: a) could we make it the default. b) could hovering the pointer over the glyphs show a summary of the issue/comments?

**Comment by maririos** [comment]
> could we make it the default. 

The purpose of APIView is to have a review discussion so having the comments enable by default is what we advocate for. If you want the feature to be oof by default only for you, you could un-select it and we will remember your preference and preserve it.
@chidozieononiwu correct me here if I'm wrong on user preferences.

>  b) could hovering the pointer over the glyphs show a summary of the issue/comments?

We could def look into this :)

**Comment by chidozieononiwu** [comment]
Show / Hide comments is not currently part of UserPreference. I will work to have it added https://github.com/Azure/azure-sdk-tools/issues/new

**Comment by maririos** [comment]
>b) could hovering the pointer over the glyphs show a summary of the issue/comments?
We could def look into this :)

Issue https://github.com/Azure/azure-sdk-tools/issues/4584

**Comment by maririos** [comment]
Request are going to be covered by individual issues so closing this one. @KrzysztofCwalina feel free to re-open if you think there is something else we should cover
