### ISSUE TITLE
API View - Add ability to name reviews

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-tools#476]
In my work flow, I create an API View review for each major feature I add to Storage.  A lot of times, these feature are in the same DLL, like Azure.Storage.Blobs.

I'd like the ability to manually name reviews in the API View tool, so I don't have multiple reviews named "Azure.Storage.Blobs"

(Only assigned to @tg-msft for triage)

**Comment by kurtzeborn** [comment]
@praveenkuttappan, this is something high on the list we've talked about adding.  Now we've got an important partner (storage team) asking for exactly this.

**Comment by praveenkuttappan** [comment]
I will get this one prioritized and make update.

**Comment by maririos** [comment]
@praveenkuttappan curious about the update on the work for this feature.

**Comment by praveenkuttappan** [comment]
@maririos  This is still a pending item since my focus is on JS integration into API view tool. This is still on my next set of enhancement in API view tool.

**Comment by maririos** [comment]
Thanks @praveenkuttappan
