### ISSUE TITLE
Add release version to the Release Planner App

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4760]
Similar to what we do in the Scheduler app. This is mainly for troubleshooting purposes.
The versioning doesn't have to be the same as the Scheduler app. Suggestion is to have the same format, which is based on our SDK versioning strategy. i.e. `1.0.0-beta.X`.

**Comment by live1206** [comment]
![image](https://user-images.githubusercontent.com/5196139/203016995-e78306ff-f364-45b9-859a-11bbf28db7c8.png)
