### ISSUE TITLE
[FEATURE REQ] Add a check that will block a mismatch of publicness between the spec and language repos

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#4767]
There are 2 places where we can point at the spec repo.  Either in an autorest.md file or in a new cadl-location.yaml file.  In either case we should have a check that if the current commit is going into the public language repo then it MUST point at a public spec repo in those places.  Only if the commit is going to the private repo is it allowed to point at the private spec repo.

**Comment by ladonnaq** [comment]
@m-nash - I am working on the extended engagement experience roadmap.  As part of that work, I am reviewing all of the issues in backlog.  Is this requirement still valid?   If not, when in the end-to-end process would you expect this validation to happen?  Before the API Spec PR merges, SDK generation, SDK release, ....?

**Comment by maririos** [comment]
There is a cehck for this now in the data plane release pipelines
