### ISSUE TITLE
When a service team updates the API Spec for maintenance/bug fix, ensure that a new version of the SDK is released 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4768]
In speaking with Pramod (pramod.valavala@microsoft.com) from the Azure CXP team he mentioned that is common to see issues where the management plane (ARM) API Spec is updated but the service team does not request new SDK versions, which results in bugs/issues opened by customers.  

I am opening this GitHub issue so that when we are ready to document the maintenance/bug fix release plan for management plane that we remember to ensure that this gap is resolved.

**Comment by josefree** [comment]
I see Marianna created a similar issue

**Comment by josefree** [comment]
let's focus on main scenario initiated from PLR check first.

**Comment by maririos** [comment]
If the user creates a Release Plan for every update they need to do to a REST API spec, then they will know they need to release an SDK.
Because this is already in place, I am going to close this issue
