### ISSUE TITLE
C++ recording issue

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-tools#4770]
when recording a request for C++ test i registered the following sanizers 

 {

    std::string body = "{\"key\" : \"Location\",\"value\" : \"REDACTED\",\"regex\": "
                       "\"https://(?<account>[a-zA-Z]+).*\",\"groupForReplace\" : \"account\"}";

    Azure::Core::IO::MemoryBodyStream payloadStream(
        reinterpret_cast<const uint8_t*>(body.data()), body.size());
    Azure::Core::Http::Request request(
        Azure::Core::Http::HttpMethod::Post, sanitizerRequest, &payloadStream);
    request.SetHeader("x-abstraction-identifier", "UriRegexSanitizer");
    Azure::Core::Context ctx;
    auto response = m_privatePipeline->Send(request, ctx);
  }
  {

    std::string body = "{\"key\" : \"Location\",\"value\" : \"REDACTED\",\"regex\": "
                       "\"https://(?<account>[a-zA-Z]+).*\",\"groupForReplace\" : \"account\"}";

    Azure::Core::IO::MemoryBodyStream payloadStream(
        reinterpret_cast<const uint8_t*>(body.data()), body.size());
    Azure::Core::Http::Request request(
        Azure::Core::Http::HttpMethod::Post, sanitizerRequest, &payloadStream);
    request.SetHeader("x-abstraction-identifier", "BodyRegexSanitizer");
    Azure::Core::Context ctx;
    auto response = m_privatePipeline->Send(request, ctx);
  }
  {

    std::string body = "{\"key\" : \"Location\",\"value\" : \"REDACTED\",\"regex\": "
                       "\"https://(?<account>[a-zA-Z]+).*\",\"groupForReplace\" : \"account\"}";

    Azure::Core::IO::MemoryBodyStream payloadStream(
        reinterpret_cast<const uint8_t*>(body.data()), body.size());
    Azure::Core::Http::Request request(
        Azure::Core::Http::HttpMethod::Post, sanitizerRequest, &payloadStream);
    request.SetHeader("x-abstraction-identifier", "HeaderRegexSanitizer");
    Azure::Core::Context ctx;
    auto response = m_privatePipeline->Send(request, ctx);
  }
  {

    std::string body = "{\"key\" : \"Location\",\"value\" : \"REDACTED\",\"regex\": "
                       "\"https://(?<account>[a-zA-Z]+).*\",\"groupForReplace\" : \"account\"}";

    Azure::Core::IO::MemoryBodyStream payloadStream(
        reinterpret_cast<const uint8_t*>(body.data()), body.size());
    Azure::Core::Http::Request request(
        Azure::Core::Http::HttpMethod::Post, sanitizerRequest, &payloadStream);
    request.SetHeader("x-abstraction-identifier", "GeneralRegexSanitizer");
    Azure::Core::Context ctx;
    auto response = m_privatePipeline->Send(request, ctx);
  }

From what i see in the recordings not all matches are replaced 

{
  "Entries": [
    {
      "RequestUri": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/create?api-version=7.3",
      "RequestMethod": "POST",
      "RequestHeaders": {
        "Authorization": "Sanitized",
        "Content-Length": "377",
        "Content-Type": "application/json",
        "User-Agent": "azsdk-cpp-keyvault-certificates/4.2.0-beta.1 (Windows 10 Enterprise 6.3 22621 22621.1.amd64fre.ni_release.220506-1250)",
        "x-ms-client-request-id": "dced16ea-e2b2-4f5b-471c-eb2306f0edb9"
      },
      "RequestBody": {
        "attributes": {
          "enabled": true
        },
        "policy": {
          "attributes": {
            "enabled": true
          },
          "issuer": {
            "name": "Self"
          },
          "key_props": null,
          "lifetime_actions": [
            {
              "action": {
                "action_type": "AutoRenew"
              },
              "trigger": {
                "lifetime_percentage": 80
              }
            }
          ],
          "secret_props": {
            "contentType": "application/x-pkcs12"
          },
          "x509_props": {
            "dns_names": [],
            "ekus": [],
            "emails": [],
            "subject": "CN=xyz",
            "upns": [],
            "validity_months": 12
          }
        },
        "tags": {}
      },
      "StatusCode": 202,
      "ResponseHeaders": {
        "Cache-Control": "no-cache",
        "Content-Length": "1250",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Mon, 21 Nov 2022 22:35:30 GMT",
        "Expires": "-1",
        "Location": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/pending?api-version=7.3\u0026request_id=5f6d8f1301ac4ca8a308829479b1dddb",
        "Pragma": "no-cache",
        "Retry-After": "10",
        "Strict-Transport-Security": "max-age=31536000;includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "x-ms-client-request-id": "dced16ea-e2b2-4f5b-471c-eb2306f0edb9",
        "x-ms-keyvault-network-info": "conn_type=Ipv4;addr=24.22.157.72;act_addr_fam=InterNetwork;",
        "x-ms-keyvault-region": "westus3",
        "x-ms-keyvault-service-version": "1.9.576.1",
        "x-ms-request-id": "a3a4582f-99ef-49cd-b447-fc86dda28812"
      },
      "ResponseBody": {
        "id": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/pending",
        "issuer": {
          "name": "Self"
        },
        "csr": "MIICfzCCAWcCAQAwDjEMMAoGA1UEAxMDeHl6MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApE9wbPTj5S0cII3Xe1PPtesJJ1sPVEoMo5/GYgQsIUvCdY5l8v7DIUhuj2GNt0xkSjzCGfHDOtLz4R30Nq6wyUm5OxEGUAJnLxFWoNgOccnVPBxJXzSzsvf2sHV7IvsCJ/7dmFggd5qQb5SkjgqYeogb0WX4Szu2i465qFLal7Iv0S3SUP1i7pdqmLFO6/LERzjVIuun2r9N10Ir2Lx4VMjukIGnz0NGYrDONuGWRq0GwFb12pWGIq8oFbR81i/ZOxWxVbNDjLlUDGNgYbpVWswmhaRhlHYFPWxvZlXg9Q0pDoVkwIyoHrEsW0iXCUkSgEbeZ8Z2yFJMvnHEaCKc9QIDAQABoCwwKgYJKoZIhvcNAQkOMR0wGzAOBgNVHQ8BAf8EBAMCBaAwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEAk3kRDZxA75zCk0pL3VfH3GUuCYNqey2TRk0jyeM/7CojW4WhwuZerZ9yqRpmonM\u002BjnV/2vnKSvY2buLtf8PaLyAWktxfkl4MyEDOFPT9xAbltTF8Y8ExVh7on2NVUn9XLiznHPYM8tRztDVbejYnlPGBu0SsH3IV\u002BFvMjeFwrUztVX7lArQaYcxkathjgI1uztadil/e56Vx4/SYVeFwKIavW1woEe7QTltSCGlP39uqHXELFId5Hllq84KCkZHuPUdcIQGjnxB\u002B4Soy\u002Bqr9SqS1W52iNG\u002BovOczGXB58xhl/fb7Ej5SpKxV2Vo2zUGG7fELPiPqGLofbvGrGJw7Dw==",
        "cancellation_requested": false,
        "status": "inProgress",
        "status_details": "Pending certificate created. Certificate request is in progress. This may take some time based on the issuer provider. Please check again later.",
        "request_id": "5f6d8f1301ac4ca8a308829479b1dddb"
      }
    },
    {
      "RequestUri": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/pending?api-version=7.3",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Authorization": "Sanitized",
        "Content-Length": "0",
        "Content-Type": "application/json",
        "User-Agent": "azsdk-cpp-keyvault-certificates/4.2.0-beta.1 (Windows 10 Enterprise 6.3 22621 22621.1.amd64fre.ni_release.220506-1250)",
        "x-ms-client-request-id": "660bd42b-e945-45c8-449c-ad2b6f56680a"
      },
      "RequestBody": null,
      "StatusCode": 200,
      "ResponseHeaders": {
        "Cache-Control": "no-cache",
        "Content-Length": "1250",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Mon, 21 Nov 2022 22:35:30 GMT",
        "Expires": "-1",
        "Pragma": "no-cache",
        "Retry-After": "10",
        "Strict-Transport-Security": "max-age=31536000;includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "x-ms-client-request-id": "660bd42b-e945-45c8-449c-ad2b6f56680a",
        "x-ms-keyvault-network-info": "conn_type=Ipv4;addr=24.22.157.72;act_addr_fam=InterNetwork;",
        "x-ms-keyvault-region": "westus3",
        "x-ms-keyvault-service-version": "1.9.576.1",
        "x-ms-request-id": "be3f9cc2-59b4-45fd-906c-3398e4cd2a8d"
      },
      "ResponseBody": {
        "id": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/pending",
        "issuer": {
          "name": "Self"
        },
        "csr": "MIICfzCCAWcCAQAwDjEMMAoGA1UEAxMDeHl6MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApE9wbPTj5S0cII3Xe1PPtesJJ1sPVEoMo5/GYgQsIUvCdY5l8v7DIUhuj2GNt0xkSjzCGfHDOtLz4R30Nq6wyUm5OxEGUAJnLxFWoNgOccnVPBxJXzSzsvf2sHV7IvsCJ/7dmFggd5qQb5SkjgqYeogb0WX4Szu2i465qFLal7Iv0S3SUP1i7pdqmLFO6/LERzjVIuun2r9N10Ir2Lx4VMjukIGnz0NGYrDONuGWRq0GwFb12pWGIq8oFbR81i/ZOxWxVbNDjLlUDGNgYbpVWswmhaRhlHYFPWxvZlXg9Q0pDoVkwIyoHrEsW0iXCUkSgEbeZ8Z2yFJMvnHEaCKc9QIDAQABoCwwKgYJKoZIhvcNAQkOMR0wGzAOBgNVHQ8BAf8EBAMCBaAwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEAk3kRDZxA75zCk0pL3VfH3GUuCYNqey2TRk0jyeM/7CojW4WhwuZerZ9yqRpmonM\u002BjnV/2vnKSvY2buLtf8PaLyAWktxfkl4MyEDOFPT9xAbltTF8Y8ExVh7on2NVUn9XLiznHPYM8tRztDVbejYnlPGBu0SsH3IV\u002BFvMjeFwrUztVX7lArQaYcxkathjgI1uztadil/e56Vx4/SYVeFwKIavW1woEe7QTltSCGlP39uqHXELFId5Hllq84KCkZHuPUdcIQGjnxB\u002B4Soy\u002Bqr9SqS1W52iNG\u002BovOczGXB58xhl/fb7Ej5SpKxV2Vo2zUGG7fELPiPqGLofbvGrGJw7Dw==",
        "cancellation_requested": false,
        "status": "inProgress",
        "status_details": "Pending certificate created. Certificate request is in progress. This may take some time based on the issuer provider. Please check again later.",
        "request_id": "5f6d8f1301ac4ca8a308829479b1dddb"
      }
    },
    {
      "RequestUri": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/pending?api-version=7.3",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Authorization": "Sanitized",
        "Content-Length": "0",
        "Content-Type": "application/json",
        "User-Agent": "azsdk-cpp-keyvault-certificates/4.2.0-beta.1 (Windows 10 Enterprise 6.3 22621 22621.1.amd64fre.ni_release.220506-1250)",
        "x-ms-client-request-id": "444ac1e8-e2d5-48b0-7797-c0750e8a0cf7"
      },
      "RequestBody": null,
      "StatusCode": 200,
      "ResponseHeaders": {
        "Cache-Control": "no-cache",
        "Content-Length": "1250",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Mon, 21 Nov 2022 22:35:30 GMT",
        "Expires": "-1",
        "Pragma": "no-cache",
        "Retry-After": "10",
        "Strict-Transport-Security": "max-age=31536000;includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "x-ms-client-request-id": "444ac1e8-e2d5-48b0-7797-c0750e8a0cf7",
        "x-ms-keyvault-network-info": "conn_type=Ipv4;addr=24.22.157.72;act_addr_fam=InterNetwork;",
        "x-ms-keyvault-region": "westus3",
        "x-ms-keyvault-service-version": "1.9.576.1",
        "x-ms-request-id": "ffaf0265-4c98-4742-9857-71f61a71d736"
      },
      "ResponseBody": {
        "id": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/pending",
        "issuer": {
          "name": "Self"
        },
        "csr": "MIICfzCCAWcCAQAwDjEMMAoGA1UEAxMDeHl6MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApE9wbPTj5S0cII3Xe1PPtesJJ1sPVEoMo5/GYgQsIUvCdY5l8v7DIUhuj2GNt0xkSjzCGfHDOtLz4R30Nq6wyUm5OxEGUAJnLxFWoNgOccnVPBxJXzSzsvf2sHV7IvsCJ/7dmFggd5qQb5SkjgqYeogb0WX4Szu2i465qFLal7Iv0S3SUP1i7pdqmLFO6/LERzjVIuun2r9N10Ir2Lx4VMjukIGnz0NGYrDONuGWRq0GwFb12pWGIq8oFbR81i/ZOxWxVbNDjLlUDGNgYbpVWswmhaRhlHYFPWxvZlXg9Q0pDoVkwIyoHrEsW0iXCUkSgEbeZ8Z2yFJMvnHEaCKc9QIDAQABoCwwKgYJKoZIhvcNAQkOMR0wGzAOBgNVHQ8BAf8EBAMCBaAwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEAk3kRDZxA75zCk0pL3VfH3GUuCYNqey2TRk0jyeM/7CojW4WhwuZerZ9yqRpmonM\u002BjnV/2vnKSvY2buLtf8PaLyAWktxfkl4MyEDOFPT9xAbltTF8Y8ExVh7on2NVUn9XLiznHPYM8tRztDVbejYnlPGBu0SsH3IV\u002BFvMjeFwrUztVX7lArQaYcxkathjgI1uztadil/e56Vx4/SYVeFwKIavW1woEe7QTltSCGlP39uqHXELFId5Hllq84KCkZHuPUdcIQGjnxB\u002B4Soy\u002Bqr9SqS1W52iNG\u002BovOczGXB58xhl/fb7Ej5SpKxV2Vo2zUGG7fELPiPqGLofbvGrGJw7Dw==",
        "cancellation_requested": false,
        "status": "inProgress",
        "status_details": "Pending certificate created. Certificate request is in progress. This may take some time based on the issuer provider. Please check again later.",
        "request_id": "5f6d8f1301ac4ca8a308829479b1dddb"
      }
    },
    {
      "RequestUri": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/pending?api-version=7.3",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Authorization": "Sanitized",
        "Content-Length": "0",
        "Content-Type": "application/json",
        "User-Agent": "azsdk-cpp-keyvault-certificates/4.2.0-beta.1 (Windows 10 Enterprise 6.3 22621 22621.1.amd64fre.ni_release.220506-1250)",
        "x-ms-client-request-id": "d292908e-9547-48d8-79e1-422518d4af17"
      },
      "RequestBody": null,
      "StatusCode": 200,
      "ResponseHeaders": {
        "Cache-Control": "no-cache",
        "Content-Length": "1171",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Mon, 21 Nov 2022 22:35:49 GMT",
        "Expires": "-1",
        "Pragma": "no-cache",
        "Strict-Transport-Security": "max-age=31536000;includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "x-ms-client-request-id": "d292908e-9547-48d8-79e1-422518d4af17",
        "x-ms-keyvault-network-info": "conn_type=Ipv4;addr=24.22.157.72;act_addr_fam=InterNetwork;",
        "x-ms-keyvault-region": "westus3",
        "x-ms-keyvault-service-version": "1.9.576.1",
        "x-ms-request-id": "0240b9cb-417f-4982-b9a0-cc02028eca6a"
      },
      "ResponseBody": {
        "id": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/pending",
        "issuer": {
          "name": "Self"
        },
        "csr": "MIICfzCCAWcCAQAwDjEMMAoGA1UEAxMDeHl6MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApE9wbPTj5S0cII3Xe1PPtesJJ1sPVEoMo5/GYgQsIUvCdY5l8v7DIUhuj2GNt0xkSjzCGfHDOtLz4R30Nq6wyUm5OxEGUAJnLxFWoNgOccnVPBxJXzSzsvf2sHV7IvsCJ/7dmFggd5qQb5SkjgqYeogb0WX4Szu2i465qFLal7Iv0S3SUP1i7pdqmLFO6/LERzjVIuun2r9N10Ir2Lx4VMjukIGnz0NGYrDONuGWRq0GwFb12pWGIq8oFbR81i/ZOxWxVbNDjLlUDGNgYbpVWswmhaRhlHYFPWxvZlXg9Q0pDoVkwIyoHrEsW0iXCUkSgEbeZ8Z2yFJMvnHEaCKc9QIDAQABoCwwKgYJKoZIhvcNAQkOMR0wGzAOBgNVHQ8BAf8EBAMCBaAwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEAk3kRDZxA75zCk0pL3VfH3GUuCYNqey2TRk0jyeM/7CojW4WhwuZerZ9yqRpmonM\u002BjnV/2vnKSvY2buLtf8PaLyAWktxfkl4MyEDOFPT9xAbltTF8Y8ExVh7on2NVUn9XLiznHPYM8tRztDVbejYnlPGBu0SsH3IV\u002BFvMjeFwrUztVX7lArQaYcxkathjgI1uztadil/e56Vx4/SYVeFwKIavW1woEe7QTltSCGlP39uqHXELFId5Hllq84KCkZHuPUdcIQGjnxB\u002B4Soy\u002Bqr9SqS1W52iNG\u002BovOczGXB58xhl/fb7Ej5SpKxV2Vo2zUGG7fELPiPqGLofbvGrGJw7Dw==",
        "cancellation_requested": false,
        "status": "completed",
        "target": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken",
        "request_id": "5f6d8f1301ac4ca8a308829479b1dddb"
      }
    },
    {
      "RequestUri": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/pending?api-version=7.3",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Authorization": "Sanitized",
        "Content-Length": "0",
        "Content-Type": "application/json",
        "User-Agent": "azsdk-cpp-keyvault-certificates/4.2.0-beta.1 (Windows 10 Enterprise 6.3 22621 22621.1.amd64fre.ni_release.220506-1250)",
        "x-ms-client-request-id": "a622e6ea-b0f0-4448-5ae9-6ce20628abf2"
      },
      "RequestBody": null,
      "StatusCode": 200,
      "ResponseHeaders": {
        "Cache-Control": "no-cache",
        "Content-Length": "1171",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Mon, 21 Nov 2022 22:35:50 GMT",
        "Expires": "-1",
        "Pragma": "no-cache",
        "Strict-Transport-Security": "max-age=31536000;includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "x-ms-client-request-id": "a622e6ea-b0f0-4448-5ae9-6ce20628abf2",
        "x-ms-keyvault-network-info": "conn_type=Ipv4;addr=24.22.157.72;act_addr_fam=InterNetwork;",
        "x-ms-keyvault-region": "westus3",
        "x-ms-keyvault-service-version": "1.9.576.1",
        "x-ms-request-id": "5044e241-c952-461e-b923-ad664e512a1a"
      },
      "ResponseBody": {
        "id": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/pending",
        "issuer": {
          "name": "Self"
        },
        "csr": "MIICfzCCAWcCAQAwDjEMMAoGA1UEAxMDeHl6MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApE9wbPTj5S0cII3Xe1PPtesJJ1sPVEoMo5/GYgQsIUvCdY5l8v7DIUhuj2GNt0xkSjzCGfHDOtLz4R30Nq6wyUm5OxEGUAJnLxFWoNgOccnVPBxJXzSzsvf2sHV7IvsCJ/7dmFggd5qQb5SkjgqYeogb0WX4Szu2i465qFLal7Iv0S3SUP1i7pdqmLFO6/LERzjVIuun2r9N10Ir2Lx4VMjukIGnz0NGYrDONuGWRq0GwFb12pWGIq8oFbR81i/ZOxWxVbNDjLlUDGNgYbpVWswmhaRhlHYFPWxvZlXg9Q0pDoVkwIyoHrEsW0iXCUkSgEbeZ8Z2yFJMvnHEaCKc9QIDAQABoCwwKgYJKoZIhvcNAQkOMR0wGzAOBgNVHQ8BAf8EBAMCBaAwCQYDVR0TBAIwADANBgkqhkiG9w0BAQsFAAOCAQEAk3kRDZxA75zCk0pL3VfH3GUuCYNqey2TRk0jyeM/7CojW4WhwuZerZ9yqRpmonM\u002BjnV/2vnKSvY2buLtf8PaLyAWktxfkl4MyEDOFPT9xAbltTF8Y8ExVh7on2NVUn9XLiznHPYM8tRztDVbejYnlPGBu0SsH3IV\u002BFvMjeFwrUztVX7lArQaYcxkathjgI1uztadil/e56Vx4/SYVeFwKIavW1woEe7QTltSCGlP39uqHXELFId5Hllq84KCkZHuPUdcIQGjnxB\u002B4Soy\u002Bqr9SqS1W52iNG\u002BovOczGXB58xhl/fb7Ej5SpKxV2Vo2zUGG7fELPiPqGLofbvGrGJw7Dw==",
        "cancellation_requested": false,
        "status": "completed",
        "target": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken",
        "request_id": "5f6d8f1301ac4ca8a308829479b1dddb"
      }
    },
    {
      "RequestUri": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken?api-version=7.3",
      "RequestMethod": "GET",
      "RequestHeaders": {
        "Authorization": "Sanitized",
        "Content-Length": "0",
        "Content-Type": "application/json",
        "User-Agent": "azsdk-cpp-keyvault-certificates/4.2.0-beta.1 (Windows 10 Enterprise 6.3 22621 22621.1.amd64fre.ni_release.220506-1250)",
        "x-ms-client-request-id": "959511ca-c38b-432d-7c3f-9a2d5e9b1d4c"
      },
      "RequestBody": null,
      "StatusCode": 200,
      "ResponseHeaders": {
        "Cache-Control": "no-cache",
        "Content-Length": "2291",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Mon, 21 Nov 2022 22:35:50 GMT",
        "Expires": "-1",
        "Pragma": "no-cache",
        "Strict-Transport-Security": "max-age=31536000;includeSubDomains",
        "X-Content-Type-Options": "nosniff",
        "x-ms-client-request-id": "959511ca-c38b-432d-7c3f-9a2d5e9b1d4c",
        "x-ms-keyvault-network-info": "conn_type=Ipv4;addr=24.22.157.72;act_addr_fam=InterNetwork;",
        "x-ms-keyvault-region": "westus3",
        "x-ms-keyvault-service-version": "1.9.576.1",
        "x-ms-request-id": "92ff3614-b72f-49f1-9210-2fa9e75ffa88"
      },
      "ResponseBody": {
        "id": "https://REDACTED.vault.azure.net/certificates/CreateCertificateResumeToken/95e8832e3236415da174dc5ad065472d",
        "kid": "https://REDACTED.vault.azure.net/keys/CreateCertificateResumeToken/95e8832e3236415da174dc5ad065472d",
        "sid": "https://gearamakeyvault.vault.azure.net/secrets/CreateCertificateResumeToken/95e8832e3236415da174dc5ad065472d",
        "x5t": "j9bUqaOsP55MBDUIS2-_ijXSuv8",
        "cer": "MIIDAzCCAeugAwIBAgIQNZDnAYcKTauW1ihumRvdmzANBgkqhkiG9w0BAQsFADAOMQwwCgYDVQQDEwN4eXowHhcNMjIxMTIxMjIyNTMwWhcNMjMxMTIxMjIzNTMwWjAOMQwwCgYDVQQDEwN4eXowggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCkT3Bs9OPlLRwgjdd7U8\u002B16wknWw9USgyjn8ZiBCwhS8J1jmXy/sMhSG6PYY23TGRKPMIZ8cM60vPhHfQ2rrDJSbk7EQZQAmcvEVag2A5xydU8HElfNLOy9/awdXsi\u002BwIn/t2YWCB3mpBvlKSOCph6iBvRZfhLO7aLjrmoUtqXsi/RLdJQ/WLul2qYsU7r8sRHONUi66fav03XQivYvHhUyO6QgafPQ0ZisM424ZZGrQbAVvXalYYirygVtHzWL9k7FbFVs0OMuVQMY2BhulVazCaFpGGUdgU9bG9mVeD1DSkOhWTAjKgesSxbSJcJSRKARt5nxnbIUky\u002BccRoIpz1AgMBAAGjXTBbMA4GA1UdDwEB/wQEAwIFoDAJBgNVHRMEAjAAMB8GA1UdIwQYMBaAFFb7o\u002BaB8lPmeHntJ0Bs4\u002B6z5kg2MB0GA1UdDgQWBBRW\u002B6PmgfJT5nh57SdAbOPus\u002BZINjANBgkqhkiG9w0BAQsFAAOCAQEAJ8biQ1MIuOjSgnLaqJYNXhe1mdjGKK1I14uFFl0IpynsuPgSlYzQnQOePBWkwS2qIPY\u002BtLTaQga0Y7yf5sAZuh0eRT8ZH\u002BhIGNKm0lHfv2bdhN1B7qsh9FExGaQ7T\u002BZampBt0HqUajWQgjTnelYlMIazfyKL31AqQhfeUifwhkQXtXUk5sLb0Gpsz\u002BKaJgE5TY1jUV2RVcD0uWKHFEck9qTi3oqOwL6nmJlYpzB9p\u002B/Kc52d5TAIC4hSPWZWv6JRVJVl3ib0qQBCRIZFZEIkIc529UvrQ6kg0QFS\u002B/l8pV6NTQ7Gh9XGLmJf6Cs3UIHmCK2SiVW96ubM\u002BfU/\u002B/OLSA==",
        "attributes": {
          "enabled": true,
          "nbf": 1669069530,
          "exp": 1700606130,
          "created": 1669070131,
          "updated": 1669070131,
          "recoveryLevel": "Recoverable\u002BPurgeable",
          "recoverableDays": 90
        },
        "tags": {},
        "policy": {
          "id": "https://gearamakeyvault.vault.azure.net/certificates/CreateCertificateResumeToken/policy",
          "key_props": {
            "exportable": true,
            "kty": "RSA",
            "key_size": 2048,
            "reuse_key": false
          },
          "secret_props": {
            "contentType": "application/x-pkcs12"
          },
          "x509_props": {
            "subject": "CN=xyz",
            "ekus": [],
            "key_usage": [
              "digitalSignature",
              "keyEncipherment"
            ],
            "validity_months": 12,
            "basic_constraints": {
              "ca": false
            }
          },
          "lifetime_actions": [
            {
              "trigger": {
                "lifetime_percentage": 80
              },
              "action": {
                "action_type": "AutoRenew"
              }
            }
          ],
          "issuer": {
            "name": "Self"
          },
          "attributes": {
            "enabled": true,
            "created": 1669069932,
            "updated": 1669070130
          }
        },
        "pending": {
          "id": "https://gearamakeyvault.vault.azure.net/certificates/CreateCertificateResumeToken/pending"
        }
      }
    }
  ],
  "Variables": {}
}

Look for KID, SID fields in the response for the response.

To repro Start test proxy, set sanitizers , run C++ test KeyVaultCertificateClientTest.CreateCertificateResumeToken look for th e gearama word

**Comment by scbedd** [comment]
@gearama how do I actually go about reproing this? I need a bit more detail then what you gave me.

**Comment by gearama** [comment]
repro https://github.com/gearama/azure-sdk-for-cpp/tree/main , checkout testProxy branch , build
run eng\common\TestResources\New-TestResources.cmd -ServiceDirectory keyvault -location westus3 
Either set the ENVs or create a .runsettings with the values spwed out 
Start TestProxy on https 5001 
record the test 
![image](https://user-images.githubusercontent.com/50641385/203181772-d139e070-3524-4bfb-84fb-e26b4f74cbbd.png)
 CreateCertificateResumeToken

**Comment by scbedd** [comment]
I debugged through this offline with @gearama . It ended up being an issue with the sanitizer configuration, as it wasn't accounting for `-` or digits in the name of the keyvault.
