### ISSUE TITLE
Ability for anyone to view all release plans for the service selected when accessing the release planner app 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4775]
The current Release Planner design only allows a user to view the release plans that they created or were shared with them.  If an engineering or PM lead at the service level wants to view all of the active product release plans for the service, then the release plan owner has to share the plan with them.  This is not only extra work but can cause confusion.  There is nothing in the current release planner app that states that you have to share the release plan for someone to view it. 

The default should be that all of the release plans are viewable for the service that was selected at login for the release planner.  
We should add an option - request access to edit.

**Comment by maririos** [comment]
This is going to be covered in part by https://github.com/Azure/azure-sdk-tools/issues/6237 and when there is filtering or a dashboard available
