### ISSUE TITLE
[Swift APIView] not picking up public api

### ISSUE THREAD

**Issue by jimchou-dev** [Azure/azure-sdk-tools#4777]
When specifying the source, it does not pick up all the files in the directory, it does not pick up `public class ChatAdapter` or anything in ChatAdapter.swift
`--source=/Users/jimchou/Downloads/communication-ui-library-ios/AzureCommunicationUI/sdk/AzureCommunicationUIChat`
But it works when specifying a more specific path
`--source=/Users/jimchou/Downloads/communication-ui-library-ios/AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources`

Repo: https://github.com/Azure/communication-ui-library-ios
Branch: `feature/chat`

FYI @tjprescott

**Comment by tjprescott** [comment]
Generally speaking, you should target the `/Sources` folder or it will parse all of your Swift test files as well.
