### ISSUE TITLE
[ApiView] Swagger not showing enum definitions

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-tools#4778]
See https://apiview.dev/Assemblies/Review/7c11c4c760344def8e4ce79217d2e805#-azureopenai-2022-12-01.swagger-Definitions-EntityErrorCode that renders like:
![image](https://user-images.githubusercontent.com/1179329/203417103-1bd61498-edbd-46f8-a077-d5e9f1e54f22.png)
even though the swagger is defined as:
```json
"EntityErrorCode": {
  "title": "EntityErrorCode",
  "description": "Entity error codes.",
  "enum": [
    "internalFailure",
    "jsonlValidationFailed",
    "fileImportFailed"
  ],
  "type": "string",
  "x-ms-enum": {
    "name": "EntityErrorCode",
    "modelAsString": true,
    "values": [
      {
        "value": "internalFailure",
        "description": "Internal error. Please retry."
      },
      {
        "value": "jsonlValidationFailed",
        "description": "Validation of jsonl data failed."
      },
      {
        "value": "fileImportFailed",
        "description": "Import of file failed."
      }
    ]
  }
},
```

**Comment by ruowan** [comment]
This issue has already been fixed in swaggerApiParser 1.0.3 version. @maririos maybe next ApiView release could use the lastest swaggerApiParser
