### ISSUE TITLE
[ApiView] Swagger not showing comment indicators in collapsed subsections`

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-tools#4779]
I have comments on https://apiview.dev/Assemblies/Review/7c11c4c760344def8e4ce79217d2e805#-azureopenai-2022-12-01.swagger-Paths-/deployments-0-operationId-Deployments_List but when collapsed it looks like:
![image](https://user-images.githubusercontent.com/1179329/203417516-9f3a0256-56de-4d4e-823f-cb5d88023745.png)

Ideally that would show the comment indicator like in the margin like:
![image](https://user-images.githubusercontent.com/1179329/203417568-b52d0aa4-c02d-402b-a0fc-c1516b1348a3.png)

**Comment by praveenkuttappan** [comment]
@chidozieononiwu Can you please link your PR that will resolve this to this issue?
