### ISSUE TITLE
REST API linter should not flag `format: unixtime` for `type: integer`

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4790]
The LintDiff PR pipeline step flags a property with `type: integer` and `format: unixtime` with the message:

> 'unixtime' is not a known format.

But `unixtime` is defined as an allowed format value for autorest:

https://github.com/Azure/autorest/blob/main/packages/libs/openapi/src/v3/formats.ts#L74

The linter rule should be updated to allow `unixtime` as a value format for integer properties / parameters.

**Comment by konrad-jamrozik** [comment]
@mikekistler looks like [this is done](https://github.com/Azure/azure-openapi-validator/pull/428), so closing this issue.
