### ISSUE TITLE
Adjust text for PR label in Scheduler App 

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#4791]
![Untitled picture](https://user-images.githubusercontent.com/9943211/203268742-340c3189-a020-4c40-9220-fbad0fbee8bf.png)
"API PR" and "Swagger PR" should be consistent and adjusted to "API Spec PR".

**Comment by maririos** [comment]
Fixed in Dev environment:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/9868623/203847615-2453558e-5053-4ac8-b6e4-74cb8d5f2815.png">
