### ISSUE TITLE
Refine integration between other Apps and Scheduler App

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#4792]
Right now, while an event is created by other Apps, such as SDK Release App, it needs to be filled in with a few columns: `Workflow`, `Service Profile`, `Product` to pass along the data into Scheduler App.
`Service Profile` and `Product` seems redundant with Workflow in place. `Workflow ID` is deprecated, should be removed.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/5196139/203684729-1faa8e6e-4cc2-4f4c-8bc7-a7bcfd35ab07.png">
<img width="755" alt="image" src="https://user-images.githubusercontent.com/5196139/203684812-59ae118c-0388-464c-b522-69bccfed1b6d.png">

With `Workflow` in `Event` table, here is the steps to retrieve corresponding data from `SDK Release Workflow`

- `Workflow` is a lookup column of table `Base Workflow` in table `SDK Release Workflow`, and it is unique for each SDK release workflow, we can query the record from `SDK Release Workflow` filtering on it. <br><img width="509" alt="image" src="https://user-images.githubusercontent.com/5196139/203704240-fd9a30e6-d27c-4830-a576-95c1bfc8a3fa.png">

- Once get the record of `SDK Release Workflow`, we can get the service from column `Service Profile` and product from column `Service Product` <br><img width="737" alt="image" src="https://user-images.githubusercontent.com/5196139/203703640-231d87d8-4c1e-4acb-a409-fd5c86f6a03b.png"><br>And also the `API Specs PR link` via column `Pull Request Url`<br>
<img width="468" alt="image" src="https://user-images.githubusercontent.com/5196139/204206208-a8b322fd-8c8f-4791-8069-782bd2e5eacb.png">

- If we want to get the ADO work item corresponding to the workflow, we can get it from table `Product Profile` using column `Work Item Id` <br><img width="504" alt="image" src="https://user-images.githubusercontent.com/5196139/203684577-a43d69dd-6add-41f0-8eb0-1bdacbed47dc.png">

**Comment by maririos** [comment]
@JonathanCrd  could you please look into this and tell us where we are and what we need to do to get to a better place?

**Comment by maririos** [comment]
@live1206 :

> `Workflow ID` is deprecated, should be removed.

It seems as the field is still tied to the `Workflow` table. Is it ok to remvoe that relationship so then we can remove this column from the `Event` table?

**Comment by maririos** [comment]
> @JonathanCrd could you please look into this and tell us where we are and what we need to do to get to a better place?

We would have to change our logic so when the app is called with the `event` parameter, we look into the `Workflow` column and follow the recommnedations from @live1206 on how to get the information for: `Service name`, `Product name`, `ADO number`, `API link`. 
I recommend not to populate the Event fields until the meeting is scheduled.

**Comment by live1206** [comment]
> @live1206 :
> 
> > `Workflow ID` is deprecated, should be removed.
> 
> It seems as the field is still tied to the `Workflow` table. Is it ok to remvoe that relationship so then we can remove this column from the `Event` table?

`Workflow` table is not in use anymore, feel free to remove any corresponding relationships.
It's hard to remove the table for now due to the existing relationships.

**Comment by maririos** [comment]
> Workflow is a lookup column of table Base Workflow in table SDK Release Workflow, and it is unique for each SDK release workflow, we can query the record from SDK Release Workflow filtering on it.

@live1206 could you give me an example with code on how from the `Event` table I can get the `Product` ?  I wasn't able to get past `event.Workflow` pointing to `Base Workflow` and not `SDK Release Workflow`

**Comment by maririos** [comment]
I tried using the workflow column but I can't get to load the properties of Service or Product withouth having to look into the table and doing a direct lookup there.

**Comment by zzvswxy** [comment]
Hi @maririos  can you try this code
`UpdateContext({baseWorkflowID: "mockID"});
UpdateContext(
    {
        myReleaseWorkflow: LookUp(
            'SDK Release Workflows',
            Workflow.Id = GUID(baseWorkflowID)
        )
    }
);
UpdateContext(
    {
        myProduct: myReleaseWorkflow.'Service Product',
        myService: myReleaseWorkflow.'Service Profile'
    }
)`
@live1206   Is the example looks good for you？

**Comment by live1206** [comment]
> Hi @maririos can you try this code `UpdateContext({baseWorkflowID: "mockID"}); UpdateContext( { myReleaseWorkflow: LookUp( 'SDK Release Workflows', Workflow.Id = GUID(baseWorkflowID) ) } ); UpdateContext( { myProduct: myReleaseWorkflow.'Service Product', myService: myReleaseWorkflow.'Service Profile' } )` @live1206 Is the example looks good for you？

Thanks @zzvswxy, this has been sorted out offline.

**Comment by JonathanCrd** [comment]
What is the purpose of the `Base Workflow` table?
I want to understand why we don't have a direct relationship between the `Base Workflow` and `SDK Release Workflow`, or even between `Event` and `SDK Release Workflow`.

**Comment by live1206** [comment]
The purpose of `Base Workflow` is to abstract the base functionalities of `Workflow`, such as `Workflow Status`, `Current Step` of the workflow. There might be multiple kinds of `Workflow` with the functionalities.
The same goes for `Base Step`, common properties like `Required` and `Step Status`.

The `Workflow` column in `SDK Release Workflow` is a lookup column to `Base Workflow`.

**Comment by maririos** [comment]
- [ ] Informational
- [ ] API 
- [ ] SDK
