### ISSUE TITLE
Support JPMS requires static for Java api review

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-tools#4795]
Related to https://github.com/javaparser/javaparser/issues/3769. When using `requires static some-org.some-module` in a `module-info.java`, we expect this `requires static` directive could be displayed in the API review. 

One example could be https://apiview.dev/Assemblies/Review/aa2cf725c3834cf38d4c2be30a1987b4#module-info. 

```java
 module com.azure.identity.providers {
     requires com.azure.identity;
     requires mysql.connector.j;
     requires org.postgresql.jdbc;
     requires transitive java.sql;

     exports com.azure.identity.providers.mysql;
     exports com.azure.identity.providers.postgresql;
}

```

But in the source code, the MySQL and PSQL modules are `requires static`. The source code can be found here https://github.com/Azure/azure-sdk-for-java/blob/346d3e8b86df67808c0362833280bf2067ab4716/sdk/jdbc/azure-identity-providers/src/main/java/module-info.java. 
```java
module com.azure.identity.providers {
    requires com.azure.identity;
    requires static mysql.connector.j;
    requires static org.postgresql.jdbc;
    requires transitive java.sql;

    exports com.azure.identity.providers.mysql;
    exports com.azure.identity.providers.postgresql;
}
```

**Comment by kurtzeborn** [comment]
Looks like a parser issue, so probably goes to someone on the Java team for follow up

**Comment by JonathanGiles** [comment]
@saragluna I'll assign this issue to you - for once you get the support into JavaParser :-)
