### ISSUE TITLE
Pipeline Generator: Live pipeline generation from tests.yml files

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#48]
- [x] Generate a new pipeline from each tests.yml file that points to that tests.yml file
- [ ] Command line parameter to apply variable group defined by identifier to build
- [ ] Scheduler which generates the kickoff schedule deterministically for every pipeline (i.e. schedule time is constant for a given pipeline name never changes)

**Comment by mitchdenny** [comment]
In the training material for partners I walk through using the single pipeline generator (including for ```tests.yml``` but I do say that the pipelines will be generated automatically within 24 hours. I know that the test pipelines, so it'll be good to get this automated. Is the hesitation to just running the pipeline generator over the whole repo the missing variable groups?

**Comment by mitchdenny** [comment]
Noticed that as I was looking at the configs last week. Now just to address the JS issue ...

**Comment by mitchdenny** [comment]
Closing this down since test pipeline generation is technically complete, its just generating once per package for JS. If when we consolidate the linked issue can be resolved too.
