### ISSUE TITLE
UKMet Supercomputer Service not found in Release Planner App drop-down menu 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4805]
The product UKMet Supercomputer is blocked from using the Release Planner app to onboard the new product.  The service does not show up in the drop-down menu.  This is a new service and new ARM namespace. The service does have an ARM namespace - microsoft.baremetal.  

Product - https://microsoftservicetree.com/products/1a8695e3-b068-4ffa-8f13-7a78e672db22

Service - https://microsoftservicetree.com/services/a44908d8-9c69-42ec-9cbb-f79103b3bb8f/metadata/ARMNamespace

**Comment by ladonnaq** [comment]
@live1206 Another new service cannot find their service in the drop-down menu.  They are blocked from onboarding with our team for APEX.

**Comment by maririos** [comment]
This might already be fixed but we need to wait for the deployment of the Scheduler App in order to bring all those services. We are working on a deployment today. I will update this issue here

**Comment by maririos** [comment]
@live1206 deployment is done. We should be good to bring back all services

**Comment by live1206** [comment]
Services added back, the above service is available now.
![image](https://user-images.githubusercontent.com/5196139/204757304-3a3d5896-e1e3-4dc0-8a5d-865285c09b9a.png)

**Comment by maririos** [comment]
Awesome! I confirm Scheduler tool fix works as expected and that we can also see the service in our end:

<img width="753" alt="image" src="https://user-images.githubusercontent.com/9868623/204827211-75444e01-d9b3-437f-ae12-d4f464e30650.png">
