### ISSUE TITLE
Avocado issues messages for missing readme in Cadl directories

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4806]
When Avocado runs on a PR that includes the Cadl API definition it issues "missing readme" messages for the Cadl directories.

An example is [PR 9634](https://github.com/Azure/azure-rest-api-specs-pr/pull/9634/checks?check_run_id=9748693363).

**Comment by raych1** [comment]
This issue was fixed in avocado. Only files underneath resource-manager and data-plane folders will be validated for this readme rule.
//CC: @tianxchen-ms

**Comment by tianxchen-ms** [comment]
It's a known issue. Only MISSING_README rule has this issue in pipeline. I'll fix it soon

**Comment by tianxchen-ms** [comment]
Fixed
