### ISSUE TITLE
Error when submit intake questionnarie

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4807]
I was trying the tool today and run into with every convination I tried:

<img width="942" alt="image" src="https://user-images.githubusercontent.com/9868623/204396231-85db9e4b-d9b2-4382-b1d5-ff6afc64753c.png">

**Comment by live1206** [comment]
@honghr Could you help take a look at this? We are hitting this error again in PPE

**Comment by live1206** [comment]
@maririos Fixed and deployed to Prod.

**Comment by maririos** [comment]
I was testing this in PPE. I confirm the error is gone and now I can submit the questionnary
