### ISSUE TITLE
Multiple products with the same name are shown in Informational meeting

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4808]
i.e.: 
<img width="426" alt="image" src="https://user-images.githubusercontent.com/9868623/204409110-5b8a9f7f-3d83-4ca6-aec7-48feaa428c41.png">

Why is this happening? is this expected? how to make it different?

**Comment by ladonnaq** [comment]
I am seeing the same thing. 



![Image](https://user-images.githubusercontent.com/67656762/204650606-c0831a7a-2f6a-4128-9c61-b9a177b6a61a.png)

**Comment by ladonnaq** [comment]
I am also not finding the product that I am looking for in the drop-down.  I am looking for a feature for the Backup offering.  It is not there, and the product is still active for APEX.  

Service tree link for product - https://microsoftservicetree.com/products/c36b07be-54d6-444d-8440-6b871045da54/overview

![Image](https://user-images.githubusercontent.com/67656762/204651333-4c53c8a6-dbd6-4554-8963-3ed17d3702a7.png)

**Comment by maririos** [comment]
@ladonnaq is this what you are expecting to see?

<img width="678" alt="image" src="https://user-images.githubusercontent.com/9868623/204867844-83dd97d4-e49d-4f44-bdd6-270bf537d8bc.png">

**Comment by maririos** [comment]
Fixed. 


![Image](https://user-images.githubusercontent.com/9868623/206321076-0825ffda-d459-48ea-acae-eb2bacd85940.png)
