### ISSUE TITLE
Cadl validation update

### ISSUE THREAD

**Issue by jianyexi** [Azure/azure-sdk-tools#4811]
Enhance the Cadl Shift-Left pipeline (in ADO)

~~1. For dataplane, skip the MissingExamplesDirectory check.~~

1. Enrich the documentation to describe more technical details.

2. Validate the new folder structure as defined [here](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/cadl-structure-guidelines.md)

3. Use the variables in the [comment below](https://github.com/Azure/azure-sdk-tools/issues/4811#issuecomment-1369577673) to locate the Cadl to be validated

**Comment by maririos** [comment]
@jianyexi when there is an error in a PR, is the link to the documentation shared? or how do people know to look [here](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/ci-fix.md#cadl-validation)?

**Comment by weshaggard** [comment]
We should also update the docs to tell folks what to do to fix an error. For example InConsistentSwagger the error says to regenerate but we should point to docs that tell folks how to do the generation. Similar for other errors we need to be explicit in what steps they need to take.

**Comment by raych1** [comment]
These're the variables used in API spec pipeline:
CadlDirForArm, CadlDirForDataplane, ServiceDirForArm, and ServiceDirForDataplane. 

In case of data plane single package, `$CadlDirForDataplane/$ServiceDirForDataplane` is the location of cadl directory;
in case of data plane multiple package, `$CadlDirForDataplane` sub folders will be scanned thru to look for the folders containing package.json;
in case of management plane single package, `$CadlDirForArm/$ServiceDirForArm` is the location of cadl directory;
in case of management plane multiple package, `$CadlDirForArm` sub folders will be scanned thru to look for the folders containing package.json.
