### ISSUE TITLE
Improve ServiceApiReadinessTest pipeline to support traffic validation based on test-proxy recording

### ISSUE THREAD

**Issue by leni-msft** [Azure/azure-sdk-tools#4816]
https://microsoftapc-my.sharepoint.com/:u:/g/personal/leni_microsoft_com/ESCWakp7UE9EtqrDOEnn5fcBT_tzrO1uOv2WtKkJgHESVA?e=nRXpgi

**Comment by tianxchen-ms** [comment]
https://github.com/test-repo-billy/azure-rest-api-specs/pull/2831
