### ISSUE TITLE
API View for C++ needs more agent storage space

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#4833]
API View for C++ requires LLVM, which consumes significant disk space during its build. 

We intend to use vcpkg caching to accomplish this by building the artifacts on an Azure DevOps agent and uploading those artifacts from the build agent to the cache. Subsequent runs of build agents should fetch LLVM at the pinned version from the cache and not require the build time. 

The build is estimated to require 250 GB of space and several hours to complete. Current VMs have only 100 GB of storage. The build fails when it runs out of disk space: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2019870&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=1bb4b58e-f076-55c3-0dfc-a70a7c67f4bb

The intend output is a Windows standalone executable meaning we'd want to build on a Windows agent. 

Avenues of exploration: 

* @LarryOsterman -- Can we build ONLY the release configuration on the agent? (I think this requires configurations on "enough" of the packages in vcpkg to work properly)
* @mikeharder -- Failing "release" only builds, can we get VMs with more disk space? Should this be a new pool or can we upgrade disk space on an existing pool?

**Comment by mikeharder** [comment]
It looks like the release-only build of LLVM fit onto the 150GB cache.

If you do need more disk space, you can add the `DiskSizeGiB` to your pipeline YML, which will attach an empty data disk as `F:\` (on Windows).  You can either set the working folder to this drive using the `WorkFolder` demand, or just manually set `VCPKG_ROOT` to use `F:\`.

**Comment by kurtzeborn** [comment]
Based on the discussion in standup last week, it sounds like this may have been sorted out.  Please close if that's the case.

**Comment by danieljurek** [comment]
This can be closed. Limiting the vcpkg build to _only_ build Release bits is sufficient and we don't require extra storage. We'll keep the `DiskSizeGiB` in mind if we run into something like this in the future and scoping the build is not feasible.
