### ISSUE TITLE
Add check for SDK generation in Sign off API Spec Readiness page

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#4838]
![image](https://user-images.githubusercontent.com/40835867/202999141-a4dc356d-8507-4a11-b887-187ca7f826c3.png)

If there is sdk generated failed, we need to add a label to indicate the failure can be ignroed. If the label doesn't exist, we should block customer from completing the task.

**Comment by honghr** [comment]
@josefree Do we need check this and block user complete this epic?

**Comment by maririos** [comment]
@ladonnaq because we are removing the view of Generating SDKs https://github.com/Azure/azure-sdk-tools/issues/5560 from the API Readiness app, is this issue still relevant?

**Comment by ladonnaq** [comment]
We can close this issue since we redesigned the API readiness app.
