### ISSUE TITLE
Stakeholder Feedback Sessions: Release Planner V2

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4841]
### **Stakeholder Feedback Plan for Release Planner Beta 2** 

1. [Stakeholder Release Planner V2 User Study Plan]( https://microsoft.sharepoint.com/:fl:/s/a8deefde-7c82-4dbf-98e1-5238b2c9e016/EQh8ZjlgMFBKgKE-o-0FphoB8x19OirRqzLrC04MHmAz5A?e=se05tm&nav=cz0lMkZzaXRlcyUyRmE4ZGVlZmRlLTdjODItNGRiZi05OGUxLTUyMzhiMmM5ZTAxNiZkPWIhLXhNU1pGQnBka3lvUkdNaG1nMV9odXNDMnJFUVNqZElqcGpPLWdYVG1vYUh1SVlIRWZDdFJaLWhMTVliZmhpaCZmPTAxQk9RNk4zSUlQUlREU1lCUUtCRklCSUo2VVBXUUxKUTImYz0lMkYmZmx1aWQ9MSZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUV0ZUUxVFdrWkNjR1JyZVc5U1IwMW9iV2N4WDJoMWMwTXlja1ZSVTJwa1NXcHdhazh0WjFoVWJXOWhTSFZKV1VoRlprTjBVbG90YUV4TldXSm1hR2xvZkRBeFFrOVJOazR6U2pkRVNWUkdORWROU2xoR1NFbFBTVkJFTkRKSlFqUkdObGMlM0QlMjIlMkMlMjJpJTIyJTNBJTIyOWQ4MzA5OTMtMTQ0Yi00MmM2LWE3MmItYzllNTEzZDNkYjAyJTIyJTdE)

Includes the following: 

- List participants and scheduled meeting dates
- Goals of the user study
- Hypotheses
- Scenarios and Participant tasks lists

2. [Notes & Observations from stakeholder feedback sessions](https://microsoft.sharepoint.com/:fl:/s/a8deefde-7c82-4dbf-98e1-5238b2c9e016/ET4hmEPwJ-JHv1jwLMgPh7cB6bBvqok2k6Ba4zxT9Ib5Tg?e=gGOtpn&nav=cz0lMkZzaXRlcyUyRmE4ZGVlZmRlLTdjODItNGRiZi05OGUxLTUyMzhiMmM5ZTAxNiZkPWIhLXhNU1pGQnBka3lvUkdNaG1nMV9odXNDMnJFUVNqZElqcGpPLWdYVG1vYUh1SVlIRWZDdFJaLWhMTVliZmhpaCZmPTAxQk9RNk4zSjZFR01FSDRCSDRKRDM2V0hRRlRFQTdCNVgmYz0lMkYmZmx1aWQ9MSZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUV0ZUUxVFdrWkNjR1JyZVc5U1IwMW9iV2N4WDJoMWMwTXlja1ZSVTJwa1NXcHdhazh0WjFoVWJXOWhTSFZKV1VoRlprTjBVbG90YUV4TldXSm1hR2xvZkRBeFFrOVJOazR6U2pkRVNWUkdORWROU2xoR1NFbFBTVkJFTkRKSlFqUkdObGMlM0QlMjIlMkMlMjJpJTIyJTNBJTIyZmIxZjZhZDAtYTI2YS00ODMxLWFiYTEtYzgyNTgyYjdlYmYzJTIyJTdE)

Related GitHub issue - https://github.com/Azure/azure-sdk-tools/issues/5041

**Comment by ladonnaq** [comment]
[UX Study Release Planner Beta 2 Plan]( https://microsoft.sharepoint.com/:fl:/s/a8deefde-7c82-4dbf-98e1-5238b2c9e016/EbbiZ4e5N05BhMFjkcJISYkBm9buDFO6X4emTWYKVTaR0Q?e=ao2Rev&nav=cz0lMkZzaXRlcyUyRmE4ZGVlZmRlLTdjODItNGRiZi05OGUxLTUyMzhiMmM5ZTAxNiZkPWIhLXhNU1pGQnBka3lvUkdNaG1nMV9odXNDMnJFUVNqZElqcGpPLWdYVG1vYUh1SVlIRWZDdFJaLWhMTVliZmhpaCZmPTAxQk9RNk4zTlc0SlRZUE9KWEpaQVlKUUxEU0hCRVFTTUomYz0lMkYmZmx1aWQ9MSZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUV0ZUUxVFdrWkNjR1JyZVc5U1IwMW9iV2N4WDJoMWMwTXlja1ZSVTJwa1NXcHdhazh0WjFoVWJXOWhTSFZKV1VoRlprTjBVbG90YUV4TldXSm1hR2xvZkRBeFFrOVJOazR6U2pkRVNWUkdORWROU2xoR1NFbFBTVkJFTkRKSlFqUkdObGMlM0QlMjIlMkMlMjJpJTIyJTNBJTIyMDc0MTIyNGItNTc0Yy00NjIzLThhYjEtYTExZWEyMjM1ZDk2JTIyJTdE)

**Comment by ladonnaq** [comment]
List of participants.  Will refresh when meetings are scheduled.  

![image](https://user-images.githubusercontent.com/67656762/205157822-0cf1a192-d086-4110-8cf1-2ec8d3539ead.png)

**Comment by maririos** [comment]
Could we include also for Cadl: Allen and Arun, and for Cadl->DPG: Laurent?

**Comment by lirenhe** [comment]
> Could we include also for Cadl: Allen and Arun, and for Cadl->DPG: Laurent?

Laurent told me many times that he wants to try it. :)

**Comment by ladonnaq** [comment]
> > Could we include also for Cadl: Allen and Arun, and for Cadl->DPG: Laurent?
> 
> Laurent told me many times that he wants to try it. :)

Yes I will add them to the participant list and setup time to meet with them next week.

**Comment by ladonnaq** [comment]
@maririos @lirenhe Allen, Arun, and Laurent have all received calendar invites to participate a feedback session for the release planner beta 2.  You can look at the release planner link for current participant list and the scheduled feedback sessions.  If the dates change, we will update the Loop doc.

**Comment by ladonnaq** [comment]
We have concluded stakeholder feedback sessions before the holidays.  We are working on documenting the feedback. Once done we will start opening GitHub issues to address the bugs, gaps, new requirements (epics), and revision of current epics. 

Due to scheduling conflict and the holidays, we did not get to meet with Mark and Arun.  We met with Mike but he did not have time to go through the tasks list.  So we will schedule feedback sessions with these stakeholders in January.

**Comment by maririos** [comment]
@ladonnaq do you think you could have a document/issue with tall he feedback (it can be a collection of GH issues) that we can share with the Engagement Experience team?

**Comment by ladonnaq** [comment]
We are using this GitHub issue to track overall Release Planner V2 Usability Plan/Status - https://github.com/Azure/azure-sdk-tools/issues/5041.

**Comment by ladonnaq** [comment]
We are going to separate the user studies between stakeholders and service partners.  This GitHub issues will be used to track initial stakeholder feedback sessions.

**Comment by ladonnaq** [comment]
We met with Mark and Mike on 01/11/2023.  We are still in process of identifying any new GitHub issues needed to address all of the feedback from stakeholder reviews.  We will begin scheduling the UX study with service partners.

**Comment by ladonnaq** [comment]
Link to the UX study results for stakeholder sessions - https://microsoft.sharepoint.com/:fl:/s/a8deefde-7c82-4dbf-98e1-5238b2c9e016/EUvyX8ZdNfNFrQKm8qiM2LABqazj4pzs7NvwP5KceysXuA?e=AlRDr0&nav=cz0lMkZzaXRlcyUyRmE4ZGVlZmRlLTdjODItNGRiZi05OGUxLTUyMzhiMmM5ZTAxNiZkPWIhLXhNU1pGQnBka3lvUkdNaG1nMV9odXNDMnJFUVNqZElqcGpPLWdYVG1vYUh1SVlIRWZDdFJaLWhMTVliZmhpaCZmPTAxQk9RNk4zS0w2SlA0TVhKVjZOQzIyQVZHNktVSVpXRlEmYz0lMkYmZmx1aWQ9MSZhPUxvb3BBcHAmcD0lNDBmbHVpZHglMkZsb29wLXBhZ2UtY29udGFpbmVyJng9JTdCJTIydyUyMiUzQSUyMlQwUlRVSHh0YVdOeWIzTnZablF1YzJoaGNtVndiMmx1ZEM1amIyMThZaUV0ZUUxVFdrWkNjR1JyZVc5U1IwMW9iV2N4WDJoMWMwTXlja1ZSVTJwa1NXcHdhazh0WjFoVWJXOWhTSFZKV1VoRlprTjBVbG90YUV4TldXSm1hR2xvZkRBeFFrOVJOazR6U2pkRVNWUkdORWROU2xoR1NFbFBTVkJFTkRKSlFqUkdObGMlM0QlMjIlMkMlMjJpJTIyJTNBJTIyMjMxZWQyNTEtMTliNi00YTg5LTkwMTUtMDlkOGNiNWFhYWI4JTIyJTdE   

Link to prioritized GitHub issues to address feedback - https://github.com/orgs/Azure/projects/318/views/24
