### ISSUE TITLE
New Cadl Docs page link added to release planner apps

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4843]
We should update our links to send users to the new Cadl GitHub.io page.  It provides a better docs user experience vs directing them to wiki pages, markdown files, etc.  We will still need to link to some information that is elsewhere, like the perquisites.  For example, [Enabling API Spec pipeline](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRyLqLSatF0RNqSnWnzd-MglUMlNSVzRMQ0ZFTEtXUDdMOU5PQlFOUDVTNS4u). 

https://microsoft.github.io/cadl/

**Comment by maririos** [comment]
This was done during the April release
