### ISSUE TITLE
New-TestResources.ps1 -TestApplicationId should not be required

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#485]
Some resources don't use SPs other than to provision (which logging in takes care of), so we should not require the TestApplication* parameters.

**Comment by heaths** [comment]
Thinking about this more, maybe they are since they pass through to set environment variables. We need to think end-to-end to be sure.

**Comment by weshaggard** [comment]
If if we do need these in some cases we should either take the SP directly and pull the values or even consider creating the SP on the behalf the users that need one.

**Comment by heaths** [comment]
Maybe, but this was optimized for CIs that have separate secret variables for tenant, client ID, and client secret. As long as we can log into with those values (should be able to - we are in the script) within the CI and pass the `$sp` returned variable, that should work.

**Comment by pakrym** [comment]
Automatic SP creation would make local developer scenarios so much better!

**Comment by heaths** [comment]
What role should they have in an organization by default? We document a default, but someone knowledgeable in a constrained subscription could figure out what they need. It's questions like that why we left it up to the user and would need to be solved before we start creating SPs on behalf of users.

**Comment by pakrym** [comment]
Owners of the test resource group, no organization wide permissions.

**Comment by weshaggard** [comment]
I'll take a look at this while looking at some other clean-up stuff.

**Comment by drwill-ms** [comment]
The Azure IoT SDK team asks for this feature. We need to be able to run this script for our own test environments, and we should be able to run it with our own credentials, rather than create an app Id that has access to our sub.

**Comment by heaths** [comment]
You can run without the `-ProvisionalApplicationId` already. There's two parameter sets. Run `help new-testresources.ps1 -syntax` to see both.

**Comment by drwill-ms** [comment]
Looks like if I do that, I can't specify my subscription Id?

**Comment by heaths** [comment]
Pass it when you log in with `Connect-AzAccount`. That will be the account that is used for provisioning if not otherwise passed to the script.

**Comment by drwill-ms** [comment]
That works, thanks. Super weird that in one case subscription Id is explicit, and in the other it is inferred.

**Comment by heaths** [comment]
It's only used for provisioning, and one parameter set is to provide parameters for provisioning instead of relying on the currently logged in user. We use the former parameter set for CIs.
