### ISSUE TITLE
Clean up the unused code

### ISSUE THREAD

**Issue by sima-zhu** [Azure/azure-sdk-tools#4851]
We merged the logic of code owner subscriber and notification configuration. The tool of GithubCodeOwnerSubscribers is no longer use since then. 

Specifically clean up the file: https://github.com/Azure/azure-sdk-tools/blob/main/tools/notification-configuration/github-codeowner-subscriber/Program.cs

**Comment by sima-zhu** [comment]
Identified another place to clean up.
https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Get-AADIdentityFromGithubUser.ps1

**Comment by sima-zhu** [comment]
@konrad-jamrozik Thanks for taking care of this issue! 👍

**Comment by konrad-jamrozik** [comment]
> @konrad-jamrozik Thanks for taking care of this issue! 👍

@sima-zhu Happy to help! :)
