### ISSUE TITLE
C++ APIView: Flag items in the `namespace _detail {`.  i.e. anything that isn't under `Azure::` but is within `_detail`

### ISSUE THREAD

**Issue by LarryOsterman** [Azure/azure-sdk-tools#4870]
We should flag items in the `namespcae _detail {`.  i.e. anything that isn't under `Azure::` but is within `_detail`

_Originally posted by @RickWinter in https://github.com/Azure/azure-sdk-tools/pull/4809#discussion_r1038627946_

**Comment by kurtzeborn** [comment]
@LarryOsterman, assigning this to you since I believe you're the one working on this.  If this was intended to go to one of the ApiView devs, please reassign.
