### ISSUE TITLE
The template for prepare-pipelines is broken by the move to ubuntu-22.04

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#4888]
Apparently, we do not declare an image to use for our prepare-pipeline template steps https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/pipelines/templates/steps/prepare-pipelines.yml which means it defaults to ubuntu-latest which recently moved from ubuntu-20.04 to ubuntu-22.04. This causes a break because our prepare-pipelines template depends on .NET 3.1 and ubuntu-22.04 no longer has that version of .NET on the image. 

See https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2034849&view=logs&j=6b902995-b73d-5f5c-66fd-a7f66c857d2c&t=a1c457be-0fbe-5525-b6b0-ac3cf58f8d6c
```
You must install or update .NET to run this application.

App: /home/vsts/work/1/pipeline-generator/pipeline-generator
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '3.1.0' (x64)
.NET location: /usr/share/dotnet

The following frameworks were found:
  6.0.11 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  7.0.0 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=ubuntu.22.04-x64
```

There are a few issues we should fix here:
1) We should update our template to be explicit about which OS we are using and pin to that, in this case ubuntu-22.04 should probably be the image.
    - #4967
2) We should update our tools to a later version of .NET, probably .NET 6.0 because .NET 3.1 is going out of support later this month.
    - #4934 
    - #4935

**Comment by konrad-jamrozik** [comment]
For reference: The image update of `ubuntu-latest` to Ubuntu 22.04 is mentioned in https://github.com/actions/runner-images/issues/6399. This issue is mentioned from [Ubuntu 20.04 software page](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md), in turn mentioned in [Microsoft-hosted agents doc](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software), in turn mentioned in ["pool" YAML schema definition doc](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/pool?view=azure-pipelines#examples-1).

**Comment by konrad-jamrozik** [comment]
Related work:
- #4934
- #4935
- #4967

**Comment by konrad-jamrozik** [comment]
> There are a few blocking issues with the .NET 7.0 toolset currently which is why I'm hesitant to move to that just yet. See [Azure/azure-sdk-for-net#32814](https://github.com/Azure/azure-sdk-for-net/pull/32814) for some of those details.

@weshaggard @benbp I am tempted to move us to .NET 7 now because the underlying problem is now fixed, per:
- https://github.com/microsoft/vstest/issues/4014#issuecomment-1349614380

**Comment by konrad-jamrozik** [comment]
> There are a few blocking issues with the .NET 7.0 toolset currently which is why I'm hesitant to move to that just yet. See [Azure/azure-sdk-for-net#32814](https://github.com/Azure/azure-sdk-for-net/pull/32814) for some of those details.

@weshaggard @benbp the underlying problem is now fixed, per:
- https://github.com/microsoft/vstest/issues/4014#issuecomment-1349614380

However, the [Ubuntu 22.04 image](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md#net-core-sdk) has `.NET 7.0.100` as of this writing, while `.NET 7.0.101` has the fix.

**Comment by konrad-jamrozik** [comment]
@weshaggard @benbp I moved bulk of our tools to `net6.0` in these PRs:

- #4915
- #4937
- #4916 
- #4984

But there are few cases left. I wanted to check with you how to proceed with them. Especially given some of these tools might be obsolete, so perhaps I shouldn't spend time figuring out how to update, and instead delete them.

### GHCreator

GHCreator uses [netcoreapp3.1](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github-labels/README.md). I believe I would have to update the target in [ghcreate repo](https://github.com/AlexGhiondea/ghcreate/blob/master/src/Creator.csproj#L5), then make the drop, and update [GHCreator config files in the tools repo](https://github.com/Azure/azure-sdk-tools/blob/main/tools/github-labels/ghcreator/GHCreator.runtimeconfig.json).

### perf-automation

perf-automation appears to use [netcoreapp3.1 for testing by default](https://github.com/Azure/azure-sdk-tools/blob/main/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml#L4).

### job-matrix

I see [a lot of references to old .NET SDKs](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/job-matrix/samples/matrix.json#L11) in the [job-matrix tool](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/job-matrix/README.md). Not sure if anything needs to change here - do we perhaps want to drop some old versions, and add newer ones. like `net6.0` ?

**Comment by benbp** [comment]
@mikeharder re: updating the perf-automation [test config](https://github.com/Azure/azure-sdk-tools/blob/main/tools/perf-automation/Azure.Sdk.Tools.PerfAutomation/tests.yml#L4)

@konrad-jamrozik re: matrix, it doesn't *need* to change as it's a sample, but it seems better to me to keep it up to date regardless.

**Comment by jsquire** [comment]
> using ghcreator? We are getting dinged for out of date NET versions, but obviously can't expect Alex to update his repo that we get the dlls from.

We can kill it.

_Context:_

We're currently only using it for label synchronization, which I need to rewrite to use the GH CLI at some point.   Killing off GH Creator will give me a forcing function to prioritize doing so.
