### ISSUE TITLE
Make the GH Project information configurable from the Admin App and integrate testing for DEV and PPE

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#4890]
This is a follow up of #3917

3 things to do here:

- [x] 1.  Right now the Project information is in the code itself, we should add new columns in the Evet Settings table to store the Project Org and Number.
    - [x] 1.1.- Then we need to add this as inputs in the Admin App
- [x] 2.  We cannot run integration tests for this flow in DEV and PPE until we have a GitHub project in the same user as the testing repos from the Bot Account.

**Comment by maririos** [comment]
@JonathanCrd is the idea to finish this in this release cycle?

What was the conclusion with the tests? How can we be confident that the feature fully works if we can't test it in Dev/PPE?

**Comment by JonathanCrd** [comment]
@maririos 
The information is now saved in `Event Settings` table. 2 new columns were added: `GitHub Project Number` and `GitHub Project Owner Type`.

We also have the testing project now, so we are ready to test this in DEV and PPE.

It should work for new issues as well as existing issues for follow-ups.

**Comment by JonathanCrd** [comment]
By the way, this flow will only be triggered if the GitHub Project information is saved in the Table. If any of those two new columns are blank, it will skip this new cloud flow.

**Comment by JonathanCrd** [comment]
Admin app has now the option to modify the Project Number and Owner type (Organization/User).
With this, the tasks on this issue have been addressed.
