### ISSUE TITLE
Test service and product for release planner app testing 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4903]
I have been working with the CLC team to figure out how we can get a test service and product for release planner testing.  The Service Tree, S360, and CLC engineering teams do not want any "fake" services or products in the production environments for any of the applications.  The testing environments could be suitable but there is not a process in place to support our request.  It was suggested that I reach out to service tree to see if they would support a "fake" service and product for testing in the service tree test environment.  If they do will support, then Cloud Lifecyle may be able to support creating a "fake" CLC record for the "fake" product in S360 Test environment.  

I was discussing this issue with @kyle-patterson and he mentioned that the Azure SDK team has 2 "services" that are used for testing.  If we could use these existing services, then I can ask the CLC team if they could create a "fake" CLC product in the S360 test environment that we could use to for testing the release planner app.

**Comment by maririos** [comment]
This has been completed with the addition of the `Release Planner Test Service`. 
Note: if we need to directly make changes in CLC then this test service won't work. We will look into it whenever it becomes an issue
