### ISSUE TITLE
Have a checkbox for when a Service doesn't have a product

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4906]
From @ladonnaq:
Have a checkbox that states "New service no product in service tree yet". There are services that come our way that do not have products identified yet. See example below.

This affects all of our apps so we need to implement the same logic.

**Comment by ladonnaq** [comment]
We can close this issue and track in the issue I opened that covers this scenario -  https://github.com/Azure/azure-sdk-tools/issues/4918
