### ISSUE TITLE
Change Product presentation and behavior

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4908]
Coming from issue in the Scheduler app: https://github.com/Azure/azure-sdk-tools/issues/4682:

- Remove the filter on `Target life cycle` from the Release Planner App
- View format for Products should be `<Product name> - <product type>`

CC: @ladonnaq

**Comment by live1206** [comment]
Deployed to PPE
<img width="838" alt="image" src="https://user-images.githubusercontent.com/5196139/207517893-4732ba2d-00f2-4382-b1ce-3a7876eb85fd.png">
