### ISSUE TITLE
Better to indicate what's next in the banner of "Complete Your Informational Meeting first!"

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#4913]
Better to indicate what's next in the banner.  In the following scenario.  Besides "Complete Your Informational Meeting first!", could there also be a link to the scheduling app and wording like "Proceed with the scheduling app. "

![image](https://user-images.githubusercontent.com/18413981/206364734-62374b1c-cbc0-4f4a-8a17-d9b4c0205b58.png)

**Comment by honghr** [comment]
I can add a scheduling app link in the banner but it will be a static link. User cannot click it because power apps not support hyperlink in this banner.

**Comment by ladonnaq** [comment]
We should have a pop-up that requires the user to schedule the information meeting before creating the release plan if the meeting is required and has not been scheduled.  There is a GitHub issue which explains what field is updated in the ADO work item to figure out if the meeting was required and scheduled. - https://github.com/Azure/azure-sdk-tools/issues/4681.  Also, the Release Planner V2 design and requirements document requested that the logic be added by the release planner to update the Info Meeting field to "required" during onboarding based on specific scenarios.  I noticed that this is not happening so I will open a GitHub issue for this work be done.

**Comment by ladonnaq** [comment]
Need to confirm new UI will handle this scenario better.  We don't want them to create a release plan until they have onboarded. https://github.com/Azure/azure-sdk-tools/issues/4800

**Comment by maririos** [comment]
This has been covered by the UX/UI design done with https://github.com/Azure/azure-sdk-tools/issues/5631
