### ISSUE TITLE
Existing work item of the selected product can be loaded earlier？

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#4914]
Currently there is a warning of an existing ADO work item of the selected product only after clicking "submit" button.  Wonder it could earlier, for example when select a product from drop down,

![image](https://user-images.githubusercontent.com/18413981/206367132-9f8fdf1a-d766-44b8-9ff2-234c6f9fe99e.png)

![image](https://user-images.githubusercontent.com/18413981/206366148-b85b04b0-9839-45f2-b98d-91b85acf4c64.png)

**Comment by live1206** [comment]
Duplicated with https://github.com/Azure/azure-sdk-tools/issues/4909
