### ISSUE TITLE
Scenario that block users from completing onboarding new product using release planner app 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4918]
- Scenario:  New service with a service tree ID but there is not a product entry in service tree or the initial offering. Only products are in scope for APEX.  
- Suggested resolution:  
- [ ] Checkbox to indicate if this a new service.  If they answer yes, then allow user to continue onboarding and create the Azure Devops work item.  Drop-down box would be empty as there is no product yet.  The user can answer the rest of the questions which helps to scope API/SDKs for the new service. 
- [ ] The name of the service should be in the work item Associated Service Name field 
- [ ] The service tree ID should be in the work item Associated Service ServiceTreeID
- [ ] Leave the product specific work item fields blank 
- [ ] Add service to the end of the title of the work item.  For example, SDK Intake - <ServiceName> + **Service** 
- [ ] When user submits the onboard form, pop-up the schedule information meeting (we would want to talk to all new services). 
- [ ] I will create a new email template to send for this scenario.

**Comment by live1206** [comment]
@ladonnaq After discussion with @honghr, I realized that we can't support this with the current design.
ADO work item and product are 1 to 1 mapping, if there is no product for the ADO work item, there is no way for us to store the ADO work item id in dataverse. We need to have another thought of how to support this scenario in release planner app.

**Comment by ladonnaq** [comment]
@live1206 We had another service blocked from onboarding because of this issue.  What is the timeline on resolving and deploying to production?  I unblocked them by looking at the metadata in service tree and asking the question we would ask in the onboard new product blade.  I will meet with them so that I can provide the information they need to get started on the API readiness for management plane.

**Comment by ladonnaq** [comment]
This GitHub issue is related (slightly different scenario) - https://github.com/Azure/azure-sdk-tools/issues/4264.

**Comment by live1206** [comment]
I had another thought on this.
Right now, we have one to one mapping between product and ADO work item. 
For this scenario, the service team only have the service set up, no product yet.
We would have to set up the ADO work item mapping with service instead, which requires minor extension with current design. No issue for this.
But once the service team have their product set up, how are we planning to migrate the ADO work item mapping from service to product afterwards?
cc @honghr

**Comment by live1206** [comment]
So, we are planning to add 2 new columns to `Service Profile`: `Is New Service` and `Work Item Id`.
If the user check `Is New Service` checkbox on the onboarding questionnaire page, we will create the ADO work item with blank product, and set the work item id to `Service Profile`.
Once the user has set up a product for the service, they can come back to the onboarding questionnaire, uncheck `Is New Service` and select the product and update the ADO work item if needed or leave the data as filled in last time. We can set `Work Item Id` from table `Service Profile` to table `Product Profile` as we are doing normally and set `Is New Service` to `False` for this service.
cc @honghr

**Comment by live1206** [comment]
> @live1206 We had another service blocked from onboarding because of this issue. What is the timeline on resolving and deploying to production? I unblocked them by looking at the metadata in service tree and asking the question we would ask in the onboard new product blade. I will meet with them so that I can provide the information they need to get started on the API readiness for management plane.

Let's aim for the implementation and deployment to PPE this week, and then @ladonnaq please help to verify things in PPE.
Once you think things are working as expected, I will deploy to Prod early next week and switch the preview app to online version at the same time.

**Comment by maririos** [comment]
> So, we are planning to add 2 new columns to `Service Profile`: `Missing Product` and `Work Item Id`. If the user check `Missing Product` checkbox on the onboarding questionnaire page, we will create the ADO work item with blank product, and set the work item id to `Service Profile`. Once the user has set up a product for the service, they can come back to the onboarding questionnaire, uncheck `Is New Service` and select the product and update the ADO work item if needed or leave the data as filled in last time. We can set `Work Item Id` from table `Service Profile` to table `Product Profile` as we are doing normally and set `Missing Product` to `False` for this service. cc @honghr

@ladonnaq @live1206  A couple of questions for this design:
- A service can have more than one product, and each product has it's own work item. how would you handle this scenario with the proposed design?
- Can a product belong to more than one service?
- A release plan is per Service, per product, and per target lifecycle? or release plan is per service per product. So a product under a specific service can have multiple Release plans? Does the workitem handle all the different release plans? or is it better to say that there is 1 work item id per release plan?

**Comment by live1206** [comment]
@ladonnaq Deployed to PPE

**Comment by ladonnaq** [comment]
Thanks @live1206!  I will try it out with one of the services that had issues onboarding. I will respond in the GitHub issues with status.

**Comment by live1206** [comment]
Thanks @ladonnaq, if things are working as expected, I will release latest beta v2 to Prod.
