### ISSUE TITLE
Naming approval support for management plane libraries in APIView

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4922]
As I understand there is support in APIView for approving namespaces for new client libraries but there is not support for approving namespaces for new management plane libraries.  
 
Naming approval for new management plane libraries is required.  Today the process is manual and is documented here for our service partners - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/821/Naming-for-new-initial-management-or-client-libraries-(new-SDKs). 

If there will be management libraries and client libraries, we should review and approve the namespaces at the same time so that we ensure consistency. 

@RickWinter agrees that this is needed for management plane.  There have been 2 recent mistakes for management plane, so this is a gap, and APIView needs to support this use case. 

@mikekistler Would you please provide status on what it would take to support management plane?

**Comment by maririos** [comment]
Related issue: https://github.com/Azure/azure-sdk-tools/issues/4601

**Comment by mikekistler** [comment]
@ladonnaq is this still something we want to do? or is the current process enough?

**Comment by ladonnaq** [comment]
> @ladonnaq is this still something we want to do? or is the current process enough?

We are using a manual process right now.  It would be good to revisit using APIView, etc.  I created this issue to revisit when we are implementing the new UI for the Power Apps -   https://github.com/Azure/azure-sdk-tools/issues/6431
