### ISSUE TITLE
Create API review for CADL from CADL pull request

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#4924]
Create API review automatically from PR for CADL changes.

Below are the steps to create API review for CADL.

1. Install CADL compiler and CADL APIreview parser

    npm install -g @cadl-lang/compiler@0.37.0
    npm install -g @azure-tools/[cadl-apiview@0.3.0](mailto:cadl-apiview@0.3.0)

2. Change working directory to CADL package root in specific folder as in below e.g. and run following commands to install dependencies and compile CADL
    For .g. https://github.com/Azure/azure-rest-api-specs/tree/feature/confidentialledger/cadl/specification/confidentialledger/ConfidentialLedger

    npm install
    cadl compile . --emit=@azure-tools/cadl-apiview

3. Step #2 should create a JSON file in output path within package root.
     ./ cadl-output/apiview.json

4. Rename apiview.json to <CADL package root>.json and publish it as artifact. In this case file should be renamed as ConfidentialLedger.json. [@Travis Prescott](mailto:trpresco@microsoft.com) Can Parser generate APIView file with a name matching package root path? APIView will show same name for all reviews without this naming change.

5. Send REST API to APIView to create API review using same REST API used for Swagger API review. Only difference is that there won’t be any baseline name parameter in request.

**Comment by ruowan** [comment]
There is a package.json inside the ConfidentialLedger cadl project.  The apiview version in [package.json](https://github.com/Azure/azure-rest-api-specs/blob/feature/confidentialledger/cadl/specification/confidentialledger/ConfidentialLedger/package.json) is 0.1.0.  Which version pipeline should use for generating cadl apiView.

**Comment by praveenkuttappan** [comment]
Version in the package.json

**Comment by ruowan** [comment]
Already deploy cadl apiview integration in prod spec pipeline. @praveenkuttappan Here is sample  PR https://github.com/Azure/azure-rest-api-specs/pull/22145
