### ISSUE TITLE
Add Product field into API Review meeting

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4926]
From issue: https://github.com/Azure/azure-sdk-tools/issues/3867 we want to remove the sub-service from API Review meeting and add Product field so the data is not entry by the user but instead from our records.
This will also help map the service to our internal data and flow information from one meeting to another.

Work to do: We need confirmation from API review meeting admin

**Comment by maririos** [comment]
Email sent to Mark and Mike to start the conversation

**Comment by maririos** [comment]
I pinged the thread again as I have gotten no response

**Comment by maririos** [comment]
No objection so far so we are going to go ahead and implement this change

**Comment by JonathanCrd** [comment]
One question:
For the event title, should it include only the name of the product or the whole display name we show the user? 

I mean: `[MyService - MyProduct]` or `[MyService - MyProduct - Offering]`
