### ISSUE TITLE
Remove/disallow the WaitForARMFeedback label when the BreakingChangeReviewRequired label is added

### ISSUE THREAD

**Issue by bdefoy** [Azure/azure-sdk-tools#4945]
1. When adding the BreakingChangeReviewRequired label, first check if the WaitForARMFeedback label is present. If so, remove it.

2. When adding the WaitForARMFeedback label, first check if the BreakingChangeReviewRequired label is present. If so, do not add the WaitForARMFeedback label.

ARM API reviewers do not review PRs with breaking changes until the breaking changes are fixed or approved, so the WaitForARMFeedback should not be on a PR while a breaking change review is required.

**Comment by ruowan** [comment]
Currently, our pipeline will not add WaitForARMFeedback and ARMReview label when there is breakingChangeReview label.  This function is already existed. Could you give me an PR example?

**Comment by rkmanda** [comment]
Was this a recent change?

**Comment by rkmanda** [comment]
Eg: https://github.com/Azure/azure-rest-api-specs/pull/21861

**Comment by ruowan** [comment]
It has been running for a time.  It's a bug in our pipeline, our pipeline don't take account the breakingChangeReviewRequired label which added bot. I will fix it and keep updated with you.

**Comment by ruowan** [comment]
I have fixed this issue and deployed it to prod pipeline. Pls monitor other PRs
