### ISSUE TITLE
Update typos in the Informational Meeting Template 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4948]
The information meeting template needs some grammar and typo errors corrected.  

See updates on the wiki page - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/773/Azure-SDK-Informational-Meeting

**Comment by ladonnaq** [comment]
@maririos I will let you know when I am done updating the wiki page.  Justin sent an email regarding some edits.  I will fix what he resolved and also review to see if anything else needs updated before engineering updates the template.

**Comment by maririos** [comment]
As part of this work, the `Example` link in the Prerequisites table for `Link Pull request` is actually pointing to the Core Concepts document. Do you have another link that we could use as example?

**Comment by ladonnaq** [comment]
@maririos  The following wiki pages are updated and you should be able to copy the info to the calendar body. 

https://aka.ms/azsdk/onboarding/informational
https://aka.ms/azsdk/onboarding/dpinfomeeting

**Comment by maririos** [comment]
> https://aka.ms/azsdk/onboarding/dpinfomeeting

Related to issue: https://github.com/Azure/azure-sdk-tools/issues/3788

**Comment by maririos** [comment]
Template updated in DEV

**Comment by maririos** [comment]
Tables that need to be updated:
- SDK Email: 
  - Row with Name: Informational Meeting Confirmation Email
- Reference Document:
  -  Add row: Rest API example
