### ISSUE TITLE
Service partner Release Planner user study Gallium 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#4957]
1. Identify Participants, 
2. Schedule Pilot onboarding meeting.  
3. User Study/Feedback sessions: 

- We can approach this similar to the stakeholder user studies.  We will meet with them and provide a task list for creating their release plan.  
- Schedule a follow-up meeting to API Readiness signoff and get feedback on their experience using the API Readiness application. Then have them proceed to SDK release readiness.   
- Schedule a follow-up meeting to validate SDK Release Readiness signoff and get feedback on their experience using the SDK rease application. 

4. We will store the participant list, participant task list, and feedback in our Loop workspace. I will share links when they are available.

**Comment by maririos** [comment]
I believe this already happened and we can close this issue, right @ladonnaq  ?

**Comment by ladonnaq** [comment]
@ccbarragan  What are your plans for user studies for the release planner with our service partners?   Do you want to wait for the new UI for the release planner and API readiness to be implemented?

**Comment by maririos** [comment]
Closing as the apps are now used by our users and there are no future plans to do user studies
