### ISSUE TITLE
[Cadl APIView] Move aliases to their own section

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#4977]
Currently aliases are mixed in with models, but you can also alias operations and template specializations, so it would be more appropriate for these to appear in their own section of the APIView document.

**Comment by lmazuel** [comment]
This is misleading to look at the APIView and have aliases under models, as those are not and will never end up as actual classes or construct (an alias is an anonymous construct, that happened to have a name for reference, but disapear at compile time).
