### ISSUE TITLE
Don't allow to create new meeting schedule if time slot is already in place

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#4981]
We shouldn't allow this:
<img width="752" alt="image" src="https://user-images.githubusercontent.com/9868623/207945584-b9977373-4fbe-4195-91e8-b438b460b20e.png">

**Comment by ladonnaq** [comment]
We need to keep this in mind when the new scheduler configuration is done.  We will address during follow-on release.

**Comment by maririos** [comment]
UI for this is gone
