### ISSUE TITLE
Find ways to link SDK libraries to the corresponding API spec version

### ISSUE THREAD

**Issue by lfraleigh** [Azure/azure-sdk-tools#4982]
We've gotten feedback from customers and service teams that it would be helpful to know which API spec version a particular SDK library was built from.  Places to include this could include (multiple are possible):

- Changelog
- In the CSV file so it can show up on aka.ms/azsdk/releases (this would also help us detect out of date SDKs in the inventory dashboard)
- Library README
- Others?

Ideally this is automated so there's no room for error / omission.

**Comment by kurtzeborn** [comment]
Everything being asked for here is covered in this original issue: https://github.com/Azure/azure-sdk/issues/1198

So, I'm closing this so we can track this work with one issue.  If you feel like anything's missing from that issue, please add a comment or update the description there.
