### ISSUE TITLE
Enable version-convention linter rule for control plane

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#4986]
ARM is adopting the data plane convention for the format of the api-version value -- it must be YYYY-MM-DD with a "-preview" suffix for preview versions, both private and public preview. The ARM docs were recently updated to remove other previously allowed suffixes:

https://msazure.visualstudio.com/DefaultCollection/One/_git/AzureUX-ARMWiki/pullrequest/7188429

Data plane already has a linter rule that checks for this, `VersionConvention`:

https://github.com/Azure/azure-openapi-validator/blob/main/docs/version-convention.md

This rule should now be enabled for control plane as well as data plane API specs.

**Comment by jianyexi** [comment]
This is done by https://github.com/Azure/azure-openapi-validator/blob/main/docs/api-version-pattern.md
