### ISSUE TITLE
Notification Configuration Tool

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#50]
To be notified of build breaks on scheduled builds a tool should configure existing systems: 

Use Azure DevOps API to: 
* Create teams to receive notifications (1 team per build pipeline)
* Create notification configurations for scheduled builds (1 notification entry per pipeline, linking to the team)

Other considerations:
* Populate teams with [code owners](https://help.github.com/en/articles/about-code-owners) information from GitHub (#52) -- Tracked separately. 
  (requires microsoft.com email address in profile) 
 
* Should manually added team members be removed? It is probably the case that they go in the CODEOWNERS file

**Comment by mikey119** [comment]
Does anyone know about sideloading a custom App in MS Teams?  we are experiencing issues with reaching the "bot" on the second request to it.  is there a way that I need to set it up on the other side of the AppStudio?
