### ISSUE TITLE
Create a cloud flow to create a placeholder meeting

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5017]
This is to create a placeholder meeting within a shared calendar when someone reschedules a meeting to different date.

**Input:**
CalendarName
Date
start time
End time
Notes(optional)
Participants
Subject

**Output**
Success or Failed status
If failed, cloud flow should send an email to Dev team.

**Comment by JonathanCrd** [comment]
I have created the cloud flow, but I haven't integrated it into the app.

The inputs are:

- Calendar Name
- Meeting Type
- Event Payload (see [this doc](https://docs.microsoft.com/en-us/graph/api/user-post-events?view=graph-rest-1.0&tabs=http#request-3) for the schema)
- Additional Notes

A couple of things to mention about this flow:

- It will add the reviewers as optional attendees, always. It won't require their reponsa back and the placeholder email will be sent as Low Priority
- If it fails, it will send to the App an `error` response. It will also send an email to us letting us know it failed.
- The placeholder subject and body contents are in the cloud itself.
