### ISSUE TITLE
Cloud flow to delete a place holder meeting

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5018]
Create new cloud flow to delete placeholder meeting when meeting slot is taken.

**Input**
Meeting ID.

**Output**
Success or failed status
If failed, send an alert to Dev team

**Comment by JonathanCrd** [comment]
I have created this cloud flow.
It recieves a Calendar Name an an Event ID. 
It also sends out an alert to the Dev team if it fails.

I wonder if we can pass that Event ID from the App. If we cannot, then we will need to find it using the weblink or other unique property.
