### ISSUE TITLE
Include APIView links in calendar invite template

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5021]
Currently they are only present in the GH issue. It will be good to add them to the calendar template too.
The problem we are facing for it is the formating of the html

**Comment by ladonnaq** [comment]
They should show in the calendar invite for API Review and SDK Review.

**Comment by JonathanCrd** [comment]
For this, we will have to generate a separate parameter value for the email template. Currently we are generating the links in Markdown format
```
[{Domain.name}]({link}),
```

and we would have to do something like this for the new parameter value:
```
<a href="{link}">{Domain.name}</a>,
```
