### ISSUE TITLE
Check Enforcer evaluate command is broken

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#5032]
See for example [here](https://github.com/Azure/azure-sdk-tools/pull/5031).

`/check-enforcer evaluate` tells check enforcer to determine if a PR is passing by calling the [check-suites api](https://docs.github.com/en/rest/checks/suites?apiVersion=2022-11-28#list-check-suites-for-a-git-reference) for the PR's latest commit. This API is now returning an empty state, either by returning 0 check-suites [for example](https://api.github.com/repos/benbp/azure-sdk-tools/commits/e2cc944026973ba20750b6d269d75ceba9345255/check-suites) or by returning a queued check suite with 0 `latest_check_runs_count`.

I'm not entirely sure yet if this is related to a functional change we made to check enforcer, or a change made on the github API side that we need to handle.

**Comment by kurtzeborn** [comment]
Ben says this is done already!
