### ISSUE TITLE
Refactor repo root dir layout

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#5056]
Per following @weshaggard's comments:

- https://github.com/Azure/azure-sdk-tools/pull/5044#discussion_r1061908902
- https://github.com/Azure/azure-sdk-tools/pull/5044#discussion_r1061909338
- https://github.com/Azure/azure-sdk-tools/pull/5044#discussion_r1061909589
- https://github.com/Azure/azure-sdk-tools/pull/5044#discussion_r1061909921

we should restructure our repo directory layout. Namely, we should:

- Move `/.azure-pipelines/` under `/eng/pipelines/`
- Move `/config/` under `/eng/`
- Move `/scripts/` under `/eng/`
- Move `/src/` and `/web/` under appropriate subdirs of `/tools/`

**Comment by konrad-jamrozik** [comment]
@weshaggard I have few question about files under `/.azure-pipelines/`. There are pipelines defined over the `.yml` files in that dir:

| .yml | pipeline |
|-|-|
`.azure-pipelines/apiview-sync-staging.yml` | [APIView Sync Production to Staging](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=2002)
`.azure-pipelines/apiview.yml` | [APIView - Deploy - Staging](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=1960)
`.azure-pipelines/apiview.yml` | [APIView](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=1136)
`.azure-pipelines/warden.yml` | [azure-sdk-tools - warden](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=106)

My questions:

- is there an easy, reliable way for me to ensure the list above is exhaustive? I am fairly sure I should be able to find relevant ADO API call to return me json with all the pipelines and so search for given `.yml`, (I mean, our `notification-configuration` does something similar) but I was just wondering if we already have some automation for that.
- how these pipelines came to be? Our `pipeline-generator` and `prepare-pipelines.yml` seems to create only pipelines that match inheritors of [`PipelineConvention`](https://github.com/Azure/azure-sdk-tools/blob/4f6a9fde9061c462dc026b9c790198053d65d322/tools/pipeline-generator/Azure.Sdk.Tools.PipelineGenerator/Conventions/PipelineConvention.cs), but these pipelines do not seem to match any convention? Have they been created by hand?
- Is this a mistake there are two pipelines based off `.azure-pipelines/apiview.yml` ? I compared them and I don't see any meaningful difference. Stages, params, vars, they all seem semantically equivalent.
- I am thinking about doing simple migration as follows: move these build definitions `.yml` files to `/eng/pipelines`, and as soon as I merge the PR, go to all these pipelines and point them to the new `.yml` file locations. This means they will be down for few seconds, but I suppose this is not a problem. Does that sound good?

**Comment by weshaggard** [comment]
1) See https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-devops we dump the definitions there from time to time and you could grep over them there and even refresh if you need to.
2) These pipelines and most of them in the tools repo was created manually as the don't follow the patterns of the mono repos. 
3) No we often will configure different pipelines by share the same yml. Usually in these cases there will be variables or branches or such created for the different pipelines.
4) Yes I'm good with migrating these but lets please make sure the apiview team is aware of it.

**Comment by konrad-jamrozik** [comment]
@praveenkuttappan @tjprescott @chidozieononiwu per [this comment above](https://github.com/Azure/azure-sdk-tools/issues/5056#issuecomment-1401450848), I am going to move the source `.yml` files for the listed API view pipelines.

These pipelines may be broken for few minutes max as I do that.

Can you confirm this works with you?

Also: can you tell me why we need both [APIView - Deploy - Staging](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=1960) and [APIView](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=1136) ? They use the same build definition and upon inspection, I was unable to determine what is the difference between these two.

**Comment by praveenkuttappan** [comment]
> @praveenkuttappan @tjprescott @chidozieononiwu per [this comment above](https://github.com/Azure/azure-sdk-tools/issues/5056#issuecomment-1401450848), I am going to move the source `.yml` files for the listed API view pipelines.
> 
> These pipelines may be broken for few minutes max as I do that.
> 
> Can you confirm this works with you?
> 
> Also: can you tell me why we need both [APIView - Deploy - Staging](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=1960) and [APIView](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=1136) ? They use the same build definition and upon inspection, I was unable to determine what is the difference between these two.

I had this in my TODO list to move them to APIView directory. We needed two pipelines to keep production deployment and dev/preprod deployment builds completely separated and releases to those environments are based on these pipelines accordingly. We can deploy all environments from same pipeline but then this can be more problematic to error prone to accidentally deploy from a wrong pipeline run to production slot.

**Comment by praveenkuttappan** [comment]
@konrad-jamrozik It's totally fine to move the pipeline yaml. I can submit a PR since I need to make trigger change as well.

**Comment by praveenkuttappan** [comment]
@konrad-jamrozik I have submitted PR https://github.com/Azure/azure-sdk-tools/pull/5244 to move pipeline YAMLs

**Comment by konrad-jamrozik** [comment]
@weshaggard @praveenkuttappan regarding [`/src/`](https://github.com/Azure/azure-sdk-tools/tree/main/src), appears to me everything under there is `APIView`.

Should we thus make a move like `/src/` -> `/tools/APIView/` ?

I am also curious: what dependencies `APIView` has on the rest of the repository? In other words, what would break if we would move `APIView` into its own repo?

**Comment by weshaggard** [comment]
Yes I would like to eventually move everything under src to somewhere under tools. While some of these things aren't stand alone tools they still fit in the general "tools" category and as such I would like them moved under the tools directory. 

tools/apiview - Please work with @praveenkuttappan and @maririos with this move to try and minimize disruption. 
tools/dotnet-analyzers - This is the .NET tools analyzer
tools/dotnet-mgmt-tools - This is an old set of tools that is still used for the track 1 mgmt package build. It isn't updated much currently but I don't think we can remove it fully yet.

**Comment by konrad-jamrozik** [comment]
I have created an issue to track the move of `/src/`:

- https://github.com/Azure/azure-sdk-tools/issues/5641

I have completed all the other moves, so closing this work item.
