### ISSUE TITLE
[Python APIView] non-Optional kwargs shown as Optional

### ISSUE THREAD

**Issue by swathipil** [Azure/azure-sdk-tools#5064]
Seeing an issue in the Python EventHubs APIView where the [ `uamqp_transport` keyword marked as a bool in the docstring](https://github.com/Azure/azure-sdk-for-python/blob/d111b555383db6401bff31756f780be6b606df22/sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py#L129) but is being [detected in APIView as `Optional[bool]`](https://apiview.dev/Assemblies/Review/3e49ce1ca870470289360023dcb51edf?diffRevisionId=5de3eee880994ce4ba7d0773dfd42f56&diffOnly=False&revisionId=881593edfe0d4d40b7ade2688c63baad&doc=False#f7fa77033aac4d29a54b5a0caa5652a4). (The `uamqp_transport` kwarg is only documented in the docstring, and it's not included as an kwarg in the method signature.)

Seems that this only happens when the type is included after `keyword` but not when it's specified under paramtype.
(ex.
```
# marked as Optional[bool]
:keyword bool uamqp_transport: ...

# marked as bool
:keyword uamqp_transport: ...
:paramtype uamqp_transport: bool

```
)

Definitely not a high priority issue since we're switching to typed keyword only args in the method signatures anyway.

**Comment by tjprescott** [comment]
Hi @swathipil do you have the link to the actual code (or repro the code here)? Generally speaking, I think APIView treats all keyword-only arguments as optional.

**Comment by swathipil** [comment]
@tjprescott - yep! here is the link to the code: https://github.com/Azure/azure-sdk-for-python/blob/d111b555383db6401bff31756f780be6b606df22/sdk/eventhub/azure-eventhub/azure/eventhub/_consumer_client.py#L129

In general, it seems to only add Optional if the type is specified right after `:keyword` in the docstring. This doesn't happen if the type is below in a separate `:paramtype` line.

**Comment by tjprescott** [comment]
Thanks, and another important question--is it actually optional?

**Comment by swathipil** [comment]
It is not, it can only be True/False.

**Comment by tjprescott** [comment]
So they have to supply that keyword-only argument or the call fails?

**Comment by swathipil** [comment]
No, by default it's set to False.

**Comment by tjprescott** [comment]
This is a limitation of the docstring parser, which only exists because of Python 2.  See: https://github.com/Azure/azure-sdk-tools/blob/main/packages/python-packages/api-stub-generator/apistub/nodes/_docstring_parser.py#L123

As we have ditched Python 2, the right answer here is to move to using Python 3 typehints:
```python
def __init__(
        self,
        fully_qualified_namespace: str,
        eventhub_name: str,
        consumer_group: str,
        credential: CredentialTypes,
        *,
        uamqp_transport: bool = False
    ):
```
This is confirmed to display correctly in APIView.
