### ISSUE TITLE
Network error unable to retrieve product list for new service 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5065]
Hello team,  I was working with a new service to help them onboard with the Release Planner application.  Both of us are getting this error when we attempt to access the onboard blade.  I also posted in the engagement teams channel where I noted the name of the service. 

![image](https://user-images.githubusercontent.com/67656762/210871729-2353b769-1b2a-4287-a980-65920c52d661.png)

 
btw - Does anyone know if I open the GitHub issue in a private repo and then add to the engagement project is it safe to information that only should be in the private repo?  I ask because when bugs are they be from service partners who are working on new services or products (which they want to keep the name and details private).

**Comment by live1206** [comment]
Prod version has switched from beta 1 to beta 2, this issue should be gone now.
