### ISSUE TITLE
Enable service team to contribute tests/samples for other SDKs in mgmt SDK apps

### ISSUE THREAD

**Issue by lirenhe** [Azure/azure-sdk-tools#5070]
In current design, it seems service team only need to provide the tests & samples for dotnet.
I think we should encourage service team to add tests/samples for all SDKs though this is not required.
![image](https://user-images.githubusercontent.com/9100546/210913656-ef297ef6-d4ce-4fa5-9e2c-ccf5dcae7e64.png)

**Comment by dw511214992** [comment]
@lirenhe Has this requirement confirmed with sdk owners? Currently, service team doesn't need to provide the test/samples for mgmt sdk (except dotnet).

**Comment by lirenhe** [comment]
This is suggested not required for service team and we need to notify them for this step.

**Comment by maririos** [comment]
Notification about the step has been added in the SDK Release apps
