### ISSUE TITLE
There is no SDK auto generation for JS, Java, Python and Go in mgmt. SDK apps

### ISSUE THREAD

**Issue by lirenhe** [Azure/azure-sdk-tools#5071]
I believe most of the SDK could achieve auto generation of the SDK  and we already achieved that for DPG so I don't think moving to powerApps, SDK owners still need to generate the SDK PR manually themselves.

Expected:  All SDK should be auto generated for JS, Java, Python and Go (probably Java has some challenges.), SDK owners and service team just need to verify the generated code.

**Comment by lirenhe** [comment]
Cadl + DPG flow would auto generate the initial version of the SDK and ask service team to add test & samples.

Seems current design is to use a different flow for mgmt. SDK in PowerApps.

**Comment by dw511214992** [comment]
Current design of mgmt powerapps keeps the original way of working. (For js, java, go and python, sdk owners generate sdk pr by themselves.)
I think we can have a discussion about it, and collect feedbacks from sdk owners and service team (if possible), then decide whether we need to make it consistent with CADL+DPG flow to generate codes automatically.
cc: @josefree

**Comment by ladonnaq** [comment]
When we start onboarding service partner to use for management plane, I will get user feedback.  The topic came up in the user studies with stakeholders for Cadl + DPG.

**Comment by maririos** [comment]
@dw511214992 @lirenhe do you know what is the reason behind this discrepancy? From a tooling perspective, what will be the implications if we automate this step to provide same experience as in data plane?

**Comment by lirenhe** [comment]
> @dw511214992 @lirenhe do you know what is the reason behind this discrepancy? From a tooling perspective, what will be the implications if we automate this step to provide same experience as in data plane?

Currently, Azure SDK team is the owner of the mgmt. SDK release while for DPG, service team are the owner of their SDK release.  In tooling, we should provide better automation for mgmt. SDK release, including auto gen, auto testing & release.

**Comment by maririos** [comment]
We have removed all automation from the SDK apps, so this issue is no longer valid.
