### ISSUE TITLE
Exported methods of unexported types appear in API review

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-tools#5075]
For example, [btpError](https://github.com/Azure/azure-sdk-for-go/blob/3a7a4f3e6a5e676a2da09147753394b6c44e2d3c/sdk/azcore/runtime/policy_bearer_token.go#L110) isn't exported but has an exported method, `NonRetriable`. The method appears as public surface in the API review while the type does not:

![Screenshot_20230106_101811](https://user-images.githubusercontent.com/10964656/211073848-70fc5aa0-8562-4b7f-8b0b-3c86d8cca1a0.png)
([source](https://apiview.dev/Assemblies/Review/61b05e90153942f68f3276de824c34e2/79006651a4844ca092d9372292f649d5?diffRevisionId=c810db7674b74e6fbd4ba18f245b3e16&doc=False&diffOnly=True))

**Comment by mikekistler** [comment]
This needs a fix in the Go parser.

**Comment by chlowell** [comment]
On further thought, we want this behavior because such methods are publicly accessible via interfaces and regardless of whether we therefore consider them public, they're salient in API reviews. For example, this behavior of apiviewgo shows reviewers whether a type implements `error` and whether azcore's retry policy should consider an error non-retriable.
