### ISSUE TITLE
Service not showing up in drop-down box when accessing Release Planner app

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5081]
Service is not showing up in the drop-down menu.  Since this is a new service, please see email that has been forwarded, message in engagement teams channel, and access service tree link for additional details.  

- Top level service for the products - https://microsoftservicetree.com/services/ae53b53f-9347-4198-b9b7-ff4b8228d6a7
- All of the products dated for 2023 are in scope for APEX.

**Comment by live1206** [comment]
Replied in teams.
