### ISSUE TITLE
[SDK Review] Help the user decide what's the correct repo to choose

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#5115]
_This is feedback we got from the SDK Archboard._

For the users, it could be confusing which repo to select for the GitHub tracking issue for their review. The archboard is worried about partnert teams selecting the wrong repo and exposing private releases to the public. What's the best way to avoid this?

Some ideas were shared, like adding a lable or a message. I also think we could do it differently, like asking questions to define what's the right repo to use (similar to the Release Planner app onboarding questionary).

**Comment by ladonnaq** [comment]
For now, implement change similar to what is done in API Review meeting.

**Comment by JonathanCrd** [comment]
Changes done. Now, instead of asking which repo, it asks if the service is on pre-release or if it is not public yet.
Then, a label appears telling the user in which repo the tracking issue is going to be

**Comment by maririos** [comment]
Could you add a screenshot of how it looks now?

**Comment by JonathanCrd** [comment]
![Image](https://user-images.githubusercontent.com/17486462/215916231-657f6cf0-4ed8-4eca-8b89-d791f96fbe55.png)
