### ISSUE TITLE
[SDK Review] The Archboard DL must not be deleted from any meeting

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#5116]
_Feedback from the SDK Review Archboard_

When editting a meeting, users can delete the invitees, and the archboard is one of those.

What happens if a user or admin removes the Archboard DL from the invitees list?
We must make sure that the user cannot remove the archboard from the event.

**Comment by ladonnaq** [comment]
We need to test this and verify that this cannot happen.

**Comment by JonathanCrd** [comment]
Tested in SDK Review Scheduler app.
Even if the reviewers are removed when updating a meeting, they will be added back automatically when sending the calendar invite.

Closing this issue since there is not problem to fix.
