### ISSUE TITLE
APIView - add support for indicating API deprecation

### ISSUE THREAD

**Issue by JonathanGiles** [Azure/azure-sdk-tools#512]
We now are seeing some API deprecated in some client libraries. Having a means to indicate that an API was deprecated, and indicating this visually (e.g. with strikethrough or similar) would be very useful.

Assigning to @pakrym for review and further discussion on how this may be best implemented.

**Comment by praveenkuttappan** [comment]
I assume we can close this one. right?
@pakrym @JonathanGiles

**Comment by JonathanGiles** [comment]
Yep, it's supported in Java now.
