### ISSUE TITLE
SDK Release Readiness signoff for data plane 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5126]
The SDK Release Readiness application signoff screen needs UI and functional enhancements. 

1. Ensure that the SDK release readiness is validated and submitted for APEX signoff.  

- This GitHub issue - https://github.com/Azure/azure-sdk-tools/issues/5087 covers the following: 

- [x] SDK Breaking changes are reviewed and approved. (Public Preview and GA) Eng:(only for management)
- [x] For new services, package name/namespace are approved by archboard. (Public Preview) 
- [ ] For new services, we should release beta first (Product Public Preview) and then release stable SDK either at GA or minimum of one month after Public Preview (Stable releases required Arch Board approval). 

- In addition to the above, the following should be validated. 

- [ ] The Cadl pull request (PR) that will be used to generate the APIViews and SDKs has the label "APIStewardshipBoard-SignedOff".  We need to ask the APIStewardship Board if there new or additional PRs after sign-off, does this trigger a follow-up API Review?  There can be additional Cadl/OpenAPI doc PRs during SDK release readiness app. 
- [x] Testing and samples meet quality for Java, JavaScript, Phyton, and .NET (data plane) https://github.com/Azure/azure-sdk-tools/issues/4595

2. The current UI does not provide status related to the requirements that must be completed and validated prior to releasing the SDKs for APEX signoff.  

- [x] I would like the sign-off pages to have the similar UI - GitHub issue for tracking API readiness sign-off screen - https://github.com/Azure/azure-sdk-tools/issues/4905

**_@ccbarragan - Do you have any thoughts on how we could re-design the APEX API Readiness and SDK Release Readiness screens (step)?_**  

Here is the info to be validated.  I indicated in the picture what would be for new Beta vs new Stable SDKs.

**Comment by zzvswxy** [comment]
`The Cadl pull request (PR) that will be used to generate the APIViews and SDKs has the label "APIStewardshipBoard-SignedOff"`
Hi @ladonnaq , Data Plane SDK Release App check the Cadl PR in Step0. Prerequisite Checks, required the RP are merged or have the label "APIStewardshipBoard-SignedOff"

**Comment by ladonnaq** [comment]
> `The Cadl pull request (PR) that will be used to generate the APIViews and SDKs has the label "APIStewardshipBoard-SignedOff"` Hi @ladonnaq , Data Plane SDK Release App check the Cadl PR in Step0. Prerequisite Checks, required the RP are merged or have the label "APIStewardshipBoard-SignedOff"

Thanks for the additional details.  We still have few things to address.  

1.  We should not assume that the PR that was associated during data plane API readiness (the other app), is the PR that the service partner want to use to generate the SDKs.  

- Additional PRs could be opened for Cadl/OpenAPI doc after the initial API Review.  For example, the Arch Board request changes. I do not know if these PRs initiate a follow-up API Review (electronic, meeting) with the APIStewardship Board.  We need input from the API Stewardship Board to determine what we should do. 

- [ ] I will follow-up with Mark and Mike to get their input.

**Comment by ladonnaq** [comment]
@kyle-patterson @ronniegeraghty @lmazuel  I want to confirm the requirements for APEX signoff for Beta SDK Release Readiness (this would be for a new initial preview API version that will be used to generate the new initial Beta client libraries).  Here is screenshot (this is not the UI just a way for me to show what I am thinking).    
My questions are: 

1. Does the "Grow Up Development and Add Tests and Samples For CADL DPG" have to be completed or in process before initial Beta SDK is released?  What about new beta SDK versions?  new initial stable SDKs?  new stable SDK versions?  
2. Any ideas how we can validate that the service teams completed "Grow Up Development and Add Tests and Samples For CADL DPG" steps?  
3. Naming is the only arch board requirement that I believe is needed for a service team to release a new initial beta SDKs - is that correct?  
4. SDK breaking changes would not be required a new initial beta SDK.  For new SDK versions, is there going to be a breaking change review board and approval process?  Just curious - this is what is done for ARM (management plane).  

![image](https://user-images.githubusercontent.com/67656762/212981559-93577aba-9a34-4b01-89a4-7e79ab92ec21.png)

**Comment by josefree** [comment]
>  The Cadl pull request (PR) that will be used to generate the APIViews and SDKs has the label "APIStewardshipBoard-SignedOff". We need to ask the APIStewardship Board if there new or additional PRs after sign-off, does this trigger a follow-up API Review? There can be additional Cadl/OpenAPI doc PRs during SDK release readiness app.

@ladonnaq this definitely does not support. DPG does not support to generate SDK upon multiple spec PRs either.  If API stewardship Board requires further updates to the spec.  The team should reopen the PR and commit new updates in the same PR.  PR pipeline will automatically takes off the label "APIStewardshipBoard-SignedOff" with new commits in.

**Comment by josefree** [comment]
> Testing and samples meet quality for Java, JavaScript, Phyton, and .NET (data plane) https://github.com/Azure/azure-sdk-tools/issues/4595

I had a discussion with Renhe's team.  Engineers have agreed to define the quality criteria an check if the criteria is met or not before SDK release. Details should be tracked in this issue https://github.com/Azure/azure-sdk-tools/issues/4595

**Comment by maririos** [comment]
> > The Cadl pull request (PR) that will be used to generate the APIViews and SDKs has the label "APIStewardshipBoard-SignedOff". We need to ask the APIStewardship Board if there new or additional PRs after sign-off, does this trigger a follow-up API Review? There can be additional Cadl/OpenAPI doc PRs during SDK release readiness app.
> 
> @ladonnaq this definitely does not support. DPG does not support to generate SDK upon multiple spec PRs either. If API stewardship Board requires further updates to the spec. The team should reopen the PR and commit new updates in the same PR. PR pipeline will automatically takes off the label "APIStewardshipBoard-SignedOff" with new commits in.

The point here is that before we generate the SDKs, we show the PR where the API Spec is. We should allow the PR to be changed/updated. @ladonnaq is there an issue for that?

I agree with @josefree that once the SDKs have been generated and PRs to each individual repo have been created, we shouldn't be able to run the generation step again. @zzvswxy is this true in the tool? will the step sget blocked for the user so they can't generate the SDKs again?

**Comment by dw511214992** [comment]
> > > The Cadl pull request (PR) that will be used to generate the APIViews and SDKs has the label "APIStewardshipBoard-SignedOff". We need to ask the APIStewardship Board if there new or additional PRs after sign-off, does this trigger a follow-up API Review? There can be additional Cadl/OpenAPI doc PRs during SDK release readiness app.
> > 
> > 
> > @ladonnaq this definitely does not support. DPG does not support to generate SDK upon multiple spec PRs either. If API stewardship Board requires further updates to the spec. The team should reopen the PR and commit new updates in the same PR. PR pipeline will automatically takes off the label "APIStewardshipBoard-SignedOff" with new commits in.
> 
> The point here is that before we generate the SDKs, we show the PR where the API Spec is. We should allow the PR to be changed/updated. @ladonnaq is there an issue for that?
> 
> I agree with @josefree that once the SDKs have been generated and PRs to each individual repo have been created, we shouldn't be able to run the generation step again. @zzvswxy is this true in the tool? will the step sget blocked for the user so they can't generate the SDKs again?

@maririos  user cannot generate the sdks again.

**Comment by zzvswxy** [comment]
> will the step sget blocked for the user so they can't generate the SDKs again?

Sorry for missing the question. User can generate & regenerate SDK in Create SDK Pull Request step
![image](https://user-images.githubusercontent.com/20081898/217188448-f55418a9-aff8-436d-a34c-14c0a3860e64.png)
But when they finish the step, we will block them to generate again.

**Comment by josefree** [comment]
“ 80% of the API Spec PRs that are approved by the API Stewardship Board are merged after API readiness is complete.”  this is not right.  it's okay, only if any further revise required,  the spec PR should be reopened for further commits, "APIStewardshipBoard-SignedOff" taking off by bot.  If there are further updates to cadl specs,  API stewardship should take a look and approve again.

**Comment by maririos** [comment]
>  do we not look for the approval label? Is there a way to validate that whatever was changed does not require any additional review by the Stewardship Board?

@ladonnaq are these quesitons to @mikekistler ? From what I've seen, anytime there is a PR created in the specs repo, it can't be merged unless someone from the API Stewardship board approves it. Mike correct me if I'm wrong

**Comment by maririos** [comment]
> only if any further revise required, the spec PR should be reopened for further commits, "APIStewardshipBoard-SignedOff" taking off by bot. If there are further updates to cadl specs, API stewardship should take a look and approve again.

Is this what you expect? we should go first with what the current flow is before asking everyone to modify their process and introduce more noise.
If a PR stays open until the API Spec is ready and approved, we should let it be.

Also a PR shouldn't be reopen. If they merged the PR and now they need changes, they should create a new PR again

**Comment by zzvswxy** [comment]
> I would like the sign-off pages to have the similar UI - GitHub issue for tracking API readiness sign-off screen -

As https://github.com/Azure/azure-sdk-tools/issues/5222 mentioned, the information on SDK signoff page is enough for now.

**Comment by live1206** [comment]
>  For new services, we should release beta first (Product Public Preview) and then release stable SDK either at GA or minimum of one month after Public Preview (Stable releases required Arch Board approval).

We can consider to use Public preview release plan completion time as base line to check the gap between it and GA.

**Comment by maririos** [comment]
@live1206 and @ladonnaq what is the work remaining here?

**Comment by live1206** [comment]
@maririos The unchecked items in this issue are left.
>  For new services, we should release beta first (Product Public Preview) and then release stable SDK either at GA or minimum of one month after Public Preview (Stable releases required Arch Board approval).

Needs more input from @ladonnaq regarding the one below.
> The Cadl pull request (PR) that will be used to generate the APIViews and SDKs has the label "APIStewardshipBoard-SignedOff". We need to ask the APIStewardship Board if there new or additional PRs after sign-off, does this trigger a follow-up API Review? There can be additional Cadl/OpenAPI doc PRs during SDK release readiness app.

**Comment by ladonnaq** [comment]
Closing this work item as the design is outdated.  We will redesign in new UI but for now will patch current UI to enable usage of the SDK release app for TypeSpec + DPG release plans.   See this issue - https://github.com/Azure/azure-sdk-tools/issues/6403
