### ISSUE TITLE
API Review meeting step needs to be moved in the UI flow 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5129]
- [x] The API Review step should be after the "Activate a Pull Request"   @josefree @live1206 - We should move the API Review to right after Associate Pull Request because it can take up to a month to get on calendar.  
- [x] Change left-hand navigation to "Schedule API Review meeting". 
- [x] Please see new text to add so that service team understands they should schedule earlier and are reminded of prerequisites.  Also, please update the current link to the API stewardship Board to the aka listed in the screenshot.  
- Text in screenshot -  
"**Book now to secure a timeslot!**  You can schedule an API Review meeting  4-5 weeks in advance.  Please review the perquisites for the meeting on this wiki page - https://aka.ms/azsdk/onboarding/restapischedule. 

_**3 days prior to the scheduled meeting you will need to ensure all the prerequisites are updated.**_"

- [x] #6072
- [x] Remove type from table. 

![image](https://user-images.githubusercontent.com/67656762/220969502-2120c389-23d6-4eab-bf5e-bd2f97805516.png)

- [x] Change the label "Activate a Pull Request" on the left hand navigation menu and also on the screen.  @ccbarragan - What do you recommend?  Several people commented that activate did not make sense. Enable or Associate were some of the terms I heard during the user study. 
![image](https://user-images.githubusercontent.com/67656762/212184148-5c901180-00fb-496a-a723-7cbe2a78f79d.png)

**Comment by maririos** [comment]
@ladonnaq answering your questions:

> Please see new text to add so that service team understands they should schedule earlier and are reminded of prerequisites. Also, please update the current link to the API stewardship Board to the aka listed in the screenshot. @maririos - Does this make sense? Any edits to the text?

I like it! 

> @maririos - Which term makes more sense prerequisties or artifacts?

Prerequisites 

>What data is supposed to be in the Type column? Is this API Review vs Follow-up? If so, does the release planner have access to this information to populate the screen? @maririos - any more info or suggestions?

API Review meeting doesn't have a Type distiction, The value will always be `Rest API Review`, so we can remove this column from this UI as it does not add value

**Comment by ladonnaq** [comment]
> @ladonnaq answering your questions:
> 
> > Please see new text to add so that service team understands they should schedule earlier and are reminded of prerequisites. Also, please update the current link to the API stewardship Board to the aka listed in the screenshot. @maririos - Does this make sense? Any edits to the text?
> 
> I like it!
> 
> > @maririos - Which term makes more sense prerequisties or artifacts?
> 
> Prerequisites
> 
> > What data is supposed to be in the Type column? Is this API Review vs Follow-up? If so, does the release planner have access to this information to populate the screen? @maririos - any more info or suggestions?
> 
> API Review meeting doesn't have a Type distiction, The value will always be `Rest API Review`, so we can remove this column from this UI as it does not add value

Thanks, updated description with decisions.

**Comment by praveenkuttappan** [comment]
@ladonnaq @maririos What value should we display under column `Review and update prerequisites`? Show we list meeting notes?

**Comment by maririos** [comment]
> @ladonnaq @maririos What value should we display under column `Review and update prerequisites`? Show we list meeting notes?

Ohh I didn't see that column. To keep it simple for now, I will say to delete it for now. If we decide we need more information later on, then we can add it

**Comment by ladonnaq** [comment]
> > @ladonnaq @maririos What value should we display under column `Review and update prerequisites`? Show we list meeting notes?
> 
> Ohh I didn't see that column. To keep it simple for now, I will say to delete it for now. If we decide we need more information later on, then we can add it

The Review and update prerequisites column is a link to the meeting that has been scheduled so that the user can easily access it to update the prerequisites before the meeting (i.e. add link to the hero scenario, core concepts, ....).
