### ISSUE TITLE
APIView - Show links to all API reviews created from swagger PR 

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5142]
Swagger PR pipeline generates SDK level API reviews, and these reviews can be identified using PR number and spec repo name. Architects has requested a feature to show links to all API reviews created from spec PR at the top of the reviews so they can easily open all reviews without searching for it using PR number.

**Comment by maririos** [comment]
Related to https://github.com/Azure/azure-sdk-tools/issues/4677

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/5417 and https://github.com/Azure/azure-sdk-tools/pull/5555
