### ISSUE TITLE
Add debug logs and deploy new release to prod

### ISSUE THREAD

**Issue by xiaoxuqi-ms** [Azure/azure-sdk-tools#5146]
THere is no comment in ado repo: https://github.com/Azure/azure-rest-api-specs-pr/pull/10669, one possible reason is that the functions may exit unexpectedly when parsing sync info or requesting reviewers in github repo.

**Comment by kurtzeborn** [comment]
Appears to be related to shift left.  Since we're reevaluating shift left all up, closing this.
