### ISSUE TITLE
APIView - Swagger review gen failed to find eligible swaggerfiles

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5156]
Swagger API review gen skipped all files in the PR and it did not generate a review. 

/mnt/vss/_work/1
outputDir: /mnt/vss/_work/1/generated
>>>>> Files changed in this PR are as follows:
[
  'dev/cognitiveservices/data-plane/Language/analyzeconversations-authoring.json',
  'dev/cognitiveservices/data-plane/Language/analyzetext-authoring.json'
]
>>>> **Number of swaggers found in this PR**: 0
>>>>> Files deleted in this PR are as follows:
[]
fileChanges in swagger: []
[]
**No tag contains changed file. skip swaggerAPIView**

PR: https://github.com/Azure/azure-rest-api-specs/pull/22209/checks?check_run_id=10703951009

**Comment by ruowan** [comment]
For this case, we will report errors and tell PR author to check readme format is valid and the tag is defined. 

Here is example PR https://github.com/test-repo-billy/azure-rest-api-specs/pull/2880: 
![image](https://user-images.githubusercontent.com/52271048/215964887-15820452-ac58-4456-935c-4e058d4600c8.png)

**Comment by ruowan** [comment]
@mikekistler The readme template in error message is [this](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/samplefiles/samplereadme.md). 

There are two readme templates in spec repo: 

- [management-plane readme](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/samplefiles/samplereadme.md)
- [data-plane readme](https://github.com/Azure/azure-rest-api-specs/blob/6b9c0891fa/documentation/samplefiles-dp/samplefiles-dp-for-single-client/readme.md)

The two readme templates have the similar structure. But some data-plane RP doesn't follow the template which cause fail to generate swaggerAPIView.  For example, [cognitiveservices](https://github.com/Azure/azure-rest-api-specs/blob/6b9c0891fa7088dcfdf3b0178c1f46b010ac65ae/dev/cognitiveservices/data-plane/Language/readme.md).

How do you think about this error message? Do we need to guide service team to update the readme file?
