### ISSUE TITLE
Redesign of UI and logic to enable user to change the PR associated with release plan for API Readiness and SDK Release

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5157]
The release planner is no longer blocking a user to change the PR that is associated with the API readiness application but the UI and logic to explain how and why you would do this is not in the tool.  As an interim solution (until new UI is implemented) we have agreed to the following design/requirements: 

@josefree @live1206  @zzvswxy 

- [ ] #5541
https://user-images.githubusercontent.com/18413981/218945874-eeee4958-a569-48a7-bdf7-d3e6365ebe7d.png

- [x] Update the SDK Release app pre-requisite page to explain the PR relationship with the SDK release.  
https://user-images.githubusercontent.com/18413981/220268499-8de83490-20d0-4b22-ae16-665503688181.png

**Comment by josefree** [comment]
My response is in this issue https://github.com/Azure/azure-sdk-tools/issues/4905.  I assume this one is to collect design ideas. @ccbarragan feel free to comment.

**Comment by josefree** [comment]
@ladonnaq We need service team to take serious consideration on 1. language scope,  2. prefered SDK release train.  And we do not encourage random updates afterwards. Because the updates can lead to communication cost and engineering cost.   The only reason we support release date updating should be that service launch date is deferred.

**Comment by maririos** [comment]
> @maririos @josefree - What is the monthly release train for data plane? Wouldn't teams have to align their release to the train? The way the app is designed it implies that a service can choose the exact release date of their SDKs.

It is monthly with code complete first Friday of the month and release next week.

**Comment by ladonnaq** [comment]
> @ladonnaq We need service team to take serious consideration on 1. language scope, 2. prefered SDK release train at first place. And we do not encourage random updates afterwards. Because the updates can lead to communication cost and engineering effort waste. The only reason we support release date updating is that service launch date could be deferred. To remove any language in the middle of release (SDK pull request is created, SDK release owner could start working on test case development already...) definitely should be communicated offline with sound justification.<

1. The default should be all languages. I also think that if the release plan is associated with a product launch(APEX) that the user should not be able to de-select a language. If they don't want to not release a language, they will have to raise an exception. I believe there could be non-APEX scenarios where they may only need to release a subset of the languages. 
2. We agreed that we will change to show options for release train not a calendar to choose a date. We ask for the SDK release date at the time the release planner is created. Perhaps for APEX we set the SDK release date (train) based on the launch dates. If the launch date changes, we update the SDK release train. There would need an option to select the train for exceptions and non-APEX but we could determine APEX SDK release train. 
3. We need to handle "the PR that was used during API Readiness is now hardcoded to the SDK release" situation better. If we are enforcing the same PR then we need to guide them through retuning to the API Readiness app to associate a different PR if they need to do so. Right now it is a very disjointed experience.

**Comment by ladonnaq** [comment]
> > @maririos @josefree - What is the monthly release train for data plane? Wouldn't teams have to align their release to the train? The way the app is designed it implies that a service can choose the exact release date of their SDKs.
> 
> It is monthly with code complete first Friday of the month and release next week.

Thank you! @josefree the train info can be updated now for data plane. I see it is done for management.

**Comment by maririos** [comment]
@ladonnaq  given all the conversations and decision in this issue, could you update the UI on what the requirements are now so Eng has a clear picture on what to do?

**Comment by josefree** [comment]
@live1206 @honghr please check the mockup below.  When user enters the blade of "Associate a pull request" again, and selects another pull request, clicks the button of "Associate the PR...", there should be a pop-up message for user to confirm he/she wants to proceed with all the cost.  There should be a notification to SDK milestone owner, and Azure SDK release owners that the spec pull request is updated. 

![image](https://user-images.githubusercontent.com/18413981/218945874-eeee4958-a569-48a7-bdf7-d3e6365ebe7d.png)

**Comment by live1206** [comment]
@josefree Thanks for the mockup, it's great to improve the notification while user re-associate the PR in API Readiness App.
But as I can see the main pain point here is that, if the user wants to re-associate Spec PR during the SDK Release process.
Or to say, how would the user know they should go back to API Readiness to re-associate the PR in SDK Release App?

**Comment by josefree** [comment]
no better solution based on current design.  The guidance to a specific scenario is better to be provided as FAQ or tutorial, Which can be referred in the place they encounter trouble.   However, current design does not include UX of FAQ and tutorial in the app.  We may plan that in UX enhancement.

**Comment by live1206** [comment]
> @live1206 @honghr please check the mockup below. When user enters the blade of "Associate a pull request" again, and selects another pull request, clicks the button of "Associate the PR...", there should be a pop-up message for user to confirm he/she wants to proceed with all the cost. There should be a notification to SDK milestone owner, and Azure SDK release owners that the spec pull request is updated.
> 
> ![image](https://user-images.githubusercontent.com/18413981/218945874-eeee4958-a569-48a7-bdf7-d3e6365ebe7d.png)

@josefree Regarding the warning text, it works with assumption that SDK Release has been kicked off. 
But the user might re-associate the Spec PR without kicking off SDK Release yet, for instance, the user can do it during the API Readiness Process just after this step.

**Comment by zzvswxy** [comment]
> * Prerequisite screen
> 
> ![image](https://user-images.githubusercontent.com/67656762/215882966-f5886a7c-765d-40f8-8692-e93e1c9e5c40.png)

Hi @ladonnaq  
![image](https://user-images.githubusercontent.com/20081898/219323645-bd6116d9-1249-4684-8fc4-2fc22a9361c1.png)
This is what Prerequisite screen look like.
Launch Type is Product Lifecycle. Service Mappling shows service info.
But checked with @live1206 , we can't get the API Version in this page.

**Comment by josefree** [comment]
![Image](https://user-images.githubusercontent.com/18413981/220268499-8de83490-20d0-4b22-ae16-665503688181.png)

**Comment by josefree** [comment]
@ladonnaq @zzvswxy please check out the prerequisite proposed above.  It is based on the change requested per offline discussion

**Comment by ladonnaq** [comment]
> ![Image](https://user-images.githubusercontent.com/18413981/220268499-8de83490-20d0-4b22-ae16-665503688181.png)

@josefree This represents the changes we discussed.  Let's update and deploy these changes to PPE and PROD.  This should suffice until the new UI is designed and implemented.

**Comment by zzvswxy** [comment]
SDK Release app
![image](https://user-images.githubusercontent.com/20081898/220501658-c82672df-e1e0-4245-b46c-3c2b3f29bad2.png)
Done in Dev, will deploy the changes to PPE and Prod.

**Comment by honghr** [comment]
> 

@josefree Does this need to updated?

**Comment by honghr** [comment]
> > @live1206 @honghr please check the mockup below. When user enters the blade of "Associate a pull request" again, and selects another pull request, clicks the button of "Associate the PR...", there should be a pop-up message for user to confirm he/she wants to proceed with all the cost. There should be a notification to SDK milestone owner, and Azure SDK release owners that the spec pull request is updated.
> > ![image](https://user-images.githubusercontent.com/18413981/218945874-eeee4958-a569-48a7-bdf7-d3e6365ebe7d.png)
> 
> @josefree Regarding the warning text, it works with assumption that SDK Release has been kicked off. But the user might re-associate the Spec PR without kicking off SDK Release yet, for instance, the user can do it during the API Readiness Process after this step.

@josefree Does this need to updated?

**Comment by zzvswxy** [comment]
Hi @josefree  @live1206  @ladonnaq  @honghr  I create a new issues to track the API readiness APP changes. https://github.com/Azure/azure-sdk-tools/issues/5541 
I will close this issue as the SDK Release App changes has been deployed to Prod environment.
