### ISSUE TITLE
Incorrect security group is copied on onboard emails 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5158]
I noticed that Siva and I are not receiving emails when a new product onboards using the release planner. I tested today and saw that the incorrect security group is copied. 

The correct email address is azsdkapex@microsoft.com.  

The current email address azuresdkapex@microsoft.com should be removed. 

I am not sure why the error was not encountered by the application.  If I send an email to the incorrect address I get an error. 

![F8C4404A-6032-4C48-9DC0-910EF3AF83AD](https://user-images.githubusercontent.com/67656762/213072060-aa3457db-cde4-4db8-b8d2-9e8d4392cbf5.png)

**Comment by ladonnaq** [comment]
@maririos Would someone be able to look into since most of the Shanghai team is out until end of January?  It is problematic because Siva/I are not receiving the emails when the service partner completes onboarding with the Release Planner.  We do look in the "APEX New" ADO query but sometimes service partners will respond to the automated emails and then they will get an error mesage because the email on copy is incorrect.

**Comment by maririos** [comment]
Interesting. Let me take a look

**Comment by maririos** [comment]
I found it!! and it has been fixed in DEV environment. I prefer to wait until @live1206 is back to dpeloy it to PROD.
@ladonnaq I will ping you for a workaround fr now.

![image](https://user-images.githubusercontent.com/9868623/213575336-ba1e5070-c5ab-47cd-83a1-6193d3ef9b7e.png)

**Comment by live1206** [comment]
@maririos Thanks for the quick fix!
@ladonnaq The fix has been deployed to Prod, the problem should be resolved now.

**Comment by ladonnaq** [comment]
> @maririos Thanks for the quick fix!
> @ladonnaq The fix has been deployed to Prod, the problem should be resolved now.

Thank you!!!
