### ISSUE TITLE
Build dotnet tools with matrix of OSes

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#5159]
We should build src/dotnet tools with different OSes like we do in the Azure/azure-sdk-for-net directory to make sure all our tests work across OSes and any TFMs we might add e.g., `net472` on Windows.

See https://github.com/Azure/azure-sdk-tools/pull/5154#discussion_r1073098588 by @heaths for context.

**Comment by weshaggard** [comment]
For our tool builds we thus far haven't really had the need to build or run tests on other OS's. However, I'm fine if we want to add different OS's to the test matrix. If we end up needing to package this for windows we might also need to move to do the build/package step on windows.

**Comment by heaths** [comment]
Thanks. I don't think we'll need to package. This is only testing net472 (analyzers won't work in net461 or net462, it seems) but will still build/pack only for netstandard2.0.
