### ISSUE TITLE
Automate API Spec Pipeline enablement for service partner

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5161]
Service partners who will be using Cadl to describe their management and/or data plane APIs are also supposed to enable the API Spec pipeline.  Link to the wiki page - 
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/606/Enable-API-Spec-Pipeline. During the stakeholder reviews the feedback was that this process should be automated.  

1. The current documentation is targeted for management plane and it is not clear what exactly needs to be done for data plane.  
2. Is there a way to validate if the API Spec Pipeline has already been enabled in the service team's ADO repo? 
3. How many services have enabled the API Spec pipeline for management plane?  If they enabled for management plane, then is there something they need to do support data plane? 
4.  The following Azure Devops (ADO) projects are supported.  Not all service partners will be associated with these projects.  
![image](https://user-images.githubusercontent.com/67656762/213215895-8ea62188-42e3-42b8-a377-fb5ce4672507.png)
5. If a service partner needs to add request support for their ADO project, they are directed to this wiki page - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/708/Prerequisite-for-new-Azure-DevOps-Account.  Again there are manual steps. The user has to first reach out to a teams channel to request key vault provision and then reach out via email to  request the personal access token and service principal key before they proceed.  
6. This is confusing because some of our service partners are working on products that are only in scope for data plane.  They may not know anything about the resource provider (RP).  
![image](https://user-images.githubusercontent.com/67656762/213227355-9ee02b8b-d036-472b-ab63-c2a34c138075.png
7. In the "prestep" section of the wiki page there is a link to a form. The release planner already has all of the information that the form request the user to complete. The rest of the instructions this section are related to "copy and paste" of directory structure and files from the API Specs repo to ADO.  Why can't we do this for the user?  We can get their source code location from service tree and we should be able to find GitHub directory for the service. 
![image](https://user-images.githubusercontent.com/67656762/213228004-0fee0ec2-c413-47c9-8e3e-11aff65ff25b.png)
![image](https://user-images.githubusercontent.com/67656762/213230582-19b12972-101e-4641-ab6d-8b9c59aebe0c.png)
8. The onboarding steps requires the user to copy templates and update variables.  We should already have most of the data or can ask for it via the release planner.  
![image](https://user-images.githubusercontent.com/67656762/213234216-59d93fba-cfb4-4abf-8ded-cec11b9b332e.png)

**Comment by maririos** [comment]
Closing this issue as API Spec Pipeline is no longer funded
