### ISSUE TITLE
Management API Readiness - feedback from experience with service partner and bugs/function not working

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5171]
I was working with service partner today and thought it would be a good opportunity to show them the release planner beta for management plane.  They are using Cadl so perfect team to use the release planner app. 

This was our experience in attempting to use the API Readiness App for management plane. 

1. When we got to the API Readiness step for Cadl validation all of the status was showing as unavailable.  I am not sure if this is because the app is not working or if it is something to do with the PR they provided.  

![image](https://user-images.githubusercontent.com/67656762/213532931-1bfd037a-7343-475c-a000-a298c52b513c.png)

2. When we selected details - we don't end up exactly where the information related to what is being validated.  For example, select details next Cadl validation directs us here.  

![image](https://user-images.githubusercontent.com/67656762/213532597-4e3d778c-8cac-428f-a588-56d6944becc7.png)

3. When I expand the "openapi-pipeline-app" and search, I do find cadl validation and the message said it succeeded.  

![image](https://user-images.githubusercontent.com/67656762/213534185-aa721760-b2bc-4590-bc31-9092c35d6fae.png)

4.  #1, #2, and #3 apply to the Review breaking changes and legacy spec issues screen/blade as well.
5. Setup API docs is also displaying unavailable but if I go look in the PR, I found that is available.  Here is the link - https://review.learn.microsoft.com/en-us/rest/api/azure-rest-preview/?branch=result_12688ab9-a7ed-4e44-9da6-e1bf5f6fd08b&view=azure-rest-preview 
![image](https://user-images.githubusercontent.com/67656762/213535516-fe799877-4e5d-41f9-9daf-f4fe93463803.png)
6. The service partner engineers had never seen this information before and did not know what to do with it. 
![image](https://user-images.githubusercontent.com/67656762/213536011-94cd63e8-029b-45e8-b35e-7460f6a54395.png)
7. They found this page confusing.  The engineers are working a new API version in the private repo for Public Preview.  There is another API Version that was approved by ARM for Private Preview and they met with ARM Review Board.  Also, the bot adds the label to initiate the ARM review.  
![image](https://user-images.githubusercontent.com/67656762/213538329-b7d0b62f-6796-44e6-a53b-c5225d46d99b.png)

![image](https://user-images.githubusercontent.com/67656762/213536842-61e5c3aa-55d4-4205-8a64-ccbe886fa51a.png)

8. Generate SDK screen/blade had no data.  
9. There is no information to explain why something failed and where to go to fix it. 
- The service partner told me that there would be new initial management libraries, so naming is required but in the app it status displays that it is not required.  
- The screen displays SDK generation is completed but on the Generate SDK screen it was blank (no SDKs seen). 
- Spec validation displays failed but there is no mention of the Spec anywhere else.  Only Cadl validation. 

![image](https://user-images.githubusercontent.com/67656762/213539187-39bfc209-6689-4e1e-ab2d-509d5745edf4.png)

**Comment by live1206** [comment]
> 1. When we got to the API Readiness step for Cadl validation all of the status was showing as unavailable. I am not sure if this is because the app is not working or if it is something to do with the PR they provided.
This PR was created from forked repo to private repo, this is not supported in OpenAPI Hub anymore, but the user can still manually create this kind of PR. The implementation in Release Planner App is via OpenAPI Hub, so this kind of PR is not supported. However, I think this is a valid case for Release Planner to support. 
@honghr We need to figure out a way to get the validation result for PR created from forked repo.

**Comment by live1206** [comment]
> 2. When we selected details - we don't end up exactly where the information related to what is being validated. For example, select details next Cadl validation directs us here.

This is the same reason as the previous issue, we could not get CI result from PR of forked repo, the link is missing `check_run_id`.

**Comment by live1206** [comment]
> 6. The service partner engineers had never seen this information before and did not know what to do with it.
![image](https://user-images.githubusercontent.com/67656762/213536011-94cd63e8-029b-45e8-b35e-7460f6a54395.png)

@josefree I know you had some internal discussion regarding this, any updates?

**Comment by live1206** [comment]
> 7. They found this page confusing.  The engineers are working a new API version in the private repo for Public Preview.  There is another API Version that was approved by ARM for Private Preview and they met with ARM Review Board.  Also, the bot adds the label to initiate the ARM review.  
![image](https://user-images.githubusercontent.com/67656762/213538329-b7d0b62f-6796-44e6-a53b-c5225d46d99b.png)
![image](https://user-images.githubusercontent.com/67656762/213536842-61e5c3aa-55d4-4205-8a64-ccbe886fa51a.png)

In Management-Plane Api Readiness App, we are trying to guide the user step by step of PR review.
If the PR is labelled with `CI-FixRequiredOnFailure`, we would expect the user to fix CI failures before ARM review.
And you are right that, we don't stop ARM Review Board from reviewing the PR right now. Do you think we should add `ARMReview` label after CI failures are fixed?

cc @josefree

**Comment by live1206** [comment]
> 8. Generate SDK screen/blade had no data.  

The SDK generation data is based on OpenAPI hub result as well, it is not working for PR of forked repo.

**Comment by live1206** [comment]
> 9. There is no information to explain why something failed and where to go to fix it. 
>- The service partner told me that there would be new initial management libraries, so naming is required but in the app it status displays that it is not required.  

Right now, if the user did not fill in the namespace review issue, the status of `Library Namespace Review` will be `Not Required`.
It should be `unavailable` since it should be filled in for public preview release. @honghr 
>- The screen displays SDK generation is completed but on the Generate SDK screen it was blank (no SDKs seen). 

For empty SDK generation, the status should be `unavailable`. @honghr 
>- Spec validation displays failed but there is no mention of the Spec anywhere else.  Only Cadl validation. 
![image](https://user-images.githubusercontent.com/67656762/213539187-39bfc209-6689-4e1e-ab2d-509d5745edf4.png)

The user needs to go back to previous step `Clean up Validation Errors` from the left navigation panel to get all the validation details.

**Comment by ladonnaq** [comment]
> > 7. They found this page confusing.  The engineers are working a new API version in the private repo for Public Preview.  There is another API Version that was approved by ARM for Private Preview and they met with ARM Review Board.  Also, the bot adds the label to initiate the ARM review.
> >    ![image](https://user-images.githubusercontent.com/67656762/213538329-b7d0b62f-6796-44e6-a53b-c5225d46d99b.png)
> >    ![image](https://user-images.githubusercontent.com/67656762/213536842-61e5c3aa-55d4-4205-8a64-ccbe886fa51a.png)
> 
> In Management-Plane Api Readiness App, we are trying to guide the user step by step of PR review. If the PR is labelled with `CI-FixRequiredOnFailure`, we would expect the user to fix CI failures before ARM review. And you are right that, we don't stop ARM Review Board from reviewing the PR right now. @ladonnaq Do you think we should add `ARMReview` label after CI failures are fixed?
> 
> cc @josefree

I do think we should include the label after CI failures are fixed.  Thanks!

**Comment by maririos** [comment]
This has been fixed with the `1.0.0-beta.8` deployment
