### ISSUE TITLE
Bug - No products showing up for service 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5179]
I met with a service partner today that is working on data plane and management plane Private Preview for a new service and initial offering.  We walked through what they needed to do.  Then I provided a quick demo of the release planner Beta 2 (PROD) and Beta 3 (PPE).  They wanted to create a release plan for tracking Private Preview but the product list failed to load for the service.  I will put the screenshot and details in the engagement experience eng teams channel.

**Comment by maririos** [comment]
This is related to https://github.com/Azure/azure-sdk-tools/issues/5180 which has been fixed. 
@ladonnaq if you still see issues, let me know
