### ISSUE TITLE
Bug - No products loading in release planner app 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5180]
It seems that no products are loading for any service.  I met with Azure Load Test team to discuss evidence they needed to provide for GA APEX signoff.  We also discussed Cadl and the release planner app.  When we tried to walk-thru how to create a release plan for their service, the product list did not load.  

![image](https://user-images.githubusercontent.com/67656762/213748708-b74f038b-9177-4939-950f-9d453d8991aa.png)

**Comment by maririos** [comment]
One of our sync flows failed to execute and ended up deleting data from a table we use to load the products. Currently all of our PowerApps are affected by it
