### ISSUE TITLE
CADL APIView - manual pipeline tries to use hard-coded cadl-apiview version but that won't work

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#5189]
Due to NPM versioning, each version of cadl-compiler requires a new release of cadl-apiview that is compatible. The current pipeline for manual APIViews (by URL) has a hard-coded value of 0.3.0, meaning it is only compatible with one specific (old) version of Cadl compiler. 

Generally speaking, the pipeline needs to install whatever version of cadl-apiview is compatible with the version of cadl-compiler present in the target spec. There are two scenarios:

**1 - cadl-apiview not present in package.json**

This is the most common case. Every spec _must_ have a dependency on cadl-compiler, so the solution here is to install the version of cadl-compiler specified in package.json and use npm dependency resolution to figure out the compatible version of cadl-apiview to install. 

**2 - cadl-apiview is present in package.json**

Give that we have enabled automatic APIVIews from PRs, this is likely to be the minor case, but if cadl-apiview is present in the package.json then it's reasonable to assume that the versions are compatible and use it. If they are not compatible, that's the fault of the spec author and should be an error.

**Comment by praveenkuttappan** [comment]
We use global package.json by default to install typespec/cadl packages. This has been taken care in following PR. 
https://github.com/Azure/azure-sdk-tools/pull/5196
