### ISSUE TITLE
Ensure that all active APEX product data is in Release Planner 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5200]
This query contains all of the active APEX products - https://dev.azure.com/azure-sdk/Release/_queries?tempQueryId=20b2c114-2dfc-45dd-ba52-a9cdf33997c7.   The data needs to be migrated from Azure Devops so that teams do not need to create new Onboard work items and so that the data will be synced from the Release Planner to the existing ADO work items. 

If we could start by having the data in the PPE environment so that we could test, that would be great!

**Comment by live1206** [comment]
@ladonnaq 
We should exclude the ones with `Release Planner App Test` tag, like this one: https://dev.azure.com/azure-sdk/Release/_workitems/edit/14249/

**Comment by live1206** [comment]
This should be part of https://github.com/Azure/azure-sdk-tools/issues/4600

**Comment by maririos** [comment]
Was this done as part of #4600 ? or still needs to happen
