### ISSUE TITLE
GitHub.io API documentation suggestions

### ISSUE THREAD

**Issue by jpeng-ms** [Azure/azure-sdk-tools#5208]
Hi, I am reaching out to provide a suggestion on how our API doc is publish to GitHub.io. Currently on https://azure.github.io/azure-sdk-for-ios/ we have documentations for few SDKs. 

The problem is that we don't have a tool to preview the doc. Comparing to MSDoc, it generates a preview link for each changes and we can share internally to review it before publishing it to public. 

It would be nice to leverage Azure function app or Azure Storage to publish the API doc internally before it becomes available on GitHub.io

**Comment by kurtzeborn** [comment]
This is a good suggestion.  Unfortunately, all of our efforts around docs are focused on learn.microsoft.com and as you note, we have daily builds of the docs for previewing before we do releases (which publishes them to the official site as part of the release pipeline).  I don't anticipate an investment in github.io docs to provide similar previews in any language, so I'm going to close this issue.  One thing I did notice in the ios github.io site is that we're not even versioning the docs there.  For all other langauges, we version the docs.  So, over time, the github.io docs accumulate many versions of the docs.  We should probably add versioned docs support for ios on github.io once we are resourced enough to invest in ios again.
