### ISSUE TITLE
API review for swagger is not shown in swagger PR

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5216]
API review was generated successfully for swagger change in PR https://github.com/Azure/azure-rest-api-specs/pull/22291

But API review was not added back in PR comment.

API review: https://apiview.dev/Assemblies/Review/e16cd9aac9a84ad3873c6b5185341ef3

**Comment by dw511214992** [comment]
it is shown in https://github.com/Azure/azure-rest-api-specs/pull/22291#issuecomment-1401808671 now
