### ISSUE TITLE
No changes to the SDK Review meeting agenda 48 hours prior to the start of the meeting 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5217]
From Ronnie: 

"We’ve got some very frustrated architects because ACS is changing the scope of the Arch Board review meeting 3 hours before the meeting starts. Changing the scope of the meeting from just .NET to .NET, Android, and iOS. This does not leave the architects enough time to review the material before the meeting. 

My suggestion would be to lock down the meeting 48 hours before it should begin, so that the description cannot be changed, and no extra links can be added unless the meeting is rescheduled to a later date."

**Comment by maririos** [comment]
Adding some feedback I had over email:

That definitely sounds frustrating. We can work on a feature like that, but my concern is that they will always be able to add content to the GH issue directly and that might create confusion on what information we should trust. 

Things I am thinking:
-	Block app for edits
-	Update Calendar invite and GH issue clarifying this is the information that should be reviewed.
-	Talk to the ACS team and make sure they understand our process. 
-	Assign someone from our team and work with the ACS team to supervise and make sure the follow the rules
-	Revisit all of the process documentation and make sure it is clear when the information should be last updated and what happens after that window of time.

What do you think?

**Comment by maririos** [comment]
Closing in favor of https://github.com/Azure/azure-sdk-tools/issues/5118
