### ISSUE TITLE
Update the Enable API Spec Pipeline doc with simplified instructions for data plane 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5223]
There is a requirement open to determine if enabling the API Spec pipeline can be partially or fully automated. https://github.com/Azure/azure-sdk-tools/issues/5161

In the near term the documentation needs to be reviewed and updated with simplified instructions for data plane.  A user today cannot determine what they are supposed for data plane, as the documentation has many references that apply to management plane. 

https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/606/Enable-API-Spec-Pipeline.

**Comment by josefree** [comment]
The guidance is for both management plane and data plane.  I will be working on the doc improvement.

**Comment by ladonnaq** [comment]
> The guidance is for both management plane and data plane. I will be working on the doc improvement.

Thanks @josefree!  

@ccbarragan - When should we start moving all of the documentation for the release planner into engineering hub?  Thinking as we start to create documentation that will be linked to from the release planner having it in engineering hub would be good.  This would address the permissions issue.  If a user does not have access to our Azure Devops, they have to request access to view our docs or we have to have aka links for everything.

**Comment by maririos** [comment]
@josefree did you get this work done before the re-deployment?

**Comment by maririos** [comment]
Closing as we are currently not investing in API Spec pipeline
