### ISSUE TITLE
[testmodeler] Bundle dependencies

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#5229]
Package `@autorest/testmodeler` should probably bundle its dependencies, similar to the `autorest` core packages (which use `webpack` to bundle dependencies during the build process).

Currently, `@autorest/testmodeler` tries to pin its dependencies by including `npm-shrinkwrap.json` in the package.  However, this file is ignored by `yarn`, which is the package manager used by `autorest` to install extensions.  So in practice, the dependencies for `@autorest/testmodeler` are currently unpinned, which leads to issues like #5183.

**Comment by mikeharder** [comment]
You should be able to copy all or most of the `webpack` bundling logic from the `autorest` core packages.

**Comment by mikeharder** [comment]
@changlong-liu: Sorry I missed this during my review, but as part of this change I think you want to move all dependencies to devDependencies. If all the dependency code is bundled, you no longer need the runtime dependencies. For example, see https://github.com/Azure/autorest/blob/main/packages/extensions/core/package.json.

**Comment by changlong-liu** [comment]
> @changlong-liu: Sorry I missed this during my review, but as part of this change I think you want to move all dependencies to devDependencies. If all the dependency code is bundled, you no longer need the runtime dependencies. For example, see https://github.com/Azure/autorest/blob/main/packages/extensions/core/package.json.

Thanks for pick @mikeharder! Yes, let me try.
