### ISSUE TITLE
Survey for Release Planner - Onboard new product feature 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5234]
Service partners have been using the Release Planner to onboard new products in scope for APEX for the last couple of months.  We need to send a survey to gather feedback on their experience.

**Immediate Todos:** 

- [x] Here is draft of the survey - https://forms.office.com/Pages/DesignPageV2.aspx?subpage=design&FormId=v4j5cvGGr0GRqy180BHbR-SRHOv9H51LkqMFimFYWbJUMlZaSVdNUzM5UkE1WjJYTlNXMlhMVkFPUy4u
- [x] We need list of user's and email addresses to send the survey.  

**Design and Requirements** 

- [ ] **Phase 1:**  Let's get the email addresses of the users since September and manually trigger the email to request feedback via the survey. 

**Phase 2:**  Automation of sending the survey
@live1206 We can do this now.  Created another GitHub issue to track changes to survey and timing once Service Partners are creating release plans. https://github.com/Azure/azure-sdk-tools/issues/5463
- [x] Add survey link to the automated emails that are sent after a product is onboarded.  "Thanks for using our new Release Planner application to onboard with the Azure SDK team! Your feedback matters to us, and we’d love to hear more about your experience using the Release Planner. Would you mind taking a quick 2-minute survey to help us improve the scheduler tool experience? Here is a link to the survey - https://aka.ms/azsdk/releaseplanner/feedback".  See example in comments.

**Comment by ladonnaq** [comment]
@live1206 - Can we add a link to the survey in the automated emails that the service team's receive when they have completed onboarding?  We can change they survey questions and the timing when the service teams are using the Release Planner to create release plans.  We don't want to spam the service team's with surveys. 

We could add this to the top of the automated emails.  

Thanks for using our new Release Planner application to onboard with the Azure SDK team! Your feedback matters to us, and we’d love to hear more about your experience using the Release Planner. Would you mind taking a quick 2-minute survey to help us improve the scheduler tool experience?   Here is a link to the survey - https://aka.ms/azsdk/releaseplanner/feedback

**Azure SDK Onboarding Information and Next Steps** 

The Azure SDK Team will engage with your team to provide guidance and/or tooling to create Azure SDKs. Our team will help you with APIs that have ARM endpoints ("management plane") and APIs that have non-ARM endpoints ("data plane").

Please refer your work item: [SDK Intake - Edge Network Fabric](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fazure-sdk%2FRelease%2F_workitems%2Fedit%2F14440&data=05%7C01%7Cladonnaquinn%40microsoft.com%7Cdfd903205aaf4ddda5dd08db0ea1fbeb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638119861119305326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=m2Ge85AX%2B4h9gZWGZm7q7IBgDLjzaWQsbAEVYXoyYYs%3D&reserved=0)

The onboarding survey responses indicated that the product is out of scope for management and data plane.
The Azure SDK onboarding team will reach out to you in 3 business days to validate that the product is out of scope.

•	Next Steps Azure SDK team: The Azure SDK onboarding team will reach out within 3 business days to confirm the product is out of scope and/or request additional information if needed.
•	Next Steps APEX product team: Please review useful resources provided below.


If you have questions, contact us by posting a question to our [teams channel ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2Fl%2Fchannel%2F19%253ade3fce22c2994be18cac50502c55f717%2540thread.skype%2FAzure%252520SDK%252520Onboarding%3FgroupId%3D3e17dcb0-4257-4a30-b843-77f47f1d4121%26tenantId%3D72f988bf-86f1-41af-91ab-2d7cd011db47&data=05%7C01%7Cladonnaquinn%40microsoft.com%7Cdfd903205aaf4ddda5dd08db0ea1fbeb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638119861119305326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7x1BCRXFk%2Bj1%2BBXSzBrVWMg6Bi0q4fgIducO00X0gJ0%3D&reserved=0), [email](mailto:plrsdk@microsoft.com), or schedule an [Azure SDK Q&A meeting with the Azure SDK Onboarding Team](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Foutlook.office365.com%2Fowa%2Fcalendar%2FAzureSDKEngagementCalendar%40microsoft.onmicrosoft.com%2Fbookings%2Fs%2FC5ji-geK-E-K2UaAvz3X1A2&data=05%7C01%7Cladonnaquinn%40microsoft.com%7Cdfd903205aaf4ddda5dd08db0ea1fbeb%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638119861119305326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eyZb%2Bqlb2oiYpEQN%2BOqMZzlFrmHZEfdKHuSaBsg8zQw%3D&reserved=0).

**Comment by ladonnaq** [comment]
@live1206 @josefree Can we go ahead and make this update so that perhaps some of the service partners who use the app for onboarding will take a minute to complete the survey?  Thanks - La Donna

**Comment by live1206** [comment]
@ladonnaq 
I have made the survey link clickable and only change the first sentence of the mail, leave the rest as it is.
Here is an example
<img width="853" alt="image" src="https://user-images.githubusercontent.com/5196139/220807161-133531f2-3006-4d69-87d8-1d4099846974.png">
The change has been deployed to PPE, you can try it out. Once confirmed, I will deploy the change to Prod.

**Comment by maririos** [comment]
@live1206 was this changed deployed to Prod?

**Comment by live1206** [comment]
> @live1206 was this changed deployed to Prod?

Not yet, only deployed to PPE.

**Comment by maririos** [comment]
Interesting. How does this work then? The email templates are inside a cloud flow, right? how was it not deployed to Prod with the latest deployment you did?

**Comment by live1206** [comment]
> Interesting. How does this work then? The email templates are inside a cloud flow, right? how was it not deployed to Prod with the latest deployment you did?

Yes, the template is in flow `Send Onboarding Questionnaire Email - Child`, I haven't deployed this flow to Prod yet.

**Comment by maririos** [comment]
Deployed to prod
