### ISSUE TITLE
Variables used for testing should have common prefix

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#524]
Whether environment variables or variables used in Azure Pipelines, we should use a common prefix like `AZURE_`. Especially with environment variables, many of these will contain sensitive information like client secrets, shared keys, etc. With more infrastructure moving toward our test-resources.json solution, along with some script changes to automate more of variable creation (including creating even more variables), it's important customers can quickly, easily, and assuredly find secrets and clean them up lest they accidentally leak.

As discussed in https://github.com/Azure/azure-sdk-tools/pull/509#discussion_r411612596, I found that quite a few services aren't doing this. It means potentially sensitive information is "spread out" over environment blocks that get increasing larger.

For example, with just a half dozen variables set for Key Vault and Search (shared) on a developer machine, I have 60 environment variables of various nature and casing. It would be hard to spot some of these and clean them up if I was done contributing and testing a change.

/cc @weshaggard @danieljurek @pakrym

**Comment by pakrym** [comment]
I think we should apply the prefix that's being added in #509 to all variables. Didn't want to do it in that PR because it's a breaking change for non .net repos.

**Comment by weshaggard** [comment]
I like having a common prefix for convention and potential easy clean-up. The more I think folks use our scripts we should reconsider if we should automatically add variables into the env and as part of that we can automatically clean them out of the env when we run the clean-up script.

**Comment by heaths** [comment]
You can't always add environment variables to the environment, especially persistently. In Windows it's easy with setx. But that's doesn't affect the current process, so instead you set them like `$env:FOO="bar"`, but the pwsh.exe process that is running may not be the process that needs to be modified, like if someone is running the .ps1 from another shell like cmd (which is why the .cmd files were added - and eventually we wanted shebang scripts for other platforms). On linux, you can `export` variables easily enough and fairly consistently across most common shells, but depending on the shell, to persist the variables you need to modify different files. .profile is pretty commonly used by various shells, but isn't always processed depending on how the login session was created.

This is why @danieljurek and I decided to document how to do it - with copy-paste code that works in some cases (a tactic I "borrowed" from `docker-machine env`) - and let the developers decide 1) how to set them, 2) in which process, 3) whether to persist them, and 4) how to persist them.

Once we use the file-based approach we talked about long ago (but never had time to fully realize) this won't be a problem.

**Comment by danieljurek** [comment]
We have old guidelines for environment variables that don't mention prefixing with `AZURE_`. If we are in agreement I can move them over to specify the prefix of `AZURE_` (and call out that secret names don't need to start with `azure-` because it's mostly implied) 

Guidelines: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/2/Azure-DevOps-Pipeline-Guidance?anchor=environment-variables

Orthogonal to this, our general SDK guidelines also recommend prefixing with `AZURE_`
> ✅ DO prefix Azure-specific environment variables with `AZURE_`.
https://azure.github.io/azure-sdk/general_azurecore.html#global-configuration-1

**Comment by heaths** [comment]
Who's on point to resolve this?

**Comment by pakrym** [comment]
I said that we shouldn't break other languages and their tests that don't know about automatic prefixes.

**Comment by heaths** [comment]
Your change was recent. How many could that be? We could work with other languages to update their test frameworks as you have been with .NET.

**Comment by pakrym** [comment]
Every single variable they use if we start prefixing all of them automatically.

My change didn't affect any existing variables in non .NET tests.

**Comment by heaths** [comment]
They were all authored before. You changed that to dump a bunch more variables (needed or not) without the old prefixes. Code changes in .NET were needed to accommodate. So if you change the prefix on variables you now dump automatically, how is that going to change other languages' tests that weren't using these new ones you just created?

**Comment by pakrym** [comment]
Changing the prefix only on those doesn't make sense, we need to change it for all the variables including the template outputs, otherwise it's would be as inconsistent as before.

**Comment by heaths** [comment]
Agreed. It wasn't clear you were referring to output variables in ARM templates.

**Comment by pakrym** [comment]
And I wouldn't do "AZURE_" because that conflicts with existing non-test variables, rather something like "TEST_".

**Comment by heaths** [comment]
As @danieljurek pointed out, that is the guidelines. Could be AZURE_TEST_. It's long, but recognizable and non-conflicting. I'd rather them be as specific as necessary so it makes it easy to identify and clean up.

**Comment by pakrym** [comment]
Guidelines are for variables read by client libraries not for test infrastructure, so they don't apply here.

You yourself gave an example of `dir env:AZURE* | del` that would remove non-test variables if customers run it.

**Comment by heaths** [comment]
Yes, because keeping secrets is more important. You're also assuming they created the ClientSecretCredential env vars for more than testing. With the updates to DefaultAzureCredential - and even that is supported the interactive browser credential before - when possible it's easier to use that. Now that it supports VS and the CLI (at least as a preview), having non-test env vars is even less likely. I only created my env vars to run tests. I use device codes for az CLI and PowerShell mods.

**Comment by weshaggard** [comment]
I also think we shouldn't use AZURE_ but have some thing about this being for testing. Maybe we do something like AZTEST_

**Comment by kurtzeborn** [comment]
This is done.  It created another problem because we settled on a service directory name convention.  There are other issues tracking further updates to this.
