### ISSUE TITLE
Typo in Onboard APEX Product

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5250]
Typo: management

<img width="960" alt="image" src="https://user-images.githubusercontent.com/9868623/215173353-5c2e2ee0-f532-41fd-af82-cd005037a155.png">

**Comment by live1206** [comment]
Fix deployed in Prod
![image](https://user-images.githubusercontent.com/5196139/220589640-c0d3d1b7-5f1e-4217-a61d-0c43a3d0359b.png)
