### ISSUE TITLE
Update ALL release planner onboarding email templates 

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5252]
See below email. The links to `Schedule a Data Plane Informational meeting` and `Schedule an Azure SDK Q&A meeting` are pointing to Bookings instead of the Scheduler tool.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/9868623/215176734-be753d70-3aaa-42ca-87a5-b89ad30a0df2.png">

@ladonnaq These should be changed. Right?

**Comment by ladonnaq** [comment]
All of the Release Planner automated emails have the old bookings link and the old email address.  

- [ ] Email should be the email address we are copying in the email, which is azsdkapex@microsoft.com. 

- [ ] The scheduling tool aka for the Informational Meeting is https://aka.ms/azsdk/scheduleinformational. 

If the release planner data shows that the product data plane scope is "Yes" or "Unsure":

- [ ] The scheduling tool should be linking to the info related to data plane info meeting type - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/663/Azure-SDK-Informational-Meeting-Data-Plane-Follow-Up.  
- [ ] The email body should also point to the Azure SDK Meeting Data Plane Follow-up wiki page too (for more information). 

Is there a way that I can view all of the automated emails?  They will all need updated. For example, the resource section.  We can probably eliminate that section when we begin using the Release Planner for management plane (the release app should provide the resources in context).

**Comment by live1206** [comment]
> * [ ]  Email should be the email address we are copying in the email, which is [azsdkapex@microsoft.com](mailto:azsdkapex@microsoft.com).

This has been fixed in https://github.com/Azure/azure-sdk-tools/issues/5158。 @ladonnaq Do you still see the wrong one?
> * [ ]  The scheduling tool aka for the Informational Meeting is https://aka.ms/azsdk/scheduleinformational.
 
The information meeting URL should vary in different environments.
> If the release planner data shows that the product data plane scope is "Yes" or "Unsure":
> 
> * [ ]  The scheduling tool should be linking to the info related to data plane info meeting type - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/663/Azure-SDK-Informational-Meeting-Data-Plane-Follow-Up.
> * [ ]  The email body should also point to the Azure SDK Meeting Data Plane Follow-up wiki page too (for more information).

Just want to mention, if we use the wiki page then in all environments it will point to Scheduler App of Prod in the wiki. And also, should we use AKA link in the wiki instead of the specific app URL?
> Is there a way that I can view all of the automated emails? They will all need updated. For example, the resource section. We can probably eliminate that section when we begin using the Release Planner for management plane (the release app should provide the resources in context).

Not sure about your intension here. Like try all different scenarios in PPE and check the auto sent mails?

**Comment by live1206** [comment]
Informational meeting link updated and deployed to PPE.

@ladonnaq I will hold the change to wiki because of the environment-related url for scheduler app.

**Comment by maririos** [comment]
> Informational meeting link updated and deployed to PPE.

@live1206  you mean we will always point to Prod? do you want me to create aka links per environment so you can reference those?

>Not sure about your intension here. Like try all different scenarios in PPE and check the auto sent mails?

I was talking with La Donna and what she wants is to see all the email templates the toolis currently generating so she can review them and approve them. You could either trigger them all and CC her or you could just share the individual templates and the conditions.

> If the release planner data shows that the product data plane scope is "Yes" or "Unsure":
> 
> * [ ]  The scheduling tool should be linking to the info related to data plane info meeting type - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/663/Azure-SDK-Informational-Meeting-Data-Plane-Follow-Up.
> * [ ]  The email body should also point to the Azure SDK Meeting Data Plane Follow-up wiki page too (for more information).

@ladonnaq  do you mean to have this information displayed in the Scheduled meeting? like in the body of the meeting?

**Comment by live1206** [comment]
> Informational meeting link updated and deployed to PPE.
> @live1206 you mean we will always point to Prod? do you want me to create aka links per environment so you can reference those?

@maririos No, the scheduler app URL is fetched from environment variable based on different environments.

**Comment by live1206** [comment]
>>Not sure about your intension here. Like try all different scenarios in PPE and check the auto sent mails?

>I was talking with La Donna and what she wants is to see all the email templates the toolis currently generating so she can review them and approve them. You could either trigger them all and CC her or you could just share the individual templates and the conditions.

@ladonnaq I have forwarded all 5 kinds of emails to you, please help check if anything is unexpected. Thanks!

**Comment by live1206** [comment]
The original fix is deployed to Prod, close this item.
@ladonnaq Feel free to re-open it or raise a new one if you found something else.
