### ISSUE TITLE
Update Azure-SDK-APEX-launch-readiness-criteria wiki links to use the Scheduler tool

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5253]
[This wiki](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/681/Azure-SDK-APEX-launch-readiness-criteria) contains links to bookings for scheduling a Data Plane information meeting. They should be changed to use the Scheduler Tool.

**Comment by ladonnaq** [comment]
@maririos This is the aka on the wiki link above - https://aka.ms/sdk-apex. (which now directs to the Release Planner). I updated it the link to use this aka - https://aka.ms/azsdk/scheduleinformational.

**Comment by maririos** [comment]
Nice. thank you!
