### ISSUE TITLE
Feedback Define SDK Release Date

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5257]
Typos:
- .NET
- Release

Lead time: the API approval is only for GA SDKs, so we should only include that information when the release plan is targeting an SDK GA release

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/9868623/215211291-fc3c25ac-7dad-4ffd-9e36-63268d703784.png">

**Comment by zzvswxy** [comment]
> Typos:
> 
> * .NET
> * Release

done in Dev env

**Comment by zzvswxy** [comment]
> Lead time: the API approval is only for GA SDKs, so we should only include that information when the release plan is targeting an SDK GA release

I was told that both SDK first beta and first GA release are need apiview review. But PM need more discuss about this. If there are any update, I will update in this issues.

**Comment by zzvswxy** [comment]
> Lead time: the API approval is only for GA SDKs, so we should only include that information when the release plan is targeting an SDK GA release

Only when service team choose and generate SDK PR then we can detect whether the xx language SDK is first beta/GA.

**Comment by zzvswxy** [comment]
deployed to Prod
