### ISSUE TITLE
Swagger breaking change should allow no-version-change for changes to /dev directory

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#5264]
Some teams, such as Cognitive Services, have started using the /dev directory in azure-rest-api-specs for development versions of their REST API prior to merging into "specifications". This development version is often updated multiple times -- keeping the api-version the same. This is expected and should not be flagged as an error by the azure-rest-api-specs PR checks.

The Swagger Breaking Change PR check is reporting changes made to the /dev directory without an api-version change as errors, e.g. in [PR 22132](https://github.com/Azure/azure-rest-api-specs/pull/22132/checks?check_run_id=10739794595).

**Comment by maririos** [comment]
@mikekistler could you point me to the documentation for the structure of the repo and how service team should take advantage of it?

**Comment by raych1** [comment]
@jianyexi , is there any change to make for 'dev' folder experience?  I think it should take latest preview version and stable version from main branch as base version for comparison, right?

**Comment by konrad-jamrozik** [comment]
@heaths is this still applicable or not? Given that we moved to TypeSpec.

**Comment by heaths** [comment]
It's still relevant in general, but not necessarily for dev/. We're not going to onboard any more teams to that since the conceptual idea went into TypeSpec's file organization, but it still applies that we don't want required validation errors on breaking changes to the same version for a feature or release branch. I've been talking with @maririos, @weshaggard, and others about that. Not sure if that's captured in another issue currently, though.

**Comment by konrad-jamrozik** [comment]
@heaths got it. I will close this work item. If we could find an example incorrect `no-version-change` breaking change that would help. But I think what you are saying may be already covered by the following issue, or one of the issues it links to:

- https://github.com/Azure/azure-sdk-tools/issues/5943

**Comment by konrad-jamrozik** [comment]
> > @heaths got it. I will close this work item. If we could find an example incorrect `no-version-change` breaking change that would help. But I think what you are saying may be already covered by the following issue, or one of the issues it links to:
> > 
> > * [ShiftLeft breaking change process on azure-rest-api-specs-pr is confusing and noisy #5943](https://github.com/Azure/azure-sdk-tools/issues/5943)
> 
> There are very often examples. Here's a recent one where Cognitive changed definitions in a release branch that hadn't yet merged to main: https://github.com/Azure/azure-rest-api-specs/pull/23020/checks?check_run_id=12598654533. Some of the breaking changes were not in the previous GA(s).

OK cool, I added this to:

- https://github.com/Azure/azure-sdk-tools/issues/5838
