### ISSUE TITLE
Usage of API Spec PR during onboarding

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#5267]
We ask user to fill in API Spec PR for data-plane and management-plane during onboarding.
The PR should be used for association during API Readiness App.

**Comment by ladonnaq** [comment]
We should update the Azure Devops field with a link to the PR that is provided.  Service partner's should be onboarding while In Dev with target lifecycle "Private Preview" so the release plan should be for private preview. This should be okay as long as we migrate all active APEX onboard work items - https://github.com/Azure/azure-sdk-tools/issues/4600.  

- [ ] Management plane field (Private Preview) 

![image](https://user-images.githubusercontent.com/67656762/215510007-3c3c17d0-1d6d-40d1-ba74-1d2ca38f9046.png)

- [ ] Data plane field (Private Preview) 
![image](https://user-images.githubusercontent.com/67656762/215510335-a6f950cc-62e1-4144-9fb9-f51ce22daeba.png)

**Comment by maririos** [comment]
@live1206 if we make sure that the ADO item alwasy has the latest PR links for management and data plane both tools (Release planner+ and scheduler tool) could query ADO.

**Comment by live1206** [comment]
> @live1206 if we make sure that the ADO item alwasy has the latest PR links for management and data plane both tools (Release planner+ and scheduler tool) could query ADO.

We store PR for management-plane and data-plane in Dataverse not ADO, basically the PR is tied to the created release plan, not the product.

During onboarding, we filled in swagger PR for management-plane and data-plane already.

**Comment by maririos** [comment]
Thanks for clarifying @live1206 . I see we are talking about 2 things. 
This issue is to make sure we reuse the information the user gave us when onboarding, so use those PRs in the "associate" step.

Seems like @ladonnaq  is also asking to save the PR information into the ADO item. am I reading this right? and if so, La Donna how do we address the concerns Wei expressed about multiple PRs and managing different Release Plans per Product?

**Comment by live1206** [comment]
@ladonnaq 
For management-plane, we have set `Swagger PR Link` in ADO already.
But for data-plane, we used another field as below based on previous design, what's the differences between them? Shall we update to use `Private Preview API PR` instead? 
![image](https://user-images.githubusercontent.com/5196139/217424580-21945703-defe-4990-89ee-401f29c1afbb.png)

**Comment by live1206** [comment]
While user submit onboarding questionnaire, we only store PRs for management-plane and data-plane in ADO not dataverse.
It's strange to read them again from ADO while needed in API Readiness App, we can just store them with `Product Profile` in dataverse.

**Comment by live1206** [comment]
PR association Implemented and deployed to Prod.
