### ISSUE TITLE
Don't add "customer-reported" label in internal repos

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#5268]
It appears that the "msft bot" adds the "customer-reported" label even on internal repos -- or did as recently as Sept 20, 2022 -- as can be seen in [azure-reset-api-specs-pr PR 8888](https://github.com/Azure/azure-rest-api-specs-pr/pull/8888):

<img width="556" alt="image" src="https://user-images.githubusercontent.com/85643503/215332716-355ea818-d4a0-4b7d-9fd9-ce9e9776598c.png">

Since customers have no access to internal repos there can be no customer reported issues or PRs in them, so this function should be disabled for internal repos.

**Comment by kurtzeborn** [comment]
@JimSuplizio, after you're done with the transition away from FabricBot, fixing this issue will probably amount to a config setting in private repos.

**Comment by JimSuplizio** [comment]
@mikekistler, this isn't a problem with the rules, this is a problem with your Azure Org visiblity.
<img width="531" alt="image" src="https://user-images.githubusercontent.com/13556087/236538095-0cc20ac3-26da-48b0-8fc5-f1082627bc72.png">
As [documented ](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/67/Permissions?anchor=i%27m-a-developer-within-a-partner-team-contributing-to-the-azure-sdk) your Azure org needs to be public not private. The reason you're seeing this label is the GitHub API that checks Azure membership will return false if you're a private member and add this label. Please change your visibility.

//CC @kurtzeborn

**Comment by mikekistler** [comment]
@JimSuplizio Maybe the question here is what "customer-reported" means. I took it to mean that the PR or issue was opened by a Microsoft customer -- someone outside of Microsoft. Is that correct or does it mean something different?

BTW, there is no description on this label in the repo, so if it does mean something different I think we should add a description to make that clear.

**Comment by mikekistler** [comment]
Reopening and adding to Specs PR Tools project.

**Comment by jsquire** [comment]
@mikekistler : For the purposes of issue management, a person is considered a "customer" if they are not a public member of the Azure organization and do not have contributor rights to our repositories.  The label is informational and has no impact outside of how our SLA metrics are calculated.

The bot makes this decision based on limitations of the GitHub API.  GitHub does not have the ability to check "is this person a Microsoft employee" nor "is this person an Azure employee."   The closest that it can come is to validate GitHub organization memberships and rights to the repository.   As Jim mentioned, for the GitHub API to see membership in an organization, it must be marked as public on your GitHub profile.

_**As part of onboarding to the Azure SDK, it is expected that partners and our internal team members join the GitHub Azure organization and configure it to be publicly visible on their profile.  This is documented on the onboarding guides that Jim linked as well as our Azure SDK team onboarding materials.   If that process is being followed, the "customer-reported" label will not be applied to issues and pull requests.**_

The "customer-reported" label is applied as part of the automated triage process and isn't something that can be toggled on or off per repository individually.  Given that it causes no ill effects, I don't see justification to invest in restructuring how the triage rule operates nor creating a parallel triage rule for the specs/internal repositories that doesn't apply the label.   

You may decide to disable issue triage entirely, which would avoid the "customer-reported" label as well as "needs-triage" and automated assignments.  I'm going to close this out as it isn't something that we plan on moving forward with at present.

**Comment by mikekistler** [comment]
Thanks Jesse. I personally see no value in labelling issues or PRs in the internal repo as "customer-reported". So I recommend that we disable automated triage for these repos.  Do you want me to open a separate issue for this?

**Comment by jsquire** [comment]
I've no issue with that - but I would like to know who is on the hook for triaging issues for those repositories and ensure that we get their buy-in.


@ronniegeraghty:  Any concerns about the lack of standard triage+labels in the specs repos from a reporting and metrics point of view?

**Comment by ronniegeraghty** [comment]
@jsquire, you're talking about the azure-rest-api-specs-pr repo right? Cause the azure-rest-api-specs repo is public and customers to create issues on it.

**Comment by mikekistler** [comment]
Yes, the repo in question is azure-rest-api-specs-pr.

**Comment by ronniegeraghty** [comment]
Then, no concerns since it's a private repo.

**Comment by jsquire** [comment]
Unexpectedly, it looks like the Specs PR repo is still running FabricBot.   I've opened [#12859](https://github.com/Azure/azure-rest-api-specs-pr/pull/12859) to stop `customer-reported` from being added to issues and pull requests.   Once we change over to JimBot, we'll need to remember to turn off the "Initial Triage" rule entirely.

//fyi: @JimSuplizio
