### ISSUE TITLE
Onboard screen - select an SDK dropdown box improvements 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5269]
Onboard screen, improve the select an SDK dropdown box experience. 

- [x] Filtering option 
- [ ] Map the product + service to the SDK packages selected 
- [x] How does this map to the Inventory Dashboard data?  
- [x] Add checkbox for user to identify that there are no existing SDKs.  Right now a user can skip selecting SDKs but we don't know if that is because there are none, they don't know, they can't find what they are looking for in the list, etc.

**Comment by ladonnaq** [comment]
**Discussion from email thread related to @maririos testing of release planner app for Cadl + DPG:** 

- (Mariana) For the SDK package release dropdown, where is the list coming from? How do we filter or make relationship between product name and SDK package name?

- (Wei) The list are from [azure-sdk/_data/releases/latest at main · Azure/azure-sdk (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk%2Ftree%2Fmain%2F_data%2Freleases%2Flatest&data=05%7C01%7Cladonnaquinn%40microsoft.com%7Cd312359709d64e4a000208db02c321e0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638106809357001176%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tFeOuAmgRpSHXFORx98p3unc0hiiVPmxnMtCUT7Ux8U%3D&reserved=0). No filtering for now. 

- (La Donna) We should start to map the packages to the product/service. We should also add a checkbox or something for the user to identify that there are no existing SDKs. Right now the user is not required to choose an existing SDK package so if they leave it blank we don’t know why.  The logic of figuring out new service/new engagement is if there are no existing SDKs packages.

**Comment by maririos** [comment]
> (Wei) The list are from [azure-sdk/_data/releases/latest at main · Azure/azure-sdk (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-sdk%2Ftree%2Fmain%2F_data%2Freleases%2Flatest&data=05%7C01%7Cladonnaquinn%40microsoft.com%7Cd312359709d64e4a000208db02c321e0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638106809357001176%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tFeOuAmgRpSHXFORx98p3unc0hiiVPmxnMtCUT7Ux8U%3D&reserved=0). No filtering for now.

@ladonnaq Is this list the same that Ronnie and PM team have been working on?

**Comment by live1206** [comment]
@ladonnaq Could you set the priority of this task? Is it blocking the data-plane onboarding?

**Comment by maririos** [comment]
We have removed the SDK dropdown from the onboarding screen. Instead we ask if there is an existing SDK.
We manage SDK information in the SDK Release apps
