### ISSUE TITLE
Add support for private spec repo in cadl project scripts

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#5275]
Today the Cadl-Project-Sync.ps1 script works with public or private repo but for private repo it only works locally.  We need to add support for token auth in order for the CI to be able to work as well.

**Comment by raych1** [comment]
@chunyu3 , should this task be assigned to you?

**Comment by m-nash** [comment]
Any of the emitter language teams can pick this up as it will be shared between all of us.

**Comment by konrad-jamrozik** [comment]
@weshaggard should it be labelled `SDK Automation` instead, like this one?
- https://github.com/Azure/azure-sdk-tools/issues/5530

**Comment by raych1** [comment]
This has been taken care of by tsp-client.
