### ISSUE TITLE
UX design pattern: Typography updates

### ISSUE THREAD

**Issue by ccbarragan** [Azure/azure-sdk-tools#5279]
## Description

UX refresh for Release Planner typography styles. All Release Planner screens should be updated to follow the latest design patterns. Part of https://github.com/Azure/azure-sdk-tools/issues/5631.

>To see how these styles look in Power Apps, check out the [UX Release Planner prototype](https://apps.powerapps.com/play/e/ca95f761-477a-4e98-b34e-dfd5dd03a770/a/ece65a45-f966-4d8b-b04a-24329c5b8e99?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47). Recommend using the prototype to copy over components or as a general design guide for implementing these patterns.

### Typography specs

All UI content uses the **Segoe UI** font family (unless specified otherwise). All sizes are in point (`pt`) sizes to match what's supported in Power Apps.

<details>
<summary><strong>App name</strong></summary>

#### App name + header text

![Example](https://user-images.githubusercontent.com/28902259/215641174-cbc69c0c-6bc6-448b-a291-ca8688615b17.png)

The text in the header of the app is used to help users orient themselves in the app experience. Header text can be used in Semibold or Regular weights to help distinguish content.

1. App name (required):
    - Font: Segoe UI
     - Font weight: Semibold (600)
    - Font size: 10pt
    - HEX color: `#FFFFFF`

2. App label (optional):
    - Font: Segoe UI
    - Font weight: Semibold (600)
    - Font size: 10pt
    - HEX color: `#C7E0F4`

3. Service picker:
    - Font: Segoe UI
    - Font weight: Regular (600)
    - Font size: 7.5pt (for 'Service'), 9pt (for service name)
    - HEX color: `#FFFFFF`

</details>

<details>
<summary><strong>Page titles</strong></summary>

#### Page titles

![header](https://user-images.githubusercontent.com/28902259/215642825-69a0d851-44d2-4693-8209-27af510f57fc.png)

Page titles are used to introduce a body of content. They're used at the top of page layouts and side panels.

- Font: Segoe UI
- Font weight: Semibold (600)
- Font size: 15pt
- HEX color: `#242424`

</details>

<details>
<summary><strong>Subtitles</strong></summary>

#### Page subtitles

![subtitle](https://user-images.githubusercontent.com/28902259/215642887-04a7fe2a-7b28-428f-a9c3-13a899fcf5aa.png)

A subtitle can be paired with a title to provide additional context. 

- Font: Segoe UI
- Font weight: Regular (400)
- Font size: 11pt
- HEX color: `#424242`

>Note: The main difference between a subtitle and body text is that the color styling is a little bit different.

</details>

<details><summary><strong>Body text</strong></summary>

#### Body text

![body](https://user-images.githubusercontent.com/28902259/215643552-c8ced91f-d4c0-4c3a-8647-a8d5a00b4ef6.png)

**Default**. Body text is the default and most frequently used style on an page. It is used for navigation menu items, labels for input fields, table column headers, table body text, and more. Body can be used in Semibold or Regular weights to help separate content.

- Font: Segoe UI
- Font weight: Regular (400)
- Font size: 11pt
- HEX color: `#242424`

#### Examples

</details>

<details><summary><strong>Captions</strong></summary>

### Captions

![captions](https://user-images.githubusercontent.com/28902259/215645244-3320aa2e-428c-4774-ab51-934fb24bf5c9.png)

Captions are used sparingly, often to show metadata, to pair with images, or when there's limited space. Captions can be used in cards and as part of table cell content.

- Font: Segoe UI
- Font weight: Regular (400)
- Font size: 9pt
- HEX color: `#616161`

</details>

### Other

<details><summary><strong>Dividers</strong></summary>

### Dividers

Dividers are horizontal or vertical lines that separate a content block from another. 

- HEX color: `#E0E0E0`

</details>

**Comment by JonathanCrd** [comment]
I would love to hear your thoughts on our options. This is related to https://github.com/Azure/azure-sdk-tools/issues/5280 too

**Comment by ccbarragan** [comment]
@JonathanCrd Super appreciate the thorough investigation into this! It looks like option 1 might be the best option at the moment that doesn't require redoing the entire apps. Bummer though that the theming can't be applied globally across all apps.

Out of curiosity, did you also investigate coded components and [React / platform library](https://learn.microsoft.com/en-us/power-apps/developer/component-framework/react-controls-platform-libraries#supported-platform-libraries-list) options for Canvas apps? If we could pull in [Fluent React components](https://fluent2.microsoft.design/components/web/react), it could mean a serious opportunity to decrease repeated work across design and engineering in the future (all new designs for Release Planner are based on the Fluent design system). Fonts, colors, and general styling are baked into the Fluent React components using [design tokens](https://fluent2.microsoft.design/design-tokens) by default, so there wouldn't be a need for handwritten stylesheets across apps. Worth noting especially is that Fluent components meet or surpass WCAG 2.1 AA standards for accessibility. 

For general Fluent theming and styling, another cool thing to consider might be the [Fluent Creator Kit for Power Apps](https://powerapps.microsoft.com/en-us/blog/introducing-the-creator-kit-efficiently-create-performant-fluent-ui-based-power-apps/) -- it has Fluent styling (fonts + colors) already built-in. 

I'm cool with whichever approach would be best for the team right now ❤️ We typically highly recommend leveraging an existing Fluent component library for general accessibility and scalability, but I suspect that using Fluent coded components with our apps right now would basically mean redoing most screens + logic as you mentioned above.

**Comment by ccbarragan** [comment]
@JonathanCrd Any updates or progress made on this issue?

**Comment by JonathanCrd** [comment]
New UI for the Release Planner has been implemented following these patterns.

It was not possible to specify a global theme, instead, each control was replaced or modify to meet the specified requirements here.
