### ISSUE TITLE
UX design pattern: Layout and navigation updates

### ISSUE THREAD

**Issue by ccbarragan** [Azure/azure-sdk-tools#5280]
## Description

UX refresh for Release Planner navigation and page layout structure. All Release Planner screens should be updated to follow the latest design patterns. Part of https://github.com/Azure/azure-sdk-tools/issues/5631.

>**Sizes indicated below are in pixels.** Power Apps uses points instead of pixels so it's not a 1:1 conversion 😢. For a quick comparison, check out the [Power Apps UX Release Planner prototype](https://apps.powerapps.com/play/e/ca95f761-477a-4e98-b34e-dfd5dd03a770/a/ece65a45-f966-4d8b-b04a-24329c5b8e99?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47). Recommend using the prototype to copy over components or as a general design guide for implementing these patterns.

#### Header

![CleanShot 2023-01-30 at 19 14 26](https://user-images.githubusercontent.com/28902259/215633873-238fba74-0115-43d8-9013-230d040b1983.png)
>:point_right: [Link to design spec](https://www.figma.com/file/3o7CN47eJShB8DdHFZ00cw/Azure-SDK-Release-Planner?node-id=769%3A165142)

#### Basic page layout

![CleanShot 2023-01-30 at 19 18 11](https://user-images.githubusercontent.com/28902259/215634496-bbb5567e-8b45-45b3-85e2-042844ef1c6c.png)

>:point_right: [Link to design spec ](https://www.figma.com/file/3o7CN47eJShB8DdHFZ00cw/Azure-SDK-Release-Planner?node-id=769%3A167225)

**Comment by live1206** [comment]
For Canvas App, there is no global way to apply custom template or theme.
