### ISSUE TITLE
Pipeline results missing for PR of forked repo

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#5282]
Right now, OpenAPI hub does not support to create PR for forked repo branch anymore, but the user can still manually create them.
Release Planner App could not get pipeline results of these PR now, which should be supported.
Example PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/10480

**Comment by live1206** [comment]
Initial though is to fetch CI results from DB via PR id.

**Comment by ladonnaq** [comment]
I am seeing this error in PPE (Beta 3).  Is this error related to this issue or is it something different? 

![image](https://user-images.githubusercontent.com/67656762/216369600-c2585933-032b-4480-af26-b2425b9acf29.png)

**Comment by ladonnaq** [comment]
@live1206 is this resolved in PPE?  This is blocking me from starting to pilot the Release Planner for management plane.  If it is fixed in PPE, I want to test it.

**Comment by live1206** [comment]
@ladonnaq It's done in Dev, not in PPE yet, we will deploy it during the day today.

**Comment by live1206** [comment]
@ladonnaq Fixed in PPE

**Comment by ladonnaq** [comment]
> @ladonnaq Fixed in PPE

Thanks I will test tomorrow.  If testing is successful using the PRs that service teams have given me, I will let you know. Then can be promote to PROD.  I think that management could be used sooner by teams even without the new UI if unblocked by this issue.
