### ISSUE TITLE
API review is empty for JS 

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5287]
API extractor output file JSON has different schema than the one expected by parser. Currently API parser for JS does not process namespace token so it ignores any children under namesapce token. Parser expects Interface/class/struct as first level token kind to generate API review. 

We should support creating API review when interface/class are within a namespace as well.

**Comment by lirenhe** [comment]
@praveenkuttappan,  I saw this issue was added into backlog but it may impact the arch board review for DPG services.
We may also use multi-client in OpenAI service in the near future.
I added ‘DPG impact’ lable and  could you work on it with high priority?  Thanks. 

cc @maririos

**Comment by praveenkuttappan** [comment]
@lirenhe I have already submitted a PR to resolve this and it's merged. It will soon get released and deployed to production.
https://github.com/Azure/azure-sdk-tools/pull/5292

**Comment by MaryGao** [comment]
@praveenkuttappan I notice that all tokens under namespaces are `un-clickable` do you know how to fix it?

More details: https://github.com/Azure/azure-sdk-tools/pull/5292#issuecomment-1412190637
