### ISSUE TITLE
[FEATURE REQ] Add support for a local repo in the cadl scripts

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#5288]
There are two ways to refer to the cadl files. One is a remote git url, the other is the local file path. In the cadl-location.yaml, you can provide (repo, commit) to indicate an remote URL of the cadl, then cadl-project-sync.ps1 will sparse-checkout the cadl folder. Also you can provide a local swagger repo folder via spec-root-dir, cadl-project-sync.ps1 just copy cadl filed to the TempCadlFiles.

previous comments for context
https://github.com/Azure/azure-sdk-tools/pull/5272#discussion_r1091364117
https://github.com/Azure/azure-sdk-tools/pull/5272#discussion_r1092234754

**Comment by tg-msft** [comment]
+1 for this feature.  It's a showstopper for iterative Cadl development if I can't see what the C# API will look like without committing and pushing a draft spec every time I make a small adjustment.

**Comment by m-nash** [comment]
@tg-msft  you can do this today (although one check in is needed).  If you add `cleanup: false` to your cadl-location.yaml it will leave the `TempCadlFiles` in place in your project directory.  You can then cd into there and make any local changes to the cadl directly that you want and then simply rerun the cadl compile command from within that directory

**Comment by mikekistler** [comment]
Our understanding is that the request is to use a local specs repo that is already present rather than sparse cloning the relevant path from the specs repo.

**Comment by raych1** [comment]
Talked to @chunyu3, this is already supported. Can you link the code location here?

**Comment by chunyu3** [comment]
> Our understanding is that the request is to use a local specs repo that is already present rather than sparse cloning the relevant path from the specs repo.

If you want to use a local specs repo that is already present, you can specify `spec-root-dir` to provide the path of the root directory of the specs repo, e.g. /home/azure-rest-api-specs, and don't provide the `commit` and `repo`.

**Comment by weshaggard** [comment]
@chunyu3 unless I'm missing something wouldn't someone need to manually change their cadl-location.yaml file to set that directory? https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Cadl-Project-Sync.ps1#L117 Ideally, we would support such flags with whatever root script we expect folks to use.

**Comment by m-nash** [comment]
It looks like I accidentally left some of the old code that pulled this from cadl-location.yaml which should be removed.  This feature should be a temporary flag passed in as we would never expect a cadl-location.yaml to be checked in with this setting.

We need to think very carefully about this feature as it opens a pathway for developing that can easily conflict once you get into CI and it won't be very obvious why things worked locally but don't work in the CI.

**Comment by konrad-jamrozik** [comment]
@weshaggard should it be labelled `sdk-automation` instead, like this one?
- https://github.com/Azure/azure-sdk-tools/issues/5530
