### ISSUE TITLE
Don't allow user to change Product once a meeting has been scheduled

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#5295]
Follow up of: https://github.com/Azure/azure-sdk-tools/issues/4681#issuecomment-1404272232

**The update scenarios are still ambiguous:**
- [ ] Adding a Product when updating a meeting updates the ADO Work Item field to "Scheduled"?
- [ ] Changing a product to another when updating a meeting... ???
- [ ] Removing a product when updating a meeting... ???

Going back to:
> I don't think that the user should be able to change the product name once the meeting is scheduled. Especially in this scenario where the info meeting is triggered during using the release planner to onboard a new product in scope for APEX.

Then, should we not allow the users to update the product selection once they specified one? Or should we not allow them to edit the product at any time, even if they didn't specify one when creating the meeting?

**Comment by JonathanCrd** [comment]
@ladonnaq could you clarify what's the expected behaviour on the app when a user wants to update the product information? And if it does that, what should happen on the ADO work item?

You can take a look at #4681 for the context and the ongoing discussion.

**Comment by maririos** [comment]
After meeting with @ladonnaq  de conclusion is to not allow the user to update the `Product` field once a meeting is created.
