### ISSUE TITLE
[JS Recording] Too many `/`s in the url - is it expected? or a bug?

### ISSUE THREAD

**Issue by HarshaNalluru** [Azure/azure-sdk-tools#5296]
interesting to see so many `/`s. /cc @HarshaNalluru @timovv

_Originally posted by @jeremymeng in https://github.com/Azure/azure-sdk-for-js/pull/24581#discussion_r1092590624_

In a particular recording in the JS repo for the package azure-developer-center, we see a mysterious URL with too many `/`s, curious about why that's the case.

It is a low priority as it is not blocking anyone yet, since the pipelines are green.

At a quick glance, it seems santizers/configs set on the recorder look simple and probably should not have caused this.

**Comment by scbedd** [comment]
Given that this doesn't happen in all cases, and very specifically happens on this test, I think that something is up with your input string or with the sanitizer config @HarshaNalluru .

I will note that `Info/Active` now allows you to see what is configured for an individual test, as long as you have a breakpoint in your runner before the test stops playback. I don't think there is a generic problem with sanitization.
