### ISSUE TITLE
Notify PM or SDK owner when not release some language SDK

### ISSUE THREAD

**Issue by zzvswxy** [Azure/azure-sdk-tools#5297]
Notify PM or SDK owner when service team chose not to release one or more languages SDK.
Currently we only record the reason in dataverse.
We should send an e-mail or record it in issue or some where.

**Comment by zzvswxy** [comment]
Hi @josefree , create an issue to track the requirement. We may need more discuss how to achieve it.

**Comment by maririos** [comment]
@ladonnaq who should we email? you if it is Data lane and Josephine if it is ARM?

**Comment by ladonnaq** [comment]
> @ladonnaq who should we email? you if it is Data lane and Josephine if it is ARM?

Just use the APEX group alias - azsdkapex@microsoft.com.  Then we will investigate and get Josephine or others involved if needed.

**Comment by ladonnaq** [comment]
I will review and look into the requirement for this in Feb 2024.  Sending email to the azsdkapex alias will be suitable.  Also, want to touch base with Josephine to see if she  would like to added to the alias.

**Comment by maririos** [comment]
I found official documentation for this process here: https://eng.ms/docs/products/azure-developer-experience/onboard/request-exception
@ladonnaq  could you follow up on this and make sure @josefree and you are in agreement?
Feel free to edit the documentation in case things change.

**Comment by maririos** [comment]
From  @josefree:

> Please select an appropriate reason for not utilizing the Azure SDK pipeline for the SDK release in a specific language.
We (the service owner) allocate resources to develop and deliver the SDK in the specific language manually.
We (the service owner) are assured that the service will not be used in a client environment involving the specific language.
Others, please specify________________

**Comment by praveenkuttappan** [comment]
> From [@josefree](https://github.com/josefree):
> 
> > Please select an appropriate reason for not utilizing the Azure SDK pipeline for the SDK release in a specific language.
> > We (the service owner) allocate resources to develop and deliver the SDK in the specific language manually.
> > We (the service owner) are assured that the service will not be used in a client environment involving the specific language.
> > Others, please specify________________

I assume we should ask only one attestation for all non-selected languages. We can send an email to [azsdkapex@microsoft.com](mailto:azsdkapex@microsoft.com) and other service partner parties involved in the release plan.

**Comment by praveenkuttappan** [comment]
One more question: @ladonnaq and @josefree Can you please confirm if we need this email notification for language exception change for both TypeSpec and OpenAPI based SDK release or only for TypeSpec?

**Comment by praveenkuttappan** [comment]
Solution:
1. Release planner will prompt user to attest the reason for no choosing a language if any tier 1 language is not selected.
2. Store this info in Dataverse table along with other information like release plan ID. Add a new column `Notified` in dataverse and set it to false for attestation records.
3. Create a cloud flow that gets triggered whenever there is a new attestation record **created**.
4. Cloud flow will process the attestation and send an email to [azsdkapex@microsoft.com](mailto:azsdkapex@microsoft.com) and other service partner parties and mark `notified` as processed.

**Comment by ladonnaq** [comment]
> One more question: [@ladonnaq](https://github.com/ladonnaq) and [@josefree](https://github.com/josefree) Can you please confirm if we need this email notification for language exception change for both TypeSpec and OpenAPI based SDK release or only for TypeSpec? We can remove language selection from current management plane SDK release request app and keep it uniform.

@praveenkuttappan - As I understand release plans for stable SDKs (generated using TypeSpec or OpenAPI) should include all tier 1 languages and if not, then it would be an exception requiring justification.  @josefree Is this your expectation?

**Comment by maririos** [comment]
Done in Dev for management plane app

**Comment by maririos** [comment]
@ladonnaq is the process the same for data plane? same email template and everything?

**Comment by ladonnaq** [comment]
The SDK policies published on GitHub show inconsistencies between the language requirements for Beta and Stable SDKs.  I highlighted the relevant content in the screenshot below. 

![Image](https://github.com/user-attachments/assets/130fcd9d-0f1f-41ce-902c-6afd92f40027)

It is illogical to require only two languages for Beta SDKs while mandating support for all tier-1 languages for Stable SDKs. Additionally, the APEX requirements for Beta SDKs mandate the release in all tier-1 languages.

I recommend updating the Beta SDK policies to require support for all tier-1 languages. If a Service team needs to stagger the language releases due to time constraints, they can request an exception. We will then use a different release plan to track and ensure the requirement is met.

Once the policy is updated, we should be able to leverage the same UI, back-end, and email template. The email should go to the azsdkapex alias and probably the arch board help desk.

**Comment by maririos** [comment]
Data plane conversation moved to https://github.com/Azure/azure-sdk-tools/issues/9387
