### ISSUE TITLE
Swagger API review - Update failure reason as comment

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5300]
API review for swagger is generated from PR only if swagger files are present in README under the tag. Currently this causes issue when tag is missing in README and we skip swagger review gen in this case.

Swagger API review gen pipeline should be updated to provide more details about this failure and also update it back as a comment on PR so PR author can take necessary steps to resolve it.

**Comment by ruowan** [comment]
The error message is this:

![image](https://user-images.githubusercontent.com/52271048/216226682-ad8fb420-db97-4621-aea3-6669878b4c3c.png)

This issue is duplicated with https://github.com/Azure/azure-sdk-tools/issues/5156.

**Comment by ruowan** [comment]
Done. Already deployed.
