### ISSUE TITLE
Remove the SDK Release Plan Preview screen from Release

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5305]
Per feedback from service partners and stakeholders, please remove SDK Release Plan Preview from the Release Planner. 

![image](https://user-images.githubusercontent.com/67656762/216146388-0ba15b58-18eb-4503-a3ad-7b120747b3f1.png)

**Comment by JonathanCrd** [comment]
I have hidden that view from the user's. 
Now, the create button is displayed in the previous view, when selecting the SDK release plans to create.

I didn't removed the view entirely just for reference purposes.

**Comment by ladonnaq** [comment]
> I have hidden that view from the user's. Now, the create button is displayed in the previous view, when selecting the SDK release plans to create.
> 
> I didn't removed the view entirely just for reference purposes.

Thanks!

**Comment by JonathanCrd** [comment]
I forgot to add a loading screen at the end, it's done now
