### ISSUE TITLE
[PR Workflow] Pipeline improvements for `CI-NewRPNamespaceWithoutRPaaS`

### ISSUE THREAD

**Issue by bdefoy** [Azure/azure-sdk-tools#5311]
ARM reviewers should not review specs for RPs that are not onboarding to RPaaS unless they have been granted an exception. Please add these to the flow for the CI-NewRPNamespaceWithoutRPaaS label.

- [x] Do not allow WaitForARMFeedback to be added if CI-NewRPNamespaceWithoutRPaaS is present

Additionally, since we occasionally allow new RP namespaces for RPs that are not onboarding to RPaaS,

- [x] Add a label like "RPaaSException" that can be manually added and replaces/blocks the addition of CI-NewRPNamespaceWithoutRPaaS

So as to point people in the right direction when they need an RPaaS exception,

- [x] Append the below sentence to the message for CI-NewRPNamespaceWithoutRPaaS:
  > Otherwise, please see https://aka.ms/RPaaSException to discuss an exception.

  So, the message will look like this, for example:

  > Hi @bdefoy This PR was flagged for introducing a new RP namespace that is not being onboarded with [RPaaS](https://armwiki.azurewebsites.net/rpaas/overview.html). Merging this PR to the main branch will be blocked as RPaaS is required for new RPs. To resolve this and allow the PR to be merged into the main branch, please [use RPaaS to onboard the new RP](https://armwiki.azurewebsites.net/rpaas/gettingstarted.html). Otherwise, please see https://aka.ms/RPaaSException to discuss an exception.

[Related Teams post](https://teams.microsoft.com/l/message/19:78cd6c72c41240dc84a36523af60b88a@thread.tacv2/1684434068539?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0cab4ce9-7691-42ae-82e3-460d4346a710&parentMessageId=1684434068539&teamName=ARM%20API%20Reviewers&channelName=ARM%20swagger%20reviews&createdTime=1684434068539)

**Comment by rkmanda** [comment]
In addition also do not allow ARMSignedOff label to be added if CI-NewRPNamespaceWithoutRPaaS is present

**Comment by konrad-jamrozik** [comment]
Relevant discussion why this work is needed [here](https://teams.microsoft.com/l/message/19:78cd6c72c41240dc84a36523af60b88a@thread.tacv2/1684434068539?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0cab4ce9-7691-42ae-82e3-460d4346a710&parentMessageId=1684434068539&teamName=ARM%20API%20Reviewers&channelName=ARM%20swagger%20reviews&createdTime=1684434068539).

**Comment by konrad-jamrozik** [comment]
For this:

> Do not allow WaitForARMFeedback to be added if CI-NewRPNamespaceWithoutRPaaS is present

I don't think it is possible to prevent a label being added by a human. But we could:

- ensure all the automation we have doesn't add the label when it shouldn't
- if it detects it is added when it shouldn't, remove it.
  - We could add rules to [comment.yml](Do not allow WaitForARMFeedback to be added if CI-NewRPNamespaceWithoutRPaaS is present) that says "if label X and condition C holds, remove label X", but this will require dev work. For example, right now it is not possible to have more than one rule per given action type and label, as explained [in this comment](https://github.com/Azure/azure-rest-api-specs/pull/24083#discussion_r1201237226).
  - Alternatively, we could make changes in [processARMReview](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=public/rest-api-specs-scripts/src/prSummary.ts&version=GC02e956adcdd563ab5e0f43e60cf1cd259669cb85&line=491&lineStartColumn=24&lineEndColumn=24&_a=contents) or in a code close to it in execution change. This is also requires some dev work.

**Comment by konrad-jamrozik** [comment]
@rkmanda 

> Do not allow WaitForARMFeedback to be added if CI-NewRPNamespaceWithoutRPaaS is present

> In addition also do not allow ARMSignedOff label to be added if CI-NewRPNamespaceWithoutRPaaS is present

In such case, should the label `ARMChangesRequested` be added? We do have an invariant that says that if `ARMReview` label is present, then exactly one of these three labels should be present at all times: `ARMChangesRequested`, `WaitForARMFeedback`, `ARMSignedOff`.

**Comment by rkmanda** [comment]
yes ARMChangesRequested should be added

**Comment by konrad-jamrozik** [comment]
> yes ARMChangesRequested should be added

I will fix it in a future PR.

**Comment by konrad-jamrozik** [comment]
Bumped priority to `High` as @rkmanda is asking about it :)

**Comment by konrad-jamrozik** [comment]
Related bug:

- https://github.com/Azure/azure-sdk-tools/issues/6673

**Comment by konrad-jamrozik** [comment]
In my implementation here:

- [Pull Request 546923](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/546923): Improve ARM review labels flow + no longer fail Summary task; block PR appropriately instead

I made the label `CI-RpaaSRPNotInPrivateRepo` also block ARM review, the same as `CI-NewRPNamespaceWithoutRPaaS`. But while `CI-NewRPNamespaceWithoutRPaaS` can be suppressed with `RPaaSException`, the `CI-RpaaSRPNotInPrivateRepo` cannot.

Please see this PR to see what guidance we provide to the users when these labels appear:

- https://github.com/Azure/azure-rest-api-specs/pull/28858

**Comment by konrad-jamrozik** [comment]
Related future work:

- https://github.com/Azure/azure-sdk-tools/issues/6624
- https://github.com/Azure/azure-sdk-tools/issues/6684

**Comment by konrad-jamrozik** [comment]
Example:

- https://github.com/test-repo-billy/azure-rest-api-specs/pull/3339#issuecomment-2084515964

![image](https://github.com/Azure/azure-sdk-tools/assets/4429827/c67e193a-7326-45cd-a0d7-0f88ccd6d083)

**Comment by konrad-jamrozik** [comment]
Note I did not yet implement this:

> In addition also do not allow ARMSignedOff label to be added if CI-NewRPNamespaceWithoutRPaaS is present

Let's see how the new model works and if there is still need for this.

**Comment by konrad-jamrozik** [comment]
[Announcements on Teams](https://teams.microsoft.com/l/message/19:78cd6c72c41240dc84a36523af60b88a@thread.tacv2/1714516332780?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=0cab4ce9-7691-42ae-82e3-460d4346a710&parentMessageId=1714516332780&teamName=ARM%20API%20Reviewers&channelName=ARM%20swagger%20reviews&createdTime=1714516332780)
