### ISSUE TITLE
Cleanup Validation Errors - management plane API Readiness - no data shows up after PR associated

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5314]
Hello, I was testing in PPE using a new product which will be releasing initial beta SDKs for management and data plane.  

Here is the PR for management plane that I tried: 

- https://github.com/Azure/azure-rest-api-specs-pr/pull/9398 (Open)
- https://github.com/Azure/azure-rest-api-specs-pr/pull/10709 (Closed) 

Questions/Comments: 
1. If a user selects swagger earlier in the UI flow, why does this screen reference Cadl. This will be confusing to teams that are not using Cadl. We need to change the description based on if the user selected swagger or Cadl.  
2. All of the shows as unavailable.  Is there some issue with the PRs?  So far, I have not been able to see any data for any screens after a PR is associated.  I tried with a open PR and a closed PR.  Not sure what the behavior should be for closed or merged PR. I would think that the app can only read the data that was in the PR at the time it was closed or merged.  But open PR I would expect to see data. 

![image](https://user-images.githubusercontent.com/67656762/216201992-e823b80f-13f5-436d-a996-724a003b90cb.png)

**Comment by live1206** [comment]
@honghr Could you help take a look? Thanks!

**Comment by live1206** [comment]
> If a user selects swagger earlier in the UI flow, why does this screen reference Cadl. This will be confusing to teams that are not using Cadl. We need to change the description based on if the user selected swagger or Cadl.

This is a valid change, will get back to this with lower priority.

> All of the shows as unavailable. Is there some issue with the PRs? So far, I have not been able to see any data for any screens after a PR is associated. I tried with a open PR and a closed PR. Not sure what the behavior should be for closed or merged PR. I would think that the app can only read the data that was in the PR at the time it was closed or merged. But open PR I would expect to see data.

This will be resolved once we fix https://github.com/Azure/azure-sdk-tools/issues/5282

**Comment by ladonnaq** [comment]
Need to test to confirm resolved

**Comment by maririos** [comment]
@ladonnaq are you seeing that this is still hapenning?

**Comment by ladonnaq** [comment]
@maririos We can close this for now and re-open if we get any feedback that it is confusing.
