### ISSUE TITLE
No SDKs are showing up in the onboard dropdown box - management plane 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5317]
I was testing with a product that is associated with previously released SDKs  in PPE.  Here is filtered link to Azure SDK release page - https://azure.github.io/azure-sdk/?search=workload. 

- Nothing shows up the dropdown box.  It is confusing.  We should provide a message to make it clearer as to what we want the user to do.  I am not sure if I am supposed to enter a URL or what I am supposed to do if nothing shows up in the dropdown box. 
- Why is nothing showing up in the dropdown box?  The ARM namespaces exist and there are management libraries that have been released. 

https://github.com/Azure/azure-rest-api-specs-pr/pull/10974

![image](https://user-images.githubusercontent.com/67656762/216211958-0a92c313-a21e-4029-9960-f3150295b117.png)

**Comment by live1206** [comment]
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/5196139/216216262-6c66cefe-19ed-40de-8702-6b7e2784e66a.png">
The package list is available in PPE.

**Comment by live1206** [comment]
Duplicated with https://github.com/Azure/azure-sdk-tools/issues/5508#issuecomment-1439358878
