### ISSUE TITLE
Namespace review approval for new initial beta client and management libraries

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#5320]
- [ ] Like the one in management-plane
<img width="893" alt="image" src="https://user-images.githubusercontent.com/5196139/216227292-0f778001-42fe-4319-9014-e16050da5af2.png">

- [ ] Add check of namespace approval for both management-plane and data-plane, need to confirm if it's possible to get the namespace approval result from ApiView

**Comment by josefree** [comment]
This provides only linkage between the review ticket and the release plan.  Renhe also mentioned that there should be a check if the ticket is closed with approval before SDK release.  @ladonnaq it's not straightforward for system to recognize if the review request (with a GitHub issue) is closed with approval or disagreement.  Can we define some labels or pre-defined strings in comment to make it clear?

**Comment by live1206** [comment]
We should be able to leverage APIView to get the approval info.

**Comment by maririos** [comment]
I found documentation around it: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/429/Troubleshooting-Guide?anchor=automatic-review%3A-build-has-a-step-to-create-api-review-and-this-is-blocking-package-release

If you have questions about it, please ping Praveen

**Comment by maririos** [comment]
> @maririos  Do you mean there is a separate rest api to check whether the package name is approved or not? We have already integrated a rest api to check whether the apiview is approved or not. Are they the same rest api? cc: @praveenkuttappan

My understanding is that it is the same API as the API approval one. The response is what is different:
- 200 means both package name and API has been approved
- 201 means API is not approved
- 202 means package name is not approved

From: https://github.com/praveenkuttappan/azure-sdk-tools/blob/main/eng/common/scripts/Helpers/ApiView-Helpers.ps1#L41

**Comment by dw511214992** [comment]
> @dw511214992
> 
> > @maririos  Do you mean there is a separate rest api to check whether the package name is approved or not? We have already integrated a rest api to check whether the apiview is approved or not. Are they the same rest api? cc: @praveenkuttappan
> 
> My understanding is that it is the same API as the API approval one. The response is what is different:
> 
> * 200 means both package name and API has been approved
> * 201 means API is not approved
> * 202 means package name is not approved
> 
> From: https://github.com/praveenkuttappan/azure-sdk-tools/blob/main/eng/common/scripts/Helpers/ApiView-Helpers.ps1#L41

In this apiview: https://apiview.dev/Assemblies/Review/841c2923236647a6a7af567abbb3f40e, I get 202 response but the package name has been approved.

**Comment by praveenkuttappan** [comment]
> > @dw511214992
> > > @maririos  Do you mean there is a separate rest api to check whether the package name is approved or not? We have already integrated a rest api to check whether the apiview is approved or not. Are they the same rest api? cc: @praveenkuttappan
> > 
> > 
> > My understanding is that it is the same API as the API approval one. The response is what is different:
> > 
> > * 200 means both package name and API has been approved
> > * 201 means API is not approved
> > * 202 means package name is not approved
> > 
> > From: https://github.com/praveenkuttappan/azure-sdk-tools/blob/main/eng/common/scripts/Helpers/ApiView-Helpers.ps1#L41
> 
> @maririos @praveenkuttappan In this apiview: https://apiview.dev/Assemblies/Review/841c2923236647a6a7af567abbb3f40e, I get 202 response but the package name has been approved.

@dw511214992 Package name was not approved for this package but one of the manual API review was earlier approved for APIs which is good enough to consider package name as approved when API surface itself is approved. But APIView is sending failure response to REST API for packages that does not have any automatic API review yet. It did return correct response of 201 for REST request for JavaScript package https://apiview.dev/AutoReview/GetReviewStatus?Language=JavaScript&packageName=@azure-rest/ai-anomaly-detector 


If your requirement is to get only package name approval irrespective of API approval status, I would say we can make a change in APIView side to accept additional optional parameter, say "approvalType=FirstPreviewApproval" and that returns only approval status for first preview release.

Currently same rest API is used to check whether latest API revision is approved (200) or not (201) or if package is approved for first preview release and we need an `Automatic` API review generated to get status. Otherwise it will return 500 error with message `Automatic review is not found for package <package name>`

You can create an issue and assign it to me if you need the change I mentioned above.
@maririos FYI..

**Comment by praveenkuttappan** [comment]
![image](https://user-images.githubusercontent.com/55455725/217296410-88027e1f-4683-430d-82da-04a1c6feb7a5.png)

**Comment by dw511214992** [comment]
@praveenkuttappan I feel a bit of confused. In https://apiview.dev/Assemblies/Review/841c2923236647a6a7af567abbb3f40e, I find the package name should be approved:
![image](https://user-images.githubusercontent.com/40835867/217411537-0230e879-c300-4b98-92e6-506168d279ec.png)
So, the apiview service should return 201 when I call https://apiview.dev:443/AutoReview/GetReviewStatus?reviewId=841c2923236647a6a7af567abbb3f40e. 

Please add a new rest api to return the approval status of package name, including both dataplane and mangement, and including all lanuages.  https://github.com/Azure/azure-sdk-tools/issues/5364

Thanks

**Comment by live1206** [comment]
Need confirmation from @ladonnaq if GH issue is created for data-plane namespace review.

**Comment by maririos** [comment]
> For data-plane, it seems that user does not create GH issue for namespace review. And it is approved during arch board review meeting via ApiView, the approval result is save into ApiView DB.
> 
> For management-plane, the user creates GH issue for namespace review, and got approval manually in the GH issue.
> 
> Ideally, for both data-plane and management-plane namespace review can be approved via ApiView.

Correct. and the goal in PM effort is to see how we can make the management-plane process as similar as possible to the data-plane one.

> Need confirmation from @ladonnaq if GH issue is created for data-plane namespace review.

GH issue is not created for data-plane namespace review

**Comment by live1206** [comment]
For data-plane, namespace review is during SDK arch board review meeting, which happens during SDK Release process.
So, we can't get the namespace approval result during API Readiness App, we can only check it at the SDK Release signoff.

cc @ladonnaq @josefree @dw511214992 @zzvswxy

**Comment by ladonnaq** [comment]
Closing this issue.  Work is done for data plane.  We will open another issue if we decide to do something different for management plane.  Right now the process is as described in this wiki page - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki?friendlyName=Request-SDK-Release-in-OpenAPI-Hub&pagePath=/Welcome%20Service%20Partners!/Azure%20SDK%20APEX%20launch%20readiness%20criteria/Naming%20for%20new%20initial%20management%20or%20client%20libraries%20(new%20SDKs)
