### ISSUE TITLE
Update version in all apps to latest in Prod

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#5321]
Right now, data-plane Apps are in beta 2, which should be beta 3.

**Comment by live1206** [comment]
@maririos I have updated the version to `1.0.0-beta.3` for data-plan apps in Prod.
But this would cause other inconsistency in Prod, because the version of `Release Planner App` is `1.0.0-beta.2`.
The main issue is we have multiple versions of `Release Planner App`, but only version of `Data-plane API Readiness App`.
I do not think this is a big issue since they are different Apps, please share your thoughts.

**Comment by live1206** [comment]
@maririos After another thought, I changed the version of data-plane Apps back to `1.0.0-beta.2`.
I think the inconsistency in PPE is better than inconsistency in Prod.
The version of all Apps will be consistent once we get management-plan release out.

**Comment by maririos** [comment]
> The version of all Apps will be consistent once we get management-plan release out.

Do you know what is stopping us from moving management plan release to PROD?

**Comment by live1206** [comment]
> > The version of all Apps will be consistent once we get management-plan release out.
> 
> Do you know what is stopping us from moving management plan release to PROD?

We have deployed management-plan apps to Prod, but only available via Release Planner of review Url(PROD-1.0.0.beta.3).
The Release Planner official Url in Prod(PROD-1.0.0.beta.2) only contains data-plane apps. 

Do you think it's OK to put everything out? I guess we are planning to unblock data-plan process firstly.

**Comment by maririos** [comment]
To avoid having copies of apps and keep having this separtion, could we have an environment flag that will determine if the management plane radio button/link/whatever information in the Release Planner is not dsiplayed in PROD?
I think this will simplify our process and our versioning too

**Comment by live1206** [comment]
> To avoid having copies of apps and keep having this separtion, could we have an environment flag that will determine if the management plane radio button/link/whatever information in the Release Planner is not dsiplayed in PROD? I think this will simplify our process and our versioning too

We can't avoid having multiple versions of app with in-development features since we haven't implemented branching strategy in Power Apps as https://github.com/Azure/azure-sdk-tools/issues/4798
For instance, we are going to implement UX enhancement, and we can't deliver it until we have implemented the UX enhancement for all Apps including release planner, api readiness app and sdk release app.

For management-plane feature, it is not easy to hide them either because multiple pages needs to be adjusted based on environment. We'd prefer to have another copy of the app instead.

**Comment by maririos** [comment]
@ladonnaq is it ok to have the management plane apps in PROD available for customers?
I don't see a problem on having them available as mostly they work and we can start helping customers with them.

**Comment by maririos** [comment]
That being said, if there are bugs or improvements, those asks have low prioprity as our main focus right now is Cadl+DPG libraries
