### ISSUE TITLE
Implement UX enhancement for Release Planner

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#5331]
https://web.powerapps.com/apps/ece65a45-f966-4d8b-b04a-24329c5b8e99

This should include layout and pattern change in 
https://github.com/Azure/azure-sdk-tools/issues/5279
https://github.com/Azure/azure-sdk-tools/issues/5280

**Comment by live1206** [comment]
Move UX work to next sprint

**Comment by maririos** [comment]
This will be covered by Epic https://github.com/Azure/azure-sdk-tools/issues/5631
