### ISSUE TITLE
Add limitation of release plan creation

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#5332]
1 release plan for 1 product per lifecycle limitation in Prod, not in non-Prod for testing purpose.

**Comment by live1206** [comment]
@ladonnaq Please set the priority of this task, is it blocking data-plane onboarding?

**Comment by live1206** [comment]
>	Can a product have multiple release plans for the same Target Phase?

[huwe] Discussed with [@Josephine Qiu](mailto:yiqiu@microsoft.com) before, we started with no striction for now.   <La Donna> In production we should not allow more than one release plan per product per lifecycle milestone.  In PPE no restriction (because we need to continue to test).

**Comment by josefree** [comment]
Hi LaDonna, for APEX scenario, I think it makes sense to have the limitation. However, for non-APEX launch scenario,  it is a common scenario that service team can work on multiple API versions in the same period.  One API version is in release pipeline, the other is in development.  We shall be able to support them create different SDK release plans, right?   I think the policy should be 

**There should be only 1 active release plan for APEX launch of a target phase.**

which means for a Contoso service

there could be an active release plan for APEX launch of Private Preview, and an active release plan for APEX launch of Public Preview.  But there could NOT be 2 active release plans, both for APEX launch of Public Preview (if there is a purpose to create another one, there should be a warning of existing active release plan).

**There could be 1 active release plans for SDK release initiated by creating a new API version.**  

When we move on to support non-APEX scenarios.
The Contoso service can have 1 release plan for APEX launch of Public Preview, and 1 release plan for non-APEX launch (initiated by creating a new API version spec). 

Do you think this makes sense to you？

**Comment by ladonnaq** [comment]
> Hi LaDonna, for APEX scenario, I think it makes sense to have the limitation. However, for non-APEX launch scenario, it is a common scenario that service team can work on multiple API versions in the same period. One API version is in release pipeline, the other is in development. We shall be able to support them create different SDK release plans, right? I think the policy should be
> 
> **There should be only 1 active release plan for APEX launch of a target phase.**
> 
> which means for a Contoso service
> 
> there could be an active release plan for APEX launch of Private Preview, and an active release plan for APEX launch of Public Preview. But there could NOT be 2 active release plans, both for APEX launch of Public Preview (if there is a purpose to create another one, there should be a warning of existing active release plan).
> 
> **There could be 1 active release plan for SDK release initiated by creating a new API version.**
> 
> When we move on to support non-APEX scenarios. The Contoso service can have 1 release plan for APEX launch of Public Preview, and 1 release plan for non-APEX launch (initiated by creating a new API version spec).
> 
> Do you think this makes sense to you？

This makes sense.

**Comment by live1206** [comment]
@honghr 


![Image](https://user-images.githubusercontent.com/5196139/218656588-ec336ce3-4bc1-4bdd-97a5-7737c48d0f72.png)

Please remove the contact info from the message.
