### ISSUE TITLE
Check if SDK are brand new SDK package

### ISSUE THREAD

**Issue by zzvswxy** [Azure/azure-sdk-tools#5333]
https://github.com/Azure/azure-sdk-tools/issues/4692

> For management plane, .NET requires ArchBoard review and approval on each releases. For other languages (Python, Java, JS, Go), only brand new SDK package requires ArchBoard review. To create a new SDK version of an already onboarded service does not require ArchBoard review.

Create this issue to track if we can find a way to detect the SDK is brand new SDK.

**Comment by maririos** [comment]
Could we have a Cloud Flow that periodically syncs the data in our table according to the changes to the file?

**Comment by dw511214992** [comment]
> Could we have a Cloud Flow that periodically syncs the data in our table according to the changes to the file? https://github.com/Azure/azure-sdk/tree/main/_data/releases/latest

We maybe able to use it.

**Comment by zzvswxy** [comment]
deployed to Prod

**Comment by maririos** [comment]
@zzvswxy To make sure I understand, what was the change done here? this? https://github.com/Azure/azure-sdk-tools/issues/5333#issuecomment-1420036104

**Comment by zzvswxy** [comment]
> @zzvswxy To make sure I understand, what was the change done here? this? [#5333 (comment)](https://github.com/Azure/azure-sdk-tools/issues/5333#issuecomment-1420036104)

On the welcome page, we detect ADO work item if the 'Data plane SDK release type' is set.
![image](https://user-images.githubusercontent.com/20081898/220791487-9eaceffe-3e55-4992-a307-8aadcab233ed.png)
If users don't set, we will show a link to tell them ask PM to add the 'Data plane SDK release type'.

And on the Define Data Plane SDK Release Date and Supported Languages page.
![image](https://user-images.githubusercontent.com/20081898/220792397-f6ea34d3-ba68-40bc-82c4-bf9ccd8f2683.png)
We detect the 'Data plane SDK release type' and if the spec PR had a label 'new-api-version'. If one of the conditions is met, we will set all languages selected and user can't uncheck any language.

On the Schedule SDK ArchBoard Review page.
![image](https://user-images.githubusercontent.com/20081898/220793206-d50ba72b-17bd-4f6f-97dd-89c4f4a901b4.png)
We also use these conditions to decide whether the meeting type is introduction or follow up.
