### ISSUE TITLE
Transition from Release plan when the product is not onboarded

### ISSUE THREAD

**Issue by mayurid** [Azure/azure-sdk-tools#5334]
Crystal's new UI feedback:
Right now the main page gives me "Create Plan" as the enabled option. When i visit that I cant find my product and i can refer to "Onboard your product".
Can we make sure that this leads us to "Onboard your product" tab. Right now it errors.

**Comment by maririos** [comment]
This has been addressed:


![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/19ec86a5-6a05-410a-8483-915b146cd72f)
