### ISSUE TITLE
Document and communicate new calendar features with Admins

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5338]
We need to provide documentation on what the new capabilities of the calendar are and how the admins should take advantage of them.
Proposal is to have documentation and to set up a meeting to live demo the experience

**Comment by maririos** [comment]
Metting is happening with Informational Admin first. 
Documentation updated: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/728/Scheduler-Experience-App?anchor=**configuring-meeting-schedule**

**Comment by maririos** [comment]
@JonathanCrd to schedule and drive meeting with the other Admins

**Comment by JonathanCrd** [comment]
Meeting scheduled for the rest of the admins
