### ISSUE TITLE
Notifications UI

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5341]
The stakeholder UX studies and recent feedback from Azure SDK engineering team (Travis, Catalina, Mayuri) is that the Power Apps default notification component is not sufficient.  
 
- The Power App notifications pop up as banners at the top of the screen and they do not remain visible for very long.  This makes the notifications very easy to miss. The user may not see them or if they do, they don't have time to read them and figure out what they mean. 

- The notification messages that are informing a user of a missing pre-requisite/requirement do not tell the user how to complete the action. (For example, notification that a user needs to schedule an information meeting but no link to the scheduing tool).

**Comment by maririos** [comment]
We have seen this feedback in the Scheduler Tool as well. We opened issue https://github.com/Azure/azure-sdk-tools/issues/3957 with some feedback and ideas

**Comment by maririos** [comment]
This is a dup of https://github.com/Azure/azure-sdk-tools/issues/4593. Closing in favor of the other that includes a proposal from our UX designer
