### ISSUE TITLE
Network error message when trying to retrieve data: API Readiness App and Release Planner App (PPE)

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5342]
Travis and I both were seeing an error in the PPE for Release Planner and API Readiness Apps. https://aka.ms/ppe-sdk-workflow

Here is a screenshot of the error seen in the Release Planner - 

![image](https://user-images.githubusercontent.com/67656762/216847436-0ccfa1fa-b229-4efe-a08e-612a15f98d6d.png)

Here is a screenshot of error in API Readiness app.  This may be associated with the issue with getting data from a PR on a forked repo - https://github.com/Azure/azure-sdk-tools/issues/5282. However, the information in the notifications ask the user to check internet connection so it is confusing. 

![image](https://user-images.githubusercontent.com/67656762/216847582-7a8b5d7c-149c-4de5-906b-f04f7f7ea494.png)

**Comment by maririos** [comment]
@ladonnaq I haven't seen this error in a while. I am going to keep the issue open for a couple of weeks and if it doesn't repro then I will close it

**Comment by maririos** [comment]
Clossing as no repro
