### ISSUE TITLE
user scenarios validation

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#5357]
**Beta Releases and Stable Graduation**

Service user choose to release a beta SDK and graduate it to GA after at least 1 month (build SDKs upon the same spec pull request) 
- two SDK release plans upon the same spec pull request, one for beta, the other for GA

**Postpone release**

Service user postpone SDK release of selected support language 
- two release plans upon the same spec pull request, with different group of support language,

**Comment by josefree** [comment]
@ladonnaq would like to check if these two are valid scenarios. and should be handled as proposed using the SDK release planner.

**Comment by maririos** [comment]
Currently, user will need to create separate release plans for each of these scenarios (which are all valid).
Closing
