### ISSUE TITLE
Bug: Orphan GitHub Issue and Calendar invite

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5359]
A GitHub Issue and Outlook Calendar Invite were created by a user, however, there is no record of that meeting in the Dataverse.

Also, the powerapps deep link in both artifacts points to a different meeting.

**Comment by JonathanCrd** [comment]
By looking at the previous runs of the different cloud flows involved on the scheduling of a new meeting, the `Calendar Event - Create` cloud flow time out for the app. However, the flow finished sending the Outlook Invite.

The possible scenario is that the user didn't see the error message and schedule a second meeting (thinking it was a new one). This second time, another GitHub Issue and Outlook event were creating, and the draft record in the DB was patched with this last attempt.

What we need to do is to catch this type of errors on the pipelines, and then, close the GitHub Issue and any other artifact that could be left alone withouth an actual meeting.

**Comment by JonathanCrd** [comment]
This happened in the SDK app, however, it is possible that this type of errors can happen in the other apps to.

I'm adding the error handling logic in the three apps:

- [ ] SDK Review
- [ ] API Review
- [ ] Informational meeting

**Comment by JonathanCrd** [comment]
Fix implemented :)
