### ISSUE TITLE
[stress] Stress deployment script should let you deploy to a specific namespace via a switch

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#5360]
Deploying to a separate namespace is a useful thing to do for one-offs or other experiments - for instance, the Python team (via @l0lawrence) created separate namespaces for different test scenarios when doing ad-hoc testing. 

This feature is so intuitive that we actually thought we _already_ had this but apparently it wasn't hooked up. @benbp would like to make it clear that this is not a "bug", but merely a feature gap.

**Comment by benbp** [comment]
Somehow we all (i.e. me) collectively forgot that this does exist and that we use it all the time.

**Comment by ckairen** [comment]
For reference: https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/stress-testing/deploy-stress-tests.ps1#L20

**Comment by richardpark-msft** [comment]
I trusted you and it was clearly unwarranted.
