### ISSUE TITLE
Return whether a package name is approved or not

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-tools#5364]
Please add a new rest api to return the approval status of package name, including both dataplane and mangement, and including all lanuages.
There maybe challenges because the sdk pr is  not created and we need a apiview to be have the sdk package namespace be approved. The following is my suggestions: 
1. We create apiviews in the spec PR. Then we can ask archboard team to approve package name in these apiviews.
2. When a package name is approved before, the package name should be approved directly when a new release is coming and a new apiview is created.
3. Besides providing a rest api to check whether package name is approved by inputting a package name, please also support only inputting an apiview id because we don't need to caculate the package name in our side.

**Comment by maririos** [comment]
> When a package name is approved before, the package name should be approved directly when a new release is coming and a new apiview is created.

This should already happen in APIView

**Comment by dw511214992** [comment]
Hi @chidozieononiwu Is there an ETA for this feature request? When it's ready in staging environment, please let me know. Thanks
