### ISSUE TITLE
APIView fix APIView link disappeared issue when retrigger pipeline

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-sdk-tools#5373]
Issue feedback from @mikekistler 

the APIView for PR #21808 disappeared.  It looks like something triggered a recreate but the recreate failed.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/52271048/217554042-5f444e3b-4486-4cb8-9162-3d1d23c78304.png)

**Comment by mikekistler** [comment]
Another instance in [PR #21841](https://github.com/Azure/azure-rest-api-specs/pull/21841#issuecomment-1344982027):

![image](https://user-images.githubusercontent.com/85643503/217607727-fd252a7a-cbf4-4010-a40e-8f8f9ec8bdf9.png)

**Comment by ruowan** [comment]
This is issue has been fixed in prod spec pipeline.

**Comment by maririos** [comment]
@mikekistler feel free to reopen if this happens again
