### ISSUE TITLE
APIView - Update APIView token file to hierarchical structure

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5374]
APIView renders review page based on a JSON token file and this token file is a flat list of tokens. Currently these tokens does not have any hierarchical information about code and parser is the one that decides how a review needs to be rendered . for e,g. space, indentation etc are part of token file itself. 

This makes it hard to implement any solution in APIView side to add any language independent changes in rendering. For e.g. different types of sorting on UI, Filter within a review, or to use better diffing logic that performs diff using DFS logic instead of a line by line comparison. These changes will also be helpful in identifying cross language implementation of a specific API or class.

We should implement a new token format that has more hierarchical data instead of storing tokens to render the UI. This will effectively reduce token file size and provide the flexibility of adding rendering logic to APIView side. Tokens should only contain information related to APIs. 

{
     "Name": "ClassLibrary1", // Would be displayed in review list
      "Language": "Json",
      "Version": "0.0.1",
      "PackageName": "",
      "Tokens": [
              "Namespaces": [
                    {
                         "Name": <Namespace1>,
                         "Kind": "Namespace", 
                         "Members": [
                             {
                                  "Name": <Class1>,
                                  "Type": "Class",
                                  "ID": <scopedID>,
                                  "CrossLanguageID": <LanguageIndependentID>
                                  "Members": [
                                         {
                                              "Name": <Method1>
                                              "Type": "Method",
                                               "ID": <ID>
                                                "Return Type": <Return Type>
                                               "Arguements": [],
                                               <Additional Properties>
                                         },
                                         {
                                              "Name": <Method2>
                                              "Type": "Method",
                                               "ID": <ID>
                                                "Return Type": <Return Type>
                                               "Arguements": [],
                                               <Additional Properties>
                                         }
                                  ]
                             },
                             {
                                 "Name": <Class2>,
                                  "Type": "Class",
                                  "ID": <scopedID>,
                                  "CrossLanguageID": <LanguageIndependentID>
                                  "Members": [
                                         {
                                              "Name": <Method1>
                                              "Type": "Method",
                                               "ID": <ID>
                                                "Return Type": <Return Type>
                                               "Arguements": [],
                                               <Additional Properties>
                                         },
                                         {
                                              "Name": <Method2>
                                              "Type": "Method",
                                               "ID": <ID>
                                                "Return Type": <Return Type>
                                               "Arguements": [],
                                               <Additional Properties>
                                         }
                                  ]
                             }
                         ]
                    }
              ]
       ]

}

This will have following tree structure and parsers will not provide any additional rendering tokens..
<PackageToken>
     <NamespaceToken>
               <ClassToken>
                         <MethodToken>
                                                            
     </NamespaceToken>
</PackageToken>

@heaths FYI...

**Comment by heaths** [comment]
I think the new hierarchical token stream should only tokenize meaningful tokens too e.g., namespace/package, types, members, return types, parameter types and names (perhaps separately), etc. The token text would still be source material such that Python has snake case, .NET PascalCase, etc., but leave how the tokens are rendered to a separate rendering engine apart from the data. This makes dealing with the data - like when it comes to sorting - easier. For example, in what order would you sort whitespace, line, or bracket tokens like are stored now?

With only meaningful tokens in a data format, it makes it really easy to semantically diff using a depth-first approach as well.

**Comment by maririos** [comment]
Dup of #5897
