### ISSUE TITLE
Swagger APIView for PR 21841 is missing information

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#5376]
The [Swagger APIView for PR 21841](https://apiview.dev/Assemblies/Review/ee454eada3414e52b4fe4ab499d17e89?diffRevisionId=cb79d3e8fd034f37a96035e17b7c89cf&diffOnly=False&revisionId=e480587e097f4d6282ae2b2599c99e7e&doc=False) is missing several important bits of information on the REST API:

- The properties of the 202 response for POST on /emails:send are not rendered.

![image](https://user-images.githubusercontent.com/85643503/217609007-3cf2ac99-1ea6-4cfb-8148-e67ce20111a4.png)

- The `Operation-Id` header parameter for POST on /emails:send is not rendered.

**Comment by ruowan** [comment]
@mikekistler Here is the fix version APIView of communicationEmail service https://apiviewstaging.azurewebsites.net/Assemblies/Review/cce8b46c14a947dd9a74d636b52f725a

The first issue has been fixed. And the second issue will be fixed in this PR. https://github.com/Azure/azure-sdk-tools/pull/5386

**Comment by mikekistler** [comment]
The first issue is occurring in APIViews generated as recently as 4 days ago:

https://apiview.dev/Assemblies/Review/3a169944515241f7b57e3fb70b9bb92d

**Comment by ruowan** [comment]
This issue happened on this PR. https://github.com/Azure/azure-rest-api-specs/pull/22316 @praveenkuttappan . I have already updated the swagger-api-parser version in spec PR pipeline. And the generated APIView artifact file is correct. But the APIView website doesn't pick up the latest APIView file.

**Comment by praveenkuttappan** [comment]
I see the issue in APIView when a new revision is available. Swagger API review has collapsible section, and this is not correctly considered when calculating the diff. I will look into it to find a solution.
//fyi: @maririos @chidozieononiwu
