### ISSUE TITLE
APIView pipeline job must update comment when APIView job fails

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#5377]
The APIView PR pipeline job posts a comment in the PR to say that it has begun generation of an APIView:

![image](https://user-images.githubusercontent.com/85643503/217617130-24d64530-bdac-46a7-8733-f95672c6be07.png)

But if APIView generation fails, the comment is not always updated to indicate that processing failed and why.

The APIView pipeline job should ensure that this comment is updated, whatever the outcome of the processing.

Also, the PR Check should not report "Succeeded" when it has actually failed.

**Comment by chidozieononiwu** [comment]
> The APIView PR pipeline job posts a comment in the PR to say that it has begun generation of an APIView:
> 
> ![image](https://user-images.githubusercontent.com/85643503/217617130-24d64530-bdac-46a7-8733-f95672c6be07.png)
> 
> But if APIView generation fails, the comment is not always updated to indicate that processing failed and why.
> 
> The APIView pipeline job should ensure that this comment is updated, whatever the outcome of the processing.

The comment is updated if APIView generation fails. The only case where it's not updated is if all the APIViews are skipped.

**Comment by chidozieononiwu** [comment]
Another thing to keep in mind is that the pipeline might generate SDK and Swagger APIReview. While it aggregates all the results in the pipeline under the Generated APIReview Comment
<img width="700" alt="SwaggerAPIReviewComment" src="https://user-images.githubusercontent.com/31145988/226069190-89b89273-f9c5-49bc-83c3-c1b593adcf3b.png">
The success report in the swagger validation pipeline refers only to the Swagger APIReview generation, so if an SDK review generation should fail this will still apprear as a success.
<img width="700" alt="Swagger Validation Report" src="https://user-images.githubusercontent.com/31145988/226069374-401b975c-4e2a-40f3-bd5d-0004659d10ab.png">

**Comment by chidozieononiwu** [comment]
Oh yes and it does send an event if the generation fails.

**Comment by chidozieononiwu** [comment]
I have fixed the first two cases. And I have added logging so as to be able to track down exactly where and how events are getting missing, dropped or not picked up.

One approach suggested by @praveenkuttappan is to add the comment directly from APIView service using the [DetectApiChanges](https://github.com/Azure/azure-sdk-tools/blob/e91878af672746ff5a865b9da02b40bca3a5f76e/src/dotnet/APIView/APIViewWeb/Controllers/PullRequestController.cs#L28) endpoint and setting `commentOnPr` to `true`. We will have to format the comment into the existing table structure, then we can disable the `unifiedPipelines -> eventhubs -> kebabbot` approach for adding the Generated APIView comment.

**Comment by weshaggard** [comment]
I would like to avoid having the APIView service knowing about the specs PR and figuring out how to update those type of comments. I know we do it for the SDK repos currently but I'd like to eliminate that at some point as well, if possible. 

Is the issue that we are generating the APIView's async and we don't update the comment until it is finished? I thought APIView was always returning a URL even if it is wasn't ready yet and we should be able to add that to the comment.

**Comment by chidozieononiwu** [comment]
A event is pushed to eventhub for each APIView generation attempted, with the result (success or fail) of the attempt.  The kebab bot picks up this event then writes the comment to Github. The issue here is one where the event was pushed to eventhub but the kebab bot did not write any comment.

**Comment by weshaggard** [comment]
Yeah that seems like a bug we should be trying to handle in the kebab bot as opposed to adding a new ApiView dependency on it.
