### ISSUE TITLE
 Gate release of client libraries

### ISSUE THREAD

**Issue by dw511214992** [Azure/azure-sdk-tools#5387]
Raised by @m-nash in https://github.com/Azure/azure-sdk-tools/issues/4718

This will also be an issue for the new [cadl-location.yaml](https://github.com/Azure/azure-sdk-for-net/blob/1849a21f5a4305a2b08ae2d749a6d406cb55a7f6/sdk/openai/Azure.AI.OpenAI/src/cadl-location.yaml) file that is used to pin a language sdk to a specific commit of a spec for cadl.

There are one thing here that we probably want to block the release pipeline on if they exist.
1. If the sha is not in the main branch
   a.  We will need a way to override this in the rare event we ship from a hotfix branch.

There is another thing we probably want to block commit preferably or PR merge if we can't do commit.
1. If the spec repo doesn't match the language repo.  I.e. if the language repo is azure-sdk-for-net and the spec repo is azure-rest-api-specs-pr or vice versa.

**Comment by ladonnaq** [comment]
@dw511214992 Is this a requirement that still needs to be addressed?  I am working on the extended roadmap and want to ensure I have all requirements identified.

**Comment by maririos** [comment]
For data plane, release pipelines have a check that validates the spec used is in the public repo in the main branch.
For management plane we can add the check in the SDK release app so that a user can't request a release until the PR is merged into main.

**Comment by ladonnaq** [comment]
> For data plane, release pipelines have a check that validates the spec used is in the public repo in the main branch. For management plane we can add the check in the SDK release app so that a user can't request a release until the PR is merged into main.  I added this issue to the todos for https://github.com/Azure/azure-sdk-tools/issues/8232.

**Comment by maririos** [comment]
This will be validated by different steps in the release planner. More design details on #5659
