### ISSUE TITLE
APIView - Realtime comments

### ISSUE THREAD

**Issue by petrsvihlik** [Azure/azure-sdk-tools#5388]
Would it be possible to employ SignalR/websockets or a similar technology in APIView to avoid the necessity of refreshing the page whenever a comment is added? 
It would be very handy during review meetings when comments are being added rapidly by multiple members at the same time.
We're running into this nearly every time during our internal ACS DevEx review meetings.

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/6402
