### ISSUE TITLE
Swagger APIView content inconsistent with generated APIView file in spec PR pipeline

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-sdk-tools#5400]
For this PR: https://github.com/Azure/azure-rest-api-specs/pull/21841

The generated APIView token file artifact has been changed, but the APIView still show the old one.

APIView link: https://apiview.dev/Assemblies/Review/ee454eada3414e52b4fe4ab499d17e89

I manually uploaded the generate apiVIew token file to test env. The two APIView are different. https://apiviewstaging.azurewebsites.net/Assemblies/Review/f5e56708f70847e78d5b39a986c5f0e8

APIView should pick up the latest generated artifact.

**Comment by maririos** [comment]
Fixed on https://github.com/Azure/azure-sdk-tools/pull/5421
