### ISSUE TITLE
Big GH profile image on APIView

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#5438]
Used this https://apiview.dev/Assemblies/Review/11fce64a45554df0aea8b315281c1e7e and clicked on "Request reviewers"

![image](https://user-images.githubusercontent.com/1050156/218837141-f69ad98a-c20e-4f40-a05d-14c1c668587b.png)

It feels APIView wants to show a big image for Anna for some reason :)

**Comment by praveenkuttappan** [comment]
PR https://github.com/Azure/azure-sdk-tools/pull/5453 will resolve this issue.
