### ISSUE TITLE
API View links are not shown when scheduling a meeting from the Release Planner app

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#5441]
When scheduling an SDK Review from the Release Planner app, the instance of the Scheduler app won't show the APIView links.

However, if the meeting is created and then you click on edit, the links will be there.

Thanks to @zzvswxy for finding this bug.

**Comment by JonathanCrd** [comment]
I was able to replicate this error.
Looks like the artifacts are not loading when the meeting is in draft mode.

**Comment by JonathanCrd** [comment]
> Looks like the artifacts are not loading when the meeting is in draft mode.

Yes, this was the reason why the list was blank: we were not retrieving the artifacts when the `mode` was set to `"new"`. Now, if it's a new meeting but a draft record, the artifacts are retrieved.

**Comment by maririos** [comment]
@JonathanCrd I made a change on where you added the implementation and did some testing,  but to double check, could you test again this scenario? Also, let's talk tomorrow about draft meetings and how that is happening in all of our apps
