### ISSUE TITLE
Missing GitHub Issue for SDK Review coming from the Release Planner app

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#5442]
An SDK review was scheduled coming from the Release Planner and no GitHub issue was created for it.

Bug reported by: @zzvswxy

**Comment by maririos** [comment]
Do you know the name of the service?

**Comment by JonathanCrd** [comment]
I do, I also have the event ID

**Comment by JonathanCrd** [comment]
@zzvswxy we know what's going on in here.

It is expected that "Release Planner Test Service" won't create a GitHub issue, since it is a test service.
This service is used to block dates and perform other types of tests. 

Thanks @maririos for catching this.
