### ISSUE TITLE
Meeting information is duplicated

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#5450]
The bot that is scheduling the meetings duplicates most of the information when a meeting is rescheduled. It would be cleaner if the main part of the issue was updated and then noted it was edited. Since users could also edit the main section, clearly indicating what is auto generated would be helpful. This would enable the bot to simply update the section of the main body that it is responsible for.

![snap-2023-02-14 17-20-12](https://user-images.githubusercontent.com/522116/218877517-8128e475-3156-4803-8a4e-b5d3df35b090.png)

**Comment by maririos** [comment]
Duplicate issue. Closing in favor of https://github.com/Azure/azure-sdk-tools/issues/5401
