### ISSUE TITLE
Scheduler tool - Add scheduler tool admin users to calendar

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5461]
Scheduler tool uses Outlook calendar meeting to maintain available meeting slots. Currently these meetings can be edited by engineering team only.  We should share these calendars with admin team DL so they can block or add a random slot within these placeholder calendars.

**Comment by maririos** [comment]
- [x] Informational
- [ x] API
- [ ] SDK (ish, ideally we can change to the DL which need to be enabled to be a SG)
