### ISSUE TITLE
Scheduler tool - Automatically block slots on US holidays

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5462]
Meeting slots are configured based on placeholder meetings created in outlook calendar and based on Pacific time zone. Outlook has a calendar for holidays. We should check if he can query this holidays calendar to find US holidays and automatically exclude those holidays from available meeting slots, so we don't have to manually delete those slots from placeholder calendars.

**Comment by maririos** [comment]
Dup of https://github.com/Azure/azure-sdk-tools/issues/5348
