### ISSUE TITLE
APIView bug with search bar

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#5465]
If I search for PKI, I find my APIView:
![image](https://user-images.githubusercontent.com/5723682/219109217-5282eafd-f48f-441b-b4e2-b8ad2e8867b7.png)

However, if I put the PR number in the search box, it finds nothing:
![image](https://user-images.githubusercontent.com/5723682/219109343-2d497ae7-aa93-4a42-b454-0910690b10c2.png)

**Comment by praveenkuttappan** [comment]
@tjprescott You can search for API reviews created from a PR using `pr:10562`

**Comment by praveenkuttappan** [comment]
@chidozieononiwu Can you please update README to include instructions about search filters we support.
