### ISSUE TITLE
[ApiView] Show Hidden APIs no longer works

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-tools#5470]
Since the new UI rollout, it appears that Show Hidden APIs is not functional. Hidden APIs are always hidden regardless of the setting.

As an example, [Event Grid API view](https://apiview.dev/Assemblies/Review/1b1c0fbd41e849debdeede261e859b1c) should have a namespace of Azure.Messaging.EventGrid.Models in the sidebar when showing hidden APIs.

This feature was added in https://github.com/Azure/azure-sdk-tools/pull/4618

**Comment by JoshLove-msft** [comment]
@maririos is there any other information needed to get this prioritized?

**Comment by maririos** [comment]
@chidozieononiwu could you please take a look?

**Comment by maririos** [comment]
> @maririos is there any other information needed to get this prioritized?

You've done it all. Because of the holiday we didn't look at the issue this week. Added it to our release
