### ISSUE TITLE
[Scheduling Tool] Redundant issues being created...

### ISSUE THREAD

**Issue by markweitzel** [Azure/azure-sdk-tools#5480]
Recently, we have been working with the Cognitive Services Health Decision Support team on their API. This work has been on-going for several months. We first reviewed their OpenAPI, then worked with them to convert this to Cadl. 

Logically, this should be one effort that spans multiple reviews. The API Stewardship Process is to create **a single** Github Issue that would be used to record the activities on this work until it is transitioned to the Azure SDK team. 

However, what we have discovered is that, since the scheduling tool does not help the service teams choose **existing** issues, they just put the PR in and go on their way. A new issue is created, which is, effectively, redundant. Ideally, the service team would be presented with a list of past issues and be able to select one. The title and/or description in the issue should be clear. Also, if we've done an API review, past comments should be easy to find as well.

By creating these "redundant" issues, we are essentially defeating the purpose and intent of the issue: to track a single scope of work over time. To correct this, an API Steward (most of the time me) has to go into each issue and manually link them together. Here is an example of where this has happened: [Health Decision Support](https://github.com/orgs/Azure/projects/196/views/4?filterQuery=is%3Aopen+health+De)

**Comment by maririos** [comment]
This is a dup of https://github.com/Azure/azure-sdk-tools/issues/4694
