### ISSUE TITLE
Scheduling Tool - Meeting time change

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-tools#5485]
With the current Scheduling tool calendar it is possible to make a meeting slot at a non-standard time, then either schedule or move a meeting from another day to that slot. However, you are not able to take a meeting scheduled for the standard time slot on a day and move it to a non-standard time slot on that same day. I believe the 1 meeting a day rule blocks any non-standard meeting slot that gets created from showing on a day that already has a meeting scheduled. 
It would be great if at least Admins had the ability to just change the time of a meeting.

**Comment by maririos** [comment]
Thank you @ronniegeraghty .
Closing as a dup of https://github.com/Azure/azure-sdk-tools/issues/4573
