### ISSUE TITLE
[test-proxy] Consider using microsoft/reverse-proxy

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#5496]
https://github.com/microsoft/reverse-proxy is "a toolkit for developing high-performance HTTP reverse proxy applications".

It might be worth investigating this project, to see if it could makes sense to implement test-proxy on top of reverse-proxy.

**Comment by mario-guerra** [comment]
Hi @mikeharder, this project looks interesting, but the current test proxy implementation meets our internal requirements as-is. What value would we gain by porting it to the reverse proxy project? 
CC'ing @kurtzeborn

**Comment by mikeharder** [comment]
@mario-guerra: I'm not sure what we might gain by porting to `reverse-proxy`, but I think it would be worth at least a few hours of investigation.  `reverse-proxy` might already solve a lot of the issues we've been seeing (e.g. removing headers, handling content-length vs chunked, etc).  But it also might be a lot of unnecessary work to rewrite `test-proxy`.

So I'm not suggesting we **should** port to `reverse-proxy`, I just think we should be aware of `reverse-proxy` and consider it.

**Comment by mikeharder** [comment]
I would add this is a very low priority, we can move it to the backlog or even close it if you're not interested.  I just discovered `reverse-proxy` the other day and wanted to make a note of it in an issue.

**Comment by mario-guerra** [comment]
I'm not a fan of putting stuff on the backlog that we know we'll never get to. If there is clear benefit to porting it would be different, but setting aside a few hours to investigate is a few hours that could be spent on the actual backlog. Plus, using this project comes with the downside of introducing a dependency on an external project. 
I move to close this issue for now, we can always reopen if we decide to revisit it in the future.
