### ISSUE TITLE
Add ability to have more than 1 meeting of the same type per day

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5498]
This work will help with:
- Have multiple slots of meetings for one type of meeting (useful for Informational and API Review)
- Reschedule meetings for the same day but different time

**Comment by maririos** [comment]
- UI change (most chunk of the work)
- Logic

Est time: 2 weeks / 1 person

**Comment by maririos** [comment]
Planning epic: https://github.com/Azure/azure-sdk-pr/issues/1256

**Comment by maririos** [comment]
Figma design: https://www.figma.com/file/OdYeiVYd0PYK8qC5FnsNMU/Multiple-meetings-per-day-in-Scheduling-Tool?type=whiteboard&node-id=0-1&t=i6G7tY9hRu16j7Z3-0

**Comment by JonathanCrd** [comment]
The first iteration of this calendar has been deployed to PROD
