### ISSUE TITLE
Cadl APIView should insert comments for all linter messages into the APIView

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#5499]
Any warning messages produced by the Cadl compile step should be captured and inserted into the APIView as comments.

We should also include suppressed warnings along with the reason for suppression, but this is probably harder and lower priority, so can be done as a follow-on feature.

Without this, reviewers must run the Cadl compile themselves locally to see the warnings/linter messages, which is cumbersome and time consuming.

**Comment by mikekistler** [comment]
The view from the API Stewardship board is that suppressions are at least as important if not more so than warnings.

**Comment by mikekistler** [comment]
@tjprescott says that there won't be any linter messages because the compile in the pipeline uses "warnAsError" and the compile will fail and no APIView will be produced in this case.

**Comment by tjprescott** [comment]
Closing this for the reasons mentioned above. We do now display suppression in the TypeSpec APIView, so architects can see where a service team chose to ignore a rule rather than fix it.
