### ISSUE TITLE
Handling no-pipeline scenarios in Check Enforcer

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#550]
Over the last couple of days there have been quite a few instances of PRs making changes where no Azure Pipeline was run. it might have been a README.md change that isn't covered by a pipeline, or some other configuration change. I'm starting this discussion to try and figure out what we want out stance to be on this.

Just a refresher on how Check Enforcer works. Check Enforcer has a setting called ```minimumCheckRuns```stored in its configuration file located at ```eng/CHECKENFORCER``` in each repository. The way Check Enforcer interprets this setting is that when it gets a check-run completed event it evaluates first whether all outstanding check runs have passed (excluding itself) and that the total number of check runs (excluding itself) meets or exceeds the minimumCheckRuns threshold.

In the case of no-pipeline PRs this threshold is not met, and so Check Enforcer remains in-progress and what change to its successful state.

> **Argument for leaving as is:**
> One of the arguments for leaving the status quo is that no-pipeline runs are a bit of a EngSys "smell" in that there might be some classes of changes where automated validation doesn't occur and additional manual verification, and administrative merge rights are required.

> **Argument for changing behavior:**
> On the flip side, there are plenty of changes which are innocuous and we shouldn't be blocking teams from getting things done whilst they hunt for an administrator to merge their change.

We first need to determine where we land on the above arguments and then, if we decide that a behavior change is required determine the best approach.

There are a few possibilities that would need exploration. One option would be to add an ignore glob patterns to the ```eng/CHECKENFORCER``` such that if a PR in its entirety is covered by the ignore pattern that Check Enforcer would turn green. There might be some other options although this one could be done in a stateless way without too much overhead.

**Comment by weshaggard** [comment]
I think having some sort of glob ignore pattern is likely the best option, to avoid questions and have the system work well.

We can also consider some `[skip-ci]` type of option, either a tag or comment of some sort, that allows folks to by-pass checkenforcer. Maybe even just `/checkenforcer skip` or something like that. 

The second option allows folks to unblock quickly and the the first option allows us to configure things so we don't have to explain the second option to many people :)

**Comment by mitchdenny** [comment]
I feel like ```/check-enforcer skip``` needs to raise some kind of alert for us so that we can go and implement the changes in the config file for the first :)

... I just took ```/check-enforcer success``` out! :)

**Comment by pakrym** [comment]
What about a timeout of around a 10 minutes? If no other PR checks started just consider it passed.

**Comment by weshaggard** [comment]
There are other times where folks might also want to ignore a failing CI leg and we shouldn't require an admin to merge those PRs.

**Comment by pakrym** [comment]
What about requiring to specify an issue when ignoring?

/check-enforcer skip http://github.com/...

That would force people to file issues for failing CI

**Comment by JimSuplizio** [comment]
I would really like to have the ability for a non-admin, to do either skip or set success on check enforcer. If there's a way we can treat these differently, like a high pri email or something that's noticeable, which would be something we can scrutinize. The reason being is otherwise we're waiting around for someone with Admin permissions to force something through. While normally, this shouldn't be an issue I've already run into two issues morning.
1. One of my pipelines finished running but one of the runs was still showing yellow. I had to re-run the pipeline to get everything green for CE to be green.
2. A partner team was pushing a PR though that had test failures (known flaky tests) and I had to ping @weshaggard since I don't have the permissions.

**Comment by weshaggard** [comment]
Or we just add logging for any cases were we someone uses this command so we can audit the cases but allow folks to unblock themselves. We could even add comments tagging some github team directly on the PR whenever this is used.

**Comment by mitchdenny** [comment]
OK ... seems like the consensus is coming around to having an unblock mechanism which raises some kind of alarm but other wise allows folks to push through. I like the idea of either @ mentioning the azure-sdk-engsys team so they know about what happened and can remediate if appropriate (adding ignores if/when that feature is added) or actually addressing pipeline coverage issues.

The idea of creating issues is a good one too. I think that would be step 2 if the @ mention option wasn't getting the desired behaviour.

What about adding a comment when the PR is created which tells people what the commands are for Check Enforcer?

**Comment by JimSuplizio** [comment]
> What about adding a comment when the PR is created which tells people what the commands are for Check Enforcer?
I've been mulling over this and I'm iffy. I don't mind telling people the basic commands like
`/check-enforcer reset` or `/check-enforcer evaluate` but I wouldn't be too keen about telling people on saying "Here's the command that'll allow you to bypass this check". Don't get me wrong, I fully realize that if a command as soon as one person is told how to skip then effectively everyone knows but I'd rather not have people thinking that was the immediate option before trying one of the other, more accepted, ways to get Check Enforcer into a good state.

**Comment by weshaggard** [comment]
I'd suggest not automatically adding comments with help. Instead just use the details link from the checkenforcer check itself for that.

We should also consider which what we call the success option, I see a couple options:
- `/check-enforcer success`
- `/check-enforcer skip`
- `/check-enforcer override`

I kind of like something like override so that it is clear that this isn't normal and people should think twice.
