### ISSUE TITLE
Auto populate API Spec link when API meeting is requested from Release Planner app

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5500]
This is currently blocked by https://github.com/Azure/azure-sdk-tools/issues/4926

**Comment by JonathanCrd** [comment]
Is this field on the ADO Work Item?

**Comment by maririos** [comment]
We talked about this offline. Ping me if you have more questions when working on this issue

**Comment by maririos** [comment]
After another look, it will be better to wait until we have a conclusion on: https://github.com/Azure/azure-sdk-tools/issues/5932 and then move with this issue

**Comment by maririos** [comment]
Done
