### ISSUE TITLE
Provide direct links to documentation for Hero scenarios

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5504]
Instead of having a link to the Azure REST API Stewardship board, we should have a direct link somewhere that explains what a Hero scenario is and an example of it.
Same with Core concepts (https://github.com/Azure/azure-sdk-pr/blob/main/onboarding/Core_Concepts.pdf)

![image](https://user-images.githubusercontent.com/9868623/219791682-7befcd52-7e15-430e-b29b-7839253431ff.png)

FYI @chunyu3 as this ties with the email thread I added you about the best place to upload these documents

**Comment by ladonnaq** [comment]
+1 Let's get this implemented as soon as possible so that we can start using the existing app with service partners.

**Comment by maririos** [comment]
@ladonnaq do you have a recommendation of a place where we can out the documents that is not in a private repo or in a wiki where it can be hard to find?

**Comment by maririos** [comment]
@ccbarragan this type of information will be in page you are setting up, right?

**Comment by ccbarragan** [comment]
> @ccbarragan this type of information will be in page you are setting up, right?

Yes. Ideally we'll have a link to this with information and examples in the new [eng.ms site](https://eng.ms/docs/products/azure-developer-experience/design/hero-scenarios).

**Comment by maririos** [comment]
Content has been added to https://eng.ms/docs/products/azure-developer-experience/design/api-design
Once the site goes live, the Release Planner can update the link to point here

**Comment by maririos** [comment]
Site goes live on Sept, so moving this issue to Sept

**Comment by maririos** [comment]
Updated https://eng.ms/docs/products/azure-developer-experience/design/api-docs
