### ISSUE TITLE
Update Getting started with Cadl link

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5506]
After rename, we need to update the link in:

![image](https://user-images.githubusercontent.com/9868623/219792214-0d3a923a-35b1-4cd1-8e2f-2343adcfb13c.png)

Current error is:

![image](https://user-images.githubusercontent.com/9868623/219792260-4a363169-b92c-4035-a64e-19f57f4678f0.png)

@mikekistler could you give us the new link we should use?

**Comment by honghr** [comment]
@maririos @mikekistler I'm not sure if it is correct link. https://microsoft.github.io/typespec/

**Comment by mikekistler** [comment]
What is the current link?

**Comment by maririos** [comment]
> What is the current link?

https://github.com/Azure/cadl-azure/blob/main/docs/cadl-getting-started.md#getting-started-for-azure-data-plane-services

**Comment by mikekistler** [comment]
Then we should replace it with:

https://github.com/Azure/typespec-azure/blob/main/docs/typespec-getting-started.md#getting-started-for-azure-data-plane-services

**Comment by live1206** [comment]
Fix deployed to Prod
