### ISSUE TITLE
Management Plane: Testing in PPE for new API version (Purview) 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5509]
**Scenario**

Service: Azure Device Provisioning Service
PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/10546
Swagger (OpenAPI)
Apps tested: Release Planner and API Readiness App
New preview API version, new preview SDK version

**ARM API Review screen**

- [ ] Error but ARM has signed off the PR and the label "ApprovedOkToMerge".  Is this correct?  

![image](https://user-images.githubusercontent.com/67656762/219797170-74124b24-170e-4003-a83a-d04fed06e225.png)

**Comment by maririos** [comment]
Could it be because the PR has CI build failures?

**Comment by live1206** [comment]
@ladonnaq Which error are you talking about? 
PR Summary error?
https://github.com/Azure/azure-rest-api-specs-pr/pull/10546#issuecomment-1374266714

**Comment by live1206** [comment]
Duplicated with https://github.com/Azure/azure-sdk-tools/issues/5527
