### ISSUE TITLE
PR already associated to my new release plan

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5510]
When creating a new release plan, there is already an associated PR. See image for information:

![image](https://user-images.githubusercontent.com/9868623/219803953-4ba140ae-71c4-44f5-b9f4-d95be1767ebb.png)

**Comment by zzvswxy** [comment]
It's designed, not a bug. @honghr  can you explain it? Thanks

**Comment by honghr** [comment]
Because there is no rp folder name associated with the current service in our app backend. As we know, The PR is associated through the rp folder name, so we'll associate service with the rp folder as well. At present, there are fields in the backend dataverse to record the default rp folder of each service, but most of the services have not been set. This still needs to be discussed whether to provide an entrance for users to choose, or we should manually preset it in advance.

**Comment by live1206** [comment]
@maririos 
I assume you are testing in PPE, the product `Release Planner Test Product` is corresponding to ADO item: https://dev.azure.com/azure-sdk/Release/_workitems/edit/14422/.
Switching to `Data-plane` tab, you can see the PR input from onboarding questionnaire:
![image](https://user-images.githubusercontent.com/5196139/220249013-13932000-472f-4701-817a-c34dd541bfbc.png)

And then, while user created a new release plan, the PR will be associated by default for the release plan, what's why you have a PR already when you enter API Readiness App. https://github.com/Azure/azure-sdk-tools/issues/5267

Please let me know if you think we should refine the behavior further, thanks!

**Comment by maririos** [comment]
> @maririos I assume you are testing in PPE, the product `Release Planner Test Product` is corresponding to ADO item: https://dev.azure.com/azure-sdk/Release/_workitems/edit/14422/. Switching to `Data-plane` tab, you can see the PR input from onboarding questionnaire: ![image](https://user-images.githubusercontent.com/5196139/220249013-13932000-472f-4701-817a-c34dd541bfbc.png)
> 
> And then, while user created a new release plan, the PR will be associated by default for the release plan, what's why you have a PR already when you enter API Readiness App. This was implemented in #5267
> 
> Please let me know if you think we should refine the behavior further, thanks!

@live1206  That makes sense. I did not check there. It was an error with the information saved in the ADO item.
Thank you!
