### ISSUE TITLE
Error when associating a PR to my release plan

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5511]
Error when associating a PR into my Release Planner App.

![image](https://user-images.githubusercontent.com/9868623/219804138-de6fae29-4f37-41a2-b62b-416faeb3fab1.png)

**Comment by live1206** [comment]
I tried with the same PR, and got it associated successfully.
@maririos Could you try again to see if you can reproduce it?

**Comment by maririos** [comment]
I get a different error now:
<img width="1751" alt="image" src="https://user-images.githubusercontent.com/9868623/220785157-87ab5e50-8010-4ee7-a648-f2fee26237fe.png">

**Comment by maririos** [comment]
This happens in PPE

**Comment by live1206** [comment]
@maririos 
When user re-associate API Spec PR with `SDK Release milestone` in progress, we need to reset the status for `SDK Release milestone`, which is stored in dataverse table `SDK Release Request`.
And the `Delete` permission was missing as the error showed, I have added it in PPE and Prod.
Please try again to see if it works.

**Comment by maririos** [comment]
That fixed it! No more errors. Thank you!
