### ISSUE TITLE
Error when click on Complete Sign Off data plane API Readiness

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5512]
I wasn't able to capture the error, and now the button is disabled (as I imagine it completed). @live1206 let me know if you would like a repro and I can see how to get it

**Comment by honghr** [comment]
@maririos Can you post the screenshot for this case?

**Comment by live1206** [comment]
@maririos Yes, please help to repro and get the screenshot. I have tried a few times, was not able to reproduce it.

**Comment by maririos** [comment]
Got it!

<img width="1698" alt="image" src="https://user-images.githubusercontent.com/9868623/220786323-97299fcd-e685-48bb-bcf3-9313e2351116.png">

**Comment by live1206** [comment]
When the API Readiness is complete, we will update ADO item to update the status, but seems like the field has been renamed:
![image](https://user-images.githubusercontent.com/5196139/220843408-a5afcd72-6145-406b-8267-980a129e6dd1.png)
It used to be `Stable API readiness state`, or I got it wrong in the first place.

Fix deployed to all environments now.
@maririos Please help to verify.

cc @ladonnaq

**Comment by maririos** [comment]
I tried it again and it didn't fail but it also didn't say it succeeded. Am I supposed to see a confirmation or something?

**Comment by ladonnaq** [comment]
> I tried it again and it didn't fail but it also didn't say it succeeded. Am I supposed to see a confirmation or something?

I don't think that the logic is implemented yet to complete what is needed.  I will find the GitHub issue.

**Comment by live1206** [comment]
No, there is no logic in place to notify the completion yet.
I think this bug is resolved for now.
