### ISSUE TITLE
Missing SDK meetings from Release Planner app Scheduled Reviews page

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5516]
I scheduled an SDK meeting for my release process 1182 and it is not showing up in the Release Planner "Scheduled Reviews" page:

![image](https://user-images.githubusercontent.com/9868623/219811147-f150de6b-785b-47e9-ae7f-d4319303191d.png)

![image](https://user-images.githubusercontent.com/9868623/219811172-7c70982c-e539-44b6-a1d7-80268d9293ba.png)

**Comment by zzvswxy** [comment]
The 2nd pic shows the meeing as expected 
![image](https://user-images.githubusercontent.com/20081898/220032155-4465018c-43f3-4988-bbae-bdc10d7446d2.png)
Could you please recheck it? @maririos

**Comment by maririos** [comment]
You are right! I tried again and it showed up correctly. 
Apologies for that
