### ISSUE TITLE
[both mgmt plane & data plane] All supported languages must be selected when new version

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#5519]
![image](https://user-images.githubusercontent.com/18413981/219993413-10c18d1b-ea45-4580-9603-632b0c5395c0.png)

The only time we believe that the default would not be all languages is if there is a need to resolve a hot fix/bug in a specific language.  For this reason, the "Supported languages to be released" in the blade should behave as below

1. if, by all means, we can know the release plan is for a new API version (either 1st beta or 1st GA for APEX language, or creating a new API version indicating in the spec pull request with a label "new-api-version"),  all supported languages should be selected, and disabled for unselection.  The message displaying under the checkboxes is "_- For cross language coverage consideration, you need to release SDK libraries of all supported languages when creating new API version._" 
2. If it is NOT 1st beta or 1st GA for APEX language, or NOT creating a new API version indicating in the spec pull request with a label "new-api-version", it should allow user to uncheck any supported languages with justification.  The message displaying under the checkboxes is "_- For cross language coverage consideration, please ensure to have business justification to uncehck any supported language._"

**Comment by zzvswxy** [comment]
DPG SDK Release App done in Prod

**Comment by zzvswxy** [comment]
deployed to Prod
