### ISSUE TITLE
SwaggerAPIView fallback machanism by using changed swagger files directly

### ISSUE THREAD

**Issue by ruowan** [Azure/azure-sdk-tools#5521]
In some spec PRs, the readme tag format is wrong. It cause our pipeline cannot found affected readme tag and swaggerAPIView cannot be generated. 

We want every changes should have APIView. So in above case, we will directly use changed swagger file to do APIView. And also this fallback machanism will suport cadl+dpg scenario which without readme file.

Here is a sample PR https://github.com/Azure/azure-rest-api-specs/pull/22331

**Comment by chidozieononiwu** [comment]
For this we should just inform PR owners to update their readme with the correct tag.
