### ISSUE TITLE
Feedback list for API readiness App and Release Planner

### ISSUE THREAD

**Issue by honghr** [Azure/azure-sdk-tools#5522]
Critical/bugs found:
 
1.	https://github.com/Azure/azure-sdk-tools/issues/5506
2.	https://github.com/Azure/azure-sdk-tools/issues/5510
3.	https://github.com/Azure/azure-sdk-tools/issues/5511
4.	[@LaDonna](mailto:ladonnaquinn@microsoft.com) or [@Josephine](mailto:yiqiu@microsoft.com) should we remove/hide the “Generate SDKs and APIView” all together from the API Readiness app as we saw in the UX studies that it creates confusion with the customers? While we understand better how people will use this information, they can always go to the PR and access it there.
              If the decision is to leave it, we should improve the experience for when the Cadl validation failed and therefore no generation was possible.
5.	Schedule API Review meeting: issue https://github.com/Azure/azure-sdk-tools/issues/5893
a.	To be consistent with the documentation, can we rename both the left menu panel and the title of the page to say “Schedule API Review meeting.”
b.	The link in API Stewardship Review is wrong. It should be: [Azure REST API Stewardship Review - Overview](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fazure-sdk%2Finternal%2F_wiki%2Fwikis%2Finternal.wiki%2F665%2FAzure-REST-API-Stewardship-Review&data=05%7C01%7Chaoranhong%40microsoft.com%7C681dcb8b534d4871c29808db131a723f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638124776564549765%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NyCVz8Ad3NQ6h5YDxG2c4P1YTc7HBonC3iLBe0J55BE%3D&reserved=0)
c.	Scheduler tool should populate the API Spec PR. I created issue for Scheduler team https://github.com/Azure/azure-sdk-tools/issues/5500
d.	Once meeting is created, I love that we can see the information about the meeting in the Release Planner apps. Comments:
                                                               i.      The API readiness app hast a link to the title of the meeting but points nowhere. Looking at the SDK  archboard review page, it contains a column for “Review or update artifacts” this is great! We could do the same for API Review
                                                             ii.      We are currently not populating any data into the “Meeting Notes” column, so I suggest removing it.
6.	https://github.com/Azure/azure-sdk-tools/issues/5512
7.	I got blocked on the SDK Readiness app after scheduling a review meeting. I believe because the meeting hasn’t happened, but that shouldn’t be the case, as I will need to generate SDKs and have the APIViews in order to go to arch board. [@LaDonna Quinn](mailto:ladonnaquinn@microsoft.com) for input here
 
General feedback:

1. https://github.com/Azure/azure-sdk-tools/issues/5503
2. https://github.com/Azure/azure-sdk-tools/issues/5505
3. https://github.com/Azure/azure-sdk-tools/issues/5504
4. https://github.com/Azure/azure-sdk-tools/issues/5513
5. https://github.com/Azure/azure-sdk-tools/issues/5514
6. https://github.com/Azure/azure-sdk-tools/issues/5516

**Comment by maririos** [comment]
All the feedback here has a respective issue. Closing
