### ISSUE TITLE
Management Plane: Testing in PPE for new API version (Azure Orbital) 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5527]
**Scenario**

**Service:** Azure Orbital 
**PR:** https://github.com/Azure/azure-rest-api-specs/pull/22080
**Apps tested:** Release Planner and API Readiness App
**API/SDK scenario:** New preview API version, new preview SDK version

- [ ] In the labels on the PR, I see Approved-BreakingChange as well as approved breaking change label for Java, JavaScript, and Go.  However, The screen still shows that there is an error for breaking changes cross version.  Which label or combination of labels corresponds to this check?  Or is this a check that does not have a corresponding label?  
- [ ] ARM did sign-off. So what label(s) or other logic is used to indicate the status on the ARM API review screen?  

![image](https://user-images.githubusercontent.com/67656762/220439596-6d706058-8e0c-4dbb-a768-5d21513ab97a.png)

![image](https://user-images.githubusercontent.com/67656762/220439468-597a152f-7a43-4094-a1bb-ba78a9aceda0.png)

![image](https://user-images.githubusercontent.com/67656762/220439351-248ab642-bf5d-496b-a711-ddd89adae9fc.png)

**Comment by live1206** [comment]
It seems like the validation result does not take approval labels into consideration, which should.
Same thing goes for ARM Review page.

**Comment by maririos** [comment]
This has been address witht he `1.0.0-beta.8` deployment
