### ISSUE TITLE
[stress] Credentials need to be rotated for the stress test deployment

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#5529]
Here's a failed pipeline: [link](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2201074&view=logs&j=38a05975-7697-5434-099a-d7b3d4012883&t=b1e71580-9408-50be-13a0-b0783b8cb008&l=43)

This causes a follow-on error where the dashboard fails since there were not tests running:

```
Query could not be parsed at ')' on line [23,79]
Token: ')' Line: 23 Postion: 79 
```

Btw, @benbp, it looks like @ckairen doesn't have rights to do this directly but probably should.

**Comment by ckairen** [comment]
The pipeline failed because the secrets for the secrets for the service connection that we use expired. We're using the "Azure SDK Test Resources" service connection which is owned by Wes.

**Comment by ckairen** [comment]
Secrets have been rotated. There's still broken stress tests that caused pipeline job failures. Dashboard issue resolved.
