### ISSUE TITLE
Remove ability to set local spec root in cadl-location.yaml

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#5530]
https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Cadl-Project-Sync.ps1#L117

https://github.com/Azure/azure-sdk-tools/issues/5288#issuecomment-1439043756

**Comment by konrad-jamrozik** [comment]
@weshaggard I am removing this from `Spec PR Tools` as it looks to be `SDK Automation` instead to me. FYI in case I am mistaken.
