### ISSUE TITLE
Close SDK Release request issues and SDK PRs when a release plan is canceled

### ISSUE THREAD

**Issue by zzvswxy** [Azure/azure-sdk-tools#5542]
When a release plan is canceled. We should clean up the table about the flow. Before the clean we should close the SDK Release request issues and SDK PRs.

**Comment by live1206** [comment]
We should apply this while a new API Spec PR is associated as well.

**Comment by maririos** [comment]
Can you currently cancel a release plan?

**Comment by live1206** [comment]
> Can you currently cancel a release plan?

No, we do not have the cancel functionality right now. 
This is needed for API Spec PR re-association for now.

**Comment by maririos** [comment]
There is no automation in the current Release planner apps so this is no longer applicable.
