### ISSUE TITLE
[back log]ideas from SDK release App users

### ISSUE THREAD

**Issue by zzvswxy** [Azure/azure-sdk-tools#5543]
1 Prerequest panel ：'APIStewardshipBoard-SignedOff' label may not sign
2 Generate sdk panel： can wei show pipeline error more directly
3 Rlease panel：meaning of complete button? can we show the status as a label or add a cancel button
4 release planner step status panel: show meeting step status with real meeting status
5 spec PR merged, but cadl need update(for example: name space): add a button to let user regenerate SDK rely on main branch

**Comment by ladonnaq** [comment]
Adding this issue to the epic for new UI to reevaluate input.

**Comment by maririos** [comment]
Most of this has been covered or is no longer applicable. Closing
