### ISSUE TITLE
Schedule API Review meeting disabled after I scheduled a meeting

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5550]
See: 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/9868623/220786625-4f616f0a-8296-41db-b42e-eb847f095e74.png">

Is this intentional until the meeting is not completed?

I will like to still access the information of the meeting but because the panel is disabled, I can't. I need to go to `Generate SDKs and APIView` and hit `Next`

**Comment by ladonnaq** [comment]
@maririos We should not be blocking teams from "looking ahead".  I don't see this behavior in the current implementation of the API readiness power app.

**Comment by maririos** [comment]
Oh good. Maybe this is not present anymore. Praveen also confirme this. I am going to clsoe the issue then
