### ISSUE TITLE
Cadl rename to TypeSpec

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#5553]
Cadl has renamed to TypeSpec.  Ensure to update wording and links related in the SDK Release App

Cadl -> TypeSpec
Getting started Docs:  https://aka.ms/cadl/azuredoc -> https://azure.github.io/typespec-azure/

**Comment by zzvswxy** [comment]
We need to change it by follow sequence: Cadl -> SDK emitter -> SDK automation pipeline -> Powerapps. For now, we can only edit the static word just like Note or describe. But leave the pipeline related text to CADL.
CC:  @maririos

**Comment by maririos** [comment]
Information from Ray:

>With this [PR](https://github.com/Azure/azure-sdk-tools/pull/5809) change, sdk generation docker image would support typespec naming. Please change the image name to `sdkgeneration.azurecr.io/sdk-generation:beta-1.1` if you want to keep using the old image with cadl naming in SDK release app.

**Comment by ladonnaq** [comment]
@maririos Is this done?   If not, can you put exactly what needs to be done in the description.
