### ISSUE TITLE
[ShiftLeft] Usability enhancement of API Spec Pipeline

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#5554]
1. revamp the wikis https://aka.ms/shiftleft
2. further automation of installation

Documentation requirements are associated with API readiness app documentation epic - https://github.com/Azure/azure-sdk-tools/issues/5628
New wiki structure 
![image](https://user-images.githubusercontent.com/18413981/220813922-c182391f-c544-4ebe-a4e7-499d22c562a5.png)

**Comment by weshaggard** [comment]
Closing this as it is outdated at this point as we aren't supporting shiftleft any longer and some of the other stuff here is being handled by the release planner.
