### ISSUE TITLE
Data Plane API readiness: Remove Generate SDKs and APIViews from the API Readiness app 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5560]
- [ ] At this time the arch board will review SDK breaking changes and generated SDKs after the REST API Stewardship Board has approved the TypeSpec/generated OpenAPI doc.  In order to not cause confusion, remove the Generate SDKs and APIViews screen from the API readiness app. 

![image](https://user-images.githubusercontent.com/67656762/220971091-c2d7e3ca-ff27-4dc8-a49f-f48b964aa0ca.png)

**Comment by maririos** [comment]
I am going to see if I can "hide" it for now, instead of removing it

**Comment by praveenkuttappan** [comment]
Do we need this change for Management plane API readiness app also? I assume yes. Please confirm. @maririos @ladonnaq

**Comment by maririos** [comment]
> Do we need this change for Management plane API readiness app also? I assume yes. Please confirm. @maririos @ladonnaq

Yes :)

**Comment by ladonnaq** [comment]
> > Do we need this change for Management plane API readiness app also? I assume yes. Please confirm. @maririos @ladonnaq
> 
> I don't know as generated SDKs are different for Management plane. This issue is specific to Data plane thoguh so maybe not?

Mangement plane SDK breaking change review does happen during API readiness for management plane so we should keep the SDK screen for management plane but hide/remove it for data plane.
