### ISSUE TITLE
Swagger diffs aren't useful without sorting or semantic diffing of some kind

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#5563]
Related to #676 swaggers and their various sections (info, paths, etc.) - perhaps even TypeSpecs - should be sorted by file, section, etc. Even just doing a recursive token sort before diffing would help. Otherwise, without sorting, a diff is effectively useless as almost everything appears different. 

Take <https://apiview.dev/Assemblies/Review/435f3c2da7e64f5a854a2b580adeb734?diffRevisionId=7f48c2acdb8c427eb613048dfbaf03d3&diffOnly=False&revisionId=19cf5f8f5d98406cbee84939d2cef8dc&doc=False#> for example. There's actually very few changes between it and the previous version, but because files were processed in a different order (it seems), paths - most of which appear exactly the same otherwise - show as dropped in the new but also added:

![image](https://user-images.githubusercontent.com/1532486/221045269-c912fb28-449e-4ef6-bc12-ddb70cb776e3.png)

While I love the structure of how the swaggers are rendered - both in the left and right views - I can't use the diff this way because it's impossible to see any *actual* changes, which can lead to reviewers missing critical changes.

**Comment by heaths** [comment]
I wonder if just sorting the files as a first step would work. Not sure in what order they are processed now, but if it's just the order the file system or git returns this, this won't be stable. So as a (hopefully) simple fix, maybe just sorting the file names alphabetically would eliminate most of the problems seen here. Teams moving paths, definitions, and/or parameters needlessly around in the file should be rare, but a full semantic diff at some point could eliminate that but would be lower priority.

**Comment by mikekistler** [comment]
Dup of #5556
