### ISSUE TITLE
[OpenAPI Hub] Service teams should be guided to create a feature branch for new versions

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#5569]
When creating new service features in [OpenAPI Hub](https://aka.ms/openapihub), service teams should be guided to create a feature branch. Personally, as a "code owner" for many services, I prefer seeing PR validation on each PR targeting the feature branch, but 1) appreciate not every service team might want to work this way, but 2) checks against PRs targeting a feature branch should not be *blocking*. I believe @weshaggard already made the changes necessary for this a while back, but we should double check. But perhaps we leave either of the last two options - as currently listed in the screenshot below - up to service teams:

![image](https://user-images.githubusercontent.com/1532486/221269530-f3d1d336-469e-451f-b90e-656cabfdcc28.png)

I would even argue that we should remove the first option - to create a one-and-done topic branch/PR. Never through the API Stewardship Board have I seen a single PR from a single engineer create an entirely new and complete api-version.

Per our [Breaking Changes Policy](https://aka.ms/AzBreakingChangesPolicy), once specs are in `main` they are published and considered "done". Ergo, devs should not treat `main` for in-development work.

Ideally, we add a link to that section in OpenAPI Hub directing them to our [walkthrough](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/630/Walkthrough-Creating-a-new-service-specification-in-a-team) for service partners. This is the walkthrough for the currently recommend specs process - not the prototype "dev" workflow, mind you.

/cc @mikekistler

**Comment by konrad-jamrozik** [comment]
Related to:
- #5290

**Comment by heaths** [comment]
Could we get this change in? Service teams should not be developing in `main`. That's when/where we consider swaggers/typespecs to be published for a particular api version.

**Comment by weshaggard** [comment]
>Per our [Breaking Changes Policy](https://aka.ms/AzBreakingChangesPolicy), once specs are in main they are published and considered "done". Ergo, devs should not treat main for in-development work.

@heaths where in that policy does it state that? I don't doubt this might be the expectation but I'm wanting to be able to point to an explicit policy doc for it. 

Also, it isn't clear to me from your description which of those options violates the development in main policy. All those options create a branch that changes go into. In fact, the first option is the only one that create a branch that can be edited without requiring any branch protection and gives folks the most flexibility. Is the issue that the first option create the branch and also create a PR against main for that branch? Should the option instead be to just create the branch let them stay there and only when it is ready be PR'ed against main?

**Comment by weshaggard** [comment]
@maririos add you to help figure out the process and if we need a change in OpenAPIHub that might be someone on your team making that.

**Comment by heaths** [comment]
> @heaths where in that policy does it state that? I don't doubt this might be the expectation but I'm wanting to be able to point to an explicit policy doc for it.
> 
> Also, it isn't clear to me from your description which of those options violates the development in main policy. All those options create a branch that changes go into. In fact, the first option is the only one that create a branch that can be edited without requiring any branch protection and gives folks the most flexibility. Is the issue that the first option create the branch and also create a PR against main for that branch? Should the option instead be to just create the branch let them stay there and only when it is ready be PR'ed against main?

@weshaggard the Board has long maintained that `main` means "published", thus many - even most - changes to specs already in `main` are breaking. @JeffreyRichter I seem to recall you adding text to this effect to the breaking changes document so it was more obvious. I remember we had discussed this.

The first option seems to imply it creates a feature branch, but last I tried it's merely a normal topic branch and even the text reflects that,

> recommended option if you want to edit this branch directly

In practice, I'd be surprised if that ever happens. Even if it was intended, I've seen other people have to jump in and try to make PRs to a topic branch because the originator is unavailable. It's happened in Cognitive a couple of times.

Even if we don't eliminate that option, we should be encouraging teams to always create feature branches because you can't predict the future, and maintaining a single-author branch isn't practical.

**Comment by maririos** [comment]
@heaths are you suggesting we remove the first option ?

**Comment by heaths** [comment]
Initially, yes; however, after discussing it last week with you et. al., I think we should put it third and make either of the first 2 default. In practice, it's usually more than one person working on it and it's easier for reviewers - service buddies - to review in bite-sized pieces, so I prefer the current third option. Reviewing a massive update all at once is cumbersome and it's easy to gloss over some changes.

**Comment by maririos** [comment]
Work will be included as part of https://github.com/Azure/azure-sdk-tools/issues/5657
