### ISSUE TITLE
Sync specs from source branch of ADO PR to Github instead of from merged branch

### ISSUE THREAD

**Issue by xiaoxuqi-ms** [Azure/azure-sdk-tools#5580]
As in this pr: https://github.com/Azure/azure-rest-api-specs-pr/pull/11349
extra commits are added after the pr is approved: https://github.com/Azure/azure-rest-api-specs-pr/pull/11349/commits/4e16257c01146da32383b48e03c40f0d7f2b40dc
When ADO pr is merged, the github cannot be auto merged since "new" commits are detected. This breaks the API Spec workflow.
Root cause: steps in API Spec sync pipeline: "Checkout aks-rp@refs/pull/7645623/merge to s" uses merged branch to sync specs, but in this scenario, only the specs from source branch should be synced.

**Comment by kurtzeborn** [comment]
Seems like this is related to shift-left.  Probably not going to do this since we're rethinking shift-left all up right now.
