### ISSUE TITLE
Flattening of nested models is really confusing in APIView for Swaggers

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#5582]
Based on the [swagger](https://github.com/Azure/azure-rest-api-specs-pr/pull/10984/files#diff-23eae4087bc8890bcfaf2e2d2377fb488fceab050b0603a432239998e1d6eb1f), only a `ResolvedConstentList` is returned, but this "flattening" of models makes it seem like either could be returned:

![image](https://user-images.githubusercontent.com/1532486/221982608-34d6dfb1-fbe8-4581-87ab-108a448193b4.png)

See [APIView](https://apiview.dev/Assemblies/Review/55c63933481d450b88a2c1524702373f#-consent.json-Paths-/checkConsent-0-operationId-Consents_Post) for more examples.

I would just show the response model (if any) and make sure the properties are linked to the definitions.

**Comment by mikekistler** [comment]
This will be a change in the parser. Should not be too hard but we need to investigate.

**Comment by heaths** [comment]
In the interim, how hard would it be to link to the original swagger - whether in a PR or whatever the originating branch is from? Often times I feel confused by APIView (like this as a prime example) and need to double check with the swagger.

**Comment by maririos** [comment]
> In the interim, how hard would it be to link to the original swagger - whether in a PR or whatever the originating branch is from? Often times I feel confused by APIView (like this as a prime example) and need to double check with the swagger.

You mean to correlate a specific teable/view with the respective line in Swagger?
or is the `Associated Pull Request` view enough
<img width="952" alt="image" src="https://user-images.githubusercontent.com/9868623/223208049-cd0f0a54-218e-4a96-b851-26bd9945503e.png">

**Comment by heaths** [comment]
The PR is sufficient, since I can still view the individual swagger that way: either the diff, or click "View file" on the web to view the whole file. Thank you. I had not noticed that. I typically collapse options.
