### ISSUE TITLE
[APIView] UI Improvements

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#5585]
Improvements to APIView UI based on feedback.

First suggestion: give more vertical space by moving the navigation tabs to icons on the left, and the footer area into the 'options' area:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/31145988/222003850-dd62489a-ae79-489d-ab4a-6fd160a5a606.png)

Second suggestion: vertical separators differ from left and right - it would be nice (although super unnecessary) to unify them into a single style:

![MicrosoftTeams-image2](https://user-images.githubusercontent.com/31145988/222003802-9045dff6-c98d-4e0b-ab13-1647cfda73ac.png)

Improve Diagnostics Comment
Try changing the col
![MicrosoftTeams-image](https://user-images.githubusercontent.com/31145988/236335312-4c27f2e2-8549-47cd-baca-ccd341718fce.png)
or to orange, add a warning icon and also add a summary at the top. like No. of warnings: , No. of errors:

**Comment by JonathanGiles** [comment]
For the icons, you could consider the following:

API: https://icons.getbootstrap.com/icons/braces/
Conversations: https://icons.getbootstrap.com/icons/chat-dots/
Revisions: https://icons.getbootstrap.com/icons/clock-history/
Usage Samples: https://icons.getbootstrap.com/icons/puzzle/

**Comment by maririos** [comment]
Most of the issues identified here have been addressed based on feedback from users
