### ISSUE TITLE
Resolved comment should be less intrusive 

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#5606]
After a comment is resolved, it lingers in the API view:
<img width="675" alt="image" src="https://user-images.githubusercontent.com/9724236/222571001-48afa104-631e-43fa-a663-01800c6b0c43.png">

After many revisions (months and years), such resolved comments just make the API listings messy. Could resolved comments be represented by inobtrusive side glyphs, as opposed to taking additional lines of the listing?

**Comment by praveenkuttappan** [comment]
This is handled in new UI. It will be taken care for other languages when they move to new parser.
