### ISSUE TITLE
Update references to cadl to refer to typespec

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#5610]
We need to rename this [file ](https://github.com/Azure/azure-sdk-tools/blob/main/doc/common/Cadl-Project-Scripts.md) and update the references to cadl-location.yaml to typespec-location.yaml

We need to rename [Cadl-Project-Sync](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Cadl-Project-Sync.ps1) and [Cadl-Project-Generation](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Cadl-Project-Generate.ps1) to be typespec and change all code mentions of cadl.

**Comment by chunyu3** [comment]
This is already completed.
