### ISSUE TITLE
API Readiness Documentation (outbound links from release planner)

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5628]
This epic will track all of the documentation requirements associated with the SDK release milestone.
Associated Release Planner documentation epics: 

- https://github.com/Azure/azure-sdk-tools/issues/5618

API Readiness documentation: 

- [ ] https://github.com/Azure/azure-sdk-tools/issues/5554

**Comment by maririos** [comment]
This has been done https://eng.ms/docs/products/azure-developer-experience
