### ISSUE TITLE
UX enhancements: SDK Release app 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5632]
This epic will be used to track the new UI design for the SDK release app. 

**UI design link:** TBD

**_Associated GitHub issues:_** 
- [ ] https://github.com/Azure/azure-sdk-tools/issues/4381

**Comment by ccbarragan** [comment]
Status: Deprioritized in favor of documentation updates. 

Pending from Crystal: Project kickoff for us to review the existing experience, understand end to end process, and start to put together some action items to start design work.

**Comment by ladonnaq** [comment]
Created a new epic and adding any issues that related to the new UI.  During kick-off for start of new UI, we should review all issues in the epics and make sure all outstanding feedback and requirements are completed.  https://github.com/Azure/azure-sdk-tools/issues/5659
