### ISSUE TITLE
APIView: updates needed for rename of Cadl to TypeSpec

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#5635]
I created an APIView with the language property set to `TypeSpec` to see what impact this would have on the web side:

- [ ] Language dropdown needs TypeSpec added and should remove "Cadl". 
- [ ] Create review language dropdown. Replace Cadl with TypeSpec. Update terminology.
- [ ] Add Revision. Replace Cadl with TypeSpec. 

For all above cases, APIView should internally recognize that any existing APIVIew's labeled Cadl should be treated as TypeSpec.

I also tried adding a TypeSpec revision on top of a Cadl revision and this worked mostly fine. The only issue is that adding a rev on top of the TypeSpec one would not give you a language dropdown, but that would presumably be fixed when the above are addressed.

**Comment by chidozieononiwu** [comment]
A few questions about how far the rename should go, specifically as relates to the [LanguageService](https://github.com/Azure/azure-sdk-tools/blob/main/src/dotnet/APIView/APIViewWeb/Languages/CadlLanguageService.cs)
will the file extensions also be renamed i.e .cadl to .typeSpec and will this need to be backward compatible with the existing name.  //cc @praveenkuttappan @maririos

**Comment by tjprescott** [comment]
The *.cadl file extension is renamed to *.tsp

Do we use that anywhere?

**Comment by chidozieononiwu** [comment]
> The *.cadl file extension is renamed to *.tsp
> 
> Do we use that anywhere?

https://github.com/Azure/azure-sdk-tools/blob/7c10ce5ef4641263b81e775aa181d82750a83da1/src/dotnet/APIView/APIViewWeb/Languages/CadlLanguageService.cs#L19

**Comment by tjprescott** [comment]
Ah, well, to whatever extent that is used, APIView probably continue to recognize `Cadl` as `TypeSpec` and `*.cadl` as `*.tsp`.
