### ISSUE TITLE
[stress] switch the network-chaos example to use curl, instead of wget

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#5643]
The chaos-network example uses wget, which is no longer included in the base mariner image as of 2.0.

We should be able to swap over to using 'curl' instead, which has equivalent options:

`curl -XHEAD <blah>` should do what we want, without following redirects.

**Comment by kurtzeborn** [comment]
@ckairen already fixed this. (per @benbp )
