### ISSUE TITLE
Swagger APIView support cadl+dpg scenario

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5646]
Example PR: https://github.com/Azure/azure-rest-api-specs/pull/22167.

Currently swagger APIView are based on readme file. For cadl+dpg senario, there is no readme file checkin, the swagger APIView won't be generated.

**Comment by mikekistler** [comment]
I think we need to maintain the README.md even if not used by DPG because it is needed for REST API Docs generation.
