### ISSUE TITLE
Remove the release plan review screen from the release planner 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5661]
The screen that displays the preview the release plan is not useful and is found to be confusing per user feedback (user study with stakeholders).  

- [ ] Remove the screen from the create a release plan UI flow 
![image](https://user-images.githubusercontent.com/67656762/223850671-a6fa1231-9d3d-46e5-ad9d-aa0ecf34eea7.png)

**Comment by maririos** [comment]
Dup of https://github.com/Azure/azure-sdk-tools/issues/5305
