### ISSUE TITLE
Change "launch date" to SDK release date in the Create a release plan screen 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5671]
- [ ]  This needs to be changed but it is incorrect.  A service team can only change the product launch date from service tree.  This field should be to set the SDK release date.  Management plane release monthly and TypeSpec + DPG is releasing anytime from what I understand.  Perhaps we just allow a user to select a month as a target date and then in the SDK release app they would select the actual release train (management plane) or date (TypeSpec + DPG)
- [ ] 
![image](https://user-images.githubusercontent.com/67656762/224127733-b2fe49e2-8b41-43b4-b440-265309e1b697.png)

**Comment by maririos** [comment]
@ladonnaq if I understand correctly, that means that Q2. should change to `What's the target month for SDK Release` ? and questions Q2.` and Q2.2 should be deleted from the view, same with the `Target Phase` information?

**Comment by maririos** [comment]
I need to look at the logic underneath and see what are the implications for that change. I imagine we want to save the Target month in the Release Plan itself....

**Comment by ladonnaq** [comment]
> I need to look at the logic underneath and see what are the implications for that change. I imagine we want to save the Target month in the Release Plan itself....

I think that we should have teams choose the month when they create a release plan and we store the data in the Release Plan. 
Then when they get to SDK release milestone, we should have the exact timeline should be specified.  For example, Cala's wiki provides this information.  
![image](https://user-images.githubusercontent.com/67656762/230420623-fb92be02-de17-41f4-94ca-b67099111639.png)

Right now, there is inconsistency between management plane, data plane that is not TypeSpec + DPG, and TypeSpec + DPG.  I believe that we should have consistency across our approach to releasing SDKs.  TypeSpec + DPG for data plane should follow the same schedule as Cala has in place for the other data plane SDKs.  This is what happens for management plane TypeSpec + code generation - they are following the same release schedule as teams using OpenAPI + code generation.  

- Management plane monthly release  - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/761/Management-SDK-Release-Cycle
- Data plane monthly release (everything except TypeSpec + DPG) -  https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/448/Monthly-Release-Schedule.  Java, JavaScript, Python, and Go SDK releases are requested via OpenAPI Hub and the expected release dates are indicated on the form.  .NET release requires manual steps that the service team must complete (similar to DPG I am told).  We are asking the service teams to line up to the release of the other languages.  We will still do releases out of cycle for product/service announces and such (i.e. Build) but teams have to send an email to request.  Also, keep in mind that only .NET SDK is required to be tested with the test published in the .NET SDK repo. 
- Data plane TypeSpec + DPG - There is process clearly documented and I was told by Allen that since the service teams are doing the work to release the SDKs (as it is not automated like management plane Java, JavaScript, Python, and Go), they let service teams release whenever they want.

**Comment by maririos** [comment]
We can add as a goal of the Engagement Experience to organize the Release trains.
For now and for this UI though, what is it that you want Eng to change?

**Comment by maririos** [comment]
Other clarification, this field should only be shown when the Service's Lifecycle is different than Private Preview, right?
In that case, there is no SDK so no `SDK Release Date`

**Comment by maririos** [comment]
@ladonnaq  ping on this issue

**Comment by ladonnaq** [comment]
> We can add as a goal of the Engagement Experience to organize the Release trains. For now and for this UI though, what is it that you want Eng to change?

For now we can let team's choose the target month for release, not the actual date.  Later on in the SDK release app we should confirm the either the release train (management plane) or the release date (data plane).  I think at this time the service teams using TypeSpec + DPG are choosing the date they will release because they are doing the work.  Is that correct?  

For question 2.2 - we would just let them choose another lifecycle milestone and we should already have that date stored because it is in the ADO work item and should be in dataverse.  We can show that date to them but they cannot change it unless they go to service tree.

**Comment by ladonnaq** [comment]
> Other clarification, this field should only be shown when the Service's Lifecycle is different than Private Preview, right? In that case, there is no SDK so no `SDK Release Date`

There is no SDK for Private Preview.  During private preview a service team is working on either or new or updates to existing REST APIs (management and/or data plane).

**Comment by maririos** [comment]
@ladonnaq ping on this issue again

**Comment by ladonnaq** [comment]
> @ladonnaq ping on this issue again

I added my comments in bold earlier this week.  Can you look and provide additional feedback on what approach you think is best for ADO updates?

**Comment by maririos** [comment]
I think we are good. We need to look at the fields in ADO and edit/create them

**Comment by JonathanCrd** [comment]
# Summary of changes done

## _Create a Release Plan_ screen:
Several layout, texts, and UI changes to avoid confusion and make the questions clearer.

- Grouped questions into three categories: Basics, API details, and Release Details
- Specified that the lifecycle is for the product
- Moved option to open product details in Service Tree to right below the question where it asks for the product
- Removed option to create both Management and Data plane release plans
- Added two new questions:
   - To specify the SDK type (Preview or Stable)
   - To specify what is the SDK release target month (Month/Year)
- Complete redesign on the second and last screen:
   - It asks for confirmation of the information provided. No other information is shown.
   - Removed the section to select proposed release plans.
- Visual enhancements in both screens.


![CreateDemo](https://github.com/Azure/azure-sdk-tools/assets/17486462/948a76fa-555b-42ba-a6a7-8fd433e7a450)

## _Release Plan details_ screen:

- Created a new "Summary" screen to show all the Product, API and Release details, as well as the contacts, and a share URL. 
   - Added all new fields that were introduced in the Creation process
   - Removed unnecessary product details
   - Added a link to open Product in Service Tree
- Cleaned up Milestones screen, by removing information that is already shown in the Summary screen

![image](https://github.com/Azure/azure-sdk-tools/assets/17486462/6e1ff874-6f85-423f-a195-f0b5aa808606)


## Next steps:
- https://github.com/Azure/azure-sdk-tools/issues/6370
- Continue working towards the new UI.

Hopefully with these changes users are gonna be less confused and information should be clearer for them.
