### ISSUE TITLE
Create an GitHub issue template for management plane naming approval 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5680]
This task is associated with the issue tracking Management plane: Naming Review - Azure DevEx Arch Board- https://github.com/Azure/azure-sdk-tools/issues/4601. 

Using the existing GitHub issue is confusing for management plane teams.  We have had more than one team confused.  Until we can execute the plan suggested in https://github.com/Azure/azure-sdk-tools/issues/4601 having a separate GitHub issue just for management would clear up confusion and make the process easier for our service teams.  

- [x] Create a new issue template that is specifically for naming approval for new initial management libraries.  
- [x] Review and update the Naming approval wiki page - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/821/Naming-for-new-initial-management-or-client-libraries-(new-SDKs).

**Comment by ronniegeraghty** [comment]
Completed the two tasks in the task list.
