### ISSUE TITLE
 Data and Management Plane: New initial beta SDK and new beta or stable SDK version release plans for TypeSpec + DPG

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5701]
Requirement for Epic of things that need to be resolved in current release planner core app - https://github.com/Azure/azure-sdk-tools/issues/5662
At this time a user can only create a new initial SDK release plan. There are differences between a new initial SDK and a new SDK version.  Typically, service teams that are launching new major releases/products will be releasing initial SDKs (client libraries).  Teams that have existing SDKs (client or management libraries), follow a modified process. 

### Data Plane 
**New initial beta SDK (client libraries)** 
- Namespace approval is required for all new client libraries (SDKs) 

**New initial stable SDK (client libraries)** 
- Remove namespace approval as it was done as part of initial beta SDK release requirements
-  Arch Board intro meeting required 
- Arch Board approval for Java, JavaScript, Python, and .NET client library releases 

**New beta SDK version (client libraries)**
- Remove namespace approval as it was done as part of initial beta SDK release requirements
- Namespace approval is required for all new client libraries (SDKs) 
- SDK breaking change review by Arch Board 

**New stable SDK version (client libraries)**
- Remove namespace approval as it was done as part of initial beta SDK release requirements
-  SDK Review meeting required 
- SDK breaking change review by Arch Board
-  Arch Board approval for Java, JavaScript, Python, and .NET client library releases 

### Management Plane 
**New initial beta SDK (management libraries) ** 
- Namespace approval is required for all new management libraries (SDKs) 

**New initial stable SDK (management libraries) ** 
- Remove namespace approval as it was done as part of initial beta SDK release requirements
- Arch Board may review initial stable management .NET library (we need to find out if this is should always be required or if there is something that triggers this review.  @josefree  - Do you know? 

**New beta SDK version (management libraries) **
- Remove namespace approval as it was done as part of initial beta SDK release requirements
- SDK breaking change review done as part of API readiness 

**New stable SDK version (management libraries) **
- Remove namespace approval as it was done as part of initial beta SDK release requirements
- - SDK breaking change review done as part of API readiness

**Comment by maririos** [comment]
This change is independent of the UI and is more of a functionality. Do we want to do this in the current UI instead of waiting on the new UI?  what is the percentage of teams that will be blocked if we wait on this one?

**Comment by ladonnaq** [comment]
> This change is independent of the UI and is more of a functionality. Do we want to do this in the current UI instead of waiting on the new UI? what is the percentage of teams that will be blocked if we wait on this one?

I would prefer we do this asap because it is blocking onboarding to the release planner app for management plane.  Since naming has not been implemented for data plane it is not blocking.  So we could make the changes in the new UI for data plane and a minor change to support mgmt plan with current UI.

**Comment by maririos** [comment]
Management plane: The current UI is already talkign about this and even has a field to include the review tiquet: 


![Image](https://user-images.githubusercontent.com/9868623/232553098-a04079de-faf0-49da-8ab8-b2bd456d34d2.png)

Data plane: It looks like all this changes are part of the SDK Release App. 

Based on this I am going to move the issue to the SDK Release Epic

**Comment by ladonnaq** [comment]
@maririos When can we create a release plan for new beta and stable SDK versions for management plane and data plane (TypeSpec + DPG)?   The steps are very similar only difference is SDK release requirements.  (i.e. namespace approval required for initial beta library release for management and data plane, ...).

**Comment by maririos** [comment]
This has been included in the new verison of the SDK release apps
