### ISSUE TITLE
Scheduling Tool and Interest Group to Azure SDK Arch Board Reviews

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-tools#5705]
When the Scheduling Tool sends out meeting invites for an Azure SDK Architecture Board Review it should also send an OPTIONAL invite to the Azure SDK Arch Board Interest alias: adparch-interest@microsoft.com

**Comment by maririos** [comment]
@ronniegeraghty  you can do this in the Admin app: https://apps.preview.powerapps.com/play/67ea5667-6bf9-4e67-8bb6-3bf1c88c3e42 uner `Event Reviewers`

**Comment by ronniegeraghty** [comment]
@maririos Thank you. Think I added it correctly.
