### ISSUE TITLE
[CadlValidation CI step][question/discussion] Can we remove the requirement to check in a TypeSpec generated openapi spec?

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-tools#5709]
CadlValidation step checks that the generated openapi spec is checked in as part of TypeSpec PRs. I think the openapi spec is currently used for docs and some other tooling, but can this be automated to remove the requirement for generating and checking in the openapi spec? I'm mainly wondering whether this is necessary and if it will always be a required check. 
Why have services generate this manually and wait for CI to pass if this could be automated somehow? 

We can have this discussion further down the line, but wanted to start a discussion on this.

**Comment by mikekistler** [comment]
I agree that generation of the openapi should be automated. Currently the ~~Cadl~~TypeSpecValidation step compiles the TypeSpec and checks to see if the emitted openapi matches what is in the PR/repo. If we know we want the openapi to match, we should just replace the diff with a new commit that updates the openapi.

**Comment by mikeharder** [comment]
CC: @weshaggard

**Comment by weshaggard** [comment]
I agree this is something we should try to get too but I don't think right now is a good time to make that happen. 

We definitely need the openapi specs checked into the repo for various reasons, some we control and others we don't such as third parties pulling the specs for processing. So, it is mostly a question of can we automatically generate them as part of the PR process, which we can but it becomes tricky to have a pipeline automatically updating a PR with new changes. There are security concerns as well as workflow concerns (i.e. the owner of the PR now has to understand git well enough to pull and merge in those changes in the middle of the changes they are working on).

I'm definitely open to ideas on how to make this work but for now I feel the easiest way is to have a check in the pipeline and if things don't match give clear instructions on how to regenerate it and push the change to the PR.

**Comment by kurtzeborn** [comment]
Closing based on Wes's comment.
