### ISSUE TITLE
[CadlValidation CI] Require package-lock.json be uploaded to TypeSpec PRs

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-tools#5717]
Require package-lock.json to be uploaded to have a list of packages and their deps per service specification

**Comment by mikeharder** [comment]
@catalinaperalta: Can you please add more details?  Is this about adding a new rule to the "Cadl Validation" step to show an error if a folder is missing a `package-lock.json`?  Or is this about adding `package-lock.json` files to the repo to pin package versions?

**Comment by catalinaperalta** [comment]
The initial ask behind this issue was to add an error if a folder is missing the package-lock.json so that we can have a source of consistent dependencies for folks checking in work now.

**Comment by mikeharder** [comment]
@catalinaperalta: I believe this issue is obsoleted by the new design which uses a `package.json` and `package-lock.json` in the repo root.  Please re-open if you disagree.

CC: @weshaggard
