### ISSUE TITLE
[openapi-hub] Cannot login to OpenAPI Hub in Edge Dev browser

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#5719]
A user is reporting they are unable to login to OpenAPI Hub in the Edge Dev browser version `112.0.1722.7 (Official build) dev (64-bit)`.  The browser console shows an error related to CORS on the login redirect.

We should investigate to determine if this is a bug in Edge Dev, or a default setting change in Edge Dev that will eventually roll to Stable (so our site needs to be updated).

**Comment by maririos** [comment]
It has been a year since this was opened and he haven't been notified about this.
Closing issue
