### ISSUE TITLE
ShiftLeft pipeline support request by Fuming Zhang: `Sync Swagger to GitHub` task is producing an empty diff

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#5725]
[Relevant post](https://teams.microsoft.com/l/message/19:9efda948665d481086766c0b7572abc3@thread.skype/1678792304688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1678792304688&teamName=Azure%20SDK&channelName=Service%20API%20Toolset&createdTime=1678792304688&allowXTenantAccess=false) on API Service Toolset Teams channel.

I had calls with Ray Chen about it. Recordings available on https://www.microsoft365.com/mycontent

[Recording 1 - about ShiftLeft in general](https://microsoft-my.sharepoint.com/:v:/p/kojamroz/EZmwda68EOlBgrBDFi3E0nQBSiyHmpR0El_dgI8QGGxFMw?e=zYU8bV)  
[Recording 2 - debugging this issue specifically](https://microsoft-my.sharepoint.com/:v:/p/kojamroz/ETThIsAr1x1Ir02pmJ7teCsBlGFVXo66B0irXlUc0DxbNg?e=4MXCZ7)

Urgency:

> [Tuesday 3/14/2023 7:55 PM] Fuming Zhang
>    got it, it takes 6 days before service is ready to perform swagger release, so we could wait a little bit

Tasks that didn't diff anything:
- [Sync TSP to GitHub](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=70067211&view=logs&j=2a48af95-7dbf-588b-8761-54b7ba180ddf&t=c39e829d-bcdc-5e74-a393-a1e3b92485f1) - this is **expected**, see [this comment below](https://github.com/Azure/azure-sdk-tools/issues/5725#issuecomment-1478817414),
- [Sync Swagger to GitHub](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=70067211&view=logs&j=2a48af95-7dbf-588b-8761-54b7ba180ddf&t=f4c5eb8c-501f-5326-5891-25b798cf0f17) - this is **unexpected**, and hence the problem.

**Comment by FumingZhang** [comment]
Hey @konrad-jamrozik, may I ask how is the progress of this bug fix? We want to do swagger release as soon as possible.

**Comment by konrad-jamrozik** [comment]
@FumingZhang apologizes for the delay! I am going to work on this over the next 12 hours, expect an update from me in that time window.

**Comment by konrad-jamrozik** [comment]
I have advised @FumingZhang to create a PR directly to the `azure-rest-api-specs` repo. This is in violation of the ShiftLeft rules, as can be seen e.g. here: https://github.com/Azure/azure-rest-api-specs/pull/22309#issuecomment-1404107367

However, the rule assumes timely support if issues like this one arise, which is currently not possible, as I am new to the codebase and I am still working through it, making progress, albeit slow. Fuming confirmed he is working on submitting a PR to the main repo.

**Comment by FumingZhang** [comment]
Manually created PR [#23189](https://github.com/Azure/azure-rest-api-specs/pull/23189).

**Comment by konrad-jamrozik** [comment]
I submitted a PR against ShiftLeft source adding diagnostic info to help diagnose the root-cause:
https://devdiv.visualstudio.com/DevDiv/_git/openapi-pipeline/pullrequest/459818

**Comment by konrad-jamrozik** [comment]
@FumingZhang I believe I found the root cause. In our call we had few days ago you gave as an example that [the following directory should have been included in the diff PR](https://dev.azure.com/msazure/CloudNativeCompute/_git/aks-rp?version=GBofficial/aks-api-release&path=/swagger/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-02-01):

`/swagger/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-02-01`

I ran another build from that branch with additional diagnostic output which you find [here](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=70473888&view=logs&j=2a48af95-7dbf-588b-8761-54b7ba180ddf&t=c39e829d-bcdc-5e74-a393-a1e3b92485f1). In this build you can see:

```
CaldDirForArm='swagger/containerservice/fleets.management' CadlDirForDataplane=''
Executing Apply-PatchTsp src='/home/vsts/work/1/s/../Azure-azure-rest-api-specs-pr/swagger/containerservice/fleets.management' tar='specification' ServiceName='containerservice' tspFolder='fleets.management' targetTspFolder='specification/containerservice/fleets.management'
Executing Remove-DeletedTsp src='/home/vsts/work/1/s/../Azure-azure-rest-api-specs-pr/swagger/containerservice/fleets.management' tar='specification/containerservice/fleets.management'
removing whole folder specification/containerservice/fleets.management
Skipped processing CadlDirForDataplane as it is an empty string
Executing Push-Changes branch='containerservice/official/aks-api-release' commitMsg='[AutoSyncTsp] bae8054ad7e Merged PR 7768257: Revert "Merged PR 7726419: [API Release] 2023-03-02-preview Create Swagger ba...'
No tsp changes
```

Please note the:
`CaldDirForArm='swagger/containerservice/fleets.management'`

this is a different path than the example you gave, of:

`/swagger/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-02-01`

it differs by suffix: `fleets.management` vs `resource-manager`.

Hence it seems to me that if you would change the value of the [CadlDirForArm](https://dev.azure.com/msazure/CloudNativeCompute/_git/aks-rp?path=/swagger/vsts-swagger-shift-left.yaml&version=GBofficial/aks-api-release&line=18&lineEnd=19&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) variable, which currently is `swagger/containerservice/fleets.management`, the PR should be properly created.

Let me know if this solves the issue, thanks!

**Comment by FumingZhang** [comment]
@konrad-jamrozik, there are 2 sub-services under the Microsoft.ContainerService namespace, the first one is aks (with path `/swagger/containerservice/resource-manager/Microsoft.ContainerService/aks`) developed in the traditional way (modify the json file directly), and the second one is fleet (with path `/swagger/containerservice/resource-manager/Microsoft.ContainerService/fleet`) developed with cadl. 

The API changes of these two services will be released independently, so we defined the manifest file like
```
"official/aks-api-release": {
    "includedPaths": [
        "containerservice/resource-manager/Microsoft.ContainerService/aks/*"
    ]
},
"official/fleet-api-release": {
    "includedPaths": [
        "containerservice/resource-manager/Microsoft.ContainerService/fleet/*"
    ]
}
```

This time, I am trying to release aks related changes via branch `official/aks-api-release` and I think it should have nothing to do with fleet or cadl (not sure what Tsp is short for, but I guess it's related to cadl).

**Comment by konrad-jamrozik** [comment]
@FumingZhang apologies, my mistake. I somehow assumed the issue is that **both** `Sync Swagger to GitHub` and `Sync Tsp to GitHub` do not create any diff, but obviously you meant only `Sync Swagger to GitHub`. Hence, I will need to work a bit more on getting the root cause, but relevant code to which I need to add diagnostic logging is very similar, so expect a reply from me within next 24h (i.e. my upcoming business day).

I believe `Tsp` stands for `TypeSpec` which is the new name for `Cadl`.

**Comment by konrad-jamrozik** [comment]
@FumingZhang I submitted a PR with experimental bugfix, waiting for approval:
[Pull Request 460255](https://devdiv.visualstudio.com/DevDiv/_git/openapi-pipeline/pullrequest/460255): Path matching bugfixes in SyncTspToGitHub.ps1 & SyncSwaggerToGitHub.ps1 for backslashes, and for case of non-existent excludedPaths.

**Comment by FumingZhang** [comment]
Thanks for the update

**Comment by konrad-jamrozik** [comment]
@FumingZhang OK looks like the bug is finally fixed!

[PR with the last bugfix](https://devdiv.visualstudio.com/DevDiv/_git/openapi-pipeline/pullrequest/460537)

[Successful build](https://dev.azure.com/msazure/CloudNativeCompute/_build/results?buildId=70679814&view=logs&j=2a48af95-7dbf-588b-8761-54b7ba180ddf&t=f4c5eb8c-501f-5326-5891-25b798cf0f17)

[Resulting PR, confirming the fix works](https://github.com/Azure/azure-rest-api-specs-pr/pull/11846#issuecomment-1483716629)

Now I am going to look into https://github.com/Azure/azure-sdk-tools/issues/5788

I am closing this issue as resolved, but let me know if something is still not right.

**Comment by FumingZhang** [comment]
Cool, thanks @konrad-jamrozik.
