### ISSUE TITLE
[ShiftLeft] support request by Matthew Ferrari: project name not correctly escaped

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#5728]
Reported on [Service API Toolset](https://teams.microsoft.com/l/message/19:9efda948665d481086766c0b7572abc3@thread.skype/1678849138423?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1678849138423&teamName=Azure%20SDK&channelName=Service%20API%20Toolset&createdTime=1678849138423&allowXTenantAccess=false) Teams channel.

Original issue: Permission denied

**Comment by matthewgferrari** [comment]
This request is not immediately urgent, but it is timely. 
 
Is a workaround available?
I believe was can manually submit PR as a work around.
 
What is being blocked by this issue? 
A new release of an Azure Access Point API version 2023-03-01-preview. 
 
How long this request can remain unsolved? 
We need to have release in 14 days to meet deliverable deadline.

**Comment by matferrari-msft** [comment]
This request is not immediately urgent, but it is timely.
 
Is a workaround available?
I believe was can manually submit PR as a work around.
 
What is being blocked by this issue?
A new release of an Azure Access Point API version 2023-03-01-preview.
 
How long this request can remain unsolved?
We need to have release in 14 days to meet deliverable deadline.

**Comment by konrad-jamrozik** [comment]
The permissions issue has been fixed (see Teams thread) but looks like ShiftLeft is currently failing on what appears to be project name not being correctly escaped. Details by Matthew [here](https://teams.microsoft.com/l/message/19:9efda948665d481086766c0b7572abc3@thread.skype/1679343800643?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1678849138423&teamName=Azure%20SDK&channelName=Service%20API%20Toolset&createdTime=1679343800643&allowXTenantAccess=false).

This requires further investigation.

[Build failure log](https://dev.azure.com/msazuredev/Mission%20Engineering/_build/results?buildId=671358&view=ms.vss-test-web.build-test-results-tab&runId=1752525&resultId=100000&paneView=debug)

[Build definition](https://dev.azure.com/msazuredev/Mission%20Engineering/_build?definitionId=7944&_a=summary)

[ShiftLeft yml definition](https://dev.azure.com/msazuredev/Mission%20Engineering/_git/AAP-resource-provider?path=/.pipelines/shift-left.yml)

I advised Matthew to work around this issue by submitting a PR to specs repo directly.
