### ISSUE TITLE
[OpenAPI Hub] feature request: automatically maintain readme.test.md file as well when adding new api version

### ISSUE THREAD

**Issue by leni-msft** [Azure/azure-sdk-tools#5738]
Currently OpenAPIHub automates most steps to create OpenAPI Specifications (a.k.a Swaggers) required when adding a new API version: [doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version#:~:text=automates%20most%20steps%20to%20create%20OpenAPI%20Specifications%20(a.k.a%20Swaggers)%20required%20when%20adding%20a%20new%20API%20version)

It mainly copies swagger/examples/scenarios to new api-version folder, and update the api-version as well as readme.md tags. However, tags in readme.test.md file currently are not updated automatically. The request is to support it as well.

See PR: https://github.com/Azure/azure-rest-api-specs/pull/22557

**Comment by kurtzeborn** [comment]
While we're not doing new features in OpenAPI Hub (and it will eventually be retired), we should absolutely take this into account when implementing Resource Planner.

**Comment by maririos** [comment]
@JonathanCrd is this being consider as part of the work on https://github.com/Azure/azure-rest-api-specs/pull/27932 ?

**Comment by JonathanCrd** [comment]
> @JonathanCrd is this being consider as part of the work on [Azure/azure-rest-api-specs#27932](https://github.com/Azure/azure-rest-api-specs/pull/27932) ?

It was not, but I'll add this to the project backlog to include it as an enhancement for the script.

**Comment by maririos** [comment]
> It was not, but I'll add this to the project backlog to include it as an enhancement for the script.

Before you add it, make sure to reach out to the person that created the issue and see if this is still needed.

**Comment by maririos** [comment]
As we keep removing the support for OpenAPI, this feature request will not happen either
