### ISSUE TITLE
Swagger API review - Skip API review step if swagger is not part of default tag

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5740]
Swagger PR pipeline step to create API review fails if modified swagger file is not part of default tag. We should ignore the failure instead of marking pipeline as failed in this case until we have the support added to create API review from non-default tag.

Issue to track long term fix: https://github.com/Azure/azure-sdk-tools/issues/5739

**Comment by chidozieononiwu** [comment]
This has been resolved by @praveenkuttappan
