### ISSUE TITLE
Scheduling Tool: Meeting Invite changes

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-tools#5741]
One of the comments I hear the most from architects is that it is hard to quickly understand what a review session will be about just from the meeting invite. They've asked for a couple of additions to the meeting invite.

- [ ] In the `Languages to review` bullet, the listed languages should be links to the related language API View.
- [ ] Allow the meeting creator to add a meeting title that should describe the meeting subject. Just having the Service team in the meeting title is often not enough for attendees to decern what meeting it is.

**Comment by maririos** [comment]
>  In the Languages to review bullet, the listed languages should be links to the related language API View.

Is this in the calendar invite?

>  Allow the meeting creator to add a meeting title that should describe the meeting subject. Just having the Service team in the meeting title is often not enough for attendees to decern what meeting it is.

From the Engagement Experience perspective we are seeking to have meetings formated as close as possible. Is this because people don't read the description?

**Comment by maririos** [comment]
> > Is this in the calendar invite?
> 
> Yes ![image](https://user-images.githubusercontent.com/28957151/226044989-5169c15a-7e65-4773-9de5-6a5b104f2858.png)
> 

Got it! Issue for this is: https://github.com/Azure/azure-sdk-tools/issues/5021

> > From the Engagement Experience perspective we are seeking to have meetings formated as close as possible. Is this because people don't read the description?
> 
> Yes, from what I understand. I've made the point to the architects that the info is in the description, but they constantly ask for it to be in the title.

@ladonnaq  do you have ideas on what we could do here?

**Comment by ladonnaq** [comment]
> > > Is this in the calendar invite?
> > 
> > 
> > Yes ![image](https://user-images.githubusercontent.com/28957151/226044989-5169c15a-7e65-4773-9de5-6a5b104f2858.png)
> 
> Got it! Issue for this is: #5021
> 
> > > From the Engagement Experience perspective we are seeking to have meetings formated as close as possible. Is this because people don't read the description?
> > 
> > 
> > Yes, from what I understand. I've made the point to the architects that the info is in the description, but they constantly ask for it to be in the title.
> 
> @ladonnaq do you have ideas on what we could do here?
1. We could add the languages to the end of the title but it would make it longer.  "Azure DevEx Architecture Board: Review of Email Communication Services" + Language(s).    For example, for this review the title would be "Azure DevEx Architecture Board: Review of Email Communication Services Java, Python, .NET, Javascript.  
2. Is there a way to add a category to the calendar invite?  If so, then the categories would show up at the top when you open the calendar invite and also in the calendar view.  See example in screenshot.  I like this idea because it is visual as well as just text. 
![image](https://user-images.githubusercontent.com/67656762/226739778-e985a7e2-924f-4c69-90e9-1941ea9e799f.png)
![image](https://user-images.githubusercontent.com/67656762/226740102-0e2d6a71-fd9b-4d7e-8925-1106b4416207.png)

**Comment by maririos** [comment]
@ronniegeraghty will adding the languages to the title help? or better to allow customization to let the user do whatever. :) 
I kept thinking about this and the prefix is static, the rest cna be custom if that is what the architects want

**Comment by ronniegeraghty** [comment]
I think having the languages in the description is enough. The real issue is not knowing the meeting topic from the title. For example, the architects may see 3 to 4 meetings from ACS on their calendar and not know which is which. If the title could include something along the lines of `Azure DevEx Architecture Review of ACS Feature to Support New Thing` I think it would resolve a lot of the confusion.

**Comment by maririos** [comment]
> I think having the languages in the description is enough. The real issue is not knowing the meeting topic from the title. For example, the architects may see 3 to 4 meetings from ACS on their calendar and not know which is which. If the title could include something along the lines of `Azure DevEx Architecture Review of ACS Feature to Support New Thing` I think it would resolve a lot of the confusion.

Noted. Let's see how we can add the custom section to the title.

**Comment by ladonnaq** [comment]
> > I think having the languages in the description is enough. The real issue is not knowing the meeting topic from the title. For example, the architects may see 3 to 4 meetings from ACS on their calendar and not know which is which. If the title could include something along the lines of `Azure DevEx Architecture Review of ACS Feature to Support New Thing` I think it would resolve a lot of the confusion.
> 
> Noted. Let's see how we can add the custom section to the title.

Would the format [Service - product] when the user selects a product be helpful. Or is this really related to the "sub-service"?   Just curious how we could come up with a consistent approach.

**Comment by ronniegeraghty** [comment]
> Would the format [Service - product] when the user selects a product be helpful. Or is this really related to the "sub-service"? Just curious how we could come up with a consistent approach.

I think the most wanted addition to the title is the specific feature being reviewed.

**Comment by maririos** [comment]
> > Would the format [Service - product] when the user selects a product be helpful. Or is this really related to the "sub-service"? Just curious how we could come up with a consistent approach.
> 
> I think the most wanted addition to the title is the specific feature being reviewed.

Issue https://github.com/Azure/azure-sdk-tools/issues/7546
