### ISSUE TITLE
Support typespec naming in SDK automation pipeline rather than cadl

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#5749]
typespec core libraries completed renaming and some emitters are done too. It needs to support that in SDK automation pipeline.

example spec PR from a service team: https://github.com/Azure/azure-rest-api-specs/pull/22990/files

**Comment by raych1** [comment]
Work is done. Both java and python packages were generated correctly for typespec example project in Azure spec repo.
https://github.com/Azure/azure-rest-api-specs/pull/23168

**Comment by lirenhe** [comment]
close it as resolved
