### ISSUE TITLE
Publish `validate-v2` image on a weekly cadence

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#5772]
Currently:

1. CI Pushes to test ACR
2. A user manually runs a release to publish from test ACR to the PROD acr
3. A user deploys to the test cluster using the new image version
4. Smoke test is run against the new image version

To properly automate this on a weekly cadence, we need a way to control the final version that is used by the `RPaaS` team. Our image is _used_ by them, so we need to make certain that they don't automatically pull latest from the prod ACR AND we don't want them to use the image of the `smoke-tests` against the test cluster fail.

To properly solve this, we want to the image release to have additional steps.

1. Publish from test ACR to PROD acr (or a "PPE" one that we can use only in our test cluster)
2. Deploy to test cluster using new image tag from previous publish step
3. Run smoke tests against new image tag

**Comment by scbedd** [comment]
I have an email out to the RPaaS folks to confirm which is the `prod` ACR. Depending on there answer we will need to rework the release process to NOT immediately publish to the `prod` ACR. Awaiting response.

**Comment by scbedd** [comment]
Looks like any new tags pushed to our prod ACR are automatically synced to an RPaaS team ACR via webhook configuration. This means that we need to update the TestCluster deployment to pull from the `test` cluster rather than the prod ACR.

I'm thinking we do the following. Update the existing "release to prod" process to...

- [ ] Allow test-cluster to pull from INT ACR
- [ ] Create a new release that combines 
   - Release to test-cluster
   - Run smoke-tests against test-cluster
   - Release from int ACR to prod ACR
- [ ] Schedule new release to run on weekly cadence

**Comment by konrad-jamrozik** [comment]
Removing `Spec PR Tool` label as it no longer applies since renaming. `validate-v2` is a component of the online validation on RPAAS-enabled ARM services.

**Comment by scbedd** [comment]
[This is complete.](https://devdiv.visualstudio.com/DevDiv/_release?definitionId=3354&view=mine&_a=releases)
