### ISSUE TITLE
Update cadl-structure-guidelines to reflect the rename from cadl to DPG.

### ISSUE THREAD

**Issue by lirenhe** [Azure/azure-sdk-tools#5775]
The below doc serves as the main reference for service team to start to onboard to our DPG/mgmt. SDK process.
We need to make sure the content is correct.

https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/cadl-structure-guidelines.md

cc @weshaggard   @mikekistler @lmazuel

**Comment by weshaggard** [comment]
I've updated them as part of https://github.com/Azure/azure-rest-api-specs/pull/23168
