### ISSUE TITLE
[openapi-alps] Remove step "install latest git"

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#5779]
Pipelines in `openapi-alps` have a step `install latest git` which takes almost a minute, and I suspect is unnecessary since the agents should have fairly recent builds of `git`.  We should try removing the step.

**Comment by benbp** [comment]
My bet is this was due to some use of sparse checkout that for a period of time broke when git made a backwards incompatibility with cone mode defaults.

**Comment by mikeharder** [comment]
This was added on 4/27/22, and the listed reason was to address a security alert.  It was part of a larger PR fixing multiple security alerts:

https://dev.azure.com/devdiv/DevDiv/_git/openapi-alps/pullrequest/395795

So I think this can be reverted now, with the assumption that the version of git pre-installed on the agents is new enough.

**Comment by mikeharder** [comment]
Fixed by https://dev.azure.com/devdiv/DevDiv/_git/openapi-alps/pullrequest/460155
