### ISSUE TITLE
Simplify connectors and connection references across environments

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#5781]
We have several connectors for the same service and severla connection references for the same connectors.

It might be good to simplify tbhis and only depend on 1 connector per service and 1 connection reference per connector or app.
Also, we should remove any connections made by any account different than the bot's.

However, this redudnancy does not represent a masive impact in the performance of the apps, so this would be low priority.

**Comment by maririos** [comment]
Done!
