### ISSUE TITLE
[TypeSpec Validation] Do not copy root package.json into project folder

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#5786]
Currently, the `TypeSpec Validation` feature has a lot of code that assumes the project folder contains a `package.json`.  However, the new design is to have one `package.json` in the repo root, and no `package.json` in project folders.

`TypeSpec Validation` should be updated to install `typespec` from the root `package.json`, and to find the metadata it needs in other files like `tspconfig.yaml` instead of `package.json`.

**Comment by ckairen** [comment]
Added in the new version of TSV
