### ISSUE TITLE
Updates in OpenAPI Hub request release

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5791]
Changes need to happen in  https://portal.azure-devex-tools.com/tools/request-api-release

1.	Title should be updated to “SDK Release Request”.  
2.	The teams channel link is pointing to a channel no long exist.  Could you help to update to this channel [SDK release support](https://teams.microsoft.com/l/channel/19%3a084875bb626242ed95f3ac8dddfaa12a%40thread.skype/SDK%2520release%2520support?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47)

**Comment by josefree** [comment]
Oh in fact, the update is not to the web page.  It is to the mail notification template generated after submission in https://portal.azure-devex-tools.com/tools/request-api-release

**Comment by josefree** [comment]
![image](https://user-images.githubusercontent.com/18413981/227446194-9b3ca979-546e-49c3-ac54-266d5ca79e23.png)

**Comment by maririos** [comment]
@josefree thanks for the clarification!

**Comment by maririos** [comment]
Changes have been applied as part of https://github.com/Azure/azure-sdk-tools/issues/8009. We will keep this issue open until the deployment happens in PROD

FYI @JonathanCrd
