### ISSUE TITLE
[Defect] Failed to generate .NET sdk for contosowidgetmanager

### ISSUE THREAD

**Issue by chunyu3** [Azure/azure-sdk-tools#5808]
In Unified pipeline, it failed to generate .NET sdk for contosowidgetmanager.
see:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2653167&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437

root cause:
Contoso.WidgetManager has dependency on Contoso.WidgetManager.Shared. But in Unified pipeline there is no anyway to find this dependency, and the TypeSpec-Project-Sync.ps1 will only sync the TypeSpec project folder `Contoso.WidgetManager`, without dependency directory `Contoso.WidgetManager.Shared`.

**Comment by lirenhe** [comment]
Will create a new issue for this.

**Comment by chunyu3** [comment]
this defect will be resolved by the sdk automation E2E for typespec. There is another issue to track. close this.
