### ISSUE TITLE
Release Planner and ADO: Onboard Services only, no product entry in service tree at time of onboarding 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5827]
**Scenario:** No product name: The Release Planner already supports this scenario. Existing ADO work items that represent a Service were not imported to the release planner yet. need to look more into how to do the import. These information will be ported in phase 2. 

- Service Name is Product Name in this ADO query.  This is because the field was inherited from the previous ADO onboard template and to add a new field would have meant that we had to manually update all of the work items (closed or active).  So I just changed the label name.  I know it is confusing when looking at an ADO query, so let me know if we need to consider adding a ADO field and having Siva manually update all of the work items.  
- We have had several new services onboard with us before they have a product entered in service tree.  In the screenshot are the current fields in the product information section that are completed when a service onboards.  
- We could change the behavior as I have a field for Product Type and in that field there is an option in the picklist for “Service – no product”.  If we did this, then this field could be used to identify services that do not have products.  For now, when service tree entries for the product are complete, we can onboard for them using the release planner and manually link the product as a child of the service.  This way we don’t lose the history.  
- We may want to modify the existing logic to leave the Product Name field blank so that is not confusing.  The Associated Service Name field has the name of the service and the title is the name of the service + service at the end so we know it is a service not a product at quick glance.  
![image](https://user-images.githubusercontent.com/67656762/228006901-3f772264-74ee-4c04-bbcd-138b71865888.png)

**Comment by maririos** [comment]
The Release Planner already has logic to support this. I need to update the logic that is porting the ADO items into the Dataverse to include this scenario

**Comment by maririos** [comment]
Done :)
