### ISSUE TITLE
Actions timing: Changes made by the user, while an action was processing and revert those changes

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-tools#5835]
Actions, take time to setup and run but during this time a user can make changes to an Issue or Pull Request. For example, a user can create an Issue with no labels and, after the issue has been created, immediately add labels. Meanwhile, the issues opened event has fired, the payload's issue is the issue in the state that it was when it was created, which means it had no labels. Part of the Initial Issue Triage processing adds at least one label. When an Issue is updated with an IssueUpdate, this isn't a merge, it's a replace as the labels in the IssueUpdate are what's set on the Issue. This results in removing the labels that were added by the user while the issues opened event was still processing. Right now, this could happen with just about any action.

This is the [example](https://github.com/Azure/azure-sdk-for-net/issues/35159#event-8856171762) that @jsquire pointed out to me.
[I was able to reproduce this in the test repository](https://github.com/azure-sdk/github-event-processor-test/issues/23#event-8856721763). 

A largest part action's processing time is checking out the repository. Second to this would be the AZ CLI commands, which only run on issues opened. Even in the test repository, which has massively shorter sync times, this can definitely happen.

/CC @weshaggard @benbp @kurtzeborn 

While it is possible to do this with FabricBot today, the window is much narrower, so much so that someone would have to be lightning quick in order to make this happen.

**Comment by benbp** [comment]
I wonder if for this event specifically we should do an extra read of the issue to get the most recent label state right before updating?

**Comment by weshaggard** [comment]
IIRC there are also rest APIs that allow you to incrementally add/remove things instead of blindly updating the entire set of labels on an issue. That would probably be safer.

**Comment by JimSuplizio** [comment]
@weshaggard and @benbp. The call to update the issue is supposed to be a patch. The [API](https://docs.github.com/en/rest/issues/issues?apiVersion=2022-11-28#update-an-issue) which is used by the [IssuesClient.cs](https://github.com/octokit/octokit.net/blob/main/Octokit/Clients/IssuesClient.cs#L494) class is supposed to be doing a patch. I think this is getting at least semi-messed up by the fact that it's creating the IssueUpdate by calling [ToUpdate](https://github.com/octokit/octokit.net/blob/main/Octokit/Models/Response/Issue.cs#L180) on the Issue which is setting anything that's already been set. I need to look at whether or not this is part of the problem.
