### ISSUE TITLE
[Breaking Change] Bypass review of BreakingChange/NewApiVersionRequired for PRs to dev branches

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#5838]
Teams should be using feature branches while working on a new api-version. It's rare - practically unheard of - for any one-and-done changes to an api-version, so going directly from a topic branch into main should be a rarity. Validation seems to expect that, though.

As such, breaking changes should probably be disabled entirely when targeting a feature branch at least following the `(dev|release)[-/]` regex for branch names. This seems to be a variation of #5024 but I think we should still run validation across previous previews, just not requiring checks to pass.

While working in a feature branch, it's common for teams to make changes due to:

1. Change in implementation or API
2. User feedback
3. API Stewardship Board review feedback

PRs should not be blocked in these cases as they target the feature branch. We shouldn't require breaking changes until it goes to main, though it's good to check both past previews (non-required) and GAs (required).

**Comment by konrad-jamrozik** [comment]
I am aggregating similar issues here:

- https://github.com/Azure/azure-sdk-tools/issues/5943#issuecomment-1504375978

**Comment by konrad-jamrozik** [comment]
Per @mikekistler: probably we should still run the checks and report breaking changes if any, but not actually fail the PR. This is because if not fixed right now, they will show up again when trying to merge to public `main`.

**Comment by heaths** [comment]
That's also what I said in the OP. ;)

> PRs should not be blocked in these cases as they target the feature branch. We shouldn't require breaking changes until it goes to main, though it's good to check both past previews (non-required) and GAs (required).

We want partners to see the issues, but not block them on merging into feature/release branches. Just main.

**Comment by mikekistler** [comment]
I'm going to change the title of this issue because it is currently misleading. We _do not_ want to disable validation for same-version changes -- these should be flagged when the PR targets main.  Rather we want to bypass _review_ of any breaking change / new-api-version-required issues for PRs that target dev branches.

**Comment by heaths** [comment]
> [konrad-jamrozik](https://github.com/konrad-jamrozik) moved this from 🤔 Triage to 📋 Backlog in [Azure SDK EngSys 🍕](https://github.com/orgs/Azure/projects/162) [yesterday](https://github.com/Azure/azure-sdk-tools/issues/5838#event-6a3ca041-54f8-572d-922d-05e6037f47a0)

How does this translate to a projected milestone? This is currently causing a lot of scalability issues, especially if assignees for spec repo PRs are checking all validation errors (many of which require drilling into AzDO pipeline failures).

**Comment by konrad-jamrozik** [comment]
@heaths it is not going to get picked up before any of the items that have `high` priority on this board:
- https://github.com/orgs/Azure/projects/198/views/1

Which mean it will be **at least** few months before I can attend to it.

**Comment by konrad-jamrozik** [comment]
Increasing priority to `High` per the email thread `RE: azure-rest-api-specs breaking change tooling is confused` with @matthchr et al.

**Comment by konrad-jamrozik** [comment]
PR: https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/513409
