### ISSUE TITLE
Custom codeowners to avoid mass reviews

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#5840]
Numerous times a day in the Azure/azure-rest-api-specs repo and occasionally in the SDK repos, I get added to a review where someone is merging main into a feature branch (or similar). GitHub's codeowners feature adds every "affected" codeowner and it's really noisy to evaluate what I need to review and what I can ignore.

Instead, could we consider using JimBot or something to support a custom codeowners feature that effectively only adds reviewers when needed e.g.,

1. Any PR into main affecting owned / watched files
2. Any PR where the HEAD is *not* a merge commit

We may need to firm up these rules, but that would be the basic idea. Any PR where the HEAD is a merge commit is likely one of these cases that can be ignored by the majority of codeowners.

**Comment by jsquire** [comment]
As I understand it, assignment of reviewers via CODEOWNERS is intrinsic to the platform and happens outside or our automation, so we have little control over the general form.   We will be extending syntax for CODEOWNERS to reflect an "Azure SDK owner" - maybe we could use that in lieu of the general syntax for adding additional reviewers with custom criteria like Heath is proposing. 

Something like:

- If I'm interested in every single thing and I want to be explicitly understood by GH to own this code, then I use the general syntax.
- If I'm conditionally interested and want to be added only for the more strict criteria, I use the "Azure SDK owners" syntax.

**Comment by kurtzeborn** [comment]
Isn't the easy way to do this just to take the individual names out of CODEOWNERS and use GitHub teams instead? Then, you can configure the GitHub team to not assign everyone to a PR and instead do it round robin (or other options).

It would be redundant to add a feature to JimBot for this.  I think we already have what's needed to accomplish this from GitHub.
