### ISSUE TITLE
APIView- Create review page shows invalid options

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5847]
Ideally TypeScript option should show a text box to enter URL to TypeSpec project and selecting any other language should show file upload button and this works fine if user selects the language only once. But toggling is incorrect if you happened to click TypeSpec twice.

Scenario:

1. Click Create review
2. Select TypeSpec from language list. This shows the expected textbox in screen.
3. Click on TypeSpec again. TextBox is changed to File picker now for TypeSpec. Incorrect
4. Click on any other language now and it shows the textbox to enter URL instead of file picker.

**Comment by chidozieononiwu** [comment]
This has been resolved by https://github.com/Azure/azure-sdk-tools/pull/5858
