### ISSUE TITLE
Change release planner to look for TypeSpec + DPG to determine if data plane release plan can be created

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5850]
The Azure Devops onboard work item fields have been updated to change Cadl to TypeSpec.  However, the release planner has not been updated so right now no one can create a data plane release plan.  

I am not sure which field the release planner is looking at to determine if TypeSpec + DPG is in scope for the product. 
I have this field, which is for public preview.  I created a new value for TypeSpec + DPG and have been updating the work items.  I plan to remove the Cadl + DPG value but was going to double check I updated all of the work items before doing so. 

![image](https://user-images.githubusercontent.com/67656762/228336238-9231ba0e-0279-4213-aa90-28ff9e983b0e.png)
I also have this field, which is for GA. 

![image](https://user-images.githubusercontent.com/67656762/228336869-7879bcd1-b50d-4a48-a66f-626ace879af2.png)

**Comment by maririos** [comment]
@ladonnaq  yes we have it in the logic of the app. We actually check both fields.
`workItemDetail.fields.Custom_DataSDKClassification <> "Cadl + DPG" && workItemDetail.fields.Custom_SDKClassificationStable <> "Cadl + DPG"`

We will need to coordinate the change so we can safely do this move

**Comment by maririos** [comment]
Changed deployed to Prod

**Comment by maririos** [comment]
FYI @ladonnaq
