### ISSUE TITLE
[typespec-validation] Detect changes to all input and output files

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#5854]
Currently, TypeSpecValidation only detects additions and changes (not deletions) to `*.tsp` files in `git diff`.  It should detect changes to all input and output files that could cause failures, including all change types (additions, changes, and deletions) and the following file patterns:

- `**/*.tsp`
- `**/tspconfig.yaml`
- Swagger *.json file(s) generated from TypeSpec

Unless we get customer requests to do this sooner, this change can be made only in the new implementation of TypeSpecValidation.

**Comment by ckairen** [comment]
This issue is fixed with the new version of TypeSpec Validation
