### ISSUE TITLE
Clarify what does "Publish" mean and in the implications

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5859]
Looks like the Management app published the changes from the private repo PR to the public repo.
If this is what we want, we should make sure to communicate that to the user. In addition, we should add a prompt to confirm this is what the user wants.

**Comment by maririos** [comment]
REq: Publish shouldn't happen in Private Preview.

TODO: Need to look at the logic in the app and see what are the expectations. Then adjust it to what is explained here

**Comment by maririos** [comment]
This issue happens in the Management plane API Readiness app. One of the last stteps is to "Publish".
According to the user, there is no text or tooltip that explains what does Publish means, so the user click the button and what the button did was to create a PR on the spec repo with the content of the branch from the private repo. The service was still in Private Preview so of course they got upset and we had to remove the code right away.

To avoid that, we should look at the code behind the Publish button and see what it is doing. According to that see if the UI explains what it means to push that button.

**Comment by praveenkuttappan** [comment]
I am assuming above changes are also required for Data plane API readiness as well and making the change to show Publish only for Public preview and GA release life cycle.
@ladonnaq @maririos

**Comment by maririos** [comment]
> I am assuming above changes are also required for Data plane API readiness as well and making the change to show Publish only for Public preview and GA release life cycle. @ladonnaq @maririos

Correct. Thanks for clarifying

**Comment by praveenkuttappan** [comment]
@ladonnaq I would like to get more clarification regarding 3rd change of adding publish button to SDK release app.

Could you please explain the process flow when a team decides to move from private preview to public preview. 

1. Do we release any libraries to private feed now when service is in private release cycle? How does it happen?
2. What does `SDK release` means for release cycle private preview?

My understanding is that SDK packages are released to public feed only from public preview and GA cycle and that requires a PR to public repo.

**Comment by maririos** [comment]
Given the main tasks for this issue have been completed, I am going to lower the priority.
I'm also moving it to blocking until we get more clarification fro the 3rd cahnge request.

**Comment by maririos** [comment]
The remaining work in this issue is:
> Include the publish option in the SDK release app as well. We can check to see if the PR link is in the private repo and show the publish button notifying the team the API spec must be published to the public repo before SDK release can occur. Perhaps this could happen either just before or as part of the SDK release action. We should show the PR that is associated with the release plan and give the user an opportunity to change it (they have published it and have updated PR that should be referenced for release) or to publish it (private repo).

 @ladonnaq clarify questions:
Should this go in the "Work on SDKs" view?
Other considerations:
- This button option should only be available if the PR is in the private repo
- Should it be a blocker for people to start working on the SDKs? or only a blocker for:
  - Management plane: can't create release request if the PR is not in public repo
  - Data plane: can't get Sign off

**Comment by maririos** [comment]
Publish information is now in the SDK apps based on design https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0-1&t=1lCBRP1NpVo69ZVV-0
