### ISSUE TITLE
Consolidate `azure-rest-api-specs` PR review workflow

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#5865]
There is a workflow that is being followed by several actors when a PR is submitted against https://github.com/Azure/azure-rest-api-specs

This work item is about mapping out this entire workflow and consolidating the guidance. This will allow us to make informed improvements to it and provide support to involved actors when necessary, including the PR submitter and the assigned PR reviewer. One person that can help with that is Mike Kistler, who is a member of the API Stewardship Board.

## Notes on the workflow

The guidance to submit a PR is in the following:
- https://aka.ms/specprreview
- and in the other URLs linked by Mariana [below](https://github.com/Azure/azure-sdk-tools/issues/5865#issuecomment-1490757594)
- In the list given in the [doc map](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/942/Doc-map) article.
- this [OneNote](https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FShanghai%20Team%2FAzure%20SDK%20-%20Shanghai&wd=target%28Swagger%20team%2FPR%20review%20process.one%7C21E7BFC0-B39D-439A-8A08-E7C0AB483BDC%2FSummary%20of%20API%20Spec%20PR%20Review%7CEBE72958-CD78-4720-A3D4-1F20A9FCBEF3%2F%29)
- This [FAQ](https://github.com/Azure/azure-rest-api-specs/wiki/FAQ-in-Swagger-PR-Review)
- [WIP Guide to design and creation of Data Plane REST API and Client Libraries](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/591/Guide-to-design-and-creation-of-Data-Plane-REST-API-and-Client-Libraries)
- List from Crystal Barragan [here](https://www.office.com/launch/fluid/content?auth=2&action=edit&drive=b!4OozMCmnG0qzF26zybsaierafCRwzhhOr1Y-sy-C7E-vrqCK7hTfQ4WBbpN2LjYF&item=01Z7TY52P3VY4RQW4QNZHIGTCEYSUMGJWZ&file=https:%2F%2Fmicrosoft.sharepoint.com%2Fsites%2Fb1441323-a6f8-4f41-883a-77b2e85be3ba&siteUrl=https:%2F%2Fmicrosoft.sharepoint.com%2Fsites%2Fb1441323-a6f8-4f41-883a-77b2e85be3ba) (issue #5989)
 
There are also templates:
- https://github.com/Azure/azure-rest-api-specs/tree/main/.github/PULL_REQUEST_TEMPLATE
- https://github.com/Azure/azure-rest-api-specs/blob/main/.github/PULL_REQUEST_TEMPLATE/control_plane_template.md
- https://github.com/Azure/azure-rest-api-specs/blob/main/.github/PULL_REQUEST_TEMPLATE/data_plane_template.md
- The templates have unclear ownership, per: https://github.com/Azure/azure-sdk-tools/issues/5290#issuecomment-1506108328

Once PR is submitted happens, a person is assigned at random to it, per this list:
https://github.com/Azure/azure-rest-api-specs/blob/main/.github/pull_request_assignment.yml

After this there is a flow based on labels depending on what happens. See the [labelling workflow diagram].

For example, if a breaking change is detected by the OAD tool from Unified Pipeline, then the PR gets auto-labelled with a label denoting there is a breaking change requiring review. Then a reviewer from a "breaking change board" is adding another label, e.g. one denoting that the breaking change got approved.

There is also suppression process, described here:
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process

## Detailed tasks

Below is a non-exhaustive list of subtasks:

We need to:

- understand what are the responsibilities of the auto-assigned PR assignee.
- come up with a process for PR assignees to escalate to us, e.g. file issues against azure-sdk-tools repo
- understand the mechanics of the labelling process
  - this issue has good pointers: https://github.com/Azure/azure-sdk-tools/issues/4675
  - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/909/API-spec-PR-review
    - and specifically the [labelling workflow diagram]
- understand the breaking changes process
  - https://aka.ms/azbreakingchangespolicy from https://github.com/microsoft/api-guidelines/tree/vNext/azure, mentioned by Jeffrey Richter
  - info here https://aka.ms/specprreview
    - links to https://dev.azure.com/msazure/AzureWiki/_wiki/wikis/AzureWiki.wiki/37684/Breaking-Changes?anchor=best-practice/guidelines-on-common-scenarios
      - links to https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-actions-team/service-lifecycle-actions-team/testfolder/media/overview_breakingchanges

## Related work

- https://github.com/Azure/azure-sdk-tools/issues/5867
- https://github.com/Azure/azure-sdk-tools/issues/5983
- https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/942/Doc-map

[labelling workflow diagram]: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/909/API-spec-PR-review?anchor=management-plane-api-review

**Comment by maririos** [comment]
> The guidance to submit a PR is here:
https://aka.ms/specprreview

I wish this was the only place where there is guidance. Here are the other links I have seen people use and share around. I have been collecting them but haven't had the time to look at each and see the accuracy of the information, etc. Sharing them here as FYI for you:
- https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/630/Walkthrough-Creating-a-new-service-specification-in-a-team
- https://armwiki.azurewebsites.net/rp_onboarding/process/api_review.html
- https://github.com/Azure/typespec-azure/blob/update-checkin-doc/docs/howtos/rest-api-publish/checking-in-api-specs-guide.md

**Comment by weshaggard** [comment]
@mikekistler @josefree are a couple folks that I think can help with this.

**Comment by konrad-jamrozik** [comment]
Closing as completed. Big chunk of this work was taken care in:

- https://github.com/Azure/azure-sdk-tools/issues/6618

Other parts are obsolete / subsumed / no longer applicable. Yet other elements are scheduled to be done in other work items, like:

- https://github.com/Azure/azure-sdk-tools/issues/6374
