### ISSUE TITLE
[PR Workflow] Sync files from public Azure rest api spec repo to private Azure rest api spec repo

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#5874]
We have mirror pipeline running to sync between public repo main branch and private repo main branch.  But it's not enough because there're other branches used for api spec review purpose. i.e. `RPSaaSMater`, `RPSaaSDev`, and `ARMCoreRPDev`.  

Some files are supposed to be updated in public repo main branch, then they should be synced to private spec repo branches automatically. These files contain: 
 - `specification/common-types/*`, 
 -  `package.json`
 -  `custom-words.txt`

**Comment by weshaggard** [comment]
custom-words.txt is currently being excluded as there might be conflicts. At some point we might write a custom mergering just for this list if it become an issue.
