### ISSUE TITLE
dev-* branch policy change request

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#5876]
@weshaggard , seems this `dev-*` branch policy in private spec repo doesn't allow user to merge PR directly and it requires review before merge. The purpose of `dev-*` branch is for develop purpose and wouldn't assign reviewers. Can you make the policy change?

This is an example PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/11891#pullrequestreview-1366287285

**Comment by weshaggard** [comment]
@raych1 I thought that is what we wanted the `dev-*` policy for? It is a shared branch for folks that want to share across their team and as such there is some policy that requires them to get reviews and pass checks. If they are working only on their own branch they want unprotected, they should pick the first option.

![image](https://user-images.githubusercontent.com/9010698/229203608-803762af-1641-41c4-8d73-e918c96f439a.png)

**Comment by maririos** [comment]
Interesting. The way I understand the `dev-*` branch is that they need PRs in order to update their code, but anyone in their team can review the PR and the author can merge.
@raych1 are you saying this is the behavior in the public repo and for some reason it is different in the private repo?

**Comment by raych1** [comment]
> @raych1 I thought that is what we wanted the `dev-*` policy for? It is a shared branch for folks that want to share across their team and as such there is some policy that requires them to get reviews and pass checks. If they are working only on their own branch they want unprotected, they should pick the first option.
> 
> ![image](https://user-images.githubusercontent.com/9010698/229203608-803762af-1641-41c4-8d73-e918c96f439a.png)

@weshaggard , for the second option, user should be able to merge the PR once the required checks are passed. I don't remember if a review from others is needed. That would need the write permission for the approvers. 

@maririos , no, it's same behavior for both pubic spec repo and private spec repo.

**Comment by weshaggard** [comment]
Second option should definitely require a review and passing checks. I don't think there is any reason to not do that here.

**Comment by maririos** [comment]
For my understanding, Review != swagger review, right?

**Comment by weshaggard** [comment]
From the branch protection prospective it is simply talking about someone signing off on the PR. However the option in OpenAPIHub "create branch without reviews" is talking about board reviews (ARM or stewardship). I think we might want to improve the wording of to help avoid the confusion.
