### ISSUE TITLE
Add optional to the API scenario/API Readiness Test in management plane API readiness app 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5904]
Add text so that teams know that this is optional at this time.   

![image](https://user-images.githubusercontent.com/67656762/229885818-8f163e3e-703b-462a-b2bb-e51a58e40f79.png)

**Comment by maririos** [comment]
Need to check the logic on the `Next` button and make sure that it won't block people. Same as part of the process make sure people can get Sign Off without this step

**Comment by maririos** [comment]
I have updated the UI:

![Image](https://user-images.githubusercontent.com/9868623/230949589-ef1cda4c-bef5-4911-8b1d-35b397d853b7.png)

and



![Image](https://user-images.githubusercontent.com/9868623/230949662-ce1078fe-017c-43a4-b440-b0ca69c59300.png)
