### ISSUE TITLE
Usage of ADO by service teams and the release planner 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5912]
Understand how service teams use ADO today to track Azure SDK milestones for APEX and/or API publishing and SDK release. 

Examples: 

- https://dev.azure.com/msazure/One/_workitems/edit/16600014  (Backup Service team tracking 2 new features) 
- https://msazure.visualstudio.com/One/_workitems/edit/15188220   (FIST team tracking the ARM work in ADO)

**Comment by maririos** [comment]
@ladonnaq could you help me understand why is this relevant? or how to tied it with everything else?

**Comment by ladonnaq** [comment]
> @ladonnaq could you help me understand why is this relevant? or how to tied it with everything else?

We can put this in the backlog.  This is something we should consider as we evolve the release planner and implement the new UI.  For example, one service team PM wanted to create ADO work items for every step in the release planner for the engineering team.

**Comment by ladonnaq** [comment]
We can close this and call it completed.  We ensured that service team can get to the appropriate ADO work items for tracking if they wish to use in their own ADO project tracking.
