### ISSUE TITLE
Release Planner error when creating a release plan for management plane 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5913]
Attempted to create a release plan for feature for Backup Service.  The release plan states it was created by it does not show up in "your release plans".   The product is "Cross Region Restore for Backup Vaults".   It is onboarded already using the release planner.  Here is the ADO work item that was created - https://dev.azure.com/azure-sdk/Release/_queries/edit/14994/?triage=true.  

![image](https://user-images.githubusercontent.com/67656762/229924433-53185588-c332-409c-8d3b-665dbdb86390.png)

**Comment by maririos** [comment]
@ladonnaq if you refresh the browser you will see the new version of the App (1.0.0-beta.5). 
When you do that, do you still see the Release plan missing?

**Comment by ladonnaq** [comment]
@maririos I am still getting the error.  I am using the release planner AKA link for PROD which is https://aka.ms/release-planner-preview.  Let me know if I need to do something in my environment (clear cache, etc).  

![image](https://user-images.githubusercontent.com/67656762/230494133-c4d58a4f-2558-4ce2-93a4-97a137ac0fea.png)
