### ISSUE TITLE
[PR Workflow] Update REST API PR labeling bot for TypeSpec rename

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#5917]
Some time back we added support in our labelling bot to add the "Cadl" label to any PRs that included files with the ".cadl" suffix. With the rename of Cadl to TypeSpec, we need to update this automation to look for files with the ".tsp" suffix and when found add the "TypeSpec" label (I already created the label).

Related work:
- https://github.com/Azure/azure-sdk-tools/issues/7353

**Comment by konrad-jamrozik** [comment]
Ideally to be fixed within the next 30 days.

**Comment by maririos** [comment]
If this is enabled, this could be used by the Release Planner apps and we can stop asking for this data manually.

**Comment by konrad-jamrozik** [comment]
[Relevant code](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=public/swagger-validation-common/src/utils.ts&version=GCb147aa4b5cb86d7afddbf061c966b815e41a0047&line=840&lineEnd=847&lineStartColumn=1&lineEndColumn=2&_a=contents):

``` typescript
export function isSwaggerGeneratedByCadl(swaggerFilePath:string) {
  try {
    return !!JSON.parse(readFileSync(swaggerFilePath).toString())?.info['x-cadl-generated']
  }
  catch{
    return false
  }
}
```

@weshaggard @mikeharder looks like we have automation that when it detects `x-cadl-generated`, it adds the `cadl` label. Do we want to follow this model, do instead regex file path matching as explained in https://github.com/Azure/azure-sdk-tools/issues/7353, or do both? If we want to do do such `x-` marker, how should it be called? `x-typespec-generated`?

[Example of `x-cadl-generated`](https://github.com/Azure/azure-rest-api-specs/blob/9c7722c82ca6c894e3d5931f074c4f025598af08/specification/voiceservices/resource-manager/Microsoft.VoiceServices/stable/2023-01-31/voiceservices.json#L6)

``` json
{
  "swagger": "2.0",
  "info": {
    "title": "Microsoft.VoiceServices",
    "version": "2023-01-31",
    "x-cadl-generated": [
      {
        "emitter": "@azure-tools/cadl-autorest"
      }
    ]
  },
```

**Comment by mikekistler** [comment]
We should do both -- check for TypeSpec files _and_ check for TypeSpec-generated OpenAPI.

OpenAPI generated from TypeSpec will have an `x-typespec-generated` marker.

<img width="322" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/85643503/82a55851-04c8-4344-89fe-dcbede84254b">

**Comment by konrad-jamrozik** [comment]
Closed as implemented and deployed. For details, see here:
- https://github.com/Azure/azure-sdk-tools/issues/7353#issuecomment-1839800985
