### ISSUE TITLE
Ask users to schedule an informational meeting if product is missing for service

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#5919]
On the release planner app, we allow partner teams to onboard a Service even if there is not any product in Cloud Lifecycle associated to it.

However, we expect them to schedule an informational meeting everytime they onboard a service withouth a prouduct, which is not happening right now.

**Comment by JonathanCrd** [comment]
Changes done here:
- An informational meeting is requested now everytime a product is missing
  -  This is now enforced. There is no option to skip scheduling the meeting and the Release Planner now checks the meeting state before proceeding.
 - UI changes:
   - Replaced warning pop-up for in-line warning (details on: https://github.com/Azure/azure-sdk-tools/issues/5233#issuecomment-1497997029)
   - Changed the the schduling pop-up.
   - Added a meeting confirmation when booking an informational meeting in the scheduler.

Here are the details for the UI changes:
![Screenshot 2023-04-05 181957](https://user-images.githubusercontent.com/17486462/230252310-3512d2d1-32ef-4bbf-aec0-5545f5b4fc22.png)
New alert for when it is required to schedule an informational meeting.

![Screenshot 2023-04-05 182116](https://user-images.githubusercontent.com/17486462/230252367-758c35e6-09ab-4fbf-8b3e-debc81ae15fe.png)
When the user clicks the button this timer gets triggered. It will check every 10 seconds to see if the meeting has been scheduled.

![Screenshot 2023-04-05 181615](https://user-images.githubusercontent.com/17486462/230252448-967628f2-25f6-41f9-a001-bf12ab4d29a6.png)
Once the meeting has been scheduled, the pop-up changes and let the user know that everything has been succesfull. The `Finish` button takes the user to the home page.

**Comment by maririos** [comment]
I really like the UI changes and the flow :)
Couple of questions:
- What does `Finish` means? just like a confirmation button to close the pop-up?
- The user is blocked to use the app because of the pop-up, correct?
- If the user closes the tab and they didn't book the meeting, when they open the Release Planner app again, what happens?

**Comment by JonathanCrd** [comment]
> What does Finish means? just like a confirmation button to close the pop-up?

Yes, it closes the pop-up, cleans some variables, and takes the user to the home screen. Any suggestions to rename the button? I'm also not quite sure "Finish" is the right word here...

> The user is blocked to use the app because of the pop-up, correct?

Yes, it blocks the entire view

> If the user closes the tab and they didn't book the meeting, when they open the Release Planner app again, what happens?

If the user doesn't click the "Book an Informational Meeting" button and closes the tab right after this pop-up appears, it will only get the email with next steps.  This is the same behaviour that we had already on the app.

Regarding the second part of your question, I don't think we have a view that let the user know which products they have onboarded.

If the user comes back to the intake questionnarie view, they will see an empty form. If the Service or Product selected has an ADO item already, they will see a notification saying that they are going to override it. I didn't change anything related to this behaviour.

![image](https://user-images.githubusercontent.com/17486462/230467459-bf5dc768-1bb4-4cd8-b1e2-4718d13ed70b.png)

I think that the current flow is not clear for users, and could lead to confusion. I would suggest to add some type of list to know what products or services have been onboarded, and also some type of confirmation screen, instead of using pop-ups.
However, since we will be working on a redesign of the app in the near future, I'm expecting for the whole layout and flow to change, so we could wait to make those improvements when we start implementing @ccbarragan's design.

**Comment by ccbarragan** [comment]
@JonathanCrd For the button label, I would go with `Close`. Common action label we use for this scenario :)
