### ISSUE TITLE
Create an adoption or usage PowerBI board for the Release Planner

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#5925]
Similar to the one we have for [Scheduler](https://msit.powerbi.com/groups/3e17dcb0-4257-4a30-b843-77f47f1d4121/reports/cda5f72c-9178-45a9-aea6-d3f3e6a822bd?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47&pbi_source=linkShare). The goal is to the adoption and usage of the tool

**Comment by maririos** [comment]
PM need this for the first iteration of the dashboard:

- Number per month of (service-product) who have onboarded
- List of (service-product) per month 
- Number of release plans created per month
- List service-product of release plans created per month and the state of the release plan 
  - Number for data or management

**Comment by JonathanCrd** [comment]
I created a PowerBI report for the Release Plans metrics inside the Azure SDK workspace, it contains:

- A graph of the number of Release Plans created month-by-month and their respective target lifecycle phase.
- A list of all the created Release Plans.
- The total number of Release Plans created with the tool.
- A donut graph for the Release Plans status (Not Started, In Progress, and Finished).
- Another donut graph for the service type (Management or Data plane).

I also created a second page for the onboarding metrics, but this is not useful until we finish working on the new Work Items implementation.

**Comment by maririos** [comment]
Added to the wiki: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/832/Release-Planner-App?anchor=usage

I will say for now this is good enough. Later on we can focus on improving it and adding the Onboarding data to it
