### ISSUE TITLE
Update SDK release request in Release Planner for management plane SDKs to include .NET SDK

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#5936]
The purpose is to extend the release request function to .NET.  Currently, it supports to request management plane SDK releases for Python, Java, JS, Go.  Without requests to track .NET SDK release, we could not build a clear view of .NET coverage, the same as other language in this dashboard https://aka.ms/azsdk/mgmt-sdk-monthly.

The issue is to request the following updates:
1.	Update SDK release request in Release Planner, ensure .NET is also listed as a supported language of management plane SDK release.  
2.	At backend, when click the “Submit Request” button, it also triggers a GitHub issue in [this repo](https://github.com/Azure/sdk-release-request/issues) for .NET coverage the same as other languages.

**Comment by josefree** [comment]
When "Management Plane" is selected, .NET is also listed in the "Languages to be released"
![image](https://user-images.githubusercontent.com/18413981/230591909-bb361772-7339-40ba-a624-8a9dba8a134a.png)

**Comment by josefree** [comment]
Add a reminder under the dropdown input: 

Note: for .NET SDK release, ensure to submit library codes, test cases and samples with a pull request in the .NET SDK GitHub repo for code review. Refer to [Management Plane SDK release process](https://aka.ms/azsdk/mgmt-sdk-for-dotnet-release)

![image](https://user-images.githubusercontent.com/18413981/230593721-1dd9c64f-ca08-4e05-b24e-a7c60e7bbcdb.png)

**Comment by josefree** [comment]
Hi wonder if we could prioritize this? According to SDK Inventory dashboard, we see .NET management plane SDK track 1 and track 2 coverage still have significant gaps.  
![image](https://user-images.githubusercontent.com/18413981/236360870-05168373-c112-4f08-9f32-0fe68167f21f.png)

To drive the improvement, I built this dashboard https://aka.ms/azsdk/mgmt-sdk-monthly to track all management-plane SDK releases cross all supported languages, however except .NET, because .NET release does not have such a tracking issue initiated by service team.  That's why I raise this request.

**Comment by maririos** [comment]
This is tied to #8161

**Comment by josefree** [comment]
since the openapi hub is deprecated. the corresponding feature has been moved to release planner. I updated title.

**Comment by maririos** [comment]
Work remaining here is:
- Update the `Request management SDK release app` to include .NET as language to select.
  - Make sure that it creates a GH issue too
- Remove the extra check  `Request a release for .NET` and instead add it to the other languages so it can be only one click
- Documentation needs to be updated too:
  - https://eng.ms/docs/products/azure-developer-experience/develop/sdk-release/sdk-release
  - https://eng.ms/docs/products/azure-developer-experience/develop/sdk-release/sdk-release-mgmt-dotnet#next-steps

**Comment by maririos** [comment]
Completed and deployed to prod. Documentation has also been updated
