### ISSUE TITLE
Swagger APIView PR pipeline automation reports success and failure

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#5941]
In [PR 23091](https://github.com/Azure/azure-rest-api-specs/pull/23091) the Swagger APIView PR pipeline automation is reporting success:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/85643503/230920654-478b1830-a680-47be-98fe-a4909e93f086.png">

AND failure:

<img width="857" alt="image" src="https://user-images.githubusercontent.com/85643503/230920774-c02b0f10-aa51-418d-867a-a7965a7122cb.png">

**Comment by mikekistler** [comment]
I have retriggered the pipeline ... hoping that this will resolve the problem.

**Comment by chidozieononiwu** [comment]
This is expected though as they are two different steps in the pipeline. The first is the run of the Swagger Parser which succeeds in creating the APIView token files. The later (which failed) is the call to the APIView endpoint to create and actual APIView using the token file generated.
Perharps we can improve the naming to say `SwaggerAPIViewParsing` for the first step?

**Comment by mikekistler** [comment]
Here is another instance: [PR 23616](https://github.com/Azure/azure-rest-api-specs/pull/23616)

It looks like the failure was:
```
  status: 500,
  statusText: 'Internal Server Error',
```
