### ISSUE TITLE
Assign reviewers on use of 'SDK Deprecation' label

### ISSUE THREAD

**Issue by mario-guerra** [Azure/azure-sdk-tools#5944]
As part of our Azure SDK [Deprecation Strategy](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/192/Azure-SDK-deprecation-strategy?anchor=process), I'm directing people to use the 'SDK Deprecation' label when they file a CSV change marking a package as deprecated. When this label is assigned, I'd like to have myself, Ronnie Geraghty, and Scott Addie added as reviewers to the PR.

This is the same functionality requested in this PR: https://github.com/Azure/azure-sdk/pull/5883
This issue is intended as an ask for implementation in the replacement for Fabric Bot.

**Comment by jsquire** [comment]
@mario-guerra :  How do we expect the label to be assigned?   If we know there's a specific CSV file that is changed for a deprecation, why would we not assign you folks as owners in CODEOWNERS for that path?  That would trigger the default GitHub behavior of assigning you whenever the CSV file is changed, regardless of whether or not a label is assigned?

**Comment by mario-guerra** [comment]
@jsquire ideally the label would be assigned by the person filing the issue, but I only yesterday learned that not everyone can add labels, only those with repo rights. Is that true? If so, then we may need to go with the CODEOWNERS option.

**Comment by jsquire** [comment]
@mario-guerra : That's correct - only folks with write access can add them.   From experience, people do not follow documented practices for adding labels when opening issues and pull requests.  If you'd like the process to be at all reliable, the CODEOWNERS approach is better.   That would allow you to get the label and review assignment automatically.

**Comment by mario-guerra** [comment]
Thanks, PR filed.

**Comment by jsquire** [comment]
I've been thinking over whether we should make this a general rule for PRs and Issues for "Add assignments when labels are added" and I just can't get it to a place where I think the benefits would outweigh all the edge cases for annoyance.

Since Mario's core use case is covered under the standard CODEOWNERS functionality, I'm going to close this one out for now.
