### ISSUE TITLE
A user can edit a past Informational meeting

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#5948]
From the main list of previous meeting, a user can see the details of any past meeting meeting.

Then, on the edit view,if the user makes any changes to the meeting, the update button will be enabled.

**Comment by maririos** [comment]
Does this happen in the other meetings too?

**Comment by maririos** [comment]
Closing as a dup of https://github.com/Azure/azure-sdk-tools/issues/6265
