### ISSUE TITLE
Release planner - SDK release app should show information why Next button is disabled

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5953]
Next button on the pre-req page of SDK release app is disabled if Spec PR is not signed off or merged. This causes confusion when a user looks at the release plan. We should show a notification why Next button is disabled to help user understand the reason.

It can be a tool tip for now.

**Comment by maririos** [comment]
This is covered in the UI improvements designs created by @ccbarragan . Clossing for now
