### ISSUE TITLE
APIView - Swagger API review does not have baseline revision for DPG swagger PR

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5955]
Baseline review is not generated for swagger PR changes in this PR. Baseline review should have been created using readme in the target branch and by using previous Tag when adding a new version tag.

https://github.com/Azure/azure-rest-api-specs/pull/23053/files#diff-ccad4a7108b6560254cfb900284c7cdd5fcc8c99bfd339c5d37724f2fe33aee2

**Comment by mikekistler** [comment]
Another case:

https://apiview.dev/Assemblies/Review/7c9102da436f48118cdbc65d7e59b09f

**Comment by mikekistler** [comment]
Another case:

https://github.com/Azure/azure-rest-api-specs/pull/24482
