### ISSUE TITLE
Release planner - Create release plan screen is not showing date as per label

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#5960]
Label `Lifecycle Stage|Date:` shows value `Private Preview|`.  It seems either label is incorrect or an expected date is missing in the value field.

![image](https://user-images.githubusercontent.com/55455725/231528221-94cef9e5-2e88-4ee6-86a8-21bf69592b13.png)

**Comment by maririos** [comment]
@ladonnaq to verify this is implemented in the new UI designs

**Comment by maririos** [comment]
This is going to be covered as part of the work on https://github.com/Azure/azure-sdk-tools/issues/5671
FYI @JonathanCrd

**Comment by JonathanCrd** [comment]
> This is going to be covered as part of the work on #5671 FYI @JonathanCrd Jonathan Cardenas FTE

Yes, as part of the changes in that issue, this label has been removed, now we just show `Product launch type` which is either Private Preview, Public Preview or GA.
