### ISSUE TITLE
TypeSpec validation should not fail if TSP changes has no impact on Swagger

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#5965]
It happens there was a PR that made a default behavior explicit. The Swagger emitter was already generating explicit syntax, this means that the change in the TypeSpec didn't implied a change in the Swagger:
https://github.com/Azure/azure-rest-api-specs/pull/23529

However, the CI failed saying that every PR should contain a Swagger. But I didn't have a Swagger on this one to put in the PR.

We forced merge the PR to unblock the service team.

**Comment by ckairen** [comment]
issue resolved with the new TSV
