### ISSUE TITLE
Change the PR box in API readiness to be a link vs box with prepopulated URL

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5966]
We have mentioned this before but I could not find a GitHub issue.  Having the pre-populated links to the public and private repo is more confusing than just copying the ULR into the box.  This feedback is from service teams and our team (stakeholders).  

![image](https://user-images.githubusercontent.com/67656762/231545545-8c39ec7d-9fee-45da-883d-80088a66f454.png)

**Comment by JonathanCrd** [comment]
Is it expected that the URLs always point to the same repos? I can add a validation step to verify that the URL is pointing to a valid repo.

**Comment by maririos** [comment]
Yes. They should be the specs and specs-pr repos.
If we find a team that doesn't use our repos, we need to talk to them

**Comment by ladonnaq** [comment]
Teams find it easier to just copy the URL vs going to find the issue number.  Also, they tend to not read the pre-populated link and then tell me their issue is not found but it is because they were using the wrong link (public repo vs private and vice versa).  If we keep the prepopulated links, then we should have a tooltip or something that explains there are 2 repos and that they need to copy the correct issue number into the box.

**Comment by ladonnaq** [comment]
> Does the `Associate` button has a validation? worth checking. Checking it ends in `pr` .... Idea from @praveenkuttappan

Good question. I was curious about that... if anything was being validated when the button was clicked.

**Comment by JonathanCrd** [comment]
I have made this change for both Management and Data plane apps.
There is validation going on already in the button, no extra validation to the textbox was needed.
