### ISSUE TITLE
RPaaS work item field data value is not always accurate 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#5971]
I was looking at all of the active work items for APEX to make sure we had contacted all of teams with launches before build.  I noticed that there were quite a few work items that had FALSE for the value of the RPaaS field but I remember from my interactions with the service team that the RP is RPaaS.  

- How is the RPaaS field updated for the ADO work items?  Is it only updated when a service team uses the release planner to onboard?  
- If so, then these could be work items that were generated with the survey. I can ask Siva to go look at the PRs for all the work items that have a value of FALSE for RPaaS because the PRs do have the label RPaaS if the RP is RPaaS.  Does anyone know of another way to confirm RPaaS or non-RPaaS?  This data is not in service tree. 

Here is the query I am using -  https://dev.azure.com/azure-sdk/Release/_queries?tempQueryId=537c0b0e-27d3-4be3-9ed9-22d5898ab46e.

**Comment by maririos** [comment]
> How is the RPaaS field updated for the ADO work items? Is it only updated when a service team uses the release planner to onboard?

It looks like the Release Planner only updates that field when a team fills the Onboarding questionnarie (notice that they can overwrite previous values). The `RPaaS` value comes from their answer on:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/9868623/231860912-456e08e4-1b87-426d-819d-3f3c02152d51.png">

**Comment by ladonnaq** [comment]
> > How is the RPaaS field updated for the ADO work items? Is it only updated when a service team uses the release planner to onboard?
> 
> It looks like the Release Planner only updates that field when a team fills the Onboarding questionnarie (notice that they can overwrite previous values). The `RPaaS` value comes from their answer on: <img alt="image" width="673" src="https://user-images.githubusercontent.com/9868623/231860912-456e08e4-1b87-426d-819d-3f3c02152d51.png">

Thanks @maririos!  I am going to keep this issue open as I explore if there are any other options that we can use to confirm RPaaS.  I have inquiries out to the ARM team.

**Comment by maririos** [comment]
This has been modified as part of the UX/UI work done https://github.com/Azure/azure-sdk-tools/issues/5631
