### ISSUE TITLE
Add URL validations and catch errors when creating a new Release Plan for Data Plane

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#5978]
This is a continuation of https://github.com/Azure/azure-sdk-tools/issues/5977

**Comment by maririos** [comment]
@JonathanCrd Is this still applicable?

**Comment by JonathanCrd** [comment]
No, we don't longer ask for these URLs when creating a release plan, and we have validations implemented in the onboarding questionnaire.
