### ISSUE TITLE
Retry on sparse checkout

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#5990]
A failure was noted in GitHub Event Processor on sparse checkout https://github.com/Azure/azure-sdk-for-cpp/actions/runs/4704718893/attempts/1 

```
+ git clone --no-checkout --filter=tree:0 https://github.com/Azure/azure-sdk-for-cpp .
Cloning into '.'...
fatal: unable to access 'https://github.com/Azure/azure-sdk-for-cpp/': The requested URL returned error: 429
Error: Process completed with exit code 128.
```

Given that 429 could be a non-terminal failure we could probably see success in these jobs by adding a retry.

**Comment by jsquire** [comment]
Since the approach has shifted to downloading the files that are needed directly from Git Hub rather than cloning, I don't believe this is needed any longer.  I'm going to close this out.
