### ISSUE TITLE
Test-Proxy should fail to start if a path starting with `/mnt/[A-Za-z]` is detected

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#6006]
To account for the common case of folks running tests in WSL against an assets repo originally stored from windows.

**Comment by benbp** [comment]
@JimSuplizio @weshaggard any idea why msftbot assigned this?

**Comment by mario-guerra** [comment]
@benbp I get assigned to issues that use the 'Test-Proxy' label to keep track of questions that come in from the developer community.

**Comment by scbedd** [comment]
Closing. We no longer support `docker`.
