### ISSUE TITLE
tool bug with adding "CI-MissingBaseCommit" tag

### ISSUE THREAD

**Issue by kazrael2119** [Azure/azure-sdk-tools#6024]
I missed a tool error in this pr:[Adding support for user assigned managed identities on ACS Resources by jorge-beauregard · Pull Request #12177 · Azure/azure-rest-api-specs-pr (github.com)](https://github.com/Azure/azure-rest-api-specs-pr/pull/12177)
the author has split the first commit ,but bot still add "CI-MissingBaseCommit" tag
![image](https://user-images.githubusercontent.com/98569699/233531329-cb9df0a4-4eaa-4a6a-919d-5722399d64b2.png)
![image](https://user-images.githubusercontent.com/98569699/233531349-af453857-439a-4ee8-8166-c1de63628879.png)

**Comment by v-xuto** [comment]
The same issue was also encountered in https://github.com/Azure/azure-rest-api-specs/pull/23676.

**Comment by konrad-jamrozik** [comment]
@kazrael2119 can you clarify what is the expected behavior and actual behavior?

Is the problem here that the tool incorrectly added the `CI-MissingBaseCommit` label? 
In which circumstances do you expect for this label to be added?

**Comment by kazrael2119** [comment]
> @kazrael2119 can you clarify what is the expected behavior and actual behavior?
> 
> Is the problem here that the tool incorrectly added the `CI-MissingBaseCommit` label? In which circumstances do you expect for this label to be added?


@konrad-jamrozik， The actual behavior is that the label is added to the pr, but the expected behavior is that the label should not be added to the pr. Because the author has already split the first commit, its first commit is simply copied from the previous apiversion.

I think it's a bug in the tool

I expect this tag ``` CI-MissingBaseCommit ```to be added when the author's first commit is not a copy of an existing apiversion

**Comment by kazrael2119** [comment]
@konrad-jamrozik ，I found a new issue in this pr:https://github.com/Azure/azure-rest-api-specs/pull/23725
this is a new service, so it doesn't have base commit. but tool still add ```CI-MissingBaseCommit```, I think if it is a new service, the tag should not be added

**Comment by sfeitler** [comment]
I think we may be seeing this issue too in https://github.com/Azure/azure-rest-api-specs-pr/pull/14352. The first commit in this PR is just a copy of the prior preview api version, but still the label has been applied.

**Comment by konrad-jamrozik** [comment]
The label `CI-MisingBaseCommit` is gone altogether.
