### ISSUE TITLE
Tracking data related to new service onboarding 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6037]
We have a request from Azure SDK leadership to provide data for new services onboarding with the Azure SDK team.  Today all of our Azure Devops data is for products that we are tracking for APEX launch readiness.  There was a field added to the ADO work items in 2022 to add name and service tree ID for the associated service and the lifecycle of the associated service.  

- Determine the best way to track new services onboarding going forward. 
- To get this data now, I pulled all of the APEX product data from Azure Devops and manually sorted to figure out an estimate of number of services onboarding over time - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/EQg6yA-U0x9Jox4a_qQ34J4BpbRfiy_DsRoxSz6YCiMfAw?e=8d3TkE.  This effort was time consuming, and I had to estimate the onboard date for the older data (because anything before 2022 was migrated to our project by Carl). It might be good to generate a work item or something for each service, then have the products be children of the service.  This way we can keep service specific data with the service record and APEX related data in the work item for the products. @maririos We should consider how we want to do this as part of the redesign of ADO release project that you were investigating.

**Comment by maririos** [comment]
This has been covered as part of https://github.com/Azure/azure-sdk-tools/issues/5698
