### ISSUE TITLE
Support request by Adrian Tang: suppression R1001 for LintDiff error doesn't work

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6044]
Per the [Teams thread](https://teams.microsoft.com/l/message/19:9efda948665d481086766c0b7572abc3@thread.skype/1682365764203?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1682365764203&teamName=Azure%20SDK&channelName=Service%20API%20Toolset&createdTime=1682365764203&allowXTenantAccess=false):

> [Yesterday 12:49 PM] Adrian Tang
>
> Title: Swagger approved, but failing OperationIdNounVerb error on already GA'ed APIs.
> 
> Hello Service API Toolset. We have an approved Swagger
> https://github.com/Azure/azure-rest-api-specs/pull/18869/checks?check_run_id=12985916840
> but is failing SwaggerLint Diff due to OperationIdNounVerb rule. The rule is failing on already GA'ed APIs. We are unable to change the names because of this.
> We were advised by the API review board to add a suppression to R1001, which we did in the pull request. We want to ask how we go about getting the suppression applied, as the Swagger LintDiff is still failing. Thanks.
> CC: Erica Sponsler (SHE/HER), Mike Kistler, Laurent Mazuel

PR: 
- https://github.com/Azure/azure-rest-api-specs/pull/18869

Suppression:
- https://github.com/Azure/azure-rest-api-specs/pull/18869/files#diff-ccad4a7108b6560254cfb900284c7cdd5fcc8c99bfd339c5d37724f2fe33aee2

**Comment by konrad-jamrozik** [comment]
@weshaggard is attempting working suppression with this PR:
- https://github.com/Azure/azure-rest-api-specs/pull/23723

I asked on the Teams thread @whisper6284 how he determined the suppression format to use. He let me know this is the format his team was using in the past 2 years plus it was recommendation from @lmazuel. It is unclear where this guidance originated from in the first place.

**Comment by weshaggard** [comment]
Fixed this particular issue with https://github.com/Azure/azure-rest-api-specs/pull/23723
