### ISSUE TITLE
[LintDiff][False positive] failure reported by Sushant Sood: incorrect error `GetCollectionResponseSchema`

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6049]
- The [Teams thread](https://teams.microsoft.com/l/message/19:9efda948665d481086766c0b7572abc3@thread.skype/1682446528744?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1682446528744&teamName=Azure%20SDK&channelName=Service%20API%20Toolset&createdTime=1682446528744&allowXTenantAccess=false)

- PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/12012
- Failing check: https://github.com/Azure/azure-rest-api-specs-pr/pull/12012/checks?check_run_id=12997222555

This is confirmed to be a problem with the tool by @lirenhe.

**Comment by rkmanda** [comment]
We took a look and the rule actually was doing what it was meant to do. The same issue was reported by the reviewer as well as an explicit comment in the PR. Once the author fixed the issue the error went away in the last iteration.
