### ISSUE TITLE
Review Ticket (Arch Board Namespace Approval) is hardcoded to azure-sdk-pr 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6053]
The review ticket field is hardcoded to azure-sdk-pr and there is no way to change.  Not all arch board namespace approval GitHub issues will be in azure-sdk-pr.  Some will be in azure-sdk.  It depends on if the service team needs to keep everything private until Public Preview or announcement.   

- [ ] Change the name of the field to `Arch Board SDK Namespace Review GitHub Issue` and let teams just put a link in vs hardcoded link.  
- [ ] This field should only show up in Public Preview release plan and only for initial beta release plans.  

![image](https://user-images.githubusercontent.com/67656762/234671598-a0e15e87-4e34-4309-9583-92e1c32dd87e.png)

**Comment by maririos** [comment]
- Review Ticket should be moved to the SDK Release app
- Remove the view `Generate SDK` from this app as it is confusing
