### ISSUE TITLE
Avocado validation failure approved for suppression but API readiness does not recognize  

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6066]
Creating a GitHub issue to track resolution of bug found in testing real service team data with release planner.  

![image](https://user-images.githubusercontent.com/18413981/234778589-a1b20df7-cf47-47b2-9096-2f8bbfc61398.png)

![image](https://user-images.githubusercontent.com/18413981/234779546-6345011f-a409-4cab-be72-f805e4ae9517.png)

![image](https://user-images.githubusercontent.com/18413981/234779783-61dc2e01-259c-4bf7-9662-ac24be21697e.png)

- [ ] Josephine confirmed that If the Avacado validation failure is approved, it should not block ARM review.  We need to figure out why this is not working as intended.  Also, when there is a spec validation failure but approved (okay to merge and ignore the failure), the status should be "Failed with approval" on the signoff screen. 

This is a blocking issue from onboarding service teams to the release planner.

**Comment by maririos** [comment]
Need to check this behavior in data plane too. Related issue #5961

**Comment by maririos** [comment]
Improve word for `Approve` as it is not clear what it means...

**Comment by praveenkuttappan** [comment]
I have looked at the code. Each validation has approval status to suppress validation failure. So, we should handle all validation suppression in this change and not just avocado failure.
