### ISSUE TITLE
API Ref Doc Preview is not being generated 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6067]
Bug was found during testing of real service team data for management plane API readiness.  

![image](https://user-images.githubusercontent.com/18413981/234779084-ea8b4e1c-d91d-49f9-929f-2b46e669a6dc.png)

- [ ] This has to be escalated to Tooling team to take a look. But very likely they will need SKILL team help.  Terry Jin of SKILL team used to be the go-to person for this hang-on issue.

**Comment by maririos** [comment]
This will be an issue in the tooling itlself and not in the Release Planner. The Release Planner is quering information from GH.
The author of the PR should follow up with the Assignee to ask for help or follow https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/923/API-Spec-Validation-Tooling-Support
