### ISSUE TITLE
[LintDiff] Deploy pending `azure-openapi-validator` changes from staging to prod

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6071]
As required by this support request:
- https://github.com/Azure/azure-sdk-tools/issues/5744

The LintDiff PR CI check running on https://github.com/Azure/azure-rest-api-specs hasn't got its changes deployed from staging to prod since months.

Investigation shows doing it in a safe, correct way is nontrivial. This task is about accomplishing this.

Related task o document this process for further deployments:
- https://github.com/Azure/azure-sdk-tools/issues/6070

Note there is a private Teams chat between Brett DeFoy, myself and few other folks to help with figuring out some specific pending changes to get deployed on request by Brett, per:
- https://github.com/Azure/azure-sdk-tools/issues/5744

**Comment by konrad-jamrozik** [comment]
# A plan how to deploy staging LintDiff changes to prod

## The goal

We want to deploy the LintDiff ruleset currently running as part of the `~[Staging] Swagger LintDiff` PR CI check to `Swagger LintDiff` PR CI check. We want to do it in a safe, reversible manner. That is, if the changes we deploy will break prod check, we want to be able to revert it quickly.

## What needs to be done

The [ruleset package.json](https://github.com/Azure/azure-openapi-validator/blob/main/packages/rulesets/package.json) needs to be updated from `1.0.1` to `1.1.0` and released to the [npm @microsoft.azure/openapi-validator-rulesets package](https://www.npmjs.com/package/@microsoft.azure/openapi-validator-rulesets?activeTab=versions) via the [azure-openapi-validator to npm](https://dev.azure.com/azure-sdk/internal/_release?_a=releases&view=mine&definitionId=80) release pipeline.

**However** we cannot do this outright, as doing so would immediately update the ruleset used in prod check and leave no easy way of reverting this change.


## The plan step by step

**Comment by weshaggard** [comment]
@konrad-jamrozik sounds like a reasonable plan.

**Comment by konrad-jamrozik** [comment]
# Plan execution status

Stage 1:

1.1:
- https://github.com/Azure/azure-openapi-validator/pull/493

1.3:
- https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/468946

**Comment by konrad-jamrozik** [comment]
Need to delay deploying the rules in staging to prod due to users reporting multiple false positives:

- https://github.com/Azure/azure-rest-api-specs-pr/pull/12357#issuecomment-1535557462

Here are the rules identified to produce false positives. They need to be disabled before we deploy anything to production:

- ResourceMustReferenceCommonTypes
- LROPostFinalStateViaProperty (the plan is to remove any rules that address 'final-state-via ')
- ProvisioningStateMustBeReadOnly

**Comment by konrad-jamrozik** [comment]
Note this rule has been disabled by:
- https://github.com/Azure/azure-openapi-validator/pull/506
