### ISSUE TITLE
Update Review meeting table column in Data plane API readiness check to replace Meeting notes

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6072]
Can we remove meeting notes and change to "Review or update prerequisites or artifacts" @maririos - Which term makes more sense prerequisties or artifacts? We want the user to update the prerequisite information in the scheduling tool so that the GitHub issues will get updated with the artifacts. They should be able to access the meeting from this table to update as they continue to prepare for the API review meeting.

**Comment by maririos** [comment]
Yes remove the `Meeting notes` column
