### ISSUE TITLE
[LintDiff][False positive] Staging linter rule LROPostFinalStateViaProperty inconsistent with ARM RPC

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6081]
The [LROPostFinalStateViaProperty linter rule](https://github.com/Azure/azure-openapi-validator/blob/main/docs/lro-post-final-state-via-property.md) checks and flags non-compliance to:

> A long running operation (LRO) post MUST have 'long-running-operation-options' specified and MUST have the 'final-state-via' property set to 'azure-async-operation'.

But this is inconsistent with the [ARM RPC](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#call-action-post-asynchronously), which says

> Optional: The response headers may include an Azure-AsyncOperation header pointing to an Operation resource (as described below).

**Comment by mikekistler** [comment]
cc: @rkmanda

**Comment by konrad-jamrozik** [comment]
@bdefoy assigning you as this is issue with rule contents. Feel free to route to the rule owner.

**Comment by konrad-jamrozik** [comment]
Note this rule has been disabled by:
- https://github.com/Azure/azure-openapi-validator/pull/506

**Comment by rkmanda** [comment]
[Task 23293591](https://msazure.visualstudio.com/One/_workitems/edit/23293591): [LintDiff][False positive] Staging linter rule LROPostFinalStateViaProperty inconsistent with ARM RPC #6081

**Comment by rkmanda** [comment]
The rule is disabled and there is no further action required

**Comment by konrad-jamrozik** [comment]
> The rule is disabled and there is no further action required

@rkmanda should we delete this rule altogether? If not, then I presume the goal is to enable it at some point. Should we have an item to track this?
