### ISSUE TITLE
[LintDiff] for ShiftLeft does not give early warning of problems

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6085]
The Swagger LintDiff PR pipeline check does not warn Shift-Left pipeline users of problems they will encounter when pushing their changes to a production branch.

The intent of the Shift-Left pipeline is to give service teams early feedback on their changes so that they can fix problems early -- not when they are really to push their changes to a production branch. But the current LintDiff pipeline check does not achieve this goal because it suppresses warnings for any changes already merged to the development branch. But those warnings are not suppressed when the changes in the development branch are targeted to a production branch.

A good example is [PR 12072](https://github.com/Azure/azure-rest-api-specs-pr/pull/12072/checks?check_run_id=12912847924), to the ARMCoreRPDev branch, and [PR 12317](https://github.com/Azure/azure-rest-api-specs-pr/pull/12317), which targets main.

The LintDiff check for PR 12072 identified 27 errors but since they were already existing in the branch prior to the PR it marked the LintDiff check as "succeeded".

The LintDiff check for PR 12317 found the same 27 errors but this time marked the check "failed" since all the errors come from the ARMCoreRPDev branch.

**Comment by konrad-jamrozik** [comment]
Closing as not planned because ShiftLeft is deprecated and unsupported.
