### ISSUE TITLE
Error trying to create data plane release plan for Public Preview 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6090]
Unable to create data plane release plan for Public Preview for product.  Management plane release plan created successfully.  

Link to work item:  https://dev.azure.com/azure-sdk/Release/_workitems/edit/12972/?triage=true

![image](https://user-images.githubusercontent.com/67656762/236063377-4e0e4cdd-622f-4876-9eb5-ef8cd6c36551.png)

**Comment by maririos** [comment]
@JonathanCrd this sounds very similar to the bug you fixed in management plane about the API Spec field. Is this familiar ?

**Comment by JonathanCrd** [comment]
It looks like. This is the issue you are referring to: https://github.com/Azure/azure-sdk-tools/issues/5913
I will take a look at this issue and see if I can repro it. Probably I can do the same fix for this issue too.

**Comment by ladonnaq** [comment]
> It looks like. This is the issue you are referring to: #5913 I will take a look at this issue and see if I can repro it. Probably I can do the same fix for this issue too.

Let me know if you figure out what field is causing the error. I checked and the fields either had data, N/A, or were blank.

**Comment by JonathanCrd** [comment]
The problem was the same as the other issue. the field `Private Preview API PR` in the Data Plane tab was set to `N/A`.

I added extra validation to ignore it when having "N/A" as its value
