### ISSUE TITLE
[APIView] Make GA baseline available for diff in PR and manual reviews

### ISSUE THREAD

**Issue by kristapratico** [Azure/azure-sdk-tools#6102]
The latest GA baseline is available to diff with in the Auto review, but it would be nice to have it for PR and Manual reviews as well. 

Examples:

Auto review (GA diff possible): https://apiview.dev/Assemblies/Review/453e3478565f4bdfb4df7e8ca9b53ba9/1dc33399b3ef45b8a21037a36c14bdaf?diffRevisionId=c047c4a8e0f647a58e2b7b3ad4cf6e10&doc=False&diffOnly=True
Manual review (I need to manually add the GA baseline myself): https://apiview.dev/Assemblies/Review/f654d0b58676400a9fe225b5df013d73
PR review (not possible right now AFAIK): https://apiview.dev/Assemblies/Review/c601ac01f6c14a5d853e3fd8623df00a

**Comment by mikekistler** [comment]
@praveenkuttappan to create a separate issue for REST API, where the same requirement exists.

**Comment by chidozieononiwu** [comment]
This is not be an issue any longer due to the fact that we now show all API-Revision for a Review regardless of type, so you can diff across APIRevision types.
