### ISSUE TITLE
Test resource group delete should ensure that all deployments are in a terminated state

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#611]
We've seen instances where a resource group came back after deletion while a deployment was ongoing. We should check for any ongoing deployments and ensure they are properly terminated before deleting the resource group. 

Investigate canceling the deployment: https://docs.microsoft.com/en-us/rest/api/resources/deployments/cancel

We should be able to repro this by:

1) Deploy ARM template with relatively slow resource (say 5 minutes to deploy)
1) Kill client process (but deployment continues on server)
1) Delete RG
1) See what happens

Then compare to the above process with steps 3 and 4:

3) Cancel ARM template
4) Delete RG

The first scenario should have the RG reappear, the second should work as expected.

**Comment by kurtzeborn** [comment]
This is done.  We do out-of-band deletion now.
