### ISSUE TITLE
[APIView] TypeSpec APIView failed with "Internal Server Error" from APIView service

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#6110]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2755162&view=logs&j=e37a1bb9-a190-5269-3a0e-37469dfbe682&t=0f4d9e1c-b84a-5348-e162-7b2c6c640d5f&l=59

**Comment by praveenkuttappan** [comment]
API review was created when I retried the same request. It had failed earlier to download generated artifact from Azure Devops. I think this was a temporary glitch in accessing artifact. I will keep this issue open for some time to see if it happens again.

Generated review: https://apiview.dev/Assemblies/Review/e92d8a52a5f7477f91fea9bd9502098c
