### ISSUE TITLE
APIView - Update version label on the automatic review 

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6111]
Automatic API review does not get a new revision if API surface matches with any of the current revision. This causes confusion when reviewing API review which shows previous package version even though package version is updated.

This Issue is filed to make an enhancement in automatic API review workflow to tag/update package version in the label of existing matching revision to show latest package version with the API surface.

**Comment by WhitShake** [comment]
This is completed. Do we want to change from updating versions to appending versions so all version usage can be tracked?
@praveenkuttappan

**Comment by WhitShake** [comment]
Completed
