### ISSUE TITLE
APIView - Add next and previous for diff

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6114]
Add next and previous button at each diff to easily navigate to next diff. Currently it is really difficult to find a diff within larger API reviews. We currently do similar next/previous buttons for the comments. We should add similar buttons for diff also.

**Comment by chidozieononiwu** [comment]
We can identify diffs by [code-removed or code-added ](https://github.com/Azure/azure-sdk-tools/blob/ffe81dfa74a95d5d5df3bf97217b154e15957047/src/dotnet/APIView/APIViewWeb/Pages/Assemblies/_CodeLine.cshtml#L21-L22) css, perhaps on button click move scroll position to next or previous sibling.

**Comment by maririos** [comment]
PR https://github.com/Azure/azure-sdk-tools/pull/8898
