### ISSUE TITLE
APIView - Add a check in PR status to show APIView approval status

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6115]
We allow to merge a PR even if API review is not approved since API review happens later in SDK dev cycle. But swagger API review team likes to know the status of API review approval before they merge swagger API review change. This issue is filed to track anew enhancement to add a new check in PR checks which will track API review status if there is an API review created for that PR. 

We should enable this check as only a required check for Swagger and TypeSpec.

**Comment by maririos** [comment]
This is currently being managed by the labels in the Specs repo. There is no need for APIView to communicate approval (that doesn't happen)
