### ISSUE TITLE
Automate updating of Java SDK metadata CSV with updated speech SDK packages

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#6116]
https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/java-packages.csv

Query in [`Query-Azure-Packages.ps1`](https://github.com/Azure/azure-sdk/blob/252df975d12a972740733d64edba9e18487fc926/eng/scripts/Query-Azure-Packages.ps1#LL36C52-L36C93) should include `com.microsoft.cognitiveservices.speech` to ensure that the speech SDK is properly updated on release.

**Comment by kurtzeborn** [comment]
This falls under the larger question of "how much work do we want to do for teams that are outside of our engineering system?"  For this, if we don't do this, it turns into another manual step (update the version in the csv or in the metadata file in the docs repo) that we could just add to the wiki for them to follow, correct?

**Comment by danieljurek** [comment]
This was initially intended to making updating docs versions of packages published outside of our engsys easier. However, since our docs onboarding logic changed later in 2023 all updates to docs versions are manual and so this work is not necessary.
