### ISSUE TITLE
Docs Metadata JSON support for "use-other-source" for version field

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#6117]
Today the `version` field in metadata JSONs overrides the version found the CSV file in all cases. 

For docs onboarding there are some cases where versions in the metadata JSON files are not updated. Since that data is already available in the metadata CSV files we don't want to have the stale version in the metadata JSON file overriding the newer version in the CSV file. So, in these cases we should have a value like `use-other-source` (or `float`, etc.) in the `version` field which our onboarding logic will recognize and handle appropriately.

**Comment by danieljurek** [comment]
@JimSuplizio and I spoke and there's a better way to do this. 

Data flow for docs package onboarding is currently: `CSV Metadata file` -> `metadata/*/*.json` -> `Docs onboarding (ci-config|bundlepackages|package.json|etc.)` 

Making data flow from `metadata/*/*.json` to `CSV Metadata file` would result in further complication of our code and increase fragility. A smarter way to do this is to onboard just from `metadata/*/*.json` files and not worry about information in the `CSV Metadata file`. 

To accomplish this we'll need to have a way to ensure that: 
1. All `metadata/*/*.json` files have information needed so that we don't have to correlate information from the `CSV Metadata file` 
2. Metadata for packages released outside our EngSys is updated by some automated means from information in the `CSV Metadata file` ... There are some edge cases where we have packages onboarded (e.g. [cognitive services speech package](https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/java-packages.csv#L724)) cannot have version information updated by automation. In those cases, we need teams to update the `CSV Metadata file` with correct version information.

**Comment by JimSuplizio** [comment]
To add to what Daniel wrote.
3. For metadata packages released outside of our engineering system we want the onboarding/updating to be simpler so external teams can be self-sufficient. If all they have to do is add a metadata/*/_library_.json file when onboarding a new library or update the version in the file when they release a new version, then we'd have to spend less time helping teams onboard.
