### ISSUE TITLE
API readiness signoff improvements

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6122]
There is currently no action to notify the Azure SDK APEX PMs and the service team member tracking APEX when API Readiness is completed.  

- [x] When the user selects "Complete" for API Readiness pop-up notification that states that the Azure SDK APEX PMs and the Cloud Lifecycle Owner for their product will be notified that API Readiness is completed for [Product name + release plan lifecycle].   
- [x] Send email to azsdkapex@microsoft.com and the APEX PM associated with the release plan stating that API Readiness is complete for [Product name + release plan lifecycle] and link to the ADO work item for the product.   Email templates, required data values, ADO updates can be found in this doc - https://microsoft-my.sharepoint.com/:w:/p/ladonnaquinn/EbrUkOkGf2dLtUzeoEDnszQBh6eqoLR0HIFYDgA8FOdndw?e=4e3hMM
- [x] ADO work item updates.   Email templates, required data values, ADO updates can be found in this doc - https://microsoft-my.sharepoint.com/:w:/p/ladonnaquinn/EbrUkOkGf2dLtUzeoEDnszQBh6eqoLR0HIFYDgA8FOdndw?e=4e3hMM

**Comment by maririos** [comment]
>  ADO work item updates. TODO: Will create a table so that it is easier to understand what fields need updated, the values, and any values that must be calculated (logic required).

This might change according to new ADO designs

**Comment by maririos** [comment]
@ladonnaq could you provide the template of the email?

- Send email to [azsdkapex@microsoft.com](mailto:azsdkapex@microsoft.com) and the APEX PM associated with the release plan stating that API Readiness is complete for [Product name + release plan lifecycle] and link to the ADO work item for the product.

**Comment by maririos** [comment]
ping @ladonnaq

**Comment by maririos** [comment]
@JonathanCrd while we get the email template, could you start with the logic implementation for this? this issue applies for both the management and data plane API Readiness apps

**Comment by JonathanCrd** [comment]
I would also add a way to close or go back to the main Release Planner app

**Comment by maririos** [comment]
> I would also add a way to close or go back to the main Release Planner app

Great point! letting the user know what happened or what it means

**Comment by ladonnaq** [comment]
FYI - I added the link to the word doc for the email templates to the description tasklist on 06/28/2023.  Just wanted to make sure you both noticed.  Thanks!

**Comment by maririos** [comment]
@ladonnaq thank you! With @JonathanCrd we have reviewed the doc and added clarifying questions to it. Could you please take a look?

**Comment by ladonnaq** [comment]
I answered questions.  @JonathanCrd Let me know if you want to meet and have a quick discussion so you will be able to implement sending the emails for API readiness for all Release Plan types.

**Comment by JonathanCrd** [comment]
Thank you @ladonnaq !

Finished adding the new templates to the database. A summary of the changes done in the scope for this issue are:

- An email is sent once the user clicks "Complete".
- New email html templates has been added into the database.
- New view has been added to let the user know they have completed the milestone, and point them into the Release Planner main app. (This new view is part of the new design).
