### ISSUE TITLE
Drop-down box to select release train is empty 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6126]
In the management plane SDK release milestone (power app), the drop-down box to select the release train is empty.  The box should show the current (if not past the code cutoff) and upcoming months.  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/f74401d3-2bb3-46a3-b529-3df413ece241)

**Comment by praveenkuttappan** [comment]
I would like to discuss about this issue to get more clarification on how release trains are created and maintained.
FYI @maririos

**Comment by praveenkuttappan** [comment]
As per the implementation, it fetches release trains for management-plane/date-plane from a Dataverse table. So my question is who is maintaining this table to create release trains. Are release trains created in an external system or entity and then synchronized to release planner app?

**Comment by ladonnaq** [comment]
> As per the implementation, it fetches release trains for management-plane/date-plane from a Dataverse table. So my question is who is maintaining this table to create release trains. Are release trains created in an external system or entity and then synchronized to release planner app?

@josefree Would you please answer the question?

**Comment by maririos** [comment]
This applies to OpenAPI Hub on how it surfaces the information when a user "Request a Release"

**Comment by maririos** [comment]
gentle ping to @josefree

**Comment by josefree** [comment]
Hi, can we adopt the implementation of https://portal.azure-devex-tools.com/tools/request-api-release.  Per I know, the release date is calculated, not pre-registered. 

![image](https://github.com/Azure/azure-sdk-tools/assets/18413981/69d99781-2ca2-420d-b1e5-f6088a87b321)

**Comment by maririos** [comment]
We went with another approach based on https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0-1&t=1lCBRP1NpVo69ZVV-0
