### ISSUE TITLE
[TypeSpec][APIView] TypeSpec and APIView generation fails but PR is merged and SDKs are in process of being released

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6127]
Azure Content Safety has simultaneous Private and Public Preview.  I am testing the API readiness app with their data.  

This PR is the latest PR in the public repo and it does not pass TypeSpec validation so it fails API Readiness in the power app. https://github.com/Azure/azure-rest-api-specs/pull/23840  However, the PR is merged and the beta SDKs are in the process of being released. 

What should be done so that API readiness will pass in the app?  

- Details on why TypeSpec failed - https://github.com/Azure/azure-rest-api-specs/pull/23840/checks?check_run_id=13332240958 and https://github.com/Azure/azure-rest-api-specs/runs/13332240958
- If this failure was "approved" and it is okay to "merge", then we need something added to the PR that indicates that we should ignore the TypeSpec error.  Perhaps a label?

**Comment by praveenkuttappan** [comment]
TypeSpec validation failure does not have a specific label to approve the failure like other validations. I think we should add a label for TypeSpec validation failure override if it is supposed to be overridden.

**Comment by maririos** [comment]
> TypeSpec validation failure does not have a specific label to approve the failure like other validations. I think we should add a label for TypeSpec validation failure override if it is supposed to be overridden.

Adding Spec Tools label as this involves a larger conversation on how we want to handle the process in the specs repo

**Comment by ladonnaq** [comment]
@maririos Is this issue still relevant?  In the API Readienss app - Do we know if TypeSpec validation fails and are able to direct the user in the API readiness app to the location in the PR that has the information related to the validation errors?   If so, then we can probably close this issue.

**Comment by maririos** [comment]
We show the status of the build and they should always go to the PR to see next steps. So yes. we should close this :)
