### ISSUE TITLE
APIView: can we change 'Approvers' to 'Approved by'?

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#6129]
In the screenshot I didn't realize that the `Approvers` had actually approved it. I thought it was telling me who _could_ approve it. I think a little rename of the label would make it clear.

![image](https://github.com/Azure/azure-sdk-tools/assets/51494936/e0346c3c-ad13-4837-8823-9b16bbd07861)

**Comment by richardpark-msft** [comment]
Thanks all, I knew if I believed in the process it would pay back.

**Comment by maririos** [comment]
> Thanks all, I knew if I believed in the process it would pay back.

You will see the changes after our deployment next week :)
