### ISSUE TITLE
ApiView should not show a diff when its just an order change

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#6132]
In this apiview [Azure.ResourceManager.Compute (1.2.0.0) - Created for PR 35294 - apiview.dev](https://apiview.dev/Assemblies/Review/f627a0d9bde640278a9ffbad2df17f87/5f6d6872cbf3432eb7191c1943df65cf?diffRevisionId=8c05696a68284ad2ba945eb732e9013d&doc=False&diffOnly=True)

We see a diff for `AvailabilitySetCollection` yet it appears the only diff is its ordering.  For the purpose of ApiView this should not be shows as a diff as there is no actual api change here.

![image](https://github.com/Azure/azure-sdk-tools/assets/64171366/3f182d74-1dd5-4e5b-878a-16b08ffdccaf)

**Comment by praveenkuttappan** [comment]
This is handled using sorted order of APIs in APIview for few languages. I think we should add sorting of APIs within API parser for .Net.
