### ISSUE TITLE
[APIView] SwaggerAPIView failed with "Create ApiView failed because of authorization failure"

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#6135]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2763385&view=logs&j=9e7477d6-80c4-54a8-ebef-1e18da128ba0&t=d53a2f62-bad1-573a-caa1-b07403b79c0d&l=294

**Comment by chidozieononiwu** [comment]
> @chidozieononiwu this was fixed in the latest deployment?

Happened again but this is due to an external resource.

**Comment by maririos** [comment]
Is there any work we still need to do or can we close the issue
