### ISSUE TITLE
[Unified pipeline] Pipeline result fails to sync to github PR

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#6143]
ADO pipeline finishes the run but the result isn't synced to github PR.  

This is an example github PR and ado pipeline run.
https://github.com/Azure/azure-rest-api-specs/pull/23895
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2766881&view=results

@konrad-jamrozik @weshaggard 
Above PR was merged. 

I added another PR with same issue: 
https://github.com/Azure/azure-rest-api-specs/pull/23891

Relevant [Teams thread](https://teams.microsoft.com/l/message/19:9efda948665d481086766c0b7572abc3@thread.skype/1683852212746?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1683852212746&teamName=Azure%20SDK&channelName=Service%20API%20Toolset&createdTime=1683852212746).

**Comment by JackTn** [comment]
also as this pr https://github.com/Azure/azure-rest-api-specs/pull/23921#issuecomment-1543322793

**Comment by weshaggard** [comment]
One of the eventhub partitions for processing the status checks stalled and after we restarted the pipeline-bot app it started processing again. So, these statuses are updating again. I've added some more logging to see if we can figure out what happened if this happens again.
