### ISSUE TITLE
Clarify what the default name tag is for readme in the SDK release app

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6148]
@ladonnaq @maririos Highlighted text in following screenshot is not user friendly. Can you please clarify what exactly is meant by this statement? I think we should make it clearer to avoid getting questions about this from users.

![image](https://github.com/Azure/azure-sdk-tools/assets/55455725/cf778d6b-34dd-4d2b-8f38-5bd642b0a236)

**Comment by praveenkuttappan** [comment]
This label became more clearer after adding a path to readme file. It became as follows after I typed a dummy path.

```
Please ensure the default tag in specification/databoxe/data-plane/readme.md is expected.
```

I think we can show this text only when a path is entered instead of showing a confusing partial text in advance.

**Comment by ladonnaq** [comment]
> This label became more clearer after adding a path to readme file. It became as follows after I typed a dummy path.
> 
> ```
> Please ensure the default tag in specification/databoxe/data-plane/readme.md is expected.
> ```
> 
> I think we can show this text only when a path is entered instead of showing a confusing partial text in advance.

I agree, go ahead and change it.  Thanks!

**Comment by maririos** [comment]
> is expected.

What does "is expected" means? @josefree do we have a documentation link we can add here so the user understand what to do?

**Comment by maririos** [comment]
@ladonnaq do you remember what the action item we agreed on the meeting was for this view?

**Comment by maririos** [comment]
This is no longer needed as we have removed this functionality based on design https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0-1&t=1lCBRP1NpVo69ZVV-0
