### ISSUE TITLE
[PR Workflow] Guideline of pushing to public repo in private spec repo is misbehaving

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#6154]
In private spec repo, main branch can't be merged. And when the PR labelled with `Approved-OkToMerge`, a comment will be added to guide the user to publish to public main. But there is no comment added after adding the label in this [PR](https://github.com/Azure/azure-rest-api-specs-pr/pull/12321#issuecomment-1543812616).

And for RPSaaSMaster branch in private repo, it is OK to merge, but [a comment](https://github.com/Azure/azure-rest-api-specs-pr/pull/12500#issuecomment-1541561175) was added for the above case.

**Comment by konrad-jamrozik** [comment]
Possibly the same root-cause as:

- #6166

**Comment by konrad-jamrozik** [comment]
Looks like the labelling workflow needs some updates to adjust.

**Comment by konrad-jamrozik** [comment]
The guidance has been updated:

- https://github.com/Azure/azure-rest-api-specs/blob/a8698bb86e66e2d29ce5e8987b6aaa8fc7f7f04b/.github/comment.yml#L8
- https://aka.ms/azsdk/specreview/merge

It works only on private `main`. The `Approved-OkToMerge` was added to `RPSaaSMaster` by a human, not the bot.
