### ISSUE TITLE
[PR Workflow] Update Open api workflow bot message when team is ARM RPaaS

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6157]
Currently, the message is: 
<img width="765" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/84fc28c2-ed27-485d-9ee1-24a3d0c5940d">

But this doesn't apply to ARM RPaaS products and it is creating confusion in customers.

**Comment by maririos** [comment]
Hmm I wonder if it is related to https://github.com/Azure/azure-sdk-tools/issues/6154 instead of the information not being accurate. 
I would leave thisopen just in case

**Comment by konrad-jamrozik** [comment]
The guidance has been updated:

- https://github.com/Azure/azure-rest-api-specs/blob/a8698bb86e66e2d29ce5e8987b6aaa8fc7f7f04b/.github/comment.yml#L8
- https://aka.ms/azsdk/specreview/merge
