### ISSUE TITLE
[PR Workflow] Remove API specs comparison report generator from initial comment in specs repo

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6159]
Now that APIView is in place, the following comment should either be updated to include APIView or remove the phrase `For specs comparison cross API versions` altogether:

<img width="713" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/219422e9-126a-4947-af22-4ce7503d54d4">

**Comment by maririos** [comment]
Once APIView support comparison across multiple API Versions we can remove this text so it is a clear replacemente

**Comment by konrad-jamrozik** [comment]
Assigned myself as I took care of it here:
- https://github.com/Azure/azure-rest-api-specs/pull/24575
