### ISSUE TITLE
[PR Workflow] Labels `data-plane`, `new-api-version` and `typespec` missing from a draft PR in azure-rest-api-specs-pr

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6173]
https://github.com/Azure/azure-rest-api-specs-pr/pull/12539 is missing several labels that should be added automatically by the PR automation:

- data-plane
- new-api-version
- typespec

Maybe because it is a draft? If this is the reason I think we should reconsider this design.

**Comment by konrad-jamrozik** [comment]
> [Azure/azure-rest-api-specs-pr#12539](https://github.com/Azure/azure-rest-api-specs-pr/pull/12539) is missing several labels that should be added automatically by the PR automation:
> 
> * data-plane
> * new-api-version
> * typespec
> 
> Maybe because it is a draft? If this is the reason I think we should reconsider this design.

@mikekistler I think you were on point, it is because it is a draft. [Source](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=public/rest-api-specs-scripts/src/prSummary.ts&version=GC02e956adcdd563ab5e0f43e60cf1cd259669cb85&line=519&lineEnd=524&lineStartColumn=1&lineEndColumn=4&_a=contents): 

``` typescript
  const isDraft = await isDraftPR(owner, repo, prNumber);
  if (isDraft) {
    console.log(`PR is draft, skip ARM review`);
    console.log("RETURN definition processARMReview")
    return;
  }
```

**Comment by mikekistler** [comment]
I agree that we should skip adding the "ARMReview" label for a PR still in draft, but the other labels should be added.

**Comment by konrad-jamrozik** [comment]
Ah, apologies, this is for data-plane, not resource-manager. I'll have another look.

**Comment by konrad-jamrozik** [comment]
Closing as a year old issue. Let's reopen if it happens again.
