### ISSUE TITLE
Update CI link information

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6174]
It should say `TypeSpec` instead of Swagger:

<img width="261" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/3c03c4de-2d1e-4cad-9138-c7c9692b1bdc">

**Comment by praveenkuttappan** [comment]
Can we just remove the word `swagger` from the text?

**Comment by chidozieononiwu** [comment]
Resolved by https://dev.azure.com/devdiv/DevDiv/_git/openapi-alps/pullrequest/483302
