### ISSUE TITLE
[LintDiff][False positive] GetCollectionOnlyHasValueAndNextLink gets applied to Get operation, but it shouldn't.

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6181]
See this discussion: https://github.com/Azure/azure-rest-api-specs-pr/pull/12351#discussion_r1194607451

**Comment by rkmanda** [comment]
Needs more investigation on why this is flagging https://msazure.visualstudio.com/One/_workitems/edit/22895869

**Comment by tejaswiMinnu** [comment]
Fixed the false positive issue for this rule "GetCollectionOnlyHasValueAndNextLink"

**Comment by tejaswiMinnu** [comment]
> > Fixed the false positive issue for this rule "GetCollectionOnlyHasValueAndNextLink"
> 
> @tejaswiMinnu Can you link to the PR with the fix? Just for future reference.

https://github.com/Azure/azure-openapi-validator/pull/541
