### ISSUE TITLE
[PR Workflow] Establish and enforce policy for merging data-plane REST API PRs to main

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6184]
We've decided that all PRs to the main branch for data-plane APIs that introduce a new api-version should be reviewed / approved by the API Stewardship board before merge.

We should configure the checks in the azure-rest-api-specs repo to enforce this policy. Some parts of this:

- ensure that the "data-plane" label is reliably applied to PRs
- ensure that the "new-api-version" label is reliably applied to PRs
- Block merge for PRs to main with "data-plane" and "new-api-version" labels but without "APIStewardshipBoard-SignedOff" label

Related work:
- https://github.com/Azure/azure-sdk-tools/issues/6374

**Comment by konrad-jamrozik** [comment]
@mikekistler per my chat with @weshaggard we are thinking about adjusting the workflow to make it consistent with the ARM one. 

In case of ARM it works like that:

- If a PR touches ARM specs, it gets `resource-manager` label.
- If a PR gets `resource-manager` label, it gets `ARMReview` label.
- If a PR has `ARMReview` label, it must get `ARMSignedOff` label to be merged.

So for data plane we are thinking:
- If a PR touches ARM specs, it gets `data-plane` label. 
- If a PR gets `data-plane` label, it gets `APIStewardshipBoardReview` label.
  -  **This would be new logic I will add**
- If a PR has `APIStewardshipBoardReview` label, it must get `APIStewardshipBoardSignedOff` label to be merged.
  - **This would be a new rule I am adding as part of #6285**

Now, some important points to consider:

- Currently there is inconsistency in labels format. `ARMReview` vs `APIStewardshipBoard-ReviewRequested` and `ARMSignedOff` vs `APIStewardshipBoard-SignedOff`. I propose to change the data-plane labels used going forward to:  
    - `APIStewardshipBoard-ReviewRequested` --> `APIStewardshipBoardReview`  
    - `APIStewardshipBoard-SignedOff` --> `APIStewardshipBoardSignedOff`

- Currently we assume that **any PR with resource-manager needs to get a review**, hence we add the `ARMReview` label to them. Basically I am proposing an equivalent approach for data-plane.

- You mentioned `new-api-version` should require `APIStewardshipBoard-SignedOff`. But this rule will become obsolete: a PR adding new API version to a data-plane API will have `data-plane` label, so it will have `APIStewardshipBoardReview` label, so it will require `APIStewardshipBoardSignedOff`. Hence this rule appears unnecessary to me.

Let me know what you think and if my reasoning is correct!

**Comment by mikekistler** [comment]
On the data-plane side, we do not review every PR as is done in ARM. We only review "new api-versions", so

> If a PR gets `data-plane` label _AND a `new-api-version` label_, it gets APIStewardshipBoardReview label.

- Label format: I don't feel strongly about this so feel free to change it as you propose.

- Same approach for data-plane? Okay but with the caveat above.

- Nope. We only review new-api-versions. Do not add `APIStewardshipBoardReview` if there is no `new-api-version` label.

**Comment by konrad-jamrozik** [comment]
This is implemented and running in production. Moved follow-up work to:
- https://github.com/Azure/azure-sdk-tools/issues/6612
