### ISSUE TITLE
[LintDiff][False positive] TrackedResourcePatchOperation

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6186]
See this discussion:
https://github.com/Azure/azure-rest-api-specs-pr/pull/12321#issuecomment-1543695885

Example build log:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2776803&view=logs&j=0574a2a6-2d0a-5ec6-40e4-4c6e2f70bea2&t=80c3e782-49f0-5d1c-70dd-cbee57bdd0c7&l=188

**Comment by konrad-jamrozik** [comment]
@bdefoy could you verify this is indeed a false positive? If so, should we disable this rule from running?

**Comment by rkmanda** [comment]
There are 2 LintDiff validation errors, one could be ignored based on this comment: https://github.com/Azure/azure-rest-api-specs-pr/pull/12321#discussion_r1181122931 and the other is saying that PrivateEndpointConnection is a TrackedResource and must have a Patch operation, but PrivateEndpointConnection is not a TrackedResource but a ProxyResource.


The first one is for final-state-via which has now been disabled.
The second one is an anomaly for PrivateEndpointConnection where the rule [TrackedResourcePatchOperation] is flagging an error. The evaluation of the rule is right but PrivateEndpointConnection is an exception, so the rule needs to account for it.
https://github.com/Azure/azure-rest-api-specs-pr/pull/12321/checks?check_run_id=13504498636

[Task 22894745](https://msazure.visualstudio.com/One/_workitems/edit/22894745): Anomaly in TrackedResourcePatchOperation

**Comment by rkmanda** [comment]
On further exploration of the issue with PrivateEndpointConnection , it was found that the issue was with the way the author defined the model. The model MUST not have a location property for proxy resources. The author was asked to remove the property as a part of the PR
