### ISSUE TITLE
TypeSpec APIView failed because typespec-apiview package not installed

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6207]
The TypeSpec APIView PR pipeline job for [PR 22310](https://github.com/Azure/azure-rest-api-specs/pull/22310) failed because the typespec-apiview package was not installed.
```
error import-not-found: Couldn't resolve import "@azure-tools/typespec-apiview"
```

This PR branch was created before the updates to package.json in the root of the repo added all the TypeSpec packages, so the team used their own package.json.

One possible solution is to install the typespec-apiview package in the PR pipeline job before attempting to use it.

**Comment by weshaggard** [comment]
In both of these cases the projects had a local project.json file which didn't include typespec-apiview emitter. The fix for these is to remove those local project.json files so the versions can be picked up correctly from the root.
