### ISSUE TITLE
Docs not generating in API readiness app for PR 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6226]
The docs are not being generated.  The screen continues to show "Documents generating" but it never resolves.  This may be associated with something wrong in the PR, not sure.  If there is an error that needs to be addressed by user or a failure in our tooling, we should let the user know what is happening.  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/a0855815-e452-4c6f-9ee6-d4cac42823f4)

**Comment by maririos** [comment]
This looks to be a tooling issue not related to the Release Planner App. I can see the pipeline finished, but the status was never updated. I created issue https://github.com/Azure/azure-sdk-tools/issues/6229 for eng to follow up.

@ladonnaq is this blocking the release plan?
