### ISSUE TITLE
Breaking change SDK blocking API Readiness 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6227]
The breaking change screen earlier in the user flow was successful (screenshot 1 below) but on the final API readiness signoff screen it is blocked (screenshot 2 below).  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/7f32c7a7-9c8f-4f54-9d01-9a138ee551a8)

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/6a8952f3-a668-415a-95f4-21f0e5d89e78)

**Comment by maririos** [comment]
These seem like 2 different checks:
- Breaking changes in the API Spec (first screenshot you are showing)
- Breaking Chande for SDKs

Also, this is a private preview so we shouldn't need to check the generated SDKs, right @ladonnaq ?

@JonathanCrd could you check: 
- If the views are in reality targetting different pipelines
- Which is the pipeline that is getting called for the `Breaking Change Validation on auto-generated SDKs`?
- Fix: make sure this step is not present for Private Preview

**Comment by maririos** [comment]
Changed to @praveenkuttappan because he is currently looking at these views and behaviors
