### ISSUE TITLE
Breaking changes failed, PR is merged in public repo with approved breaking change label

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6228]
Breaking changes failed and request suppression is available. However, this is a merged PR in the public repo for a service team so not sure if it is safe for me to choose "request suppression".  Also, the label for approved breaking changes is on the PR.  So not sure what request suppression will do to the PR.   

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/61ef3ed6-0922-4aeb-baf4-8037a8e14f89)

**Comment by maririos** [comment]
Request supresion has been removed. Also, if the PR is merged, we allow completion of the API Readiness step
