### ISSUE TITLE
[ApiDocPreview] job never updating end result (stuck in "in progress")

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6229]
Looks like the `ApiDocPreview` job is not reporting the end status to the Unified Pipeline as the message is not getting updated even though the pipeline finished.
Repro:
- PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/12105
- ApiDocPreview: In progress:

![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/4dacd0c7-9652-4398-a4d1-db670f369be7)

![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/f9e8fa17-2cef-4fcf-ae7f-6e21d7edce27)

- Pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2712912&view=logs&j=f06b4322-f7bf-57ee-ecc5-6d0feac67556
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/fb4b8a4a-1928-4873-be2b-08494d0d106e)

**Comment by ladonnaq** [comment]
I also ran into the issue with data plane - 

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/6752e500-8c62-4fa5-ba59-83fe8ae214ec)

**Comment by konrad-jamrozik** [comment]
@weshaggard this has similar symptoms to stuff you were debugging previously.

**Comment by weshaggard** [comment]
@danieljurek looks like the this is expecting an external process to update the status check here but something went off track. Have you been able to figure out the expected workflow for these?

**Comment by maririos** [comment]
We can close it. also it is outside our scope
