### ISSUE TITLE
Breaking change did all pass in the API readiness app, API readiness signoff shows passed and ready for signoff

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6233]
I tested 2 scenarios with slightly different results. 

- Serverless Validation Screen shows that everything is green. 

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/ca864eda-83e9-4965-bd25-01c6d5361afc)

- Serverless - Breaking Change fails with option to request suppression. 

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/0846b6d0-6d22-4eca-a432-f6faa5d2eebc)

- Serverless API readiness signoff shows breaking changes are completed, which is confusing because there was error shown on the breaking change screen.  
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/2b8ce3bc-00cb-4b6f-adce-740b66a323b9)

- Discovery and Assessment of Spring Boot apps to Azure Spring Apps - Breaking change fails but no option to request suppression.  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/819d1d07-0f93-44ef-876a-b76340046b08)

Discovery and Assessment of Spring Boot apps to Azure Spring Apps shows breaking changes is completed, which is confusing becaues there was error shown on the breanking change review screen. 
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/f31a9f89-5b26-4f86-a0d9-38d02d09dd62)

**Comment by praveenkuttappan** [comment]
Modified the logic to show breaking change status based on GitHub checkrun status instead of labels.
