### ISSUE TITLE
API readiness app associated PR link is disabled 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6234]
I need to update the PR for Health Insights as the initial PR has been closed.  The new PR is https://github.com/Azure/azure-rest-api-specs/pull/22990.  The API Readiness app is showing all of the buttons as disabled. I cannot update associated a new PR. 

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/1963a3bc-8c2f-497a-a0b4-3ef0505d0123)

**Comment by maririos** [comment]
@ladonnaq Fixed! you can do it now:

![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/626da5a2-fdcf-4ba7-ac0c-41281f237c54)
