### ISSUE TITLE
Apply SubscriptionConfiguration/Location pattern from .NET to other live test templates

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#628]
Live test templates should use the pattern from .NET: 

* Template parameters for `Location` and `SubscriptionConfiguration` with default values
* Variable set at job level for `$(SubscriptionConfiguration)` as a default
* Use `$(SubscriptionConfiguration)` and `$(Location)` in `deploy-test-resources.yml` template invocations

This gives you the ability to set the default in one place in your `tests.yml` file or set per-matrix-entry in your `Matrix` parameter variable that override that default.

**Comment by kurtzeborn** [comment]
This is done.
