### ISSUE TITLE
[PR Workflow] Automate blocking PRs from being merged

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6285]
Per email from @rkmanda, the following needs to be automated (for details and additional criteria, see email thread `RE: About Spec PR review requirements` from 6/2/2023, as well as `RE: Brainstorm ways to automate the responsibilities of the PR assignee`):

Are all checks other than the ARM specific ones already codified into the required checks today? Heres the list of the merge criteria we had documented earlier

1.	Common [between control and data plane]
a.	All required checks in the pipeline passed
b.	If BreakingChangesRequired label exists check existence of the BreakingChangesApproved label.
c.	If Individual language breaking change label exists, check existence of the appropriate corresponding approval labels.
2.	Control plane
a.	Existence of ARMSignedOff 
b.	Existence of ArcSignedOff if its applicable
  
4.	Suppression review 
a.	Not being performed by anyone today
b.	If SuppressionReviewRequired label exists, check existence of the Approved-Suppression label

5.	PR assignee confirms with the author when it is ok to merge
a.	In remote scenarios - Force merge when there are pipeline issues
b.	NOTE: DoNotMerge label exists but sometimes authors forget.

### Possible approaches

One way of doing it is to do all these checks in the unified pipeline `Summary` task and make it fail if they fail. `Summary` task passing would mean PR is ready to be merged.

Alternatively, instead of failing the `Summary` task, we could introduce a new task, named like `VerifyLabelsAllowMerging`, that must pass. This way we will avoid bolting additional responsibilities on top of the `Summary` task.

### Update 6/14/2023: suppressions

The `SuppressionReviewRequired` label should be blocking (unless appropriate "suppression approved" label is present (if applicable)). Per:
- https://github.com/Azure/azure-rest-api-specs/pull/24227#issuecomment-1570639108

### Update 7/5/2023: ShiftLeft approval

`Approved-OKToMerge` label needs to be present for ShiftLeft scenarios.

For full details, see [this Teams discussion](https://teams.microsoft.com/l/message/19:9efda948665d481086766c0b7572abc3@thread.skype/1688398467780?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1687975507812&teamName=Azure%20SDK&channelName=Service%20API%20Toolset&createdTime=1688398467780).

### Update 7/18/2023: rules for data-plane

Per [this comment](https://github.com/Azure/azure-sdk-tools/issues/6285):

- https://github.com/Azure/azure-sdk-tools/issues/6184#issue-1712414883

### Pull Requests

- Deployed 7/6/2023: [Pull Request 481115](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/481115): Refactor + improve logs in `PipelineEventListener.ts`; remove dead code from `pipelineChecks.ts`.
- [Pull Request 481115](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/481115): Refactor + improve logs in `PipelineEventListener.ts`; remove dead code from `pipelineChecks.ts`.
- [Pull Request 482899](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/482899): Improve diagnostic logs around sending events to EventHubs + rename refactor
- [Pull Request 483276](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/483276): Add experimental stub support for check AllMergingRequirementsFulfilled + major refactoring and logging update of renderUnifiedPipelineChecks and related code
- [Pull Request 484831](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/484831): Apply few bugfixes to the experimental check
- [Pull Request 484966](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/484966): AllMergingRequirementsMet experimental check now checks for appropriate required checks and labels states
- [Pull Request 485263](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/485263): De-anonymize "All merging requirements met" check; fix bug in evaluating missing required labels; improve the check description
- [Pull Request 485529](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/485529): Improve "all merging requirements met" check description with help guidance
- [Pull Request 485873](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/485873): Improve data-plane rules for "all merging requirements met" check

**Comment by konrad-jamrozik** [comment]
@weshaggard I think this task boils down to the following subtasks:

1. Review which of the existing CI checks should actually be required and set them as appropriate. Setting the status checks on GitHub side is explained in step 7 [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule#creating-a-branch-protection-rule). The ADO doc about integrating with GH status checks refers to the same doc, as can be seen in ADO docs on that [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&preserve-view=true&tabs=yaml#protected-branches).
    - I think the ADO pipeline tasks themselves have simple return code of success/failure, as explained [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/process/tasks?view=azure-devops&tabs=yaml#task-control-options).
    - Full lists of checks running is defined in [openapi-alps .azure-pipelines.yml]. There might be some complexity involved in post-processing them by our bots, but I grokked the code I think I know where is what.
    - Specifically, the [pipeline-bot PipelineEventListener](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=/private/openapi-kebab/src/bots/pipeline/pipelineBot.ts&version=GCbe2519051785e2781ed1eae2ad9ab04ceeb98444&line=102&lineEnd=110&lineStartColumn=1&lineEndColumn=30&lineStyle=plain&_a=contents) may be doing some relevant post-processing, but again, I think I can work with that.
2. Add another task to the [openapi-alps .azure-pipelines.yml], to run at the end, like `VerifyLabelsAllowMerging`, to capture all the rules for labels on the PR. If any of them is violated, the check will fail.

[openapi-alps .azure-pipelines.yml]: https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps?path=%2Fprivate%2Fazure-rest-api-specs-pipeline%2Fazure-pipelines.yml&version=GBmain&_a=contents

**Comment by konrad-jamrozik** [comment]
@weshaggard re this:

> For https://github.com/Azure/azure-sdk-tools/pull/1 once the checks are ready I can update the required checks in the branch protection. I don't want to make them required until we are confident, they work as expected and can be trusted.

I think we could captured what people are already doing. For example, I know that checks like breaking change verification, production LintDiff or Avocado in practice must pass, so they should be required. But some other checks appear to be bypassed most of the time. So I would say we could start by making quick assessment, consulting with our partners, and deciding based on that. 

I could compile a list of all checks and message our partners what is our plan, so they can review.

Re this:

> For your VerifyLablesAllowMerging that one likely cannot be a task in the pipeline as we need to update it based on our other bots as well. I suspect this should be a github status check instead of the standard Devops check suite/run so that we can mutate it from all our bots and pipelines as the process proceeds.

I realized that we probably want for this to be the `Summary` task after all. This is because the `Summary` task processes the labels, including making any label corrections if labels have been manually tampered with. Hence if we would have a separate GitHub check of kind `status`, it would, in practice, have to do very similar work to the `Summary` task. Otherwise someone could tamper with the labels after `Summary` task ran, and fulfill the labelling requirements.

**Comment by konrad-jamrozik** [comment]
I had a chat with @weshaggard. Here are our conclusions.

- We will ensure the PR is ready to be merged by adding a GitHub status check of type status, like `AllReviewsComplete` or maybe `AllMergingRequirementsFulfilled`. 
- That status check will be set by pipeline-bot by the [pullRequestLabeled](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineBot.ts&version=GCbe2519051785e2781ed1eae2ad9ab04ceeb98444&line=143&lineStartColumn=16&lineEndColumn=34&_a=contents) event handler, which triggers [when the PR is labelled or unlabelled](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineBot.ts&version=GCbe2519051785e2781ed1eae2ad9ab04ceeb98444&line=86&lineEnd=87&lineStartColumn=1&lineEndColumn=56&_a=contents). It will principally check for two things:
    1. The `Summary` task check needs to be green, denoting the CI check suite ran successfully.
    2. All the labels are in consistent state. This will be achieved by reading all the labels on the PR using Octokit (`Summary` task is currently doing this too) and doing label state validation, not unlike the `Summary` task is doing.

Specifically, the pipeline-bot is processing the labelling events via [PipelineEventListener.processEvent](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/PipelineEventListener.ts&version=GC0c217f8798717d8765122e85d788f086f528c038&line=171&lineStartColumn=16&lineEndColumn=28&_a=contents). This calls [renderUnifiedPipelineChecks](renderUnifiedPipelineChecks), which ends up applying the check update via a call to [context.appClient.checks.update](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/PipelineEventListener.ts&version=GC0c217f8798717d8765122e85d788f086f528c038&line=662&lineStartColumn=17&lineEndColumn=48&_a=contents).

I will work on this iteratively. The plan for first PR is to add a capability to the pipeline-bot to do the following on labelled or unlabelled event:

- Read the Summary task check status.
- Read all the labels from GitHub API (Octokit) and apply some most basic label validation logic, to be improved in future PR.
- Update the `AllMergingRequirementsFulfilled` check based on the above. That check needs to be added.

In later iterations on this work we might consider some way of preserving the state that was used to compute the labels, to protect against manual tampering with them. For example, currently the `Summary` task computes the label denoting breaking changes presence based on the output of the "Breaking Change" task, which runs in the same pipeline. This information is not readily available during "on labeled" event of pipeline-bot. It would have to be pulled e.g. from given ADO build run for given PR, assuming that build would persist it e.g. as an artifact drop.

**Comment by konrad-jamrozik** [comment]
## A note on suppressing checks

CI checks can be suppressed by adding appropriate label. For example, if the [`Swagger BreakingChange`](https://github.com/test-repo-billy/azure-rest-api-specs/pull/2937/checks?check_run_id=14511108714) check is failing, adding the `Approved-BreakingChange` will immediately change its state from `failed` to `neutral`. My cursory investigation shows that the code emitting that state change lives in pipeline-bot, in `renderUnifiedPipelineChecks`, [here](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps/?path=/private/test-unified-pipeline/node_modules/openapi-kebab/src/bots/pipeline/PipelineEventListener.ts&version=GBr_processBreakingChangeLabels&_a=contents&line=624&lineEnd=642&lineStartColumn=1&lineEndColumn=18).

The production environment config file that defines which label can suppress which check appears to be [`config/production/Azure/azure-rest-api-specs.yml`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/azure-rest-api-specs-pipeline/config/production/Azure/azure-rest-api-specs.yml&version=GC917e278536f9e362757c727b2a104838346367e4&line=31&lineEnd=39&lineStartColumn=1&lineEndColumn=47&_a=contents).

**Comment by maririos** [comment]
FYI @praveenkuttappan for Release Planner

**Comment by konrad-jamrozik** [comment]
Related PR:

- https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/481115

**Comment by konrad-jamrozik** [comment]
@mikekistler I am about to deploy the checks described in this work item. What checks should I add for data plane reviews?

I see labels like:

- [APIStewardshipBoard-SignedOff](https://github.com/Azure/azure-rest-api-specs/issues?q=is%3Apr+is%3Aclosed+label%3AAPIStewardshipBoard-SignedOff)
- [APIStewardshipBoard-ReviewRequested](https://github.com/Azure/azure-rest-api-specs/issues?q=is%3Apr+is%3Aclosed+label%3AAPIStewardshipBoard-ReviewRequested)
- [data-plane](https://github.com/Azure/azure-rest-api-specs/issues?q=is%3Apr+is%3Aclosed+label%3Adata-plane)

What labelling rules I should add? Any required checks that should pass specifically for data-plane? Anything else?

**Comment by mikekistler** [comment]
@konrad-jamrozik I think the rules we want are described in this issue:

https://github.com/Azure/azure-sdk-tools/issues/6184

**Comment by konrad-jamrozik** [comment]
@rkmanda @raych1 in the private repo, I see labels like [these](https://github.com/Azure/azure-rest-api-specs-pr/pull/13602#event-9805280888):

![image](https://github.com/Azure/azure-sdk-tools/assets/4429827/9dbe752f-b190-4609-a27b-b704131509fb)

But they do not align with the public repo. I.e. the private repo has `Approved-BreakingChange-Go` while public repo has `Approved-SdkBreakingChange-Go` (note the extra `Sdk` after `Approved-`). The [config file for private repo](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/azure-rest-api-specs-pipeline/config/production/Azure/azure-rest-api-specs-pr.yml&version=GC5a09313dfcf5ff9cde0a80bebc372cb0f22315f7&line=21&lineEnd=24&lineStartColumn=1&lineEndColumn=62&_a=contents) says the labels should always be as in public repo. In fact, [I cannot find `Approved-BreakingChange-Go` in the source code at all](https://devdiv.visualstudio.com/DevDiv/_search?text=Approved-BreakingChange-Go&type=code&lp=code-Project&filters=ProjectFilters%7BDevDiv%7DRepositoryFilters%7Bopenapi-alps%7D&pageSize=25). Can you let me know how to interpret this?

**Comment by tadelesh** [comment]
Seems mislabeled. @raych1 may know more about the background.

**Comment by konrad-jamrozik** [comment]
## Progress update 7/20/2023

The experimental check is deployed and has most of the rules codified in it.

Major big remaining work left to do:

- Instead of hardcoding the list of required checks (`requiredChecksNames`), read the list of required checks on the PR from GitHub API. Note that we should warn on mismatch between the these checks and the list of tasks defined in the config file, e.g. [here](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps?path=/private/azure-rest-api-specs-pipeline/config/production/Azure/azure-rest-api-specs.yml&version=GBmain&line=31&lineEnd=32&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents). Notably, we should catch all cases where there is a required check without a corresponding task.
- Add proper support for data plane "review required" label - currently there is a todo (`TODO:`) in the code for that.
- Add more diagnostic logs - currently there is a todo (`kja`) in the code for that.

**Comment by benbp** [comment]
@konrad-jamrozik the github checks api is a bit of a beast with lots of little edge cases. Let me know when you get to the "list required checks via api" step.

**Comment by konrad-jamrozik** [comment]
Closing as principally done. It is deployed to production and running. Primary follow-up work moved to:
- https://github.com/Azure/azure-sdk-tools/issues/6613
