### ISSUE TITLE
Duplicate ADO work items for Azure Monitor SCOM Managed Instance 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6288]
I do not believe any engineering work is required.  We have 2 active work items for Azure Monitor SCOM Managed Instance 
and I want to delete the one but not sure which is associated with the dataverse for the Release Planner apps. 

Please confirm which work item is in dataverse and I will make sure the info is copied into the correct work item and the other work item is deleted.   

- https://dev.azure.com/azure-sdk/Release/_workitems/edit/12972/?triage=true
- https://dev.azure.com/azure-sdk/Release/_workitems/edit/9214/?triage=true

**Comment by maririos** [comment]
> https://dev.azure.com/azure-sdk/Release/_workitems/edit/12972/?triage=true

@ladonnaq This is the issue the Release Planner knows about :)

**Comment by ladonnaq** [comment]
> > https://dev.azure.com/azure-sdk/Release/_workitems/edit/12972/?triage=true
> 
> @ladonnaq This is the issue the Release Planner knows about :)

Thanks!  I closed the other one and added link for duplicate and duplicate tag to the work item.
