### ISSUE TITLE
Migrate permissions Docs to Engineering Hub

### ISSUE THREAD

**Issue by kurtzeborn** [Azure/azure-sdk-tools#6290]
As a guinea pig, we want to migrate permissions docs from the wiki to the engineering hub.  [repo](https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms)

Notes:
- Don't delete the pages for the old docs.  Delete the content and provide a link to the new location.
- Instead of maintaining/updating a list of teams, provide a link with a query to the teams on both the [OpenSource Portal](https://repos.opensource.microsoft.com/teams?q=azure-sdk-write-) and [GitHub](https://github.com/orgs/Azure/teams?query=azure-sdk-write-)

**Comment by kurtzeborn** [comment]
PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/746

**Comment by maririos** [comment]
As part of this work, could you also:
- Update the [aka.ms/azsdk/permission](https://aka.ms/azsdk/permission) to point to the new page
- Update the existing wiki informing the user that some of the information was moved to (new link)
