### ISSUE TITLE
Swagger APIView - new property in schema creates diff for all remaining properties 

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6296]
In [PR 24291](https://github.com/Azure/azure-rest-api-specs/pull/24291), a new property `id` was added to the `Pool` schema, but all other properties are unchanged:

<img width="1010" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/85643503/7fb879e7-94b1-46d3-9c04-fac26e413c85">

But in [APIView](https://apiview.dev/Assemblies/Review/d1d36f62705344809ae4bf40280d7f16?diffRevisionId=e131ff0ea26843639a4db31d63421582&diffOnly=False&revisionId=27ff3988a9bc4b9aae1b70c81aa67a9c&doc=False), all the properties after `id` are highlighted as a diff from the base release.

<img width="863" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/85643503/696f9b6c-f0e4-4977-a4a3-4df12f414a63">

**Comment by heaths** [comment]
May be a dup of #6132. We should probably sort properties, but make sure to keep my breadth-first change in there. The old depth-first was very misleading.
