### ISSUE TITLE
[azure-resource-manager-schemas] in Swagger Generation Artifacts is stuck "in progress"

### ISSUE THREAD

**Issue by JackTn** [Azure/azure-sdk-tools#6301]
Description: pipeline `azure-resource-manager-schemas` always run in progress https://github.com/Azure/azure-rest-api-specs/pull/24274#issuecomment-1574175163 
rerun get the same issue

**Comment by konrad-jamrozik** [comment]
Here is the build:
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2824019&view=results

I just re-triggered it, let's see if it helps:
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2827930&view=results

**Comment by JackTn** [comment]
Thanks, I can see the erros `Error: PR 24274 is not merged to main branch.`
