### ISSUE TITLE
[Breaking Change] The Breaking Change Specs PR check should not treat previews > 1yr old as GA

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6322]
I believe that the Breaking Change tools treat a prior preview version as GA if the date portion of the api-version is > 1yr ago, and this causes the PR to be flagged for breaking change review when it might not otherwise be.  But the api-version dates are not reliable indicators of when a service entered public preview, so we want to discontinue this logic.

**Comment by konrad-jamrozik** [comment]
Per chat with Mike, this might be a simple fix. Need to remove the relevant check.

**Comment by konrad-jamrozik** [comment]
[Relevant discussion](https://teams.microsoft.com/l/message/19:9efda948665d481086766c0b7572abc3@thread.skype/1690316070343?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689398801981&teamName=Azure%20SDK&channelName=Service%20API%20Toolset&createdTime=1690316070343) on Teams.

**Comment by konrad-jamrozik** [comment]
PR:
- [Pull Request 487317](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/487317): Do not consider preview API comparisons of more than 1 year errors.
