### ISSUE TITLE
**BLOCKING BUG** - TypeSpec PRs - Getpipelineresults.Run failed 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6326]
I am seeing this error on the TypeSpec PRs used in API readiness app.   This is for Azure Code Signing.  The PR is still open and the API Stewardship Board has signed off on the preview TypeSpec. 

Here is the error - "
Getpipelineresults.Run failed: { "error": { "code": 502, "source": "unitedstates-002.azure-apim.net", "clientRequestId": "a37b9de9-1de9-4d62-b267-085e70446354", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not receive a response from an upstream server. Request tracking id '08585150229849932523754149907CU20'." } } } }" 

Here is the PR - https://github.com/Azure/azure-rest-api-specs/pull/22310.   

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/a54583a8-7dbc-46fb-b197-386af6e92afa)

**Comment by praveenkuttappan** [comment]
Release planner app for data plane api readiness will no longer require GetPipelineRunDetails cloud flow to get details and this fix will be part of next release planner release.
