### ISSUE TITLE
***BLOCKING BUG*** Error when selecting push to public 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6328]
Error when selecting push to public.  The label "Approved-OkToMerge" is in the PR but the API readiness app does not seem to recognize it.  This issue was found by the service team engineer who is testing release planner in PROD.  I recreate the error in PPE so I would not accidently do anything to the service team's real data.  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/fed68aa9-a458-43bb-b139-c2b90bcfc72d)

**Comment by maririos** [comment]
> I recreate the error in PPE so I would not accidently do anything to the service team's real data.

In some cases this is true, but in this particular case, I don't think it is true. 
@praveenkuttappan can you confirm?

**Comment by praveenkuttappan** [comment]
Publish button is only visible if PR is from azure-rest-api-specs-pr only. So this error message is incorrect. I have looked at the code and app shows this static error message when it actually failed in openapihub side to publish a PR and actual error message is not available. I will check if we can get more accurate message about failure and list.

**Comment by maririos** [comment]
Because this is an OpenAPI Hub intermitent failure, the Release Planner is just surfacing that error.
the fix here, like PRaveen said is to improve error messages that come from OpenAPI Hub

**Comment by praveenkuttappan** [comment]
Updated to show actual error message from OpenAPI Hub in case of failure.
