### ISSUE TITLE
TypeSpecValidation doesn't filter on the specs within sub folders

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#6339]
This is the PR with typespec changes only within `cognitiveservices/anomalydetector` folder, but validation reports the errors of another peer folder `cognitiveservices/OpenAI.Inference`.
See this run result https://github.com/Azure/azure-rest-api-specs/pull/23904/checks?check_run_id=14243246263 for details.
```html

❌ MissingExamplesDirectory | "details":"The 'examples' directory is missing in the typespec folder specification/cognitiveservices/OpenAI.Inference,please ensure the 'examples' is added in the PR."
-- | --
❌ SwaggerNotExistInPRBranch | "details":"The generated swagger file 2022-12-01/openapi.json from typespec specification/cognitiveservices/OpenAI.Inference is not on the branch."
❌ SwaggerNotExistInPRBranch | "details":"The generated swagger file 2023-03-15-preview/openapi.json from typespec specification/cognitiveservices/OpenAI.Inference is not on the branch."

```

**Comment by raych1** [comment]
CC: @weshaggard @mikekistler

**Comment by weshaggard** [comment]
@raych1 we decided in order to not break things like shared references we are scoping the validation to a specification folder so cognitiveservices in this case and all the specs should continue to remain functioning so this shouldn't be an issue.

cc @mikeharder

**Comment by ckairen** [comment]
closing because new tsv resolves the issue
