### ISSUE TITLE
Support the changelog generation with RLC SDK for js-sdk-release-tools

### ISSUE THREAD

**Issue by MaryGao** [Azure/azure-sdk-tools#6340]
https://github.com/Azure/azure-rest-api-specs/pull/23904#issuecomment-1542097109

cmderr	[automation_generate.sh] [ERROR] Generate changelog failed: ENOENT: no such file or directory, open '/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/anomalydetector/ai-anomaly-detector-rest/changelog-temp/package/CHANGELOG.md'

**Comment by MaryGao** [comment]
I will look at this in this sprint.

**Comment by raych1** [comment]
This work has been done.
