### ISSUE TITLE
openapi-pipeline-app / SDK azure-powershell check failing since April 2023

### ISSUE THREAD

**Issue by JackTn** [Azure/azure-sdk-tools#6351]
Sample PRs with check failure:
 
* https://github.com/Azure/azure-rest-api-specs/pull/24399/checks?check_run_id=14265695115
 * https://github.com/Azure/azure-rest-api-specs/pull/24426/checks?check_run_id=14240365442
 
 Error logs show below details:
 
 error Fatal error: SSL error: syscall failure: Broken pipe error The following packages are still pending: error Az.app.DefaultTag

Issue From https://github.com/Azure/azure-rest-api-specs/issues/24445

@jijohn14

**Comment by raych1** [comment]
This issue seems to be fixed.
