### ISSUE TITLE
[Python APIView] wire up PR APIViews to provide --source-url

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#6361]
apistubgen has had support for `--source-url` for about a year, which will display the provided URL in the preamble of the APIView. The goal here is to link back to the PR that generated them.

The request here is for EngSys to pass this parameter on PR-based APIViews.

cc/ @lmazuel @johanste

**Comment by tjprescott** [comment]
@maririos that's right.

**Comment by chidozieononiwu** [comment]
This is already a feature present in APIView
<img width="808" alt="Associated Pull Requests" src="https://github.com/Azure/azure-sdk-tools/assets/31145988/263b638d-bb94-455f-97c3-e879cafc2cb7">
