### ISSUE TITLE
CadlApiView Error

### ISSUE THREAD

**Issue by JackTn** [Azure/azure-sdk-tools#6372]
hi~ 
  In this PR https://github.com/Azure/azure-rest-api-specs-pr/pull/13145#issuecomment-1594200188 the CadlAPIView is failed to generate cadl APIView. I saw the log is `error import-not-found` but in message , it shows `Check the detailed log and update cadl version to latest`

Log Link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2852252&view=logs&j=299bb30c-c67a-54fe-f056-8e2399aa462d&t=5523928c-bed7-5d50-c37b-68ad6cb0c720&l=60

**Comment by maririos** [comment]
Usually if the CADL validation fails, then the CadlAPIView fails too. I will suggest making sure the validation works and if there is still no API View created then ping us again

**Comment by JackTn** [comment]
> Usually if the CADL validation fails, then the CadlAPIView fails too. I will suggest making sure the validation works and if there is still no API View created then ping us again

Follow by https://github.com/Azure/azure-sdk-tools/issues/6359

**Comment by JackTn** [comment]
https://github.com/Azure/azure-sdk-tools/issues/6377
