### ISSUE TITLE
Save button on aka.ms/trytypespec/azure does nothing in Edge Dev

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#6393]
Clicking the save button in https://aka.ms/trytypespec/azure in Edge Dev 116.0.1923.0 (and for many versions before) does nothing. The address doesn't change, and there's no visual cue of any kind. Seems on the old site it works, since @johanste sent me a URL to saved state and told me how he did it.

**Comment by johanste** [comment]
Dup of https://github.com/microsoft/typespec/issues/1265
