### ISSUE TITLE
[Breaking Change][PR Workflow] Breaking Changes should not flag breaks from prior preview as errors

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6396]
New API versions, either preview or GA,  may have breaking changes from prior previews - this is allowed by the Azure Breaking Change policy. But the current Breaking Changes PR check in the azure-rest-api-specs repo flags these as errors and triggers a breaking change review. This should be changed to flag these only as warnings and bypass breaking change review.

An example: https://github.com/Azure/azure-rest-api-specs/pull/24494

This issue belongs to a set of related (and possibly at least partially duplicate) issues:

- https://github.com/Azure/azure-sdk-tools/issues/4850
- https://github.com/Azure/azure-sdk-tools/issues/5024
- https://github.com/Azure/azure-sdk-tools/issues/5838
- https://github.com/Azure/azure-sdk-tools/issues/6396
- https://github.com/Azure/azure-sdk-tools/issues/6567
- https://github.com/Azure/azure-sdk-tools/issues/6900

**Comment by konrad-jamrozik** [comment]
Recent case from Mike:

> Here is a recent PR with no BreakingChange / Versioning label but the Automated Merging Requirements check is blocking merge due to a failing Swagger Breaking Changes check:
https://github.com/Azure/azure-rest-api-specs-pr/pull/16902

**Comment by konrad-jamrozik** [comment]
PR with a fix:

- [Pull Request 526579](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/526579): Do not fail breaking change checks if only OAD failures are related to previews
