### ISSUE TITLE
Redesign Data Plane Sign off management plane SDK release readiness screen

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6417]
This issue is to track requirements for the redesign of the Data Plane Sign off management plane SDK release readiness screen. 
**Current UI design **
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/3d3ebaf0-23b7-4b59-86e8-33c9be4cf468)

```[tasklist]
### Changes we discussed to simplify this screen in the current UI design
- [ ] Remove information in checkbox 1.  
- [ ] Keep confirmation of SDK release date and languages.  Perhaps clean this up because the red is difficult to read.  A user may get  to this screen and decide they are going to need more time and need to change the release date.  We should provide information or offer an option to change the date.  
- [ ] Clean up the table so that all of the link are under the link column and only status is shown.  Here are is powerpoint with the table of requirements for new beta and new stable for data plane - https://microsoft-my.sharepoint.com/:p:/p/ladonnaquinn/EWMO8xdq_uhNrfZhK0z5N78BlVfrVUqZQIyD0NHjQnYr8Q?e=FZDM77.  
```

**Comment by maririos** [comment]
@ladonnaq clarifying questions:
- Is this issue for data plane sign off?
- For the testing and samples, where do we ask the user for the folder path? is asking for the path enough? 
- Same question for docs. what is the link for? From what I know, when a DPG library is released, the docs get generated https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/602/Package-Onboarding-step-by-step

**Comment by maririos** [comment]
Changes made based on https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0-1&t=3DS7wrOEmrnoyo9G-0
