### ISSUE TITLE
Data Plane SDK Release App namespace review/approval, initial beta SDKs

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6418]
The data plane SDK release app is missing step for namespace review/approval.  

```[tasklist]
### Tasks
- [x] Teams releasing initial beta client libraries/SDKs are asked to schedule an Introduction meeting with the Azure SDK Arch Board.  During this meeting the namespace review should begin.  APIView should be updated with the approval of the namespace.
- [ ] We should show status of namespace approval in the SDK Release App.  For now, can show the status on the SDK Release Readiness screen.  Here is the GitHub issue tracking redesign of that screen - https://github.com/Azure/azure-sdk-tools/issues/6417.
```

**Comment by maririos** [comment]
@ladonnaq clarifying questions:
- "Teams releasing initial beta client libraries/SDKs " how do we know this information? Currently we are not asking that anywhere in the app. So should we?
- In which view/step should the schedule SDK Review meeting should happen?

**Comment by maririos** [comment]
> In which view/step should the schedule SDK Review meeting should happen?

[figma design](https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0-1&t=HmgBq7dkzSKfHn8f-0) help us with where the step should be

>"Teams releasing initial beta client libraries/SDKs " how do we know this information? Currently we are not asking that anywhere in the app. So should we?

For now, this will need to be updated manually in the work items. The issue to add this property into the UI of Create a Release Plan is: https://github.com/Azure/azure-sdk-tools/issues/6964
