### ISSUE TITLE
Decide naming convention for package id in the case of monolithic releases

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#642]
Most releases today are at the level of a package, for example `Azure.Storage.Files.Shares` ... The release tags take the form of `<package_id>_<version>` example: `Azure.Storage.Files.Shares_12.2.1` 

In the case of releasing a monolithic entity like the entire C SDK the package identity may not be as straightforward. What should the `<package_id>` portion (if any) of the release name be? 

In the case of the C SDK today we assume there is no package identity and the release tag takes the form of `<version>` (e.g. `1.0.0-preview.1`). Should this include a package identity?

**Comment by weshaggard** [comment]
Given it is a source release I suggest using the same convention we plan to use for azure-sdk-tools which is the repo name. So I suggest a tag name that looks like `azure-sdk-for-c_1.0.0-preview.1`
