### ISSUE TITLE
Handle `EDITOR` env variable being set

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#6420]
Currently, the test-proxy uses `lightweight` tags. Process to `push`

```bash
# check for changes with git status, if no changes abandon
git status
git add -A .
git commit -c user=blah email=blah -m "message"
git tag <tagname>
git push <tagname>
```

The issue is that when `EDITOR` is set, pushes of tags with no commit message will PROMPT for a message. This is PROBABLY an error, as a tag with no commit message **is a lightweight tag** and should be fully supported by git. However, @heaths has the `EDITOR` var value set, and as such is getting an invisible prompt for the annotated tag message. It is invisible because `vim` is a CLI app, and the way that `git` is in a new window. No communication can happen, hang occurs.

This is tangentially related to #4720

**Comment by heaths** [comment]
Seems it's not the `EDITOR`, but indeed `tag.gpgsign`. I'm curious how `git tag -c tag.gpgsign=false ...` broke the build. It's been supported for a while. How old is git on those agents?!

**Comment by scbedd** [comment]
Abysmally old. I'll definitely add `tag.gpgsign=false` again and check to see if it works on the default git. Worth a shot!

**Comment by scbedd** [comment]
Closing this! Fixed and rolled out!
