### ISSUE TITLE
Redesign the SDK Release Screen in the management SDK Release App 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6423]
The current screen is confusing and not very helpful.  
**Current UI** 
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/f12ec186-5ab8-4563-8460-ccc41f6424a8)

```[tasklist]
### Tasks
- [ ] Add additional information so that teams understand that their SDKs will not be released until the "expected target date".    Show target date, product name, languages being released, SDK versions, and status of GitHub issues.  
```

**Comment by maririos** [comment]
@ladonnaq where should the "GitHub issues" be created? After the Sign Off? 
Also, are you thinking on having the user click a button to generate the GH issues? or for us to create them without the user requesting it?

**Comment by maririos** [comment]
Changes made based on https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0-1&t=3DS7wrOEmrnoyo9G-0
