### ISSUE TITLE
Management namespace approval improvements for new UI 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6431]
Today the management namespace approval is a manual process.  Teams have to create a GitHub issue and follow the guidance on this wiki page to initiate the process.  https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/821/Naming-for-new-initial-management-or-client-libraries-(new-SDKs)

Questions: 

- Should a dedicated team of architects be responsible for approving the management plane namespaces?   
- Should the archboard use APIView to approve the namespaces?  This is how it is done for data plane. 
- Are teams blocked from releasing new initial SDKs if they do not have approval for namespace for management plane?  This is implemented for data plane. 
- If we are going to continue with the current process, then we should create the GitHub issue for the user in the Release Planner.  The user can enter the suggested names of the namespaces and we have all of the other information needed to create the GitHub issue for them using the template - https://github.com/Azure/azure-sdk-pr/issues/new?assignees=kyle-patterson%2C+ronniegeraghty&labels=architecture%2C+board-review%2C+mgmt-namespace-review&projects=&template=adp_mgmt_namespace_review.md&title=Board+Review%3A+Management+Plane+Namespace+Review+%3Cclient+library+name%3E

**Comment by maririos** [comment]
All of the questions have been covered either in docs or already implemented in the SDK release app
The only reminaing one is 
>If we are going to continue with the current process, then we should create the GitHub issue for the user in the Release Planner. The user can enter the suggested names of the namespaces and we have all of the other information needed to create the GitHub issue for them using the template - https://github.com/Azure/azure-sdk-pr/issues/new?assignees=kyle-patterson%2C+ronniegeraghty&labels=architecture%2C+board-review%2C+mgmt-namespace-review&projects=&template=adp_mgmt_namespace_review.md&title=Board+Review%3A+Management+Plane+Namespace+Review+%3Cclient+library+name%3E

which will be covered by https://github.com/Azure/azure-sdk-tools/issues/4601
