### ISSUE TITLE
Improve error messaging when API Ref Doc generation is failing in the PR 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6449]
Retesting previous release plans and encountered bug in preview docs generation.   There does seem to be an error in generating the API Reference Doc in the PR as well.   

It seems that there are bugs from time to time when the API reference doc is generated.  We should have a clear error message and explain to user what they should do if they see an error in generating the API Ref Docs in the Release Planner App and in the PR.  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/878d73e7-acf8-4062-8bc0-908cc5968e0b)

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/dbcef0f9-bd2a-47b0-b283-982ed40a19d6)

**Comment by maririos** [comment]
For the Release Planner we should improve the message as it is currently hard to see.
As for guidance on what to do, we should only have that in one place and that should be GitHub. 
@danieljurek do you know if that guidance is already in existance in the GH PR workflow?

FYI @konrad-jamrozik

**Comment by danieljurek** [comment]
TSG for failing `Swagger ApiDocPreview` build here: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/79/Generation-of-docs-on-learn.microsoft.com?anchor=%22swagger-apidocpreview%22-build-is-failing

The message posted in the PR links to the failing build in the pipeline hosted by the docs team. We've seen a lot of instances where the docs team needs to be consulted to understand the nature of the error.

**Comment by konrad-jamrozik** [comment]
@danieljurek thx for the info. Can you approve this PR? 
- https://github.com/Azure/azure-rest-api-specs/pull/24843
