### ISSUE TITLE
[docs automation] Replace GitHub owner resolution with a DL

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#6461]
At some point codeowners will migrate away from individual owner aliases and resolving a primary owner will become more difficult. 

1. Create DL with
    1. Daniel
    2. Jim
    3. Lori
    4. Justin
2. Remove [codeowners discovery automation](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/Helpers/Metadata-Helpers.ps1#L73) and use the alias instead

**Comment by JimSuplizio** [comment]
@danieljurek, if that alias is for content owners then you and I should not be on there.

**Comment by danieljurek** [comment]
ms.author: azsdkdocs
