### ISSUE TITLE
Design how the different work item types will be saved in our existing dataverse structure

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6475]
Currently, our Dataverse assumes there is only one work item type and value per Product. After working on the dashboard aggregation data we realized this is not correct and that we need different work item types to track different type of information.

The purpose of this issue is to come up with a design on how we are going to reflect that design into our existing Dataverse

**Comment by JonathanCrd** [comment]
I have created [this document](https://microsoft.sharepoint.com/:w:/t/AzureDeveloperExperience/EXKQbw6DdcBOjq2h1cPDhOYBiw6AXrBLPXzIOjS1GRcmkQ) for the chosen design and other discarded alternatives.

**Comment by JonathanCrd** [comment]
I added the new column in `Service Profile`, `Product Profile` and `Base Workflow` tables
