### ISSUE TITLE
Design how data will keep in sync between Dataverse and the ADO work items

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6476]
Release Planner needs the information in the different ADO work items in order to make decision in the UI (logic, information, etc). Although this data is in Dataverse, it is also in ADO. We want it to be in ADO so people can edit it accordingly. If such an update happens, how will the Release Planner will keep that information in sync?

Same is true for Service Tree information. If a service or product name changes, we want to make sure that the change is consumed in both Dataverse and the ADO workitems

**Comment by praveenkuttappan** [comment]
We can use an automated cloudflow that gets triggered when work item is created or updated.

**Comment by praveenkuttappan** [comment]
@maririos I believe we can close this now since we have cloud flows in place to sync the data between ADO and Dataverse.
