### ISSUE TITLE
Implementation design on how to work with existing work items (onboarding) and new work item types

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6477]
Currently the Release Planner and the Scheduler tool uses the ADO workitem `Onboarding` to save information, and make decisions. Our PM team also uses the existing WI to track and make progress on their work.
With the new design of having different workitems, how shoul we implement it withough affecting the existing flow?

**Comment by praveenkuttappan** [comment]
We can use a tag in addition to release planner test to mark any work item types are created by release planner . For e.g. package work item etc and these work items can be ignored by Cala or anyone who uses work items other than onboarding work item even after we roll this feature to production. This will help us continue creating all types of work items at all stages. We need to identify what work item needs to be created by which stage of the release plan.

//cc: @maririos @JonathanCrd

**Comment by maririos** [comment]
You mean add a label/tag to the WI, like "Release Planner App Test" ?

**Comment by JonathanCrd** [comment]
Where do you want to add the tag? In the Work Item or the Database?

**Comment by maririos** [comment]
In the work Item
