### ISSUE TITLE
Issue triaging bot should tag service owners no matter which order the labels are applied

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#6480]
Currently as implemented (https://github.com/Azure/azure-sdk-tools/blob/main/tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/EventProcessing/IssueProcessing.cs#L164) the service attention rule will only trigger when the "Service Attention" label is applied. So in a case where the "Service" label is applied after this rule will not correctly tag users in the comments.

cc @jsquire @JimSuplizio

**Comment by jsquire** [comment]
This is by-design and fits the current triage process.   `Service Attention` is the trigger to alert service teams that an issue is their purview.   `Service` is just a classification and is not considered as part of triage.   Once the CODEOWNERS changes are complete and we can enable fully automated triage, the initial process would identify that a service team should that library be owned by a service team.

As additional context, we should not be keeping pure service issues open in our repository, as these are not actionable.  If we receive an issue that is unrelated to an SDK - such as for a service or the portal, we should be guiding the issue author towards opening an Azure Support ticket.   The only `Service` issues that we should have in our repository are those that we use for tracking changes that we need to make to the SDK which are blocked by a service feature.

I'll leave this open for Jim to weigh in, but I don't see action here.

**Comment by jsquire** [comment]
@weshaggard :  I'm re-reading this and wondering if I initially interpreted the intent wrong.    When you mention "service" above, are you talking about the literal `Service` (yellow) label or one of the pink labels that represent a service area?   My initial read was based on the former.   If it's the latter, then my opinion is different.

**Comment by weshaggard** [comment]
I'm talking about the Service Area label that is paired with the Service Attention (ex: https://github.com/Azure/azure-sdk-for-net/blob/main/.github/CODEOWNERS#L69) There is always a pair of labels that need to be present, and I believe the order of applying them shouldn't matter we don't want to make this that fragile and force folks to know they have to apply "Service Attention" last.

**Comment by jsquire** [comment]
Ah, apologies.   I misinterpreted.   I agree that we should be able to add Service Attention and then add pink area labels to trigger notifications.  This was something that Fabric Bot couldn't do, so we overlooked it when porting rules.

@JimSuplizio :  I like this suggestion and would like to take it.   Any thoughts?

**Comment by JimSuplizio** [comment]
@jsquire @weshaggard @kurtzeborn 
I'll make the necessary changes when I'm updating this to remove the old codeowners parser.
