### ISSUE TITLE
Web-hosted API Reviewing Tool

### ISSUE THREAD

**Issue by mccoyp** [Azure/azure-sdk-tools#65]
We want a tool to review API content and structure in a parallel, easily accessible way. A web app being developed to achieve this is currently hosted [here](https://apiview.azurewebsites.net/).

Major features to be added:
- [ ] Cross-language comparison
- [ ] File diffs

**Comment by mccoyp** [comment]
Minor bug and desired feature tracking:
- [ ] Toggling of type name qualification
- [ ] Linking of only types within assembly
- [ ] Complete independence from Microsoft.CodeAnalysis library
- [ ] Uniform behavior on different browsers
- [ ] Redirect to review page of uploaded DLL
- [ ] Non-side-scrolling code display
- [ ] Use of named enum values instead of underlying type values in references
- [ ] Omission of namespaces without public/protected contents
- [ ] Nested namespace name chaining (Azure.Storage...)
- [ ] Operator rendering
- [ ] Default value support for all types (like structs)

**Comment by pakrym** [comment]
Done
