### ISSUE TITLE
APIView - doesn't accept .json files when uploading a review

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#6510]
Could we allow this again? If I attempt to do this apiview tells me it only takes .gosource files.

I got used to doing this when @praveenkuttappan showed me this forever and it's so much more convenient than creating a .zip file of all the go code over and over again since I (inevitably) also zip up all the other temporary junk like my .env file).

**Comment by mikekistler** [comment]
Check should be relaxed to allow JSON for the specified language type.

**Comment by chidozieononiwu** [comment]
@richardpark-msft You can select json in the dropdown then upload your json file.

**Comment by richardpark-msft** [comment]
Oh, awesome. I didn't think to look for a different type! 

Looking at it now though - do you even need the user to identify the type of upload? It seems like you always have enough info in the file extension/type of thing they upload (ie, .nupkg, .jar, etc..)
