### ISSUE TITLE
Explicit approval for new artifact names

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#652]
@JonathanGiles had a good idea for improving our release pipelines which would add an explicit approval step anytime an artifact is about to be released which includes a new artifact name (in the context of Java, this might mean a new ```groupId:artifactId``` combination).

The idea is that whenever we go to publish an artifact which has never been published before that we stop and ask for approval from the appropriate set of folks (a subset of folks that can approve deployments normally).

In order to do this we would need to go through the set of artifacts we are publishing, query the destination repository and if (and only if) it is a new artifact loop in folks to provide the additional approval).

**Comment by mitchdenny** [comment]
So now that I've said that this is a good idea. I feel we need to ask ourselves why we feel our general pull request process is not sufficient for picking up artifact names that we don't want.

**Comment by mitchdenny** [comment]
After some further discussion on our teams chat:

https://teams.microsoft.com/l/message/19:5e673e41085f4a7eaaf20823b85b2b53@thread.skype/1590532506522?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1590532506522&teamName=Azure%20SDK&channelName=Language%20-%20Java&createdTime=1590532506522
(internal link sorry)

We think the way to do this is to add a script to the Analyze job which is called once for each artifact listed in ```Artifacts:``` in the ```ci.yml``` file. This script would exist in each repository and be unique for the kinds of packages that they are producing. It would check the target registry (e.g. Maven Central) to see if an artifact with that name has been published, and if not check to see if it is explicitly referenced in a pre-approved list. If not it will fail the analyze step with a helpful error message pointing to our guidance documentation.

Our owners file will explicitly specify the architects as owners of that pre-approval file so that if someone tries to add it in for a package that has not been released yet, then they'll automatically be included in the review for the pull request.

**Comment by weshaggard** [comment]
It would be great if we can avoid duplicating the artifact list in multiple files. So perhaps we can roll this work in with our other plans to make the artifacts a separate configuration or template file. We could then give it a unique extension that we could use in our codeowners files for the architects to review. 

Also as an FYI @chidozieononiwu has added some helpers for finding the list of artifacts, see https://github.com/Azure/azure-sdk-tools/blob/master/eng/common/scripts/modules/Package-Properties.psm1#L238.

**Comment by kurtzeborn** [comment]
Overall, I think this issue is tracking a great addition to our process. However, I like the suggestion to move this upstream to PR validation rather than having the approval be required at release time.  Release days/weeks tend to be tense, and running into this road block at the end would add to that tension.  By recognizing the new artifact upstream (in the PR when it's introduced), we can defuse that and still get the benefit of architect approval of the new artifact.

@JonathanGiles what do you think about this?

**Comment by JonathanGiles** [comment]
Totally - I don't mind when it occurs, just that it occurs before we muddy up the Maven repo. Thanks for all the consideration.

**Comment by mitchdenny** [comment]
I think the architect review process for API release effectively closes this requirement off.

**Comment by weshaggard** [comment]
I think the api review process definitely helps but I don't believe it fully closes the gaps. Especially in the context of our partner release pipelines I know some architects wanted to block any new packages names being published anywhere if they are using our convention if they aren't approved. I'm not sure how we go about that but I know that is still an ask.
