### ISSUE TITLE
[PR workflow][pipeline-bot] Pushing changes to a PR in rapid succession will cause the GH CI check to stay longer in the 'queued' state.

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6523]
For example, the `PR Summary` GH check in this PR:
- https://github.com/Azure/azure-rest-api-specs/pull/24843/checks?check_run_id=15059371737

became green only 2 out of 4 times, even though there were 6 ADO pipeline builds which always said it is green:

- https://dev.azure.com/azure-sdk/internal/_build?definitionId=1736&_a=summary&keywordFilter=24843

For example:
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2921364&view=logs&j=d6a48a56-e996-55ca-2302-c3a9a7be685b&t=56afeb6c-46c2-527a-6538-834c38a9be60&l=16

```
2023-07-14T21:23:38.9472654Z {"level":"info","message":"EventHubProducer.send: FQN/eventHubName: openapi-platform-events.servicebus.windows.net/pipeline-events, events: {\"env\":\"prod\",\"source\":\"github\",\"unifiedPipelineTaskKey\":\"Summary\",\"unifiedPipelineSubTaskKey\":\"\",\"unifiedPipelineBuildId\":\"611e3b09-8197-4d10-98df-d1d8fba0c99d\",\"pipelineBuildId\":\"2921364\",\"pipelineJobId\":\"d6a48a56-e996-55ca-2302-c3a9a7be685b\",\"pipelineTaskId\":\"\",\"logUrl\":\"https://dev.azure.com/azure-sdk//internal/_build/results?buildId=2921364&view=logs&j=d6a48a56-e996-55ca-2302-c3a9a7be685b\",\"status\":\"completed\",\"result\":\"success\",\"subTitle\":\"\",\"logPath\":\"\"}"}
2023-07-14T21:23:40.1202726Z {"level":"info","message":"EventHubProducer.send: FQN/eventHubName: openapi-platform-events.servicebus.windows.net/pipeline-events, Done"}
```

Note the `"status\":\"completed\",\"result\":\"success\"`.

My investigation ([Kusto query](https://dataexplorer.azure.com/clusters/https%3a%2f%2fade.loganalytics.io%2fsubscriptions%2f8c0e0d10-c2d6-42b8-b1d9-e7132b6f18a3%2fresourcegroups%2frg-container-apps-prod%2fproviders%2fmicrosoft.operationalinsights%2fworkspaces%2fworkspacergcontainerappsprod9a92/databases/workspacergcontainerappsprod9a92?query=H4sIAAAAAAAEANVYW2%2fbOBp9L9D%2fwPFDLoAlWZItXxZBMU22nWCyTZCkmIeiMCiJtjmRSS1JxePF%2fvg9pGRZSZyZ2e4AixZFIInf9XxXOgjIze31BSl5yQoumJdKQwq51H3y9k0QkJyl1XLJxZJsVluykIqYFdfgmZGVMaWeBcGSm1WV%2bplcBz%2f%2bq1IsoPavp5g2Hi25p0uW6aCsiiKIhpNh7OSaFSO6Wq%2bp2pJsxbIHsqGaaFPhiQvyz4pVLCdfwq%2bEPTIBclktV4QbAjVlwQwOpXBSdpYTzXNGvkRffavAKTmXIisqzaVoP91f%2fe0Ctt9JOCkfNCn4A3NisqooFeRbM9aQWumV9VqwjVW55kYTIx3lza21UMG1HC5kGdNWww%2btiisItqzU1F7CvbwqYHBrqaqEJl%2fir%2f2uEeuqMByuEbmwfGuyYarLDZ30hdY%2b2QB9HIVkzUVlGKELwxRhNFsRCTFqVscxmoUTcvMPcnNx37cv085LNOi%2bxO0L2AW%2bjJKnX%2bLZKGy%2bOKjJtSi2xGwkQcjhRG3rx5%2fI%2bWUT2qrMqWGaeOSOwcJCS4cpE8YGccHBozRJWSE3FmQNos2KwwObiIQChjWHu2JZ63tfmS5wSBAkETAFo8gJFS5lzC5cf7cvPyFB2wDBLBDJVDP1yGodTRpwPXMUCoKY%2biz4grP8pgnbufVlRkr1WRXfnv392ro7Q02lZ%2ft0BrhUP1wwQ3nh10D6gq4ZcrUuk0MEupHCxbxUcomvuobokzTWH6RgjQVKdl84KfB7TZal7Eqrs%2bd%2bZXPRBYKK7TPIgHhOhDSuXla0LJkAnw3SxqYLGsrKsXZdtQfd3NjxAR1%2f6c%2faUH1vgWil%2bP8%2f8zMpDPvN%2bED0vOCg8R3S2q%2bhPnFvc9TLnIPa9%2bED2q02F9TQ09q5Qw7XUm4rcZnPSDgajMaTSTwMkz554byzoem8s1236pOOnkYBWmmjY1%2bdyLUOwPpZetrKXTIktEB5H7caj50RjKRbe2psJtradxDtWClayFIg%2f8HJrQSEQFrLnsUHLrqe8axf2K5km5xLfjDvm%2fCz7uF4fl%2f0XxV9v3oq%2fx64%2fcy2nch1Eeimp4P41kFLbCyCGuZgR9kICCok8AKS86DTFb4HD7%2fB1yaiQcvZRvOD23vQwqjGGEPy5DwXx8ZlIlKjLqzZ9wCLTywpLH5f8SK%2fzIOqbHjxdFelraBoMU3TfDH00nwUe8NpvvAmw%2bHYm2TJdBxFScoWYbBDDkMAA4Cgvmlhy6uw495g0DgddqMplZ9VCv3QNIrRQxj6xyIZenFCE2%2bYh6GXpqOJF49ZNM3Gi2wxinxyy0ylhC1oRlXxpE9Aaz02EO2YGL5mere0tCuHiynLreO%2fuJViTQ0amX66OrqFrLPcupGGJc6ZvuOo55UjRc1%2f5HapICemHY3DvgNhdLq30e6v3xrpoO7a77rt%2bqzuu8PxdBDWCqK9gpw9%2bk6m01FL1%2fkDChfrlaBFMHfxaLJfv2uicxZNozBOhkePnG3ObHc7%2bvUsT%2bhwQkeJx6bTxBuNMupF8SDysphO6ThlyWSUHpmzUUIXLE0yb5hkkTeKxtRLRvHEQ2CzeEKnIBzUdsb%2ftZ3vXOPhBg0WRobjODma07PmznD0wLYbqfIPbnc8a%2b4VduTg9eR4p4rmzIdHFFK3hmfa5xJVnupM8dIK1sEkG7BBHg68LMqRhFE68dIwn3psHMZRmizCCY0tYrJSGVsqWZU6UEvPzliKzFEIXak9FH0e4M8jriBKB2ueKanlwviyZIpaTRR5hvGzMjqA3Q%2b6pOgS%2b0e1bCVagVbelE6j41MfaUxTtJ2T3h8R90798933HzH74Z4s2BUCOj%2b%2fevvm3wRLgV2QP9%2bfkzNXLnPT%2bXxzd4%2fPtmrcUWWyuZHzQma0OAFLn%2fQ%2b3wU3NEPfyXqnlnHjUt%2fypcxsGOruZMd%2bEg2i2BuMvXBIwng2GOD%2fqe8fPB43xx2ZrR8fLeKf0LPnttY16XXvqb09A7wExQ%2bO5PLTh2vbhkExe4Xk5hpG41I0GLxCEKAiA8TskTkCZBouVVgurLNUZx3Y3r4h%2bPfSYGB5yIt%2bTX%2fLHhsiPHG7RDw5fl%2bJLRUNhbVLvDxtTtZ62R40Ib%2fG6l0f7g5%2bQfIZKa4wFIrmqLDPzwl2MjHA6BIKrZ9A8leWGTSqGgVA0CcuIV7619851u%2b4sHvud%2bzrPzGpfdsHo%2fHRBcNVd48E9qcKcnlxmKgZRb3Dp78%2flXuu33fpX5mePdvMDsk%2fvIu%2fSv7aiu4YyCGOTuN3SHzgCgO2t1%2bge%2fv51K9vfphkx%2fXvKMe4eYt6c3UKCBL6gPRxOGhwvmOwMP%2bLxbvbghOP0a3%2bhPTz%2fXbvNT8FaJQd5mSzmx3WNI3HmBbjGib0bVw%2f%2fzdV%2fwFgln1iJBMAAA%3d%3d)) shows the culprit is [in this code](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/PipelineEventListener.ts&version=GC0ab4a859066e3aad63869f27429842591f80aae8&line=381&lineEnd=389&lineStartColumn=1&lineEndColumn=38&_a=contents):

``` typescript
    if (pr && pr.currentBuildId && pr.currentBuildId !== event.unifiedPipelineBuildId) {
      await this.logger.logWarning(
        `${logPrefix}. Task upBuildId/upTaskKey/upSubTaskKey: ${event.unifiedPipelineBuildId}/${event.unifiedPipelineTaskKey}/${event.unifiedPipelineSubTaskKey}`
        + `is not equal to latest buildId of pr.currentBuildId: ${pr.currentBuildId}. Returning early.`
      );
      return;
    }

    taskResult.status = event.status;
```

I.e. I see logs like:

`processUnifiedPipelineRunEvent: prUrl: https://github.com/Azure/azure-rest-api-specs/pull/24843, event.unifiedPipelineTaskKey: Summary, event.status: completed. Task upBuildId/upTaskKey/upSubTaskKey: 2f9bbdf4-bd53-49df-8447-8c697226bef1/Summary/is not equal to latest buildId of pr.currentBuildId: 1e834f64-36a6-4d11-bb58-37e29c7fcf52. Returning early.`

causing early return and `taskResult.status = event.status;` not being called. If it were, the `taskResult.status` would get updated from `queued` to `completed` and pipeline-bot would update the check.

## Workaround

Comment on the PR with `/azp run` and let it finish without pushing any additional changes.

**Comment by konrad-jamrozik** [comment]
I am closing this for now as I am not 100% sure if this was in fact a bug.

**Comment by benbp** [comment]
Devops can get in odd states with rapid pushes, as it cancels out earlier checks that were running and starts new checks for the latest commit.
