### ISSUE TITLE
[github event processor] Add retries and/or ignore failure checking rate limit api

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#6524]
See https://github.com/Azure/azure-sdk-for-net/actions/runs/5559064410/jobs/10154804951 for an example of a job run that failed just because of a transient github server error checking the rate limit API. It appears from the source https://github.com/Azure/azure-sdk-tools/blob/main/tools/github-event-processor/Azure.Sdk.Tools.GitHubEventProcessor/GitHubEventClient.cs#L310 that we do not do a retry on that call and do not ignore any failures (arguably we ignore a fail there).

**Comment by JimSuplizio** [comment]
I'm going to be adding the retries, it'll try 5x waiting 200ms in between replies. This is the as much as I'm willing to do as anything more has the potential to delay action processing which is not what we want. Ignoring the result is not really an option, if we can't get the rate limits then no rules should be processing.
