### ISSUE TITLE
Samples documentation for data plane SDKs

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6531]
When using DPG, is there any documentation for generating samples? or guidance per language on how to write their samples?

We will like to use this information in the new Eng Hub documentation site for our service partners

Section: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-samples?tabs=dataplane

**Comment by lmazuel** [comment]
@lirenhe FYI

**Comment by lirenhe** [comment]
@weidongxu-microsoft   @ArcturusZhang,   @MaryGao,  @msyyc,   could you provide the link of the current sample writing/generation guide for the SDK you are working on?  thanks

**Comment by weidongxu-microsoft** [comment]
Java https://github.com/Azure/azure-sdk-for-java/wiki/TypeSpec-Java-Quickstart#examples

**Comment by msyyc** [comment]
For python, we don't support generating samples for now. Here is guidance about how to write test/samples:
- https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen#how-to-write-tests
- https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen#how-to-write-sample

**Comment by maririos** [comment]
> For python, we don't support generating samples for now. Here is guidance about how to write test/samples:
> 
> * https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen#how-to-write-tests
> * https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen#how-to-write-sample

@msyyc  Should https://aka.ms/azsdk/dpg/python/tests be updated to point to https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen#how-to-write-tests instead ?

**Comment by maririos** [comment]
Draft PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/778
Still need:
- .NET
- JS

**Comment by msyyc** [comment]
> > For python, we don't support generating samples for now. Here is guidance about how to write test/samples:
> > 
> > * https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen#how-to-write-tests
> > * https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen#how-to-write-sample
> 
> @msyyc Should https://aka.ms/azsdk/dpg/python/tests be updated to point to https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen#how-to-write-tests instead ?

https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen#how-to-write-tests will also jump to https://github.com/Azure/azure-sdk-for-python/wiki/Dataplane-Codegen-Quick-Start so I think it is ok to keep it.

**Comment by ArcturusZhang** [comment]
@chunyu3 do we have a doc on how to write samples for DPG?
The generated samples are always generated when you generate the code.

**Comment by chunyu3** [comment]
> @chunyu3 do we have a doc on how to write samples for DPG? The generated samples are always generated when you generate the code.

This is the doc about how to write samples in .NET SDK : https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/Azure_SDK_Package_Ship_Requirements.md#samples

**Comment by MaryGao** [comment]
JS guide: https://github.com/Azure/azure-sdk-for-js/blob/main/documentation/RLC-quickstart.md#how-to-write-samples

**Comment by lirenhe** [comment]
> Draft PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/778 Still need:
> 
> * .NET
> * JS

@maririos,  I updated your PR for the link of JS and .dotnet.   Thanks all for providing the information.

**Comment by maririos** [comment]
Merged and deployed: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-samples?tabs=dataplane
