### ISSUE TITLE
Samples documentation management plane SDK

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6533]
Is there any documentation for generating samples? or guidance per language on how to write their samples?
Are there any requirements on the number of samples? is it different for .NET?

We will like to use this information in the new Eng Hub documentation site for our service partners
Section: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-samples?tabs=management

**Comment by weidongxu-microsoft** [comment]
Java, by default enabled, as long as spec has example JSONs (these are required by spec).

**Comment by msyyc** [comment]
Here is guidance for Python: https://github.com/Azure/azure-sdk-for-python/wiki/What-to-do-after-generating-the-SDK-code-with-codegen#how-to-write-sample

**Comment by tadelesh** [comment]
For Go, samples (examples in Go) are generated by tool. Refer this: https://github.com/Azure/autorest.go/blob/main/packages/autorest.gotest/doc/gotest_howto.md#generate-examples

**Comment by maririos** [comment]
thank you all. Will the autogenerated samples work if the REST API spec is written in TypeSpec?

**Comment by weidongxu-microsoft** [comment]
@maririos 

Currently there is no direct codegen from TypeSpec to SDK. It is via TypeSpec to Swagger, then Swagger to SDK.

I think typical TypeSpec to Swagger flow is that examples in TypeSpec folder will be transferred to Swagger folder via typespec-autorest (option `examples-directory`).

e.g. https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/Fleet.Management/tspconfig.yaml#L7 to https://github.com/Azure/azure-rest-api-specs/tree/main/specification/containerservice/resource-manager/Microsoft.ContainerService/fleet/preview/2023-03-15-preview

The result would be a Swagger directory same as usual (with examples).

The rest would be same OpenAPI to SDK via autorest.

**Comment by live1206** [comment]
For dotnet, sample generation is via below command and located in [sample](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/devcenter/Azure.ResourceManager.DevCenter/samples) folder
```
dotnet build /t:GenerateTests
```
Normally, there is no hand-written samples for dotnet. But hand-written scenario tests are located in [tests](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/devcenter/Azure.ResourceManager.DevCenter/tests) folder.

Detailed documentation of dotnet generation is [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process?anchor=sdk-generation-from-updated-spec)

**Comment by qiaozha** [comment]
For typescript mgmt plane, we have an autorest option  --generate-sample=true which is enabled when we release the mgmt plane library. 
We currently don't have the manual written samples for mgmt plane.

**Comment by maririos** [comment]
Thank you all. I have added all the information in my draft PR here: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/783?_a=files&path=/docs/develop/sdk-samples.md

Please take a look to make sure I aggregated the information correctly

**Comment by maririos** [comment]
Merged and deployed: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-samples

**Comment by weidongxu-microsoft** [comment]
> Java, by default enabled, as long as spec has example JSONs (these are required by spec).
> 
> dev can turn off via `generate-samples=false` in autorest option.
> 
> Handwritten samples can be added to `src/samples/java/<namespace>` folder.

The link of Java is wrong. It points to guide on sample for DPG.

As above, just say "dev can turn off via `generate-samples=false` in autorest option" would be fine.

**Comment by maririos** [comment]
> > Java, by default enabled, as long as spec has example JSONs (these are required by spec).
> > dev can turn off via `generate-samples=false` in autorest option.
> > Handwritten samples can be added to `src/samples/java/<namespace>` folder.
> 
> The link of Java is wrong. It points to guide on sample for DPG.
> 
> As above, just say "dev can turn off via `generate-samples=false` in autorest option" would be fine.

In which cases will the dev want to turn off the samples generation if they are required in order to release?

**Comment by weidongxu-microsoft** [comment]
> @weidongxu-microsoft In which cases will the dev want to turn off the samples generation if they are required in order to release?

I haven't see any service wanted to disable it (theoretically they can disable it and handwrite they samples, but none did that). So I assume we can just omit it. Maybe you can see in mgmt-plane, generate samples is enabled automatically.

**Comment by maririos** [comment]
@weidongxu-microsoft PR => https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/789
