### ISSUE TITLE
Documentation for sdk-generate-mgmt-dotnet

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6534]
Need to add content to page: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-generate-mgmt-dotnet

**Comment by lirenhe** [comment]
@maririos,  could you provide more details about what content need to be provided in that page?
As this item is added into the backlog,  I expect this is not an urgent task,  is that correct?

**Comment by maririos** [comment]
Sure. We are moving information from our internal wiki to Eng Hub and there is a section about the .NET management plane SDK that we should move. I did an initial structure for it, but the information per se needs to be moved.
The deadline is Sept 1st.

See more information about this here: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/995/%E2%9D%97%EF%B8%8FAction-Migrate-partner-docs-to-Engineering-Hub

**Comment by ArthurMa1978** [comment]
Here is the pr https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/779

**Comment by maririos** [comment]
Related: https://github.com/Azure/azure-sdk-tools/issues/6724

**Comment by maririos** [comment]
New PR https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/874

**Comment by maririos** [comment]
Merged: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-generate-mgmt-dotnet
