### ISSUE TITLE
Move Release checklist to Eng hub

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6535]
See section: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-release

This applies to both management and data plane

**Comment by ccbarragan** [comment]
Hi @czubair Any updates for this item?

**Comment by czubair** [comment]
@ccbarragan Hi Crystal! Sorry I don't quite understand what I should be updating/reviewing here. Feel free to ping me or set up a meeting. Since I am transitioning off the release, this might be better for others to decide.

**Comment by ronniegeraghty** [comment]
Link to ADO PR to get checking list in Docs: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/947
