### ISSUE TITLE
APIView - Improve the instructions to get access to APIView

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6546]
APIView is accessible only if user a member of Azure or Microsoft GitHub org and this org membership has to be publicly available. Currently instructions on APIView is as follows when authentication fails. 

![image](https://github.com/Azure/azure-sdk-tools/assets/55455725/41a9ffad-4c33-4fa6-b568-37fa34f0acd7)

This should be improved with more instructions and links and more instructions on how to change it to public to help them easily change org membership to public.

I think it’d help if we make the links more specific like:
-	Azure
o	Join Org: [https://repos.opensource.microsoft.com/orgs/Azure](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Frepos.opensource.microsoft.com%2Forgs%2FAzure&data=05%7C01%7CPraveen.Marottickal%40microsoft.com%7C7c45c0aeaea44ef8f6b608db8811080e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638253378965861694%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d4X%2F4XTqn2E5GsG13N9LMKPmavoMIzdPqA98wrCjDUQ%3D&reserved=0)
o	Make Public: [https://github.com/orgs/Azure/people?query=your-alias](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Forgs%2FAzure%2Fpeople%3Fquery%3Dyour-alias&data=05%7C01%7CPraveen.Marottickal%40microsoft.com%7C7c45c0aeaea44ef8f6b608db8811080e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638253378965861694%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UkMF6wiGrn2rYcgPanEEKLggV%2BFpgZJmP8USElvoeWA%3D&reserved=0)
-	Microsoft
o	Join Org: [https://repos.opensource.microsoft.com/orgs/Microsoft](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Frepos.opensource.microsoft.com%2Forgs%2FMicrosoft&data=05%7C01%7CPraveen.Marottickal%40microsoft.com%7C7c45c0aeaea44ef8f6b608db8811080e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638253378965861694%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=53mrgPPNwEEmDsBn6HaeUn5NafjRvAQgqP0bLRtH1u4%3D&reserved=0)
o	Make Public: [https://github.com/orgs/Microsoft/people?query=your-alias](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Forgs%2FMicrosoft%2Fpeople%3Fquery%3Dyour-alias&data=05%7C01%7CPraveen.Marottickal%40microsoft.com%7C7c45c0aeaea44ef8f6b608db8811080e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638253378965861694%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=cmVjdVNZalvDj%2FWxQE%2BGZSzdCOrGp0%2Bq3TldNbO18XE%3D&reserved=0)

**Comment by mikekistler** [comment]
I thought we changed the permissions model to check the Microsoft directory, so that public membership was not required.
