### ISSUE TITLE
Change release scripts so packages are children of release plan in ADO instead of "related" items

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6552]
For the design chosen in https://github.com/Azure/azure-sdk-tools/issues/6475, all related Work Items in an ADO Work Item must be converted to Childs. Since packages will only depend on one release plan, all Work Items of type Package created by any script must be included as Child in the Release Plan Work Item parent.

**Comment by maririos** [comment]
PR: https://github.com/Azure/azure-sdk-tools/pull/6782

**Comment by maririos** [comment]
We need to change the logic to look for the release date of the Release Plan to guarantee we have the right one

**Comment by praveenkuttappan** [comment]
Revert the changes in prepare release scripts so that package work items are created as children of product work item.
