### ISSUE TITLE
[Save-Package-Properties.ps1] Add support for filtering by IsNewSdk based on parameter

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#6553]
Recent [changes](https://github.com/Azure/azure-sdk-tools/pull/6544/files) to `Save-Package-Properties.ps1` to mitigate the Java Storage track 2 pipeline getting incorrect package metadata will result in the track 1 pipeline exporting incorrect metadata. 

To that end, we looked at two options: 

1. Add in a parameter to `Save-Package-Properties.ps1` which filters packages based on whether the build is "client" (track 2) or "data" (track 1). This can be determined by the `SDKType` parameter coming from `ci.yml` and `ci.data.yml`
2. Pass in a list of artifacts being built in the pipeline and constrain the output from `Get-AllPkgProperties` based on the specified artifacts. These can also be passed in through the `ci.yml` or `ci.data.yml`. 

Currently this issue is known to impact only `azure-storage-blob` for track 1 and no other packages based on looking at artifact names in the various `ci.yml` and `ci.data.yml` files organized by services in Java and .NET (JS and Python do not have `ci.data.yml` files)

**Comment by JimSuplizio** [comment]
@danieljurek I think this bug can be closed. com.microsoft.azure:azure-storage-blob was removed from azure-sdk-for-java with this [PR](https://github.com/Azure/azure-sdk-for-java/pull/40460) 3 months ago. At this point this version of azure-storage-blob will no longer cause the SNAFU in preview or latest.

**Comment by danieljurek** [comment]
Closing. This was resolved with the removal of the problematic track 1 package.
