### ISSUE TITLE
More diagnostic information needed when recording syncing fails

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#6563]
Related to #6562, it would be great if the test proxy could output more diagnostic information - at least for CIs, if not local dev loops - about what is being sync and any failures that occur. Looking at the failed run, I was not able to tell what had happened. Someone more familiar with the implementation was able to help, but to scale we need more self-diagnosable information available in the CI.

**Comment by scbedd** [comment]
> Related to #6562, it would be great if the test proxy could output more diagnostic information - at least for CIs, if not local dev loops - about what is being sync and any failures that occur. Looking at the failed run, I was not able to tell what had happened. Someone more familiar with the implementation was able to help, but to scale we need more self-diagnosable information available in the CI.

It definitely outputs it. I'm betting that my ordering of exceptions is off, and that's why you're not getting the initial `GitProcessException` that shows the _actual_ error that you're expecting. 

One recommendation for the .NET CI is that it should upload the output of the proxy that we kick as part of the framework. Given the lack of proxy logging I don't really know where to begin to figure out what actually happened here.

**Comment by heaths** [comment]
Should it just write to stdout or even stderr? I find that tends to be the easiest to diagnose. For example, I saw a couple of `git --version` commands and outputs. Didn't help for this, but clearly helpful for however needs to know when diagnosing issues.

**Comment by scbedd** [comment]
> Should it just write to stdout or even stderr? I find that tends to be the easiest to diagnose. For example, I saw a couple of `git --version` commands and outputs. Didn't help for this, but clearly helpful for however needs to know when diagnosing issues.

Yeah I think this is the problem [right here](https://github.com/Azure/azure-sdk-tools/blob/2387badad3382ffba032c4ae726dac632dea292c/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Store/GitProcessHandler.cs#L173) We're collecting the stderr -> but we're not outputting it onto StdErr pipe -> so the .NET framework isn't **seeing** [that output](https://github.com/Azure/azure-sdk-for-net/blob/60ad0fdd3c63b3306b5fc03345dc67f702a663f9/sdk/core/Azure.Core.TestFramework/src/TestProxy.cs#L207) -> you aren't seeing it in CI.

**Comment by JoshLove-msft** [comment]
Addressed on the .NET Test Framework side in https://github.com/Azure/azure-sdk-for-net/pull/37994
