### ISSUE TITLE
Informational meeting scheduler - Update Triage work item

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6580]
Update triage work item for the product/service when an informational meeting is setup to provide details like informational meeting details.

Dependency : https://github.com/Azure/azure-sdk-tools/issues/6579

**Comment by maririos** [comment]
View with new logic added. I also fixed other bugs in the app. Nothing major.
We need to delete the old view and connect everythng to the new one :)

**Comment by maririos** [comment]
Done
