### ISSUE TITLE
Release planner - Update API-Spec ADO work item 

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6583]
Update API spec work item when a pull request for spec changes are associated to a release plan using `Associate pull request` screen in Data plane and management plane API readiness app.

- [x] Data Plane
- [x] Management Plane

**Comment by JonathanCrd** [comment]
We have a `Rest API Review PRs` field in the work item. When saving the associated PR in the Readiness App, do we want to replace the old value here? Or keep the current value and just append the newest linked-PR?

CC @maririos

**Comment by maririos** [comment]
> Or keep the current value and just append the newest linked-PR?

This. We want to make sure to have the history
