### ISSUE TITLE
Release plan - Mark API spec work item as completed

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6586]
Update API spec work item status and API readiness release plan is completed.

Change required in: 

- [x] Data plane API readiness
- [x] Management plane API readiness

**Comment by JonathanCrd** [comment]
For the `API SPEC` work item type, exactly what field should be updated?
`State` as 'Published'? or `API Spec State` as 'Approved'?

**Comment by maririos** [comment]
@ladonnaq to help with this question

**Comment by ladonnaq** [comment]
> For the `API SPEC` work item type, exactly what field should be updated? `State` as 'Published'? or `API Spec State` as 'Approved'?

Good question.  So the state of the work item should be the overall state of the artifact.  The API Spec State is specifically related to the API Spec state (Is it in API Review, published, deprecated, etc).  Let me know if we should create a new field or update the label to of that field so that it makes more sense.

**Comment by JonathanCrd** [comment]
Sorry, it is still not clear to me.
When a user clicks the "Complete Button" and completes the API Readiness milestone, exactly what field and value should be updated by the app?

**Comment by JonathanCrd** [comment]
After talking with @ladonnaq, these are the fields on each work item type that must be updated when the API Readiness Milestones is completed:

- [ ] RELEASE PLAN
   - [ ] API readiness milestone state -> `Completed`
- [ ] API SPEC
   - [ ] System.State -> `Published`
- [ ] EPIC (Product)
   - [ ] APEX Mgmt _(Management Plane only)_
      - [ ] Mgmt API Validation Private Preview -> `Completed` _(Private Preview only)_
      - [ ] Mgmt PubPrev API readiness -> `Completed` _(Public Preview only)_
      - [ ] GA mgmt API Readiness State -> `Completed` _(GA only)_
   - [ ] API Data _(Data plane only)_
      - [ ] PrivPrev Data Plane API Readiness State -> `Completed` _(Private Preview only)_
      - [ ] PubPrev Data Plane API Readiness State -> `Completed` _(Public Preview only)_
      - [ ] Data GA API Readiness State -> `Completed` _(GA only)_

**Comment by maririos** [comment]
For issue: https://github.com/Azure/azure-sdk-tools/issues/6587 currently we can only mark complete the Release Plans that are in private preview and that is when the API Readiness is completed. 
so as part of 
>  RELEASE PLAN
 API readiness milestone state -> Complete

Could you also update the status of the Release plan work item to `Finished` ?
