### ISSUE TITLE
Release planner - Update work item for any obsolete language as not required

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#6588]
Not all release plans releases SDK packages for all languages but a package work item is created for all tier 1 languages when a release plan is created. We need to mark ADO work item for any package that is not required to be released as part of a release plan when required languages are selected in SDK release app.

Change required in: Management and Data plane SDK release apps

**Comment by maririos** [comment]
After talking to @ladonnaq we have decided to create the SDK packages work items in the SDK apps and not when a release plan is created. 

This issue is still valid for the SDK apps when a language is unchecked

**Comment by praveenkuttappan** [comment]
Package work items are created only based on the list of languages selected in SDK release apps. So, we don't need to close any package work item. SDK release apps does not allow to uncheck a language once confirmed. So, we need to revisit whether we need to close the work item only if functionality is modified to uncheck a language from previously confirmed languages.
