### ISSUE TITLE
Horizontal tablist component for Power App Screens

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6596]
**Requirement:** Create an horizontal tablist component, which will be used across the Power apps Screens.  

**Why:** The horizontal tablist provides a better user experience, enabling user to better understand the order of sub-task for each of the major steps in the API readiness and SDK release readiness apps. 

See screenshot from Crystal's figma design - https://www.figma.com/file/JzbPB3xPwrjdxJ5SiG7hYD/Design-sync%3A-SDK-readiness?type=whiteboard&node-id=0%3A1&t=mCRHlDarUXpqPfdG-1

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/2f013224-e04e-4e93-bd39-a2a80284776e)

**Comment by ccbarragan** [comment]
Created separate issue to track design work:

https://github.com/Azure/azure-sdk-tools/issues/6629

**Comment by maririos** [comment]
Related issue: https://github.com/Azure/azure-sdk-tools/issues/6992

**Comment by maririos** [comment]
@praveenkuttappan 
With the implementation you did for the SDK release apps, do you consider we still need this? or we can reuse what PowerApps has

**Comment by ladonnaq** [comment]
> @praveenkuttappan With the implementation you did for the SDK release apps, do you consider we still need this? or we can reuse what PowerApps has

@praveenkuttappan  @maririos Can we close this and remove it?  Or is there follow-on work that should be tracked in a new GitHub issue?

**Comment by maririos** [comment]
We are good. Let's close it
