### ISSUE TITLE
[RPaaS LiveValidation] `validate-v2` unavailable while specs refresh?

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#6602]
The RPaaS team has reported an outage over a two minute time span where the specs were unable to refresh due to networking issues to github.com.

The service should definitely be available and validating requests while this refresh occurs, so we need to dig in and figure out what's up.

**Comment by kurtzeborn** [comment]
@scbedd this seems like something that the RPaaS team should be taking ownership of.

**Comment by scbedd** [comment]
We have transitioned this codebase. Closing.
