### ISSUE TITLE
Update the schedule tool to clarify the API meeting is for data plane API

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6603]
The tool is used to schedule data plane API reviews, but we've seen instances where ARM APIs are being scheduled (e.g. Azure Firewall - Azure Firewall Premium).  Can add the words “data plane” and/or “non-ARM” in a couple of places.  e.g., on the schedule tool landing page we could say “If you’ve built a data plane API specification ….”  And then even in the text that ends up in the invite, there is probably an opportunity say data plane / non-ARM once or twice.

**Comment by maririos** [comment]
Added data plane information into:


![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/55551964-792f-4f88-bce7-5956b885ba15)



![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/2d90a238-7e34-477a-9259-636835d56d9f)
