### ISSUE TITLE
[APIView] Error in DownloadPackageArtifact

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#6609]
We are still getting too many failures while attempting to download DevOps artifacts at https://github.com/Azure/azure-sdk-tools/blob/da981359e9e344cf91475a83a0df30f2915f7210/src/dotnet/APIView/APIViewWeb/Repositories/DevopsArtifactRepository.cs#L67-L79
The retires don't seems to be enough to overcome the throttling. We should investigate what is going on and resolve the issue.

Examples:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2955857&view=logs&j=e37a1bb9-a190-5269-3a0e-37469dfbe682&t=0f4d9e1c-b84a-5348-e162-7b2c6c640d5f&l=433

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2953413&view=logs&j=e37a1bb9-a190-5269-3a0e-37469dfbe682&t=0f4d9e1c-b84a-5348-e162-7b2c6c640d5f&l=431

**Comment by benbp** [comment]
Do we log the `X-RateLimit-Limit` and `X-RateLimit-Resource` headers? It might help to diagnose how/when the limits are getting hit, we do a similar pattern with the github event processor. Docs: https://learn.microsoft.com/en-us/azure/devops/integrate/concepts/rate-limits?view=azure-devops#api-client-experience

**Comment by mikeharder** [comment]
@chidozieononiwu: Can you share some example logs when this fails, or tell me how to find the logs myself?
