### ISSUE TITLE
[PR Workflow] Improvements to API spec PR review process

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6610]
In this work item I aggregate all the various identified areas for improvement to be made for API spec PR review process.

The current API spec review process for ARM PRs is given by this diagram:
- https://github.com/Azure/azure-rest-api-specs/blob/main/.github/PULL_REQUEST_TEMPLATE/spec_pr_review_workflow_diagram.png

plus a plethora of various comments added to the PR by our automation.

There are some gaps and inconsistencies in this process and surrounding documentation that lead to folks not being able to follow it properly.

This issue discusses various proposed fixes to make the process easier to follow.

However, this work item will most likely be subsumed by: 
- #6617 

Things to improve:

- **DONE** Mention in the diagram people should refer to the `Automated merging requirements met` check to unambiguously determine what they are missing.
  - **DONE** Sort out with Ray how to handle `DoNotMerge` and `Approved-OkToMerge` labels. This confuses users, see [this](https://github.com/Azure/azure-rest-api-specs-pr/pull/12930#issuecomment-1579439459) and [my intervention](https://github.com/Azure/azure-rest-api-specs-pr/pull/12930#issuecomment-1652543423).
  - **DONE** Also fix the typo in one of the workflow-bot comments that says `Approve-OkToMerge`.
  - **DONE** Understand how the label `ShiftLeftApiSpecReview` comes into play here.
- **DONE** Surface better to the users that for them to get their PR reviewed by ARM team, they need to ensue it is on the review queue, and link to the review queue. Now it is very hidden in Teams channel announcements below the fold.
- **DONE** Make people understand that LintDiff suppressions are to be reviewed by ARM team ([example confusion](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1690496632918?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1690496082508&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1690496632918)) but there are also LintDiff SDK suppressions to be reviewed by SDK team instead. See [this doc](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/openapi-authoring-automated-guidelines.md) linked from [this doc](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/85/Swagger-Suppression-Process).
    - **ON BACKLOG** Probably we should split the suppression label into two: one for ARM, one for SDK.
- **DONE** Explain better the case when breaking change policy says there is no approval needed. [Example confusion](https://teams.microsoft.com/l/message/19:f6d52ac6465c40ea80dc86b8be3825aa@thread.skype/1690233040201?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1690232121944&teamName=Azure%20SDK&channelName=General&createdTime=1690233040201) and also [Roopesh's reply](https://teams.microsoft.com/l/message/19:f6d52ac6465c40ea80dc86b8be3825aa@thread.skype/1690455266247?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1690232121944&teamName=Azure%20SDK&channelName=General&createdTime=1690455266247).
- **DONE** Explain to folks that claims that they don't require a review must be verified by people doing the reviews. [Example confusion](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1690234218008?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1690231059259&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1690234218008).
- **ON BACKLOG** Do the doc updates I mentioned in email thread `Consolidating official docs and support channel announcements` from 7/13/2023.
- **DONE** Update and transplant https://aka.ms/azsdk/support/spectools to EngHub.

### Related work

- https://github.com/Azure/azure-sdk-tools/issues/6617

**Comment by konrad-jamrozik** [comment]
@raych1 

I have a question about the `DoNotMerge` label. I understand that it has two meanings. 

Meaning one: to be manually added by the PR author, to denote that even though the PR with the spec may be ready to merge, the service is not yet running, so if the API is merged and deployed, it won't actually work

Meaning two: added in case of ShiftLeft scenario. Here, the workflow is as follows: once the source ADO PR is ready to be merged, the PR author adds `Approved-OkToMerge` label, then merges the ADO PR, then automation merged the GitHub PR. [Example comment](https://github.com/Azure/azure-rest-api-specs-pr/pull/12930#issuecomment-1579439459) and [a follow-up](https://github.com/Azure/azure-rest-api-specs-pr/pull/12930#issuecomment-1652543760).

Is my reasoning correct?

**Comment by raych1** [comment]
> @raych1
> 
> I have a question about the `DoNotMerge` label. I understand that it has two meanings.
> 
> ### Meaning one
> To be manually added by the PR author, to denote that even though the PR with the spec may be ready to merge, the service is not yet running, so if the API is merged and deployed, it won't actually work
> 
> ### Meaning two
> Added in case of ShiftLeft scenario. Here, the workflow is as follows: once the source ADO PR is ready to be merged, the PR author adds `Approved-OkToMerge` label, then merges the ADO PR, then automation merged the GitHub PR. [Example comment](https://github.com/Azure/azure-rest-api-specs-pr/pull/12930#issuecomment-1579439459) and [a follow-up](https://github.com/Azure/azure-rest-api-specs-pr/pull/12930#issuecomment-1652543760).
> 
> Is my reasoning correct?

@konrad-jamrozik , that's correct for meaning one. Meaning two: for shift left scenario, github PR should be merged after the ADO PR is merged. So by default `donotmerge` label is added automatically and it would be removed when the bot merges the github PR automatically or the author would request for merge manually if automation not working.

**Comment by konrad-jamrozik** [comment]
Closing as completed. Addressed by:

- https://github.com/Azure/azure-sdk-tools/issues/6618

And plenty of other work.
