### ISSUE TITLE
ApiView live updates stomp pending comments

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-tools#6619]
We've been seeing a fun race condition when two reviewers comment on the same API at the same time, but you can repro it yourself in two different browser tabs:
- Alice opens an ApiView listing in one window
- Bob opens the the same ApiView in another window
- Alice sees an issue on the first line and starts working on a really long comment without submitting it yet
- Bob sees a different issue with the first line and submits a "Lol, no" comment
- **Expected**: Alice sees Bob's comment appear above the one she's writing
- **Actual**: Alice's long comment is completely replaced by Bob's comment and there's no way to recover what she wrote

**Comment by chidozieononiwu** [comment]
We have actually fixed this https://github.com/Azure/azure-sdk-tools/pull/6574
The changes have not been deployed. They likely be deployed today.
