### ISSUE TITLE
ApiView live updates jumping across reviews

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-tools#6620]
This is a really tricky one that's led to lots of confusion.  It seems the ApiView live update feature is sending notifications to every listing with a given API, not just the listing where we're adding comments.  The live updates do not persist upon refreshing the page.

- Alice opens the [Azure.Core PR #37349](https://apiview.dev/Assemblies/Review/52b58c3eb11144e383612c92c69f1f74/6f9d249df11249928f1caf8b7226151f?diffRevisionId=c53fffb104884669addf0e6c1fdfd4d2&doc=True&diffOnly=True) listing
- Bob opens a different [Azure.Core PR #35946](https://apiview.dev/Assemblies/Review/54c1aa15378b4dda9153865bb8520d5b/50c3f56679fc41bc910e7e50150e9937?diffRevisionId=d9876baa1b894d91b489bd911b4830cf&doc=True&diffOnly=True) listing
- Alice adds a comment on an API appearing in both listings
- Bob's listing updates with Alice's comment
- Bob responds to Alice's comment
- Bob refreshes the page, Alice's comment disappears, and now Bob looks like he's talking to himself when folks review this in the Arch Board.
- **Expected**: Live updates are only applied to the same ApiView listing
- **Actual**: Bob begins to question his sanity:
![image](https://github.com/Azure/azure-sdk-tools/assets/1179329/21a555b6-8aeb-4c29-8444-b380afe83bb0)

**Comment by chidozieononiwu** [comment]
This has been resolved. Changes will be deployed later this week.

**Comment by maririos** [comment]
https://github.com/Azure/azure-sdk-tools/issues/6565
