### ISSUE TITLE
Service are unable to create release plans if there is no products showing up in the drop-down list

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6639]
I would consider this a bug but it is also a gap because I don't think that we have addressed this scenario in the "Create a release plan" feature. 

We have a new service that has onboarded and they do not have a product yet.  There Private Preview is not until next year so we are engaging this team very early in the development process for the new service.

The Service Partner reviewed the updated docs and attempted to create a release plan but could not.  They contacted me for help. 

We should resolve this issue as we are allowing non-APEX teams to onboard and they will all need to create release plans.  We could run into this issue again as I am seeing more teams come to us very early (which is good that means that what we are doing is working).  :-)

**Comment by maririos** [comment]
Very interesting. Why would they want to create a Release Plan if they don't have a product to release? could you expand more on the scenario?

**Comment by ladonnaq** [comment]
This scenario is different from "no CLC action items" showing up - https://github.com/Azure/azure-sdk-tools/issues/6638.  It is still a valid scenario.  I will look to see how many services came to us in since April 2022 with this scenario this month (Jan 2024).

**Comment by ladonnaq** [comment]
Closing and will track in this issue which is duplicate - https://github.com/Azure/azure-sdk-tools/issues/7522
