### ISSUE TITLE
Service Partner cannot edit existing release plans, error when trying to create a new GA plan b/c one exist

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6667]
The Azure Content Safety PM attempted to access existing release plans created by me during our scenario testing.  She is unable to edit the release plans.  She attempted to create a new release plan and received an error.   

At this time we need to allow teams to have multiple release plans for a given type.  This is because teams will need to create new release plans for extension work.  We have not updated the Release Planner with a release plan type for extensions.  However, completing an extension will be the same steps as one of the current release plan types (Private, Public, and GA).   

Suggestion for quick fix until we begin work on the new UI for the Release Planner: 

- [x] Do not block teams from creating multiple release plans 
- [ ] Add a question/field in the Create a release plan to indicate if this is for an extension.  Then perhaps add that to the release plan type.  For example,  where it states Release Plan is public preview we could just add a something like Public Preview - extension
<img width="1191" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/67656762/b12049d2-8160-4f68-bdcb-2076a3de912c">

**Comment by maririos** [comment]
I removed the `bug` label as this is a feature request.

**Comment by maririos** [comment]
> The Azure Content Safety PM attempted to access existing release plans created by me during our scenario testing. She is unable to edit the release plans.

Why they can't edit the release plan? This shouldn't happen. If we look into this then they shouldn't create a new release plan.

Can you share the Service and Product? I can't find it from the screenshot you added here

**Comment by maririos** [comment]
I talked offline with @ladonnaq and understand the restrictions more.
I am going to look into what it means to have multiple release plans

**Comment by maririos** [comment]
@ladonnaq how do you want to do this? Why is it important to have the clarification?

>  Add a question/field in the Create a release plan to indicate if this is for an extension. Then perhaps add that to the release plan type. For example, where it states Release Plan is public preview we could just add a something like Public Preview - extension

**Comment by maririos** [comment]
For the extension part of the changes, we can use issue https://github.com/Azure/azure-sdk-tools/issues/4537.
I am leaving this issue to be about creating multiple release plans per product
