### ISSUE TITLE
Error when onboarding product

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6669]
When onboarding a service - product on the DEV environment I keep getting this exception. It happens with this specific combination, it doesn't matter the options I select:

<img width="1178" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/39580ca0-6e42-47c3-89ec-db1ad5f1c1d6">

**Comment by JonathanCrd** [comment]
This was an error in the ADO work item itself, not in the app.

The `State` field in the Work Item was set to 'Closed', which is not part of the valid options for `State`. I checked and our app does not set this value to 'Closed' in the Release Planner, it was a manual entry.
