### ISSUE TITLE
Ref docs issue 

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-tools#6679]
Error:

> ##[error]vstsOptionsAccessToken : The term 'vstsOptionsAccessToken' is not recognized as the name of a cmdlet, function, script 
> file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
> and try again.
> At line:1 char:59
> + ... CI.pull.ps1' -vstsOptionsAccessToken $(vstsOptionsAccessToken) -vstsO ...
> +                                            ~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (vstsOptionsAccessToken:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException
>  
> 
> ShallowCloning https://github.com/MicrosoftDocs/azure-docs-sdk-node
> D:\a\1\s> Git.exe -c http.extraHeader="Authorization: Basic ***" ls-remote --heads https://github.com/MicrosoftDocs/azure-docs-sdk-node main
> 1e10022ba0257623c395a23626530725307adaec	refs/heads/main
> D:\a\1\s> Git.exe -c http.extraHeader="Authorization: Basic ***" ls-remote --tags https://github.com/MicrosoftDocs/azure-docs-sdk-node main
> 
> branch exists: 1e10022ba0257623c395a23626530725307adaec	refs/heads/main, tag exists: 
> target branch exists, cloning with --branch main
> D:\a\1\s> Git.exe -c http.extraHeader="Authorization: Basic ***" clone -c core.longpaths=true https://github.com/MicrosoftDocs/azure-docs-sdk-node target_repo --depth 1 --shallow-submodules --branch main
> 
> ##[error]Process completed with exit code 0 and had 1 error(s) written to the error stream.

For more details check here:

- https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=377948&view=results

@danieljurek for notification.

**Comment by JimSuplizio** [comment]
I'm closing this. Whatever issue was happening with this step last year isn't happening anymore.
