### ISSUE TITLE
secret rotation tool should update private key for prss signing cert in service connection

### ISSUE THREAD

**Issue by benbp** [Azure/azure-sdk-tools#6681]
After running the secrets rotation tool against the prod/signing configs, it appeared to update everything except the private key for the prss signing auth cert in the service connection used for signing in our pipelines. I'm not sure if this should be automated, or not. If not, I did not see any documentation noting this as a required step. I had to find the new `azure-sdk-esrp-signing-certificate` cert generated and download+base64 encode the pfx/pem file.

https://dev.azure.com/azure-sdk/internal/_settings/adminservices?resourceId=5e347f86-8fb1-4c60-9c93-c67f7ca9517b

**Comment by hallipr** [comment]
This should be covered with the existing configuration:

https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-build-tools?path=/tools/secret-management/prod/esrp/signing/azure-sdk-esrp-signing-certificate.json

**Comment by hallipr** [comment]
Per the configuration, the tool will start a new secret version operation and wait for completion.  Once complete, it should put the base64 encoded cert into the service connection.

This won't happen if the certificate in KV is configured to auto rotate before the threshold in the tool configuration, as the tool will never see the cert as expiring within its window

**Comment by benbp** [comment]
@hallipr so was the issue here that we had the expiry timings wrong? If one secret has downstream dependencies on other secrets, how can we make sure those get updated?
