### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#6682]
Deployment pipeline to PPE is failing for the Release Planner solution.

The error has to do with the "user" not having enough privileges to access the Key Vault Subscription to retrieve the secrets for certain Env Vars

**Comment by maririos** [comment]
We are going to contact the PowerApps team to see if they can help us get unblocked here

**Comment by JonathanCrd** [comment]
This was fixed already last Monday. Our release pipelines work again.
