### ISSUE TITLE
Scheduling app should block API Stewardship review of mgmt plane API 

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6685]
The Azure Firewall team scheduled a REST API review with the API Stewardship board (data plane) and supplied a [PR for a management plane API](https://github.com/Azure/azure-rest-api-specs/pull/24638). The PR is clearly labeled "resource-manager". This problem was not discovered until the week of the review -- 2 weeks after the meeting was scheduled. We can cancel the meeting but it is like that the slot could have been used by another team but now will go unfilled. This is inefficient and could be avoided by having the scheduling tool check the linked PR for a "data-plane" label and blocking the meeting request if not present.

**Comment by maririos** [comment]
Teams are allowed to book a meeting with no PR specified. One solution could be that once they add the PR the tool verifies the `data-plane` label is added. When this is not the case, show an error that the meeting is only for data plane REST APIs.

This will only prevent people to update a meeting though. They will still have to cancel it.

What do you think?

**Comment by mikekistler** [comment]
Meetings with no PR is another constant struggle. So we could a) prevent scheduling or updating a meeting with a management plane PR, _and_, b) cancel any meeting without a PR 7 days before the scheduled meeting.

Also, we need to be clearer about using the scheduling app only for data plane REST APIs -- this wasn't obvious to the Firewall team as indicated by [this comment](https://github.com/Azure/azure-rest-api-specs/issues/24989#issuecomment-1668153965).

**Comment by maririos** [comment]
>  Cancel any meeting without a PR 7 days before the scheduled meeting.

I created issue https://github.com/Azure/azure-sdk-tools/issues/6692 .  We have logic that already does this but it was turned off a while back.

**Comment by maririos** [comment]
> Also, we need to be clearer about using the scheduling app only for data plane REST APIs -- this wasn't obvious to the Firewall team as indicated by https://github.com/Azure/azure-rest-api-specs/issues/24989#issuecomment-1668153965.

Covered by #6603

**Comment by maririos** [comment]
> So we could a) prevent scheduling or updating a meeting with a management plane PR,

Done. I ahve added logic to check the labels of the PR. Here is an exmaple of the error. This will prevent the user from scheduling a meeting:

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/705d16fa-b617-4af0-bc59-46c6dc378b9a)
