### ISSUE TITLE
[PR Workflow][PR Summary] Failed due to GitHub API rate limit

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-tools#6691]
```
error checking PR summary
RequestError [HttpError]: API rate limit exceeded
```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2985154&view=logs&j=d6a48a56-e996-55ca-2302-c3a9a7be685b&t=f4162ac4-a5be-580e-39db-db0d6209bd6a&l=70

Note added by kojamroz 7/21/2024:

Related queries for viewing and profiling GitHub rate limit telemetry:
- https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/1015/pipeline-bot-Kusto-queries?anchor=github-rate-limit-telemetry

**Comment by konrad-jamrozik** [comment]
Some insights on API rate limiting here:
- https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps/pullRequest/491153#1691976640

**Comment by konrad-jamrozik** [comment]
[Pull Request 565606](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/565606): renderUnifiedPipelineCheck only for the applicable checks (GitHub rate limit optimization)
