### ISSUE TITLE
Migrate "Azure SDK APEX launch readiness criteria" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6699]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/681/Azure-SDK-APEX-launch-readiness-criteria

**Comment by ccbarragan** [comment]
@ladonnaq has pull requests for this content. Reviewed, pending changes before merging.

- https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/835
- https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/836
