### ISSUE TITLE
Migrate "Lifecycle Requirement: API design and API readiness" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6700]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/807/Lifecycle-Requirement-API-design-and-API-readiness

**Comment by MrJustinB** [comment]
![Image](https://github.com/Azure/azure-sdk-tools/assets/105250266/889da161-7539-4adb-9fa1-1f25cd4efdda)

**Comment by ladonnaq** [comment]
Completed.

**Comment by maririos** [comment]
@ladonnaq you still need to delete the content from the previous wiki and at the top include a link to the new wiki. See as an example: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/10/Welcome-Service-Partners!

Also, the wiki has an aka.ms link that needs to be updated to the new documentation site

Reopening until that is done
