### ISSUE TITLE
Migrate "Azure SDK Extension Process (previously known as signoff with exception)" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6701]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/644/Azure-SDK-Extension-Process-(previously-known-as-signoff-with-exception)

**Comment by ccbarragan** [comment]
PR from @ladonnaq: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/835
