### ISSUE TITLE
Migrate "Lifecycle: Management Plane - Enlist in Early Swagger Live Validation" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6705]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/685/Lifecycle-Management-Plane-Enlist-in-Early-Swagger-Live-Validation

**Comment by ladonnaq** [comment]
Completed.

**Comment by maririos** [comment]
@ladonnaq you still need to delete the content from the previous wiki and at the top include a link to the new wiki. See as an example: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/10/Welcome-Service-Partners!

Also, the wiki has an aka.ms link that needs to be updated to the new documentation site

Reopening until that is done

**Comment by ladonnaq** [comment]
Done https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/685/Lifecycle-Management-Plane-Enlist-in-Early-Swagger-Live-Validation
