### ISSUE TITLE
Migrate "Lifecycle: Onboard new Product for APEX with Azure SDK team" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6706]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/683/Lifecycle-Onboard-new-Product-for-APEX-with-Azure-SDK-team

**Comment by ccbarragan** [comment]
This content is covered in https://eng.ms/docs/products/azure-developer-experience/onboard. Closing.
