### ISSUE TITLE
Migrate "Azure SDK Archboard Review" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6707]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/667/Azure-SDK-Archboard-Review

**Comment by ronniegeraghty** [comment]
Opened PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/799

**Comment by ronniegeraghty** [comment]
[Page added to Engineering Hub](https://eng.ms/docs/products/azure-developer-experience/develop/sdk-review)
