### ISSUE TITLE
Migrate "Naming for new initial management or client libraries (new SDKs)" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6708]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/821/Naming-for-new-initial-management-or-client-libraries-(new-SDKs)

**Comment by ccbarragan** [comment]
@ronniegeraghty Any updates on this item?

**Comment by ronniegeraghty** [comment]
@ccbarragan, I'm have the markdown for this page waiting to be pushed up, but I still don't know what section of our Engineering Hub Docs it should be placed in. In the wiki it is in the same section as a lot of LaDonna's Onboarding docs but I don't see any of those added to Engineering Hub yet. Should it go under the Onboarding tab as a requirement for management plane sdk releases? Or under the Develop SDKs section and if so under what sub section? I'm confused on how the layout of the Engineering Hub Docs relates to our wiki docs and where certain pages and information should be placed. It would be nice to get an idea of what each section is for so I can better understand where my content belongs.

**Comment by ronniegeraghty** [comment]
I guessed on the proper section and opened this PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/798

**Comment by ccbarragan** [comment]
> I'm confused on how the layout of the Engineering Hub Docs relates to our wiki docs and where certain pages and information should be placed. It would be nice to get an idea of what each section is for so I can better understand where my content belongs.

@ronniegeraghty Sorry about the confusion, thought we'd already chatted about the placement for this one :) 

The EngHub docs don't map 1:1 with the wiki. We created a new information architecture to better align with service partner goals and their journey with us. We have general guidance about where to place articles [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/995/%E2%9D%97%EF%B8%8FAction-Migrate-partner-docs-to-Engineering-Hub?anchor=how-do-i-get-started%3F).

**Comment by ronniegeraghty** [comment]
[Page added to Engineering Hub](https://eng.ms/docs/products/azure-developer-experience/develop/namespace-review)
