### ISSUE TITLE
Migrate "Azure REST API Stewardship Review" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6709]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/665/Azure-REST-API-Stewardship-Review

**Comment by ccbarragan** [comment]
PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/785

**Comment by ccbarragan** [comment]
https://eng.ms/docs/products/azure-developer-experience/design/api-review
