### ISSUE TITLE
Migrate "Getting started with OpenAPI specifications" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6710]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/80/Getting-started-with-OpenAPI-specifications

**Comment by ccbarragan** [comment]
This page has already been migrated to https://eng.ms/docs/products/azure-developer-experience/design/api-specs/api-openapi. Moving to done.
