### ISSUE TITLE
Migrate "OpenAPI Spec Authoring & Validation tools" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6711]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/84/OpenAPI-Spec-Authoring-Validation-tools

**Comment by konrad-jamrozik** [comment]
Parent issue:
- https://github.com/Azure/azure-sdk-tools/issues/6618

**Comment by konrad-jamrozik** [comment]
PR:
- https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/791
