### ISSUE TITLE
Migrate "Guide to design and creation of Data Plane REST API and Client Libraries" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6716]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/591/Guide-to-design-and-creation-of-Data-Plane-REST-API-and-Client-Libraries

**Comment by maririos** [comment]
Deployed: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-samples
