### ISSUE TITLE
Migrate "Track 1 management SDK migrate to Track 2 management SDK FAQ" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6717]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/669/Track-1-management-SDK-migrate-to-Track-2-management-SDK-FAQ

**Comment by ccbarragan** [comment]
@ladonnaq Is this content still needed?

**Comment by ladonnaq** [comment]
Completed.

**Comment by maririos** [comment]
@ladonnaq you still need to delete the content from the previous wiki and at the top include a link to the new wiki. See as an example: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/10/Welcome-Service-Partners!

Reopening until that is done

**Comment by ladonnaq** [comment]
Done - https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/669/Track-1-management-SDK-migrate-to-Track-2-management-SDK-FAQ
