### ISSUE TITLE
Migrate "Azure SDK Support" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6719]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/19/Azure-SDK-Support

**Comment by ronniegeraghty** [comment]
Some of the information on this page I believe falls under my umbrella but I am unsure about other parts. I can review/update/migrate information on our GitHub Issue support processes, but the other support workflows mentioned here are not something I have knowledge on.

**Comment by maririos** [comment]
@jsquire do you know if this process is still what we are doing? I know recently there was a conversation about CSS involvement and how things might change...

**Comment by jsquire** [comment]
@maririos:  I don't have insight; my understanding is that the docs migration is happening.   @lfraleigh would probably the best person to ask.

**Comment by lfraleigh** [comment]
I think this wiki page needs restructured.  I would actually separate what we do for GitHub from what we do for issues that come in through paid support channels.  Service team partners need to know everything related to GitHub. 

I question what service team partners need to know about how we handle paid support requests that come in through CSS.  The reality is if it's something we don't handle, it automatically gets transferred to their queue and they deal with it.  

And Jesse, just to be extra confusing, CSS is different from the CXP stuff.

cc @MrJustinB

**Comment by ronniegeraghty** [comment]
I made a new page that is specifically the info Service partner teams would need for handling customer GitHub issues: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-customer-support

@jsquire, we might want to link this new page when a Service Team is mentioned in an issue.
