### ISSUE TITLE
Migrate "Mgmt .NET SDK release process" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6724]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/78/Mgmt-.NET-SDK-release-process

**Comment by maririos** [comment]
Done in PR https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/874

**Comment by maririos** [comment]
Release planner has been updated to point to this new page
