### ISSUE TITLE
Migrate "Sample Directory Structure for Swagger" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6727]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/211/Sample-Directory-Structure-for-Swagger

**Comment by mikeharder** [comment]
@konrad-jamrozik: This appears to be for specs written in Swagger rather than TypeSpec, so I'm not sure if this should be assigned to me.

**Comment by konrad-jamrozik** [comment]
@mikeharder yeah don't stress over it ;) let's chat about this tomorrow. There is some extra context here.

**Comment by konrad-jamrozik** [comment]
Assigned myself too to actually do the work, or find someone responsible.

@mikeharder will chat with TypeSpec folks to see if the OpenAPI spec directory structure guidance should be somehow changed to account for new APIs generated from TypeSpec specs.

**Comment by konrad-jamrozik** [comment]
Parent issue:
- https://github.com/Azure/azure-sdk-tools/issues/6618

**Comment by konrad-jamrozik** [comment]
Note: this needs to be deduped with:

https://github.com/Azure/azure-rest-api-specs/blob/main/CONTRIBUTING.md#directory-structure

which is mentioned in EngHub:
https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms?path=docs/design/api-specs/api-specs.md&version=GC7714fb6a874732aa0626fb78660d7e6ea9f5f72f&line=51&lineStartColumn=1&lineEndColumn=128&_a=contents
