### ISSUE TITLE
Migrate "Azure Open API Spec Linter" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6728]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/636/Azure-Open-API-Spec-Linter

**Comment by konrad-jamrozik** [comment]
Parent issue:
- https://github.com/Azure/azure-sdk-tools/issues/6618

**Comment by konrad-jamrozik** [comment]
Addressed this one while working on:
- https://github.com/Azure/azure-sdk-tools/issues/6711
