### ISSUE TITLE
Migrate "Azure OpenAPI Specification Schema Validator" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6729]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/638/Azure-OpenAPI-Specification-Schema-Validator

**Comment by scbedd** [comment]
These have already been migrated by the transition of https://aka.ms/swaggertools. Click on ``ci fix guide` to get to the same information as covered in this page.
