### ISSUE TITLE
Migrate "OpenAPI Hub: Adding new API version" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6734]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/208/OpenAPI-Hub-Adding-new-API-version

**Comment by maririos** [comment]
After taking a look at this document, most of the content has already been covered in https://eng.ms/docs/products/azure-developer-experience/design/tutorial/api-tutorial-1-branch

I have decided to not migrate this doc and deprecate it. If people start asking about it, I will move it
