### ISSUE TITLE
Migrate "Request SDK Release in OpenAPI Hub" to Eng Hub

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#6736]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/336/Request-SDK-Release-in-OpenAPI-Hub

**Comment by MrJustinB** [comment]
@maririos  FYI



![Image](https://github.com/Azure/azure-sdk-tools/assets/105250266/7aa63ee2-cce1-44b9-8154-99159fec9091)

**Comment by lirenhe** [comment]
> PR is here: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/782
> 
> @lirenhe could you take a look?

Sure, left a couple of comments.  Thanks

**Comment by maririos** [comment]
PR merged and deployed: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-release?tabs=management
