### ISSUE TITLE
Tidy Up APIView Approval Requirements

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#6740]
We have a case where a GA package was releases and passed APIView approval check based in the approval of a pre-release package. See [build ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2840532&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2f6d9e30-39c7-586f-0d04-0c26aa424aa7&l=123)and [apiview created by build](https://apiview.dev/Assemblies/Review/67fd3a143d9c4f3eb8f558bd6ce85c55?revisionId=42b71f429d254bdd9de56b5213cac696&doc=False)

subsequent [run ](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2991204&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=2f6d9e30-39c7-586f-0d04-0c26aa424aa7&l=157)of the pipeline fails due to the GA package not being approved yet.

We should tidy up the workflow to prevent block like this. Should approved prerelease review mean that GA can be released without approval? If so how do we ensure the GA review is eventually approved.

**Comment by WhitShake** [comment]
Non-issue?

**Comment by WhitShake** [comment]
Not currently an issue
