### ISSUE TITLE
Document required service team attendees to API Review and SDK Archboard meetings

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#6744]
We should clearly set expectations with service teams on attendance to API Review and SDK Archboard meetings. This should be done in the scheduling tool and possibly also in the release planner.

The expectations are that the service API architect and PM are required attendees.

**Comment by maririos** [comment]
@mikeharder the scheduler contains this information:


![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/ed57377b-6e15-464e-9f61-191d1c709aec)

Are you expecting extra validation for this?

**Comment by mikekistler** [comment]
We've had some instances where this hasn't been followed. Not sure if the service team saw this and ignored it or it wasn't clear enough.

**Comment by maririos** [comment]
For sure. When you see this happening, you can ask them for more information on why this might have happened and then we can determine what to do

**Comment by mikekistler** [comment]
Could we also have this statement added to the meeting invite? And I would change "expected" to "required".

**Comment by maririos** [comment]
Added in UI:
<img width="386" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/162af87a-00a4-4cdf-ba8d-3993868b2066">

Added to email template:
<img width="752" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/27ff9458-3023-47f6-bb8e-303f22dd8233">
