### ISSUE TITLE
Update the URL link of SDK package and SDK automation run log to azure blob from openapi hub url

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#6749]
As the openapi hub adds a redirection rule for the URL access because of the network restriction. We would like to use azure blob url directly for package link and log link.

**Comment by raych1** [comment]
@lirenhe , this is the testing PR. The log link and sdk package link are prefixed with azure blob url. Clicking on it would download them directly.
https://github.com/openapi-env-test/azure-rest-api-specs/pull/3667#issuecomment-1669210304

**Comment by lirenhe** [comment]
> @lirenhe , this is the testing PR. The log link and sdk package link are prefixed with azure blob url. Clicking on it would download them directly. [openapi-env-test/azure-rest-api-specs#3667 (comment)](https://github.com/openapi-env-test/azure-rest-api-specs/pull/3667#issuecomment-1669210304)

Is it possible to use aka.ms link instead of showing the blob URL directly?

**Comment by raych1** [comment]
aka.ms link cannot be used as part of the URL then append the extra paths and query.  Changes were deployed to PROD.
