### ISSUE TITLE
How do we transition users to use the new version of the apps

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6752]
We don't want to disrupt users. how do we avoid that? how can we make sure that the links will still work?

**Comment by JonathanCrd** [comment]
We can merge the two Release Planner apps together manually using git. These are the steps to do so:

1. Add the Release Planner current app to one solution. 
2. Add the Release Planner vNEXT app to another solution.
3. Download both solutions as unmanaged.
4. Clone the Engagement Experience Repo in your local machine, and create a new branch. This branch will host the content of the "legacy" app.
5. Move to that branch in your local.
6. Move the downloaded zip file for the unmanaged Base app solution into the cloned repo folder.
7. Unzip the solution by running this command: 
   ```
   pac solution unpack -z .\<YOUR_ZIP_FILE_NAME>.zip --folder .\UnpackedSolution
   ```
   This will create a new folder named `UnpackedSolution`. 
8. Now unpack the canvas app using this command:
   ```
   pac canvas unpack --msapp .\UnpackedSolution\CanvasApps\<NAME_OF_YOUR_APP>.msapp --sources .\UnpackedSolution\CanvasApps\UnpackedApp
   ```
   This will create a new folder under CanvasApps with all the content and code of the original app. The one that we want to merge the new code into.

9. Commit and push your changes.
10. Now create a new branch based on the first one. This branch is going to host the code for the vNext version of the app.
11. Repeat steps 6 to 8.
12. Before commiting your changes, make sure to:
    1. Discard changes for `CanvasManifest.json`, `CheckSum.json`, and `AppCheckerResults.sarif`.
    1. Modify the solution xml file to upgrade the version.
13. Commit and push your changes.
14. You can review the code that will override the base app by making a PR to the first branch. If everyhting looks good. You can pack the Canvas App and the solution by running the following commands:
    ```
    pac canvas pack --sources .\UnpackedSolution\CanvasApps\UnpackedApp --msapp <NAME_OF_YOUR_APP>.msapp
    ```
    ```
    pac solution pack -z MergedSolution.zip --folder .\UnpackedSolution\
    ```

15. Then, import `MergedSolution.zip` into the environment using PowerApps web.
   Note: It might be a good idea to do a manual backup of the environment just in case.

16. Finally, open the app on edit mode and review all the changes. Some Data and Flows connections might be broken, fix it by refreshing them or removing them and adding them back to the app.

**Comment by JonathanCrd** [comment]
For the other apps, I'd recommend to make the changes on duplicated screens, since there are less changes to do and we can avoid all of the previous steps.
