### ISSUE TITLE
[PR workflow][Prettier][cSpell] Inconsistent tooling versions between `RPSaaSMaster` and `RPSaaSDev`

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6753]
Per [this Teams discussion](https://teams.microsoft.com/l/message/19:de3fce22c2994be18cac50502c55f717@thread.skype/1691686138720?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1691046400887&teamName=Azure%20SDK&channelName=Azure%20SDK%20Onboarding&createdTime=1691686138720)

Quote:

> The prettier version is supposed to be 2.1.2 (which is mentioned in the docs) but it's confusing because in the RPSaaSMaster branch the version is 2.8.8.
>
> The cSpell.json is different so the spell check validation can have different results and it make sense. 
>
> Other than that, I think that the swagger lint-diff validation was different.

**Comment by weshaggard** [comment]
Prettier tool version is now in-sync across the branches. I'm planning to do some other tools like cspell similarly but those will be tracked by other issues as we do them.
