### ISSUE TITLE
How is SDK list updated in the Onboarding screen?

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6762]
The SDKs that are presented in the `Onboarding screen` seem to not be updated? How does this work?
(BTW test where done in DEV, not sure the other environments)

For example, when looking for `Openai` no results come back, even though the azure-sdk website does list it.

Not present:
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/e9445ffd-4b0b-4461-a59c-994c571522a0)

-----
Yes in Azure-sdk website:
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/d5bb3c22-87dc-462c-b517-2efe5786c94a)

**Comment by praveenkuttappan** [comment]
This is no longer required. I have removed SDK package selection option from onboarding screen as per the discussion with PM team.
