### ISSUE TITLE
[Openapi-Diff] Removals are not reported in cross version breaking change CI check

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#6765]
This is the repro PR:
https://github.com/Azure/azure-rest-api-specs/pull/24771

In this PR, there're a bunch of removals comparing to previous version 2023-06-01-preview but they're not reported in the cross version breaking change result. such as: `ExportPipeline`, `ExportPipelineListResult`, `ExportPipelineProperties`, etc.

This issue would result in the breaking change review ignoring these changes.

**Comment by raych1** [comment]
I found they're reported as warnings. Closed this issue to confirm with Mike.

**Comment by AntonioVT** [comment]
Just to add to the discussion, those "removals" are from features that are in preview versions but are not ready to be GA'd/stable. They will be for sure included in the next preview API release.
