### ISSUE TITLE
[PR Workflow] The specs repo GH action that adds `mergeRequested` label is unreliable

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6768]
https://github.com/Azure/azure-rest-api-specs-pr/actions/workflows/comment.yml

![image](https://github.com/Azure/azure-sdk-tools/assets/4429827/e3edd1a6-c94e-41ea-8cc9-7db6ccadf5f8)

https://github.com/Azure/azure-rest-api-specs-pr/actions/runs/5852785819/job/15865587878#step:2:459

![image](https://github.com/Azure/azure-sdk-tools/assets/4429827/e4bb2f11-b353-4a7f-a4b0-2db2e6396900)

Workflow originally added in:
- https://github.com/Azure/azure-rest-api-specs/pull/25091

**Comment by benbp** [comment]
@konrad-jamrozik I've seen issues where the event body is slightly different or points to the wrong place when PRs come from forks vs origin. Is this something that could be happening, or is it just API flakiness?

**Comment by konrad-jamrozik** [comment]
@benbp I think it is just flakiness. Have a look at the first screenshot I attached in the PR description:
- https://github.com/Azure/azure-sdk-tools/issues/6768#issue-1850262992

**Comment by benbp** [comment]
Oh, I missed the `gh edit` command. Yep makes sense.

**Comment by konrad-jamrozik** [comment]
@benbp this is failing on a regular basis. Do you think that scrapping a call to `gh` and calling the underlying API directly would help?

**Comment by benbp** [comment]
@konrad-jamrozik this was the short term workaround fix? I would wrap it in some retries with backoff and see what happens.

**Comment by konrad-jamrozik** [comment]
Yes

**Comment by konrad-jamrozik** [comment]
More reports of flakiness [here](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1694718163045?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1694703455319&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1694718163045).

**Comment by JainRah** [comment]
I am also facing similar error: https://github.com/Azure/azure-rest-api-specs-pr/actions/runs/6193928660/job/16816168753

gh pr edit 14458 --add-label "MergeRequested"
GraphQL: Resource not accessible by integration (repository.pullRequest.projectCards.nodes)
WARNING: Failed to add label
Error: Process completed with exit code 1.
