### ISSUE TITLE
Migrate Package Onboarding step-by-step to Eng Hub

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6777]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/602/Package-Onboarding-step-by-step

**Comment by ccbarragan** [comment]
@danieljurek Any updates on this item?

**Comment by danieljurek** [comment]
Other PR merged. Working on this one.

**Comment by danieljurek** [comment]
Closing. This was done.
