### ISSUE TITLE
[APIView GPT] "Generate AI Review" fails and provides no info

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#6784]
![image](https://github.com/Azure/azure-sdk-tools/assets/5723682/96497904-825b-4115-8913-ef21b0b8cdc9)

This makes it impossible to understand what went wrong. Since this is the staging site, it would be helpful to display the actual error.

**Comment by chidozieononiwu** [comment]
Resolved and deployed
