### ISSUE TITLE
Test TypeSpec "next" versions across autorest and sdk repos

### ISSUE THREAD

**Issue by hallipr** [Azure/azure-sdk-tools#6788]
The "next" tagged versions of TypeSpec packages should be tested regularly in the language specific autorest repositories and the emitter packages produced should be tested in the respective sdk repositories.

**Comment by hallipr** [comment]
Per autorest repository, the general flow should be:
- Build and test autorest.{lang} (autorest repo)
  - Update package.json to point to the -dev version of all typespec dependencies by targeting each packages "next" version
  - Build and test the emitter including local generation tests
  - Publish the emitter with -dev typespec dependencies to the internal npm feed
- Regenerate and test azure-sdk-for-{lang} (sdk repo)
  - Create a branch in the sdk repo and update emitter-package.json to use the new "-alpha" version
  - Generate a regeneration job matrix
    - Collect a list of services to be regenerated
    - Split the regeneration into a set of balanced lists
    - Emit a job matrix with a leg per list
  - Regenerate services using the job matrix, pushing the changes to the new branch
  - Create a draft PR from the new branch
  - CI Builds will queue as necessary for the changeset in the PR

**Comment by hallipr** [comment]
Item 1.iii (publish to dev feed) feed target is determined by the publish script in the autorest repo. If a package wants to publish and consume alpha versions using the public npm registry, they will just need to override the feed redirection function in [TypeScript-Project-Generate.ps1](https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/TypeSpec-Project-Generate.ps1#L49-L54)

This will be made customizable with the function `Initialize-{Language}-EmitterNpmInstall` added to LanguageSettings.ps1, referenced through the variable `$InitializeEmitterNpmInstallFn` in [common.ps1](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/common/scripts/common.ps1#L62)

If the function is undefined, this default behavior will be used:
-  If the package version uses an "-alpha" prerelease tag, a .npmrc fill will be created pointing to the internal npm feed.

**Comment by lirenhe** [comment]
@hallipr,  for (2) Regenerate and test azure-sdk-for-{lang} (sdk repo);   as I know,  not all SDK have a step to regenerate all SDKs for any codegen code, which means if we detect any issue in (2), it would be difficult to tell whether this is cause by the typespec update or the codegen update.  Have you discussed plan with different SDK owners?

**Comment by hallipr** [comment]
@lirenhe, this is something that @m-nash and I have talked about.  We know that azure-sdk-for-python, and possibly other languages, don't regenerate their libraries unless the library needs a functionality update.  This would mean that over time, there will be general code generation detritus building in the repo. 

We allow the language repo to tune the generation function that's used to create the regeneration job matrix.  This would allow repos like -for-python to be selective in the projects they regenerate while still allowing repos like -for-net to regenerate all possible projects.

**Comment by hallipr** [comment]
The generic preview pipeline template is complete and language specific pipelines have been created in the c#, python, java and typescript autorest repos.
