### ISSUE TITLE
"Share this release plan with others" do not convey permissions

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#6789]
In the summary view of a release plan, there is this box:
![image](https://github.com/Azure/azure-sdk-tools/assets/1050156/2cc1255a-7f9c-4838-9160-58a6ad556b59)

If you actually share this link, you will hit permissions problem:
![image](https://github.com/Azure/azure-sdk-tools/assets/1050156/68e74ede-1c44-474f-b6bc-395f01de5ae6)

I expect since I'm able to see it, anybody I give the link should be too.

**Comment by JonathanCrd** [comment]
Fixed this on PROD, you should be able to use the link now.
