### ISSUE TITLE
I'd like to be able to update dates in the Summary view of the release planner

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#6790]
![image](https://github.com/Azure/azure-sdk-tools/assets/1050156/5f070ea2-b179-42ae-8a66-9773082cf4cb)

Would love to get the pen to edit that from the summary, like for PM:
![image](https://github.com/Azure/azure-sdk-tools/assets/1050156/81e95022-51da-4409-a8da-6cf2d1280c19)

**Comment by maririos** [comment]
FYI @JonathanCrd as you work on the new UI

**Comment by JonathanCrd** [comment]
Done, now you can edit the release target month from the summary view.
This will update our records as well as the ADO work item.
