### ISSUE TITLE
Get plan progress label clickable

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-sdk-tools#6791]
In the summary view of the release planner:
![image](https://github.com/Azure/azure-sdk-tools/assets/1050156/0ecb8d06-2a9f-4e06-910d-112cd5851a07)

I'd like the title to be clickable, like they are on the milestones view:
![image](https://github.com/Azure/azure-sdk-tools/assets/1050156/b79eb41d-0a18-4935-a6bf-c42afe81ac39)

**Comment by maririos** [comment]
Will be address as part of https://github.com/Azure/azure-sdk-tools/issues/6640
