### ISSUE TITLE
APIView "approved" status is tied to rev number

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#6793]
**Repro**
1. Create rev 0, 1 and 2.
2. Approve Rev 1.
3. Delete rev 0.
4. Voila! Now what was rev 2 is "approved"! 

**What should happen**
After steps 1-3, rev 0 should be approved and rev 1 (formerly rev 2) should not

**Comment by WhitShake** [comment]
Completed no longer an issue
