### ISSUE TITLE
Make SDK generation check required and can be suppressed by labels.

### ISSUE THREAD

**Issue by qiaozha** [Azure/azure-sdk-tools#6847]
In this PR, https://github.com/Azure/azure-rest-api-specs/pull/24606 the JS SDK generation is failed and currently we have no way to block PR like this to get merged and because of SDK generation is failed, we don't know whether this PR has SDK breaking change or not. As breaking change detection happens after a success generation.

I hope we can make the SDK generation as required check, and it can be suppressed by add some specific labels. 

I think we can make JS, Go, Python, Java as required. As dotnet is failing most of the time, we probably should make it optional.

**Comment by raych1** [comment]
Dup with https://github.com/Azure/azure-sdk-tools/issues/6509
