### ISSUE TITLE
[Breaking Change] Breaking change presence should not always result in a required review

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#6859]
As currently written here:
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/1009/Breaking-Change-Detection-Rules

> This document will describe which conditions detected by the breaking change tooling should be flagged for breaking change review.
> 
> The following SHOULD be labeled for review:
> 
> - Any "error" condition relative to a prior GA version.
> 
> The following SHOULD NOT be labeled for review:
> 
> - Any condition that is not relative to a prior GA version.
> - Any PR that is not to a "production" branch -- "main" in the public repo or "RPSaaSMaster" in the private repo.

Specifically the problem is that right now, if breaking change check detects an issue, it adds a label `BreakingChangeReviewRequired`or `NewApiVersionRequired`. In addition, the check is `required` in GitHub.

But going forward we don't want that: sometimes there is a breaking change, but it is OK, hence no need for official breaking change review. We need to figure out how to surface / communicate it.

Note that sometimes the check fails to add the labels. If so, this is most likely #6169.

There is also ongoing discussion about "self-approval" in the email thread `Subject: FW: Need help in a false positive breaking change check in a API Spec PR`.

Related email threads:
- `Subject: Re: Adding new POST action to swagger is causing BreakingChange check to fail.`
  > This check does not apply to private previews.  But our tooling flags it because it has no way to 
    know when a preview API version is in private preview or public preview.
    We are planning an improvement to the process that will allow a service team to “self certify” 
   that the API version is in private preview and thus “auto approve” the change.

- `Subject: RE: breaking changes detected in PR `
- `Subject: FW: Need help in a false positive breaking change check in a API Spec PR`
- `Subject: RE: Please approve the breaking changes of HDInsight private preview service`

Related work:
- https://github.com/Azure/azure-sdk-tools/issues/5838
- https://github.com/Azure/azure-sdk-tools/issues/6374

**Comment by konrad-jamrozik** [comment]
Reopening the issue as I realized there is one complexity to consider. 

While the `BreakingChangeReviewRequired` and `NewApiVersionRequired` labels will no longer be added where they shouldn't, the "breaking change" checks are still `required` on the repos GitHub branch policies, so they will block PRs from being merged per [`getRequiredAndAutomatedMergingRequirementsMetCheckRuns`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-kebab/src/bots/pipeline/pipelineEventListener/getRequiredCheckRuns.ts&version=GCa0b6fac2fa92c17ce2fe394068a3ae9cd6e5a2bd&line=13&lineStartColumn=23&lineEndColumn=77&_a=contents), and hence will require `Approved-BreakingChange` label as explained in https://aka.ms/azsdk/pr-suppressions. Not every spec author has permissions to add such labels. Albeit perhaps we may want to give them such option, as we plan to give PR authors more leeway anyway, per #7354. They could possibly do it the way they can add `MergeRequested` label, as implemented in [this PR](https://github.com/Azure/azure-rest-api-specs/pull/26630/files).

Alternatively, I could modify the implementation so that if the relevant labels are not added, relevant required checks to not fail in the first place, but e.g. end up `neutral`. But I don't like it, as I believe this would be a confusing messaging.

**Comment by konrad-jamrozik** [comment]
I had a conversation with @weshaggard. The way we want to approach it is to make the breaking change checks be no longer `required` on GitHub on all the branches except these two that require breaking change board review. As a result, there won't be any need to add `Approved-BreakingChange` label anywhere. As Wes said, having people add `Approved-BreakingChange` would teach the PR authors bad habits.

We are also considering stopping the breaking change checks even running on all the branches except these two that require breaking change board review. This means any PRs to dev branches will no longer provide any information about potential breaking changes, but perhaps this information is not that useful anyway.

**Comment by heaths** [comment]
If GitHub's required checks feature isn't expressive enough, we do have that "Required validation" bot that could treat it as required - the one that lists checks / other issues that need to be addressed. That bot - as a check? - is required itself, so if it's not happy the PR can't be merged. Might be easier to keep all the "what's required" stuff centralized via that bot; though, GitHub's required checks icon is pretty nice. That said, in my experience, not a lot of spec authors seem to pay attention to it anyway. I often, as a review, have to point out the failures before it can be approved/merged.

**Comment by heaths** [comment]
It might also be a good time to check out the new ruleset feature I mentioned to @weshaggard. These are a superset of branch rules, and you can define multiple matching branch names / patterns. It doesn't solve the problem as much as makes it easier to apply the same branch rules to numerous branches, so you could easily have a "production" ruleset (or whatever you want to call it) and a "development" ruleset that doesn't require the breaking change build.

I've used it in one or two repos if I want me to give a quick tour / comparison.

**Comment by konrad-jamrozik** [comment]
Per another chat I had with @weshaggard I executed on [this plan](https://github.com/Azure/azure-sdk-tools/issues/6859#issuecomment-1832674821). Audit log of my changes to GitHub branch protection rules:

https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/1029/Changelog-GitHub-branch-protection-rules

This closes this work item.
