### ISSUE TITLE
Deprecate live validation error detail page in openapi portal

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6880]
Deprecate live validation error detail page in openapi portal, e.g. https://openapihub.azure-devex-tools.com/amekpis/correctness/detail?errorId=4CAA5994-A2D3-473F-82ED-3AE5B319ECBA

**Comment by maririos** [comment]
PR: https://devdiv.visualstudio.com/DevDiv/_git/openapi-portal/pullrequest/512197?_a=files

**Comment by JonathanCrd** [comment]
PR: https://devdiv.visualstudio.com/DevDiv/_git/openapi-portal/pullrequest/512197
