### ISSUE TITLE
Error when onboarding in PPE 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6888]
Yoga and I are testing the data aggregation model implementation and we saw this error.  When we de-selected the field to identify existing SDKs, we did not see the error.  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/a4e8fffb-fb97-4afd-851c-554fe8128513)

**Comment by maririos** [comment]
We need to revisit all the logic for this SDKs....

**Comment by maririos** [comment]
Same issues as https://github.com/Azure/azure-sdk-tools/issues/6961
Clossing as dup
