### ISSUE TITLE
Work with ARM and redmond engsys team on the swagger s360 KPI deprecation work

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#6893]
Here're the break down tasks. This task is used to track the communication with stakeholders and the tasks except the last one of resource cleanup.

•	Disable the flag in ARM frontdoor code to call live validation service       [@Ray Chen](mailto:raychen@microsoft.com) [Done]
•	Shutdown live validation service, azure stream analytics jobs, and azure functions     [@Ray Chen] (mailto:raychen@microsoft.com)  [Done]
•	Deprecate live validation error detail page in openapi portal, e.g. [https://openapihub.azure-devex-tools.com/amekpis/correctness/detail?errorId=4CAA5994-A2D3-473F-82ED-3AE5B319ECBA](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fopenapihub.azure-devex-tools.com%2Famekpis%2Fcorrectness%2Fdetail%3FerrorId%3D4CAA5994-A2D3-473F-82ED-3AE5B319ECBA&data=05%7C01%7Craychen%40microsoft.com%7Cdb18244283de45ab5b3908dba8ff7182%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638289587386423240%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G%2BeI18NCj9LpQIgeTCldI15xQJmDZF7Go%2BhhWmYU%2FXg%3D&reserved=0) Mariana Rios Flores
•	Notify devdiv data team for the retirement of AME data store        Wes Haggard  [Done]

•      Archive the live validation service and enumerator service repos  [Done, I deleted all the code and disabled the pipelines]

•	Delete related azure resources including aks cluster, asa jobs, storage accounts, appInsights, event hubs, secrets in key vault, etc.              [@Ray Chen](mailto:raychen@microsoft.com)  [Done for TEST and PPE]

**Comment by maririos** [comment]
>Deprecate live validation error detail page in openapi portal

https://github.com/Azure/azure-sdk-tools/issues/6880

**Comment by raych1** [comment]
ARM deployment of the change is targeted at 9/22.

**Comment by lirenhe** [comment]
close it as resolved
