### ISSUE TITLE
Update aka.ms links to point to Engineering Hub

### ISSUE THREAD

**Issue by ccbarragan** [Azure/azure-sdk-tools#6896]
Update the following links to point to the appropriate page in Engineering Hub. If a relevant page doesn't exist, [determine whether the content belongs in Engineering Hub](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/995/%E2%9D%97%EF%B8%8FAction-Migrate-partner-docs-to-Engineering-Hub), and if so open a follow-up issue to migrate your content.

>If I tagged you incorrectly, or if you're not the owner of the aka.ms link, please help us and tag the correct owner :) You can find a link owner by using the [aka.ms](https://aka.ms) hub.

#### aka.ms links to update

- [x] https://aka.ms/azsdk/onboard @ladonnaq 
- [x] https://aka.ms/azsdk/apex/launch-criteria @ladonnaq 
- [x] https://aka.ms/azsdk/APEX/exception @ladonnaq 
- [x] https://aka.ms/azsdk/onboard/office-hours @ladonnaq 
- [x] https://aka.ms/azsdk/onboarding/informational @ladonnaq 
- [x] https://aka.ms/azsdk/onboarding/restapischedule @mikekistler 
- [x] https://aka.ms/azsdk/onboarding/archboardschedule @ronniegeraghty 
- [x] https://aka.ms/azsdk/releases/partnerinfo @ladonnaq 
- [x] https://aka.ms/azsdk/release-checklist @czubair 
- [ ] https://aka.ms/azsdk/publishsdk  (owner is laurent and adpleads. docs page in Azure Devops, should it be moved to engineering hub?)
- [ ] https://aka.ms/azsdk/mark-release-status @czubair  (Docs page in Azure Devops, should it be moved to engineering hub?) 

#### aka.ms links to delete
- [x] https://aka.ms/azsdk/engage @ladonnaq 
- [x]  https://aka.ms/azsdk/APIreadiness @ladonnaq
- [x] https://aka.ms/azsdk/onboarding/APEX/privatepreview/APIreadinessLC @ladonnaq 
- [x] https://aka.ms/azsdk/APEX/GA/management-SDK-release-readiness @ladonnaq 
- [x] https://aka.ms/azsdk/apex/publicpreview/dataplane/requirements @ladonnaq 
- [x] https://aka.ms/azsdk/onboarding/dpinfomeeting @ladonnaq

**Comment by ccbarragan** [comment]
@ladonnaq We still have several aka.ms links that haven't been updated. Can you update so that they point to Engineering Hub? ([Conversation in Teams meeting](https://teams.microsoft.com/l/message/19:meeting_NTg4Y2Q3Y2ItMGM3OS00YjAzLTk3ZTItYTRjMDUyZWU0M2Nk@thread.v2/1696615016966?context=%7B%22contextType%22%3A%22chat%22%7D))

**Comment by ladonnaq** [comment]
@maririos I will either delete or update any aka links that I own in Jan 2024.

**Comment by maririos** [comment]
@ladonnaq could you update when is the ETA for this work?

**Comment by ladonnaq** [comment]
> @ladonnaq could you update when is the ETA for this work?

I am just getting around to looking at the docs GitHub issues.  I will take care of either updating aka links or deleting if we no longer need them.

**Comment by ladonnaq** [comment]
@maririos - 2 links remaining but the docs pages are still in Azure Devops. I was not sure if there was a reason they needed to stay in Azur Devops. So wanted to confirm before I created PRs to start a draft to move them to engineering hub.  

- [ ] https://aka.ms/azsdk/publishsdk (owner is laurent and adpleads. docs page in Azure Devops, should it be moved to engineering hub?)
- [ ] https://aka.ms/azsdk/mark-release-status @czubair (Docs page in Azure Devops, should it be moved to engineering hub?)

**Comment by ladonnaq** [comment]
> @maririos - 2 links remaining but the docs pages are still in Azure Devops. I was not sure if there was a reason they needed to stay in Azur Devops. So wanted to confirm before I created PRs to start a draft to move them to engineering hub.
> 
> * [ ]  https://aka.ms/azsdk/publishsdk (owner is laurent and adpleads. docs page in Azure Devops, should it be moved to engineering hub?)
> * [ ]  https://aka.ms/azsdk/mark-release-status @czubair (Docs page in Azure Devops, should it be moved to engineering hub?)

Nevermind I found the GitHub issues.  https://github.com/Azure/azure-sdk-tools/issues/7037 and https://github.com/Azure/azure-sdk-tools/issues/7036.

**Comment by ladonnaq** [comment]
> Thank you @ladonnaq :) I also added the specific link to update in the respective issues. We can close this!!!

Thanks @maririos!
