### ISSUE TITLE
Bug - Getting error that Info Meeting must be complete before creating data plane release plan  

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6901]
In testing the implementation of the new data plane aggregation model, we have encountered a bug.  I am not sure where the release planner is "reading" the value for if Info Meeting is complete but when the data fields are updated in the new triage work items, I would expect that is where the release planner is "reading" the value.  

Link to the triage work item created in PPE - https://dev.azure.com/azure-sdk/Release/_queries/edit/17951/?triage=true
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/885663c2-7539-4e4b-848c-3d9c0420215f)

**Comment by maririos** [comment]
Did you try going back to Welcome or refresing the app and then trying to create a release plan again?

**Comment by maririos** [comment]
We are parsing the fields with `Text(...)` but something else must be happening here as double clicking the button works

**Comment by maririos** [comment]
Problem found and fixed
