### ISSUE TITLE
DataScope and MgmtScope missing from the epic product type work item

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#6902]
In testing we noticed that the DataScope and MgmtScope field was missing from the product details page of the epic work item template. 

When a release plan is created, the values for DataScope and MgmtScope from the triage work item should be the values of the fields in the epic work item.  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/678acaed-6c66-4eeb-ab44-b4ef9705ebab)

**Comment by maririos** [comment]
> When a release plan is created, the values for DataScope and MgmtScope from the triage work item should be the values of the fields in the epic work item.

How do we know this information? According to the field they selected when onboarding? 

![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/17fae87d-eb6b-4ba9-95c8-b170d28e625b)

**Comment by maririos** [comment]
Added
