### ISSUE TITLE
Bug: The Info Meeting State is not being updated in the triage work item

### ISSUE THREAD

**Issue by yogananda0517** [Azure/azure-sdk-tools#6908]
**Scenario Tested:** Onboard a product, Date plane scope is YES, Management plane scope is NO

**Expected Result:** Information Meeting State should be auto-populated with the value "REQUIRED"

**Actual Result:** Information Meeting State is not auto-populated and field is blank

![image](https://github.com/Azure/azure-sdk-tools/assets/138707803/680fcd15-7e0c-4c99-9cc7-9ca496d09398)

**Comment by maririos** [comment]
Updated
