### ISSUE TITLE
Summary field for onboarded product is displayed bank.  This is the description field in service tree product information. 

### ISSUE THREAD

**Issue by yogananda0517** [Azure/azure-sdk-tools#6911]
Scenario Tested: Onboard a product, Summary information should be auto populated from the Service Tree into the Summary field of the Onboarded product

Note:  This is the description field in service tree product information. 

Expected Result: Summary information should be auto-populated from Service Tree

Actual Result: Summary information is not auto-populated from Service Tree and Summary information field is displayed as blank

Work Item details: https://dev.azure.com/azure-sdk/Release/_workitems/edit/17969
Environment	PPE
Application	Release Planner
User	Release Planner Admin
URL	https://aka.ms/ppe-sdk-workflow
Triage Query	Triage Query - All - Boards (azure.com)
URL	https://dev.azure.com/azure-sdk/Release/_queries/query/7d782fac-ed04-4f9d-86c1-06fc3078a890/?fullScreen=true

![image](https://github.com/Azure/azure-sdk-tools/assets/138707803/d7a5b3bb-64f3-47e2-84ae-395cffa9dbd2)\

**Comment by maririos** [comment]
We have the information about the service, so what I am doing now is to add the description for when the service doesn't have a product.

For a product, we don't have this information in our DB. We have the service one though. @ladonnaq do you want me to look if we need to see how to fetch the description for the product from Service Tree?
This is not a regression so it will be a new feature .

**Comment by maririos** [comment]
After looking at Service Tree, there is no description for product. only for service. Closing issue
