### ISSUE TITLE
Bug: RPaaS is YES but only data was in scope.

### ISSUE THREAD

**Issue by yogananda0517** [Azure/azure-sdk-tools#6912]
Scenario Tested: RPaaS is YES but only data was in scope.

Expected Result: RPaaS field should be No since only data was in scope.

Actual Result: RPaaS field is displayed with value Yes even though only data was in scope.

Login and Details:

Environment	PPE
Application	Release Planner
User	Release Planner Admin
URL	https://aka.ms/ppe-sdk-workflow
Triage Query	Triage Query - All - Boards (azure.com)
URL	https://dev.azure.com/azure-sdk/Release/_queries/query/7d782fac-ed04-4f9d-86c1-06fc3078a890/?fullScreen=true

![image](https://github.com/Azure/azure-sdk-tools/assets/138707803/a0fd12cf-3a15-4a84-91a8-158a0339ebc0)

**Comment by maririos** [comment]
default value has been set to `No` .
I wonder, did you change the product before trying again to onboard? what was the flow you used?
