### ISSUE TITLE
Identify what is the API Spec definition type of a PR providing during onboarding

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6932]
If a pull request is provided during onboarding,  it will be good to determine if the API Spec is defined in TypeSpec or OpenAPI.  Then once determined, automatically update fields of the work item type "Triage":
- Triage Data API Spec Definition Type
- Triage Mgmt API Spec Definition Type

For now, the service/product team or the PM team can update that value manually in the work item

**Comment by maririos** [comment]
This should also apply to the API Readiness apps. When the PR is provided, check the type, use it for the API Spec work item.

**Comment by maririos** [comment]
The automation we wanted to use in the specs repo is not 100% reliable so I am going to move this issue out of this release

**Comment by maririos** [comment]
Automation work ahs been merged and deploy https://github.com/Azure/azure-sdk-tools/issues/5917. We can try this again :)

**Comment by praveenkuttappan** [comment]
API Spec definition field in Triage and API-Spec work items are updated as TypeSpec or OpenAPI based on the PR.
