### ISSUE TITLE
Update the State of the Release plan workitem as the release plan state changes in the app

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6940]
Release plan:
- Created -> "Not Started"
- API Readiness app opened, the state of the Release plan changes to "In progress" so the Release plan WI needs to be "In Progress"
- Finished -> Same as above but with finished
- Abandoned (right now this is manual. If this happens, both release plan and WI need to be updated)

**Comment by praveenkuttappan** [comment]
Created a new cloud flow `Automated Release Plan Sync State` to sync the status changes from Dataverse to work item so it handles all scenarios including manual change to `Abandoned`
