### ISSUE TITLE
Update-DocsMsMetadata.ps1 should only update metadata if released package is later version

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#6943]
Only write the metadata JSON file if the releasing version is later than the released version (i.e. check the version in the metadata.json file for the expected moniker). 

1. If metadata JSON file already exists for moniker: 
    1. If releasing version is later than the metadata JSON file version: update
    2. Else: do nothing
2. Else: create the metadata JSON file for the releasing version

**Comment by JimSuplizio** [comment]
CC @weshaggard, @kurtzeborn

Just so we're very clear, this a Learn docs problem as GitHub.IO has docs for each and every released version.

This is not the right course of action and I'm not even sure there is one. Here's the problem; There are times when a second version of a library is in development, with a higher version than the currently recommended one. This doesn't mean that the second library's version is Beta and the first's version is always GA, as there are, and have been, minor version Betas released for the first. I can speak for Java in that Core, Identity and KeyVault libraries are just a few of the libraries that have done this.

Right now, Learn docs just kind of flip/flop between these versions depending on what was last released before the respective language repository's docs main is merged into live. Changing this script to only ever use the highest version is not the right move as we don't know which version of the library should be documented on Learn. Further, even if we added a mechanism for someone to choose at release time, that would require people paying attention which is also not something I'd bank on. I suggest closing this out as "not planned" and leaving things as-is.

**Comment by danieljurek** [comment]
The scenario that this targets is one of hotfix releases. Hypothetically: 

1. Release azure-storage-blob at v1.2.3 -- Docs site shows docs at v1.2.3
2. Release azure-storage-blob with new features at v1.3.0 -- Docs site shows docs at v1.3.0
3. Major issue discovered in v1.2.3, release hotfix v1.2.4 -- Docs site now shows v1.2.4 instead of v1.3.0 

In step 3 the docs site now shows documentation for v1.2.4 instead of docs for v1.3.0 (new features from step 2 are now missing). 

This would be done on a per-moniker basis so a new beta package which supersedes a released GA package would not overwrite documentation. 

After chatting w/ @JimSuplizio I agree that this should just be documented because it's possible for a new beta version of a package silently superseding all other published versions even if it's abandoned.

The real fix here is to have all versions of docs available on a docs site (i.e. github io docs).
