### ISSUE TITLE
Parallelize asset checkout

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-tools#6953]
We should add the ability for Test Proxy asset checkout to check out assets in parallel. Possibly make this configurable between synchronous and parallel based on the number of unique assets that need to be fetched.

**Comment by benbp** [comment]
Java core, for example, does 91 restore operations. Clone times take around 1-2 seconds, and fetch + checkout times take the same (with some exceptions like fileshare/blob which take 5-13 seconds for checkout since the recordings are larger).

We could reduce the time here dramatically if we cached the initial clone and added some concurrency:

1. clone once in some parent cache location and copy the .git directory from the cache to the asset location (e.g. add a `--clone-cache` flag to `restore` in CI or something)
3. fetch refs for each asset in parallel (with batch size)
4. checkout recordings for each asset in parallel (with batch size)

**Comment by benbp** [comment]
Ah, java is a bit unique in that they frontload the test proxy restore. So this issue is java specific. https://github.com/Azure/azure-sdk-for-java/blob/main/eng/pipelines/templates/steps/restore-test-proxy-recordings.yml

**Comment by scbedd** [comment]
We do. That's why you're facing problems.

**Comment by scbedd** [comment]
> Java core, for example, does 91 restore operations. Clone times take around 1-2 seconds, and fetch + checkout times take the same (with some exceptions like fileshare/blob which take 5-13 seconds for checkout since the recordings are larger).
> 
> We could reduce the time here dramatically if we cached the initial clone and added some concurrency:
> 
> 1. clone once in some parent cache location and copy the .git directory from the cache to the asset location (e.g. add a `--clone-cache` flag to `restore` in CI or something)
> 2. fetch refs for each asset in parallel (with batch size)
> 3. checkout recordings for each asset in parallel (with batch size)

This is something that we can definitely do. I see where you're coming from with this change.

**Comment by benbp** [comment]
@scbedd I think if we move the restore operation into the test framework, like the other languages do (or maybe java already does this), then it's all done in parallel and we should gain a few minutes? But only if test proxy does its own sort of caching of the refs.

**Comment by scbedd** [comment]
> @scbedd I think if we move the restore operation into the test framework, like the other languages do (or maybe java already does this), then it's all done in parallel and we should gain a few minutes? But only if test proxy does its own sort of caching of the refs.

I've actually come full circle. The proxy supports parallel asset checkout. In Azure/azure-sdk-for-java#36792 we removed the script that runs prior to test start.

All java tests run in parallel.

For each of those `startPlayback` commands, there is a server thread handling the incoming request.

If two requests are for different assets.json files, they will be _restored in parallel_. We only force the `git` process interacting with the recordings to an individual handler _per asset directory_ to prevent conflicts/weirdness.

**Comment by benbp** [comment]
I think we can close this now, the issue was specifically about the script that has now been removed (see above comment).
