### ISSUE TITLE
Show only diffs in APIView for easier review of changes

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#6960]
When the API Stewardship Board is reviewing new API versions in APIView, it would be very productive to have a toggle that shows only the differences, even expanding them if possible - or perhaps that's a separate gesture.

**Comment by heaths** [comment]
Could this be a dup of #3640, or just similar? I looked before I opened this but didn't see anything like that, oddly.

**Comment by maririos** [comment]
> Could this be a dup of https://github.com/Azure/azure-sdk-tools/issues/3640, or just similar?

That issue is to increase the scope of the diff that we are showing. 

Fow swagger specifically we disabled that option https://github.com/Azure/azure-sdk-tools/issues/6254 . @chidozieononiwu  do you remember why?

This is still a good ask though so I want to keep this issue open

**Comment by chidozieononiwu** [comment]
It show only diff was not implemented for Swagger. Was not a natural fit

**Comment by maririos** [comment]
For all other languages, they will get this when they move to Tree token style parser
