### ISSUE TITLE
Scenario Tested: Onboard a product by selecting the SDK Package and verify the confirmation message on screen

### ISSUE THREAD

**Issue by yogananda0517** [Azure/azure-sdk-tools#6961]
Scenario Tested: Onboard a product by selecting the SDK Package and verify the confirmation message on screen

Expected Result: Product should be onboarded and confirmation message should be displayed

Actual Result: Product is onboarded, confirmation message is displayed along with error message "Network error when using Patch function:  You dont't
have permission to create this row

Details:

DevOps Product details: https://dev.azure.com/azure-sdk/Release/_workitems/edit/18663

Environment: PPE
Application: Release Planner
User Release Planner Admin
URL https://aka.ms/ppe-sdk-workflow
Triage Query Triage Query - All - Boards (azure.com)
URL: https://dev.azure.com/azure-sdk/Release/_queries/query/ad5e9f2c-725f-4c19-a99b-c5ab86536fc3/

![image](https://github.com/Azure/azure-sdk-tools/assets/138707803/3eabad66-b6fe-4430-97dc-dca57bfadc73)
![image](https://github.com/Azure/azure-sdk-tools/assets/138707803/1a9e82d0-367d-4394-9609-4708cd1ed86d)

**Comment by praveenkuttappan** [comment]
Removed package selection option and we no longer need to save SDK packages in data verse when onboarding a product to release plan.
