### ISSUE TITLE
New Release Planner UX feedback

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6977]
### Help

- [x] Format - Unnecesary caps

<img width="170" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/920b46f5-1cab-4e98-bf59-8af0ed5a1c5e">

- [x] Should be `Report a bug`

<img width="236" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/08f14dec-522f-47de-b9d6-f69205016f9c">

- [x] Should be:

- Open a GitHub issue
- Post in Teams channel (same for the help text here `Teams channel`

### Dashboard

- [x] Does the `Good morning` thing changes according to the browser time fo the user?

<img width="971" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/bd66c8e1-c2ca-4776-b874-7a65179d6e55">

- [x] I think it should be `Last modified` 

### Your release plans

<img width="516" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/cf402a7f-1f44-4afe-b340-dddf24c4b88a">

- [x] `REST API scope`
- [x]  If there is no Release SDK (private preview) then we shouldn't allow the user to be able to change the release date:

<img width="223" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/db2d2c61-7e96-4fc5-a0d2-cb4c31290fa2">

### Release ...

- [x] Diagram not loading. I copied the release plan link and opened in a new tab and that is when it didn't load:

<img width="480" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/489cb05d-4a5b-455c-9bc6-a4bde30ad7ad">

**Schedule a review ui** 

- [x] We can improve the text to `View or schedule meetings with the Azure SDK PMs, the Azure API stewardship board, and the SDK review board for the current release plan.`

<img width="570" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/87599ccd-6172-4e74-a850-42368905e4d8">

- [x] Reviews are not showing up after scheduled. For example I scheduled an API review. I had to get out of the Release plan and click it again. Maybe this is ok for now but calling it out just in case:

<img width="922" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/fb597689-2a85-419e-b810-db624a3519d8">

<img width="769" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/468ebb97-d7f3-49d6-909b-3cf5fab69c30">

### Onboard your product

- [x] Link to docs should be https://eng.ms/docs/products/azure-developer-experience/onboard
- [x] I would consider changing `API` to `REST API`. so for example `REST API details`.

<img width="567" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/a2046f77-a88a-41e2-85d1-8487c90233d7">

- [x] I was expecting that by clicking `I am not sure` that everything else was going to get unchecked. it is confusing otherwise.
- [x] `Azure REST API specs repositories`
<img width="393" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/e545cf22-1ed3-446a-aee8-6f9ba6f7dd32">

- [x] Consider removing the text `Check all boxes that apply` as there is only one box
 
<img width="241" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/08db6e01-e900-4b60-b6b3-6fa8b382fd40">

- [ ] #6984

<img width="446" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/1ea12234-aed1-4df9-92df-4fba2deb71d5">

- [x] Should we check this is a valid PR?

<img width="439" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/5d6d1022-8ae7-4cc5-88b6-44edc025d860">

- [x] Uncheck management plane and RPaaS is automatically checked 
<img width="494" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/3895c1b2-1f3f-4455-8516-4f4225c46216">

- [x] Error when onboarding a product (looks like the tittle was empty? I selected a Service that didn;'t have a product):
<img width="1007" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/5201acb8-c912-4a46-bf25-f59cb63df7e3">

I still got the prompt to schedule an informational meeting (I selected unsure). I would expect this to not happen if there was a failure

- [x] When we onboard a product that says Yes to Data plane, the triage field `Info meeting State` needs to have value `Required`. I added this code and idk if I missed the comment or it got lost in the move to the new UI

### Create a release plan

- [x] I selected a product that had informational meeting completed. Then, instead of hitting next, I checked another product. The informational check still said completed (prob a cached variable):

<img width="613" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/e68c592f-bf34-4e9c-b0ef-6cb2c909ccf5">

- [x] Text doesn't fit:
<img width="718" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/7e289fb0-f91f-43cc-acf5-632389088bb2">

- [x] Spelling: `supported`:
<img width="730" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/eb9c5f80-81b4-4a8b-b4b5-9ea32cae4c2e">

- [x] The Release plan work item created link is incomplete. Looks like it is missing the ID of the release plan:
*update*: I tried it again and I can see it. I wonder if this only fails for Private preview....
<img width="511" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/0458388b-4884-4093-9af2-1bf914db812e">

- [x] SDK Release month is not populated on the release work item:
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/4a6ae5fe-c36d-4df4-ac59-ef1a0d94c0f1)

- [x] I shouldn't be able to select past dates:
<img width="509" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/bb06c9d6-e974-4a6f-9ff4-27549e34f32c">

### Settings

- [x] Swap buttons? In all other windows I see `save` on the right:
<img width="911" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/8f3e7b41-eb3e-41b9-b987-3e6baf6d2674">

**Comment by JonathanCrd** [comment]
>  Does the Good morning thing changes according to the browser time fo the user?

It does: Good Morning / Afternoon / Evening

>  Diagram not loading. I copied the release plan link and opened in a new tab and that is when it didn't load:

This is a weird visual bug; I have to investigate more why it's not showing up

>  Reviews are not showing up after scheduled. For example I scheduled an API review. I had to get out of the Release plan and click it again. Maybe this is ok for now but calling it out just in case:

I added a "refresh" button, so user don't have to reload the page

**Comment by JonathanCrd** [comment]
>  Consider throwing error if the user checks the checkbox but doesn't provide the SDKs

Instead of throwing an error, I can prevent them from continuing to the next step. Just to be sure, if they click this button, then they *must* provide the published SDKs list too?

**Comment by maririos** [comment]
> > Consider throwing error if the user checks the checkbox but doesn't provide the SDKs
> 
> Instead of throwing an error, I can prevent them from continuing to the next step. Just to be sure, if they click this button, then they _must_ provide the published SDKs list too?

hmm now I am doubting... feature wise I think u are right. they shouldn't be able to continue if they don't say which SDKs. The problem is that the current list is not working very well.... (we haven't look into it but there is an issue for it).. so idk...

... ok, let's allow them to check and not select SDKs. until we fix the bug.

**Comment by JonathanCrd** [comment]
>  Should we check this is a valid PR?

Yes! I added the same validation we're doing in the API Readiness app, plus the extra option "N/A" which the PM uses sometimes for onboarding. This is what it looks like now:
![image](https://github.com/Azure/azure-sdk-tools/assets/17486462/2b340eb0-6314-47d5-b51e-32277e65290e)

**Comment by JonathanCrd** [comment]
> Error when onboarding a product (looks like the tittle was empty? I selected a Service that didn;'t have a product):image
I still got the prompt to schedule an informational meeting (I selected unsure). I would expect this to not happen if there was a failure

@maririos can you give me more details on how to replicate this problem? Did you tried to onboard a service (service with no products)?

**Comment by maririos** [comment]
>  Did you try to onboard a service (service with no products)?

Correct

**Comment by JonathanCrd** [comment]
>  When we onboard a product that says Yes to Data plane, the triage field Info meeting State needs to have value Required. I added this code and idk if I missed the comment or it got lost in the move to the new UI

Added this logic back. Just one question, does it also apply when updating existing work items?
For example, if the value was `Completed` but then the service team onboards again and overwrite it, should it be set to `Required` again? or should I keep `Completed`?

**Comment by maririos** [comment]
> > When we onboard a product that says Yes to Data plane, the triage field Info meeting State needs to have value Required. I added this code and idk if I missed the comment or it got lost in the move to the new UI
> 
> Added this logic back. Just one question, does it also apply when updating existing work items? For example, if the value was `Completed` but then the service team onboards again and overwrite it, should it be set to `Required` again? or should I keep `Completed`?
> 
> Right now is overwriting it to `Required` no matter what value had.

@ladonnaq could you help answer this question?
