### ISSUE TITLE
Show a quick snapshot of the release plans 

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#6993]
This is feedback I got from the new release planner UI:

> Under the plans tile [...] it might be interesting to visualize, maybe it's like a pie chart or something, the different status of each of the plans. [...] maybe show like 2 release plans are in this state and 1 release plan in in this state... just a little way to bring more color and visualization to the dashboard.

For context, this is what the person is referring to. (Ignore the number, it is unrealistic that a true service will have that many release plans)
![image](https://github.com/Azure/azure-sdk-tools/assets/17486462/7c0415e5-d115-4512-bc52-fb3ae3a024a4)

I like this idea, but I'm not sure of how to avoid duplication considering that we have the Progress view where the app shows the top seven recently updated release plans:

![image](https://github.com/Azure/azure-sdk-tools/assets/17486462/3cdfd33e-e776-4ffa-91cb-3d884826e5b0)

**Comment by maririos** [comment]
FYI @chunyu3

**Comment by maririos** [comment]
Closing as current UI seems to be working if we get new feedback we can always re evaluate
