### ISSUE TITLE
Update Epics tasks for SDK apps in Dataverse

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#6996]
With the new design, the tasks inside an epic are different and therefore we need to change the DB to make sure previous release plans and new release plans are compliant with the steps.

**Comment by maririos** [comment]
- Management plane Epic tasks:
  - Prerequisite Checks for Management-plane SDK Release
  - Schedule SDK ArchBoard Review for Management-plane SDK Release
  - Create a Pull Request & Generate Code for Management-plane SDK Release
  - Sign off SDK Readiness for Management-plane SDK Release
  - Release SDK Libraries for Management-plane SDK Release

**Comment by maririos** [comment]
### Management plane deleted epic tasks:

- Management plane task deleted:
- Monitor CI Job and APIView Generation for Management-plane SDK Release
- Setup SDK release plan for Management-plane SDK Release
- Work on .NET SDK for Management-plane SDK Release
- .NET SDK Grow Up, & Write Tests for Management-plane SDK Release
- Generate SDKs and Management Library Namespace Review for Management-plane

**Comment by maririos** [comment]
### Cloud flows responsable for this:
- Delete epic tasks
- Update task name

**Comment by praveenkuttappan** [comment]
As per latest design discussions, we don't need a step for sign off.

**Comment by maririos** [comment]
> As per latest design discussions, we don't need a step for sign off.

Thank you! I updated the DB with this information and updated the respective comments in this issue

**Comment by maririos** [comment]
As part of releases to other environments, we need to make sure that the tasks we want are with `visible=true`. in the `SDK Workflow Task Configurations` table
