### ISSUE TITLE
SDK release management place app feedback

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7008]
I took a look at the SDK release management plane app as of today and here is the general feedback:

### General

- [x]  In the Release Planner app, the order of steps is not right. It shows generate SDKs before sheduling a review meeting
- [ ] General UI improvements could be done to fonts, size, etc

### Welcome screen

- [x] Remove API spec from welcome screen
- [x] Checks are not correctly loading when the team already did some steps in the past.

### Prerequisites

- [x] General UI improvements could be done to fonts, size, etc
- [x] tittle should be `Prerequisites checks`
- [x] loading screen looks weird. like things are in different order
- [x] I can move around the tabs with no clicking next button (looks like this is ok? )
- [x] Add validation for release month not in the past
- [x]  Fix `Update my link` in SDK release details
- [x] Fix the alignment of badge in release target month selection tab
- [x] Fix the Width of API milestone owner
- [x]  Save languages and default them to when continuing a release in progress.

### SDK review

- [x] Update or modify documentation link.
- [x] Should I be able to click next if I don't book a meeting?
- [x] After scehduling a meeting, it did not show up. I had to refresh the app. Could we add a refresh button?
- [x] Fix .NET casing
- [x] Meeting was cancelled but it still shows up in the table
- [x] Meeting date is incorrect. It shows created date instead of meeting date.

### Generate SDK

- [ ] There is something weird with the tabs. There is an extra at the end that is always by default and creates confusion
- [x] Fix language name in each language section. Python, JS and Go tab talks about Java.
- [x] #7029
- [x] Fix Links .NET
- [x] Fix links in Java
- [x] Fix links in JavaScript
- [x] Fix links in Python
- [x] Fix links in Go
- [x] Do not show Review package name checkbox when release plan is for GA

### Release SDKs

- [x] View gets disable if I click on the Welcome screen
- [x] Fix wording on Request signf-off
- [x] Same problem with the tabs not respecting the checks
- [x] Wording on publish SDK reference docs
- [x] Complete button doesn't work. it does nothing
- [x] Display options based on the language selected. For e.g If .NET is not part of release plan then don't show release .NET option.
- [x] Fix Links in Request release
- [x] Fix links in Request sign-off
- [x] Fix links in Verify release
- [x] Enable Complete button only if all steps are completed.
- [ ] Open question in figma about link to verify preview docs for .NET v/s other languages
- [x] Generate and show correct concatenated language names for Request releases chekbox

**Comment by praveenkuttappan** [comment]
Added fix to clear release target month when selected date is past date and shows an error message.

**Comment by maririos** [comment]
Testing 9/29:

### Welcome

- [ ] Color of `Start` button is blue

### Prerequisites checks

- [ ] `Next` and `Back` button color is blue
- [ ] Request an exception doc link should be: https://eng.ms/docs/products/azure-developer-experience/onboard/request-exception
- [ ] 

### Schedule SDK review

- [ ] The `schedule meeting` button should always be enabled. A team can schedule multiple meetings if they want. Also, if they cancel a meeting and they want to book it again, they should be able to

### Generate SDK

- [ ] I can't click on the links of the check boxes because they are disabled. We should only disabler the checkbox though, so docs are always available (This only happens in .NET though)
- [ ] Java, Javascript, and Go spelling error in `Review samples` => `check outthe`
