### ISSUE TITLE
Release plan tag showing up on all work items, even PROD

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7019]
- The release plan tag is showing up on the new work items created in PROD.  I believe @maririos has fixed this bug but we should test and validate.

**Comment by ladonnaq** [comment]
FYI -This behavior is still being seen in PROD for triage work item.  I updated an existing work item (which did not have the Release Planner App Test tag), then after the update the tag was there.  Here is the triage work item - https://dev.azure.com/azure-sdk/Release/_workitems/edit/17877.  I have removed the tag so that it will show in our query for now.

**Comment by maririos** [comment]
Yes. The fix right now is manual. It will fix in our next deployment.

**Comment by maririos** [comment]
Also, this is a dup of https://github.com/Azure/azure-sdk-tools/issues/7015
