### ISSUE TITLE
[Release Planner] Published SDK dropdown is unusable for selecting multiple SDK

### ISSUE THREAD

**Issue by devlie** [Azure/azure-sdk-tools#7021]
Trying to onboard a new product, and on the Published SDK details page, the dropdown to select published SDK is unusable:

* It's randomly sorted, so trying to find my SDK manually is next to impossible.
* The autocomplete/type ahead is able to list multiple SDK results, but it disappears after selecting one SDK.
* The autocomplete/type ahead wouldn't appear again as long as there's already one SDK selected.

**Comment by praveenkuttappan** [comment]
I have removed SDK package selection option from onboarding task since that's not required anymore. We only need to track whether a product has released public packages in the past.
