### ISSUE TITLE
Error when selecting existing SDKs during onboarding 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7022]
We are still seeing an error in PROD if the user selects existing SDKs.   See error message in screenshot.  Also, the UI is a difficult to use.  When I search by name a subset of options do show but when I select one then I am returned to the entire list again.  Is it possible for the subset of options to show a little longer so that I can select all that apply from the search? 

<img width="961" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/67656762/314c41a3-e8d2-40c7-b036-e6676cc61d94">

**Comment by ladonnaq** [comment]
FYI - Engineering opened issue related to usability of the UI for selecting existing SDKs.  https://github.com/Azure/azure-sdk-tools/issues/7021

**Comment by maririos** [comment]
Dup of https://github.com/Azure/azure-sdk-tools/issues/6961 as this was happening with previous UI and keeps happening in new UI
