### ISSUE TITLE
Update Triage work item states via import/export 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7028]
- The triage work item state is manual until the first release plan is created.  At that time the state of triage changes to "Completed". 
- All Triage work items currently have a state of "New".  This is not correct as state of "New" indicates that no one has completed scoping for the new product.  The states need to be changed to reflect the true state of triage work item.  Since this action will require a human to look and make the decision, we cannot automate the cleanup of the state for the Triage work items. 
- I will manually change the states by using ADO's bulk edit feature, which allows a user to export a query to cvs, update to new field value, and then import back to ADO.

**Comment by maririos** [comment]
I am not following. Could you explain what are the states and the trigger to change each state?
The way I see it is:
- `New`: user just onboarded on the tool
- `Triage updated`: user made changes to the onboarding questionnary in the tool so PM needs to be notified
- `Completed`: user attended an informational meeting and now both service partner team and Azure SDK team know about each other

I don't see more states as I don't expect the triage work item to be set to `Finished`

**Comment by ladonnaq** [comment]
Completed.
