### ISSUE TITLE
Data plane SDK release app

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#7030]
To do's:

- [x] Welcome
   - [x] Update steps
- [x] Requirement checks
   - [x] Save selected languages in database
- [x] Schedule review
- [x] Generate SDKs
   - [x] Copy logic from Management Plane app to get the list of languages
   - [x] Create a set of checkboxes per each laguage for
      - [x] Public Preview
      - [x] GA
- [ ] Release SDKs

**Comment by maririos** [comment]
Testing 9/29:

### Prerequisites checks

- [ ] After I clicked `save and continue` it took me to the Schedule SDK review, but the view in the navigator didn't enable the `Prerequisites checks`
<img width="536" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/8ff7f039-505e-4723-9d5a-00fcec9369e2">
- [ ] When I go back to the Welcome screen it also doesn't mark it as checked. But if I look at the Release plan view, it does look like checked:
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/a34fac15-174e-4d5a-aad9-cf60b8babf4e)

FYI: The last 2 issues are fixed if I refresh the app again.

**Comment by praveenkuttappan** [comment]
- [ ] Language tab in `Release SDKs` is not switching any tabs/views
- [ ] Next button is enabled in Release SDKs without selecting all required checkboxes

**Comment by JonathanCrd** [comment]
> Next button is enabled in Release SDKs without selecting all required checkboxes

This is intentional. I would need more time to implement a check for this, and keep track of each checkbox, per language and per tab. Also, the `Next` button is purely there for navigation, and given the fact that the user can navigate freely across the different tabs, I didn't find this  validation too useful.

However, I do prevent the users to move to the next language if one of the checkboxes for the language is unchecked. This way, when we save the state of each sub-step (language), we won't mark any of those as completed unless all of the checkboxes in the 5 tabs are checked.

**Comment by JonathanCrd** [comment]
> Review package name: maybe we should just say Get an approval for package name during your SDK review meeting and then the Only required....

I like this idea, but I cannot add links in the checkbox label. Unless we want to get rid of the link pointing to the docs?

**Comment by JonathanCrd** [comment]
> For all the links here, can we point to the wiki with the data plane tab directly?
i.e: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-samples?tabs=dataplane
This applies to generate sdk, tests, samples. What I want to avoid is having to change links in two places if something changes

Do you mean pointing to the eng hub wiki instead of the final docs?
If so, yes, we can do that, but then all of the links will point to the same wiki no matter the language.

**Comment by maririos** [comment]
> > Review package name: maybe we should just say Get an approval for package name during your SDK review meeting and then the Only required....
> 
> I like this idea, but I cannot add links in the checkbox label. Unless we want to get rid of the link pointing to the docs?

no link is fine too then

**Comment by maririos** [comment]
> > For all the links here, can we point to the wiki with the data plane tab directly?
> > i.e: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-samples?tabs=dataplane
> > This applies to generate sdk, tests, samples. What I want to avoid is having to change links in two places if something changes
> 
> Do you mean pointing to the eng hub wiki instead of the final docs? If so, yes, we can do that, but then all of the links will point to the same wiki no matter the language.

Yes. that is what I mean. I prefer that than having to keep updating links in 2 places
