### ISSUE TITLE
Azure SDK sup report ready not working

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7035]
When I go to https://msit.powerbi.com/groups/3e17dcb0-4257-4a30-b843-77f47f1d4121/reports/c30a45b0-ae9b-4b19-9a33-b8ecfe8e5e3c/ReportSectionda56afa07b9b086510e1 I get this and no way to update the report:

<img width="1678" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/4c34ad71-b97e-4e74-b60a-ebc3b3dfbc47">

**Comment by maririos** [comment]
@ladonnaq who is the person responsable for this?
The Data plane SDK release app is using this link for:
<img width="1281" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/36520c7f-081b-4b5f-be3b-16a6503fd198">

**Comment by ladonnaq** [comment]
> @ladonnaq who is the person responsable for this? The Data plane SDK release app is using this link for: <img alt="image" width="1281" src="https://private-user-images.githubusercontent.com/9868623/271687895-36520c7f-081b-4b5f-be3b-16a6503fd198.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NDc3OTEsIm5iZiI6MTcwNDc0NzQ5MSwicGF0aCI6Ii85ODY4NjIzLzI3MTY4Nzg5NS0zNjUyMGM3Zi0wODFiLTRiNWYtYmUzYi0xNmE2NTAzZmQxOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMjA1ODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2JiOWM0ZDVmMzMwYzJkZjc5YTc3NzQyNDNjMzhiZWJiMGE1MDMxMjBmNWViNWZhZmE3MTUzM2VjNmU3NDIyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tuamvtJ17ykL-2AhRFHubHyPUgPJQYZUP7TDMC67ey0"

@maririos I do not know who owns the report.  If you have not identified the owner yet, I will ask around and find out who owns it.

**Comment by maririos** [comment]
@ladonnaq  Should we just remove this line from our apps then if no one knows? it means it is not useful for our team....

**Comment by maririos** [comment]
I am going to remove this from the apps as it is useless as is.

**Comment by ladonnaq** [comment]
> I am going to remove this from the apps as it is useless as is.

Sounds good.  Can we go ahead and close this issue?

**Comment by maririos** [comment]
> Sounds good. Can we go ahead and close this issue?

I will close when it is deployed to PROD

**Comment by ladonnaq** [comment]
[heart]         LaDonna Quinn reacted to your message:
________________________________
