### ISSUE TITLE
Move Marking a package as in release doc to Eng hub

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7036]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/444/Marking-a-Package-as-In-Release

**Comment by ladonnaq** [comment]
Related to https://github.com/Azure/azure-sdk-tools/issues/6896

**Comment by maririos** [comment]
link to update: https://aka.ms/azsdk/mark-release-status

**Comment by ladonnaq** [comment]
This has been automated in the release plan.  I am not going to move the document to engineering hub.  Instead, I will update the doc in ADO to indicate that this process has been automated via Release Planner App and service partners should be using release plans.
