### ISSUE TITLE
Move Publishing packages to Eng Hub

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7037]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/446/Publishing-Packages

**Comment by ladonnaq** [comment]
Related to https://github.com/Azure/azure-sdk-tools/issues/6896

**Comment by maririos** [comment]
link to update: https://aka.ms/azsdk/publishsdk

**Comment by maririos** [comment]
PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/1022

**Comment by maririos** [comment]
Eng hub link: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-release/sdk-release-pipeline
