### ISSUE TITLE
SDK target release month has a duplicated value

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#7044]
Bug found in Data Plane SDK readiness. It might be present in the management plane app too.

![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/2c128e9f-21ed-4073-a3e8-f83f10b889cc)

`October` is duplicated. This might be happening because that was the value from the database and the default property of this drop-down is not configured correctly. So, instead of choosing `October` from the list of items, it's creating a new "default" one.

**Comment by maririos** [comment]
Happens in Release Planner app too. It is because of how we are assigning the defaultSelectedItem

**Comment by maririos** [comment]
Fixed:

- [ ] Release Planner
- [ ] Data Plane SDK
- [ ] Management plane SDK
