### ISSUE TITLE
Add README for APIView

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-tools#705]
It would be useful to have a description of APIView functionality and intended use that we could use to help the team and partners understand what APIView does and how to use it.

Example content started here: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/249/Reviewing-the-API-in-APIView

**Comment by pakrym** [comment]
Wonder we can put it somewhere on the site itself.

**Comment by annelo-msft** [comment]
Can reference this:
https://github.com/Azure/azure-sdk-pr/blob/master/training/azure-sdk-apis/getting-started/6-review-the-api.md

**Comment by annelo-msft** [comment]
@kurtzeborn, could you link to the README so we can share it with our partners?
