### ISSUE TITLE
Consider splitting the Release Planner solution into multiple smaller solutions

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#7054]
The number of items inside the Release Planner solution has been going up over time, which increases the deployment time (at this moment it takes around 30 minutes). 
Usually, we just make changes in one app or a couple of cloud flows, but we still pack and deploy everything.

I wonder if there is a way to simplify this and have multiple solutions, one for each app:

- Release Planner Core
- API Readiness
- SDK Readiness
- Automatization
- Etc...

This way, we will only have to deploy the solutions in which the modified apps are. 

This approach might increase the complexity of managing dependencies and solution layers, so we need to evaluate its benefits and drawbacks carefully.

**Comment by ccbarragan** [comment]
@JonathanCrd How might splitting it up impact the user experience? Would this affect anything that's perceivable by users today?

**Comment by JonathanCrd** [comment]
@ccbarragan it won't affect the users, this is just how we manage and organize the different items internally (Apps, cloud flows, environment variables, etc.)

**Comment by maririos** [comment]
Closing as we will leave the current design as is
