### ISSUE TITLE
Save the state of each step for the Generate and Release SDK tasks

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#7055]
In the SDK Readiness App, both Management and Data plane, we only keep track of the entire task. If the user closes the app in the middle of one task, they will lose all the progress they've done in the sub-tasks.

We could implement a new feature to store the progress at a sub-task level, or even save the state of each of the checkboxes in the app. That way, if the user leaves the sub-task incomplete, the progress won't be lost.

**Comment by ccbarragan** [comment]
+1. Ideally we're able to automatically save the user’s progress when possible. In the instances where this can't happen, provide a mechanism that allows them to save their current state and return later. In these cases, we recommend a footer like this one:

![Prerequisites - Permissions (success)](https://github.com/Azure/azure-sdk-tools/assets/28902259/cf4ab201-3339-4d7a-a277-4ac243058366)


1. Go back to the previous step
2. Continue to the next step
3. Save and close --> this action saves progress and takes users to the dashboard (welcome screen of the app)
4. Cancel --> this action doesn't save progress and takes users back to the dashboard (welcome screen of the app)

**Comment by maririos** [comment]
This has been covered in release `1.3.4-beta.1`
Reminaing work is:
- https://github.com/Azure/azure-sdk-tools/issues/7341
- https://github.com/Azure/azure-sdk-tools/issues/7342
