### ISSUE TITLE
API Spec Type and SDK Type as part of "Create a release plan" 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7061]
**Suggested changes:**  During creation of public preview and GA release plans we ask if the SDK will be beta or stable.  We should also ask if the API Spec will be preview or stable.  

**Why is this important?** 
We want teams to release new functionality in Beta SDKs first, for minimum of 30 days before promoting to stable. 
It is possible to release a Beta SDK using stable API version but the service teams will need to make sure the readme tag has the -b, -beta, -preview syntax.  Since a service team will be on the hook to support stable SDKs until end of life of the service or they go through the complicated and highly discouraged process of deprecating specific REST API versions/SDK versions.

**Comment by maririos** [comment]
@ladonnaq you mean something like this?
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/0e824fca-8da1-454e-93f0-d4faa7e30080)

Also, what should we do with that information? where do you want it to be saved?

**Comment by ladonnaq** [comment]
Closing this issue and will track using this issue - https://github.com/Azure/azure-sdk-tools/issues/7492
