### ISSUE TITLE
Language `Go` should not be selected by default in the SDK Readiness app

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#7064]
Since `Go` is optional at the moment, it shouldn't be one of the default languages for this dropdown in the prerequisites checks step:

![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/11829a92-f0cb-4df8-b4d8-488a78927a97)

**Comment by ladonnaq** [comment]
Just want to make sure this is data plane SDK release app only.  Go is required for management plane.
