### ISSUE TITLE
OpenAPIHub - secondary rate limiting error when creating new API version

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#7065]
OpenAPI hub fetches information about all branches in both public and private repos and all its forks to show information in current branch view. This cache is refreshed after creating or updating an API version which leads to secondary rate limiting due to multiple APIs triggered to get branches and PR info for each repos.

This issue is to resolve secondary rate liming error when creating/updating API version using Open API hub.

**Comment by maririos** [comment]
Deployed to Prod
