### ISSUE TITLE
Update all existing release plan work items to that the state matches state of release plan in Release Planner 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7079]
The state field is not being updated for the Release Plan work item.  This is an important field for queries as it represents the overall state of the release plan.

- [x] Link to the Release Plan work item template state field options - https://dev.azure.com/azure-sdk/_settings/process?process-name=SDK&type-id=SDK.ReleasePlan&_a=states
- [x] Note that if we change the state of Release Plan to from Finished to Complete as suggested in this GitHub issue - https://github.com/Azure/azure-sdk-tools/issues/7062, then we also need to change the state field options 
- [x] May want to complete above before updating all existing release plan states.  Right now none of the states are accurate.  They are mostly new, except for a few that we have manually updated when working with service partners past couple of weeks.

**Comment by maririos** [comment]
@praveenkuttappan this is done too, right?

**Comment by praveenkuttappan** [comment]
@maririos  I still don't see "Complete" as an option for Release plan state field in work item. So I am a bit confused about what needs to be done here.

But we have completed the work to match all release plan work item state as per release plan state in dataverse.

**Comment by maririos** [comment]
> @maririos I still don't see "Complete" as an option for Release plan state field in work item. So I am a bit confused about what needs to be done here.

I think our tooling uses Finished, which is fine too. The importatn thing is that the state is updated
