### ISSUE TITLE
Triage Work Item Field Updates - Onboard a new or update triage for product

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7081]
Link to spreadsheet tab with details, search for triage work item type - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=Nz0Bjy
- [x] Epic Product Onboard Date (New Field in Triage work item and Epic work item) 
- [x] Service Onboard Date  (New field in Triage work item and Epic work item) 
- [x] Related SDKs - Change the UI to eliminate the drop-down box for now because the UI is complicated and difficult to use.  For now, we can just use the existing field (which is a multi-text field) and just simply input TRUE or FALSE depending on if the box is checked in the onboarding UI. 
- [x] State:  If no triage work item exists then state is New.  If triage work item exist, then state is "Triage Updated".  This seems to be working but adding to make sure we validate.

**Comment by ladonnaq** [comment]
We should not change this field when a team updates triage information by onboarding again.  This date is to help us determine the load of new teams we are onboarding over time.

**Comment by maririos** [comment]
Questions:
- How are the product and service onboard dates, different than the `onboard date` in each of the specific service/product work items? is the behavior the same?
- `Related SDKs` what is the purpose of this field? should it better be `ReleasedSDKs` = True/False ?

**Comment by ladonnaq** [comment]
> Questions:
> 
> * How are the product and service onboard dates, different than the `onboard date` in each of the specific service/product work items? is the behavior the same?  **They should be the same.  I was just including field here since it is part of the base triage information.  However, if you just want to update the fields in the epic product and epic service that would be fine as well. These fields are not updated again. They are timestamp. I am not sure if there is a way to programmatically update all of the existing work items. This might need to manually done by looking to see when if an epic for the service already exist (created by the release automation that creates the epic and packages right now).  Then use the creation date as the onboard date for the service.  Then for product onboard date, we would have to look at the creation date of the original onboard work item.  Then use that date for the onboard date. I can create queries to get this info and export. Then would have to export the epics and map the fields manually.  Then import the updated epics back to ADO.**  
> * `Related SDKs` what is the purpose of this field? should it better be `ReleasedSDKs` = True/False ?  **Yes but we have this field in the epic and values would be Beta SDKs, Stable SDKs, no SDKs.  We can create a field "existingSDKs" and make it True/False.  That way if a user chooses the button during onboarding indicating there are existing SDKs, we will know.  Then during onboarding we will manually update the initial value of the RelatedSDKs field in the epic.  Will that work?**

**Comment by maririos** [comment]
Conclusion for Eng team:

- Product onboard date: same behavior as product
- Service onboard date: same behavior as service
- Existing SDKs: should match the answer for the question during onboarding
