### ISSUE TITLE
[Api-stub-generator] cannot import name 'epylint' from 'pylint' in Python3.11

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-tools#7101]
CI of autorest.python integrate apiview tool while it [fails only in Python3.11](https://dev.azure.com/azure-sdk/public/_build/results?buildId=3151035&view=logs&jobId=51623fb1-0b3d-59bb-23fe-ec2bbec168f9&j=51623fb1-0b3d-59bb-23fe-ec2bbec168f9&t=ec5d0648-df70-50bc-a81e-a1b2d8dd6376). According to [log](https://[dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/3151035/logs/298](https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/3151035/logs/298)), it happens in `_stub_generator.py` when import `epylint` from `pylint`:
![image](https://github.com/Azure/azure-sdk-tools/assets/70930885/050aaaad-0ad1-43fc-97a2-d8021357bf12)

**Comment by l0lawrence** [comment]
If you pin the version of pylint to be <3.0.0 it should no longer throw this error --- #7093
