### ISSUE TITLE
Bug in creating Private Preview release plan 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7103]
Yoga and I were helping the Network security perimeter team this morning.  I created a Private Preview release plan for them but I am getting an error when I access the API readiness milestone app. 

Triage work item:  https://dev.azure.com/azure-sdk/Release/_workitems/edit/18608
Release plan work item:  https://dev.azure.com/azure-sdk/Release/_workitems/edit/19044

There does not seem to be an API Spec work item created for the release plan.  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/0ef92234-e84e-4e2f-baa7-aa76d65516d2)

**Comment by maririos** [comment]
The cloud flow responsible for creating this Triage work item failed with error message: "The field 'Service Lifecycle' contains the value 'In Development' that is not in the list of supported values"

Looking to see what happened

**Comment by maririos** [comment]
Found the error. Fix and deployed to DEV.

**Comment by maririos** [comment]
Deployed to Prod
