### ISSUE TITLE
Bug - after completing API readiness milestone the return to main does not work 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7104]
The link does not return to the release plan, which is where I expect it to return me.  It returns me to a different service in a different environment (app is not in PROD anymore). 

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/6ec97ec6-ed59-410d-bd75-e1c8fd338c7c)

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/503741a2-4bf2-4e93-be54-148187991a00)

**Comment by maririos** [comment]
@ladonnaq next time could you specify the app you worked on and the version? For example, Data plane readiness app. version 1.3.0

**Comment by maririos** [comment]
This issue has been fixed. For context, the environment variable `Release Planner ID` was pointing to DEV because of the limitaiton we have with issue:  https://github.com/Azure/azure-sdk-tools/issues/5975

@JonathanCrd  FYI for everytime we deploy to PROD we need to check this variable

**Comment by maririos** [comment]
> @JonathanCrd FYI for everytime we deploy to PROD we need to check this variable

It gets overwriten to the DEV value :( so we need to prioritize #5975 or we are going to forget about this in every deployment
