### ISSUE TITLE
[TestProxy] Running Golang tests on Windows into TestProxy running on Docker WSL2/Linux container leads to incorrectly referenced recording files

### ISSUE THREAD

**Issue by adreed-msft** [Azure/azure-sdk-tools#7109]
# Scenario

- Test proxy docker version: [`azsdkengsys.azurecr.io/engsys/test-proxy:1.0.0-dev.20230818.1`](https://github.com/Azure/azure-sdk-for-go/blob/main/eng/common/testproxy/target_version.txt)
- `azure-sdk-for-go` branch: `feature/storage/azbfs/newsubdirectoryclient`

I set up the test proxy via the eng/common script here: https://github.com/Azure/azure-sdk-for-go/blob/main/eng/common/testproxy/docker-start-proxy.ps1

Lead by instructions at https://msazure.visualstudio.com/One/_wiki/wikis/One.wiki/386238/Testing-Framework

# Expected behavior

Test recordings should be stored as a file under `sdk/storage/azdatalake/...` rather than as a file named `sdk\storage\azdatalake\...`

# Actual behavior

Test recordings get stored with their native Windows path separator, meaning that they're actually a file in the root folder, not a file under the correct folder

# Temporary mitigation

`git mv <incorrectly named test> <correct location>`

This only resolves getting tests into the pipeline, not running recordings locally.

**Comment by scbedd** [comment]
Resolved by [this PR.](https://github.com/Azure/azure-sdk-for-go/pull/21874)
