### ISSUE TITLE
API Readiness Signoff email includes incorrectly formatted release plan url

### ISSUE THREAD

**Issue by MrJustinB** [Azure/azure-sdk-tools#7111]
When I received an email from the Azure SDK bot account for the API Signoff notification, the hyperlink did not work. 
 What called my attention to it is that text seems missing from the sentence.  When I try to select the url to open it, nothing happens.  When I right-mouse click and try to open it the same thing.  When I right mouse click on it and copy, it doesn’t copy the url, it copies the text “Access the release plan”.  I think the address and the displayed text for the link are inadvertently flipped.

**Comment by maririos** [comment]
Templates modified in Dev, PPE, and Prod environments:
- API Readiness Signoff Public Preview Data Plane
- API Readiness Signoff Public Preview Management Plane
