### ISSUE TITLE
Remove the condition of having a namespace starting with Microsoft

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7119]
3p RPs have always been supported (and the namespace name for 3p RPs dont start with Microsoft.)

**Comment by maririos** [comment]
Our guidance https://github.com/Azure/azure-rest-api-specs does say that the folder name should include `Microsoft` on it. so we need to look at this more before implementing it

**Comment by maririos** [comment]
@JonathanCrd with the new changes, is this something that you are considering, validating, or checking in the script?

**Comment by JonathanCrd** [comment]
There's no validation for the Namespace in the script, only a mention in the docs that it **usually** starts with `Microsoft.`

The script will take the RP Namespace from the user directly and it will work as long as the directory for that namespace exists,

**Comment by JonathanCrd** [comment]
Is this a condition in OpenAPI Hub? Or where are we doing this validation that is blocking users?

**Comment by maririos** [comment]
> Is this a condition in OpenAPI Hub? Or where are we doing this validation that is blocking users?

It was a condition in OpenAPI Hub. But if we removed it, then we are ok. We can go ahead and close this issue
