### ISSUE TITLE
TypeSpec APIView job cannot resolve typespec-apiview emitter

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#7129]
In https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3165054&view=logs&j=e37a1bb9-a190-5269-3a0e-37469dfbe682&t=09cb0672-20c5-5dce-4552-dad3f3e96fd3&l=46 (from https://github.com/Azure/azure-rest-api-specs-pr/pull/15379), I got the error:

```
Compiling files and generating APIView
Executing command: npx tsp compile . --emit=@azure-tools/typespec-apiview --option @azure-tools/typespec-apiview.emitter-output-dir={project-root}/output/apiview.json in folder: specification/secretmanagementtestsvc/resource-manager/Microsoft.SecretManagementSampleProvider/cadl
stderr: 
stdout: TypeSpec compiler v0.48.0

Diagnostics were reported during compilation:

error import-not-found: Couldn't resolve import "@azure-tools/typespec-apiview"

Found 1 error.

No emitter was configured, no output was generated. Use `--emit <emitterName>` to pick emitter or specify it in the typespec config.

error: Command failed: npx tsp compile . --emit=@azure-tools/typespec-apiview --option @azure-tools/typespec-apiview.emitter-output-dir={project-root}/output/apiview.json
```

Adding `@azure-tools/typespec-apiview` to my `package-lock.json` in my repo solves this, but seems it should not be necessary. Even more odd is that it is also in main and the two RPSaaS* branches in our internal specs repo, but I have my own copy in https://github.com/Azure/azure-rest-api-specs-pr/pull/15379/files#diff-cca687daa14d3358881226621e7b53a67ba8c2a9c581f367ddaceed2e7fde6a1. Should the swagger pipeline not copy that over?

/cc @chitturs

**Comment by heaths** [comment]
This may not be a problem after all. After talking with @mikeharder I understand that this was only a problem because a project's own `package.json` and `package-lock.json` were copied over and shouldn't have been. The pipeline that did that is old and based on previous Shift Left recommendations and will have to be changed.

Still, because we do need to support other repos, this is something we should collectively consider if we end up writing and/or maintaining any pipelines that help teams synchronize their changes.

Given that, do with this bug what you will: retitle it to fit the long-term goal, close it, whatever. :smile:

**Comment by tjprescott** [comment]
@heaths I'm not sure what that other package.json looked like, but if typespec-apiview was appropriately listed as a dependency and npm installed, then the compilation step with `--emit` should work just fine. I'm going to close this for now, but if that's not the case, please reopen.
