### ISSUE TITLE
Previously created release plans are not showing the new SDK release milestone app

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7134]
The Azure Workloads as a Platform team is preparing to release SDKs to complete exception work for Public Preview.  This is the release plan they were using but it does not have the SDK release milestone app.  Can engineering resolve?  Or does the service team need to have the old release plan marked as abandoned and then create a new release plan?   

Link to release plan - https://aka.ms/sdk-release-planner?release-plan-id=663a6257-074c-ee11-be6e-000d3a3418aa

**Comment by ladonnaq** [comment]
> If they created the release plan before the 1.3.0 release (end of Sept) of the Release Planner, then yes. It will be best for us to mark the release plan as abandoned and create a new release plan.
> 
> How common is this scenario? is this work around acceptable? or should we look into creating all the SDK release milestones for all open release plans that are not targeting Private Preview

This is the 3rd team that has come to since last week asking the same question.  We may want to go ahead and look into how to create the SDK release milestones for all of the open release plans not targeting Private Preview as you suggested.  Let me know how long that would take and how complicated it will be.  We are getting lots of teams coming our way because of Ignite in November.  Teams are working to get signoffs done before end of October.

**Comment by maririos** [comment]
> Isn't there anyway to just do this for the service teams? Meaning just add the milestone to existing release plans.

You mean for us to automatically do it? What will be the criteria? non private preview release plans, and plans that haven't been completed or abandoned?

**Comment by maririos** [comment]
@ladonnaq how often is this happening? is it a priority that you would like it for it to happen in november?

**Comment by maririos** [comment]
Content AI team needs this. Moving this item to Nov

**Comment by ladonnaq** [comment]
@maririos I don't think this matter so much now because we have been telling teams to just create a new plan.  We do want to ensure going forward that all existing release plans are always updated when new features are deployed.  I think that is happening now.

**Comment by maririos** [comment]
> @maririos Mariana Rios Flores FTE I don't think this matter so much now because we have been telling teams to just create a new plan. We do want to ensure going forward that all existing release plans are always updated when new features are deployed. I think that is happening now.

Great! Let me know if we need to abandon plans then.
