### ISSUE TITLE
Mark release plans abandoned, possible to change release plan to private preview? 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7135]
Background: katie contacted me with questions regarding the release planner app.   Please see questions and info below. 

- (Katie) I believed something happened where it changed the status from private preview to public preview. I found this screenshot for release plan 1042 that we did have it under launch type private preview previously. Not sure if it's a potential bug but I was certain that 1077 and 1042 was for private preview.  
- (La Donna) I am not sure what happen here.  Katie thinks these were private preview release plans but now they are showing up as public preview.  Is there a way to change them to private preview?  Or do we need to just go with the plans that are complete.  We have signed off Private Preview already so these are completed plans.  
- (Katie) Yes please if you can flag 1075 and 1074 to be abandoned. I'll try again to see if I can get the new SDK milestones under the product skus.  
- 
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/d8ad5ad3-2cfb-4370-bebf-dc62cd3db8eb)

**Comment by maririos** [comment]
Changes have been made and user plans are reflecting what the user wanted. 
I am now looking into why the 2 plans changed from Private Preview to Public Preview

**Comment by maririos** [comment]
Found the bug. It was introduced when we enabled the SDK Release apps. Looking into the fix

**Comment by maririos** [comment]
Fixed. this was directly on the DB so no need for deployment.
Thanks @ladonnaq !
