### ISSUE TITLE
Integrate scheduling an Informational Meeting as another step of the onboarding and create release plan process  (Proposed for dilithium-2H) 

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7144]
Then, depending on the field state in ADO, we can make that step optional or required.

Requirement discussion happened over email

Related GitHub issue - https://github.com/Azure/azure-sdk-tools/issues/7237

**Comment by ladonnaq** [comment]
Resolved, scheduling tool prompt is shown if service team needs to schedule Info Meeting.
