### ISSUE TITLE
Bug - Offering not showing up in drop-down for onboarding but shows up for create release plan 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7149]
Yoga and I are helping the SQL team with 2 SKUs that they are changing into offerings.  SQL service tree organization is VERY different as there are MANY services mapped to the offerings because all have needed functionality to enable the new offerings. 

We were able to find one of the offerings but we have one that is not showing up. 

- - [SQL Server on Azure Virtual Machines Offering](https://microsoftservicetree.com/products/76866409-0079-4a2e-ab5f-760791e0bb20/overview) is mapped to MANY services and it is not showing up under any we tried.  
- The service that is most closely related to the new offering is 
[SQL MI Prod Clusters](https://microsoftservicetree.com/services/c2bb981e-04a9-4f19-9463-9f731d7d0431/products).  The new offering does show up mapped to the service in service tree but it is not showing up in the Release Planner drop down to onboard.  However, it does show up in "create a release plan" but blocked b/c we can't onboard.  

Service team is blocked at moment, so resolving is a priority.  Thanks!

**Comment by maririos** [comment]
@JonathanCrd could you please take a look?

**Comment by JonathanCrd** [comment]
I could not reproduce this bug, Service `SQL MI Prod Clusters` only shows one product for me in both forms in PROD. However, I found the product you're looking for. It is under `SQL Storage Engine` service.

**Comment by JonathanCrd** [comment]
> [SQL Server on Azure Virtual Machines Offering](https://microsoftservicetree.com/products/76866409-0079-4a2e-ab5f-760791e0bb20/overview) is mapped to MANY services and it is not showing up under any we tried.

@ladonnaq I noticed that the offering this link points to has a different name than the one you wrote. I found this other offering in service tree for [SQL Server on Azure Virtual Machines](https://microsoftservicetree.com/products/751bf410-c159-44cc-b368-ceef99b34d5a). Was this a mistake?
