### ISSUE TITLE
Update fields when a SDK release milestone is completed

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7161]
This needs to happen in both management and data plane apps

Epic/Product:
- Field: `Released SDKs type`: update only when the field value is different than stable SDKs. If the value is different, then when a release plan is completed update the value with the SDK type that was released.

Triage:
- Field: `Existing SDKs`: update to Yes if it was No

**Comment by JonathanCrd** [comment]
- [ ] Data Plane
- [ ] Management Plane

**Comment by JonathanCrd** [comment]
FYI:
The values in the Dataverse for the SDK type do not match the options in the Work Item. I am going to map them in the code.

**Comment by JonathanCrd** [comment]
> Field: Existing SDKs: update to Yes if it was No

Should I consider a Blank value as a "No"? Or should I ignore it?

**Comment by maririos** [comment]
> Should I consider a Blank value as a "No"? Or should I ignore it?

Ignore it. I found that if we don't send the field, then it will be ignored and not modified. We need to make sure it doesn't have a default value. a test could tell us this

> FYI: The values in the Dataverse for the SDK type do not match the options in the Work Item. I am going to map them in the code.

Could you expand more on this? Althought strings are not the same the concept is the same. Or is that not what you are saying?

<img width="145" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/94991052-453f-4e5e-90f9-4e8c4754c6a9">

**Comment by JonathanCrd** [comment]
> Could you expand more on this? Althought strings are not the same the concept is the same. Or is that not what you are saying?

Yes, the concept is the same. I'm just letting you know that the values can't be used directly.

**Comment by JonathanCrd** [comment]
Changes have been made based on the new field
