### ISSUE TITLE
[Breaking Change][False positive] The TypeFormatChanged error message should contain the name, old format and new format.

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#7182]
`TypeFormatChanged` is a very common issued reported as a breaking change but it is often, but not always, benign. 

In many cases, the name, old format, and new format is enough information to assess the severity of the change, but this information is not included in the error message. Reviewers must open the links for both the old and new version to get this information. And [sometimes those links are inaccurate](https://github.com/Azure/azure-sdk-tools/issues/4933), making it even more laborious to assess the error.

It will greatly benefit reviewers to have this information included directly in the error message.

**Comment by mikekistler** [comment]
Added the new and old format to the message in https://github.com/Azure/openapi-diff/pull/304.

Still to be done (sorry I did not do it in 304) is to include the name of property / parameter.

**Comment by konrad-jamrozik** [comment]
- https://github.com/Azure/openapi-diff/pull/333

**Comment by konrad-jamrozik** [comment]
- [Pull Request 557572](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/557572): Print out JSON path for `New` entry in breaking changes table rows

**Comment by konrad-jamrozik** [comment]
Closing this work item as subsumed by:

- https://github.com/Azure/azure-sdk-tools/issues/8435
