### ISSUE TITLE
[Breaking Change][False positive] The `AddedRequiredProperty` should not flag `readOnly` properties changed from `optional` to `required`

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#7184]
The Breaking Changes tooling flags properties that are changed from optional to required, but this is not a breaking change if the property is response-only.

It can be difficult to determine when a property is response-only -- it involves tracing all request inputs to see if the schema is ever included in a request. But there is an instance where it can easily be determined -- when the property is marked `readOnly: true`. And this case is beginning to occur somewhat frequently, as it is common in REST API definitions generated from TypeSpec.

To avoid unnecessary effort investigating these false positive errors, this rule should not flag a property changed from optional to required if that property is also marked `readOnly: true`.

**Comment by konrad-jamrozik** [comment]
@mikekistler can you confirm my understanding is correct?

Looking at this example:

https://github.com/Azure/openapi-diff/blob/master/docs/rules/1034.md

We have this property:

```
        "b": {
          "type": "string",
          "description": "Required. Enum Property b.",
          "enum": [ "b1", "b2" ]
        }
```

that has been added as `required`, causing breaking change

```
      "required": [
        "a",
        "b" <<<<<<<<<<<<<<<<<<<<<<<<<<< added
      ],
```

If I understand correctly, if we would have the same scenario, but if `b` would be `readOnly`, like this:

```
        "b": {
          "type": "string",
          "description": "Required. Enum Property b.",
          "enum": [ "b1", "b2" ],
          "readOnly": true
        }
```

then adding `b` as `required` should not trigger breaking change, correct?

**Comment by mikekistler** [comment]
That is correct.
