### ISSUE TITLE
Breaking Change(Cross-Version) Runtime exception: Additional properties not allowed:

### ISSUE THREAD

**Issue by emmeliaAra** [Azure/azure-sdk-tools#7188]
A runtime exception occurs on breaking change check with ERROR: Schema violation: Additional properties not allowed: identity

The PR is created for the new API version 2023-12-10-preview for "cloudhsm".
The new Property Identity is added under [CloudHsmClusterResource  ](https://github.com/Azure/azure-rest-api-specs/blob/7956f1979d5ed9fe5ca6fb64450ee8e993b9c379/specification/hardwaresecuritymodules/resource-manager/Microsoft.HardwareSecurityModules/preview/2023-12-10-preview/cloudhsm.json#L626C6-L626C29)

Impacted PR: https://github.com/Azure/azure-rest-api-specs/pull/26326

**Comment by konrad-jamrozik** [comment]
@emmeliaAra I believe you refer to [this error](https://github.com/Azure/azure-rest-api-specs/pull/26326/checks?check_run_id=18269480375). Please have a look at the error message: this is not a runtime exception, but the tooling reporting problem with the specification. I am closing this issue. If you have reasons to think the tool is at fault after all, please provide evidence for that and reopen this issue. Thx!

**Comment by konrad-jamrozik** [comment]
Note: there was additional elaboration on this error in the comments on the affected PR, starting [here](https://github.com/Azure/azure-rest-api-specs/pull/26326#issuecomment-1789913188).
