### ISSUE TITLE
Remove management plane SDK review meeting from SDK release readiness app

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7189]
Our management plane team has apparently decided that they will review the .NET SDK when the PR to release is submitted for review by our .NET engineering team.  This is change in the previously agreed to process, which was to have teams schedule a SDK Review and indicate in the description field is for management .NET SDK only. 

Immediate need: 
- [ ] Right now this is blocking service teams using the SDK release app for management plane.  So immediate need is to remove as to not block teams.  

Next Steps: 
I will schedule a call next week with Josephine and Arthur to discuss, reach agreement and timeline for the following: 

- [ ] Update engineering hub docs with clear guidance and instructions for .NET SDK reviews for management plane 

- [ ]  Revise and move the .NET SDK test and release doc into Engineering Hub - (I think this should only be track 2 guidance, they can keep track 1 guidance on the old wiki if needed but I believe at this point all services should have track 2 SDKs because our team was suppose to migrate for them). 

@maririos - Anything missing from the todo lists?

**Comment by maririos** [comment]
@ladonnaq there are no docs for .NET management plane in Eng Hub. They still point to the wiki because work on PR https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/779 never happened

>  Right now this is blocking service teams using the SDK release app for management plane. So immediate need is to remove as to not block teams.

It is not that easy to remove/add major tasks in a milestone as this all comes from the DB. Before making any change, I would like to get confirmation from the management SDK folks and according to that see how we should proceed

**Comment by maririos** [comment]
Although currently in PR, it does look like there is no need for the arch board. Recommendation is to completely remove it from the UI and as a task of the milestone After the pre-requisites, people can go to generate SDKs.
The change for generate SDKs for .NET is to update the documentation link to ...

**Comment by maririos** [comment]
Needs to happen in 

- [ ] DEV
- [ ] PPE
- [ ] PROD

**Comment by maririos** [comment]
Documentation update: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-generate-mgmt-dotnet
