### ISSUE TITLE
kojamroz contributions summary 4/15/2023 - 9/29/2023

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#7211]
## About this summary 

This summary pertains to a time period from April 15, 2023 until September 29, 2023, both dates inclusive.

It is a complementary material to Microsoft connect, https://aka.ms/connect. For full context, see the relevant connect.

This time period spanned 120 work days out of which 14 I was out of normal work duty (6 out of these 14 days were Hackaton), totaling 106 effective work days.

Summary for the previous time period: #5974

## Stats: issues and PRs (pull requests) closed

- [55 issues closed](https://github.com/issues?q=is%3Aissue+assignee%3Akonrad-jamrozik+archived%3Afalse+is%3Aclosed+closed%3A2023-04-15..2023-09-29)
- Total of 160 PRs closed, or 1.51 PRs per work day on average.
- [51 closed openapi-alps (Unified Pipeline) PRs](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequests?_a=completed&createdBy=e3bba399-628a-6716-8ee0-01c0479f74e9)
- [35 closed azure-sdk-docs-eng.ms (EngHub docs) PRs](https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequests?_a=completed&createdBy=e3bba399-628a-6716-8ee0-01c0479f74e9)
- [29 closed azure-rest-api-specs PRs](https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Apr+author%3Akonrad-jamrozik+is%3Aclosed+closed%3A2023-04-15..2023-09-29) (this excludes the 7 PRs made for internal testing)
- [26 closed azure-openapi-validator (LintDiff) PRs](https://github.com/Azure/azure-openapi-validator/pulls?q=is%3Apr+author%3Akonrad-jamrozik+is%3Aclosed+closed%3A2023-04-15..2023-09-29)
- [8 closed avocado PRs](https://github.com/Azure/avocado/pulls?q=is%3Apr+author%3Akonrad-jamrozik+closed%3A2023-04-15..2023-09-29+is%3Aclosed)
- 6 closed PRs about updating Ubuntu images made to misc. repos: [azure-sdk-for-c PR 2546](https://github.com/Azure/azure-sdk-for-c/pull/2546) and [PR 2549](https://github.com/Azure/azure-sdk-for-c/pull/2549), [azure-sdk-for-cpp PR 4562](https://github.com/Azure/azure-sdk-for-cpp/pull/4562), [azure-sdk-for-ios PR 1525](https://github.com/Azure/azure-sdk-for-ios/pull/1525), [azure-sdk-for-python PR 29954](https://github.com/Azure/azure-sdk-for-python/pull/29954), [autorest.typescript PR 1825](https://github.com/Azure/autorest.typescript/pull/1825)
- [4 closed Azure/azure-sdk-tools PRs](https://github.com/Azure/azure-sdk-tools/pulls?q=is%3Apr+author%3Akonrad-jamrozik+is%3Aclosed+closed%3A2023-04-15..2023-09-29+)
- [1 PR to rest-api-specs-scripts: PR 101](https://github.com/Azure/rest-api-specs-scripts/pull/101)

**Comment by kurtzeborn** [comment]
Great work this semester!
