### ISSUE TITLE
OpenAPI Hub diff tool doesn't accept GitHub SAS URLs

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#7224]
Some time in the not too distant past, raw.githubcontent.com URLs started requiring a SAS(?) token e.g., <https://raw.githubusercontent.com/Azure/azure-rest-api-specs/700d939f5839c513b7f0db0297755b6ca49aca1d/specification/cognitiveservices/data-plane/Language/preview/2023-11-15-preview/common.json> (probably expired by the time you read this). Pasting that into the OpenAPI Hub swagger diffing tool using the "Using OpenAPI Json file" option does enable the `Compare!` button but clicking on it does nothing. If you delete the query string, the button does navigate but the tool fails almost immediately (which is a welcome change opposed to waiting 20 minutes for a nondescript parsing failure) saying,

> Tool failed INVALID_PARAMETERS invalid request. expect json files but received non-json files

I imagine the tool is getting 404s trying to get the files, because that's what GitHub does without the `token` parameter. But seems the tool doesn't like query strings.

Use files in https://github.com/Azure/azure-rest-api-specs/pull/25817. I couldn't use the `readme.md` file because the tool fails on that with a nondescript error long after I submit the change (this has been typical for quite a while).

I appreciate OpenAPI Hub and swaggers tools aren't a priority, but we still support a ton of swagger-based services who are constantly working on updates. We need a reliable diffing tool. /cc @weshaggard @maririos @mikekistler

**Comment by JonathanCrd** [comment]
Closing this issue since OpenAPI Hub has been retired.
