### ISSUE TITLE
Comment links in the Conversation view are not redirecting people to the api code

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7228]
Reported by the Azure batch team, when they are in the `Conversations` tab and click on the line of code where the code is attached, the redirection takes the user to the main `api` page but to the beginning and not the specific line of code.
Note that the URL seems fine? 

- APIView review: https://apiview.dev/Assemblies/Review/11795f74eb564b8c8423f3d2f185b0ec

**Comment by maririos** [comment]
@chidozieononiwu  I know you are changing this view / or part of the code. Not sure if this will be fixed by it, so making a specific GH issue to track this.

**Comment by mario-guerra** [comment]
Pinging @dpwatrous for visibility.
