### ISSUE TITLE
Add APISpecDefinition to the Release Plan Work Item 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7230]
I am working on the queries for tracking TypeSpec.  There is not a way for me to filter just on TypeSpec in the tree/direct link queries.  We need to add the APISpecDefinition Type to the Release Plan.  We already have fields to represent if the SDKs are new initial releases or new versions. It makes sense that we capture the TypeSpec vs OpenAPI for the Release Plan, since this is a priority for our team (onboarding teams to TypeSpec).  Otherwise, we end up with Release Plans that are OpenAPI and TypeSpec and that is more data to have to sort through. 

Here is the query - https://dev.azure.com/azure-sdk/Release/_queries/query/73061ee1-a6e4-4241-8f01-0fda58f53c04/ 

I have already added the field to the Release Plan template.  So all is left is to ensure it gets populated when the release plans are created and also we need to update already created release plans.  There are only 16 release plans with an APISpecDefinition of TypeSpec, so I can manually change those quickly.  No need to create and one a Cloud Flow for updating the existing release plans.

**Comment by maririos** [comment]
@ladonnaq this information is in the API Spec work item. Why not just add it to the query?
<img width="773" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/a9d739ad-261a-440a-8f73-26537bb84021">

This is already filtering what you want with no need to create a new field. 
I really want to avoid having duplicated information. So if this satisfy your request, please delete the field you created in the Release Planner work item template

**Comment by ladonnaq** [comment]
> @ladonnaq this information is in the API Spec work item. Why not just add it to the query? <img alt="image" width="773" src="https://user-images.githubusercontent.com/9868623/280139961-a9d739ad-261a-440a-8f73-26537bb84021.png">
> 
> This is already filtering what you want with no need to create a new field. I really want to avoid having duplicated information. So if this satisfy your request, please delete the field you created in the Release Planner work item template

Yes it is working in this query - not sure why it was not working earlier but I am exhausted and have spent way too much time the last 2 weeks in queries. :-)  However, I can't generate any charts in a non-flat ADO query to add to the ADO Dashboard so they would just have query tiles.  So to get charts need flat query and I would need a way to identify at the release plan work item level that is it TypeSpec.  Since we are identifying the library type there and SDK release target month, thought it may make sense to also identify the API Spec type there as well.  Go to this query and look at charts and you will see what I mean - https://dev.azure.com/azure-sdk/Release/_queries/query-charts/9133ca54-cc09-4113-8964-6984e75b256c/.

**Comment by maririos** [comment]
If we can't do charts because of a limitation on the tooling, then we should use another tooling. We shouldn't duplicate data across our work items
