### ISSUE TITLE
Service Team Blocked - The release planner is blocking teams at the "schedule API review" or "schedule SDK review" 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7232]
We have teams that are mid-stream in completing their work for upcoming launches and they are adopting the release planner to complete the work.  Many of the teams have already completed the REST API Review and the SDK Reviews.  

Can we stop blocking teams on this step?  Or is there a way for them to indicate they already have completed the meeting so they can bypass.  

I am getting this feedback for data and management plane.  For management plane, I have a call scheduled next week with Josephine and Arthur to discuss what we do.  Right now every management plane team will be blocked b/c they can't bypass the SDK Review, which we are not told is not required. Instead, Arthur is reviewing when they submit the .NET PR to approve.

**Comment by maririos** [comment]
dup of https://github.com/Azure/azure-sdk-tools/issues/7166
