### ISSUE TITLE
[SDK Automation] The check `SDK $(sdkName)` is stuck `in progress` when AutoRest config (README.md) does not define any language SDKs

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#7235]
## PR where this issue was first observed

- https://github.com/Azure/azure-rest-api-specs-pr/pull/15700
- As discussed here https://github.com/Azure/azure-rest-api-specs-pr/pull/15700#issuecomment-1793010379

### Check is stuck

The following check is stuck on the PR in progress:

![image](https://github.com/Azure/azure-sdk-tools/assets/4429827/e1e8a943-55cc-4d2c-b6a4-f7c7179377b1)

### ADO pipeline task `SDK / SDK Automation` logs fatal error with `$(sdkName)`

An [example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3232772&view=logs&j=fe340961-61f6-52e3-0065-17370d33fdc8&t=ab4aa5f2-ce64-5f4d-f35b-589922884781&l=19):

```
06:41:54.455 error 	Fatal error: Error: SDK $(sdkName) is not define in SpecConfig
    at Object.exports.getSdkRepoConfig (/mnt/vss/_work/1/a/unified-pipeline-runtime/private/openapi-sdk-automation/lib/types/SpecConfig.js:41:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async workflowInitConfig (/mnt/vss/_work/1/a/unified-pipeline-runtime/private/openapi-sdk-automation/lib/automation/workflow.js:234:27)
    at async Object.exports.workflowInit (/mnt/vss/_work/1/a/unified-pipeline-runtime/private/openapi-sdk-automation/lib/automation/workflow.js:70:29)
    at async Object.exports.sdkAutoMain (/mnt/vss/_work/1/a/unified-pipeline-runtime/private/openapi-sdk-automation/lib/automation/entrypoint.js:210:31)
    at async /mnt/vss/_work/1/a/unified-pipeline-runtime/private/openapi-sdk-automation/lib/cli/cli.js:20:18
```

### ADO pipeline task `Filter SDK / SDK Automation` reports no language SDKs to generate

In ADO pipeline, `Filter SDK / SDK Automation` task does not list any language repositories. 

[An example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3232772&view=logs&j=5b9ddb1d-0a4c-5b60-5f43-d992eb6e5840&t=5aaf2286-0a7d-520b-4a04-1c6b6d38f79b&l=34): 

```
06:40:29.047 section 	Filter SDK to generate
06:40:29.056 info 	SDK to generate:
06:40:29.056 warn 		azure-resource-manager-schemas not found in specificationRepositoryConfiguration.json. Skipped.
06:40:29.056 warn 		azure-cli-extensions not found in specificationRepositoryConfiguration.json. Skipped.
06:40:29.057 endsection 	Filter SDK to generate
```

Contrast it with an [example](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3232544&view=logs&j=5b9ddb1d-0a4c-5b60-5f43-d992eb6e5840&t=5aaf2286-0a7d-520b-4a04-1c6b6d38f79b&l=23) working case from [PR 26555](https://github.com/Azure/azure-rest-api-specs/pull/26555):

```
04:49:57.830 section 	Filter SDK to generate
04:49:57.840 info 	SDK to generate:
04:49:57.840 info 		azure-sdk-for-python-track2
04:49:57.840 info 		azure-sdk-for-java
04:49:57.840 info 		azure-sdk-for-go
04:49:57.840 info 		azure-sdk-for-js
04:49:57.841 info 		azure-resource-manager-schemas
04:49:57.841 warn 		azure-cli-extensions not found in specificationRepositoryConfiguration.json. Skipped.
04:49:57.841 info 		azure-powershell
04:49:57.842 endsection 	Filter SDK to generate
```

## Root-cause

The affected PR did not define in the AutoRest config (`README.md`) any language repository. The `SDK Automation` tooling doesn't gracefully handle this scenario, resulting in the fatal error with `$(sdkName)` as mentioned above.

You can observe in the PR [the following snippet in the README](https://github.com/Azure/azure-rest-api-specs-pr/pull/15700/files#r1382182017):

```
yaml $(swagger-to-sdk)
swagger-to-sdk:
  - repo: azure-resource-manager-schemas
  - repo: azure-cli-extensions
```

If this config would include a line with `azure-sdk-for-*` for one of the supported languages, it would prevent the issue. An example of valid config can be found [here](https://github.com/Azure/azure-rest-api-specs/blob/4f2b6b0d8a206618e365ba0babdc14a1cc830ba0/specification/app/resource-manager/readme.md?plain=1#L277), e.g. `- repo: azure-sdk-for-js`.

# Relevant source code

- Code parsing `swagger-to-sdk` yaml tag [is located within `findSwaggerToSDKConfiguration`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=public/azure-js-dev-tools/lib/autorest.ts&version=GC3d8eb4c1fd2cd145473276e8490afc8954b8fc80&line=327&lineStartColumn=11&lineEndColumn=60&_a=contents).
- The `findSwaggerToSDKConfiguration` is called by [workflowFilterSdkMain](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-sdk-automation/src/automation/workflow.ts&version=GCe9ef1b8bbfd823030e51363452b86c1db4941df0&line=151&lineStartColumn=14&lineEndColumn=35&_a=contents), which plumbs the information from `swagger-to-sdk` yaml tag to ADO pipeline variables. Notably to the [`EnabledJobs` variable](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-sdk-automation/src/automation/workflow.ts&version=GCe9ef1b8bbfd823030e51363452b86c1db4941df0&line=203&lineStartColumn=3&lineEndColumn=107&_a=contents) with property of `sdkName` for each entry.
- Then the `EnabledJobs` variable gets used as input to the matrix strategy in `SdkGen` job [within `SDKAutomation.yml`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/azure-rest-api-specs-pipeline/.azure-pipelines/SDKAutomation.yml&version=GC96a63a3533c797c423b1cfba747dd2d3f6be1da1&line=45&lineStartColumn=1&lineEndColumn=79&_a=contents).
- Each entry of the strategy calls `RunSDKAutomation.yml` where [it passes `$(sdkName)` as value of `SDK_REPO_NAME`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/azure-rest-api-specs-pipeline/.azure-pipelines/templates/RunSDKAutomation.yml&version=GC18a68db6a17ad44522c53c18bea3dabebfc84082&line=44&lineStartColumn=5&lineEndColumn=30&_a=contents).
- The `SDK_REPO_NAME` is then used within `schema.ts / SDKAutomationCliConfig` as [sdkRepoName / env](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-sdk-automation/src/cli/config/schema.ts&version=GC18a68db6a17ad44522c53c18bea3dabebfc84082&line=101&lineStartColumn=11&lineEndColumn=24&_a=contents) which is loaded up by [`cli.ts` for SDK automation](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-sdk-automation/src/cli/cli.ts&version=GC115e6add74598b0274b319aaef796cf3ccc55337&line=16&lineStartColumn=3&lineEndColumn=41&_a=contents) and [passed to `sdkAutoMain` invocation as `sdkName`](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=/private/openapi-sdk-automation/src/cli/cli.ts&version=GC115e6add74598b0274b319aaef796cf3ccc55337&line=26&lineEnd=26&lineStartColumn=7&lineEndColumn=34&lineStyle=plain&_a=contents).
- The data then flows from `entrypoint.ts / sdkAutoMain` to `workflow.ts / workflow` to `workflowInitConfig` to `getSdkRepoConfig` where [it throws the fatal error](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-alps?path=private/openapi-sdk-automation/src/types/SpecConfig.ts&version=GCe9ef1b8bbfd823030e51363452b86c1db4941df0&line=61&lineEnd=63&lineStartColumn=1&lineEndColumn=4&_a=contents).

@raych1 FYI

**Comment by raych1** [comment]
I agree this is a bug around error handling, but this is an edge case. `Swagger-to-sdk` config in readme is required config to generate SDK. 

I will put this bug in my backlog.

**Comment by konrad-jamrozik** [comment]
I observed that this bug is not triggered if there are no SDKs to generate and there is no autorest README, e.g. this PR:
- https://github.com/Azure/azure-rest-api-specs/pull/26754

doesn't trigger it.

**Comment by JackTn** [comment]
new issues example: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4075365&view=logs&j=5b9ddb1d-0a4c-5b60-5f43-d992eb6e5840&t=5aaf2286-0a7d-520b-4a04-1c6b6d38f79b

**Comment by raych1** [comment]
Test PRs:
[[test pr 575396] test scenario 1 filter sdk step error by JackTn · Pull Request #30990 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/30990/checks?check_run_id=31436851832)
[[test pr 575396] test scenario 2 swagger to sdkconfg is missing by JackTn · Pull Request #30991 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/30991/checks?check_run_id=31436851200)
[[test pr 575396] test scenario 3 not find correct language by JackTn · Pull Request #30992 · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/pull/30992/checks?check_run_id=31436879775)
