### ISSUE TITLE
Update PowerBi report for Release Planner app

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7245]
Questions we want to answer per month:
- Products onboarded. Be able to aggregate by:
   - [x] Service
   - [x] API Scope (Management vs data plane)
- Number or Release plans created. Agreggate by:
   - [x] Product
   - [x] Product lifecycle
   - [x] API Scope (Management vs data plane)
   - [x] SDK type to be released
   - [x] Status
   - [ ] ~~Status of the milestone~~

**Comment by maririos** [comment]
> Number or Release plans created. Agreggate by: Status of the milestone

The more I thought about it, I think it doesn't make sense here. This will tell us the progress of a Release Plan and that sounds more like something that belongs in the dashboard and not in our PowerBI usage.
That to say, you can ignore this

**Comment by JonathanCrd** [comment]
PowerBI report has been updated in the Azure SDK workspace
