### ISSUE TITLE
[bug][.net analyzer] ignore property bag class with suffix `Options`

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-tools#7247]
## Problem

In [AZC0030](https://github.com/Azure/azure-sdk-tools/blob/41c4ad12414f0aaa2b679bee62be7a89a61ee3c0/src/dotnet/Azure.ClientSdk.Analyzers/Azure.ClientSdk.Analyzers/ModelName/GeneralSuffixAnalyzer.cs#L21), we will report a warning if a model class name ends with `Options`. However, our property bag class will have an `Options` suffix. That causes false alerts, like https://github.com/Azure/azure-sdk-for-net/pull/39653/checks?check_run_id=18337868902

> sdk/integrationspaces/Azure.ResourceManager.IntegrationSpaces/src/Generated/Models/BusinessProcessCollectionGetAllOptions.cs(14,26): Error AZC0030: Model name 'BusinessProcessCollectionGetAllOptions' ends with 'Options'. Suggest to rename it to 'BusinessProcessCollectionGetAllConfig' or any other appropriate name.

`BusinessProcessCollectionGetAllOptions` is a property bag. We should ignore such cases in AZC0030

**Comment by shrutijha041100** [comment]
Hi, I am facing the same issue with my model class name ending in "Parameter" ending in the error AZC0030. What can I do?

**Comment by archerzz** [comment]
> Hi, I am facing the same issue with my model class name ending in "Parameter" ending in the error AZC0030. What can I do?

@shrutijha041100 Ordinary models should avoid `Parameter` suffix. You can rename the model, see here for details: https://github.com/Azure/autorest.csharp#rename-a-model-class
