### ISSUE TITLE
Allow admins to select any date from the calendar

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#7260]
The calendar only lets user to choose dates from 2 days in advance, but sometimes admins wants to re-schedule meetings or schedule new ones on the same or next day.

We should let admins choose whatever day they want, and even think about letting them choose any hour too.

**Comment by maririos** [comment]
Yes! We def need this. This is a dup of https://github.com/Azure/azure-sdk-tools/issues/7137
