### ISSUE TITLE
tsp-client doesn't use emitter-package-lock.json or `npm ci`

### ISSUE THREAD

**Issue by hallipr** [Azure/azure-sdk-tools#7283]
When copying emitter-package.json in the temporary generation folder, tsp-client should also copy emitter-package-lock.json if it's present.
https://github.com/Azure/azure-sdk-tools/blob/2c51c84ba5c1fa351bef1e79b519fc74166a550d/tools/tsp-client/src/index.ts#L156-L157

When installing node modules for client generation, tsp-client always uses `npm install`.  It should use `npm ci` if a `package-lock.json` file is present.
https://github.com/Azure/azure-sdk-tools/blob/2c51c84ba5c1fa351bef1e79b519fc74166a550d/tools/tsp-client/src/npm.ts#L23

Also, `--no-lock-file` isn't a valid option for `npm install`.  `npm install` just fails to complain about invalid options:

```
> npm install --invalid-option

up to date, audited 115 packages in 431ms
```

**Comment by catalinaperalta** [comment]
Closing as completed since v0.5.0.
