### ISSUE TITLE
[Breaking Change] Make openapi-diff runnable locally and write CONTRIBUTING.md for it

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#7290]
Similar to what we have for LintDiff:
https://github.com/Azure/azure-openapi-validator/blob/main/CONTRIBUTING.md

Relevant repo: https://github.com/Azure/openapi-diff

**Comment by mikekistler** [comment]
I have fixes for these in my local fork. I'll submit a PR and tag you to review.

**Comment by konrad-jamrozik** [comment]
PR submitted by @mikekistler 

- https://github.com/Azure/openapi-diff/pull/284
