### ISSUE TITLE
APIView used last stable as base version rather than a newer preview

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#7295]
The APIView for [PR 26294](https://github.com/Azure/azure-rest-api-specs/pull/26294) included the stable API version 2022-12-01 as the base version

![image](https://github.com/Azure/azure-sdk-tools/assets/85643503/9498397a-36de-4211-bd26-77161de4102d)

but this service had a newer preview 2023-05-01-preview that would have been a better base version (smaller diff).

![image](https://github.com/Azure/azure-sdk-tools/assets/85643503/7dde4ba0-e371-4b48-a7ff-80e1359d85d3)

Ideally both the APIView would include both versions to allow users to see either one as needed, but if there is only one base version then I think it should be the most recent preview rather than an older stable version.

**Comment by maririos** [comment]
With the recent changes to APIView, this shouldn't be an issue anymore as the user can select which base version to compare their changes to.
If this happens again, let us know
