### ISSUE TITLE
ApiView: Show a list of all unresolved comments and a link to the revision they were added

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-tools#730]
It's hard to track unresolved comments across API changes when the feature team updates ApiView frequently.  I would love an optional tab next to "Revisions" called "Unresolved" that lists every unresolved comment, links to the ApiView revision where the comment was added, and optionally includes which revision made it hidden.

https://apiview.dev/Assemblies/Review/cf2c57b3d4c44ef08c2e8284f7441a2d is a good example of how this feature would be really useful.

**Comment by pakrym** [comment]
done
