### ISSUE TITLE
Automatically apply PR labels based on changes in PR

### ISSUE THREAD

**Issue by mitchdenny** [Azure/azure-sdk-tools#734]
Based on a request from @ramya-rao-a we want to have a mechanism that knows how to apply a label based on the changes in a pull request. This would use the existing ```CODEOWNERS``` file if possible. At the moment the ```@``` symbol is used on each line of the ```CODEOWNERS``` file to designate a user who is responsible for files that match that pattern. My proposal is that we make use of another symbol (for example ```%``` to designate a label). Hopefully the ```%``` symbol would be gracefully ignored by GitHub itself.

**Comment by danieljurek** [comment]
Docs say CODEOWNERS syntax follows .gitignore syntax: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax .. but little else about a % symbol. 

A quick perusal of the Notification Configuration tool shows that it gracefully ignore words that start with a `%` character. 
 -- https://github.com/Azure/azure-sdk-tools/blob/master/tools/notification-configuration/github-codeowner-subscriber/Program.cs#L125

**Comment by mitchdenny** [comment]
Closing this down. @AlexGhiondea came up with an alternative solution.
