### ISSUE TITLE
[PR Workflow] Allow PR authors to merge their PRs once the automated merging criteria is met 

### ISSUE THREAD

**Issue by rkmanda** [Azure/azure-sdk-tools#7354]
We want to make the ARM swagger PR review process more self-serve. One step towards that is to allow PR authors to merge their own PRs without having to wait for the reviewer to press the merge buttons.

When the PR author requests a merge today, once all required checks pass, the only thing the API reviewer does is to approve the PR and then merge it.

Sometimes there are delays in doing this as the reviewer may be busy with other API reviews or there are holidays in certain timezones or there is a very urgent need from the RP team to perform the merge and they cannot wait until the next business day for the merge to happen. This causes frustration for the PR author and can be easily avoided by giving them merge privileges.

We have developed a lot of confidence over past many months in the automated merging requirements check and we should now make the merge action self-serve.

There is a danger that the PR authors may add all the required labels for a merge and bypass the review process now that they have the ability to merge PRs on their own, however, we are willing to place some trust in our fellow engineers to do the right thing. We can also augment this with some periodic audits, lets say once a month to catch any such attempts.

**Comment by weshaggard** [comment]
Related to https://github.com/Azure/azure-sdk-tools/issues/7648 which is about data-plane merges.

**Comment by weshaggard** [comment]
This work has been completed.
