### ISSUE TITLE
Following release plan link is not taking me to the release plan

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7360]
Instead, it takes me to the Release Plan tool with the service I last selected.
To repro:
1. I have `.NET Core` as my service in the tool
2. Click on the link of another team's Release Plan: https://apps.powerapps.com/play/e/ed2ffefd-774d-40dd-ab23-7fff01aeec9f/a/821ab569-ae60-420d-8264-d7b5d5ef734c?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47
3. It takes me to Home page of the tool with the `.NET Core` service selected

**Comment by maririos** [comment]
@JonathanCrd I wonder if this regression started because of the work in https://github.com/Azure/azure-sdk-tools/issues/6842

**Comment by JonathanCrd** [comment]
@maririos Where did you get that link from?
The URL is missing the query param `release-plan-id`, that's why it is taking you to the home page instead of the release plan.

Share links in PROD looks something like this: `https://aka.ms/sdk-release-planner?release-plan-id=<id>`

Maybe they copied the URL from the browser (which is static through the app)

**Comment by maririos** [comment]
> @maririos Mariana Rios Flores FTE Where did you get that link from? The URL is missing the query param `release-plan-id`, that's why it is taking you to the home page instead of the release plan.
> 
> Share links in PROD looks something like this: `https://aka.ms/sdk-release-planner?release-plan-id=<id>`
> 
> Maybe they copied the URL from the browser (which is static through the app)

ohh for the user. They sent me 3 links and I never verified. Thank you for that :)

**Comment by JonathanCrd** [comment]
Tell them to use the link from the "Share this release plan" card:
![image](https://github.com/Azure/azure-sdk-tools/assets/17486462/a17e27af-b142-4da6-88c5-16d0c640f9f7)


This gave me an idea, probably people are not aware that the URL from the browser is static. I'll think about how I can improve this.

**Comment by JonathanCrd** [comment]
Tell them to use the link from the "Share this release plan" card:
![image](https://github.com/Azure/azure-sdk-tools/assets/17486462/6da3b9a4-9259-4e75-a1e6-bc9a6a12cba0)

This gave me an idea; people might not be aware that the URL from the browser is static. I'll think about how I can improve this.
