### ISSUE TITLE
APIView column-based layout becomes row-based on small enough viewports.

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-sdk-tools#741]
As the title says, on my laptop certain API reviews push the review content to the bottom of the page far underneath the sidebar, as opposed to next to it, see the screenshot here:

![image](https://user-images.githubusercontent.com/29314371/86183223-66503b80-bae6-11ea-90da-5b0324d8858b.png)

This can be addressed in a few ways.  The naive fix I use to "just make it happy locally" is to remove the flex-wrap from the parent element as seen here.

![image](https://user-images.githubusercontent.com/29314371/86183089-18d3ce80-bae6-11ea-9086-e785d725a94b.png)

but this may have side effects; I would likely move to a pattern wherein a naive flex-column approach is used, and the leftmost column is constrained by windowsize, with the remaining columns left to fill the space.

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/2785
