### ISSUE TITLE
Scan source for documentation issues

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#743]
Could we add support to DocWarden to scan source for comment-based doc violations? For example, references to docs.microsoft.com should *not* include the culture (e.g. "en-us") in the URL. The service will user the browser's preferred language(s) to direct the user to the appropriate language automatically. The Docs Authoring Pack (docsmsft.docs-authoring-pack) for VSCode, for example, checks this for .md files, but recently @mairaw has graciously been submitting PRs to fix the same violation in .cs files. This makes our comment-based docs much more accessible to users and doesn't need to understand much about the source language. In fact, for this particular rule it may not even have to understand different syntaxes for comments since it could just scan for any URL for docs.microsoft.com (though, admittedly, that's a pretty specific rule and not really generalized).

**Comment by weshaggard** [comment]
@KarishmaGhiya this type of link guidance rules should fit in with the other link validation stuff you are working on. We probably should add a rule to the link guidance and then add it and any other link checks in our verify links script.

**Comment by sima-zhu** [comment]
We are going to enable the locale checking in PR: https://github.com/Azure/azure-sdk-tools/pull/895

**Comment by sima-zhu** [comment]
We have enabled the check of the culture in md now. 
As far as I know, documentation has more rules need to follow besides of culture check in doc.microsoft.com. So it is better to have language to set and check its own rule sets.
Close this one. Please reopen another issue if it has to do documentation scan.
