### ISSUE TITLE
Hero scenarios link validation is failing

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7432]
A user is trying to add hero scenarios link to the SDK archboard meeting and is getting `invalid link` even though the link is correct.

Ping me for the link

**Comment by JonathanCrd** [comment]
This is an issue with the Regex that is most like in all of the apps.

**Comment by JonathanCrd** [comment]
I updated the regex for all URL fields in API Review, SDK Review and Informational apps. (Except for ApiView links)
