### ISSUE TITLE
Epics with state = New

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7447]
I was using the ADO data to create graphs and determine any trends for APEX data.  I noticed that there are quite a few products with a state=New.  The state should match the state of the lifecycle of the product.  This should be job/cloud flow that runs on a schedule so that our ADO data is always accurate.  I recognize a most of the products as APEX products so they should have the state updated.  Can someone help me investigate and figure out what needs to be done to clean up the query?  

https://dev.azure.com/azure-sdk/Release/_queries/query-edit/fa0d725a-db96-48fc-9f0f-6a76670d2380/

**Comment by maririos** [comment]
@praveenkuttappan as part of the work validating the prerelease script , could you check this issue and see if it is related?

**Comment by ladonnaq** [comment]
@praveenkuttappan - FYI I am still concerned that some of the epic products with state of New should have their states updated by the cloud flow you are running to keep the other products in synch with service tree.   
When I edit the product query to show epic-products with state of New as well, most appear to be duplicates.  However, there are a few products that are GA that I think need to be included in the cloud flow so that their state is updated.  These teams will likely be using release plans for post-GA work so want to make sure that the epic-product is in our query. 
What is the best approach to sorting this out?  I don't think there are that many - seems to be mostly GA products.  Should I send you link to the epics that I believe should be updated.

**Comment by maririos** [comment]
@praveenkuttappan and @ladonnaq met and marked some of the duplicated work items. 
This is done

**Comment by maririos** [comment]
@ladonnaq can u confirm?

**Comment by ladonnaq** [comment]
Praveen helped me and it is sorted out!
