### ISSUE TITLE
Purpose of the Launch date

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7469]
- What is the purpose of the `Launch Date` ? 
- Should it be related to the Launch type?
- Right now it is the `Target date` for the product, which is not linked to the launch type.

Thsi is the Service Tree information for this product: https://microsoftservicetree.com/products/2f8ac231-74e7-4980-83c4-16dfc1e725a3/metadata/Lifecycle%20Status

<img width="275" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/b1877455-94b6-4e35-a184-d72fd237712a">

**Comment by ladonnaq** [comment]
> * What is the purpose of the `Launch Date` ?
> * Should it be related to the Launch type?
> * Right now it is the `Target date` for the product, which is not linked to the launch type.
> 
> Thsi is the Service Tree information for this product: https://microsoftservicetree.com/products/2f8ac231-74e7-4980-83c4-16dfc1e725a3/metadata/Lifecycle%20Status
> 
> <img alt="image" width="275" src="https://private-user-images.githubusercontent.com/9868623/290922717-b1877455-94b6-4e35-a184-d72fd237712a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3Mzg4NzYsIm5iZiI6MTcwNDczODU3NiwicGF0aCI6Ii85ODY4NjIzLzI5MDkyMjcxNy1iMTg3NzQ1NS05NGI2LTRlMzUtYTE4NC1kNzJmZDIzNzcxMmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDhUMTgyOTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg3NTNhZTY1ZmIyM2EyN2RjOTNjZGMxNTM4ZmJkODhkNTNkNzZkOTNkMDExMDc2NDBiMWVmOWMwYjc1MTViOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SxBF9Hi47Jf5lwYdB-v1oy93Mbamm3T-LQb_GKrk-2k">

@maririos The launch date is associated with the lifecycle milestone.   There is a current lifecycle (which is the lifecycle that the product is in right now and there will be a launch date for when it completed).  Then target lifecycle (which is what is coming next) will have a launch date and it is the target date for the upcoming product launch.  Let me give it some thought as to what we really want to show here.

**Comment by praveenkuttappan** [comment]
I assume the Launch date should be set to the date associated to Launch type selected which means if launch type is same as target launch type, then date will be target launch date.

If that's the case,  launch date will be empty if a Product has already GAed in life cycle.

**Comment by maririos** [comment]
> I assume the Launch date should be set to the date associated to Launch type selected which means if launch type is same as target launch type, then date will be target launch date.
> 
> If that's the case, launch date will be empty if a Product has already GAed in life cycle.

For now this looks good. My understanding from today's meeting is that we are going to eliminate this information from the app. @ladonnaq please confirm

**Comment by ladonnaq** [comment]
@maririos I will keep this issue in backlog and we can revisit in the future (when we simplify the API readiness app).

**Comment by maririos** [comment]
We can still remove this field from the view. That would be cheap and will help avoid confusion on users

**Comment by ladonnaq** [comment]
> We can still remove this field from the view. That would be cheap and will help avoid confusion on users

Removing it would be fine.

**Comment by maririos** [comment]
Apps that need to be updated:

- [ ] Data Plane API Readiness
