### ISSUE TITLE
API Readiness App API Spec State Changes not reflected in the API Spec work item

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7493]
Requirement:  When a user accesses the API readiness app and is working on steps, the API Spec work item state should be changed to "In Progress".

**Comment by ladonnaq** [comment]
Reminder for @ladonnaq -  Test this to see if it has been resolved.  If not, then move the issue to the epic for tracking the smaller line items - https://github.com/Azure/azure-sdk-tools/issues/7822

**Comment by maririos** [comment]
It hasn't been resolved
