### ISSUE TITLE
Update Azure SDK links on APEX Eng Hub pages 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7499]
APEX team moved pages from their deprecated wiki to Eng Hub in Dec/Jan without notifying anyone.  So there are now incorrect links on the APEX Eng Hub site - https://eng.ms/docs/cloud-ai-platform/azure-core/azure-core-pm-and-design/trusted-platform-pm-karimb/service-lifecycle-and-actions-team/service-lifecycle-actions-team/apex/media/launchingaproduct

**Comment by maririos** [comment]
@ladonnaq  is this still a thing?

**Comment by maririos** [comment]
@ladonnaq ping again :)

**Comment by maririos** [comment]
I am just going to remvoe a Release from here as it was been moving since Feb with no update

**Comment by ladonnaq** [comment]
I already updated the APEX pages in Feb and forgot to close the issue.  Thanks @maririos
