### ISSUE TITLE
Move Service Tree Link ADO Field to epic-service and remove from Triage to reduce duplication

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7508]
**Requirement:** In order to reduce duplication, move the service tree link to epic-service and remove from the triage work item.  

**Work Item:** Epic-Service
**Work Item Field Label:** Service Tree Link
**ADO Field Name:** ? - currently do not have permissions to view the work item template to get the field name 
**Data Source:** Service Tree 
**Action:** To reduce duplication remove this field from Triage work item.  Add or ensure field is in epic-service work item.  The field value should be the service tree link for the service that the product maps to in Azure Devops. 

See this spreadsheet  - https://microsoft-my.sharepoint.com/:x:/p/ladonnaquinn/ETD9YCt4cfxHlL4mC1KlVygBIQss1mm6NMIpu3_BdOJhJQ?e=mgfST9&nav=MTVfe0RENEM1MzJDLUNCMkItNEJFRS1CNTAwLUE3RDMzMTE4MkRGQX0

**Comment by maririos** [comment]
After taking a look with @praveenkuttappan the action items are:
- Hide service tree link and product tree link from the Triage work item
- Add a service tree link in the Epic - service section
