### ISSUE TITLE
[Python APIView] doesn't indicate variadic arguments (*args)

### ISSUE THREAD

**Issue by chlowell** [Azure/azure-sdk-tools#752]
For example, [this code](https://github.com/Azure/azure-sdk-for-python/blob/a8796e37d045861b68bb9b3beed8e75b9520e592/sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py#L41):
```py
def get_token(*scopes, **kwargs):
  # type: (*str, **Any) -> AccessToken
```

Produces this json:
```json
{
    "Kind": 5,
    "DefinitionId": "azure.identity.AuthorizationCodeCredential.get_token.param(scopes",
    "Value": ""
},
{
    "Kind": 0,
    "DefinitionId": "azure.identity.AuthorizationCodeCredential.get_token.param(scopes",
    "Value": "scopes"
}
```

And looks like this in apiview:
![image](https://user-images.githubusercontent.com/10964656/86397654-16de4c80-bc59-11ea-8f5d-2d9fbee060d1.png)

... making `scopes` look like a single string argument when it's actually an arbitrary number of positional string arguments.

**Comment by tjprescott** [comment]
@chlowell PR #2479 should address this for you, assuming your code has Python 3-style type hints somewhere. APIView does not actually parse Python 2-style type hints for anything except return types, but it will work with a Python 3-style type hint:

```Python
  def with_variadic_type(self, *vars: str, **kwargs):
        return None
```

Per https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html#when-you-re-puzzled-or-when-things-are-complicated the type here for vars should be `str`, not `*str`.
