### ISSUE TITLE
Add env var with git commit hash to stress test build

### ISSUE THREAD

**Issue by lmolkova** [Azure/azure-sdk-tools#7521]
I'd like to have a recorded git commit hash of the code being tested in my stress tests.
Having something like `--build-arg GIT_COMMIT=$(git rev-parse HEAD)` in the stress test deployment script would allow anyone to use this as they see please (e.g. stamp on telemetry for troubleshooting/reporting later)

EDIT (@benbp): Also add job/pod labels for git commit sha, so that queries can use the git commit to locate pods running it.

**Comment by benbp** [comment]
Similar to https://github.com/Azure/azure-sdk-tools/issues/4644 I'm going to close that one and add it to this.
