### ISSUE TITLE
Two meetings scheduled for the same day

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-tools#7531]
Currently there are two meeting scheduled for Feb 20th on the Azure SDK Review calendar. 
I'm not sure how this happened, but it may have to do with the fact that one meeting was schedule by me (an admin, maybe??).

**Comment by ronniegeraghty** [comment]
Update: I reschedule the meeting I scheduled to the following day but the scheduling tool is now showing the Feb 20th time slot as available even though [this meeting](https://github.com/Azure/azure-sdk/issues/7103) is scheduled for that day.

**Comment by maririos** [comment]
@JonathanCrd I believe you fixed this already and deployed the changes.
@ronniegeraghty  any other cleanup we should do? or all good now.

**Comment by ronniegeraghty** [comment]
> @JonathanCrd I believe you fixed this already and deployed the changes. @ronniegeraghty any other cleanup we should do? or all good now.

No, removing the timeslot from the calendar stops the date from showing as available.

**Comment by maririos** [comment]
I looked at the DB to understand why the space was being shown if a neeting was already scheduled. IT turned out that the meeting for 2/20 didn't have the type of meeting. I updated this and will keep an eye in case this happens again so we can triage it.

Thanks @ronniegeraghty
