### ISSUE TITLE
Resource Cleanup Improvements

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#754]
We've run into issues where live test resources have been left behind by canceled and timed out tests. We've had to manually query for and delete these resources when this happens. Let's improve how our automation handles this: 

Things to do: 

* [x] Always delete resources (remove `succeededOrFailed()` condition) 
* [x] Reduce `DeleteAfter` time -- this time is set arbitrarily but we are not aware of anyone going back to investigate a live test resource left behind during a timed out or canceled run so shortening this time can return resources faster

Things to consider: 

* [x] Run cleanup more frequently -- Perhaps every hour. It doesn't use much agent time (6 minutes max according to the run history) 
* [x] Run the cleanup process as an Azure Function and have the job run as a server job so that we don't eat up agent time

**Comment by weshaggard** [comment]
We should also try to kick off the clean-up asynchronously so we don't have to block

**Comment by mikeharder** [comment]
@benbp: I think we should prioritize async cleanup since it can save a lot of time on our limited internal agents.

**Comment by weshaggard** [comment]
@benbp  reopening as I think we might still want to do some of the other things in the list as well. Your PR fixed the async nature but are there other improvements we might want to enable.

**Comment by benbp** [comment]
Closing because I've increased frequency, reduced expiration, and added async deletion. Running delete in a function is not addressed, but because of the frequency increase, the cleanup job takes <1 minute now, so I don't think agent quota is a concern.
