### ISSUE TITLE
Create a release plan - add a question to identify if the Beta or Stable SDK is a initial release (no previously released SDKs) 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7550]
Requirement:  There are additional requirements for initial Beta and initial Stable SDK releases.  Confirming this information when the release plan is created will enable us to ensure that the release plan has all of the steps/guidance for initial SDK releases.  Today we ask the service teams during onboarding and manually update the triage ADO field that contains this data.  Any manual data updates made to ADO Fields are prone to error.  Having user confirm during creation of the release plan should provide better quality of data. 

TODO: Draft requirement and meet with @JonathanCrd to discuss UI, backend, and dashboard.

**Comment by maririos** [comment]
@ladonnaq  Is this the same as https://github.com/Azure/azure-sdk-tools/issues/7492 ?

**Comment by ladonnaq** [comment]
Closing as duplicate of https://github.com/Azure/azure-sdk-tools/issues/7550.
