### ISSUE TITLE
Add APIView documentation for specs repo failures

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7559]
Add a section for APIView failures in the specs repo: https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/ci-fix.md

Informaiton we could add:
- What errors mean
- What to do
- Who to contact if nothing else works

**Comment by konrad-jamrozik** [comment]
> * Who to contact if nothing else works

Some info on that in [this pinned post](https://teams.microsoft.com/l/message/19:0351f5f9404446e4b4fd4eaf2c27448d@thread.skype/1689115217750?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1689115217750&teamName=Azure%20SDK&channelName=API%20Spec%20Review&createdTime=1689115217750)
