### ISSUE TITLE
[Java-Feature] Add WildCard, Union, Intersection types handler implementation feature.

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-tools#756]
To add below three new type implementation:

- [ ] Wild card type
- [ ] Union type
- [ ] Intersection type

**Comment by JonathanGiles** [comment]
@mssfang is this a feature request for API view, or something else? Is it still current or have these been supported? Are you able to give code saves of exactly what is not supported?

**Comment by mssfang** [comment]
@JonathanGiles it is because the Type could be WildCard, Union, Intersection types. I just added the else if statement for future reference. It is still not supported in APIView.

https://github.com/Azure/azure-sdk-tools/pull/751/files#diff-866fceddd51b11a1901ea992fd0ff7a4R708
```
  } else if (type.isWildcardType()) {
        // TODO: add wild card type implementation, #756
  } else if (type.isUnionType()) {
       // TODO: add union type implementation, #756
  } else if (type.isIntersectionType()) {
      // TODO: add intersection type implementation, #756
```

**Comment by mssfang** [comment]
Close it since I am no longer work on it
