### ISSUE TITLE
Remove "create a release plan" Info Meeting requirement for some scenarios 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7564]
Requirement:  Remove the block that was in place during initial deployment of the Release Plan feature.  

We should no longer block teams from creating a release plan.  It has been 3 months and we have updated all docs, process, and are actively engaging teams with launches between now and June 2024.   We should remove the block as at this time it is creating extra work and frustration (service partner has to schedule a meeting they may not need or find someone to remove the block so they can continue). 

Checks that should be done before allowing user's to create a release plan 
- Product must be onboarded before creating a release plan 
- Data plan release plans:  API Definition is TypeSpec, Data plane must be in scope, Info Meeting must be completed. 
- Management plane release plans:  Management plane must be in scope 

When should Info Meeting be prompted during Onboarding or before a release plan is created: 

- If unsure was selected for DataScope or MgmtScope, then Info Meeting required before the service partner creates a release plan.

**Comment by maririos** [comment]
@ladonnaq questions on the requirements:
> Data plan release plans: API Definition is TypeSpec

We want to remove this so release plans can also be created for OpenAPI specifications

> Data plan release plans: Data plane must be in scope

Is this determine by the field in the Triage work item `DataScope` ? same applies for management plane

**Comment by praveenkuttappan** [comment]
Looks like we have a bug in onboarding currently that set DataScope as `No` even if option unsure is selected in onboarding page. I will fix this to set Scope as unsure.

Question: Should we allow creating release plan for management plane even if unsure is selected or make informational meeting required whenever unsure is selected? Please note that there is no unsure option per management or data-plane. Option unsure is selected when product team is not sure whether they need to release management or data-plane.

@ladonnaq , @maririos  FYI...

**Comment by maririos** [comment]
> Looks like we have a bug in onboarding currently that set DataScope as No even if option unsure is selected in onboarding page. I will fix this to set Scope as unsure.

ohh thank you!

> Question: Should we allow creating release plan for management plane even if unsure is selected or make informational meeting required whenever unsure is selected? 

The later. Make informational meeting required whenever unsure is selected
