### ISSUE TITLE
decode-uri-component 0.2.0 is vulnerable

### ISSUE THREAD

**Issue by gaobob-msft** [Azure/azure-sdk-tools#7567]
Description
decode-uri-component 0.2.0 is vulnerable to Improper Input Validation resulting in DoS.

Recommendation
Upgrade decode-uri-component from 0.2.0 to 0.2.1 or above to fix the vulnerability.

https://github.com/Azure/azure-sdk-tools/blob/7226bac731fca3741fa12cc44ae207858d40939e/tools/sdk-generation-pipeline/common/config/rush/pnpm-lock.yaml#L2135

**Comment by kurtzeborn** [comment]
Not sure who this goes to on your team @lirenhe

**Comment by lirenhe** [comment]
The  code in sdk-generation-pipeline are removed.  So close this issue.
