### ISSUE TITLE
Create flow to abandon a release plan

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7571]
Right now this is a manual task, but it happens often-ish that to keep a record of the changes, it will be best to have a cloud flow. 
Also, avoid possible human error.

Logic is:
- Table `Base Worklfows`
- Find release plan in column `name`
- Change value of property `Workflow status` to `Abandoned`

**Comment by maririos** [comment]
This has been done. The name of the flow is `Abandon release plan` and it accepts the release plan number as input.
Right now it is using my connection reference:

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/3e77b476-4147-4784-816f-4c650102ad6a)

@JonathanCrd I tried to change the connection reference following https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/946/Troubleshooting?anchor=invalid-connection-for-cloud-flow-in-ppe-or-prod but double click didn't work. is it because I am in DEV? what is the right way to do it?

**Comment by JonathanCrd** [comment]
@maririos this flow hasn't been pushed to PPE, right?

To change the connection reference of the flow you have to log-in using the Bot account, and then edit the flow and select the proper connection in the actions that need them. For this case, all Dataverse actions. The proper connection is the one that has the Bot's email on it. Then Save the flow and that's it. Ideally, we would have one connection reference per service, the one that points to the connection owned by the Bot Account.

Now, if the connection reference is broken in PPE or PROD, it means that the connection that it's pointing does not exist or hasn't been setup yet. For that we would have to update the connection reference to point to the right connect, again, logged into the bot account.

Note how I'm making a distinction between connections and connections references. Briefly, Connections are set up and owned by a single user, per environment. They are the user's credentials for a particular service. Now, connection references point to those connections and belong to a solution. They can be used by other users and can be imported and exported to other environments. Think about them as a "proxy" for the real connection.

```mermaid
flowchart LR

A(Connection) 
C[Connection Reference]
E(CloudFlow 1)
F(CloudFlow 2)
G(CloudFlow n)


E --> C --> A
F --> C
G --> C

```

I already updated the connection references to the one linked with the Bot Account.

**Comment by maririos** [comment]
Thank you @JonathanCrd I added an entry in our wiki so next time I can follow that :)  
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/946/Troubleshooting?anchor=set-connection-for-cloud-flow-in-dev
