### ISSUE TITLE
Move deprecation document to Eng hub site

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7577]
https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/192/Azure-SDK-deprecation-strategy

**Comment by maririos** [comment]
FYI @ladonnaq

**Comment by mario-guerra** [comment]
@MrJustinB there was a reason we didn't migrate the deprecation doc when we did the mass migration from the wiki to Eng hub, but I don't remember what the reason was. Do you?

**Comment by ladonnaq** [comment]
@mario-guerra I am often asked by service partner what the process/steps they need to take to deprecate their APIs and SDKs.  I think it would be very helpful to move the relevant information from this doc to engineering hub.

**Comment by mario-guerra** [comment]
Okay, I can certainly do that. Where on eng hub do you think it makes the most sense to put it?

**Comment by ladonnaq** [comment]
@maririos Retirement should have its own section on engineering hub.  Can we add a top-level category for Retirement? Perhaps in between "Develop SDKs" and "Support".  If you agree, then @mario-guerra can add the section and start rewriting the docs. We can also cross-reference the links to Azure Docs (ARM, APEX program includes retirement, etc).

**Comment by maririos** [comment]
PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/962

**Comment by maririos** [comment]
Docs live: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-deprecation-guidelines

**Comment by maririos** [comment]
Old wiki doc updated to point to new place.
