### ISSUE TITLE
azure-sdk-for-net-track2 fails due to some model name and operation name warning

### ISSUE THREAD

**Issue by yifan-zhou922** [Azure/azure-sdk-tools#7589]
PR: 
[Feature/datamap tsp by yifan-zhou922 · Pull Request #26702 · Azure/azure-rest-api-specs (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-rest-api-specs%2Fpull%2F26702%2Fchecks%3Fcheck_run_id%3D20641525808&data=05%7C02%7Cyifanzhou%40microsoft.com%7Cdd440dc3ed0542ce5a0908dc1e100484%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638418301429510042%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=yvWC%2FIL4hsf0%2FiC5%2BuD4M3Iq0gSmJSYGBIqZShqQ3b0%3D&reserved=0)

![image](https://github.com/Azure/azure-sdk-tools/assets/78060542/1cb3608e-c195-4b8d-9710-3ae44c6c902e)

The errors are:
We want to suppress the rule for this model names to build the .net packages
- AutoCompleteOptions.cs(13,26): error AZC0030: Model name 'AutoCompleteOptions' ends with 'Options'. Suggest to rename it to 'AutoCompleteConfig' or any other appropriate name.
- ClassificationAssociateOptions.cs(14,26): error AZC0030: Model name 'ClassificationAssociateOptions' ends with 'Options'. Suggest to rename it to 'ClassificationAssociateConfig' or any other appropriate name.
- MoveEntitiesOptions.cs(14,26): error AZC0030: Model name 'MoveEntitiesOptions' ends with 'Options'. Suggest to rename it to 'MoveEntitiesConfig' or any other appropriate name.
- /QueryOptions.cs(15,26): error AZC0030: Model name 'QueryOptions' ends with 'Options'. Suggest to rename it to 'QueryConfig' or any other appropriate name. 
- SuggestOptions.cs(13,26): error AZC0030: Model name 'SuggestOptions' ends with 'Options'. Suggest to rename it to 'SuggestConfig' or any other appropriate name. 

We name several operation groups like Discovery/Entity/Relationship/Lineage/etc. This also cause the build failures. However, these issues do not exist in other languages
- Generated/Discovery.cs(19,26): error AZC0012: Single word class names are too generic and have high chance of collision with BCL types or types from other libraries 
- Generated/Entity.cs(21,26): error AZC0012: Single word class names are too generic and have high chance of collision with BCL types or types from other libraries
- /Glossary.cs(21,26): error AZC0012: Single word class names are too generic and have high chance of collision with BCL types or types from other libraries 
- Lineage.cs(19,26): error AZC0012: Single word class names are too generic and have high chance of collision with BCL types or types from other libraries
- Relationship.cs(19,26): error AZC0012: Single word class names are too generic and have high chance of collision with BCL types or types from other libraries

**Comment by raych1** [comment]
These are analyzer error caused by naming doesn't meet the requirements.
