### ISSUE TITLE
APIView emitter crashing on "case 90"

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#7593]
See https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3445077&view=logs&j=e37a1bb9-a190-5269-3a0e-37469dfbe682&t=09cb0672-20c5-5dce-4552-dad3f3e96fd3&l=180

The APIView emitter is failing with a weird error about "case 90". There are a bunch of warnings about invalid engines at the beginning, too.

**Comment by GrahamMThomas** [comment]
+1

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3448618&view=logs&j=e37a1bb9-a190-5269-3a0e-37469dfbe682&t=09cb0672-20c5-5dce-4552-dad3f3e96fd3

**Comment by hahahahahaiyiwen** [comment]
+1

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3448561&view=logs&j=e37a1bb9-a190-5269-3a0e-37469dfbe682&t=09cb0672-20c5-5dce-4552-dad3f3e96fd3

**Comment by tjprescott** [comment]
This has already been fixed.
