### ISSUE TITLE
docindex pipelines' CreateDocIndex job is failing

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#7601]
Succeeding image version: 20240122.1.0
Failing image version: 20240128.1.0

Failures likely related to a change in PowerShell: https://github.com/actions/runner-images/issues/9115

Two things to do: 
1. Fix script 
2. Change jobs to use 1ES pools instead of Azure Pipelines for better stewardship of resources... it's possible that the 1ES pipelines may use a different version of PowerShell, so ensure that the fix is backwards compatible.

**Comment by kurtzeborn** [comment]
Assigning this to you @JimSuplizio since Daniel is about to disappear for a few months.

**Comment by JimSuplizio** [comment]
Whatever was going on looks like it was fixed with the linked change Daniel made in Feb. Right now, the doc index runs are all on the same image version `Current image version: '20240807.2.0'` which the most recent and all of the doc index pipelines
