### ISSUE TITLE
[SDK automation] SDK automation for TypeSpec PRs in the rest repo need to consider multiple products under a service directory

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-tools#7603]
Services, like Health Insights, can provide multiple products under their general service definition, therefore we need to look for the tspconfig.yaml files for each product and run the SDK automation step for each one. 

For example, given the following TypeSpec project structure: 
```
- Health Insights/
  - main.tsp
  - tspconfig.yaml
  - OncoPhenoType/
    - client.tsp
    - tspconfig.yaml
    - <other product specific files>
  - RadiologyInsights/
    - client.tsp
    - tspconfig.yaml
    - <other product specific files>
  - TrialMatcher/
    - client.tsp
    - tspconfig.yaml 
    - <other product specific files>
  - ...etc
```

An automated SDK generation needs to be carried out for each of the Health Insights products listed under the main directory, in this scenario there would be an SDK automation run for each of the sub directories:  OncoPhenoType, RadiologyInsights, TrialMatcher, etc

cc @weshaggard

**Comment by weshaggard** [comment]
After talking with @raych1 I believe this scenario is supported the issue was related to another change that was breaking the automation. I'm going to close this but if that isn't the case please re-open with more details.
