### ISSUE TITLE
Add service tree link when onboarding a product

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7610]
When a team is onboarding, we should provide a link to the Service Tree instance so the user can verify which product they really want to onboard.
This is important when there are products with the same name but different type (offering vs sku).

An idea is to add the link like we do when creating a release plan:

![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/480f71f2-13e3-4685-ad1c-626073767684)

**Comment by maririos** [comment]
Open to more ideas too :)

**Comment by praveenkuttappan** [comment]
Updated the display name to show product type
