### ISSUE TITLE
Bug in `CI-MissingBaseCommit` logic

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7620]
Logic for label `CI-MissingBaseCommit` assumes the PR was created from OpenAPI Hub by looking at the name of the PR.
@JonathanCrd removed this functionality from OpenAPI Hub because there is no point on the tool creating a PR.

This broke the logic though. I think the check should look either into the content of the commits, or the name of the commits (that are generated from OpenAPI Hub).

Example of this: https://github.com/Azure/azure-rest-api-specs/pull/27607

**Comment by maririos** [comment]
@konrad-jamrozik as OpenAPI Hub team caused this, let me know if you would like our help here

**Comment by konrad-jamrozik** [comment]
Relevant logic:
https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps?path=/public/rest-api-specs-scripts/src/prSummaryProcessArmReview.ts&version=GBmain&line=82&lineEnd=83&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

Relevant comment added:
https://github.com/Azure/azure-rest-api-specs/blob/784dcbc568c61801a33dfe197cb785ffe22a9dec/.github/comment.yml#L6

What behavior and comment you folks would like to see?

**Comment by konrad-jamrozik** [comment]
[Pull Request 525956](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/525956): Get rid of CI-MissingBaseCommit

@maririos @weshaggard FYI

**Comment by konrad-jamrozik** [comment]
I just got rid of this label completely, as all it was doing was "if PR is not opened via with ShiftLeft or OpenAPI Hub, then add this label". Now both ways to open PRs via ShiftLeft and OpenAPI Hub are deprecated, hence this label makes no sense anymore.

**Comment by maririos** [comment]
> I just got rid of this label completely, as all it was doing was "if PR is not opened via with ShiftLeft or OpenAPI Hub, then add this label". Now both ways to open PRs via ShiftLeft and OpenAPI Hub are deprecated, hence this label makes no sense anymore.
> 
> If there was also an intent of someone adding this label manually, then since our team took over in beginning of 2023 nobody ever did this.

ohh nice. I thought there would be more logic behind the addition of this label. Like for example, if you didn't ad your base commit then your PR is wrong. 
But if that is not true, great! 

Thank you for taking a look and fixing it @konrad-jamrozik
