### ISSUE TITLE
Failed to execute Update-GitHubIssue

### ISSUE THREAD

**Issue by Alancere** [Azure/azure-sdk-tools#7621]
It was successful before, but it's a problem now.

Update-GitHubIssue: https://github.com/Azure/azure-sdk-for-go/blob/main/eng/common/scripts/Invoke-GitHubAPI.ps1#L367

pipeline failure link: https://teams.microsoft.com/l/message/19:b76b7ede-5516-43b4-96c2-f580fa4309d7_eaa95837-fda2-47de-949f-654b6771e436@unq.gbl.spaces/1706860464853?context=%7B%22contextType%22%3A%22chat%22%7D

### curl: (successful)
```
curl -L -X PATCH -H "Authorization: Bearer $env:GITHUB_TOKEN" https://api.github.com/repos/Azure/azure-sdk-for-go/issues/22333 -d '{"state":"open","labels":["Beta"],"assignees":[]}
```
#### Failure: The given key 'Content-Type' was not present in the dictionary.
```
Invoke-RestMethod -Method PATCH -Body '{"state":"open","labels":["Beta"],"assignees":[]}' -Uri https://api.github.com/repos/Azure/azure-sdk-for-go/issues/22333 -Headers @{"Authorization" = "Bearer $env:GITHUB_TOKEN"} -MaximumRetryCount 3
```
we ran this test locally using latest powershell 7.4.1.
#### Adding Content-Type in Headers was successful (Content-Type: "application/json")
```
Invoke-RestMethod -Method PATCH -Body '{"state":"open","labels":["Beta"],"assignees":[]}' -Uri https://api.github.com/repos/Azure/azure-sdk-for-go/issues/22333 -Headers @{"Authorization" = "Bearer $env:GITHUB_TOKEN"; "Content-Type" = "application/json"} -MaximumRetryCount 3
```

**Comment by raych1** [comment]
@weshaggard , do you know why this issue doesn't happen in eng sync pipeline? I haven't found the reason.

**Comment by weshaggard** [comment]
I cannot open the teams link for some reason. Can you directly link the failing build so I can have a look? I know that the new PS version has started rolling out to our pipelines and it has causes some encoding issues.

**Comment by Alancere** [comment]
Updated build link: https://[dev.azure.com/azure-sdk/internal/_build/results?buildId=3461611&view=logs&j=0ab14b9f-e499-56d5-97b1-fd98b70ea339&t=2e9e19b8-1db7-53d9-fe91-457c791ee9df](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3461611&view=logs&j=0ab14b9f-e499-56d5-97b1-fd98b70ea339&t=2e9e19b8-1db7-53d9-fe91-457c791ee9df)

<img width="387" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/46921893/6d4f961c-f337-4331-82b8-352814afb168">

**Comment by Alancere** [comment]
It appears that the definition of ContentType was changed in pwsh 7.4
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.4#-contenttype

**Comment by raych1** [comment]
@weshaggard content-type has to be set explicitly. Please review the PR which works for pwsh 7.4 and the previous version.

**Comment by kurtzeborn** [comment]
Pretty sure this has been fixed by @weshaggard already.

**Comment by weshaggard** [comment]
I believe this was fixed by https://github.com/Azure/azure-sdk-tools/pull/8275
