### ISSUE TITLE
Pipeline result fails to be published

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#7631]
## Problem
The SDK automation result of spec PR pipeline occasionally stuck in progress while the run actually finished. The reason is the `publishResult.js` fails to run with the following errors.

```pwsh
Script contents:
node node_modules/@azure/publish-pipeline-result/lib/publishResult.js --status completed --result failure --env prod --logPath pipe.log
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /mnt/vss/_work/_temp/9d471d97-da1a-4758-a9c9-1517e198c4d4.sh
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module '/mnt/vss/_work/1/s/node_modules/@azure/publish-pipeline-result/lib/publishResult.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v18.19.0

##[error]Bash exited with code '1'.
```

This is an example PR which has this issue for azure-sdk-for-js.
https://github.com/Azure/azure-rest-api-specs/pull/27585

**Comment by raych1** [comment]
It could be caused by npm install locally in JS automation script.

This issue happens for Java when install tsp-client locally but was fixed by global install - `npm install -g @azure-tools/typespec-client-generator-cli`.

**Comment by raych1** [comment]
The root cause is the `node_modules` folders are renamed by JS release tool, but if the tool quits unexpectedly, the `node_modules` folders may not be recovered.

To address this issue, we propose using a `try/finally` block to ensure that the `node_modules` folders are always recovered. The relevant code can be found at the following location: https://github.com/Azure/azure-sdk-tools/blob/115b3f0f30b4a96d15567ab03bee0b4f7354957a/tools/js-sdk-release-tools/src/autoGenerateInPipeline.ts#L46-L78

@MaryGao can you help with the fix?  //CC: @qiaozha

**Comment by mikeharder** [comment]
We saw another failure today.  So if the fix has already been deployed, it doesn't seem to be working.

https://github.com/Azure/azure-rest-api-specs/pull/27733/checks?check_run_id=24518858971

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3753879&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=3de61303-123b-5ab1-40f3-ad043cb08f5f&l=18

**Comment by MaryGao** [comment]
https://github.com/Azure/azure-rest-api-specs/pull/27733/checks?check_run_id=24664599412

Shoud be fixed now and feel free to re-open if existing.
