### ISSUE TITLE
Gaps in the SDK release readiness generate SDK feature 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7633]
**Requirement:**  The Generate SDK release step in the SDK release readiness app is missing links to instructions/docs/guidance and the get approval step is after the user enters the SDK package namespace.  A new product releasing a new initial SDK would need to get approvals before they know what namespace to enter into the field. 

**Doc/Guideline Links:** 

- https://azure.github.io/azure-sdk/policies_releases.html#package-versioning (SDK versioning guidelines) 
- SDK namespace syntax :  Generic guidelines: https://azure.github.io/azure-sdk/general_design.html#namespaces
- For get approvals the link should be: https://eng.ms/docs/products/azure-developer-experience/develop/namespace-review (management plane SDK review process and examples) 

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/781c9b70-8306-4854-9b78-ed365c7620a4)
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/65853173-05c1-4dc6-9781-719d8abcdb5b)

**Comment by maririos** [comment]
@ladonnaq I have updated the description of the issue with the relevant documentation links

**Comment by ladonnaq** [comment]
> @ladonnaq I have updated the description of the issue with the relevant documentation links

What should we link to for data plane namespace guidance?  It is done as part of the initial SDK review/Intro meeting for new products/services.  I think at minimum we need to provide example like we do for management plane. Here is where I find the information on our docs site - 
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/28df2305-ca3b-4bef-9836-08d9c97310c3)

**Comment by ladonnaq** [comment]
@maririos - This is still a priority.  This is what has caused the most confusion.  When can this be completed and deployed to PROD?  There are around 130 Public Preview or GA launches planned by 1H2024.  If this is not fixed, it will generate quite a bit of noise/chaos.  Or we will end up with incorrect info.  A service partner pinged me for help the other day with something else and I noticed that he had entered just the product name in the SDK namespace field.

**Comment by maririos** [comment]
Thank you for bringing my attention to it. It got lost in my releases.
it is set for next cycle.

**Comment by maririos** [comment]
> > [@ladonnaq](https://github.com/ladonnaq) I have updated the description of the issue with the relevant documentation links
> 
> What should we link to for data plane namespace guidance? It is done as part of the initial SDK review/Intro meeting for new products/services. I think at minimum we need to provide example like we do for management plane. Here is where I find the information on our docs site - ![image](https://private-user-images.githubusercontent.com/67656762/302761859-28df2305-ca3b-4bef-9836-08d9c97310c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NDEyNzQsIm5iZiI6MTcwODY0MDk3NCwicGF0aCI6Ii82NzY1Njc2Mi8zMDI3NjE4NTktMjhkZjIzMDUtY2EzYi00YmVmLTk4MzYtMDhkOWM5NzMxMGMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDIyMjkzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1OTAwZDhjZGQwYjYzYjc5YjVlNGJmNzhkZGY3OWJiYTExNjM2MTFlZTE4YWY4N2QwOThlM2E5ZTZiMjlmNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5DBnwmay06OKlOyt9uFQEr824HEeqs7wF2KGvSGRb9o)

PR opened for this: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/922

**Comment by maririos** [comment]
After looking into this there is no clear guidance from our team on what is the order of steps a user should take when generating the SDK. It varies per language and then also on when the namespace got approved. For now, I moved the `Generate SDK` stepto be the first, then `Get approvals`, and then `Package details`. This might change again, but it is the best we have as of now.
I am joining the v-team that is looking into this process and once there is a conclusion we will of course update the apps.

Changes need to happen in:

- [ ] Data plane SDK app
- [ ] Management plane SDK app

**Comment by ladonnaq** [comment]
> After looking into this there is no clear guidance from our team on what is the order of steps a user should take when generating the SDK. It varies per language and then also on when the namespace got approved. For now, I moved the `Generate SDK` stepto be the first, then `Get approvals`, and then `Package details`. This might change again, but it is the best we have as of now. I am joining the v-team that is looking into this process and once there is a conclusion we will of course update the apps.
> 
> Changes need to happen in:
> 
> * [x]  Data plane SDK app
> * [x]  Management plane SDK app

Thanks @maririos for investigating and joining the v-team that is looking into this process. My understanding is that the approval for data plane happens during the first SDK review/intro with the arch board.  If that is true, then there needs to be a target timeline for completing and approving the namespaces in APIView.  btw - Don't we need the namespaces to generate the SDKs?  Or can we generate and then update the namespace?  I sent email as you recommended on the topic of "Do service teams need to update the namespaces some place (config file) or if our team is doing that for the service teams.  So waiting for feedback on that topic.  Whatever the outcome we should communicate to the service partners (in our docs and maybe release planner).

**Comment by maririos** [comment]
@ladonnaq answering your questions:

> My understanding is that the approval for data plane happens during the first SDK review/intro with the arch board. If that is true, then there needs to be a target timeline for completing and approving the namespaces in APIView. btw

This is true. and it does happen in APIView but it is unclear when the architects do the actualy click on APIView if at the beginning of the process or before the user is going to release the package.

>Don't we need the namespaces to generate the SDKs? Or can we generate and then update the namespace? 

They can update it later. Ideally it goes in the `tspconfig.yml` file (confirmed with Wes) but that can be updated later. In an ideal world, when the user goes to a REST API meeting, they can also get the name approved and therefore, they don't need to make another change to the `tspconfig` file later on and create another PR... but here we are. 
This is something we need to keep looking into

**Comment by maririos** [comment]
Changes have been deployed to PROD. We will keep the conversation about the process in the v-team meetings
