### ISSUE TITLE
Cleanup defunct docs docker secrets when docker is no longer being used for docs validation

### ISSUE THREAD

**Issue by JimSuplizio** [Azure/azure-sdk-tools#7646]
This is directly related to #7645.

When the new docs validation tools are completely integrated into Java, JS, Net and Python the following secrets need to be removed from our secrets vault and from the [Secrets for publishing individual package documentation](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-distributed-task.hub-library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=76&path=Secrets%20for%20publishing%20individual%20package%20documentation) variable group.

- azuresdkimages-cr-clientid
- azuresdkimages-cr-clientsecret

**Comment by danieljurek** [comment]
These secrets have been removed.
