### ISSUE TITLE
`Automated merging requirements met` check will remain stuck in `queued` state if any of the required non-unified-pipeline GitHub checks finishes after ADO build pipeline, like `TypeSpec Validation`

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#7657]
Consider these two cases of `Automated merging requirements met` check stuck in `queued`:
- https://github.com/Azure/azure-rest-api-specs/pull/27707/checks?check_run_id=21380486084
- https://github.com/Azure/azure-rest-api-specs/pull/27678/checks?check_run_id=21340084129

In both of these cases the `PR Summary` check run succeeded 1 minute before `TypeSpec Validation`.

For example, this `PR Summary` finished at 12:12 PM:

- https://github.com/Azure/azure-rest-api-specs/pull/27678/checks?check_run_id=21340084129

While `TypeSpec Validation` finished at 12:13 PM:

- https://github.com/Azure/azure-rest-api-specs/pull/27707/checks?check_run_id=21380719644

The update of the `Automated merging requirements met` check is triggered by `openapi-alps` `pipeline-bot` event listener, which reacts to a) messages from event hub, produced by the `After <Task>` tasks from the backing ADO pipeline or b) labelling events. Notably, it does not trigger on non-unified-pipeline GitHub check reporting success. 

So here is what happens: ADO build fully finishes by 12:12 PM, and there are no more events incoming that would trigger the `Automated merging requirements met` check update. Upon its last run, `TypeSpec Validation` is still queued, and other checks are green, hence it reports it is still waiting. `TypeSpec Validation` finished one minute later, but this never gets propagated to the `Automated merging requirements met` check in any way.

Note that `/azp run` will not help if in the next run `TypeSpec Validation` (or any other `required` non-unified-pipeline GitHub check) will succeed too late.

**Comment by mikeharder** [comment]
@konrad-jamrozik: This issue is impacting a lot of my PRs now.  I think because check "TypeSpec Validation - All" is growing in runtime so always finishes last.

Could we prioritize a fix or a workaround?  Otherwise I need to admin merge most of my PRs now.

**Comment by konrad-jamrozik** [comment]
@mikeharder sorry for that. The way it works currently is that each time an ADO task powering given unified pipeline GH check finishes, it then runs [`AfterTask.yml`](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps?path=%2Fprivate%2Fazure-rest-api-specs-pipeline%2F.azure-pipelines%2Ftemplates%2FAfterTask.yml&_a=contents&version=GBmain) that puts an event on event hub that is read by a pipeline-bot to process the result.

Given the above, I see at least following approaches:

1. Make the non-unified-pipeline checks, like "TypeSpec Validation - All", also put an event on that event hub and add code to openapi-alps to handle such events.
2. Modify only openapi-alps to be aware that it needs to also wait for non-unified-pipeline checks. For example, once it detects that all of its own checks pass, and the only checks it still waits for are non-unified-pipeline, it could start periodically pulling GitHub for the status of the remaining checks.
3. Perhaps there is some other way where we could say "if the 'automated merging requirements met' check is queued for too long, trigger some event'.

All of these approaches have drawbacks:

1. this is seems to be complicated; we would have to pollute the 'new' code we have with logic to interact with the legacy 'openapi-alps' and figure out how to plumb permissions to access the event hub.
2. this ends up being this weird hybrid model where usually we are in push-model == event-driven, but in this special case we start doing pull-model and we let the handler of an event to linger for some time to do its pulls.
3. I don't know how technically feasible it is yet.

**Comment by mikeharder** [comment]
> 2. Modify only openapi-alps to be aware that it needs to also wait for non-unified-pipeline checks. For example, once it detects that all of its own checks pass, and the only checks it still waits for are non-unified-pipeline, it could start periodically pulling GitHub for the status of the remaining checks.

I like this option.  I can try to create a PR for it if you want.

**Comment by konrad-jamrozik** [comment]
> I like this option. I can try to create a PR for it if you want.

@mikeharder works for me! You will probably want to add somewhere inside of [`renderAutomatedMergingRequirementsMetCheck`](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps?path=/private/openapi-kebab/src/bots/pipeline/pipelineEventListener/renderAutomatedMergingRequirementsMetCheck.ts&version=GBmain&line=25&lineEnd=26&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents) or close to it.

Let me know if you have any questions.

**Comment by konrad-jamrozik** [comment]
For reference, a guide to unblock stuck PRs in other cases, where they can be unstuck:

- https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/1064/How-to-unblock-stuck-specs-PR

**Comment by mikeharder** [comment]
Minimal Repros:

Check "Manual Validation" passed before last unified check, so "Automated merging requirements met" passed as well
https://github.com/test-repo-billy/azure-rest-api-specs/pull/3291

Check "Manual Validation" passed after last unified check, so "Automated merging requirements met" is stuck
https://github.com/test-repo-billy/azure-rest-api-specs/pull/3292

**Comment by konrad-jamrozik** [comment]
- [Pull Request 549546](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/549546): Bugfix: re-trigger unified pipeline evaluation when external checks finish later (swc: 0.17.1 -> 0.18.0)
- [Pull Request 549546](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/549546): Bugfix: re-trigger unified pipeline evaluation when external checks finish later (swc: 0.17.1 -> 0.18.0)

**Comment by konrad-jamrozik** [comment]
Verified working e.g.:

- https://github.com/Azure/azure-rest-api-specs/pull/29117
- Query for label:
  https://github.com/Azure/azure-rest-api-specs/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3APipelineBotTrigger
