### ISSUE TITLE
Release planner automation to release SDK packages

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#7672]
SDK release apps in release planner still requires user to manually verify change log, API approval, package version and enter these details correctly in the app and also need to run the prepare release script manually. User needs to run the release pipeline manually once all the action items are checked in the release planner to release the package.

### Main issues with this approach:
1. Too many manual steps that can be confusing and require additional help and follow up.
2. Prepare release script needs to be triggered manually from the repo which ends up with incorrect details in some cases.
3. Running prepare release script is not enforced so we don't have the package information for all the packages released.
4. Package work item is created from release planner and also attempted by prepare release script.

### Solution:
We can add an automation in release planner that will validate all the checks like, 
 - API approval
 - change log verification
 - package version
 - package name approval
 
If any checks are failed, then it will show a description next to it to show what needs to be done to resolve the error.

User can also click a button in the release planner to release the package instead of manually running the pipeline to release the package. 

There won't be any need to run prepare release script with approach since it's taken care by automation itself and they also do not need to know the package version in advance.

### How to implement it:
1. Change in release build pipeline
Prepare release script currently performs a series of checks and shows the failure on console. We can modify these checks to be integrated in build pipeline that gets triggered when someone attempts to release a package. If any of these checks fail, it will update package work item in DevOps to show the failure and an explanation with details on how to resolve it.  Release pipeline will have a parameter to just run this validation without releasing a package to perform dry run of validations as well. 

2. Package work item:
   New fields to show validation status and details.

3. Release planner

-     Instead of checklist for validations, release planner will have a button to run the release checks. This will trigger release pipeline with a flag indicating it's to verify package preparedness (dry run of release). Release planner will poll the status of pipeline and show validation details from package work item when available.

- Release planner will also have a button to release the package, and this will run the release pipeline without dry run flag. 
    
 
 
 ### Overall SDK release workflow from release planner for service partner
1. Complete API readiness milestone
2. Open SDK release app and select the package to release for their product and select languages to release. 
3. Generate SDK(not yet automated), get API approval, package name approval.
4. Once SDK code is in the language repo, run release readiness validation by clicking the button in release planner.
5. If validation fails, then fix the code and run the validation again.
6. Click the button to release the package.

Question: Data plane SDK release pipeline requires approval to run the release stage. This might still be required manually (since only few people can approve the release), and we can provide information on release planner if that's the case.

```[tasklist]
### Tasks
-[ ] 7750 
- [ ] https://github.com/Azure/azure-sdk-tools/issues/7750
```

**Comment by weshaggard** [comment]
I think we will want some way to also query information like the version for a given package from the repo so it can be automatically displayed in the release plan and folks don't need to provide it. As part of the validation if they see the version isn't correct we can point them at instructions on how to update that in the repo. 

> Question: Data plane SDK release pipeline requires approval to run the release stage. This might still be required manually (since only few people can approve the release), and we can provide information on release planner if that's the case.

We can make adjustments to this once we start kicking off these pipelines from the release planner.

**Comment by maririos** [comment]
Remaining issue for this work is https://github.com/Azure/azure-sdk-tools/issues/8222 
I am going to close this epic and we will follow up with that issue separately
