### ISSUE TITLE
[tsp-client] Add functionality to sync and update emitter-package-lock.json file 

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-tools#7691]
package-lock.json files provide a specific dependency tree that allow for reproducible builds. The tsp-client tool is used across various repositories, having a consistent way to update the emitter-package-lock.json file and save it to the repository would help language repo owners to provide consistent dependency trees.

- Investigate the best way to create the package-lock.json file. 
- Upon successful creation add it to the eng/ folder in the repo. Language owner will have to open a PR with the file updates after running the command. 
- If there is an error, ask user to verify that module versions specified in emitter-package.json are compatible. 
- Create instructions for tsp-client repo maintainers

**Comment by hallipr** [comment]
I've recently moved powershell scripts used to generate emitter-package-lock.json from emitter-package.json:
https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/typespec/New-EmitterPackageLock.ps1

That script is paired with a script to generate emitter-package.json from an emitter's package.json file:
https://github.com/Azure/azure-sdk-tools/blob/main/eng/common/scripts/typespec/New-EmitterPackageJson.ps1

**Comment by hallipr** [comment]
When creating emitter-package-lock.json, we want to be sure its functionally the same as package-lock.json compared to emitter-package.json.  To this end, we simply `npm install` over emitter-package.json in a temp folder and extract the resulting package-lock.json.

This doesn't completely alleviate the concerns that the dependency tree expressed in emitter-package-lock.json won't be the same as was used to build the emitter or when creating emitter-package.json.

**Comment by catalinaperalta** [comment]
Thanks for the input and links @hallipr! I'll open another issue to track adding some functionality to generate an emitter-package.json from the emitter's package.json.
