### ISSUE TITLE
Review SDK package names for data plane is empty

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7695]
See:
<img width="286" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/84fe67ac-20f5-4965-b6e3-50dceeb9ee9e">

Maybe just linking it to the archboard intro meeting will be enough, but letting @ronniegeraghty decide

**Comment by ronniegeraghty** [comment]
Not sure why there is a data plane tab for this. There's no official process for data plane right now. If I added the tab, I claim amnesia. We're theorizing how we can have a more formally recorded process for this now, but nothing's been decided yet.

**Comment by maririos** [comment]
Done with PR https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/922
