### ISSUE TITLE
Update onboarding email templates

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7712]
If only management plane is in scope then this would be the email to send.  The only change I made was to direct teams to go create release plans (without scheduling an Info meeting or attending onboarding).  Self-service is the end goal, so let’s try this out and see how it goes.  We will remove the “schedule info meeting” from the management plane only scenario and see if office hours is sufficient.  Today I do spend a significant amount of time helping management plane end to end for the new initial SDK scenarios. 

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Based on the information you provided when onboarding to the Azure SDK team, API details are <scope is yes for mgmt> for this product. 
Your onboarding record in Azure DevOps is: [Triage - Release Planner Test Product](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fazure-sdk%2FRelease%2F_workitems%2Fedit%2F17128&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817701584%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=AvQQyiTxj%2BNo2505xHI7564CVoDV75WTTOUt%2B7m%2BqDY%3D&reserved=0) 
Next steps
•	If your product is in scope for APEX, then you should mark the “Lifecycle: Onboard with the Azure SDK team to determine API/SDK scope, ID = d0ac2647-8e12-4fd6-a7f2-69d9747c86b4”, launch criteria as complete and paste the link to the onboarding record in the requester’s notes. See guidance for submitting evidence for APEX signoffs - [APEX launch readiness and signoffs (eng.ms)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Feng.ms%2Fdocs%2Fproducts%2Fazure-developer-experience%2Fonboard%2Frequest-apex-sign-off&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817708065%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=AVxCjpA9k%2BW4whFUFAqofjk8O%2FASDoIF3KHfGcLTyqE%3D&reserved=0)
•	Create a release plan and use it to complete work, ensure all requirements are met, and receive APEX signoff for new Azure REST APIs and SDK versions.  [What is a release plan? (eng.ms)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Feng.ms%2Fdocs%2Fproducts%2Fazure-developer-experience%2Fplan%2Frelease-plan&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817714574%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=ugZsFPghLmGPCh%2Bxo2krmPoOceB06fmOUH80Ew6Xc2o%3D&reserved=0)
•	Get familiar with the Azure SDK release process and changes in the APEX signoff process [https://aka.ms/azsdkdocs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdkdocs&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817720943%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=TXaPNpAdggMHtw%2FgbXnESilgZj809h%2Fn1XrYNMd7IDg%3D&reserved=0)
If you have questions, contact us by posting a question to our [teams channel](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdk%2Fsupport%2Fonboarding-channel&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817726593%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=noZ8k27ZBer1eruaDDMw4s3NbjIvHFxxP%2B6OOhFrDJs%3D&reserved=0), [email](mailto:plrsdk@microsoft.com), or attending Azure SDK Onboarding office hours posted in our teams channel - [https://aka.ms/azsdk/onboarding-channel](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdk%2Fonboarding-channel&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817732741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=%2Bh04hhioiMYtPEy0MFoqKs30v0goDnBR5zrG6bGthGw%3D&reserved=0)
Your feedback matters to us, and we’d love to hear more about your experience using the Release Planner. Take a quick 2-minute survey to help us improve. Here is a [link](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdk%2Fonboard%2Ffeedback&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817738847%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=sBe2GLHMj4Bih3%2BcV3MQNvwu4V7j5DkiTc3tE7c39ws%3D&reserved=0) to the survey. 
Regards 
Azure SDK Onboarding PM team 

-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Based on the information you provided when onboarding to the Azure SDK team, API details are unsure or data plane is in scope for this product. 
Your onboarding record in Azure DevOps is: [Triage - Release Planner Test Product](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fazure-sdk%2FRelease%2F_workitems%2Fedit%2F17128&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817744422%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=QecFPFTAlXff7l2Ce80ir9U96sJVmNzkmbnbXY8eMeM%3D&reserved=0) 
Next steps
•	Attend an Informational meeting with the Azure SDK team. If while you onboarded your team you didn’t get prompt to schedule a meeting, please schedule as soon as possible - [Azure SDK informational meeting](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdk%2Fscheduleinformational&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817750852%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=3hBdP3Xg%2FUB1o0q4VHGevoTi4qgmEk9scRGmsFGlIDA%3D&reserved=0). During the information meeting we will validate the REST APIs in scope for your product/service, provide overview of the new improvements to our process and tooling, and help you create the appropriate release plan(s). 
•	If your product is in scope for APEX, then you should mark the “Lifecycle: Onboard with the Azure SDK team to determine API/SDK scope, ID = d0ac2647-8e12-4fd6-a7f2-69d9747c86b4”, launch criteria as complete and paste the link to the onboarding record in the requester’s notes. See guidance for submitting evidence for APEX signoffs - [APEX launch readiness and signoffs (eng.ms)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Feng.ms%2Fdocs%2Fproducts%2Fazure-developer-experience%2Fonboard%2Frequest-apex-sign-off&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817756502%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=5aSa0kJirJfBW%2Bo1YH62e0hVkU1DIvlDmr%2Feai4TvV8%3D&reserved=0)
•	Get familiar with the Azure SDK release process and changes in the APEX signoff process [https://aka.ms/azsdkdocs](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdkdocs&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817762876%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=O%2FEJCC5wJZCWuXnm3htFt38bTFVRto7PskgUPGeEdIw%3D&reserved=0)
If you have questions, contact us by posting a question to our [teams channel](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdk%2Fsupport%2Fonboarding-channel&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817768313%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=em%2BOPDdFSxAUU%2BLohrFTL3q4uzyGelF57NPftAcFCT0%3D&reserved=0), [email](mailto:plrsdk@microsoft.com), or attending Azure SDK Onboarding office hours posted in our teams channel - [https://aka.ms/azsdk/onboarding-channel](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdk%2Fonboarding-channel&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817774356%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=89whmud6BCuAcvXtj%2FJi%2FonueUFVfplqZZkNoSisrSQ%3D&reserved=0). 
Your feedback matters to us, and we’d love to hear more about your experience using the Release Planner. Take a quick 2-minute survey to help us improve. Here is a [link](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fazsdk%2Fonboard%2Ffeedback&data=05%7C02%7Cmariari%40microsoft.com%7C16da12db0ea541d209f708dc2cac1576%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638434364817780306%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=H2F6qQlwBDLTaBO1uCU1bFPCL0AW9TMpuN%2BvCCvjqTQ%3D&reserved=0) to the survey. 
Regards 
Azure SDK Onboarding PM team

**Comment by ladonnaq** [comment]
Closing this issue. I created new email templates and provided links in the GitHub issue tracking the redesign of the onboarding feature. https://github.com/Azure/azure-sdk-tools/issues/7084
