### ISSUE TITLE
[LintDiff] Need separate ruleset for TypeSpec-generated Swaggers

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-sdk-tools#7732]
We need the following capabilities in LintDiff:
1. Creation of a distinct ruleset for TypeSpec-generated Swaggers, which is a subset of the normal ruleset for hand-authored Swaggers. There should never be a rule in the TypeSpec ruleset that is not in the normal ruleset. The goal will be to shrink the number of rules in this ruleset until it is empty, and no LintDiff rules run against TypeSpec-generated Swaggers.
2. We need a flag or other parameter to tell LintDiff which ruleset to apply. 

The mechanism will allow us to accomplish the following goals:
1. Avoid a LintDiff failure when the corresponding TypeSpec rule has been purposefully suppressed. Authors should not have to suppress the same thing twice.
2. Allows us to use LintDiff as a backstop for catching issues when an equivalent check does not exist in TypeSpec. As we add equivalent checks to TypeSpec, or identify rules that aren't relevant to TypeSpec-generated Swagger, we will remove them from this ruleset. Eventually, this ruleset will be small or empty.

**Comment by konrad-jamrozik** [comment]
This work is now completed.

Test PR:
https://github.com/Azure/azure-rest-api-specs/pull/27936/checks?check_run_id=22018004440
 
Log:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3532098&view=logs&j=0574a2a6-2d0a-5ec6-40e4-4c6e2f70bea2&t=80c3e782-49f0-5d1c-70dd-cbee57bdd0c7
 
Raw log:
https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/3532098/logs/286

The raw log shows rules have been disabled for TypeSpec-generated specs:

```
	Line 210: 2024-02-27T07:19:53.6176794Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"information","message":"DISABLED Spectral rule for TypeSpec-generated OpenAPI specs, severity 'DISABLED': 'AdditionalPropertiesAndProperties'"}
	Line 242: 2024-02-27T07:19:53.6196764Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"information","message":"DISABLED Spectral rule for TypeSpec-generated OpenAPI specs, severity 'DISABLED': 'Nullable'"}
	Line 247: 2024-02-27T07:19:53.6201570Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"information","message":"DISABLED Spectral rule for TypeSpec-generated OpenAPI specs, severity 'DISABLED': 'OperationSummaryOrDescription'"}
	Line 251: 2024-02-27T07:19:53.6204248Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"information","message":"DISABLED Spectral rule for TypeSpec-generated OpenAPI specs, severity 'DISABLED': 'ParameterDescription'"}
	Line 262: 2024-02-27T07:19:53.6211148Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"information","message":"DISABLED Spectral rule for TypeSpec-generated OpenAPI specs, severity 'DISABLED': 'PropertyDescription'"}
	Line 270: 2024-02-27T07:19:53.6216280Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"information","message":"DISABLED Spectral rule for TypeSpec-generated OpenAPI specs, severity 'DISABLED': 'SchemaDescriptionOrTitle'"}
	Line 271: 2024-02-27T07:19:53.6216932Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"information","message":"DISABLED Spectral rule for TypeSpec-generated OpenAPI specs, severity 'DISABLED': 'SchemaNamesConvention'"}

```

but not for manually-written specs, e.g.:

```
2024-02-27T07:19:53.6160999Z {"pluginName":"spectral","extensionName":"@microsoft.azure/openapi-validator","level":"information","message":"Spectral rule for manually written OpenAPI specs, severity 'Warning': 'PropertyDescription'"}
```
