### ISSUE TITLE
Support output variables from test-resources-pre.ps1 script

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-tools#775]
We should support output variables from test-resources-pre.ps1 scripts. To support back compat with any scripts that may be emitting output now (accidentally or otherwise), variables should use the structure:

```powershell
[pscustomobject]@{
  Name = 'string'
  Value = 'string'
  IsOutput = $true
}
```

These variables will be passed as parameters to the template, as well as the -post script, and treated as output variables. Thus, they need to also be added to whatever we do for clean up in #554.

**Comment by benbp** [comment]
@heaths is this still needed?

**Comment by heaths** [comment]
Needed? No, not that I'm aware; however, when I opened this I did help someone work around it, so this would be useful, but low priority and maybe worth cutting. We could always bring it back if someone needed.

**Comment by benbp** [comment]
Sounds good. I'm going to close for now and we can re-open if someone needs it again (should be easy enough to implement when the need arises).
