### ISSUE TITLE
Create metadata file to record SDK release readiness checks

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#7750]
Build/Analyze pipeline runs some checks that are part of prepare release script and/or build pipeline.

We need to create a metadata artifact by the pipeline so it can be updated in package work item after each run of the pipeline. Release planner will consume this data on package work item to show package details and release readiness.

- Change log verification
- API review approval
- Package name approval
- Package name
- Package version
- Pipeline build ID
- Link to pipeline run
- Readme verification

Create a new YAML template in eng/common that can be plugged in to each language's build or analyze job.

**Comment by maririos** [comment]
@praveenkuttappan this has been done, right?

**Comment by praveenkuttappan** [comment]
yes, It's completed now.
