### ISSUE TITLE
Create or update package work item from build pipeline

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#7751]
Create or update a package work item using current package name and version (as long that version is not already released) by each run of pipeline job that's used to release a package irrespective of how it was triggered. CI, manual or from release planner.

Package work item will be updated with the metadata in new release readiness artifact emitted by build/analyze pipeline job.

Package work item creation step should pass `unknown` as service name and package display name value to tag the package work item under unknown service tree for a new package. This will be linked correctly by release planner before the release. If request is to update an existing package work item then it will ignore service name and package display name as long as a work item already exists with that same package name.

**Comment by maririos** [comment]
@praveenkuttappan  Is there something else remaining here or can we close it

**Comment by praveenkuttappan** [comment]
This is completed. Closing it.
