### ISSUE TITLE
VerifyChangeLogEntry step fails for private repo.

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#776]
See example https://dev.azure.com/azure-sdk/internal/_build/results?buildId=451689&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=72c41882-9d21-5580-4869-7f3ea1bd9c0a

Logic at https://github.com/Azure/azure-sdk-tools/blob/master/eng/common/scripts/Verify-ChangeLog.ps1#L27 
```
 $Language = $RepoName.Substring($RepoName.LastIndexOf('-') + 1)
```
fails for our private repos that are named like `azure-sdk-for-js-pr`

We probably should start explicitly passing in the language or importing a common variable file for each repo that has common properties like language.

**Comment by chidozieononiwu** [comment]
Fixed with https://github.com/Azure/azure-sdk-tools/pull/779
