### ISSUE TITLE
Add/modify title and description of autogenerated language PRs

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7760]
When a user creates a PR against the specs repositories, SDKs get generated and draft PRs are created too. The purpose is to preview changes but not to actually commit the changes in a repository.
Users are getting confused with this, so one suggestion is to make the purpose of these PRs very clear and make sure the user doesn't try to use those PRs.
An example could be add/modify the title and the description of the PR to signal that it is only for "preview" purposes.

**Comment by raych1** [comment]
Will add the following comment to the PR's description.
"This pull request has been automatically generated for preview purposes."

**Comment by konrad-jamrozik** [comment]
[Pull Request 540940](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/540940): Add/modify title and description of autogenerated language PRs

**Comment by JackTn** [comment]
@maririos  Test Snapshot https://github.com/azure-sdk/azure-sdk-for-net/pull/7636. Let me know if it is OK, Thanks

**Comment by maririos** [comment]
Thank you so much for making this change

**Comment by raych1** [comment]
The change had been deployed to production.
