### ISSUE TITLE
Create Review and Create a revision UI should be as close as possible

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7782]
According to the path the user is taking, the UI (and help messges) are different. To make sure we are consistent and help users we should integrate this. 
For example, here is the screenshot when creating a review:
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/e7459ba7-dc4e-4778-8358-a514202fe34f)

And here when creating a revision:
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/ae93f30f-d808-4ac7-acde-e456b123a8e4)

**Comment by praveenkuttappan** [comment]
It's fixed in new UI which uses new tree style parser.
