### ISSUE TITLE
API View: Add the ability to label revisions

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-tools#782]
We need the ability to label revisions to indicate which ones are GA revisions (and which versions), and give names corresponding to features/changes to other revisions. For example,

Revision 0: Prototype
Revision 1: Preview 1
Revision 2: Feature A
Revision 3: Feature B
Revision 4: Preview 2
Revision 5: GA V1
....

**Comment by tg-msft** [comment]
Related to https://github.com/Azure/azure-sdk-tools/issues/367 and https://github.com/Azure/azure-sdk-tools/issues/476

**Comment by seanmcc-msft** [comment]
This would also be a great feature.

**Comment by JoshLove-msft** [comment]
@praveenkuttappan I would be interested in tackling this if you haven't already started working on it.

**Comment by praveenkuttappan** [comment]
@JoshLove-msft I haven’t started on it yet. I am focusing on integrating JS into API view tool now.
