### ISSUE TITLE
Deprecate Create OpenAPI Spec from OpenAPI Hub

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#7829]
Once [#7828](https://github.com/Azure/azure-sdk-tools/issues/7828) is done, we can deprecate this feature from the portal.

To do so, first we have to show an alert to let users know that they have to move to the new script and point them to our docs.

Then, we can remove this feature and the repo sync pipeline we have in place. However, we should not remove the front-end path in case users have it bookmarked, we should leave it and show a message saying that the feature has been deprecated and they have to use the new script.

**Comment by konrad-jamrozik** [comment]
Related work:
- https://github.com/Azure/azure-sdk-tools/issues/7915
