### ISSUE TITLE
Update release plan ADO work item with SDK target date 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#7838]
Requirement:  The SDK target date field needs to be in the release plan so that our release plan queries can track upcoming SDK releases.  Right now the field is in the package but the package is not created until the SDK release milestone.  We want to know the target date for the SDKs from the start and as teams change it the field is updated so that we can track upcoming SDK releases. 

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/b51dca3d-5c9e-46d7-8177-087157ef4f51)

**Comment by maririos** [comment]
The Release Plan work item already contains the target release date. It does not include the day, but it is enough to track upcoming releases.
See: https://dev.azure.com/azure-sdk/Release/_queries/edit/19945/?triage=true
<img width="213" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/2066ce02-ad70-4a67-acaa-36d1faadb94b">

See how this is present in the TypeSpec - Release Plans query:
<img width="1063" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/9868623/e1fc9f0e-2a78-4b08-b6db-aa05a1c880b8">
