### ISSUE TITLE
get-pr-users.ps1 should use "parent of" logic that github applies to github during PR

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#784]
Right now, if you pass in `/sdk/servicebus/` only matches of that EXACTLY will be found and added as reviewers.

Ideally, this would be a bit more relaxed. For instance, you're going after  `/sdk/servicebus/`. If there isn't a entry for that path, but there _is_ an entry for `/sdk/`, we should fall BACK to the owners presented on that rule.

**Comment by danieljurek** [comment]
This is finished
