### ISSUE TITLE
Release planner - Enable cloud flow to create package work item

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#7851]
Cloud flow to create package work item is disabled now due to empty package root path. Enable the cloud flow to create package work item once the issue is fixed to set repo path by identifying the repo path within the pipeline,

**Comment by maririos** [comment]
@praveenkuttappan could you verify that the cloud flow is on after the deployment from last week?

**Comment by praveenkuttappan** [comment]
Yes. It was turned back on. Closing this issue.
