### ISSUE TITLE
BranchPolicyException breaking change approval labels

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#7860]
This is a minor swizzle to our labeling design. Please

- change the `Versioning-Approved-NotReleased` to `Versioning-Approved-BranchPolicyException`
- add a `BreakingChange-Approved-BranchPolicyException` label

"NotReleased" is a bit too bland and nondescriptive. These are exceptions to the branch policy and we should make the label communicate that clearly.

Notes by kojamroz:

- This is part of work on https://github.com/Azure/azure-sdk-tools/issues/6374

**Comment by konrad-jamrozik** [comment]
- [ ] [Pull Request 542484](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/542484): Add BranchPolicyException to breaking changes approval labels
- [ ] Update labels on the specs repos
- [ ] Update the docs
