### ISSUE TITLE
Document Publish to Public pipeline deprecation

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7861]

**Comment by JonathanCrd** [comment]
PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/936

**Comment by maririos** [comment]
@JonathanCrd is there an equivalent issue to remove the functionality from the OpenAPI Hub portal?

**Comment by maririos** [comment]
I just realized, you are going to have to update the comment the bot creates in the spes PR: https://github.com/Azure/azure-rest-api-specs/blob/main/.github/comment.yml#L2

**Comment by JonathanCrd** [comment]
>  is there an equivalent issue to remove the functionality from the OpenAPI Hub portal?

No, but instruction were provided on the docs.
The bot instructions have been updated too.
