### ISSUE TITLE
Bot bug: bot is stuck in a dead loop when adding or removing label: no receive activity

### ISSUE THREAD

**Issue by kazrael2119** [Azure/azure-sdk-tools#7867]
In this pr https://github.com/Azure/azure-rest-api-specs/pull/27220, two bots are stuck in a dead loop when adding or removing label: no receive activity

![image](https://github.com/Azure/azure-sdk-tools/assets/98569699/68458ee9-cbf8-4329-a5e1-8f509213a769)

**Comment by kurtzeborn** [comment]
This was a transient issue due to FabricBot backend misbehavior.  The long term solution is likely to eliminate our dependency on FabricBot.
