### ISSUE TITLE
APIView tooltips misspelled/misleading

### ISSUE THREAD

**Issue by richardpark-msft** [Azure/azure-sdk-tools#7889]
Just some minor cosmetics...

"Conversations" is misspelled here:

<img width="99" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/51494936/658bc848-fc12-4f8b-b614-37f13528bb12">

If you click on the tooltip it swaps to saying "API" - I'm pretty sure that's wrong but it didn't appear to affect anything. 

<img width="66" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/51494936/11fb8828-4fcf-4423-bcfd-edc8886ea886">

Suggested fixes:

* Change the dictionary to accept the misspelling for Conversations. (difficulty: moderate)
* When Conversations' tooltip switches to "API", change the "API" one to "Conversations" (difficulty: impossible)

No alternatives solutions available, unfrotunately.

(BTW, so far I'm liking this new design)

**Comment by maririos** [comment]
Revisions is also mispelled:

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/f19c0255-5724-41a2-a369-de7b572eb75f)

**Comment by richardpark-msft** [comment]
@maririos, please file your own issue. This one is just about me.

**Comment by maririos** [comment]
I am all about efficency @richardpark-msft ☺️

**Comment by maririos** [comment]
PR: https://github.com/Azure/azure-sdk-tools/pull/7939

**Comment by richardpark-msft** [comment]
@WhitShake, is it too late to bring the typos back? I think I'm going to miss them.
