### ISSUE TITLE
Release planner: Minor UI aligment issues in Release Plan details

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#7911]
I found some minor UI issues in the release plan details view.

1) The tab menu is not allign with the Milestones and reviews screen

![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/8bccaf12-5b89-4e1a-a749-6171fd35f8cd)

2) The progress labels in the milestones graph are not aligned to the right

![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/4fc07c6b-6cc7-4367-8ac2-81ba83377e45)

3) Contents are no longer responsive to the side panel. The side panel now goes on top of the contents

**Comment by JonathanCrd** [comment]
Fixed

![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/9189f3fb-3b84-4b19-8990-5564bf4f8c36)

![Image](https://github.com/Azure/azure-sdk-tools/assets/17486462/43b92cff-067b-4998-a7d7-ab9cabf36dcc)

**Comment by JonathanCrd** [comment]
@maririos did you find other visual bugs? or why did you reopen the issue?

**Comment by maririos** [comment]
> @maririos did you find other visual bugs? or why did you reopen the issue?

ohh no. my bad
