### ISSUE TITLE
New 1es check is blocking checkins as this fails in main

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-tools#7933]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=3624229&view=logs&j=7e6a3fb7-dbfe-5169-4db8-92b72295ba6c&t=d77a525f-4ebd-52c1-1413-b7d9a101e2a3&l=52

I don't know what the remedy for this error is but it is odd that we are building track 1 libraries in a track 2 ci.

**Comment by m-nash** [comment]
@pallavit this is blocking this issue https://github.com/Azure/autorest.csharp/issues/4242

**Comment by JoshLove-msft** [comment]
This is blocking the Aspire releases as well.
