### ISSUE TITLE
Add query to the emails that get sent out regarding customer reported issues in invalid state

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#795]
We now have a system where we get sent an email every week for customer reported issues in an invalid state.
It would be great if the email had a link to the GitHub query for such issues so that as and when we work on fixing the state, we get an updated view

cc @AlexGhiondea

**Comment by AlexGhiondea** [comment]
There isn't a good way to create a query for those :(. 

[Here](https://github.com/Azure/azure-sdk-tools/blob/master/tools/github-issues/Azure.Sdk.Tools.GitHubIssues/Reports/CustomerReportedInvalidState/FindCustomerRelatedIssuesInvalidState.cs) is the logic behind that query:
