### ISSUE TITLE
[SDK Automation] Log the output of the 'tsp compile' command to the pipeline

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#7958]
The common automation scripts used to generate SDK based on `TypeSpecs` does not log the command output, making it hard to troubleshoot the root cause of failures.

Currently, when this command fails, the log of pipeline is as follows for this [spec PR](https://github.com/Azure/azure-rest-api-specs/pull/28320#issuecomment-2007630933):
```powershell
01:21:41.233 cmdout 	[Invoke-GenerateAndBuildV2.ps1] npx tsp compile /mnt/vss/_work/1/s/azure-sdk-for-net/sdk/applicationinsights.livemetrics/Azure.Monitor.OpenTelemetry.LiveMetrics/TempTypeSpecFiles/ApplicationInsights.LiveMetrics/main.tsp --emit @azure-tools/typespec-csharp --option @azure-tools/typespec-csharp.emitter-output-dir=/mnt/vss/_work/1/s/azure-sdk-for-net/sdk/applicationinsights.livemetrics/Azure.Monitor.OpenTelemetry.LiveMetrics/src
01:21:42.991 cmderr W 	[Invoke-GenerateAndBuildV2.ps1] Write-Error: /mnt/vss/_work/1/s/azure-sdk-for-net/eng/scripts/Invoke-GenerateAndBuildV2.ps1:120
01:21:42.992 cmderr W 	[Invoke-GenerateAndBuildV2.ps1] Line |
01:21:42.992 cmderr W 	[Invoke-GenerateAndBuildV2.ps1]  120 |  … ectFolder = & $processScript $typespecFolder $commitid $repoHttpsUrl  …
01:21:42.992 cmderr W 	[Invoke-GenerateAndBuildV2.ps1]      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
01:21:42.992 cmderr W 	[Invoke-GenerateAndBuildV2.ps1]      | Failed to generate sdk project at
01:21:42.992 cmderr W 	[Invoke-GenerateAndBuildV2.ps1]      | /mnt/vss/_work/1/s/azure-sdk-for-net/sdk/applicationinsights.livemetrics/Azure.Monitor.OpenTelemetry.LiveMetrics
01:21:43.066 warn 	Script return with result [warning] code [0] signal [null] cwd [azure-sdk-for-net]: pwsh ./eng/scripts/Invoke-GenerateAndBuildV2.ps1
```

@weshaggard , it appears that the `tsp-client` library adoption work for each SDK language automation is currently in backlogs. How do you think of improving the [TypeSpec-Project-Generate.ps1](https://github.com/Azure/azure-sdk-tools/blob/dda0e83f76efd2f34b2c0d7cd9c63b677a1c4c90/eng/common/scripts/TypeSpec-Project-Generate.ps1#L109) script to address this issue?

**Comment by weshaggard** [comment]
Do you know if tsp-client handles this correctly? If so perhaps the work here should be to move to tsp-client instead of fixing these scripts.

**Comment by raych1** [comment]
@weshaggard ,
Yes, `tsp-client` logs the output of `tsp compile` errors and it's easy to extend the logging information there. I agree to integrate with `tsp-client` in SDK automation tool. Now the request is the support of the private spec repo by tsp-client.
https://github.com/Azure/azure-sdk-tools/issues/8012

**Comment by raych1** [comment]
Close this as we would like to adopt `tsp-client`.
