### ISSUE TITLE
OpenAPIHub - Identify server request usage from telemetry to find any unknown dependency

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#7964]
Identify the requests processed in a month by OpenAPIHub server to identify usage pattern to help us determine if we can safely deprecate OpenAPIHub. This telemetry can be queried from logs using request path.

**Comment by JonathanCrd** [comment]
After going trough the logs, we identified 2 different endpoints that require further investigation:

```[tasklist]
### Tasks
- [ ] sdk-dl-pub
- [ ] docs/previews
```
