### ISSUE TITLE
Scheduling a REST API meeting fails with invite sent, GH issue created, and meeting in Draft mode

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#7974]
This has been happening for 2 users. It looks like the tool is crashing when saving in the DB. 
- Event Invitees table is not updated with users
- Event table record stays in Draft mode so it is never updated with real data. The date in the scheduler so no one can take it
- User is not able to edit/update/cancel the meeting as it is in draft mode
- Outlook calendar and GH issue were created and successfully shared with everyone present.

**Comment by JonathanCrd** [comment]
I had a monitored session with the user and got the logs. Weirdly, no errors were thrown, and the event record was updated in the database. However, **no invitees were added**. Looking at the logs I noticed that **the invitees list was empty**, this is generated by the output of the `Pick User` component.

So, I have these theories of what is possible going on:

- Something changed in the component's behavior, and it is not being rendered properly for this user.
- The code that generates the invitee list is possible being skipped.

**Comment by JonathanCrd** [comment]
I'm going to improve our failure mechanisms to detect when this happens and get more detailed logs of the information at each key step of the meeting creation.

Also, if this is a problem with the component, I will also design a new approach of how to get and process meeting invitees
