### ISSUE TITLE
Discuss how to replace Request OOB release of Azure PowerShell Module

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8001]
This feature in OpenAPI Hub redirects the user to create a work item in ADO with a pre-populated template.

**Comment by JonathanCrd** [comment]
Is somebody using this?
Is this still needed? Should we document it?

I'll take a look at the code and understand if there's something happening behind the scenes when a user clicks this button.

**Comment by JonathanCrd** [comment]
I took a look at the code and these are my findings:

In general, this feature in OpenAPI Hub is just a `go.microsoft.com` link that redirects to ADO > Create Work item and contains a `templateId` and `ownerId` query params. This link is not owned by any members of our team.  I'll send both links and owners aliases in an internal email thread.

People are creating work items with this templates to request to request an out-of-band release of Azure PowerShell Module, but it is unknown to me if they are actually coming from OpenAPI Hub or somewhere else, since it is just a link.

I don't think we should own or include this link in our documentation since this process is not part of our REST API & SDK processes. @maririos what do you think? Is the request of an out-of-band release part to our team processes?

Should we decide to exclude it from our documentation, I can notify the link's owners via email that the link will no longer be accessible on OpenAPI Hub, allowing them to incorporate it into their own docs or wiki.

**Comment by maririos** [comment]
> I don't think we should own or include this link in our documentation since this process is not part of our REST API & SDK processes. @maririos what do you think? Is the request of an out-of-band release part to our team processes?

I lack context here. @ladonnaq  or @josefree could you help?

**Comment by maririos** [comment]
People responsible for this have communciated back that they no longer need this functionality so we are good to go to delete it.
