### ISSUE TITLE
Turn off Azure functions used by OpenAPI Hub

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8002]
OpenAPI Hub utilizes azure functions.

We have to make sure that these functions are not being used by other tool, and then turn them off.

**Comment by maririos** [comment]
I looked at all the functions under https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/8c0e0d10-c2d6-42b8-b1d9-e7132b6f18a3/resourceGroups/openapi-platform-preview/providers/Microsoft.Web/sites/openapi-jobs/appServices  and they all had the following logs:

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/a6453aec-94f1-49e8-b757-774b38eef244)

So I went ahead and disabled them all and turned off the Function app. I am going to wait couple of days and see if someone breaks (I doubt it).
Also, Most of the functions were deprecated. More info in: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/832/Release-Planner-App?anchor=azure-function---deprecated

We also have Function app https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/8c0e0d10-c2d6-42b8-b1d9-e7132b6f18a3/resourceGroups/openapi-platform-preview/providers/Microsoft.Web/sites/openapi-jobs-ppe/appServices which has been stopped

**Comment by maririos** [comment]
In the test subscription, I have turned off the Function app: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/4e7b30e5-96b6-4d26-ae34-bd0b75fdafb4/resourceGroups/openapi-platform-test-v2/providers/Microsoft.Web/sites/openapi-jobs-test/appServices
