### ISSUE TITLE
Delete Azure resources for OpenAPIHub

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8004]

**Comment by maririos** [comment]
Tracking: https://microsoft.sharepoint.com/:x:/t/AzureDeveloperExperience/EVpIBFw43epPiepSj9jLwu8BNPUdgcP2USx_X6xJay6Dbw?e=T5E5FX

**Comment by JonathanCrd** [comment]
I have deleted the resources. You can find more information on: [Azure resource updates audit log
](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/992/Azure-resource-updates-audit-log)
