### ISSUE TITLE
Delete deployment pipelines for OpenAPI Hub

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8005]
First, identify the pipelines we use for deployment to TEST, PPE and PROD, including the ones that build the project.

**Comment by JonathanCrd** [comment]
I deleted the release pipeline, but neither @weshaggard nor I have sufficient permissions to delete this other pipeline: https://devdiv.visualstudio.com/DevDiv/_build?definitionId=8618. 

However, the pipeline is currently disabled, and the associated code has been removed.

**Comment by JonathanCrd** [comment]
@maririos do you think is it ok to mark this issue as completed?

**Comment by maririos** [comment]
> @maririos do you think is it ok to mark this issue as completed?

Yes. Looks like we tried to do what we could :)
