### ISSUE TITLE
Archive OpenAPIHub repo from ADO

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8006]

**Comment by JonathanCrd** [comment]
Instead of deleting the repo, we can delete all the files, and create a new Readme.md that says that it has been deprecated.

**Comment by maririos** [comment]
- PR platform repo: https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/openapi-portal/pullrequest/548094
- PR openapi-tools repo:
