### ISSUE TITLE
Design and implement new SDK release request solution

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8009]
Design and implement a new solution to replace the **SDK Release request** feature in OpenAPI Hub.

# Requirements
The new tool or features should stick to current flow in OpenAPI Hub, with few changes on some steps:

| | Step| Requested changes|
|--------|--------|--------|
| 1 | Ask for release details | Include .NET as one of the languages. All languages should be selected by default. Ask for a justification in case the user un-select one of the languages|
| 2 | Create a GitHub issues for each language that is going to be released and add respective properties | |
| 3 | Create a new project for the release and add the previously created GitHub Issues | |
| 4 | Send an email with a link | Include the justification for the non-selected languages. Modify the template for GA Releases to make sure that service partners know what it implies (E.g.: Committing for no breaking changes) |
| [NEW] | Save the links to the GitHub issues in the Release Plan| | 
| [NEW] | Save the Justification in the Release Plan DB | | 

## Tasks
- [ ] When working on the email template, sync with @josefree to review the current template and improve it. Refer to comments on this issue https://github.com/Azure/azure-sdk-tools/issues/5791 too.

## Additional info
Consider these articles and issues when designing and implementing the features:
- [How to ask for official SDK](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/release-request/rules-for-release-request.md) readme
- https://github.com/Azure/azure-sdk-tools/issues/5936

**Comment by JonathanCrd** [comment]
# Implementation design
It has been decided to include this feature in the Release Planner, more specifically, in the SDK Release App for Management Plane.

Most of the information that was asked in OpenAPI Hub has already been provided in previous steps of the Release Plan, so instead of creating a new screen for this, we can simply integrate this "tool" as part of the steps included in the app. However, the current flow of the Management SDK Release app won't make sense, so it must be changed.

Refer to the following FigmaJam to understand where each step in the OpenAPI Tool is going to be located, which information we already have, and what new things need to be added: [SDK Release design - FigJam](https://www.figma.com/file/UTgYQuDTJAnbykomIDJYNW/SDK-Release-redesign?type=whiteboard&node-id=0%3A1&t=tv6f8h8rKEUbuWYx-1)

**Comment by maririos** [comment]
For the .NET addition, we are going to wait for clarity on https://github.com/Azure/azure-sdk-tools/issues/8161

**Comment by maririos** [comment]
@JonathanCrd could you open an issue with the requirements that are still not implemented in the Release Planner?
