### ISSUE TITLE
Add customer-reported labels to PRs from outside the team

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-tools#801]
We currently have the bot applying the `customer-reported` label to issues logged by folks outside the team.
Can we have the same done for PRs as well?

cc @AlexGhiondea, @jongio

**Comment by AlexGhiondea** [comment]
Yes, we should be able to do that! /cc @lilyjma

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by lilyjma** [comment]
@AlexGhiondea : I don't think we've configured the bot to do this yet. Do you want me to do it?

**Comment by ramya-rao-a** [comment]
@lilyjma Please do

**Comment by AlexGhiondea** [comment]
Yes -- let's see if we can do that easily! 🙂 I wonder if we could update the existing rule to apply to both PRs and Issues.

**Comment by lilyjma** [comment]
@AlexGhiondea we can't--rules are quite specific to what they're reacting to. I send an email proposing a rule @ramya-rao-a and @AlexGhiondea

**Comment by ramya-rao-a** [comment]
Closing as this has been implemented
