### ISSUE TITLE
Update docs on how to request an SDK release

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8010]
Information found on https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/release-request/rules-for-release-request.md should be included

**Comment by maririos** [comment]
It will be good to check the ARM wiki too just in case they have info there

**Comment by maririos** [comment]
Docs that we still need to update:

- [ ] In Eng hub:
  - [ ] Edit [Release SDK (eng.ms)](https://eng.ms/docs/products/azure-developer-experience/develop/sdk-release?tabs=management) to let the users know that they have to use the release planner from now on.
  - [ ]  Hide [Access OpenAPI Hub (eng.ms)](https://eng.ms/docs/products/azure-developer-experience/support/openapihub)
  - [ ] Add a migration guide instead, telling the users which tools have replaced each feature of OpenAPI Hub.
- [ ] In the repos:
  - [ ] Modify [azure-rest-api-specs/documentation/release-request/rules-for-release-request.md at main · Azure/azure-rest-api-specs (github.com)](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/release-request/rules-for-release-request.md)

**Comment by maririos** [comment]
Eng Hub PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/978
