### ISSUE TITLE
Update docs on how to create a new OpenAPI specs version using the new Copy-ApiVersion script

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8011]

**Comment by maririos** [comment]
Places to check:
- EngHub
- REST repos
- ARM wiki

**Comment by konrad-jamrozik** [comment]
> Places to check:
> 
> * EngHub
> * REST repos
> * ARM wiki

Details here:
- https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullRequest/937#1711332886

**Comment by JonathanCrd** [comment]
PR for EngHub: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/937

**Comment by JonathanCrd** [comment]
Updated docs in EngHub.

Follow up: 
- https://github.com/Azure/azure-sdk-tools/issues/8073
