### ISSUE TITLE
Documentation: update the TypeSpec directory structure guidance in the specs repo

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#8028]
A follow-up to:
- https://github.com/Azure/azure-rest-api-specs/pull/28464
- https://github.com/Azure/azure-rest-api-specs/pull/28606

As requested by @weshaggard:

- https://github.com/Azure/azure-rest-api-specs/pull/28464#discussion_r1542005681

The article:
- https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/typespec-structure-guidelines.md

Needs to be updated to:
- reflect the updated dir structure article at https://aka.ms/azsdk/spec-dirs
- change the tense to reflect this is no longer a proposal but the current state of things
- change `service family` to `service group`. See [this discussion](https://github.com/Azure/azure-rest-api-specs/pull/28464#discussion_r1554481114)

**Comment by josefree** [comment]
I wonder if you are going to retire this guidance https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/typespec-structure-guidelines.md when https://aka.ms/azsdk/spec-dirs is refreshed?

**Comment by konrad-jamrozik** [comment]
Closing as completed. We may eventually merge the two dir structure docs but this can wait, given both of the articles have been updated.
