### ISSUE TITLE
[SDK Automation - Java] Adjust the steps to run in the automation script

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8040]
The current goal for the SDK automation in the spec PR phase is to generate the SDK code and generate the API View.

We would like to define required steps and optional steps in the SDK automation script. If any required steps fail, it should fail the SDK generation CI check and stop the execution. If any optional steps fail, it could be reported as warnings and shouldn't impact the followed API View generation step.

@weidongxu-microsoft

**Comment by weidongxu-microsoft** [comment]
Current the automation likely already only running the required steps (Java need to compile the code to generate JAR for apiview -- that require compile pass).

If we add breaking changes check etc., it should be on the optional part.

**Comment by weidongxu-microsoft** [comment]
Last PR https://github.com/Azure/azure-sdk-for-java/pull/40282
