### ISSUE TITLE
[SDK Automation - JS] Adjust the steps to run in the automation script Automation Tool

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8042]
The current goal for the SDK automation in the spec PR phase is to generate the SDK code and generate the API View.

We would like to define required steps and optional steps in the SDK automation script. If any required steps fail, it should fail the SDK generation CI check and stop the execution. If any optional steps fail, it could be reported as warnings and shouldn't impact the followed API View generation step.

@MaryGao @qiaozha

**Comment by raych1** [comment]
The implementation has been finished for modular client codeGen. It will need work to support for other codeGen.

**Comment by wanlwanl** [comment]
Checked, RLC and HLC already skip test and publish sample tasks. Modular regards test and publish sample tasks as optional
