### ISSUE TITLE
[SDK Automation - Python] Enable breaking change detection for DPG & MPG

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8045]
We will keep the same contract using in MPG to detect/present the breaking changes in the SDK automation CI framework. 

@msyyc

**Comment by msyyc** [comment]
more details are in https://github.com/Azure/autorest.python/issues/2354

**Comment by raych1** [comment]
As synced with @msyyc offline, we will keep this issue open for further testing effort tracking.

**Comment by raych1** [comment]
@msyyc is this task fully completed? How about the task of adding allowlist for services to enroll breaking changes detection? Can you link the related task? Thanks.

**Comment by msyyc** [comment]
@raych1 - MPG is done.
- For DPG, we plan to use allowlist. If there is service wants breaking detection, the package name shall be added [here](https://github.com/Azure/azure-sdk-for-python/blob/13c2dc8deb665ac027e111db773d5287505d2226/scripts/breaking_changes_checker/breaking_changes_allowlist.py#L10).

**Comment by wanlwanl** [comment]
@msyyc do you have ETA for DPG?

**Comment by msyyc** [comment]
It is already done. Breaking change detection is already enabled to some of data-plane SDK (e.g. "azure-ai-contentsafety", "azure-ai-vision-face") and we plan to enable more DPG SDKs gradually.

**Comment by wanlwanl** [comment]
Is adding package name to the allow list a manual or auto step? Can we enable detection by default for DPG that generated by codegen? Is it done? https://github.com/Azure/azure-sdk-for-python/issues/37871

**Comment by msyyc** [comment]
Both manual and auto step is OK. https://github.com/Azure/azure-sdk-for-python/issues/37871 is not yet and I plan to finish it this sprint.

**Comment by raych1** [comment]
> Both manual and auto step is OK. [Azure/azure-sdk-for-python#37871](https://github.com/Azure/azure-sdk-for-python/issues/37871) is not yet and I plan to finish it this sprint.

@msyyc is this remained work completed?

**Comment by msyyc** [comment]
> > Both manual and auto step is OK. [Azure/azure-sdk-for-python#37871](https://github.com/Azure/azure-sdk-for-python/issues/37871) is not yet and I plan to finish it this sprint.
> 
> [@msyyc](https://github.com/msyyc) is this remained work completed?

You could close this issue.
