### ISSUE TITLE
[SDK Automation - JS] Support and Enable Breaking Change Detection for Modular Client

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8046]
We will keep the same contract using in MPG to detect/present the breaking changes in the SDK automation CI framework. 

@MaryGao @qiaozha 

```[tasklist]
### Parity with existing tooling in Track2
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8303
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8307
```

```[tasklist]
### New functionality
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8305
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8304
- [ ] https://github.com/Azure/azure-sdk-tools/issues/8317
```

**Comment by wanlwanl** [comment]
fix #8303 in #8332

**Comment by wanlwanl** [comment]
Add a [dashboard](https://github.com/orgs/Azure/projects/684/views/1?visibleFields=%5B%22Title%22%2C%22Status%22%2C120274438%2C%22Assignees%22%2C%22Linked+pull+requests%22%5D) for other issues related to JS SDK Automation. 
Please link new issue to the new dashboard for other issue except for modular support

**Comment by wanlwanl** [comment]
Related issue: #8580

**Comment by raych1** [comment]
We will start the testing with beta package of the release tool.

**Comment by wanlwanl** [comment]
No sub-layer for modular needs to detect now
