### ISSUE TITLE
[SDK Automation - JS] Adopt `tsp-client` in automation script

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8048]
See the linked epic for details.

Refer to this usage for other language.
https://github.com/Azure/azure-sdk-for-java/blob/17ad2f817e33378f9389ed98a2d50711ba258360/eng/automation/generate_utils.py#L365

@MaryGao @qiaozha

**Comment by wanlwanl** [comment]
Renhe's context: 

The overall goal is to
'tsp-client adoption
Adopt tsp-client to replace the common powershell script to interact with tsp-config.yaml, fetch the TypeSpec specs, and run TypeSpec language emitters.
This could improve the logging experience for the steps tsp-client tool covers.'

**Comment by wanlwanl** [comment]
Ziwei is fixing in #8723
