### ISSUE TITLE
[SDK Automation - .NET] Adopt `tsp-client` in automation script

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8049]
See the linked epic for details.

- update scripts in azure-sdk-for-net to adopt tsp-client
- remove previous scripts (typespec-XXX.ps1)from azure-sdk-tools so they don't show up in azure-sdk-for-net/eng/common any longer

@chunyu3

**Comment by chunyu3** [comment]
depend on https://github.com/Azure/azure-sdk-tools/issues/8352
