### ISSUE TITLE
[SDK Automation - Java] Support SDK generation in CI pipeline for the services migrated from Swagger to TypeSpec

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8055]
If the migrated service has existing customized SDK code, the automation will keep them and report the error in the compiling step when the generated codes are not compatible with existing code. 

This refers to the option 1 described in the linked epic.

> option 1: keep the existing customized SDK code and generate the SDK code based on TypeSpec specs.
> If the customized SDK code is not compatible with the new specs, the generation should fail in the build/compile step providing the comprehensive error message, such as "The SDK has customized SDK code and might not be compatible with the new specs, the service team may need to update the customized code or the new specs."

@weidongxu-microsoft

**Comment by raych1** [comment]
Synced with @weidongxu-microsoft offline and summarized the agreement as follows.

Given that this scenario is corner case, we will implement a basic solution to clean up the existing SDK code and generate the new code based on the TypeSpec. We also mention this generation strategy in the log and provide the guidance for the service team.

**Comment by weidongxu-microsoft** [comment]
Generate from TypeSpec is good. Upon compile failure and finding "swagger" folder existed, it will delete the folder and re-generate a fresh SDK from TypeSpec.
https://github.com/Azure/azure-rest-api-specs/pull/29521/checks?check_run_id=26456973433

However, the error in above CI comes from the "generate from Swagger" step https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3888703&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=164

Can we avoid triggering the Swagger flow, if service has configured TypeSpec for language?
