### ISSUE TITLE
[SDK Automation - JS] Support SDK generation in CI pipeline for the services migrated from Swagger to TypeSpec

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8057]
If the migrated service has existing customized SDK code, the automation will keep them and report the error in the compiling step when the generated codes are not compatible with existing code. 

This refers to the option 1 described in the linked epic.

> option 1: keep the existing customized SDK code and generate the SDK code based on TypeSpec specs.
> If the customized SDK code is not compatible with the new specs, the generation should fail in the build/compile step providing the comprehensive error message, such as "The SDK has customized SDK code and might not be compatible with the new specs, the service team may need to update the customized code or the new specs."

@MaryGao

**Comment by raych1** [comment]
Synced with @wanlwanl and he will verify for both modular codeGen and RLC codeGen.

**Comment by wanlwanl** [comment]
Code gen method:
- autorest: codegen will clear code, so automation doesn't need to clear again
- typespec: automation should clear package folder before code gen
