### ISSUE TITLE
Update ARM wiki to remove references to OpenAPI Hub

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8073]
More details can be found here:
https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullRequest/937#1711332886

**Comment by maririos** [comment]
- ARM wiki PR: https://msazure.visualstudio.com/DefaultCollection/One/_git/AzureUX-ARMWiki/pullrequest/9941775

**Comment by maririos** [comment]
Changes have been merged and are live: https://armwiki.azurewebsites.net/rpaas/swaggeronboarding.html

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/66a9c43f-fe7c-4338-ba5b-68a735feccc0)
