### ISSUE TITLE
Update the Release Planner ADO state to use "Complete" vs "Finished"

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8075]
The reason that the Release Planner ADO state is "Finished" was to keep the terminology consistent between the Release Planner and ADO.  Since the Release Planner UI uses the term "Complete", the Release Planner state should be changed to use "Complete".  Once all of the existing release plan states are changed from "Finished to Complete", we can remove the "Finished" state from the Release Plan ADO template.  

- [ ] Add a state named "Complete" to the Release Planner Azure Devops (ADO) work item template. 
- [ ] Change back-end automation to set the state of the Release Plan work item to "Complete" instead of "Finished" when a release plan is completed. 
- [ ] Update all existing Release Plans with a state of "Finished" to "Complete".  If this cannot be done via the back-end automation, then it can be done manually. A query with that is filtered to include all Release Plans with State = Finished can be exported from Azure Devops. Once exported, then the value of the state can be changed to "Complete".

**Comment by maririos** [comment]
@ladonnaq  Curious, besides consistency, what problem is this causing?
Asking because this will take time and I want to understand the priority

**Comment by maririos** [comment]
Closing as a dup of #8071
