### ISSUE TITLE
Existing SDK field needs to be changed to include a data plane and management plane existing SDK field.  

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8081]
In the current onboard UI flow, there is only one option to select existing SDKs.  This is not enough detail to determine the onboarding scope for the new product or new functionality.  New services and new products will often add data plane REST APIs at or even after GA. 

Update the onboard UI to include a field for existing SDKs, then a sub-field for user to select "data plane" and/or "management plane". 

We can improve even further after the RP namespace feature and new ARM RP namespace field is included in the onboard UI flow - https://github.com/Azure/azure-sdk-tools/issues/8079 and https://github.com/Azure/azure-sdk-tools/issues/7503.  If the RP namespace is new, then there are no existing SDKs for management plane.

**Comment by maririos** [comment]
It is covered by the implementation of issue https://github.com/Azure/azure-sdk-tools/issues/7084
