### ISSUE TITLE
Investigate what other services are using the `sdk-dl-pub` endpoint

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8084]
As part of https://github.com/Azure/azure-sdk-tools/issues/7964 we identified that there were 26 requests to the `sdk-dl-pub` endpoint in the backend of OpenAPI Hub. This endpoint is used for dowloading the public SDK artifact.

We have to identify where these calls are coming, see if this is necessary, and come up with a way to replace this if needed,

**Comment by maririos** [comment]
After talking to Ray, he created issue: https://github.com/Azure/azure-sdk-tools/issues/8114

**Comment by maririos** [comment]
But we can go ahead and turn off OpenAPI hub even if the code is still not deleted. They are no longer using it
