### ISSUE TITLE
Investigate why there are many requests for `docs/previews` endpoint

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8085]
As part of https://github.com/Azure/azure-sdk-tools/issues/7964 we identified that there have been at least 422 calls to this endpoint.

It seems that the OpenAPI portal do multiple calls to this endpoint everytime a user wants to preview the docs. We just have to make sure that no external tool is using this endpoint and that there is nothing unexpected with the weird amount of call.s

**Comment by maririos** [comment]
I think I found where this is happening. 
When a PR is created, the job `Swagger ApiDocPreview` is executed. As part of it, the CI is using OpenAPI Hub code.
See for exampel the output of PR https://github.com/Azure/azure-rest-api-specs/pull/28742
When clicking in `Please click here to preview with your @microsoft account.`, the user sees https://review.learn.microsoft.com/en-us/rest/api/azure-rest-preview/?branch=result_c5e68036-e9fb-4a80-b631-c7f662763a59&view=azure-rest-preview:

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/1915a083-0873-4621-b39f-6fe5e7dabb90)

Code for this is https://devdiv.visualstudio.com/DevDiv/_git/openapi-portal?path=/src/backend/js/docsGeneration/DocsGeneration.ts
