### ISSUE TITLE
[SDK Automation] Remove ANSI code from displaying in the SDK automation result

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8087]
Some SDK language automation will use the ANSI code to control the color of text displayed in the console terminal. However, it is not recognized in the html content in github comment.  It makes the user difficult to understand the log.

Example:
```powershell
cmderr	[Invoke-GenerateAndBuildV2.ps1] �[31;1mGeneratePackage: �[0m/mnt/vss/_work/1/s/azure-sdk-for-net/eng/scripts/Invoke-GenerateAndBuildV2.ps1:131�[0m
cmderr	[Invoke-GenerateAndBuildV2.ps1] �[31;1m�[0m�[36;1mLine |�[0m
cmderr	[Invoke-GenerateAndBuildV2.ps1] �[31;1m�[0m�[36;1m�[36;1m 131 | �[0m               �[36;1mGeneratePackage `�[0m
cmderr	[Invoke-GenerateAndBuildV2.ps1] �[31;1m�[0m�[36;1m�[36;1m�[0m�[36;1m�[0m�[36;1m     | �[31;1m               ~~~~~~~~~~~~~~~~~�[0m
cmderr	[Invoke-GenerateAndBuildV2.ps1] �[31;1m�[0m�[36;1m�[36;1m�[0m�[36;1m�[0m�[36;1m�[31;1m�[31;1m�[36;1m     | �[31;1mFailed to build sdk. exit code: False�[0m
cmderr	[Invoke-GenerateAndBuildV2.ps1] �[31;1mGeneratePackage: �[0m/mnt/vss/_work/1/s/azure-sdk-for-net/eng/scripts/Invoke-GenerateAndBuildV2.ps1:131�[0m
cmderr	[Invoke-GenerateAndBuildV2.ps1] �[31;1m�[0m�[36;1mLine |�[0m

These ANSI codes should be removed from the log before rendering in the html content.

**Comment by raych1** [comment]
Code snippet for reference to remove ANSI codes:

```powershell
function Remove-AnsiEscapeCodes {
    param (
        [Parameter(Mandatory=$true)]
        [string]$Text
    )

    # ANSI escape codes start with the ESC character (\u001b or `e in PowerShell)
    # followed by [, then zero or more numbers or semicolons, and end with a letter.
    $ansiEscapeCodeRegex = "`e\[[0-9;]*[A-Za-z]"

    $Text -replace $ansiEscapeCodeRegex, ""
}
```

You can use this function to remove ANSI escape codes from a string. For example:
$errorText = "\u001b[31;1mError:\u001b[0m Something went wrong"
$plainText = Remove-AnsiEscapeCodes -Text $errorText

After running this code, $plainText will contain the string "Error: Something went wrong", with all ANSI escape codes removed.

**Comment by JackTn** [comment]
Use this regexp `/\x1b\[(\d{1,2}(;\d{0,2})*)?[A-HJKSTfimnsu]/` instead. And pr is  https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/544280 test snapshot is https://github.com/test-repo-billy/azure-rest-api-specs/pull/3285

**Comment by raych1** [comment]
Fixed in production: https://github.com/Azure/azure-rest-api-specs/pull/28716#issuecomment-2060682829
