### ISSUE TITLE
Look into AzSecPack for APIView

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8093]
Reading the documentation, it doesn't look like we need to install it as APIView is an Azure App Service. We are still responsible of audit logs and other metric collection.
More information here: https://eng.ms/docs/microsoft-security/cloud-ecosystem-security/azure-security/security-health-analytics/azure-security-monitoring-asm-slam/azure-security-monitoring/azuresecuritypack/home/azsecpackoverview

**Comment by maririos** [comment]
While we are at it, might as well check: https://identitydivision.visualstudio.com/IdentityWiki/_wiki/wikis/IdentityWiki.wiki/55423/Otel-Audit-Library-Usage

We might be able to do both in one go as both are about audit logs

**Comment by praveenkuttappan** [comment]
> While we are at it, might as well check: https://identitydivision.visualstudio.com/IdentityWiki/_wiki/wikis/IdentityWiki.wiki/55423/Otel-Audit-Library-Usage
> 
> We might be able to do both in one go as both are about audit logs

It's unclear what is required to be done. Can you please provide more context about this change?

**Comment by praveenkuttappan** [comment]
This change is not required for APIview which is deployed as Azure app service and also note that APIView does not use Geneva.
