### ISSUE TITLE
[SDK Automation - Java] Improve the logging to be concise and actionable

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8096]
The user is having difficulty to understand the error reported in the SDK generation log and is unsure of how to proceed.

Refine the error logs to enhance clarity and conciseness, provide guidance on corrective actions, and include relevant document links as necessary. The logging should include three parts information if possible.

- error code or error message
- next steps or suggested actions
- associated document links if have

@weidongxu-microsoft

**Comment by weidongxu-microsoft** [comment]
@raych1 

Do you plan to have some consistency on error?

E.g. do you want something consistent, if automation find that tspconfig is not correct.

**Comment by weidongxu-microsoft** [comment]
Part of the logging and "recommendation on failure" is included in the tspconfig validation PR https://github.com/Azure/azure-sdk-for-java/pull/39953

**Comment by raych1** [comment]
As synced, we will monitor the errors reported in the log and improve them if necessary next two months.
