### ISSUE TITLE
[SDK Automation - JS] Improve the logging to be concise and actionable

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8098]
The user is having difficulty to understand the error reported in the SDK generation log and is unsure of how to proceed.

Refine the error logs to enhance clarity and conciseness, provide guidance on corrective actions, and include relevant document links as necessary. The logging should include three parts information if possible.

- error code or error message
- next steps or suggested actions
- associated document links if have

@MaryGao

**Comment by wanlwanl** [comment]
Will do in next week
