### ISSUE TITLE
Clean up connection references in our environments

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8108]
- [x] Stablish an strategy for connection references
- [x] Document statregy in our Release Planner wiki https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/832/Release-Planner-App
- [x] Clean up environments
  - [x] DEV
  - [x] PPE
  - [x] PROD

**Comment by maririos** [comment]
Document update: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/946/Troubleshooting?anchor=create-a-new-flow

**Comment by JonathanCrd** [comment]
Deployment to PROD has been completed.
