### ISSUE TITLE
Document `sdk-suppressions.yaml` support and relevant labels in aka.ms/pr-suppressions

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#8134]
See the `CAUTION` note in:
- https://github.com/Azure/azure-sdk-tools/issues/8133

Doc contribution guide:
- https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms?path=/README.MD

The doc source:
- https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms?path=/docs/design/specs-pr-guides/pr-suppressions.md

@raych1 @JackTn FYI

**Comment by raych1** [comment]
Guidance has been added to https://eng.ms/docs/products/azure-developer-experience/design/specs-pr-guides/pr-suppressions.
