### ISSUE TITLE
C# emitter package points to a very old version while publishing C# generator

### ISSUE THREAD

**Issue by live1206** [Azure/azure-sdk-tools#8137]
After I merge my change to autorest.csharp, the CI publishes the corresponding packages and create PR in azure-sdk-for-net.

But somehow, the `emitter-package-lock.json` points `@autorest/csharp` to a very old version `3.0.0-beta.20230309.1` as
```
    "node_modules/@autorest/csharp": {
      "version": "3.0.0-beta.20230309.1",
      "resolved": "https://registry.npmjs.org/@autorest/csharp/-/csharp-3.0.0-beta.20230309.1.tgz"
    },
```
The artifacts can be found in this [CI run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3718875&view=artifacts&pathAsName=false&type=publishedArtifacts), which contains the above content

**Comment by hallipr** [comment]
It looks like the command `npm install @autorest/csharp@3.0.0-beta.20240422.1 --save-exact` failed:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3718875&view=logs&j=b5cdfb1e-c180-561f-918e-a169e451719e&t=bba6bcd4-3b77-59b2-cfc4-b19094ee8575&l=159
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @autorest/csharp@3.0.0-beta.20240422.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in: C:\npm\cache\_logs\2024-04-22T07_36_48_359Z-debug-0.log
```

We appear to be vulnerable to race conditions between npmjs indexing a newly published package and our call to install the package.   Perhaps we could look at consuming the package as a file:/ reference, then mutating the package.json prior to publishing instead.
