### ISSUE TITLE
NewTestResources.ps1 script to be made NS 2 compliant.

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-tools#8186]
Currently the NewTestResources.ps1 script deploys resources with public internet access enabled.
It needs to deploy resources with public internet access disabled or access allowed from selected virtual networks / IP addresses.

The resources in focus are: 
1. Storage
2. Cosmos
3. Kusto
4. SQL server
5. KV.

**Comment by benbp** [comment]
Closing for now as the approach is going to be changed at a higher level (arm templates, service tagging, aux tenant)
