### ISSUE TITLE
Gaps in data needed for Engagement Experience PowerBI Report

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8194]
There are several gaps in data needed for Engagement Experience PowerBI Report.  

**Release Plan work item** 
- [x] The SDK Release Milestone work item field needs to be updated with progress.  When user opens/accesses SDK release milestone app for first time, change work item field value to "In Process".  
- [x] Update APEX PM, Engineering Lead, and Primary PM work item fields with the data in the release plan.  The field value should contain the email address or the full name + shortname/alias so that it is easier to contact the correct the person if needed. 
- [x] Update release plan work item field "SDK type to be released" when release plan is created.  This maps to the SDK type selected when user creates a release plan. 
- [x] Create new single text custom ADO field named "Languages" and update with value based on the languages selected in the release plan.  
- [x] Create new single text custom ADO field for "Architecture Board review link".  I expect that the scheduler tool has this data.

**Comment by maririos** [comment]
>  Create new field "Languages in scope" and update with value based on the languages selected in the release plan.
 Create new field for "Architecture Board review link". I expect that the scheduler tool has this data.

@ladonnaq is this something you can do from the ADO workitem template's perspective?

**Comment by ladonnaq** [comment]
> > Create new field "Languages in scope" and update with value based on the languages selected in the release plan.
> > Create new field for "Architecture Board review link". I expect that the scheduler tool has this data.
> 
> @ladonnaq is this something you can do from the ADO workitem template's perspective?

Yes but I do not access to edit. If we change my access, I can do it. I would recommend I make the changes in ADO first, then engineering updates the automation. We just need to coordinate the timing,

**Comment by maririos** [comment]
> > > Create new field "Languages in scope" and update with value based on the languages selected in the release plan.
> > > Create new field for "Architecture Board review link". I expect that the scheduler tool has this data.
> > 
> > 
> > @ladonnaq is this something you can do from the ADO workitem template's perspective?
> 
> Yes but I do not access to edit. If we change my access, I can do it. I would recommend I make the changes in ADO first, then engineering updates the automation. We just need to coordinate the timing,

I thought you only needed to request JIT access and then you are good to go. Same as when you deleted some of the queries and moved some to other places

**Comment by ladonnaq** [comment]
> > > > Create new field "Languages in scope" and update with value based on the languages selected in the release plan.
> > > > Create new field for "Architecture Board review link". I expect that the scheduler tool has this data.
> > > 
> > > 
> > > @ladonnaq is this something you can do from the ADO workitem template's perspective?
> > 
> > 
> > Yes but I do not access to edit. If we change my access, I can do it. I would recommend I make the changes in ADO first, then engineering updates the automation. We just need to coordinate the timing,
> 
> I thought you only needed to request JIT access and then you are good to go. Same as when you deleted some of the queries and moved some to other places

You were correct, after I activated the [ADO-AZURE-SDK-PCA-JIT](https://ms.portal.azure.com/?feature.msaljs=true#view/Microsoft_Azure_PIMCommon/ResourceMenuBlade/~/members/resourceId/af620bb3-d162-4be9-a842-1a193ac635dc/resourceType/Security/provider/aadgroup/resourceDisplayName/ADO-AZURE-SDK-PCA-JIT/resourceExternalId/af620bb3-d162-4be9-a842-1a193ac635dc) Group, and re-evaluated permissions in Azure Devops, I can now edit the work item templates. I will add the new fields today (05/14/2024) and update this GitHub issue.

**Comment by maririos** [comment]
For 2:

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/d00b3747-c117-47f6-a955-bae10e143499)

**Comment by maririos** [comment]
For 2:

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/4e99917d-64c7-4377-a84a-57e5e360aaeb)

**Comment by maririos** [comment]
FYI @ckairen  I wonder if https://github.com/Azure/azure-sdk-tools/issues/6760 will get fixes with your changes. IF not, feel free to close it
