### ISSUE TITLE
Cleanup OpenAPIHub custom connector

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#8211]
Remove OpenAPIHub custom connector and the service principal used for authentication.

**Comment by maririos** [comment]
oh plop. I thought we had eliminated it from all of the apps. Do you know which ones still need it?

**Comment by praveenkuttappan** [comment]
Connector itself and env variables and secrets in the KV that's used by connectors.

**Comment by praveenkuttappan** [comment]
Custom connectors for OpenAPIHub and Devops have been removed now. Cleanup of KV variables is yet to be done.
