### ISSUE TITLE
[SDK Automation] Beta version is flagged incorrectly for JS SDK

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8218]
This issue only happens for JS language SDK. When the SDK is flagged as beta version, then the breaking change will not be rendered in the spec PR and the breaking change label won't be added to the spec PR.

This is an example [spec PR](https://github.com/Azure/azure-rest-api-specs/pull/28926) that has this issue.

**Comment by lirenhe** [comment]
Close it as completed
