### ISSUE TITLE
Integrate SDK Release Request into the Release Planner with new features

### ISSUE THREAD

**Issue by JonathanCrd** [Azure/azure-sdk-tools#8232]
(Draft) Revised design that separates the request for SDK generation from the request for SDK release.    
https://www.figma.com/board/fpBODZ0TcpJ481HCvY926J/SDK-Release-Milestone---Management?node-id=1-435&t=F4Mwoi0cKchHHwqw-1 

**History:** 
In order to deprecate OpenAPI Hub, we created a new app to replace the Request SDK Release feature in:
- https://github.com/Azure/azure-sdk-tools/issues/8009
- Also, check if PR is merged prior to requesting release of management plane SDKs - https://github.com/Azure/azure-sdk-tools/issues/5387  

For this task, we have to integrate this process in the Management SDK Release App and use information from the Release Plan.

There are some new features requested by the Management Plane team that can be found in the original issue and must be implemented too.

**Comment by maririos** [comment]
![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/d42ed28c-6f6d-48ae-aee8-21469c040bc8)

**Comment by maririos** [comment]
To take into account in the design: https://github.com/Azure/azure-sdk-tools/issues/8393#issuecomment-2155486314

**Comment by ladonnaq** [comment]
Related to https://github.com/Azure/azure-sdk-tools/issues/8431 (long-term approach for handling OpenAPI when TypeSpec SDK generation is automated). We may be able to start to align the processes when we integrate the SDK release request app into the release plans.

**Comment by ladonnaq** [comment]
@maririos @praveenkuttappan - Do you think we can close this issue since we will address the issues in the redesign of the SDK release milestone for mgmt TypeSpec scenarios?  I believe we have captured everything in the revised workflow diagram.

**Comment by maririos** [comment]
We will need a new GH issue with the changes to the UI
