### ISSUE TITLE
[SDK Automation] different generateInput.json when both swagger and typespec changed

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-tools#8251]
In https://github.com/Azure/azure-rest-api-specs/pull/29085/files, Python changes both of swagger and tsp, according to [log](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3782125&view=logs&j=b7f68bce-9df8-5468-1c9f-74766cfc9a39&t=25fc8ae6-51ed-58e2-b772-f4d054412fe3), pipeline provides `generateInput.json` like:
![image](https://github.com/Azure/azure-sdk-tools/assets/70930885/c5443195-9414-4a1c-8346-42ed3f0c7889)
which only contains changes about typespec.

However, in https://github.com/Azure/azure-rest-api-specs/pull/29019/files. Java changes both of swagger and tsp, according to https://[dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/3782156/logs/480](https://dev.azure.com/azure-sdk/590cfd2a-581c-4dcb-a12e-6568ce786175/_apis/build/builds/3782156/logs/480), pipeline is called twice with different generateInput.json
![image](https://github.com/Azure/azure-sdk-tools/assets/70930885/d50329aa-a83a-4206-a2fa-63e02a5aa777)

![image](https://github.com/Azure/azure-sdk-tools/assets/70930885/aa1f6809-eef3-4308-b153-a4f9376afc6b)

**Comment by raych1** [comment]
@msyyc , the difference between Python automation run and Java automation run is the configured mode for generation is different. Refer to Python config and Java config.

When using the 'one-for-all-configs' mode in SDK automation, the generation process will prioritize `TypeSpec` over `Swagger`. This can result in the generation being skipped based on `swagger` if `TypeSpec` is present. If we want to generate SDK from swagger, the emitter option should be deleted or commented out.

**Comment by msyyc** [comment]
@raych1 I hope pipeline could keep current process for **Python that only typespec folder are provided even if both of tyepspec and swagger folder are changed**.

**Comment by raych1** [comment]
Yes, we agree on this strategy currently.
