### ISSUE TITLE
[Python APIView] weird rendering of enum kwarg

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-tools#827]
`api_version` should be Union[str, ApiVersion]. Instead it's being returned as:

![image](https://user-images.githubusercontent.com/43154838/88837066-b41f9880-d1a5-11ea-8c5b-49c8e1b0483f.png)

Sphinx docs [here](https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py#L64). It appears its catching the beginning of the ..admonition section

**Comment by praveenkuttappan** [comment]
@iscai-msft Is this still an issue in latest reviews?

**Comment by tjprescott** [comment]
This should be fixed in 0.2.6

**Comment by tjprescott** [comment]
This should be fixed. Please reopen if that is not the case.
