### ISSUE TITLE
(PM task) Determine how many existing services have handwritten or generated SDKs + convenience layer 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8274]
Identify the number of services that are either blocked or not fully supported by the Release Planner App.  The data will help us to determine the priority in supporting additional release scenarios or improving existing release scenarios. 
 
@ronniegeraghty - Is there a list or way to identify services that have handwritten or generated SDKs + convenience layer?

**Comment by ronniegeraghty** [comment]
I don't believe there is currently a programmatic way to identify what libraries are fully generated vs generated w/ convince layer vs fully hand crafted. Unless the language generators leave some form of watermark on the code they produce that we could pick up on to identify them as generated and/or something similar for convince/hand crafted code.

In a more manual effort, I could start requiring teams that come to the Arch Board to have a linked Release plan. That would send a lot of teams your way with questions on if they can use the release planner with their scenario.

**Comment by ladonnaq** [comment]
> @ladonnaq could you share why the services that have `convenience layer?` are blocked using the Release Planner?

"Identify the number of services that are either blocked or **_not fully supported_** by the Release Planner App."   We need to improve the release plans for this scenario by adding documentation to explain how the SDK PR review process.  Ronnie is going to discuss with Krzysztof and the arch board. There is no consolidated process documented as far as we know.  GitHub issue for docs - https://github.com/Azure/azure-sdk-tools/issues/8178.

**Comment by ladonnaq** [comment]
> I don't believe there is currently a programmatic way to identify what libraries are fully generated vs generated w/ convince layer vs fully hand crafted. Unless the language generators leave some form of watermark on the code they produce that we could pick up on to identify them as generated and/or something similar for convince/hand crafted code.
> 
> In a more manual effort, I could start requiring teams that come to the Arch Board to have a linked Release plan. That would send a lot of teams your way with questions on if they can use the release planner with their scenario.

@maririos has updated the scheduling tool to include a field for the release plan.  Maybe we need to add a question to the "Create a release plan" UI to allow users to identify if they have an existing generated SDK with a convenience layer.  
<img width="798" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/67656762/233cda38-cbfc-4df0-a009-e42192ee0de0">

**Comment by maririos** [comment]
@ladonnaq 

> by adding documentation to explain how the SDK PR review process

This applies to everyone, not just convenience layers. Basically how it works today is we tell them "hey go and read each repo documentation to figure out what you need to do to get your data plane SDK ready and then go to an archboard". This has nothing to do with convenience layers.
So why are we focusing on that?

**Comment by ladonnaq** [comment]
Closing issue.  We know that the handcrafted and SDK team releases the SDK on behalf of the service partner are the only release scenarios not onboarded to use the release planner yet.  We will pilot using release plans as-is for this semester and then in Selenium we can decide if there needs to be any modification to improve efficiency of the workflows for these scenarios.
