### ISSUE TITLE
Release Plans that need status changed to "Abandoned" or "Complete"

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8290]
The Onboarding PM team is following up with service partners who have overdue release plans.  

The following release plans need state changed to "Abandoned".  

- [x] 1298 - https://aka.ms/sdk-release-planner?release-plan-id=6a645f6e-ed17-ef11-9f89-000d3a3754d9
- [x] 1168 - https://aka.ms/sdk-release-planner?release-plan-id=21c35845-eb9d-ee11-be37-000d3a341a24
- [x] 1254 - https://web.powerapps.com/apps/821ab569-ae60-420d-8264-d7b5d5ef734c?release-plan-id=a83c4824-60f0-ee11-904c-000d3a3412d3   
- [x] 1255 - https://web.powerapps.com/apps/821ab569-ae60-420d-8264-d7b5d5ef734c?release-plan-id=8c031aaa-60f0-ee11-904b-000d3a3783ac
- [x] 1256 - https://web.powerapps.com/apps/821ab569-ae60-420d-8264-d7b5d5ef734c?release-plan-id=155e1dd5-60f0-ee11-904c-000d3a3412d3 
- [x] 1136 - https://aka.ms/sdk-release-planner?release-plan-id=1ee320a8-7472-ee11-9ae7-000d3a340b2c (Communications Gateway)
- [x] 1156 - https://aka.ms/sdk-release-planner?release-plan-id=3e58d16e-978e-ee11-8179-000d3a3412d3 (Azure Center for SAP Solutions)
- [x] 1156 - https://aka.ms/sdk-release-planner?release-plan-id=3e58d16e-978e-ee11-8179-000d3a3412d3 (Azure Center for SAP Solutions)
- [x] 1194 - https://aka.ms/sdk-release-planner?release-plan-id=f2623579-a2b9-ee11-a569-000d3a3418aa (AKS Backup - Vault Tier & CRR)
- [x] 1148 - https://aka.ms/sdk-release-planner?release-plan-id=cfe52659-af79-ee11-8179-000d3a3418aa (AI Studio) 
- [x] https://aka.ms/sdk-release-planner?release-plan-id=e2a15c53-ed92-ee11-be37-000d3a340b2c (Azure Orbital Ground Station)
- [x] https://aka.ms/sdk-release-planner?release-plan-id=bb350477-9c9e-ee11-be37-000d3a3418aa (ASZ-Arc VMs)
- [x] https://aka.ms/sdk-release-planner?release-plan-id=5e9d3a51-97b0-ee11-a569-000d3a3412d3 (AI Studio) 
- [x] https://aka.ms/sdk-release-planner?release-plan-id=4629dc4b-23b7-ee11-a569-000d3a3418aa (release planner app test)
- [x]  https://aka.ms/sdk-release-planner?release-plan-id=4057d6b9-84da-ee11-904d-000d3a3411c3 (Defender for APIs)
- [x] 1062 auto-abandon
- [x] 1065 auto-abandon
- [x] 1064 auto-abandon
- [x] 1103 auto-abandon (Playwright - created in Sept before SDK release milestone) 
- [x] 1280 auto-abandon

The following release plans need state changed to "Complete".  
- [x] https://aka.ms/sdk-release-planner?release-plan-id=ad64f80e-6d9f-ee11-be37-000d3a341a24  (Quantum) 
- [ ] https://aka.ms/sdk-release-planner?release-plan-id=497ea72d-7ebf-ee11-9079-000d3a3412d3  (Liftr-Informatica) 
- [x] https://aka.ms/sdk-release-planner?release-plan-id=ead0ccad-b0ca-ee11-9079-000d3a341bd5 (NetApp feature) 
- [x] https://aka.ms/sdk-release-planner?release-plan-id=24d0f6d7-b3d1-ee11-9079-000d3a3411c3 (NetApp feature) 
- [x] https://aka.ms/sdk-release-planner?release-plan-id=0f221f58-b4d1-ee11-9079-000d3a3411c3 (NetApp feature) 
- [x] https://aka.ms/sdk-release-planner?release-plan-id=b9106d81-acd2-ee11-9079-000d3a341bd5 (API Center, Python only release). 
- [x] https://aka.ms/sdk-release-planner?release-plan-id=1bb81747-8872-ee11-9ae7-000d3a3411c3 (Azure Logic Apps - Azure Arc)
- [x] https://aka.ms/sdk-release-planner?release-plan-id=b1c549ce-d378-ee11-8179-000d3a3418aa (Azure Monitor SCOM Managed Instance)
- [x] https://aka.ms/sdk-release-planner?release-plan-id=17a30c77-0c78-ee11-8179-000d3a341bd5 (Apache Airflow on Astro - An Azure Native ISV Service)
- [x] https://aka.ms/sdk-release-planner?release-plan-id=8cc1bc92-d878-ee11-8179-000d3a3412d3 (Semantic Search)
- [x] https://aka.ms/sdk-release-planner?release-plan-id=d4f94dbd-ae79-ee11-8179-000d3a340b2c (Azure AI Studio)
- [x] https://aka.ms/sdk-release-planner?release-plan-id=cf2bb307-ec83-ee11-8179-000d3a3411c3 (Document Translation) 
- [x] https://aka.ms/sdk-release-planner?release-plan-id=3df8b542-d38d-ee11-8179-000d3a341a24 (Azure Center for SAP Solutions)
- [x] https://aka.ms/sdk-release-planner?release-plan-id=ef64cb1e-c572-ee11-9ae7-000d3a3411c3 (Dev Box)
- [x] https://aka.ms/sdk-release-planner?release-plan-id=ba9ad94a-4027-ef11-840b-000d3a3783ac
- [x] 1268 auto-complete
- [x] 1060 auto-complete
- [x] 1341 auto-complete
- [x] 1362 auto-complete
- [x] 1372 auto-complete
- [x] 1373 auto-complete 
- [x] 1374 auto-complete 
- [x] 1366 auto-complete 
- [x] 1251 auto-complete 
- [x] 1304 auto-complete

Table of release plan IDs and the new state.  I tagged the release plan work items with the appropriate tag and exported query to create a table so it would be easier for me to track.  I used the tags auto-complete and auto-automate. 

Status | ReleasePlanID | Tags
--| -- | --
✅ | 1360 | auto-abandon
✅ | 1350 | auto-abandon
✅ | 1339 | auto-abandon
✅ | 1331 | auto-abandon
✅ | 1328 | auto-abandon
✅ | 1316 | auto-abandon
✅ | 1310 | auto-abandon
✅| 1294 | auto-abandon
✅ | 1288 | auto-abandon
✅ | 1279 | auto-abandon
✅ | 1272 | auto-abandon
✅ | 1271 | auto-abandon
✅ | 1266 | auto-abandon
✅ | 1263 | auto-abandon
✅ | 1246 | auto-abandon
✅ | 1212 | auto-abandon
✅ | 1210 | auto-abandon
✅ | 1200 | auto-abandon
✅ | 1197 | auto-abandon
✅ | 1177 | auto-abandon
✅ | 1161 | auto-abandon
✅ | 1146 | auto-abandon;   extension-data-PrivPrev; TypeSpec data
✅ | 1142 | auto-abandon
✅ | 1113 | auto-abandon
✅ | 1062 | auto-abandon
✅ | 1035 | auto-abandon
✅ | 1033 | auto-abandon;   retired before GA; retiring the service under process
✅ | 1030 | auto-abandon
✅ | 1101 | auto-abandon
✅ | 1041 | auto-abandon
✅ | 1067 | auto-abandon
✅ | 1088 | auto-abandon
✅ | 1057 | auto-abandon
✅ | 1097 | auto-abandon
✅ | 1313 | auto-complete
✅ | 1302 | auto-complete
✅ | 1259 | auto-complete
✅ | 1244 | auto-complete
✅ | 1243 | auto-complete
✅ | 1241 | auto-complete
✅ | 1230 | auto-complete
✅ | 1229 | auto-complete
✅ | 1224 | auto-complete
✅ | 1214 | auto-complete
✅ | 1199 | auto-complete
✅ | 1193 | auto-complete
✅ | 1189 | auto-complete
✅ | 1124 | auto-complete
✅ | 1038 | auto-complete
✅ | 1096 | auto-complete
✅ | 1039 | auto-complete
✅ | 1050 | auto-complete

**Comment by maririos** [comment]
@ladonnaq what do you recommend to do for the `completed` Release plans? Current information is not accurate, but overwritting DB might cause the same as we won't have all information or dates correctly.

Maybe something we can do is complete the Release plans on the DB and add something in the release plan work item that identifies the release plan as closed automatically. A label? a comment? a field?

What do you think will be more easier to query and mantain?

**Comment by ladonnaq** [comment]
> @ladonnaq what do you recommend to do for the `completed` Release plans? Current information is not accurate, but overwritting DB might cause the same as we won't have all information or dates correctly.
> 
> Maybe something we can do is complete the Release plans on the DB and add something in the release plan work item that identifies the release plan as closed automatically. A label? a comment? a field?
> 
> What do you think will be more easier to query and mantain?

@maririos Go ahead and mark the release plans as complete in the DB and for the Release Plan work item do the following: 

- [ ] Change the state to "Finished" 
- [ ] Add tag "auto-closed"

**Comment by maririos** [comment]
> * Change the state to "Finished"
> * [ ]  Add tag "auto-closed"

Ok. I have created automation for this to work. Once this is in prod I will start marking all the selected issues as `completed`.
More details on implementation here: https://github.com/Azure/azure-sdk-tools/issues/8872

**Comment by maririos** [comment]
Improvement to this process is tracked: https://github.com/Azure/azure-sdk-tools/issues/8921

**Comment by maririos** [comment]
All done
