### ISSUE TITLE
Allow user to edit the SDK type in the Release Plan summary 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8293]
The SDK codegen team needs to track # of Beta vs Stable SDK releases by month.  There is currently no functionality in the release planner to allow the user to change the SDK Type after the release plan is created.   We should allow user's to edit this field in the near-term.  
 

- [ ] Until we address the gaps identified in this GitHub issues - https://github.com/Azure/azure-sdk-tools/issues/8291,  allow user to edit the SDK release type from the Release Plan Summary view. 
- [ ] When a release plan is created update the "SDK type to be released" field in the release plan work item.  If the value changes in the release plan, ensure that the value is also updated in the release plan work item.

**Comment by maririos** [comment]
@ladonnaq In which circumstances will the SDK type change?

**Comment by ladonnaq** [comment]
> @ladonnaq In which circumstances will the SDK type change?
I will provide additional detail later this afternoon.

**Comment by ladonnaq** [comment]
@maririos - Instead of allowing the user to update the "SDK types to be released" field in the release plan summary.  We could go ahead and modify the Create a release plan UI to include API Spec type (preview/stable depending on release plan) and limit Public Preview release plans to Beta SDKs and GA release plans to Stable SDKs.  The requirements in this GitHub issue - https://github.com/Azure/azure-sdk-tools/issues/8291.

**Comment by maririos** [comment]
> @maririos - Instead of allowing the user to update the "SDK types to be released" field in the release plan summary. We could go ahead and modify the Create a release plan UI to include API Spec type (preview/stable depending on release plan) and limit Public Preview release plans to Beta SDKs and GA release plans to Stable SDKs. The requirements in this GitHub issue - #8291.

Sounds good. :)

**Comment by lahsha** [comment]
@maririos , can we assign this to @eatkimchee please?

**Comment by maririos** [comment]
> @maririos , can we assign this to @eatkimchee please?

This was my bad. I tagged you by mistake. Apologies for that

**Comment by ladonnaq** [comment]
> > @maririos - Instead of allowing the user to update the "SDK types to be released" field in the release plan summary. We could go ahead and modify the Create a release plan UI to include API Spec type (preview/stable depending on release plan) and limit Public Preview release plans to Beta SDKs and GA release plans to Stable SDKs. The requirements in this GitHub issue - #8291.
> 
> Sounds good. :)

I will close this issue and we will take the approach indicated in #8291.  Thanks!
