### ISSUE TITLE
Support the breaking detection for modular classical client

### ISSUE THREAD

**Issue by MaryGao** [Azure/azure-sdk-tools#8303]

**Comment by MaryGao** [comment]
This is supported in track 2 so we need to support them also.

**Breaking Change Categorization**
Bug (Unwanted Breaking Changes):

- [ ] Missing data from the spec in the new implementation.
- [ ] Incorrect results produced by the new implementation.
- [ ] Slight differences in the new implementation that do not improve user experience. If uncertain, categorize as unwanted.
- [x] Taking away a capability that was previously supported

Improvements (Acceptable Breaking Changes):

- [ ] Fixes broken behavior in the new implementation.
- [ ] Offers clear enhancements to user experience.
- [ ] Eliminates or discourages bad patterns.
- [ ] Provides additional functionality.
- [ ] Aligns more closely with TypeSpec standards.

**Comment by wanlwanl** [comment]
#8332

**Comment by lirenhe** [comment]
Close it as fixed.
