### ISSUE TITLE
Support Modular SDK Automation in Swagger Repo

### ISSUE THREAD

**Issue by MaryGao** [Azure/azure-sdk-tools#8307]

**Comment by MaryGao** [comment]
**EngSys and Automation Categorization**
- [ ] Parity with existing tooling in Track2
- [x] New functionality

**Comment by wanlwanl** [comment]
- script: 
  - `code-gen-pipeline --inputJsonPath=$1 --outputJsonPath=$2 --use=@autorest/typescript@^6.0.12 --typespecEmitter=@azure-tools/typespec-ts`: https://github.com/Azure/azure-sdk-for-js/blob/main/.scripts/automation_generate.sh
  - https://github.com/Azure/azure-sdk-tools/blob/c43f0da13a4ddf24a08c50bbad152495dc257f1c/tools/js-sdk-release-tools/package.json#L16
- schema: https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/sdkautomation/GenerateInputSchema.json

**Comment by wanlwanl** [comment]
Waiting for CodeGen ready
Wating for vendor test
PR: https://github.com/Azure/azure-sdk-tools/pull/8659
Test in pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4031500&view=logs&j=d604d9d3-50fa-561f-7843-6e35c47b42c6&t=f68d31e8-a71a-52e9-c8f2-e4c985408a03 (note that: 'build sample' and 'test' steps are optional, the pipeline will continue whether the steps are successful  or not; 'build sample' failure are expected)
