### ISSUE TITLE
When a user completes the management plane "Request SDK release" PowerApp, automatically check off the task in the release plan 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8318]
@maririos @praveenkuttappan As part of the PM process, we are manually reaching out to service partners to find out status on overdue release plans.  As part of the effort, we are finding service partners who have submitted the "Request SDK release" via the PowerApp but the task was not checked off in the release plan.  This is confusing and causing extra manual effort to resolve.  

I understand that engineering is working on integrating the management plane "Request SDK release" PowerApp into the SDK release milestone.  If the integration work will not be complete by mid-June, it would be good to resolve this issue.  

<img width="784" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/67656762/114c16c8-ad45-43ef-bc4d-1ee23ccfdf52">

**Comment by maririos** [comment]
For now, we can remove the check and just have the button. 
They will still need to "Verify the release"

@ladonnaq will that work?

**Comment by ladonnaq** [comment]
> For now, we can remove the check and just have the button. They will still need to "Verify the release"
> 
> @ladonnaq will that work?

If we could get this done for this release, that would be great.  I have been reaching out to teams to determine the state of their incomplete release plans.  Nearly everyone did not check the box so it is confusing.  I don't know if they requested the SDKs or not.  Also, very few of the management plane release plan work items are showing the related SDK packages.  I suspect this is related to https://github.com/Azure/azure-sdk-tools/issues/8796.

**Comment by maririos** [comment]
This will be included in the next release cycle

**Comment by ladonnaq** [comment]
[heart]         LaDonna Quinn reacted to your message:
________________________________

**Comment by praveenkuttappan** [comment]
@ladonnaq @maririos I am working on removing the checkbox in request release page. So, it will look like below. But I think we need a way to show status whether a request is released or not, so it is clear to user when they look at it again (it's more helpful in case of a release plan where multiple users are involved).

![Image](https://github.com/user-attachments/assets/310c3ec2-66bb-4539-b83c-bab64c46e46a)

**Comment by ladonnaq** [comment]
> @ladonnaq @maririos I am working on removing the checkbox in request release page. So, it will look like below. But I think we need a way to show status whether a request is released or not, so it is clear to user when they look at it again (it's more helpful in case of a release plan where multiple users are involved).
> 
> ![Image](https://private-user-images.githubusercontent.com/55455725/369972090-310c3ec2-66bb-4539-b83c-bab64c46e46a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMTg1MDksIm5iZiI6MTcyNzExODIwOSwicGF0aCI6Ii81NTQ1NTcyNS8zNjk5NzIwOTAtMzEwYzNlYzItNjZiYi00NTM5LWI4M2MtYmFiNjRjNDZlNDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE5MDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjgyN2EwNmViOTYyODdjNjk0MTc0NDU2YzUwZDkxNTMxYmNkMjBmODkwOTAyZWE2ZmQxY2JjODNkNzNjYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ae2N5UKt0oJEh-2cvCb1GquLQNwGHLOeQ_g2OArlbbI)

The issue with the box is that very user's were checking the box and the Power App re-sets so there was no way to know if someone requested the releases.  As you mention, removing the box leaves us with the same issue.  Can we Grey out the box once the "form" is submitted in the "Request SDK" Power App?

**Comment by praveenkuttappan** [comment]
I have made a change to gray out the box once release request is submitted and also shows a badge to indicate request was submitted. Please see the screenshot below. I assume this should be good enough to communicate that this step was completed.

![Image](https://github.com/user-attachments/assets/5faeb6d0-fa9a-40a5-9a11-0e2ba2f346d0)

**Comment by ladonnaq** [comment]
> I have made a change to gray out the box once release request is submitted and also shows a badge to indicate request was submitted. Please see the screenshot below. I assume this should be good enough to communicate that this step was completed. ![Image](https://private-user-images.githubusercontent.com/55455725/370053516-52bf097a-98eb-43ef-8dd7-dd57507cb04c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMjgyNjAsIm5iZiI6MTcyNzEyNzk2MCwicGF0aCI6Ii81NTQ1NTcyNS8zNzAwNTM1MTYtNTJiZjA5N2EtOThlYi00M2VmLThkZDctZGQ1NzUwN2NiMDRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDIxNDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNDkwY2MxOGMzMjFlYmU1MTc4YzBhMTUwMDg2NjQ5MjRlYTUzMjU4ZTgyMzFiYmQ3NDUyMGFjY2IzMWMyNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ClQmdVQXMpOW1JuFQS5MHcI6mZCc_8AQQWI4F4StYT8)

Perfect! Thank you very much! 😀

**Comment by ladonnaq** [comment]
[heart]         LaDonna Quinn reacted to your message:
________________________________
