### ISSUE TITLE
Allow user to select current month as SDK release target month (impacting data integrity of engagement experience PowerBI report) 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8320]
**Problem:** Currently a user cannot select the current month for an SDK release target date.  Management plane "request SDK release" cutoff is the 2nd Friday of the month and service partners can request adhoc releases. As far as I know, there is not a strict "cutoff" date for data plane SDK releases.  This is resulting in inaccurate SDK release target dates in the release plans, which impacts the data integrity of the engagement experience PowerBI report.  

**Stakeholder:** The DPG team needs to track the exact month that the SDKs were released. 

Requirement:  Allow user to select the current month as the SDK release target month.  

@maririos - Please take a look and let me know if it is possible to resolve in current release cycle.

**Comment by praveenkuttappan** [comment]
Change will be in

- [ ] Release planner - > Summary
- [ ] Management plane - SDK release request - Prereq
- [ ] Data plane - SDK release request - Prereq

**Comment by ladonnaq** [comment]
> Change will be in
> 
> * [ ]  Release planner - > Summary
> * [ ]  Management plane - SDK release request - Prereq
> * [ ]  Data plane - SDK release request - Prereq
> * [ ]  Create release plan

Thank you!
