### ISSUE TITLE
Management Plane SDK release request - option for user to provide link to the root directory of the API Spec version vs pull request 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8321]
**Scenario:**  The process for the Microsoft.Network RP team for management plane involves all product teams updating their REST APIs for the designated API version and merging their pull requests. Subsequently, a member from one of the Microsoft.Network services requests the release of new SDK versions for Java, JavaScript, Python, and Go. Typically, the individual requesting the SDK releases provides a link to the root directory of the target API version rather than a pull request. Although there is a pull request for the monthly SDK releases, the Network team prefers to supply the link to the root directory of the target API version to ensure the inclusion of all changes for that API version.  Here is an example of a pull request for Network SDK monthly releases.  https://github.com/Azure/azure-rest-api-specs/pull/28527

**Requirement:**  Allow user to provide link to the root directory of the target API version when requesting release of SDKs.   

**Questions:** 

- Is it possible to validate that there are no open PRs against the target API version?  

@maririos @praveenkuttappan - This requirement is related to the work being done to integrate the management plane "Request SDK releases" PowerApp into the release plan (SDK Release Milestone).

**Comment by maririos** [comment]
> Allow user to provide link to the root directory of the target API version when requesting release of SDKs.

How is this different than what we currently have:

![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/7fea5c64-8659-4e28-87f7-c3eab126eea9)

**Comment by ladonnaq** [comment]
> > Allow user to provide link to the root directory of the target API version when requesting release of SDKs.
> 
> How is this different than what we currently have:
> 
> ![image](https://private-user-images.githubusercontent.com/9868623/332907953-7fea5c64-8659-4e28-87f7-c3eab126eea9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MDc1MzgsIm5iZiI6MTcxNjQwNzIzOCwicGF0aCI6Ii85ODY4NjIzLzMzMjkwNzk1My03ZmVhNWM2NC04NjU5LTRlMjgtODdmNy1jM2VhYjEyNmVlYTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMTk0NzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ3NzVlM2JiM2ZjMjljMWRiNDU3ZGRjZWFjYmZmZmE3NDc3NzBiMzJlY2YwOTBhYTY1YjY1MDc4YzFmYWJjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AWHBqzTY714b_dL5Mdeeei863xrfKDkQLP9xdk7zlqs)

That is correct. I just wanted to make sure that the feature would still be available when integrated.  :-)

**Comment by maririos** [comment]
> That is correct. I just wanted to make sure that the feature would still be available when integrated. :-)

Yes. we wont remvoe features when we integrate
