### ISSUE TITLE
Include Azure SDK APEX email alias on management "Request SDK releases" autogenerated emails 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8322]
Previously, Josephine had an SDK release stakeholder alias that included me on the autogenerated emails sent after a service team submits a request to release SDKs.  I believe that the alias is not in use anymore.  Would someone please add the azsdkapex@microsoft.com alias to the autogenerated emails being sent by the "Request SDK release" PowerApp?

**Comment by maririos** [comment]
Added.
