### ISSUE TITLE
[tsp-client] tsp-client cannot run in parallel

### ISSUE THREAD

**Issue by chunyu3** [Azure/azure-sdk-tools#8352]
`tsp-client` will delete `sparse-spec` after copying the spec files to `TempTypeSpecFiles`.  But `sparse-spec` is a common shared temp directory, when we run `tsp-client` in parallel, one `tsp-client` process may delete `sparse-spec` before other `tsp-client` finish copying their spec files. As a result the second `tsp-client` process will fail because of lack of spec files.

Expected: 
`tsp-client` can run in parallel.

Possible solution:
We can create `sparse-spec` directory for each SDK generation separately, not the use the common one

**Comment by catalinaperalta** [comment]
Already have a PR open for this, feel free to add your review to the PR
