### ISSUE TITLE
[tsp-client] `tsp-client init` stuck in Pipeline

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-tools#8368]
## Symptom

Java SDK has our own code generation pipeline to generate SDK from TypeSpec:
https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=2238&nonce=e6ID6FSUknWJb/xkwTih5Q%3D%3D&branch=main

Recently the pipeline stuck at the last output line and timed out after 60 minutes. 
<img width="1000" alt="Screenshot 2024-06-03 at 14 41 57" src="https://github.com/Azure/azure-sdk-tools/assets/92354331/aa596d16-f0ba-4715-a6dd-c197507ca123">
Failed Run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3839396&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=356bb04c-cb4a-5f04-82ca-d3b102917eba

Last successful run was about two weeks ago:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3761145&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=356bb04c-cb4a-5f04-82ca-d3b102917eba

## Reproducing the bug
rerun the pipeline and it'll stuck:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3887788&view=results

## Env

vmImage: ubuntu-20.04
python --version: Python 3.10.14
nodejs: 18.20.3

command: `npx tsp-client init --debug --tsp-config https://github.com/Azure/azure-rest-api-specs/blob/9df71d5a717e4ed5e6728e7e6ba2fead60f62243/specification/informatica/Informatica.DataManagement/tspconfig.yaml`

When run locally on my machine, there's no stuck. 
SDK Automation seems fine too..
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3839388&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=1222

## Expected behavior
We know that this is our own pipeline, though just wondering how the stuck occurred from tsp-client perspective. Would like some insight on the issue. Thanks!

**Comment by weidongxu-microsoft** [comment]
Is it intermittent, or always fail on certain RP?

**Comment by XiaofeiCao** [comment]
> Is it intermittent, or always fail on certain RP?

It always fails for `informatica`. I'll give it a try for other RPs.

**Comment by XiaofeiCao** [comment]
Same for `deviceregistry`..
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3842824&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9

**Comment by XiaofeiCao** [comment]
Seems hanging at compile https://github.com/Azure/azure-sdk-tools/blob/b7c22df944c532ef622fdf523ccb901f39f53d73/tools/tsp-client/src/typespec.ts#L100-L106

**Comment by XiaofeiCao** [comment]
Latest finding:
When there's error in tsp file, the pipeline won't stuck, and throws error successfully:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3888615&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=356bb04c-cb4a-5f04-82ca-d3b102917eba&l=118
<img width="676" alt="Screenshot 2024-06-20 at 16 50 57" src="https://github.com/Azure/azure-sdk-tools/assets/92354331/7d57f95e-7a2b-44b8-bd82-6cf57290c859">

**Comment by XiaofeiCao** [comment]
Latest finding: Use macos-13 succeeded...
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3888966&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ffe5b61a-4918-59e6-2d77-95255068933d

**Comment by weidongxu-microsoft** [comment]
You may change the vm if really need to (but maybe Windows instead of Mac)

**Comment by XiaofeiCao** [comment]
Also stuck on windows bash:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3892604&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=356bb04c-cb4a-5f04-82ca-d3b102917eba

Tried PowerShell, also stuck:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3892700&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=1a5cc010-7735-550a-9d76-c0b745122dab

I don't understand. `tsp-client` is run direclty:
![image](https://github.com/Azure/azure-sdk-tools/assets/92354331/76896880-be1a-468f-b415-2989ece1493e)

**Comment by XiaofeiCao** [comment]
stuck even with sdkautomation command... (tsp-client init --local-repo)
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3893256&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ffe5b61a-4918-59e6-2d77-95255068933d

**Comment by catalinaperalta** [comment]
Does it get stuck with every library or just some? Is there any issues reported when the debug level is set?

**Comment by weidongxu-microsoft** [comment]
> stuck even with sdkautomation command... (tsp-client init --local-repo) https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3893256&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ffe5b61a-4918-59e6-2d77-95255068933d

What's the difference of your experiment branch with the current sdk automation (I assume they are still fine)?

**Comment by XiaofeiCao** [comment]
> Does it get stuck with every library or just some?

For my pipeline, it's every library. 

>  Is there any issues reported when the debug level is set?

No, the last output was:
<img width="814" alt="Screenshot 2024-06-26 at 10 17 48" src="https://github.com/Azure/azure-sdk-tools/assets/92354331/3d0e65ea-70d8-4a1d-8fa6-aec7d28222df">
The command was simple, e.g.: 
`https://github.com/Azure/azure-rest-api-specs/blob/7605afe88e3201dc25ce0881c2e49fe1b6bbdd54/specification/mongocluster/DocumentDB.MongoCluster.Management/tspconfig.yaml`

**Comment by XiaofeiCao** [comment]
> > stuck even with sdkautomation command... (tsp-client init --local-repo) https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3893256&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=ffe5b61a-4918-59e6-2d77-95255068933d
> 
> What's the difference of your experiment branch with the current sdk automation (I assume they are still fine)?

Currently I'm not seeing major differences... We all use node 18.x:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3910442&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=181

One thing I noticed is that sdk automation runs in AzureCLI. Though also tried AzureCLI with same result.
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3910442&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=3
https://github.com/Azure/azure-rest-api-specs-pipeline/blob/master/.azure-pipelines/templates/RunSDKAutomation.yml#L10

**Comment by catalinaperalta** [comment]
So it just hangs at the compile function? Without any errors being returned? Also, I still need to understand, is this always happening in this pipeline? For every library?

**Comment by XiaofeiCao** [comment]
> So it just hangs at the compile function? Without any errors being returned? 

Yes. No error's returned. It just hangs for 60 minutes and timeout.
<img width="459" alt="Screenshot 2024-06-27 at 14 25 55" src="https://github.com/Azure/azure-sdk-tools/assets/92354331/497e4e2f-82f5-483a-8fc5-3b29597ca906">

Like this pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3914963&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=356bb04c-cb4a-5f04-82ca-d3b102917eba

This hanging task is just calling `tsp-client init`:
```yaml
- bash: |
    npx tsp-client init --tsp-config $(TSP_CONFIG) --debug
  displayName: '[Experiment] run tsp-client directly'
  condition: eq(variables.fromTypeSpec, true)
```
https://github.com/Azure/azure-sdk-for-java/compare/main...mgmt_directly_call_tsp-client

> is this always happening in this pipeline? For every library?

Yes. It hangs for every library for this pipeline.

**Comment by catalinaperalta** [comment]
I'm adding @timotheeguerin to see if he has any ideas since we're failing in the typespec compile call. Maybe there's something we can do to further debug the compile step. Tim, here is the link to the compile function: https://github.com/Azure/azure-sdk-tools/blob/d471d1f370dcdc696d995eb2b41dd0ac4ef95fb3/tools/tsp-client/src/typespec.ts#L55

Likewise I tested the init command directly in powershell with the sphere library and had no issues. My node version is 20.11.0 and I'm on a windows 11. The command I ran: `npx tsp-client init --tsp-config https://github.com/Azure/azure-rest-api-specs/blob/7a41d14c661171b4fffec5863c51fb70529ee1db/specification/sphere/Sphere.Management/tspconfig.yaml --debug  `

Since tsp-client is successfully running in the automation pipelines, it seems there's some new configuration in this pipeline that's causing the issue or we might be inputting some unexpected data into the tool. Could be worth a look to see if there's anything in the other pipeline configurations that could help resolve this issue. By the point we get to the compile call in tsp-client we've already finished up with all of the tsp project cloning, installing the emitter deps, etc. So at that point we're just waiting to get the compiled library back from the `@typespec/compiler`

**Comment by catalinaperalta** [comment]
@XiaofeiCao could you also share an example of the tspconfig.yaml url or path you're passing into the command?

**Comment by XiaofeiCao** [comment]
> @XiaofeiCao could you also share an example of the tspconfig.yaml url or path you're passing into the command?

Sure, here it is: https://github.com/Azure/azure-rest-api-specs/blob/7605afe88e3201dc25ce0881c2e49fe1b6bbdd54/specification/mongocluster/DocumentDB.MongoCluster.Management/tspconfig.yaml

You may also try your own url in my pipeline by clicking `Run New` in my [stuck pipeline](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3914963&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=356bb04c-cb4a-5f04-82ca-d3b102917eba) and in `variables`, replace `TSP_CONFIG` with your own. 
![image](https://github.com/Azure/azure-sdk-tools/assets/92354331/3661b6a5-9522-4dab-b4f4-ee810daf7f26)

**Comment by XiaofeiCao** [comment]
@catalinaperalta Another interesting finding is that the pipeline won't stuck in macOS vmImage..

**Comment by catalinaperalta** [comment]
@XiaofeiCao thanks for the link. This seems to be something specific to the environment in the pipeline. Could you also make sure to update to the v0.9.1 version of the tool, I just released it and it improved error logging during the compile step, plus makes sure we exit earlier if there are errors during compile. Let me know if it helps at all

**Comment by XiaofeiCao** [comment]
Thanks @catalinaperalta ! I'll try that out.

**Comment by XiaofeiCao** [comment]
@catalinaperalta No luck... https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3930418&view=logs&j=42d88303-8e48-5332-e7e9-82bec1356e32&t=ce7f9b1c-74d4-53cc-71fb-14221b7018a5

We've made a workaround to use macOS for tsp-client: https://github.com/Azure/azure-sdk-for-java/pull/40781 
It's not a blocker for now. Though I'm still curious about the cause...

**Comment by XiaofeiCao** [comment]
@catalinaperalta 
We encountered similar stuck with non-tsp-client too. Root cause is found, and it's due to Java codegen implementation. See: https://github.com/Azure/autorest.java/issues/2923#issuecomment-2306541926

Thanks for your help! I'll close this issue.
