### ISSUE TITLE
[tsp-client] support specific setting about `service-dir` for specific language emitter in tspconfig.yaml

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-tools#8379]
According to https://github.com/Azure/typespec-azure/blob/161add8c6d5c3d6e74b5dcde4a3b6a4e41cc57a2/docs/howtos/Generating%20with%20tsp-client/tsp_client.md#per-repository-set-up, all language emitters shall share same value of `servide-dir` as part of output folder, which makes sense for new service.
![image](https://github.com/Azure/azure-sdk-tools/assets/70930885/09afba1d-2035-44dc-8b5a-555f41ec2be0)

However, for existing service, SDK across may have different output folder (e.g. avs in python is in [sdk/compute](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/compute) while in java is [sdk/avs](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/avs)). So we hope tsp-client could support specific `service-dir` for different emitter. For example:
```
parameters:
  "service-dir":
    "@azure-tools/typespec-python": "sdk/contosowidgetmanager-python"
    default: "sdk/contosowidgetmanager"
...
```

**Comment by raych1** [comment]
The Go management plane SDK is located under [`/sdk/resourcemanager`](https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/resourcemanager) folder, with the corresponding `service-dir` being `/sdk/resourcemanager/{serviceName}`. This setting is not consistent with other languages. We need the ability to override the `service-dir` at the emitter level. 

@catalinaperalta , I discussed with @weshaggard, and we aligned on adding support for the override capability for `service-dir` in `tsp-client` at the SDK emitter level. This approach allows us to avoid changing the way we call the SDK emitter and the SDK emitters themselves. This feature request is a blocker for MPG. Could you please prioritize this feature request?

//CC: @msyyc @Alancere

**Comment by raych1** [comment]
we might consider override it at SDK emitter config part like the following:
```yaml
"@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/aad"
    package-dir: "armaad"
    flavor: azure
```

**Comment by catalinaperalta** [comment]
Hello, I'm happy to support this new flag in tspconfig.yaml, but need more clarity? Will it be set as part of the global parameters or under the specific emitter configuration parameters? Please let me know

**Comment by catalinaperalta** [comment]
Could you please share a full tspconfig.yaml example of what the convention will be?

**Comment by msyyc** [comment]
Here is example of tspconfig.yaml: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml. And we hope each language emitter has option to override `service-dir` as declared in https://github.com/Azure/azure-sdk-tools/issues/8379#issuecomment-2178543045

**Comment by catalinaperalta** [comment]
Ok so I'll support this based on the override being under the language specific configs:
```
"@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/aad"
    package-dir: "armaad"
    flavor: azure
```

**Comment by catalinaperalta** [comment]
tsp-client v0.9.0 was released and supports providing a service-dir in the emitter config options. Please update to that version to get this functionality.
