### ISSUE TITLE
DevOps YAML to install standalone exe

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#8387]
This is already done by some languages directly in their testing framework. This issue is to create an eng/common YAML like `test-proxy-tool.yml` which uses the standalone exe instead of the .NET SDK dependent tool. 

Discussed in: https://github.com/Azure/azure-sdk-tools/pull/8373

**Comment by weshaggard** [comment]
@scbedd I assume you handled this with https://github.com/Azure/azure-sdk-tools/pull/8549

**Comment by scbedd** [comment]
You're dead on the money Wes. Closing.
