### ISSUE TITLE
[Release Planner] many duplicate inputs in the SDK Readiness app and Request an Official SDK Release app

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#8393]
I found the feature of "create a release request" in the deprecated OpenAPI Hub was poorly integrated into the SDK Readiness App of Release Planner. 

I had though the function would be placed as a shortcut for brownfield service to create a SDK release request with clear targeting release date. The entry is side-by-side with 'Create a release plan'.

![image](https://github.com/Azure/azure-sdk-tools/assets/18413981/1f9c44f3-5af3-400e-803d-adc31a232ac8)

After submission, the backend can still create a release plan and release requests for  all 5 supported languages.

But now it is placed in the SDK Readiness app.

![image](https://github.com/Azure/azure-sdk-tools/assets/18413981/8adc7ed0-f0b6-4be8-8008-5bd58187d1d1)

And with all prerequisite checks before, it still asks user to confirm prerequisites are met...
![image](https://github.com/Azure/azure-sdk-tools/assets/18413981/277263ae-190c-40e5-9b6a-9acbbb3b9eaa)

And the follow-up panel has multiple duplicates with what has already been asked in the SDK Readiness app. And it is very confusing when .NET has been listed in the SDK readiness app, but missing here.  And the target release date is also different between the two apps (the backend logic is different?)

![image](https://github.com/Azure/azure-sdk-tools/assets/18413981/cb7d1eb8-4bc1-464f-bbbd-86456dfef823)

Please help to remove the confusing and duplicate steps.   And I created another issue ask to [improve the route of a release plan for brownfield service](https://github.com/Azure/azure-sdk-tools/issues/8392)

**Comment by ladonnaq** [comment]
Hello @josefree,  As I mentioned during our meeting yesterday, the "Request SDK Release" Power App is an interim solution. We needed to deprecate OpenAPI Hub as soon as possible due to Spring Grove.  Please review this GitHub issue (has link to the new design) - https://github.com/Azure/azure-sdk-tools/issues/8232.  @praveenkuttappan @maririos

**Comment by maririos** [comment]
> And the target release date is also different between the two apps (the backend logic is different?)

The target release date is set by the user when they create a release plan. This can be whenever in the future.
The release date from the Request SDK Release app is based on the release train the management plane team has. When we integrate the apps, we could look into how to integrate the dates.

**Comment by josefree** [comment]
Hope this could be prioritized, the duplicate inputs are confusing.  It is concerned that even a brownfield SDK engineer, like Storage SDK engineer,  needed side-by-side guidance to walk through the request creation.  You may feel free to contact them for further feedback.  Wei Wei & Yifan Zhang, Storage SDK engineers.

**Comment by maririos** [comment]
> Hope this could be prioritized, the duplicate inputs are confusing. It is concerned that even a brownfield SDK engineer, like Storage SDK engineer, needed side-by-side guidance to walk through the request creation. You may feel free to contact them for further feedback. Wei Wei & Yifan Zhang, Storage SDK engineers.

Not sure I undertand the concern. This is the same implementation that OpenAPI Hub had.

**Comment by ladonnaq** [comment]
> Hello @josefree, As I mentioned during our meeting yesterday, the "Request SDK Release" Power App is an interim solution. We needed to deprecate OpenAPI Hub as soon as possible due to Spring Grove. Please review this GitHub issue (has link to the new design) - #8232. @praveenkuttappan @maririos

@josefree Please look at the Figma design and provide feedback.
