### ISSUE TITLE
APIView - diff colors

### ISSUE THREAD

**Issue by kasobol-msft** [Azure/azure-sdk-tools#840]
Can we make colors on the APIView diffs more contrasting (or configurable)? It takes a lot of effort on some monitors and with certain degree of colorblindness to notice all changes ... 

@kurtzeborn FYI

**Comment by JonathanGiles** [comment]
It would be pretty cool to have a well defined set of css selectors that allow for custom themes, alongside a drop down selector and this persisting per user. I know a few months back I hacked a 'darcula' theme that looked nice to me, but it bitrotted as the codebase moved on. As part of this we could of course define diff color selectors.

**Comment by xirzec** [comment]
Another pretty low-effort option here is to prefix affected lines with symbols (e.g. +, -) to show what was added/removed even if a user is fully colorblind. VS Code does this for diff views.

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/2785
