### ISSUE TITLE
Update release planner with new TypeSpec info blurb

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8408]
We need to make sure that both API readiness app have the same consistent info blurb. it should cover greenfields and brownfields.
The message should be the same as the one our CI tooling is using. https://github.com/Azure/azure-sdk-tools/issues/8406

**Comment by MrJustinB** [comment]
Here is the verbiage we will use:  "TypeSpec usage for API definition has been a requirement for all new (greenfield) data plane and management plane services. This is now a mandatory requirement and will be enforced by the API Stewardship Board for data plane services and ARM API Review Board for management plane services. Starting by the end of July 2024, the tooling warning on API Spec builds not complying with the TypeSpec requirement will be changed from a warning to a blocking error for new data plane and management plane service API spec Pull Requests."

**Comment by maririos** [comment]
Data plane app:

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/9fedfa35-f929-4639-8489-503e6ee8f153)

Management plane app:

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/3c0c91ab-a8bb-44e4-865f-e97e7865ea40)
