### ISSUE TITLE
[SDK Automation] Support generated SDK artifacts downloading in spec PR pipeline

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8418]
**Context**
Based on the spring grove requirement, we disabled the SDK artifact downloading feature in the spec PR pipeline because it uses SAS token to download the artifacts from Azure blob.

There are still several service teams reached out us to download the generated SDK packages. They will need the SDK for Azure CLI development purpose.

**Proposal**
We will publish the generated SDK packages to the Azure DevOps pipeline run, and the user can browse to the corresponding pipeline run to download the SDK. In order to download the SDK, the user will need the Azure-Sdk ADO permission.

**Comment by maririos** [comment]
> This task is completed. Refer to the document [aka.ms/azsdk/sdk-automation-faq](https://aka.ms/azsdk/sdk-automation-faq)

would it be worth to move this documentation to the wiki of the repo for people to find it more easily? https://github.com/Azure/azure-rest-api-specs/wiki/About-the-Wiki

it might be good too, to add why people will want to download the artifact and what to do with it
