### ISSUE TITLE
Change email for .NET management plane release

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8449]
The current guidance on the Management SDK release app says that to request a release of .NET, the user needs to email `azdevxdotnet@microsoft.com` but that email is no longer valid. Instead use `sdkowners`. 

This is a hot fix while we implement: https://github.com/Azure/azure-sdk-tools/issues/5936

**Comment by maririos** [comment]
FYI @ladonnaq @josefree

**Comment by ladonnaq** [comment]
[heart]         LaDonna Quinn reacted to your message:
________________________________
