### ISSUE TITLE
Update the Data Plane API Readiness with messaging to help enforce TypeSpec for all Greenfield Services 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8453]
Justin was looped into discussion on providing better support for enforcing TypeSpec for all new data plane APIs (Greenfield Services). 
When the support for OpenAPI was added for data plane release plans, a message reminding service teams that all new data plane APIs are required to be defined using TypeSpec was not added.  

- [ ] Update Using TypeSpec tab of the Design and define service APIs step of the API readiness milestone with messaging to remind user that TypeSpec is required for all new data plane APIs.  Screenshot below.  Please adjust the spacing

<img width="524" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/67656762/0446fa13-7cfd-49ff-9dcf-da31dd2a5d99">

**Comment by maririos** [comment]
Dup of https://github.com/Azure/azure-sdk-tools/issues/8408
