### ISSUE TITLE
Validate Impacted Specs - `tsp compile` step regenerates deleted directory & directory contents in pipeline

### ISSUE THREAD

**Issue by russellbuck** [Azure/azure-sdk-tools#8458]
As stated above, the `tsp compile` step in the Validate Impacted Specs job causes TypeSpec Validation to fail.  The folder in question is a deleted "stable/0000-00-00" directory structure which was renamed to "preview/2024-06-01-preview".  Somehow tsp compile manages to regenerate the "stable/0000-00-00" directory which then causes the "files have been changed after tsp compile" error.  This behavior occurs both locally and in the build pipeline, despite there being no reference to the directory.

Link to PR:
https://github.com/Azure/azure-rest-api-specs-pr/pull/18602/files

![image](https://github.com/Azure/azure-sdk-tools/assets/130503251/bc634cee-92f7-4d23-9f28-937308c57984)

![image](https://github.com/Azure/azure-sdk-tools/assets/130503251/34ab79df-6982-495e-9bc4-32e8713a849d)

```Running git diff on folder /mnt/vss/_work/1/s/specification/physicalnetwork
Rule Compile failed
{"not_added":["specification/physicalnetwork/resource-manager/Microsoft.PhysicalNetwork/stable/0000-00-00/examples/Operations_List.json","specification/physicalnetwork/resource-manager/Microsoft.PhysicalNetwork/stable/0000-00-00/microsoftphysicalnetwork.json"],"conflicted":[],"created":[],"deleted":[],"modified":[],"renamed":[],"files":[{"path":"specification/physicalnetwork/resource-manager/Microsoft.PhysicalNetwork/stable/0000-00-00/examples/Operations_List.json","index":"?","working_dir":"?"},{"path":"specification/physicalnetwork/resource-manager/Microsoft.PhysicalNetwork/stable/0000-00-00/microsoftphysicalnetwork.json","index":"?","working_dir":"?"}],"staged":[],"ahead":0,"behind":0,"current":"HEAD","tracking":null,"detached":true}
Files have been changed after `tsp compile`. Run `tsp compile` and ensure all files are included in your change.
```

**Comment by kurtzeborn** [comment]
If this is happening as part of TypeSpec validation, then this should go to you.  If this is the TypeSpec tool itself, this needs to be transferred to the TypeSpec repo.  @weshaggard  is suspicious that this is just a local configuration problem though.

**Comment by russellbuck** [comment]
Error was due to an unversioned typespec model, linter didn't catch it.  Closing issue
