### ISSUE TITLE
Add a pull request field and making it mandatory for .NET management plane

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8469]
User's shouldn't be able to request a release if there is no .NET pull request created for the code.
If this happens, they can request a release of the .NET SDK too: https://github.com/Azure/azure-sdk-tools/issues/5936

**Comment by maririos** [comment]
Added a new tab to link the pull request: 

![Image](https://github.com/Azure/azure-sdk-tools/assets/9868623/d711595c-2430-4a86-ac67-f4f8362eef20)

- The link is validating that the PR belongs to the .NET repo. 
- It won't let the user click `Next` if the field is not valid
- User won't be able to move to release SDKs unless the .NET PR has been added

**Comment by maririos** [comment]
FYI @ladonnaq and @lirenhe

**Comment by ladonnaq** [comment]
[heart]         LaDonna Quinn reacted to your message:
________________________________

**Comment by ladonnaq** [comment]
Thank you @maririos! This will ensure .NET is released at same time as other languages.
