### ISSUE TITLE
[SDK Automation - Java] Support breaking change detection for DPG & MPG

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-tools#8477]
Offline synced with Ray, we need:
1. List breaking changes in `Breaking Changes` section in changelog.md
2. List breaking changes in output, format: https://github.com/Azure/azure-rest-api-specs/blob/cc92c5922e1d69bab8f0deb8e1f778f6d9455739/documentation/sdkautomation/GenerateOutputSchema.json#L49
![image](https://github.com/Azure/azure-sdk-tools/assets/92354331/b0aa7d7d-55db-42f6-80cf-1818210ec8fe)

/cc @raych1 @weidongxu-microsoft

**Comment by XiaofeiCao** [comment]
> 1. breaking changes should always compare with a previous GA SDK
> 2. there could be issue about version (in current SDK automation, we don't set a version to package)

Thanks, there could be a case where previously we released beta SDK for GA service, or never released at all. This case, we are not able to generate breaking changes since we can't find the SDK to compare with.

**Comment by raych1** [comment]
> > 1. breaking changes should always compare with a previous GA SDK
> > 2. there could be issue about version (in current SDK automation, we don't set a version to package)
> 
> Thanks, there could be a case where previously we released beta SDK for GA service, or never released at all. This case, we are not able to generate breaking changes since we can't find the SDK to compare with. @raych1

@XiaofeiCao , it's ok to return false if a SDK hasn't have any GA version released.

**Comment by raych1** [comment]
> 2. there could be issue about version (in current SDK automation, we don't set a version to package)

SDK automation doesn't need to know the package version. It's up to the language tool to pick up the base version and do comparison then report the breaking change.
