### ISSUE TITLE
[JS] Need update the changelog template

### ISSUE THREAD

**Issue by kazrael2119** [Azure/azure-sdk-tools#8487]
need update the template from 
```
## 5.0.0 (2024-06-28)
    
**Features**

  - XXX

**Breaking Changes**
  - XXX
```
to
```
## 5.0.0 (2024-06-28)
    
### Features Added

  - XXX

### Breaking Changes
  - XXX
```

and make sure replace all the \*\*XXX\*\* to ### XXX from the old changelog

**Comment by wanlwanl** [comment]
#8489

**Comment by wanlwanl** [comment]
Fixes:
https://github.com/Azure/azure-sdk-tools/pull/8489
https://github.com/Azure/azure-sdk-tools/pull/8490
https://github.com/Azure/azure-sdk-tools/pull/8498

**Comment by wanlwanl** [comment]
Fixes:
https://github.com/Azure/azure-sdk-tools/pull/8489
https://github.com/Azure/azure-sdk-tools/pull/8490
https://github.com/Azure/azure-sdk-tools/pull/8498

The fixes are simply convert `**Features**` to `###Features Added`, and I found [SDK Automation Protocol](https://microsoft.sharepoint.com/teams/AzureDeveloperExperience/_layouts/OneNote.aspx?id=%2Fteams%2FAzureDeveloperExperience%2FShared%20Documents%2FShanghai%20Team%2FAzure%20SDK%20-%20Shanghai&wd=target%28Swagger%20team%2FAzure%20SDK%20Automation.one%7C54BF589A-97CD-4236-9709-0E1B16FAB371%2FSDK%20Automation%20Protocol%7C6CB34287-31DA-4545-A9BA-B997B6193AC1%2F%29)
has a property `"breaking_change_keyword": "** Breaking Change **"`, while azure-sdk-for-js doesn't set it [here](https://github.com/Azure/azure-sdk-for-js/blob/main/swagger_to_sdk_config.json).

I'm afraid it could breaking automation workflow.  
@raych1 Will the fixes break the current SDK automation from azure-rest-api-specs?
