### ISSUE TITLE
[Breaking Change] Swagger Breaking change detected errors but did not set a review required label

### ISSUE THREAD

**Issue by mikekistler** [Azure/azure-sdk-tools#8499]
In PR https://github.com/Azure/azure-rest-api-specs-pr/pull/18515, the Swagger Breaking Change check detected errors:

<img width="834" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/85643503/d1543f66-e5a8-4bb5-9778-6ea555906ca0">

But did not flag the PR as VersioningReviewRequired. The Automated Merging Requirements also makes no mention of breaking change review.

<img width="614" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/85643503/d9b28ac9-1127-492b-a7e9-624b7be6584d">

**Comment by konrad-jamrozik** [comment]
@mikekistler I see [in log](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3903929&view=logs&j=d6a48a56-e996-55ca-2302-c3a9a7be685b&t=f4162ac4-a5be-580e-39db-db0d6209bd6a&l=121):

> processBreakingChangeLabels: PR: https://github.com/Azure/azure-rest-api-specs-pr/pull/18515, targetBranch: main. The addition of 'BreakingChangesReviewRequired' or 'VersioningReviewRequired' labels has been prevented because we checked that the PR is not targeting a production branch.

Per https://aka.ms/azsdk/pr-brch-deep#breaking-changes-and-versioning-issues:

> The result of running these checks may result in one of these labels being applied: BreakingChangeReviewRequired or VersioningReviewRequired. If this happens, your PR is blocked from any further review, including ARM review, if applicable.

>
> The breaking change/versioning checks are performed only on PRs targeting the main branch in the [public specs repo](https://github.com/Azure/azure-rest-api-specs) or RPSaaSMaster branch of the [private specs repo](https://github.com/Azure/azure-rest-api-specs-pr).

**Comment by mikekistler** [comment]
That explains it! Thanks @konrad-jamrozik !
