### ISSUE TITLE
Add release planner information into the scheduler wikis

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8518]
API stewardship meeting and SDK archboard wikis talk about scheduling the meeting directly from the Scheduler app: https://eng.ms/docs/products/azure-developer-experience/design/api-review#schedule-a-meeting

But we could change it to direct people to the Release Planner so they schedule the meetings from there.
For people that don't have release planner, we still need to provide that information.

@ladonnaq  what do you think?

**Comment by ladonnaq** [comment]
@maririos Great idea! I think we should update the guidance to direct the reader to use the "review" feature in their release plans or schedule the review at the step in their release plan .  We still lack visibility to how many service partners are not supported thru the service partner model. This would provide a way to identify the number of service partners and identify additional scenarios we need to support.

**Comment by maririos** [comment]
It was @catalinaperalta idea :) 
I guess we can always revert the change back and add the direct link to the scheduler if "hidding" it becomes too noise or complicated

**Comment by maririos** [comment]
PR: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/1019
