### ISSUE TITLE
Changelog Tool Bumps Stable Version for Preview API with Latest Modular CodeGen

### ISSUE THREAD

**Issue by kazrael2119** [Azure/azure-sdk-tools#8522]
this pr is generated with modular
https://github.com/Azure/azure-sdk-for-js/pull/30102
and the generated version is 1.0.0-beta.1
but after usiing changelog tool, it becomes 1.0.0

**Comment by wanlwanl** [comment]
Looks like the tool is out of date, releasing new tool https://dev.azure.com/azure-sdk/internal/_releaseProgress?releaseId=24877&_a=release-pipeline-progress

**Comment by wanlwanl** [comment]
PR to fix: https://github.com/Azure/azure-sdk-tools/pull/8671
