### ISSUE TITLE
[tsp-client] The output of the `tsp compile` command should be logged using the Logger

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8523]
**Description**
The output while calling the SDK emitter in `tsp-client` is currently only displayed in the console. For better troubleshooting, this output should also be emitted to the Logger so that it can be displayed in the pipeline scenario.

This is the code location:
https://github.com/Azure/azure-sdk-tools/blob/eaa42a758c1478fa7a3262a53254d3fe26d8ea37/tools/tsp-client/src/typespec.ts#L112

//CC: @catalinaperalta @chunyu3

**Comment by chunyu3** [comment]
Hello @catalinaperalta in .NET generator we will log some information, but when `tsp-client` execute .Net emitter, the logs of .NET emitter are missing.

When I run local, it can see the logs, but when run in ci pipeline, the logs are missing

**Comment by catalinaperalta** [comment]
Hi all, I opened a PR addressing this yesterday, you should be able to see it linked to this issue. Waiting on a review then will release a tsp-client update. Feel free to add your own review on the PR as well :)

**Comment by catalinaperalta** [comment]
v0.9.1 of tsp-client was released and is not printing the diagnostics with the logger. Please update to that version and give it a try. Thanks

**Comment by catalinaperalta** [comment]
@raych1 the output of the diagnostics causes a lot of noise when generating using tsp-client. Any issues if I move this to the debug level? I think you're already using the `--debug` flag in the pipeline, right?
