### ISSUE TITLE
Calendar get api only brings 50 events, so some meetings are not surfacing

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8576]
This is causing issues where a user tries to update a meeting that was created a while back and the updates don't take place because the meeting information is not returned from the `Get events from calendar` API that PowerApps provides.

We should look into a way to filter so we can get the information we need.

the meeting that is blocked by this is https://github.com/Azure/azure-sdk-pr/issues/1695 because they need to update the meeting and the flow is failing because it can retrieve the outlook event

**Comment by maririos** [comment]
I tried filtering by the `webLink` but the API doesn't support it. 
Other possible way to filter results is by filtering by the `subject` name, which we have in the apps. The downside is that we might need to modify the parameters of the flow so we pass the subject. This will cause a change in all 3 apps.

The flow will be like:
![image](https://github.com/user-attachments/assets/574ed8f9-4bf0-4a8e-906d-a37a7dbf4002)

where we woould need to do `replace(triggerBody()['text'],'&','%26')` because `&` is a special reserve character that it is used in the subject, like for example `Azure SDK - Azure.Core & Event Grid System Events`

**Comment by praveenkuttappan** [comment]
I have used start and end time to filter the meetings. Here is a good reference about ODATA filter for outlook events.
https://rakhesh.com/power-platform/get-events-v4-vs-get-calendar-view-of-events-v3/
