### ISSUE TITLE
Customer Blocked: Error when linking API Spec PR 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8595]
**Scenario:**  User attempted to link API Spec PR in API readiness milestone and received error message. See screenshots.  

**Service Partner contact:** @emmeliaAra 

<img width="302" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/67656762/9c32fdc2-279b-4c56-989e-74ca3929fef4">
![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/cf1e3ca3-9463-4754-9039-0071a4811e8f)

**Recreation and experimentation:** 

1. Recreated and experimented in PROD and PPE. 
2. Onboarded product again and updated the API Spec PR link.  
3. Validated that the triage work item contained the new API Spec PR link. 
4. Refreshed ADO and Release Planner App, accessed release plan and API readiness milestone. 
5. The updated API Spec PR link is not pre-loaded into the "Associated pull request" step.  See screenshot. 
<img width="1244" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/67656762/e1acb173-5024-4359-aa11-ec7fffc36797">
6. Tried again using a different API Spec PR and received same error message.

**Comment by maririos** [comment]
Thanks for the report. There was a change in credentials and we had to update them. I tested it by adding the PR to this release plan. See:
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/010565b9-506b-4399-8e4e-e59523e5f8ae)
