### ISSUE TITLE
Customer blocked: Product mapped in service tree but now showing up in Release Planner 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8599]
Service partner cannot find product in onboard drop-down associated with the service "Azure IOT Operations".   However, the product is mapped to other services and it is showing up in the drop-down boxes when the service context is changed.  
Service partner contact: @Adaeze934 

Link to Service Tree for the Product - https://microsoftservicetree.com/services/f67d3cd4-186d-4d8e-9637-72d40f6695c3

Not sure if this is important but we noticed that the Service Type = Manual Process Service.   The service will have ARM REST APIs/SDKs.  The ARM RP namespace metadata is in the service tree entry for the Azure IOT Operations service.  

![image](https://github.com/Azure/azure-sdk-tools/assets/67656762/a1334f58-6532-4769-94c2-117285b25c86)

**Comment by maririos** [comment]
These are the services that have that product:
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/1a510545-cd5e-4906-8388-2096925cffb5)

Which maps with Service tree:
![image](https://github.com/Azure/azure-sdk-tools/assets/9868623/2f816273-b9ad-46fd-9ac8-c626f1ec7427)

> Service Type = Manual Process Service

I do wonder if that is the case, as it is odd that it is the only service that is not linked

**Comment by ladonnaq** [comment]
> These are the services that have that product: ![image](https://private-user-images.githubusercontent.com/9868623/347594909-1a510545-cd5e-4906-8388-2096925cffb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDUyNjksIm5iZiI6MTcyMDY0NDk2OSwicGF0aCI6Ii85ODY4NjIzLzM0NzU5NDkwOS0xYTUxMDU0NS1jZDVlLTQ5MDYtODM4OC0yMDk2OTI1Y2ZmYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMjA1NjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzViMTljYmUzZWUxODFmNmZlNzI3NWUwMmZjZmFjZDRiMzZiMTNhMmY1OTYyMzEwMTg0NzJhYjY2M2FlZGQ2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GQoiszldiPBVuLWXs3XTQ4FPT3p1TnmLol3rqF8pX-k)
> 
> Which maps with Service tree: ![image](https://private-user-images.githubusercontent.com/9868623/347594999-2f816273-b9ad-46fd-9ac8-c626f1ec7427.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NDUyNjksIm5iZiI6MTcyMDY0NDk2OSwicGF0aCI6Ii85ODY4NjIzLzM0NzU5NDk5OS0yZjgxNjI3My1iOWFkLTQ2ZmQtOWFjOC1jNjI2ZjFlYzc0MjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTBUMjA1NjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGM1ODEzYzgxZmIwMDI4NzE0OWMzZjIzNWRjY2JiMzQ5ZDA4NGVmNmJiNDYyNmVkZjg0ZWU0YmU5YWZiMWQyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZVfrIgVEIdBjXQwP9K4NQaYWhlEwvuCUY3_u0MFi-1M)
> 
> > Service Type = Manual Process Service
> 
> I do wonder if that is the case, as it is odd that it is the only service that is not linked

@maririos  - Can check to see if the code that is ingesting the data from service tree is filtering to exclude services based on the "Service Type"?  Here is screenshot the metadata in service tree.  

<img width="430" alt="image" src="https://github.com/Azure/azure-sdk-tools/assets/67656762/fe9de33b-5e2d-4a40-aa4b-1d961ad8708f">

**Comment by praveenkuttappan** [comment]
There is no filter at Service Type. I can see Azure IoT operations in product dropdown.

**Comment by ladonnaq** [comment]
Issue resolved.  Service partner was able to onboard their product.
