### ISSUE TITLE
Remove obsolete `Swagger Generation Artifacts` comment

### ISSUE THREAD

**Issue by konrad-jamrozik** [Azure/azure-sdk-tools#8612]
These comments ([example](https://github.com/Azure/azure-rest-api-specs/pull/29861#issuecomment-2233681916)):

![image](https://github.com/user-attachments/assets/b4907206-db9d-462e-b8c1-feef69f2159b)

Reasons:

- these reports provide no new info, they are all available in checks tab
- they distract people from next steps to merge comment causing unnecessary support burden (I need to remind people to read that comment)
- they cause us to hit GitHub API rate limits, due to my recent change of: https://github.com/Azure/azure-sdk-tools/issues/8585

@raych1 @weshaggard FYI

**Comment by raych1** [comment]
One impact is that the history pipeline run link is missing if removing the PR comment, leaving users without a way to access it.
![image](https://github.com/user-attachments/assets/6037e593-0669-4b33-9a01-a551c1be9458)

In addition, users will need to be guided to browse to `Checks` tab to view the check result.

+@lirenhe @ArthurMa1978 @weidongxu-microsoft to comment on the concerns.

**Comment by konrad-jamrozik** [comment]
@raych1 we are moving towards the model of guiding users to the `checks` tab. The checks tab do have history in them. Hence both concerns should be alleviated by this.

**Comment by raych1** [comment]
@konrad-jamrozik 
can you share me where I can view the history run of the CI checks? I remember it needs to query the pipeline run by the PR# on the page of https://dev.azure.com/azure-sdk/internal/_build?definitionId=1736&_a=summary.

**Comment by konrad-jamrozik** [comment]
@raych1 yeah, so few options:

1. Query the ADO pipeline runs, as you mentioned:
- https://dev.azure.com/azure-sdk/internal/_build?definitionId=1736&_a=summary

2. Use the GitHub UI for check
- https://github.com/Azure/azure-rest-api-specs/pull/29873/checks?check_run_id=27589947039
![image](https://github.com/user-attachments/assets/e107e25e-f38b-4275-a61f-e700f844c833)

Note that if you open view of a previous checkRun, the `[View Azure DevOps build log for more details.](https://dev.azure.com/azure-sdk//internal/_build/results?buildId=3971516&view=logs&j=b7f68bce-9df8-5468-1c9f-74766cfc9a39)` link will point to corresponding, previous, ADO run

3. Query our Kusto cluster for the logs
See [this function](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/1147/SpecsPipelinesBuildsJobLogs.kql) I wrote.

**Comment by konrad-jamrozik** [comment]
[Pull Request 565678](https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/565678): Remove "Swagger Generation Artifacts" comment

**Comment by raych1** [comment]
> ### 1. Query the ADO pipeline runs, as you mentioned
> * https://dev.azure.com/azure-sdk/internal/_build?definitionId=1736&_a=summary
 
> ### 2. Use the GitHub UI for check
 
> ### 3. Query our Kusto cluster for the logs

The second approach only associates with the latest run for a specific commit. For multiple pipeline runs for a given commit, it relies on the first approach. Therefore, while it technically allows for history queries, it requires additional effort.

**Comment by konrad-jamrozik** [comment]
@raych1 yes, it is in line with our approach of the 20/80 approach - 20% effort (i.e. using just the `checks` tab instead of coding entire new comment) to get the 80% result (i.e. the few extra steps people have to take by going the `checks` tab).
