### ISSUE TITLE
[new feature] To ensure typespec folder structure conform to guidelines

### ISSUE THREAD

**Issue by josefree** [Azure/azure-sdk-tools#8616]
TypeSpec folder structure should conform to guidelines for [TypeSpec project repositories](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/typespec-structure-guidelines.md) and [specification directory structure](https://github.com/Azure/azure-rest-api-specs/blob/main/documentation/directory-structure.md). Or there is a risk that we must customize SDK release pipeline to accommodate the inconsistency. It could also add complexity in breaking change detection. Currently, the common problems we encountered were as below

- No `Management` suffix at the end of the service RP-name so that indicates a management (resource manager) library. An example of this is https://github.com/Azure/azure-rest-api-specs/pull/29740, and https://github.com/Azure/azure-rest-api-specs/pull/29748

The feature (or at least necessary suffix as prioritized) should be enabled in the spec PR pipeline prior to the program of [TypeSpec Brownfields Conversion](https://microsoft-my.sharepoint.com/:w:/r/personal/mattge_microsoft_com1/_layouts/15/Doc.aspx?sourcedoc=%7B57BAE71D-CCE9-446C-AD6D-B0A314B628C1%7D&file=TypeSpec%20Brownfields%20Conversion%20Specification.docx&action=default&mobileredirect=true&share=IQEd57pX6cxsRK1tsKMUtijBAUWaqqhv4lqD384_DZ1knC4) in execution.

**Comment by raych1** [comment]
The folder structure validation is covered by `TypeSpec validation` tool and the suffix validation has been added recently. Refer to this issue for details. https://github.com/Azure/azure-rest-api-specs/issues/29654
