### ISSUE TITLE
Add Type Prefix to Issue Labels

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-tools#8627]
Add prefixes to issues labels related to their type. 

### Examples:
1. `issue-addressed` -> `workflow: issue-addressed`
2. `Mgmt` -> `Plane: Mgmt`
3. `Service Bus` -> `Service: Service Bus`

### Concerns: 
1. Proper Syntax:
   - Should the type be added to the label as a prefix or suffix? 
   - How should the type be separated from the actual label text? Dash or colon? 
   - Some existing labels are all lower case with dashes and some have the first letter capitalized with spaces. Should the types have a unified styling or should they match the style of the labels in their type. 
   
 2. Updating the existing labels:
    - We currently don't have an automated way for us to update labels. We can push new labels out, but they won't overwrite the old labels. 
    - We cannot remove the old labels then add the new labels. We need to update the labels, so the issue tagged with the old labels get the updated version.

3. Updating GitHub Action rules:
    - All GitHub Action rules need to be updated to use the new issue labels.

**Comment by kurtzeborn** [comment]
Assigning this to @JimSuplizio since he'll do this work, but it's important that @jsquire provide input and @ronniegeraghty should probably run this change past all the language leads as well.

**Comment by jsquire** [comment]
Well, this opens up the question:  If we're going to go through all of this, can we PLEASE stop doing a 2-label system?   The whole pink+yellow classification is difficult to work with and causes issues.   I think everyone (especially @joshfree ) would love to see us adopt a consistent format with a single label.
 
For example, something like:

- `area-service-bus`
- `area-service-bus-mgmt`

would be better than

- `service: Service Bus`  +  `plane: Data`
- `service: Service Bus` +  `plane: Mgmt`

**Comment by jsquire** [comment]
Also, @ronniegeraghty - be aware that this overhaul will invalidate all the ML models for the AI service.   If we just rename in place, I can retrain and we won't lose confidence.   If we make the more wholistic change that I'm advocating for, we'll end up needing to do some scripting to fix up the old issues so that we can retrain.

**Comment by ronniegeraghty** [comment]
Attempting to bridge the problem by adding a prefix to the label description so people can search the description prefix.

**Comment by JimSuplizio** [comment]
I've assigned this to both @ronniegeraghty and myself because, if this ends up getting done, the work won't be just on my plate.

**Comment by ronniegeraghty** [comment]
We've currently fixed the issue at hand by adding a Prefix to labels' description. This allows someone to search the labels for the prefix in the description and get a list of all the labels used in the Resolution process.
