### ISSUE TITLE
Improve API details section of the Release Plan Summary 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8632]
**Requirement:**  Modify the API details section of the "Release Plan Summary" to improve data quality. 

- [x] Change name of "release details" to "SDK details". 
- [x] API details - Change the "Target lifecycle" field to "API Spec type" and field value should be beta or stable.  

<img width="821" alt="image" src="https://github.com/user-attachments/assets/7a2d4f28-39b3-4f96-ad57-362ed98b3020">

**Comment by maririos** [comment]
>  API details - Add new field named "API target release date" with value as month (similar to SDK).

We currenlty don't get this information for data plane.
For management plane, we can add it once the user request the release but that work will need to wait until #8232 is complet

**Comment by maririos** [comment]
For the information we have, here are the changes I made:

![Image](https://github.com/user-attachments/assets/13816548-17bf-4fb2-9c9a-813b52e05d71)

@ladonnaq instead of using `API spec type` I used `API lifecycle` since that is the one we use accross the apps. API spec type refers more to typespec of swagger

**Comment by maririos** [comment]
For the remaining of the work I have moved:
- API details - Add new field named "API target release date" with value as month (similar to SDK). issue https://github.com/Azure/azure-sdk-tools/issues/8759
- API details - Add new field named "API version" with the value of the API version as indicated by the user. Added as part of the work on issue  #8631.
