### ISSUE TITLE
Verify-Links.ps1 should flag invalid aka.ms links

### ISSUE THREAD

**Issue by billwert** [Azure/azure-sdk-tools#8637]
Today, if an aka.ms link is missing or pointed to the wrong place, it redirects to Bing with a 302. In the case it is pointing somewhere valid, it redirects with a 301.

We can enhance the script to know about this to find invalid aka.ms links. I did so manually with something like this:

```pwsh
# imagine $links is populated with everything we found to check.
$links | % { iwr -MaximumRedirection 0 -SkipHttpErrorCheck -pv result -ErrorAction SilentlyContinue } | ? { $result.StatusCode -eq 302 -and $result.Headers.Location -match "https://www.bing.com/"  } |  % { ... add to broken links }
```

Once we've validated we get a 301 we should then follow the link without a redirect to ensure it is valid. aka.ms will redirect with a 301 to an invalid page (ie, one that returns a 404 etc.)

This is related to #6196.

**Comment by joshfree** [comment]
For an unknown reason, a handful of the Java SDK repo aka.ms links embedded in README.md and TROUBLESHOOT.md files were deleted, and only noticed by @billwert through ad hoc review (and then full repo scripted testing).

Having this safety check added to Verify-Links.ps1 would have caught this much sooner.  It would be good to push this improvement for all SDK language repos.
