### ISSUE TITLE
[Go-SDK-Automation] Error should be reported when the readme.go.md has incorrect format

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8658]
**Description**
When the readme.go.md has incorrect format, the automation doesn't report any issue and finishes without any code generated.

**Expected**
The tool should report the error in the readme.go.md and mention that the error blocks the SDK generation.

**Sample file**
https://github.com/Azure/azure-rest-api-specs-pr/pull/8191/files#diff-82faea9bc06869bf1e50aeac41520f37a592dd279717dd2dcce99c4eadfb0843

**Screenshot**
Additional 'go' is added in the readme.go.md:
![image](https://github.com/user-attachments/assets/3bffe1c4-a95b-44e8-b4ab-64f954870710)

The logs of the automation tool:
![image](https://github.com/user-attachments/assets/a9518e9d-7b12-4180-a938-ac710b11ceea)

**Comment by Alancere** [comment]
resolve in: https://github.com/Azure/azure-sdk-for-go/pull/23073/commits/b904ff1b961522aa9e13c1e66dc55b5a32fc0303
