### ISSUE TITLE
APIView SPA - Bug Fix for First release button

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-tools#8695]
- [x] Ensure First Release approval is not disabled when not approved

**Comment by chidozieononiwu** [comment]
https://github.com/Azure/azure-sdk-tools/pull/8700

**Comment by maririos** [comment]
Merged but not yet deployed to PROD

**Comment by maririos** [comment]
Reopening as this is not working when the users uses a URL directly instead of following the UI flow

**Comment by chidozieononiwu** [comment]
> Reopening as this is not working when the users uses a URL directly instead of following the UI flow

Actually, this one is fine. should be closed. The one with the issue you mentioned is https://github.com/Azure/azure-sdk-tools/issues/8693
