### ISSUE TITLE
APIView - Invalid diff when only attribute of the APIview is different

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#8703]
New parser considers API attribute as part of the API node and this leads to marking entire API line as modified even if only attribute is changed.  for e.g. 
An addition of attribute shows as a breaking change. Can this be improved? Here is an example: [APIView](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fspa.apiview.dev%2Freview%2Fda95782e37db4ce286d1e9bebf1cec36%3FactiveApiRevisionId%3D0bd04140e9814876b6337030a910fdcc%26diffApiRevisionId%3D83618c6222ad413b833f5e5068c61e79%26nId%3DMicrosoft.Extensions.Azure.ConversationAnalysisClientExtensions&data=05%7C02%7CPraveen.Marottickal%40microsoft.com%7C5b2fd52cf4064714e4c408dcacbc717d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638575172573696985%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=qHZRFCRZGfyv4f0DJ%2Bw7Qc87GjvqSIruvl95jn1tJFo%3D&reserved=0)

**Comment by maririos** [comment]
This change is for the .NET parser
