### ISSUE TITLE
APIView - Hide skipped diff in UI

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#8704]
APIView supports skipping some of the review areas when comparing the revisions. But this diff is still visible on UI even though it's ignored when comparing two revisions for matching API surface. Architects has suggested not to show the skipped diff sections as modified by default. Instead, it should be visible as modified only if an option `Show ignored diff` is selected.

**Comment by maririos** [comment]
@praveenkuttappan was this done?

**Comment by maririos** [comment]
Yes
