### ISSUE TITLE
JS Breaking Change Tool Failed to Detect Union Enum Breaking Change for Some Case

### ISSUE THREAD

**Issue by wanlwanl** [Azure/azure-sdk-tools#8707]
Failed to detect breaking change: `export type ProvisioningState = "succeeded" | "provisioning" | "failed` -> `export type ProvisioningState = "Succeeded" | "Provisioning" | "Failed"`

Issue: https://github.com/Azure/azure-sdk-for-js/pull/30014#discussion_r1690855320

**Comment by wanlwanl** [comment]
Pull request: https://github.com/Azure/azure-sdk-tools/pull/8708

**Comment by raych1** [comment]
@wanlwanl can you close this issue if it has been fixed?
