### ISSUE TITLE
Install fewer moduled in deploy-test-resources.yml

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#871]
Currently, we install all Az modules and it takes 1.5 minutes to do.

I suspect we only need a few like Az.Accounts and Az.Resources for our scripts.

cc @heaths @danieljurek

**Comment by danieljurek** [comment]
I'm aware of at least one example where a `-post` script uses `Az.Storage`: https://github.com/Azure/azure-sdk-for-js/blob/master/sdk/storage/test-resources-post.ps1#L38

If we install Az.Accounts and Az.Resources by default then we should have a place in tests.yml for services to specify additional modules to install.

**Comment by pakrym** [comment]
Can scripts install modules themselves?

**Comment by heaths** [comment]
Yes, scripts themselves can install and invoke modules themselves. I've used this approach in the past for some end user scripts I wrote to work around rare problems we heard from feedback.

**Comment by weshaggard** [comment]
Related to https://github.com/Azure/azure-sdk-tools/issues/1051.

**Comment by weshaggard** [comment]
Closing this using #1051 to track the work to improve this and I suggest we start by using what is on the image instead of force installing.
