### ISSUE TITLE
[SDK-Automation] All the SDK artifacts and APIViews should be available even if one package fails to generate in the spec PR

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#8710]
**Description**
When a spec PR contains multiple services, if there is a package fail to generate, then this will cause the subsequent steps not run, such as artifacts copy, and APIView creation, etc.

**Screenshot**
![image](https://github.com/user-attachments/assets/1e6e994f-0066-4e10-be66-93c125444454)

**Expected**
Only the package fails to generate can be ignored from displaying, other packages should be available for downloading and API Views should be generated.

**Sample PR pipeline run**
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3970611&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437

**Comment by wanlwanl** [comment]
it's marked done in project.  please reopen it if dnecessary.
