### ISSUE TITLE
Block multiple click on upload button in Apiview - Create review

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#872]
Upload button is not disabled after user clicks upload button. So if upload takes longer to parse the code when creating review, they can click again and it will generate duplicate review. Solution should to be to show an message like upload in progress and disable upload button as soon user clicks upload button.

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/2785
