### ISSUE TITLE
APIView is showing diff lines even without selecting a diff revision

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#8724]
APIView shows diff lines in view even when a diff revision is not selected. Below screenshot shows that diff revision is empty but APIView view section shows deleted lines.

I don't have a diff selected, yet the view shows me removed members. is this a bug or how should I interpret it?

![image](https://github.com/user-attachments/assets/44c929d8-d394-4c5a-87fc-0f0178021270)

**Comment by maririos** [comment]
@praveenkuttappan could you add the link to the APIView ?

**Comment by praveenkuttappan** [comment]
> @praveenkuttappan could you add the link to the APIView ?

I don't have the URL for the reported issue. But I was able to repro it by first checking the diff and then copying the URL without diff revision and opening it on different browser. It seems @chidozieononiwu  is aware of this issue.
https://spa.apiview.dev/review/76332000a1a44557b19f7a7eacc39624?activeApiRevisionId=7da1191982e44dc390026416c92b9d12
