### ISSUE TITLE
Clean-up akams telemetry pipeline and resources

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#8726]
Our pipeline hasn't been ran for awhile and we don't believe we need it any longer so we should delete it.

Things to clean-up
- [x] [automation - akams-telemetry-sync](https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=5565) pipeline
- [x] Variable group https://dev.azure.com/azure-sdk/internal/_apps/hub/ms.vss-distributed-task.hub-library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=126&path=Secrets%20for%20aka.ms%20API
- [x] KV secrets in variable group (https://dev.azure.com/azure-sdk/internal/_search?action=contents&text=akams-app-id&type=code&lp=code-Project&filters=ProjectFilters%7Binternal%7DRepositoryFilters%7Bazure-sdk-devops%7D&pageSize=25&result=DefaultCollection/internal/azure-sdk-devops/GBmaster//eng/secret-management/manual/AzureSDKEngKeyVault/akams-app-id.json)
- [x] AAD App
- [x] Tools and script for the pipeline in [azure-sdk-build-tools repo ](https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-build-tools?path=/tools/akams-telemetry-sync&_a=history)
- [x] Remove [service connection](https://dev.azure.com/azure-sdk/internal/_settings/adminservices?resourceId=a8a58890-5284-44b0-b510-747857776593)

**Comment by danieljurek** [comment]
This can be closed once the source code is deleted. Relevant authentication and authenticated assets have all been deleted. Source code cleanup is just cleanup work.

**Comment by danieljurek** [comment]
Done.
