### ISSUE TITLE
APIView - Add an option to run a dry run on review upgrade

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#8788]
APIView reviews are automatically upgraded when parser version is changed. We don't have a way to verify if this upgrade is going to be successful for all revisions until we actually run the update, and this can lead to some reviews upgraded and some reviews with older versions. We need to a built-in mechanism in APIView to run a dry run of upgrade that runs the upgraded without updating the metadata and code file in production storage account. (More like a read only mode run to verify all reviews are upgradable).

**Comment by maririos** [comment]
https://github.com/Azure/azure-sdk-tools/pull/8882

This work was done to test .NET production changes
