### ISSUE TITLE
Missing SDK package work items for completed release plans  (data plane)

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8796]
I am not consistently finding the SDK package work items related to the release plans or epic-product type in Azure Devops. 

Here is a recent example:  

- Release plan for Azure Health AI Deidentification service - https://dev.azure.com/azure-sdk/Release/_workitems/edit/19945
- Release plan state is "Complete/Finished".  
- This release plan is for the first initial Beta SDK releases for the new service and offering. 
- I find that the Beta SDKs on the Azure SDK GitHub release page - https://azure.github.io/azure-sdk/releases/latest/index.html?search=Deidentification

Here is a query of all "Completed/Finished" Public Preview or GA release plans - https://dev.azure.com/azure-sdk/Release/_queries/query/?tempQueryId=f12549a7-1731-4862-a512-1836e431ead1.

**Comment by maririos** [comment]
Looking at this issue, there are multiple things happening:
1. The cloud flow is creating package work items, when they already exist. The logic is: a DevOps package appears, our sync jobs downloads the information into our `SDK packages` table. That information is then loaded into the UI so when the user selects the package and hits `Next`, we shouldn't create it again. Because of this we have decided to turn off the cloud flow in all instances.
2. When the user selects a package and hits `Next`, we should link that package into the release plan and the product. We should have all this information already. In here, we need to make sure that the package work item doesn't have a parent already (if there is a parent we won't be able to link it to a Prodcut). If they have a parent and it is not the Product work item we expected, then we should overwrite.

**Comment by ladonnaq** [comment]
> Looking at this issue, there are multiple things happening:
> 
> 1. The cloud flow `Automated create package work item` is creating package work items, when they already exist. The logic is: a DevOps package appears, our sync jobs downloads the information into our `SDK packages` table. That information is then loaded into the UI so when the user selects the package and hits `Next`, we shouldn't create it again. Because of this we have decided to turn off the cloud flow in all instances.
> 2. When the user selects a package and hits `Next`, we should link that package into the release plan and the product. We should have all this information already. In here, we need to make sure that the package work item doesn't have a parent already (if there is a parent we won't be able to link it to a Prodcut). If they have a parent and it is not the Product work item we expected, then we should overwrite.

@maririos There are quite a few management plane release plans that are complete and I know the SDKs were released (b/c I saw the request email and the request issues are closed) but the package work items are not found with the release plan.  Do you know why this is happening so we can resolve it?  Does management plane need to do something specific to ensure that the package work items are created? 

Here is another example - SDKs were released end of July but I do not see any of the SDK packages in ADO. 

- Link to release plan: https://aka.ms/sdk-release-planner?release-plan-id=3ded0538-0549-ef11-a316-002248043531
- Link to ADO release plan work item: https://dev.azure.com/azure-sdk/Release/_workitems/edit/23323/
- Link to the GitHub request issues (The release plan was only for Python & Go): https://github.com/Azure/sdk-release-request/issues/5338 & https://github.com/Azure/sdk-release-request/issues/5337

**Comment by maririos** [comment]
The fix I have been working on is for data plane.
For management plane, do we have those work items created by any automation @praveenkuttappan ? if so, do you know how do they get linked to the product or the release planner work item?

**Comment by ladonnaq** [comment]
[like]  LaDonna Quinn reacted to your message:
________________________________

**Comment by maririos** [comment]
We talked more about this during stand up and it does seem that my change won't affect management plane.
Praveen has some ideas on how we can improve this experience once he works on https://github.com/Azure/azure-sdk-tools/issues/8232.

To keep this issue in context, I am going to keep focusing on the data plane fix

**Comment by ladonnaq** [comment]
[like]  LaDonna Quinn reacted to your message:
________________________________
