### ISSUE TITLE
Feedback onboarding APEX feature

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8837]
From the image:

<img width="689" alt="image" src="https://github.com/user-attachments/assets/6b87ed88-b114-482c-a525-4502524dbbde">

1. There seems to be a border shadow in this component. Could you check the properties and remove it?
2. It is better to use aka.ms links when we can so we don't need to update the UI and do a release if the link changes. The link is https://aka.ms/azsdk/rest-api-scope  **(La Donna) I agree the aka link should be used.**  
3. If might be better if this check box only appears if the user selects `management plane` -> `In scope`  **(La Donna) I agree if it would improve UI if the RPaaS checkbox only is displayed if user selects management plane as in scope.**  
4. Because the UI might change according to the check box for RPaaS, what do you think about flipping `management plane` and `data plane` so that `data plane` is the first and then you have UI space for the second? **(La Donna) Good idea, let's do it.** 

Scenario - already onboarded product:
<img width="443" alt="image" src="https://github.com/user-attachments/assets/ce8de894-fdcc-4fe8-b5d6-d9582adf2621">

I thought the goal here was to know if the existing SDKs are management plane or data plane. What if the wording is instead:
- This product already has public management plane SDKs.
- This product already has public data plane SDKs.
- Eliminate `This product has public SDKs`.  **(La Donna) We could only show the relevant options based on the values of DataScope & MgmtScope.  If the user already indicate there are no management plane REST API endpoints publicly exposed, then there would be no reason to ask if there are existing management plane SDKs.** 

Also, could you show me where is this updated in the work items?   

From  image:

![image](https://github.com/user-attachments/assets/6de0326c-f796-43d3-93cc-809f633cc333)

- Product lifecycle value is not present (should be GA). Here is the product work item I used for my testing: https://dev.azure.com/azure-sdk/Release/_workitems/edit/16756

**Comment by maririos** [comment]
I have moved # 4 and 6 to issue https://github.com/Azure/azure-sdk-tools/issues/8841 and will remove it from the description of this issue, so it only states UI related feedback

**Comment by maririos** [comment]
After reviewing PPE there are issues that are still not solved:
- Scenario - already onboarded product: the wording needs to be updated
- Summary view, product lifecycle is still empty
- In that view, there also seems to be an error where the product name is showing in the wrong place:

![Image](https://github.com/user-attachments/assets/3eaa5c81-c935-4fd1-b879-920fc1c029f4)

Other feedback:
- Email template is not rendering properly. I forwarded it
- When onboarding is done I get a window that I can't do anything about. When an informational meeting is not required, why do I get that pop up?
- Talking about the same window, the message in orange is super confusing. What do I do with that? better to leave that for the email template that has more context:

![Image](https://github.com/user-attachments/assets/4f8e15df-6701-4c02-962e-af577f031e43)

**Comment by maririos** [comment]
I tried onboarding a new Product and got an exception. My selections:
- Data plane: No
- Management pane: yes
- no PRs
- No SDKs 

Given this conditions I shoukd have got a request for an informational meeting, but that didn't happen:

![Image](https://github.com/user-attachments/assets/a4ca9301-b8f8-4596-b1ed-ce17c6c2a888)

**Comment by ckairen** [comment]
> After reviewing PPE there are issues that are still not solved:
> 
> * Scenario - already onboarded product: the wording needs to be updated
I don't think we've reached a consensus with LaDonna on this one?
> * Summary view, product lifecycle is still empty
This value is from products table, which I believe is from service tree. It's empty because the table value is not populated. other GA products can be shown successfully
![image](https://github.com/user-attachments/assets/34354576-b732-4dfd-8b44-9c567867d6fa)

> * In that view, there also seems to be an error where the product name is showing in the wrong place:
> 
> ![Image](https://private-user-images.githubusercontent.com/9868623/361049565-3eaa5c81-c935-4fd1-b879-920fc1c029f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTAzNDYsIm5iZiI6MTcyNDQ1MDA0NiwicGF0aCI6Ii85ODY4NjIzLzM2MTA0OTU2NS0zZWFhNWM4MS1jOTM1LTRmZDEtYjg3OS05MjBmYzFjMDI5ZjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMjE1NDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTUyZDUzYTZkYzQ2MzE3NmY3OWVlYmIyZDc5YjQzYjJkZWVhMDM4MzQ4NmNlMjY5OTM0NDdmZTQ0ODE0ZmQ1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.it7fGEg_PI3g4mBCklLIJnpvgPfbZ0S1NjXXSnvROnY)
> 
> Other feedback:
> 
> * Email template is not rendering properly. I forwarded it
should be fixed, am waiting on republish to ppe (will update this line later)
> * When onboarding is done I get a window that I can't do anything about. When an informational meeting is not required, why do I get that pop up?
fixed
> * Talking about the same window, the message in orange is super confusing. What do I do with that? better to leave that for the email template that has more context:
Do we want to leave this for the email? or should we keep this as @ladonnaq suggested in the original issue
> 
> ![Image](https://private-user-images.githubusercontent.com/9868623/361053782-4f8e15df-6701-4c02-962e-af577f031e43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0NTAzNDYsIm5iZiI6MTcyNDQ1MDA0NiwicGF0aCI6Ii85ODY4NjIzLzM2MTA1Mzc4Mi00ZjhlMTVkZi02NzAxLTRjMDItOTYyZS1hZjU3N2YwMzFlNDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjNUMjE1NDA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWZlYTRiMzJmMjY0M2FmYTk1OWI1MGI1MGQwNzNjMWZjYWFmMGUwZGE3ZGU2NDY5ODU4OTdlNDliZDRmOTMwMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.giN58QJuGwb2KYxK67L238PMEY6w4wE1h86ENrA83AA)

**Comment by maririos** [comment]
> After reviewing PPE there are issues that are still not solved:

Scenario - already onboarded product: the wording needs to be updated
I don't think we've reached a consensus with LaDonna on this one?

Well, the current text doesn't read properly. If you need explicit consensus from La Donna you can ping her and provide the options I gave plus the ones you consider. 
Either way, I would feel more comfortable releasing to prod with an improved wording.

**Comment by maririos** [comment]
I tried to onboard a product that is new and got the following exception:
> UpdateReleaseWorkItem.Run failed: { "error": { "code": 502, "source": "unitedstates-002.azure-apim.net", "clientRequestId": "cd27c530-3ce0-40b0-a092-6b9c51cb142d", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not receive a response from an upstream server. Request tracking id '08584768925454604995059120700CU173'." } } } }

**Comment by maririos** [comment]
Given issue: https://dev.azure.com/azure-sdk/Release/_workitems/edit/23808
My answer for data plane was unsure. Does it make sense that the value for `Data plane SDK release type = new initial SDKs` ?

**Comment by maririos** [comment]
Given issue: https://dev.azure.com/azure-sdk/Release/_workitems/edit/23810
My answer was:
- yes data plane.
- No management plane
- yes existing SDKs

Why was I prompted to schedule an informational meeting?

![image](https://github.com/user-attachments/assets/5903a20f-042d-4f7c-9380-03cf63eb9e16)

**Comment by ckairen** [comment]
removed the "has existing sdk" option and reworded dataplane & mgmt as options
- This product already has public management plane SDKs.
- This product already has public data plane SDKs.
according to consensus reached in meeiting

**Comment by ckairen** [comment]
> I tried to onboard a product that is new and got the following exception:
> 
> > UpdateReleaseWorkItem.Run failed: { "error": { "code": 502, "source": "unitedstates-002.azure-apim.net", "clientRequestId": "cd27c530-3ce0-40b0-a092-6b9c51cb142d", "message": "BadGateway", "innerError": { "error": { "code": "NoResponse", "message": "The server did not receive a response from an upstream server. Request tracking id '08584768925454604995059120700CU173'." } } } }

the 502 was due to empty entries of "current lifescycle stage" & "target lifecycle stage", opening an issue for prompting error message for partner teams to update service tree https://github.com/Azure/azure-sdk-tools/issues/8893
