### ISSUE TITLE
DataScope and MgmtScope 

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8841]
From conversation on issue #8837 

**Mariana:** What do you think about In scope for APEX and Out of scope for APEX? I know it is longer, but it provides more context, and it might save people a click to the documentation.  (La Donna)  The **DataScope** and **MgmtScope** fields are not specific to APEX so it would not make sense to use in scope for APEX or out of scope for APEX. These fields are specific to the REST API endpoints that the service will be exposing publicly to enable new products and functionality to external customers. The **isAPEX** field is the APEX specific field and the **_scope for APEX data and/or management launch readiness requirements and lifecycle states fields are determined by the DataScope & MgmtScope field values._**

**La Donna**: As I am testing the onboarding scenarios, I think that the current drop-down choices will be be confusing. The data we need is to know is the scope of the Service & product REST APIs (data and/or management plane). We are using this information to determine DataScope and MgmtScope and then later in the back-end to automatically determine the value of the isAPEX data field in the epic-product type.
- Let's use these values for the drop-down box_"Yes", "No", or "Unsure"_.
- Also, let's provide better context in the statement. "To help us learn more about your REST APIs, please identify which endpoints are publicly exposed." Then update the field titles to make it clearer as to what we are asking. Management (ARM endpoints) Data (non-ARM endpoints).

When we change the values to "Yes", "No", or "Unsure" and make the other updates I suggested for https://github.com/Azure/azure-sdk-tools/pull/5, I think that the user will understand they need to select the appropriate choice for data plane REST APIs. The questions we really want to know the answers are "Will or does the product being onboarded have REST APIs with publicly exposed endpoints? If yes, Are the endpoints ARM (management plane) or non-ARM (data plane) or both.

**Comment by maririos** [comment]
@ladonnaq from Crystal's work, we learn that we need to be short. so instead of 
> "To help us learn more about your REST APIs, please identify which endpoints are publicly exposed." 

We could do:

> Determine REST API scope => where scope is a hyperlink to the docs

**Comment by maririos** [comment]
So to clarify, this has nothing to do with APEX. 
So the difference from what we have today is that it is adding the `No` option for people to select, so people can say `No` to both and cover one of the request you had a long time ago

**Comment by ladonnaq** [comment]
> @ladonnaq from Crystal's work, we learn that we need to be short. so instead of
> 
> > "To help us learn more about your REST APIs, please identify which endpoints are publicly exposed."
> 
> We could do:
> 
> > Determine REST API scope => where scope is a hyperlink to the docs

We can use your suggested statement and monitor for feedback.

**Comment by ladonnaq** [comment]
> So to clarify, this has nothing to do with APEX. So the difference from what we have today is that it is adding the `No` option for people to select, so people can say `No` to both and cover one of the request you had a long time ago

That is correct the DataScope and MgmtScope fields are not specific to APEX.   They are specific to the REST API endpoints that the service will be exposing publicly to enable new products and functionality to external customers.   The isAPEX field is the APEX specific field and the scope for APEX data and/or management launch readiness requirements and lifecycle states are determined by the DataScope & MgmtScope field values.
