### ISSUE TITLE
Make CompareBodies without order if it is application/json 

### ISSUE THREAD

**Issue by pshao25** [Azure/azure-sdk-tools#8857]
This [function](https://github.com/Azure/azure-sdk-tools/blob/414852cd27e1bc737934fd0ad5448aa73f034d5a/tools/test-proxy/Azure.Sdk.Tools.TestProxy/Common/RecordMatcher.cs#L157) requires the payloads cannot have order difference. I think we should only compare the key-value without considering the order.

**Comment by scbedd** [comment]
Closing in favor of the original #3171 , and pulling the original onto my near future backlog. Should have a version for you in a day or so.
