### ISSUE TITLE
Flow to mark a release plan as completed

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#8872]
Create a cloud flow that given a release plan ID, change the state of the release plan to `Finished/completed` and add tag `auto-closed`.
More context in issue https://github.com/Azure/azure-sdk-tools/issues/8290

**Comment by maririos** [comment]
New flow created under the name `Manually complete a release plan`
Test in dev: https://dev.azure.com/azure-sdk/Release/_workitems/edit/18827/

**Comment by ladonnaq** [comment]
> Create a cloud flow that given a release plan ID, change the state of the release plan to `Finished/completed` and add tag `auto-closed`. More context in issue #8290
I created a query that identifies all of the release plans tagged auto-complete or auto-abandon.  Do you want to use the query in the cloud flow and then remove the tags after complete and add tag auto-closed?

**Comment by ladonnaq** [comment]
Something must have been corrupted when I exported and imported the work items to change add values of isAPEX & isInitial fields. I will omit any date fields when I export and import in the future.  Excel tries to convert anything resembling a date to a "date field" and ADO date fields are not standard (remember Praveen had to just use text field). 
Is there a way to push the data for that field back out to the release plans?  If not, I can go to each release plan that is showing incorrect and edit in the release plan.  That does work as I just tried it.

**Comment by maririos** [comment]
>I created a query that identifies all of the release plans tagged auto-complete or auto-abandon. Do you want to use the query in the cloud flow and then remove the tags after complete and add tag auto-closed?

If you are manually adding those tags, then i will prefer for you to keep filling an issue with the release plan numbers and we will run the respective flows
