### ISSUE TITLE
Display error message if Lifecycle metadata is empty when Service or Product onboards to the SDK System (using the Release Planner App)

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8893]
**Requirement:** During onboarding the Service Tree metadata for Product and Service Lifecycle is ingested by the Release Planner App. It is the Service Team's responsibility to maintain the Lifecycle metadata for their Service and Products.  If the Release Planner encounters the field value to be EMPTY, then an error message should be shown the user with directions how to resolve. 

**Service Tree Current Lifecycle metadata** 
<img width="749" alt="image" src="https://github.com/user-attachments/assets/fc25f92c-3b19-4629-b6fd-f439c5eb29da">

**Scenario:**  _User is onboarding a service only (no product) AND the Current Lifecycle metadata field is EMPTY._ 

- [ ] If Service Current Lifecycle metadata is EMPTY, then display an error message to the user and block onboarding. 
- [ ] **Error Message:**  The Service's Service Tree "Current Lifecycle" metadata is empty.  You will need to update the lifecycle metadata in Service Tree before continuing to onboard to the SDK System. Link to Service's Service Tree entity - <link to Service's Service Tree Entity>. 

**Scenario:** _User is onboarding a Product AND the Current Lifecycle metadata field is EMPTY._ 

- [ ] If Service Current Lifecycle metadata is EMPTY, then display an error message to the user and block onboarding. 
- [ ] **Error Message:**  The Product's Service Tree "Current Lifecycle" metadata is empty.  You will need to update the lifecycle metadata in Service Tree before continuing to onboard to the SDK System. Link to Product's Service Tree entity - <link to Product's Service tree Entity>. 
-

**Comment by maririos** [comment]
@ckairen currently what happens if this is the case? how is our tooling behaving?

**Comment by praveenkuttappan** [comment]
@ladonnaq Changes to show error message and disable onboarding.

Service does not have Current life cycle stage set and product list is empty scenario:

![Image](https://github.com/user-attachments/assets/80bbe181-cc31-4545-b24e-6fc7e18c2064)


Product does not have current life cycle metadata in correct service tree tables:
![Image](https://github.com/user-attachments/assets/5dcca68c-e5b5-4d50-b6ee-c350419769a9)

**Comment by ladonnaq** [comment]
Thank you, messaging and UI looks great!
