### ISSUE TITLE
tsp-client failed to generate ts client for oracle/Oracle.Database.Management

### ISSUE THREAD

**Issue by wanlwanl** [Azure/azure-sdk-tools#8899]
# Error
The `../../../models/exadata/exadatainfra.tsp` is out of typespec root, looks like tsp-client failed to copy the shared tsp files that out of typespec root to temp folder, and cause the error below:
```
04:05:03.379 cmderr 	[automation_generate.sh] /mnt/vss/_work/1/s/azure-sdk-for-js/sdk/oracledatabase/arm-oracledatabase/TempTypeSpecFiles/Oracle.Database.Management/operations/exadata/exadatainfrastructureOperations.tsp:2:1 - error import-not-found: Couldn't resolve import "../../../models/exadata/exadatainfra.tsp"
```

# Repro Step
``` shell
# Repro
cd <root>
git clone https://github.com/Azure/azure-sdk-for-js
git clone https://github.com/test-repo-billy/azure-rest-api-specs
cd azure-rest-api-specs
git checkout user/raych1/sdk-gen-batch6
cd ../azure-sdk-for-js
tsp-client init --debug --tsp-config ../azure-rest-api-specs/specification/oracle/Oracle.Database.Management/tspconfig.yaml --local-spec-repo ../azure-rest-api-specs/specification/oracle/Oracle.Database.Management --repo ../azure-rest-api-specs --commit a4f8429b81f26cac2366953b4183e297bba442d1
```

**Comment by raych1** [comment]
@wanlwanl 
this is a configuration issue. Please refer to sample `tspconfig.yaml` to add the `[additionalDirectories](https://github.com/Azure/azure-rest-api-specs/blob/a3913f4b26467aed413cdc907116e99894f08994/specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml#L6)`, so that the additional reference TypeSpecs can be downloaded too.

**Comment by wanlwanl** [comment]
[additionalDirectories](https://github.com/Azure/azure-rest-api-specs/blob/a3913f4b26467aed413cdc907116e99894f08994/specification/contosowidgetmanager/Contoso.WidgetManager/tspconfig.yaml#L6) works
