### ISSUE TITLE
APIView - Create a tool to convert existing C++ review to new parser model

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#8916]
Existing C++ API reviews does not have original source file to automatically recreate API review when a parser is upgraded. We need a tool to convert existing review to new format so when parser is changed to new tree model then we can convert existing sequential token model to new tree model.

**Comment by maririos** [comment]
Tool is done Waiting on documentation

**Comment by maririos** [comment]
Documentation #9270
