### ISSUE TITLE
Support Data Plane Modular Client SDK Automation

### ISSUE THREAD

**Issue by wanlwanl** [Azure/azure-sdk-tools#8935]
Currently, js-sdk-release-tool support management plane only. The sdk generation part can be resued for data plane.
To support data plane automation, we need to revisit:
1. What are required options in tspconfig
2. What is the condition lead to generate data plane modular sdk instead of management plane

Related PR: https://github.com/Azure/azure-sdk-tools/pull/8906

Depend on: https://github.com/Azure/autorest.typescript/issues/2636

**Comment by raych1** [comment]
@wanlwanl please use `Automation Tool` label, which is to replace `SDK Automation`.

**Comment by wanlwanl** [comment]
same root cause to #8532, dup

**Comment by wanlwanl** [comment]
dup issue, close
