### ISSUE TITLE
.\Verify-Links.ps1 reporting error The property 'Response' cannot be found on this object. Verify that the property exists.

### ISSUE THREAD

**Issue by nkalyanreddy** [Azure/azure-sdk-tools#8936]
Hi,
I am trying to integrate linkchcker script(Verify-Links.ps1) into build pipeline to monitor brokenlinks on the site. But the script is returning the error "System.Management.Automation.PropertyNotFoundException: The property 'Response' cannot be found on this object. Verify that the property exists."
Please find below console log for the run. Thanks.

.\Verify-Links.ps1 https://azure.github.io/azure-sdk/index.html
WARNING: Some web requests will not work in versions of PS earlier then 6. You are running version 5.1.22621.3958.
https://azure.github.io/azure-sdk/index.html
Chrome/87.0.4280.88
Exception encountered while processing pageUri https://azure.github.io/azure-sdk/index.html : System.Management.Automation.PropertyNotFoundException: The property 'Response' cannot be found on this object. Verify that the property exists.
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
The property 'Response' cannot be found on this object. Verify that the property exists.
At C:\Users\kreddy\source\repos\ConsoleApp1\ConsoleApp1\Verify-Links.ps1:438 char:7
+       $statusCode = $_.Exception.Response.StatusCode.value__
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

**Comment by weshaggard** [comment]
>WARNING: Some web requests will not work in versions of PS earlier then 6. You are running version 5.1.22621.3958.

@nkalyanreddy are you running this script on Windows Powershell? If so that is likely the issue you should probably be running it in Powershell Core v7 or higher.
