### ISSUE TITLE
Scheduling App not permitting update of .NET APIView link after meeting was scheduled 

### ISSUE THREAD

**Issue by ladonnaq** [Azure/azure-sdk-tools#8992]
Bug reported by user of the Scheduling App:  

"One thing I encountered in the PowerApp for SDK Review scheduling was when I initially scheduled the review meeting, I entered in an incorrect URL for the .NET API View. When I tried to update the URL after the meeting was created, the tool would not let me update it and I couldn't delete it an recreate the API View link for the meeting entry since it was the only one we had. I figured out that I could add another language entry for the API view URLs that was invalid (since we only have one right now), and then I could delete the .NET entry with the incorrect URL, and recreate it with correct URL. So a little hack around worked, but it wasn't intuitive."

- [ ] Need to recreate to see if the bug still exist or it was an intermittent issue

**Comment by maririos** [comment]
It looks to be an intermittent issue. I tried in both `Introduction` and `Follow up` and with both I was able to update the link.
I am going to close the issue. If we see this again, feel free to re-open it
