### ISSUE TITLE
Add Support for Larger Size VM Pools

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-tools#9002]
At the time of writing this issue, the VMs used in CI and testing are 4 vCPU machines. In most situations, the size of these machines is sufficient for good CI times, as there can be many situations where CI and testing isn't capable of scaling up to large VM sizes. But for some CI jobs and test jobs they scale very well for a larger machine size.

We should look into offering support for a scale up scenario, likely with machines that are 8 vCPUs.

**Comment by kurtzeborn** [comment]
We already have a pool (storage) where we provide larger machines for specific test scenarios.  We don't want to blanket add larger machines to all pipelines whether they need it or not.  If you have a specific test scenario or pipeline that you think needs a bigger VM, please reach out to @weshaggard or @benbp and let's discuss the specifics.  As I said, we already do this in certain scenarios, so it's already supported when needed.

**Comment by alzimmermsft** [comment]
Thanks for the information @kurtzeborn!

I've actually been meaning to close this issue as @benbp and I ran experiments using 8 vCPU machines and the results weren't near doubling performance and saw a much longer VM deployment time when running CI. In this we reach a conclusion, where if necessary, we'd copy what .NET did where they partition out their large running jobs into slices of SDKs to run. For example, in Java the Core From Source run is hitting about an hour to run (again) at the time of this comment and the resolution would be spawning multiple jobs where groups of SDKs are packed together in smaller jobs that run 15-20 minutes each (but consuming additional VMs each matrix run).
