### ISSUE TITLE
[tsp-client] unexpected error when running `tsp-client update`

### ISSUE THREAD

**Issue by msyyc** [Azure/azure-sdk-tools#9073]
- [@azure-tools/typespec-client-generator-cli](https://www.npmjs.com/package/@azure-tools/typespec-client-generator-cli): 0.13.0
- @azure-tools/typespec-python version: 0.35.0

When regenerate SDK for [azure-mgmt-trustedsigning](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/trustedsigning/azure-mgmt-trustedsigning) with cmd:
```
PS C:\dev\azure-sdk-for-python\sdk\trustedsigning\azure-mgmt-trustedsigning> tsp-client update
```
, the following error happens and no SDK code refreshed:
![image](https://github.com/user-attachments/assets/7d029984-b8cb-42ce-b7b5-59b30cadd21d)

However, if run command with additional configuration `--save-inputs`, no error happens and SDK code is generated successfully:
```
C:\dev\azure-sdk-for-python\sdk\trustedsigning\azure-mgmt-trustedsigning> tsp-client update --save-inputs
```
![image](https://github.com/user-attachments/assets/0a0227b6-b58c-432d-92fc-48d54258b018)

**Comment by msyyc** [comment]
This issue blocks upgrade on typespec-python@0.35.0 https://github.com/Azure/azure-sdk-for-python/pull/37633 and you can reproduce the error with that PR.

**Comment by catalinaperalta** [comment]
I saw a similar issue with someone from the powershell emitter team. It ended up happening because they were missing an await somewhere in their code. Could you take a look and see if you're missing an await somewhere? If it's fixed with the save-inputs flag, this makes me think that we're having an async problem somewhere
