### ISSUE TITLE
[Scheduling Tool] Meeting type Intro & Follow Up -> Preview & Stable

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-tools#9078]
### Current status: 
In the Scheduling tool, when scheduling an Azure SDK Review there is a `Meeting Type` field, with options for `Introduction` and `Follow up`. The `Introduction` meeting type is meant to be used for reviews for preview (beta) versions of libraries and the `Follow up` meeting type is meant to be used for reviews for stable (GA) versions of libraries. 

![image](https://github.com/user-attachments/assets/c6d25ca3-9059-4869-8c65-e03b1719ddd5)

### Problem: 
Partner teams cannot easily infer that they should select `Introduction` for a review of a preview version and `Follow up` for a stable version. They often believe since they have gone through the Azure SDK Informational meeting that they do not need to schedule an `Introduction` Azure SDK Review meeting, so they go right to the "Follow up" meeting type. This causes our team to prompt them to add all the required materials for a "Follow up" meeting which is a lot more than the required materials for a `Introduction` meeting. 

### Proposal: 
Switch the `Introduction` meeting type to `Preview Review` and the `Follow up` meeting type to `Stable Review`.
Or if possible, infer the type of review meeting from the type of release linked in their release plan.

**Comment by maririos** [comment]
OMG I love this idea! It will be so much clearer.
@ladonnaq what do you think?

**Comment by ladonnaq** [comment]
> OMG I love this idea! It will be so much clearer. [@ladonnaq](https://github.com/ladonnaq) what do you think?
I have mentioned this before, but there is still confusion among service teams regarding SDK review requirements for Beta vs. Stable SDK reviews. We do not use the term "Preview" with SDKs, so I recommend using "Beta" or "Stable" review. As I understand it, only the first (initial) Beta versions and all Stable versions require Arch Board review. If this is correct, we should make it clear. Given we know the release scenario, could we determine the default meeting type? For example, if it is a Greenfield TypeSpec scenario and they have not released Beta SDKs yet, when the user schedules the SDK Review, we could automatically determine it should be a "Beta review."

**Comment by maririos** [comment]
> For example, if it is a Greenfield TypeSpec scenario and they have not released Beta SDKs yet, when the user schedules the SDK Review, we could automatically determine it should be a "Beta review."

We can look into this more. For now I am going to see what the implications are for changing the names of the meetings (even if it is only in the UI :) )

**Comment by maririos** [comment]
This will change the title of the meeting too.
i.e:
`Azure SDK Review - [Introduction to Backup]` -> `Azure SDK Review - [Beta SDK for Backup] `
`Azure SDK Review - [Backup]` -> `Azure SDK Review - [Stable SDK for Backup] ` 

@ronniegeraghty you ok with that?

Example:

![Image](https://github.com/user-attachments/assets/4fe44492-7f58-41ea-aaf5-1fe34d56d95c)

**Comment by ronniegeraghty** [comment]
> [@ronniegeraghty](https://github.com/ronniegeraghty) you ok with that?


Yes, I think that looks great and makes it clearer for even our Architects.

**Comment by maririos** [comment]
It was easier than I thought. Changes have been deployed to DEV instance. I am expecting to do a PROD release on Monday.

**Comment by maririos** [comment]
Documentation update: https://dev.azure.com/azure-sdk/internal/_git/azure-sdk-docs-eng.ms/pullrequest/1113
I will merge once the changes are deploy to PROD

**Comment by maririos** [comment]
deployed
