### ISSUE TITLE
Verify-Links script should detect broken links on redirect

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-tools#910]
See https://github.com/Azure/azure-sdk-for-c/issues/1101. There was a page redirect that was broken. We should consider options to see if we can detect and report these as broken links.

**Comment by sima-zhu** [comment]
Based on the testing, the Invoke-WebRequest actually returns us status code of 200. We have to parse html to get the redirect link. For the link-verification scripts, it is responsible to report the error status code. If the link is still able to redirect you to the right link with 200 status code. We treat it as valid case for now.

Closed the issue and feel free to reopen this if anything unaddressed.
