### ISSUE TITLE
apiview/parsers/js-api-parser, "error TS5057" on "npm run-script build"

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-tools#9119]
[microsoft/typespec repository](https://github.com/microsoft/typespec) runs ts-genapi here https://github.com/microsoft/typespec/blob/52377dda44ba6aabf19f57d137f327fe3464c71e/eng/emitters/scripts/Generate-APIView-CodeFile.ps1#L40

On 2.0.0, this line produces error like [this](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4212318&view=logs&j=0bd0b8f1-704c-5c31-e9b8-328eae1b0e9f&t=f70cc04c-4888-588a-2f4f-a1a5f3954e09&l=822), which sets the `LASTEXITCODE` to 1, which in turn fails the whole PS/CI.
```
error TS5057: Cannot find a tsconfig.json file at the specified directory: '.'.
```

1.0.7 appears to be good on this account.

I am not sure whether this be a bug in ts-genapi, or an incorrect usage of ts-genapi in microsoft/typespec.

Please let me know if latter, and I can check with eng there to fix.

**Comment by weidongxu-microsoft** [comment]
@jeremymeng for awareness

**Comment by jeremymeng** [comment]
Looking

**Comment by jeremymeng** [comment]
PR to pin the version to 1.0.7 for now: https://github.com/microsoft/typespec/pull/4652
