### ISSUE TITLE
APIView is not showing icons in non SPA  page

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#9149]
APIView is not showing icons in old UI. This looks like a regression due to changes in PR. 

https://github.com/Azure/azure-sdk-tools/pull/9068/files#diff-22952b67e702457ddf58807a9d50a698a9e2da7be7665d04a99b6932293c72f8

**Comment by maririos** [comment]
PR: https://github.com/Azure/azure-sdk-tools/pull/9158

**Comment by chidozieononiwu** [comment]
Resolved
