### ISSUE TITLE
Add tasks/tabs into the Generate SDK for other languages != .NET

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#9195]
Add changelog, tests, samples, and codeowners review for all languages that are not .NET.

i.e.:

![Image](https://github.com/user-attachments/assets/50f028fe-dff3-456a-a10a-fbf755262814)

**Comment by praveenkuttappan** [comment]
Currently release planner will show an option to submit a request to generate SDK for all languages other than .NET
