### ISSUE TITLE
Modify the automated pipeline that published the TypeSpec management plane Go package

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#9204]
We want the user to be the one to queue the release instead of having automation.

**Comment by praveenkuttappan** [comment]
We don't need to make this change. We will show the status as released for Go and also inform user that merging a Go PR will automatically releases it.

**Comment by maririos** [comment]
Verify with help from @raych1

**Comment by praveenkuttappan** [comment]
Confirmed that Go release pipeline is automatically triggered when SDK PR is merged.
