### ISSUE TITLE
Enable/Disable Docs.MS Publishing Per Artifact

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#922]
The ability to retarget a repo based on `ci.yml` is already there, but I neglected to support disabling certain packages. This is due to the fact that even management packages need to be documented.

Well, turns out the `spring` starters aren't valuable from a artifact documentation point of view.

![image](https://user-images.githubusercontent.com/45376673/91246929-f5a05680-e705-11ea-9c67-63b941d9e77a.png)

So we need a methodology to enable/disable the `update-docs-ci` run _specifically_ in `update-docs-metadata.yml`. The readme updates are still judged to be valuable.

**Comment by sima-zhu** [comment]
Sync with @scbedd,  @weshaggard, will update a new `artifact.options.skipDocMs` option in condition step.

**Comment by sima-zhu** [comment]
All codes have checked in. 
Closed the issue.
Feel free to reopen if anything undone
