### ISSUE TITLE
[SDK Automation] azure-sdk-for-net-track2 generate script build error

### ISSUE THREAD

**Issue by JackTn** [Azure/azure-sdk-tools#9221]
After run azure-sdk-for-net-track2 [Generate Script](https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/Invoke-GenerateAndBuildV2.ps1) in sdk-automation. 
It missing file path **relatedTypeSpecProjectFolder** or **readmeMd** and **version** when input file is relatedTypeSpecProjectFolder or relatedReadmeMdFiles. The pipeline result you can see [1](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4250524&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=504) [2](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4250526&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=848)
The correct response refer to [this](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4250524&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=253)

**Comment by raych1** [comment]
@chunyu3 

either `typespecProject` or `readmeMd` and `version` need to be added to the output of .NET generation script.
