### ISSUE TITLE
[SDK Automation] azure-sdk-for-java generate script build error

### ISSUE THREAD

**Issue by JackTn** [Azure/azure-sdk-tools#9222]
After run azure-sdk-for-java [Generate Script](https://github.com/Azure/azure-sdk-for-java/blob/main/eng/automation/generate.py) in sdk-automation.
It missing **changelog content** and **version** when input file is relatedTypeSpecProjectFolder or relatedReadmeMdFiles. The pipeline result you can see [1](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4250524&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=547) [2](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4250526&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=1443)
The correct response refer to [this](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4250524&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=253)

**Comment by raych1** [comment]
@weidongxu-microsoft @XiaofeiCao 
both `content` and `breakingChangeItems` need to be added to report the breaking changes.

**Comment by weidongxu-microsoft** [comment]
@raych1 

I may not get it. There is only 1 stable api-version in AzureFleet (computefleet as SDK)
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurefleet/resource-manager/Microsoft.AzureFleet

So, there is no breaking change to report at all -- there is no previous GA SDK at all

**Comment by JackTn** [comment]
@weidongxu-microsoft  Apologies for any confusion caused. The issue at hand is that the breakingChangeItems are not being returned as expected. For a clearer understanding, please refer to the results shown here [result](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4247148&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=1256). and here is correct response [this](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4250524&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=253).Additionally, it appears that the version has been returned accurately. Therefore, you may disregard it.

**Comment by weidongxu-microsoft** [comment]
@JackTn 

I still didn't get you.

Result in azure-data-schemaregistry is because there was 1.0.0 https://azure.github.io/azure-sdk/releases/latest/?search=azure-data-schemaregistry

No result for computefleet and datafactory is because there were no GA release in Java. (computefleet released 1.0.0 today)

**Comment by weidongxu-microsoft** [comment]
And DO NOT COMPARE JAVA WITH GO. Breaking change depends on SDK state of each language, and they could be in different state.

**Comment by weidongxu-microsoft** [comment]
You can reopen with a PR in specs, that it contains breaks to a released Java SDK, but it didn't have content in breaking changes section.

If you are unsure whether Java code change would be a break, check Revapi step in Java CI. https://dev.azure.com/azure-sdk/public/_build/results?buildId=4225865&view=logs&jobId=b70e5e73-bbb6-5567-0939-8415943fadb9&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=ba3cf43a-b2bf-50f9-f95f-93049ca44ad1

**Comment by JackTn** [comment]
Thansks, will check on this CI

**Comment by JackTn** [comment]
> [@raych1](https://github.com/raych1)
> 
> I did not get it. There is only 1 stable api-version in AzureFleet (computefleet as SDK) https://github.com/Azure/azure-rest-api-specs/tree/main/specification/azurefleet/resource-manager/Microsoft.AzureFleet And Java hadn't released it (it is scheduled today -- 10/22).
> 
> So, there is no breaking change to report at all -- there is no previous GA SDK, every SDK before is beta/preview
> 
> SDK only concerns about breaking change compared to a prior GA SDK (it be 2nd GA compares to 1st GA; or a next beta compares to 1st GA -- but you have to have a 1st GA SDK)

As the AzureFleet is release, this [pr](https://github.com/Azure/azure-rest-api-specs/pull/31160/checks?check_run_id=31958643408) has correct hasBreakingChange flag for [GO](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4260299&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=1291). But why there are no breakingchange items return when the hasBreakingChange is true ? @weidongxu-microsoft

**Comment by weidongxu-microsoft** [comment]
@XiaofeiCao to take a look

@JackTn Which "breakingchange items" is it?

**Comment by XiaofeiCao** [comment]
@JackTn Seems this `breakingChangeItems` is [added](https://github.com/Azure/azure-rest-api-specs/commit/c2dff09296593a12cadba0f9d3352212c78a3baa#diff-3e250b45d586f370c38f81095541e3504afd0bbf8e34d218f0a1b37fbf505779R59) after we supported breaking change detection, see original issue https://github.com/Azure/azure-sdk-tools/issues/8477#issue-2363689460

I'll add support for this property

**Comment by JackTn** [comment]
> [@JackTn](https://github.com/JackTn) Seems this `breakingChangeItems` is [added](https://github.com/Azure/azure-rest-api-specs/commit/c2dff09296593a12cadba0f9d3352212c78a3baa#diff-3e250b45d586f370c38f81095541e3504afd0bbf8e34d218f0a1b37fbf505779R59) after we supported breaking change detection, see original issue [#8477 (comment)](https://github.com/Azure/azure-sdk-tools/issues/8477#issue-2363689460)
> 
> I'll add support for this property

Thanks!

**Comment by XiaofeiCao** [comment]
We have roughly three kinds of breaking changes
### 1. class-level
```markdown
#### `ModelA` was removed
```
proposed breaking change item: 
```markdown
- Class `ModelA` was removed.
```

### 2. method level
```markdown
#### `ModelB` was modified
* `sku()` was deleted
* `tier()` was deleted
```
proposed breaking change item:
```markdown
- Class `ModelB` was modified: `sku()` was deleted, `tier()` was deleted.
```

### 3. fluent lite stage
```markdown
#### `ModelC$DefinitionStage` was modified
* `properties()` was deleted from stage 3
```
proposed breaking change item:
```markdown
- Class `ModelC$DefinitionStage` was modified: `properties()` was deleted from stage 3
```

**Comment by raych1** [comment]
@XiaofeiCao how about the other cases, such as adding new required parameters, changing the optional parameters to required parameters? Are they considered as breaking changes?

**Comment by XiaofeiCao** [comment]
> [@XiaofeiCao](https://github.com/XiaofeiCao) how about the other cases, such as adding new required parameters, changing the optional parameters to required parameters? Are they considered as breaking changes?

Yeah, adding a new required parameters(or changing optional to required) will result in method signature change. This is method-level breaking change.

**Comment by raych1** [comment]
@JackTn 
can you please verify and close this issue if it has been fixed?

**Comment by JackTn** [comment]
Mark as resolved.
Test before: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4247148&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=1256
After : https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4397740&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=1167
