### ISSUE TITLE
[Release Planner] Links to language generation tutorials

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-tools#9223]
## Current Situation
In the Release Planner's Data Plane SDK readiness app, the Generate SDKs page has a step to "Generate the SDK for <Language>" step. 
This step has a link to the instructions for how to generate the library in that language. 
![Image](https://github.com/user-attachments/assets/3a2710c4-6881-4b99-98d0-d95a96ea3f05)
However, this link doesn't go right to the instructions. It goes to the [Eng Hub page on Develop client libraries (SDK)](https://eng.ms/docs/products/azure-developer-experience/develop/sdk-develop?tabs=dataplane). Then on this page you need to click the link for the languages instructions on generating libraries: 
![Image](https://github.com/user-attachments/assets/fbb6b80f-484d-4dc2-bd9b-dabd5cba04f0)

## Problem
It is easy for users of the Release Planner to get lost when going between the release planner links and Eng Hub links. 

## Proposed solution 
The release planner links directly to the language's instruction on generating libraries, rather than stopping through the Eng Hub docs.

**Comment by maririos** [comment]
@ronniegeraghty 

> The release planner links directly to the language's instruction on generating libraries, rather than stopping through the Eng Hub docs.

The reason we did that is so we don't have duplication in both places. and to keep it in sync. I can see though, how it is more hoops for the users.
This will be true too for testing and generating samples. 

Would you still suggest for us to follow the link directly strategy for those 3 areas?

**Comment by ronniegeraghty** [comment]
> Would you still suggest for us to follow the link directly strategy for those 3 areas?

I think so.

**Comment by maririos** [comment]
@praveenkuttappan any objections to this plan?

**Comment by praveenkuttappan** [comment]
I think it's fine to do it but we need to add information about "Before we begin" to be listed in release planner.

```_You have access to the GitHub repositories and respective GitHub groups.
You read our repository branches strategy.
You are familiarized with the Azure SDK Architecture design guidelines.```

**Comment by maririos** [comment]
> I think it's fine to do it but we need to add information about "Before we begin" to be listed in release planner.
> 
> ```
> You read our repository branches strategy.
> You are familiarized with the Azure SDK Architecture design guidelines.```
> ```

Ohhh interesting. Reading that section, it looks like it should belong in as part of the prerequisites checks instead of generation SDK task itself.
As we look into improving the process, lets contemplate this too.

**Comment by maririos** [comment]
Done for code generation, tests, and samples. I am using the same links as the ones provided in Eng Hub
