### ISSUE TITLE
Generate Private Java Package YML and add for Ignite

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#923]
Currently docs CI HAS to go to maven to generate without workarounds. The package in question won't be published till during/after Ignite.

Use the [migration.json](https://github.com/Azure/azure-docs-sdk-java/blob/master/temporary-src-based-yml/migration.json) workaround.

**Comment by sima-zhu** [comment]
Seems a missing task. Since ignite has already happened. Closed the issue.
