### ISSUE TITLE
SuppressionFile link should point to the PR branch rather than the main branch

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#9237]
**Description**
The link won't be available if suppression file doesn't exist in the main branch.
Instead, it should point to the PR branch.

**Sample spec PR**
https://github.com/Azure/azure-rest-api-specs/pull/31158/checks?check_run_id=31909166267
![Image](https://github.com/user-attachments/assets/9bee3e71-f07a-4d32-b05d-5aaf7a8a9ba5)

In addition, if the suppression file doesn't exist in both the main branch and the PR branch, it **should not be rendered** in the CI check result.

**Comment by JackTn** [comment]
One more sentence， if no breakingchange, no render suppression. if has breakingchange, show PR branch supression file

**Comment by JackTn** [comment]
fix by https://devdiv.visualstudio.com/DevDiv/_git/openapi-alps/pullrequest/587267
