### ISSUE TITLE
Create guidance document for SDK code generation (Go management plane)

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#9240]
This task involves creating a comprehensive guidance document for generating SDK code in the Go language. The document should be applied to both manual and automated generation processes.

**Purpose**
The document will serve as a reference for the service team, detailing the steps for SDK code generation while the automation process is still under development. Once finalized, the guidance will be linked to the release planner app and used by the service team as the primary resource.

**Requirement**
It should provide clear instructions, examples, and relevant best practices to ensure consistent and reliable SDK generation

**References**
[Auto generation pipeline](https://dev.azure.com/azure-sdk/internal/_build?definitionId=5110)
[Initialization script](https://github.com/Alancere/azure-sdk-for-go/blob/ba957e167ced10ad32ba0b6a742c4b5c924b42bd/eng/scripts/automation_init.sh)
[Generation tool](https://github.com/Alancere/azure-sdk-for-go/tree/ba957e167ced10ad32ba0b6a742c4b5c924b42bd/eng/tools/generator)

**Comment by raych1** [comment]
Added the linked issue:
https://github.com/Azure/azure-sdk-for-go/issues/23709

**Comment by lirenhe** [comment]
@chidozieononiwu, was this item completed?

**Comment by chidozieononiwu** [comment]
> [@chidozieononiwu](https://github.com/chidozieononiwu), was this item completed?

Yes, this work is done.
