### ISSUE TITLE
Share md -> html conversion

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#929]
We render the repo level readme as the landing page for the `index`

This is individually implemented by each indexing build. We should write a single script for this (currently python is used) and share across all languages.

Immediate benefit is that if we need to process this markdown differently due to some constriction on `docs.ms` or the like, we'll be able to change it in a single location to get results.

**Comment by kurtzeborn** [comment]
This was done with the service-level readme work.
