### ISSUE TITLE
Migrate dependencies on azure-js-dev-tools

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#9309]
The code base of `azure-js-dev-tools` are in both the openapi-alps repo and the GitHub repo. We will need to sync the changes from openapi-alps repo to the GitHub repo and publish the latest version to npmjs.com.

Alternatively, we may replace this library with other more popular library.

**Comment by maririos** [comment]
Which GH repo? is there a way we can go around this without publishing a npmjs package at all?
what functionalities are in this library that we need?

**Comment by raych1** [comment]
This is the repo: https://github.com/ts-common/azure-js-dev-tools.

What we use in the sdk automation include the file systems, GitHub interaction, autorest, html builders, array and stringmaps accessor, etc.
