### ISSUE TITLE
tsp client should log the command used to call typespec

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/azure-sdk-tools#9347]
This makes it hard to verify if `tsp-client` or typespec is causing issues as it abstract away the typespec call.

We should ideally log the comand the user could paste back and check if that is running or its just a tsp client issue.

**Comment by catalinaperalta** [comment]
This already exists in the tool. Pass the `--debug` flag and an example command will be outputted at the end of the debug log. However, please note that tsp-client is currently using the typespec/compiler library directly and not using a shell command to generate specs so we might need to perfect this "example" command. I'll close this issue now, but feel free to open a new one if we need to fix anything with the example command.
