### ISSUE TITLE
Provide documentation on using the generated draft SDK pull request

### ISSUE THREAD

**Issue by raych1** [Azure/azure-sdk-tools#9350]
Following discussions around the `Liftr` team’s requests, we plan to provide a guidance document on effectively using the draft SDK pull requests generated by the current SDK automation process. 

This documentation will offer step-by-step instructions on how to access and utilize the draft SDK PRs, allowing the team to retrieve the SDK code directly from a PR rather than generating it manually. 

This solution aims to support the team while we continue developing the new SDK automations.

**Comment by maririos** [comment]
Documentation available at: https://eng.ms/docs/products/azure-developer-experience/develop/sdk-draft-pullrequest
