### ISSUE TITLE
PowerApps deployment to use federated identity

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#9376]
PowerApps deployment pipeline uses Entra App and client secret to authenticate to env. This needs to be changed to use federated identity instead of client secret.

**Comment by maririos** [comment]
Is this available now for PowerApps? I thought that was our limitation

**Comment by maririos** [comment]
Dup of https://github.com/Azure/azure-sdk-tools/issues/9503
