### ISSUE TITLE
Clean up .NET automation scripts

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#9422]
It looks like the [automation folder](https://github.com/Azure/azure-sdk-for-net/tree/main/eng/scripts/automation) contains code that is no longer consumed that needs to be cleaned so we don't confuse our users with outdated documentation. For example, file https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/automation/Invoke-GenerateAndBuild.ps1#L75 is using tools that we want to retire.
Also, looks like this script is no longer used and the one that is consumed is https://github.com/Azure/azure-sdk-for-net/blob/main/eng/scripts/Invoke-GenerateAndBuildV2.ps1

**Comment by maririos** [comment]
@chunyu3 could you please take a look at this issue and do the proper cleanup so previous tooling is not in the repo and confusing our users?

**Comment by chunyu3** [comment]
@maririos  Thanks. Yes, `Invoke-GenerateAndBuild.ps1` script is not used anymore, we will delete this script. 
And there are several scripts which may not usefully after we adopt `tsp-client` for both mgmt-plane and data-plane SDKs.  After we update related document such as https://github.com/Azure/azure-sdk-for-net/blob/main/doc/DataPlaneCodeGeneration/AzureSDKPackage_Setup.md#create-sdk-package, we will remove those scripts also,
