### ISSUE TITLE
Feedback for release 1.4.0-beta.2 management plane SDK release app

### ISSUE THREAD

**Issue by maririos** [Azure/azure-sdk-tools#9425]
- [x] Management app SDK release API specs view has 3 references to the word REST
- [x] Tab `Package Namespace` casing should be `namespace`
- [x] There are some visual alignment issues with the Package namespace UI. I wonder if we could improve it and make the checkbox more clear. Yes or no answer or something like that.
  - [x] For the message `Namespace approval is pending` we should use the same color/font/template of the API specs are not merged in previous tab
  - [x] The last `Next` button of the Prerequisites triggers a banner with a warning when the API spec is not merged in main. It is confusing that it happens after I clicked the next button for Package namespace. Because this is already implementing by a badge, we don't ned the banner. We can remove it
- [x] When submitting an exception, it is not clear that an email is going to be send to our team to evaluate the release exception. We should improve the UI here to mention that. An idea: "A generated email will be sent to the Azure SDK PM team for review". BTW, was is this feature applied to data plane?
- [x] When in Package Name tab, the Back button takes to SDK release details instead of API specs

Not related to the changes, but should the name of this feature be `Package name` instead of `Package namespace`?

**Comment by maririos** [comment]
All changes have been made in the management SDK release app. They have not been published though

**Comment by praveenkuttappan** [comment]
I have found an issue in alignment and label was not visible. Fixed and publishing it now. Thanks for fixing the issues.
