### ISSUE TITLE
[Scheduling Tool] Add label to GitHub issues for Azure SDK Reviews

### ISSUE THREAD

**Issue by ronniegeraghty** [Azure/azure-sdk-tools#9449]
## Problem: 
Currently it is difficult for architects to search through issues from past Azure SDK Reviews to find notes or materials for reference. This is because issues for Azure SDK Reviews are opened in the Azure/azure-sdk and Azure/azure-sdk-pr repo, which contain many other types of issues that obscure the Azure SDK Review issues. 

## Proposed solution
When the scheduling tool creates an issue for an upcoming Azure SDK Review it should add a label to the issue. This way architects can filter the issue list for issues tagged with the label. 

### Suggestion for label
The Azure/azure-sdk repo currently has a `SDKArchboard ReviewRequested` label which we could adopt and add to the Azure/azure-sdk-pr repo. 
IMO the ideal label would be `Azure SDK Review` to match the type of meeting in the scheduling tool.

**Comment by maririos** [comment]
We can totally do this. We already have this functionality implemented in the API Review meetings. For example: https://github.com/Azure/azure-rest-api-specs/issues/31706

I like the `Azure SDK Review` label too. If you are good with that we can implement it

**Comment by maririos** [comment]
In all honesty, we haven't touched this code in a while, but because I know we already support it, it shouldn't take too long to figure it out :)

**Comment by maririos** [comment]
This is from our test repo: https://github.com/azure-sdk/TestingForEngagementExperience-pr/issues/299

What do you think?

**Comment by ronniegeraghty** [comment]
> This is from our test repo: https://github.com/azure-sdk/TestingForEngagementExperience-pr/issues/299
> 
> What do you think?

Looks like I don't have permission to view that repo.

**Comment by maririos** [comment]
> > This is from our test repo: [azure-sdk/TestingForEngagementExperience-pr#299](https://github.com/azure-sdk/TestingForEngagementExperience-pr/issues/299)
> > What do you think?
> 
> Looks like I don't have permission to view that repo.

While I look at permissions:
![Image](https://github.com/user-attachments/assets/f718b9ee-5c3f-4725-8970-f9b2aec4d99b)

**Comment by ronniegeraghty** [comment]
Looks great!

**Comment by maririos** [comment]
Deployed
