### ISSUE TITLE
Add support for C++ to the Apiview

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-tools#945]
Currently, we support C#, Java, C, Python, JS/TS. It would be great if we can add C++ support as the azure-sdk-for-cpp is ramping up.

https://github.com/Azure/azure-sdk-for-cpp

![image](https://user-images.githubusercontent.com/6527137/91916483-1ae71480-ec72-11ea-9385-0102e45907ab.png)

cc @pakrym

**Comment by pakrym** [comment]
I think C processor can be extended to do C++, it might be hard considering how many features C++ has though.

**Comment by ahsonkhan** [comment]
@praveenkuttappan, @kurtzeborn - the C++ Core and Storage teams would really benefit from this in preparation for the upcoming architecture board review and GA release.

**Comment by praveenkuttappan** [comment]
I will have a look at this and check how much effort is required in supporting C++. I am not sure if this is feasible before October GA since I need to finish few other changes in EngSys side also. I will check if we can add support quickly and update you.

**Comment by ahsonkhan** [comment]
Fixed in https://github.com/Azure/azure-sdk-tools/pull/1098
