### ISSUE TITLE
Proxy can auto-shutdown after X minutes

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#9467]
@heaths is working away at integrating the test-proxy with the azure-sdk-for-rust repo. As part of this work, we're discovering new limitations for how the proxy is used. Specifically, the proxy has no way to automatically shut itself down. This is especially meaningful in `rust`, because there _is no_ attachment point for 

> after all tests are finished do X

So there is no way to shut off the auto-started test-proxy process.

This issue covers adding a new parameter to the `start` verb:

- `--auto-shutdown X`

Where X is the number of minutes since last handled request, after which the proxy will auto-shutoff.

**Comment by heaths** [comment]
Will that override the default number of minutes, or it only shuts down if you specify that? Any reason not to always auto-shutdown and free up system resources if, say, a test harness completely crashes?
