### ISSUE TITLE
[MONITOR-SPEC-PR]tspconfig does not configure packagename

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9481]
**Description:**
packageName is invalid and must start with `arm`.
**Additional context:**
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4386901&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=175

**Comment by wanlwanl** [comment]
user error.

**Comment by wanlwanl** [comment]
@jianingwang123 you can ask customer to update the tspconfig to the corrent one.
