### ISSUE TITLE
[MONITOR-SPEC-PR] Failed to generate Js, .Net SDK

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9484]
**Additional context:**
https://github.com/Azure/azure-rest-api-specs/pull/31434

**Comment by wanlwanl** [comment]
Resolved

**Comment by wanlwanl** [comment]
The sdk has costom code, service team should be responsible for it. 
@jianingwang123 as you can see, they have `https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/ai/Azure.AI.Projects/src/Custom` custom code.

**Comment by jianingwang123** [comment]
This problem is because author modified the `package-dir` but did not change `generateMetadata` to true, resulting in no `package.json` being generated under the new path.
