### ISSUE TITLE
[MONITOR-SPEC-PR] Net: sdk isn't existed in code repo

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9486]
**Additional context:**
https://github.com/Azure/azure-rest-api-specs/pull/31419

**Comment by wanlwanl** [comment]
no autorest.md: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4304173&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=203

**Comment by wanlwanl** [comment]
management-plane scaffolding only typespec.
Has no decision if this is green field or brown field. 
Please correct me if I'm wrong. @josefree

**Comment by wanlwanl** [comment]
Tracked in https://github.com/Azure/azure-sdk-for-net/issues/46862

**Comment by wanlwanl** [comment]
close it due to dup to https://github.com/Azure/azure-sdk-for-net/issues/46862
