### ISSUE TITLE
[MONITOR-SPEC-PR] Could not read file

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9513]
**Description:**
Could not read file.

**Additional context:**
https://github.com/Azure/azure-rest-api-specs/pull/31791/checks?check_run_id=34015374376

Go :
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4390312&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=223

Java:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4390312&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=234

Js:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4390312&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=202

.Net:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4390312&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=218

Python:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4390312&view=logs&j=b7f68bce-9df8-5468-1c9f-74766cfc9a39&t=25fc8ae6-51ed-58e2-b772-f4d054412fe3&l=857

**Comment by wanlwanl** [comment]
@jianingwang123  
error: `05:12:37.457 cmdout 	[automation_generate.sh] error   |   Error: Could not read 'file:///mnt/vss/_work/1/s/azure-rest-api-specs/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01/artifacts.json'.
` https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4390312&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=200
there's no specific file in the pr: https://github.com/Azure/azure-rest-api-specs/tree/7b0a9941dcaf759876551377a0eaa66d3ebe409b/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01
so it's a user error
