### ISSUE TITLE
[MONITOR-SPEC-PR] PreCheck/DuplicateSchema | Duplicate Schema named 'Resource'

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9516]
section1:
**Description:**
AutoRest found a duplicate pattern named 'Resource' while checking for duplicate patterns. (.Net and go)

**Additional context:**
link1: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4400779&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=321
link2: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4400779&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=346
link3: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4395188&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=467
link4: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4399246&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=473
link5: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4403099&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=276

section2:
**Description:**
PreCheck/DuplicateSchema | Duplicate Schema named 'ManagedServiceIdentity'.
**Additional context:**
link: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4421863&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=230

**Comment by wanlwanl** [comment]
@raych1 could you troubleshoot what is duplicated?
What's the number mentioned here? Looks like they are not line number `properties.id.$ref: "#/components/schemas/schemas:182" => "#/components/schemas/schemas:557"`
```
[Go] error   | PreCheck/DuplicateSchema | Duplicate Schema named 'Resource' (8 differences):
12:33:14.984 cmdout 	[Go]   - properties.id.$ref: "#/components/schemas/schemas:182" => "#/components/schemas/schemas:557"
12:33:14.984 cmdout 	[Go]   - properties.id.description: "Fully qualified identifier of the key vault resource." => "Fully qualified resource ID for the resource. E.g. \"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}\""
12:33:14.985 cmdout 	[Go]   - properties.name.description: "Name of the key vault resource." => "The name of the resource"
12:33:14.985 cmdout 	[Go]   - properties.type.description: "Resource type of the key vault resource." => "The type of the resource. E.g. \"Microsoft.Compute/virtualMachines\" or \"Microsoft.Storage/storageAccounts\""
12:33:14.985 cmdout 	[Go]   - properties.location: {"$ref":"#/components/schemas/schemas:185","description":"Azure location of the key vault resource.","readOnly":true} => <none>
12:33:14.985 cmdout 	[Go]   - properties.tags: {"$ref":"#/components/schemas/schemas:186","description":"Tags assigned to the key vault resource.","readOnly":true} => <none>
12:33:14.985 cmdout 	[Go]   - properties.systemData: <none> => {"readOnly":true,"description":"Azure Resource Manager metadata containing createdBy and modifiedBy information.","$ref":"#/components/schemas/schemas:626"}
12:33:14.985 cmdout 	[Go]   - title: <none> => "Resource"; This error can be *temporarily* avoided by using the 'modelerfour.lenient-model-deduplication' setting.  NOTE: This setting will be removed in a future version of @autorest/modelerfour; schemas should be updated to fix this issue sooner than that.
12:33:14.985 cmdout 	[Go] fatal   | Error: 1 errors occured -- cannot continue.
12:33:14.985 cmdout 	[Go] fatal   | Process() cancelled due to failure 

```

**Comment by raych1** [comment]
It needs the respective language team to investigate the details.

**Comment by wanlwanl** [comment]
@tadelesh could you guide customer how to resolve it?

**Comment by tadelesh** [comment]
added config to `readme.go.md`, should resolve the problem

**Comment by wanlwanl** [comment]
Thanks

**Comment by wanlwanl** [comment]
@jianingwang123 please note it and then you can close it
