### ISSUE TITLE
[MONITOR-SPEC-PR] Unknown decorator

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9521]
**Description:**
/mnt/vss/_work/1/s/azure-sdk-for-js/sdk/deviceregistry/arm-deviceregistry/TempTypeSpecFiles/DeviceRegistry.Management/client.tsp:6:3 - error invalid-ref: Unknown decorator @clientNamespace

**Additional context:**
link1:
https://github.com/Azure/azure-rest-api-specs/pull/31805/checks?check_run_id=34167982225
link2:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4397754&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=213

**Comment by wanlwanl** [comment]
@jianingwang123 if the error is for `tsp` file, it's user error, you don't need to open an issue for that in the future

**Comment by jianingwang123** [comment]
This issue occurred because the `azure-sdk-for-js` repository had not updated the tcgc dependency at that time. This problem should no longer exist now.
