### ISSUE TITLE
Extend code-owners resolution to allow teams

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-sdk-tools#954]
@chidozieononiwu was adding the following change: 

![image](https://user-images.githubusercontent.com/45376673/92159940-12fab200-ede3-11ea-8d74-dcf8b4f20e17.png)

Currently we do not pass these discovered owners into the "teams" argument of the `Tag PR` step. They are assumed to be real users currently. 

We need to update `eng/common/scripts/get-codeowners.ps1` to 

1. Validate each retrieved item, determine if it's a user or a team
2. Set the `GHTeamReviewersVariable` from within the script, just like it currently does for `GHReviewersVariable`

**Comment by chidozieononiwu** [comment]
@weshaggard points out that [tagging with teams will not work in other orgs](https://github.com/Azure/azure-sdk-tools/pull/981#discussion_r486643958)

**Comment by weshaggard** [comment]
Even though teams won't work in other orgs we can still use it to filter out users from teams. We should however try avoid failures on teams just like we do for users in other orgs.

**Comment by chidozieononiwu** [comment]
Fixed
