### ISSUE TITLE
[MONITOR-SPEC-PR] pathspec 'CommitId' did not match any file(s) known to git

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9544]
**Description:**
GitError : error : pathspec 'CommitId' did not match any file(s) known to git [/mnt/vss/_work/1/s/azure-sdk-for-net/sdk/migrate/Azure.ResourceManager.Migrate/src/Azure.ResourceManager.Migrate.csproj]

**Additional context:**
link1: https://github.com/Azure/azure-rest-api-specs/pull/31890/checks?check_run_id=34429863535
link2: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4411997&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=513

**Comment by wanlwanl** [comment]
dup to https://github.com/Azure/azure-sdk-tools/issues/9486
