### ISSUE TITLE
[MONITOR-SPEC-PR] InvalidRef

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9550]
Section1
**Description:**
InvalidRef | Ref '#/definitions/AzureTrafficCollectorByCircuitListResult' is not referencing a valid location.

**Additional context:**
https://github.com/Azure/azure-rest-api-specs/pull/31886/files#diff-4ea6e949f9857fb02c7281a689deb341b5bd6fe226666bb42c4107b2f52b5f29R561

go:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4410700&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=297

Java:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4410700&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=372

Js:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4410700&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=283

Net:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4410700&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=291

Python:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4410700&view=logs&j=b7f68bce-9df8-5468-1c9f-74766cfc9a39&t=25fc8ae6-51ed-58e2-b772-f4d054412fe3&l=1011

Section2
**Description:**
error   | InvalidRef | Ref '#/definitions/Certificate' is not referencing a valid location.

**Additional context:**
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4417490&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=777

Section3
**Description:**
InvalidRef | Ref '#/definitions/RetrieveBootDiagnosticsDataResult' is not referencing a valid location.

**Additional context:**
.net:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4418123&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=265
Java:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4418123&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=307\
Js:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4418123&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=257
Go:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4418123&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=271

**Comment by wanlwanl** [comment]
@jianingwang123 : 
user error, you can ignore this kind of issues in the future, when it's swagger (openapi2) error: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4418123&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=266

You can learn OpenAPI2 basics
