### ISSUE TITLE
[MONITOR-SPEC-PR] error ambiguous-symbol

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9554]
**Description:**
error ambiguous-symbol: "nextLink" is an ambiguous name between TypeSpec.nextLink, Azure.Core.nextLink. Try using fully qualified name instead: TypeSpec.nextLink, Azure.Core.nextLink

**Additional context:**
PR1:
Go:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4403502&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=303
Java:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4403502&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=224
Js:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4403502&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=240
Net:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4403502&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=237
Python:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4403502&view=logs&j=b7f68bce-9df8-5468-1c9f-74766cfc9a39&t=25fc8ae6-51ed-58e2-b772-f4d054412fe3&l=851

PR2:
Java:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4405085&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=195
Js:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4405085&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=211
.Net:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4405085&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=182
Python:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4405085&view=logs&j=b7f68bce-9df8-5468-1c9f-74766cfc9a39&t=25fc8ae6-51ed-58e2-b772-f4d054412fe3&l=822

**Comment by wanlwanl** [comment]
dup to https://github.com/microsoft/typespec/issues/5048

**Comment by MaryGao** [comment]
@wanlwanl I think this issue should be resolved once the emitter is adopted to the latest(December) compiler version(https://github.com/Azure/azure-rest-api-specs/commit/7e22a66617633d162735fe65388c2852127b4aac). I tried to re-run but it seems the original pr is merged to main. So it returned directly: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4405085&view=results.

**Comment by wanlwanl** [comment]
@MaryGao Thanks for the comfirmation
