### ISSUE TITLE
[MONITOR-SPEC-PR] Syntax error Encountered

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9562]
**Description:**
error   | JsonSpec/SyntaxError | Syntax error Encountered: Unexpected token { in JSON

**Additional context:**
Go:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4407177&view=logs&j=0303ead4-2e3b-557b-303e-fe8735d4d18f&t=b29b24f0-8be9-5e66-edce-54fd3565c09c&l=313
Js:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4407177&view=logs&j=47092895-c7c8-567a-c7a6-8c88f3ec178e&t=d293a8e8-c6af-5091-cdf7-4c66482dd6f2&l=299
Java:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4407177&view=logs&j=a8a7a537-82b0-583c-7971-bac70b9822ca&t=37e3947b-3cfb-5d36-86ba-0e22bb7dbc33&l=324
.Net:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4407177&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=307

**Comment by wanlwanl** [comment]
@jianingwang123   this one can be ignored
