### ISSUE TITLE
[MONITOR-SPEC-PR] System.InvalidOperationException

### ISSUE THREAD

**Issue by jianingwang123** [Azure/azure-sdk-tools#9563]
**Description:**
System.InvalidOperationException: BMSBackupSummariesQueryObject has a property named "Type" which is not allowed.

**Additional context:**
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4415902&view=logs&j=03afb3bb-7296-55ad-aa07-ceee610c73b2&t=0f320c29-1c90-5304-d2d3-c58a6bb76437&l=304

**Comment by wanlwanl** [comment]
@jianingwang123  .net naming rules. you can ignore it
