### ISSUE TITLE
APIView - Support specifying language by language parser

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#963]
Currently library language is not saved in json file. Add the support to include language in JSON file so it can be used in the future to group reviews based on language. Similarly adding support for service name, package name etc will be helpful in grouping as well.

**Comment by praveenkuttappan** [comment]
Add new fields in Reviews table for following:
a.	Package name
b.	Package Version
c.	Language
d.	Locked  - This is to ensure only bot can add new revision

**Comment by JonathanGiles** [comment]
Java has a PR that adds this support here: https://github.com/Azure/azure-sdk-tools/pull/1171
