### ISSUE TITLE
Support grouping reviews based on a package name in APIView

### ISSUE THREAD

**Issue by praveenkuttappan** [Azure/azure-sdk-tools#964]
Jonathan from Java team has asked for a feature in APIView that will help reviewer to group/filter all reviews for a specific package to identify the reviews easily.

Snippet from email
`Longer term, the other feature I think would be interesting would be to have the ability to group together all reviews for a particular library. Imagine if we could easily see a page that shows all reviews created for azure-blob-storage, for example. It could form the basis of improved tooling that would allow service teams / v-teams to centralise their documentation, usage samples, etc into APIView itself…`

**Comment by chidozieononiwu** [comment]
Resolved in https://github.com/Azure/azure-sdk-tools/pull/2785
