### ISSUE TITLE
Add pipeline for Golang APIView generator

### ISSUE THREAD

**Issue by catalinaperalta** [Azure/azure-sdk-tools#967]
Please add pipeline that covers go build, go lint, go vet, go test for unit tests. 

Generator is in: /src/go

**Comment by praveenkuttappan** [comment]
Go parser is already included in APIView build and test pipeline. So we should add test for go parser and plug that in current pipeline. This will be more of a change in parser than pipeline side.

**Comment by RickWinter** [comment]
@praveenkuttappan What work is left on this issue?

**Comment by chlowell** [comment]
I assume the parser here is the tool that lives in `/src/go`--like any of our Go SDK modules, it has unit tests a pipeline can run with `go test`.

**Comment by RickWinter** [comment]
Adding @jhendrixMSFT as we were discussing this yesterday.  @praveenkuttappan is there documentation on how to add tests for the parsers?

**Comment by praveenkuttappan** [comment]
This was already completed in one of the changes to run Go API parser tests in APIView pipeline. We don't need a separate pipeline for GO parser. https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2743021&view=logs&j=e4eadbe2-ad2e-5c91-4f07-f425300dce36&t=28e4b713-8228-5db3-36e9-9acae333919b
