### ISSUE TITLE
Set cache-control header for storage blobs on 'versions' file

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-tools#976]
After publishing docs the 'versions' file from the cache is stale and this may cause docs to not refresh properly for customers. Setting no cache or a rather short cache expiry (e.g. `max-age=300, must-revalidate`) when uploading the `versions` file might fix this. 

Description of `CacheControl` property: https://social.technet.microsoft.com/wiki/contents/articles/25528.azure-blob-storage-and-effective-use-of-cache-control-property.aspx

**Comment by sima-zhu** [comment]
Setup a pipeline to run the storage azure powershell commands.
https://dev.azure.com/azure-sdk/playground/_build/results?buildId=558582&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=b3b67622-0f16-555e-6574-f031225f4b13

**Comment by sima-zhu** [comment]
Update the cache-control to `max-age=300, must-revalidate` for now.

**Comment by sima-zhu** [comment]
It's been updated and verified for all existing ones.

Need to figure out how to set cache-control headers for upcoming blobs.

**Comment by sima-zhu** [comment]
All changes merge into master. Close the issue. Feel free to reopen if anything unaddressed.
