### ISSUE TITLE
APIView page "jumps" after load

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-tools#983]
Because we dynamically hide lines after page loaded, we might want to generate them hidden on the server-side.

https://apiview.dev/Assemblies/Review/b6ca1e24411349658b47a22abc87bbaa

and especially

https://apiview.dev/Assemblies/Review/b6ca1e24411349658b47a22abc87bbaa?diffRevisionId=46cd6f52c0004f2ba24760bd76d65db3

@praveenkuttappan

**Comment by praveenkuttappan** [comment]
I will check and submit a PR soon.

**Comment by pakrym** [comment]
Toggling is also very slow on https://apiview.dev/Assemblies/Review/3c788060d3ef44a5b629653545710cc6

**Comment by JonathanGiles** [comment]
Yes, I noticed toggling docs visible / hidden is very slow. Hopefully a faster approach can be found!

**Comment by praveenkuttappan** [comment]
I have made few fixes to improve this and it’s yet to deploy. Will make few more changes to improve it further.

**Comment by praveenkuttappan** [comment]
These changes to fix page jump and some perf improvement in showing documentation is deployed to production instance now.
